### ISSUE TITLE
1337x max search results

### ISSUE THREAD

**Issue by mapleleafs89** [Jackett/Jackett#10007]
# Environment: Docker

**OS**: CentOS

### Description

Searching 1337x indexer in jacket does not return all results.

Example: 
South Park S23

Results:
Jackett (1337x): 60 results
1337x (direct): ~140 results

This is an issue for me because when doing season searches, individual episodes are missed because they are not in the result set. The 60 results will primarily be filled with the latest torrents for that season, and the older episodes are excluded beyond the 60th result. This affects programs like Sonarr because a season search may only return a few episodes of the total season, and thus the older episodes in that season are not found when doing a historical season search.

I don't know if this is a configuration issue with jackett, a limitation of the 1337x api that jackett depends on, or perhaps just an issue for myself. Maybe there is a way to increase this limit that I am not aware of :) Thanks in advance!

**Comment by garfield69** [comment]
the 1337x web site by default provides 20 results per page.
when you do your search on the web site direct, do you get 140 results in one page?

there does not appear to be an option to ask it to provide more results per page.

the Jackett 1337x indexer does three requests to fetch pages 1,2 and 3 in order to at least provide 60 results

But we are not going to add more page fetches as this will most likely pass a DDoS threshold that could flag your Jackett session as a DDoS bot and see your IP blocked.

**Comment by mapleleafs89** [comment]
Gotcha, yes you are correct it is 140 across & pages. I thought they might have provided an API to get all results in one shot. I guess I will need to try and find another indexer to fix this limitation of the other, else in some cases Sonarr won't be able to fetch episodes when doing a season search (e.g. show added, sonar will do a season search like above for S23, unless a season pack is returned, it expects the individual episodes to be returned as well like S23E01, S23E02, and so on, and since the first 60 results only show the most recent few episodes, the earlier episodes are just missed). Thanks for the reply!
