### ISSUE TITLE
[enhancement] improve the Windows Tray start-up code

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#10094]
currently the Windows system Tray start-up code looks like this
https://github.com/Jackett/Jackett/blob/0ad911f97ae322d7c25674e564725cd85ed8fbef/src/Jackett.Tray/Main.cs#L95-L113

we should be able to improve this to allow for a more dynamic start-up that starts the tray as soon as practical
a suggestion as a starting place is the following script provided by @ilike2burnthing 

```
@echo off
start JackettUpdater.exe
timeout /t 30 > NUL # if we wanted to keep the 30s delay
:_loop
tasklist /FI "IMAGENAME eq JackettUpdater.exe" | findstr = > NUL || goto _cleanup
timeout /t 5 > NUL
goto _loop
:_cleanup
C:\ProgramData\Jackett\JackettTray.exe
```

volunteer needed to implement this, or something similar, that allows the tray to be started without interfering with the updater (see issue #10068)

**Comment by ilike2burnthing** [comment]
I've tried looking for a similar way to monitor a running program just using a single command, but no luck (`start /w` won't work, as we're not running JackettUpdater from cmd). So, I've got a suggestion for a different approach.

---
Change the Arguments line to:
`Arguments = $"/c timeout 5 > NUL & \"{FolderPath}\check.bat"",`

Where `FolderPath` (that's probably not right, I couldn't find what it was) is the installation directory, and `check.bat` (or whatever name we want) is:
```
@echo off
:_loop
tasklist /FI "IMAGENAME eq JackettUpdater.exe" | findstr = > NUL || goto _cleanup
timeout /t 5 > NUL
goto _loop
:_cleanup
start JackettTray.exe --UpdatedVersion yes
```

---
`FolderPath` is needed because we can't just assume C:\ProgramData\Jackett\, and `check.bat` has to be run from there because we want to launch JackettTray.exe from the same folder as it.

I've tested running the JackettUpdater with the ` --norestart` argument, from C:\Windows\Temp, while check.bat is running in C:\ProgramData\Jackett, and check.bat is updated without issue, and then launches Jackett tray with the update notification after the update completes.

What do you think? I could put together a WIP PR to see how it plays out.

@ngosang I know you don't develop for Windows, but does the formatting of `Argument:` look ok? No other obvious issues?

**Comment by garfield69** [comment]
Using windows bat scripts is fine, as, for instance, the linux version of Jackett has several bash scripts to start services and stuff.

However `check.bat` as a name sucks ;-D
IMO something like: `systemTrayStartup.bat` or similar would be better.

In you example argument line 
`Arguments = $"/c timeout 5 > NUL & \"{FolderPath}\check.bat"",` 
I think there is a missing escape for the last quote, should probably be
`Arguments = $"/c timeout 5 > NUL & \"{ScriptPath}\systemTrayStartup.bat\"",`

The Jackett/src/Jackett.Tray/Main.cs code already has examples of setting paths
I think something like
```C#
        public string ScriptPath => Path.Combine(Path.GetDirectoryName(Process.GetCurrentProcess().MainModule.FileName), "systemTrayStartup.bat");
```
should work.

All the above need a C# review, I'm spit balling and dont know for sure it any of it works.

**Comment by ilike2burnthing** [comment]
> I'm spit balling and dont know for sure if any of it works.

Same lol

> However `check.bat` as a name sucks ;-D

Harsh! OK, yea it does ;P

Thanks, that looks good!

**Comment by ngosang** [comment]
External scripts are a bad practice. I have a better idea.

**Comment by garfield69** [comment]
confused.
even with the jackett service stopped and the tray closed (using the tray stop-service and close-tray right-click menu commands), the script starts the tray straight away.
a manual ping shows the port is responding to the ping, I presume it has not been released by the system?
![image](https://user-images.githubusercontent.com/6933240/98428174-1a9d4680-2105-11eb-8844-aa42db31576a.png)

is my test of the script in this manner not valid?

**Comment by garfield69** [comment]
Oh, I see. my bad. did not understand the script first time round.
Since I don't have the JackettUpdater.exe it launches the tray. Duh!
