### ISSUE TITLE
Torznab error detected on a many Indexers (EZTV, Zooqle, Limetorrents, Torrentz2, MagnetDL, tvchaosuk)

### ISSUE THREAD

**Issue by rrrevin** [Jackett/Jackett#10120]
### Environment
**OS**: Ubuntu 20
**.Net Runtime**:  Mono JIT compiler version 6.12.0.90
**Jackett Version**: 0.16.2076.0
**Last Working Jackett Version**: 0.16.1922.0
**Are you using a proxy or VPN?** no

### Description
Some Indexers are showing errors with Sonarr (v2.0.0.5344).  Sonarr has not been updated in months, but Jackett is (somewhat) regularly. After the upgrade yesterday to 2076, I'm now seeing erros with a few Indexers. When running a connect/test in Sonarr, Sonarr displays the following error. It is the same for the following indexers : EZTV, Zooqle, Limetorrents, Torrentz2, MagnetDL, tvchaosuk; just the name of the indexer changes.

This does not happen for all indexers that I use in Jackett, just the ones that display this new error.
The following work with no issue: 1337x, ETTV, Torrenting

### Logged Error Messages
magnetdl
```
20-11-6 08:31:34.1|Debug|Torznab|Downloading Feed http://jackett:49117/api/v2.0/indexers/magnetdl/results/torznab/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100
20-11-6 08:31:34.2|Warn|Torznab|Unable to connect to indexer

[v2.0.0.5344] NzbDrone.Core.Indexers.Torznab.TorznabException: Torznab error detected: magnetdl does not support the requested query. Please check the capabilities (t=caps) and make sure the search mode and categories are supported.
  at NzbDrone.Core.Indexers.Torznab.TorznabRssParser.PreProcess (NzbDrone.Core.Indexers.IndexerResponse indexerResponse) [0x000ca] in <4d3cc4e5f7ed4ed2814d83bdaf94809e>:0 
  at NzbDrone.Core.Indexers.RssParser.ParseResponse (NzbDrone.Core.Indexers.IndexerResponse indexerResponse) [0x0000d] in <4d3cc4e5f7ed4ed2814d83bdaf94809e>:0 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].FetchPage (NzbDrone.Core.Indexers.IndexerRequest request, NzbDrone.Core.Indexers.IParseIndexerResponse parser) [0x00050] in <4d3cc4e5f7ed4ed2814d83bdaf94809e>:0 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].TestConnection () [0x00024] in <4d3cc4e5f7ed4ed2814d83bdaf94809e>:0 

20-11-6 08:31:34.2|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to indexer, check the log for more details
20-11-6 08:31:34.2|Debug|Api|[POST] /api/indexer/test: 400.BadRequest (255 ms)
```
eztv
```
20-11-6 08:33:40.3|Debug|Torznab|Downloading Feed http://jackett:49117/api/v2.0/indexers/eztv/results/torznab/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100
20-11-6 08:33:40.3|Warn|Torznab|Unable to connect to indexer

[v2.0.0.5344] NzbDrone.Core.Indexers.Torznab.TorznabException: Torznab error detected: eztv does not support the requested query. Please check the capabilities (t=caps) and make sure the search mode and categories are supported.
  at NzbDrone.Core.Indexers.Torznab.TorznabRssParser.PreProcess (NzbDrone.Core.Indexers.IndexerResponse indexerResponse) [0x000ca] in <4d3cc4e5f7ed4ed2814d83bdaf94809e>:0 
  at NzbDrone.Core.Indexers.RssParser.ParseResponse (NzbDrone.Core.Indexers.IndexerResponse indexerResponse) [0x0000d] in <4d3cc4e5f7ed4ed2814d83bdaf94809e>:0 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].FetchPage (NzbDrone.Core.Indexers.IndexerRequest request, NzbDrone.Core.Indexers.IParseIndexerResponse parser) [0x00050] in <4d3cc4e5f7ed4ed2814d83bdaf94809e>:0 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].TestConnection () [0x00024] in <4d3cc4e5f7ed4ed2814d83bdaf94809e>:0 

20-11-6 08:33:40.3|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to indexer, check the log for more details
20-11-6 08:33:40.3|Debug|Api|[POST] /api/indexer/test: 400.BadRequest (247 ms)
```
Limetorrents
```
20-11-6 08:35:01.6|Debug|Torznab|Downloading Feed http://jackett:49117/api/v2.0/indexers/limetorrents/results/torznab/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100
20-11-6 08:35:01.6|Warn|Torznab|Unable to connect to indexer

[v2.0.0.5344] NzbDrone.Core.Indexers.Torznab.TorznabException: Torznab error detected: limetorrents does not support the requested query. Please check the capabilities (t=caps) and make sure the search mode and categories are supported.
  at NzbDrone.Core.Indexers.Torznab.TorznabRssParser.PreProcess (NzbDrone.Core.Indexers.IndexerResponse indexerResponse) [0x000ca] in <4d3cc4e5f7ed4ed2814d83bdaf94809e>:0 
  at NzbDrone.Core.Indexers.RssParser.ParseResponse (NzbDrone.Core.Indexers.IndexerResponse indexerResponse) [0x0000d] in <4d3cc4e5f7ed4ed2814d83bdaf94809e>:0 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].FetchPage (NzbDrone.Core.Indexers.IndexerRequest request, NzbDrone.Core.Indexers.IParseIndexerResponse parser) [0x00050] in <4d3cc4e5f7ed4ed2814d83bdaf94809e>:0 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].TestConnection () [0x00024] in <4d3cc4e5f7ed4ed2814d83bdaf94809e>:0 

20-11-6 08:35:01.6|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to indexer, check the log for more details
20-11-6 08:35:01.6|Debug|Api|[POST] /api/indexer/test: 400.BadRequest (254 ms)
```
etc..

**Comment by ilike2burnthing** [comment]
Check the categories you have set in Sonarr for each of those indexers match those shown in Jackett (these may have recently changed).

**Comment by LoicAuge** [comment]
Same issue here with differents indexers.
What can we do ? In Sonarr, the default categories are 5030 and 5040 and this don't work. When I use 5000, I have a return on the URL but Sonarr says " Query successful, but no results were returned from your indexer. This may be an issue with the indexer or your indexer category settings."

**Comment by ilike2burnthing** [comment]
Which indexers?

**Comment by LoicAuge** [comment]
oxtorrent, gktorrent and torrent9clone

**Comment by LoicAuge** [comment]
No issue with Radarr on categorie 5000

**Comment by garfield69** [comment]
for Sonarr, edit your Sonarr indexer and set the following cats
oxtorrent: TV(5000)
gktorrent: TV(5000)
torrent9clone: TV(5000) and Movies(145469)
you need a movie cat for T9clone because during testing the site returns only movies.
tested Sonarr searching for Mandalorian S02E01 OK for all three.

**Comment by LoicAuge** [comment]
I can't use the indexer on 5000 categorie because Sonarr show an error : "Query successful, but no results were returned from your indexer. This may be an issue with the indexer or your indexer category settings." 
I think I have to see that with the guys of Sonarr right ?

**Comment by garfield69** [comment]
reopened, waiting of @rrrevin to report.

**Comment by rrrevin** [comment]
Will test changing categories to 5000... stand by..

**Comment by ilike2burnthing** [comment]
5030 and 5040 are default cats given by Sonarr for all indexers, as they generally work, but you should set the cats to what what Jackett actually specifies. In most cases 5000 will be sufficient, as it includes all subcats, but you may wish to be more specific.

Can you check LimeTorrents is working in Jackett?

**Comment by garfield69** [comment]
Limetorrent's keywordless search (TEST) returns Other categories only, so to set up in Sonarr you need to add 8000(Other) to the categories list in that indexer.

**Comment by rrrevin** [comment]
Again.. This used to work in jackett build 16.1922. What changed?

**Comment by rrrevin** [comment]
I found where this change was PREDICTED to cause issues..[ https://github.com/Jackett/Jackett/pull/10006#issuecomment-718047609]( https://github.com/Jackett/Jackett/pull/10006#issuecomment-718047609).. specifically near the bottom of that comment :
_It's not necessarily wrong to have subcategories that don't contain any releases, in fact it could be useful in some cases. It's like "Yes I recognize this category". In fact, by default Sonarr only selects 5030 and 5040._

Right there.. whatever change was put in place, is breaking loads of Sonarr installs. Perhaps, until Sonarr gets their stuff resolved, Jackett can work around it?

**Comment by ilike2burnthing** [comment]
Changes to Sonarr revealed issues with how Jackett organised categories. Fixes and further improvements were made. You can find the main ones here:
https://github.com/Jackett/Jackett/pull/9986
https://github.com/Jackett/Jackett/pull/10005
https://github.com/Jackett/Jackett/pull/10006
https://github.com/Jackett/Jackett/pull/10031
https://github.com/Jackett/Jackett/pull/10060
and the rest here:
https://github.com/Jackett/Jackett/search?q=categorymappings&type=commits

The change made most likely to have affected you, and the one you mention above, is that sub-cats no longer show everything from its parent cat. This is a useful change, as you can now select, for example, TV HD, search for an episode, and only get HD results (assuming the site categorises releases correctly).

As for using the default categories provided by Sonarr, this was never a good thing to be solely relied on, they should always have been set to what was specified in Jackett. In most cases now, 5000 will work as a catch all (unless the indexer only uses `Other`).

Where the category `Other` had to be used to obtain results, the changes made by Sonarr broke that anyway, so we would have always had to fix it.

Between here, Sonarr's repo, Radarr's repo, and Sonarr's forum, I've seen maybe 5 people with this issue, and telling them to check their cats has resolved it each time.

**Comment by Taloth** [comment]
@ilike2burnthing Problem with the edge case is actually that it's affecting Sonarr v2 a bit more heavily than v3. 
I didn't realise that until now. In v2 there's no dropdown so the user has no idea what the error is about and how to fix it. (Heck, ppl even ask support when they have v3 despite the message mentioning categories)

Second problem is when adding the indexer to sonarr, it probably throws a random validation error with no visible details. So the user has to go to the log files to see actual cause. That's on us, I checked and TorznabException message isn't actually shown on the UI while some other exception types are. (í'll try get that fixed in v3)
Again a bigger problem in v2 since it has no dropdown.

I see two approaches:
- Update Jackett to return a clearer error. Perhaps something along the lines "categories x don't exist, please change to y" rather than "doesn't support the requested query"
- Or, transparently convert 5030,5040 to 5000 _if_ only 5000 exists. That'd mean that the dropdown in v3 still shows only 5000. But 5030,5040 would still work as before on v2/v3.

For Sonarr v3 I should plan these changes:
- Update it to actually show that error on the ui during validation.
- While adding a new indexer, automatically convert 5030,5040 to 5000.

I've seen maybe a dozen reports about it on discord and other support channels. For v3 I was like, yes just have people fix the cats, but for v2...

**Comment by ilike2burnthing** [comment]
Would it be worth changing Sonarr's default cats to just 5000? This won't affect users' existing indexers, but at least hopefully stop more getting the issue going forward.

Admittedly I'm a layman here, but I'd prefer changing the error, if only to get users to pay attention to what they're setting, rather than allowing wrong cats to be accepted and fixed in a black box. That could end up leading to more confusion about why the can set 5030/40 when Jackett doesn't specify it, but can't set other non-existent cats.

@ngosang @garfield69 any thoughts?

**Comment by Taloth** [comment]
We intentionally have the default at 5030,5040 it means that the pages contain more relevant content. In v3 the 'default' is less important because the user gets to select it visually anyway.
The reason I list option two is for backward compat with v2 and existing users, Sonarr v3 should take care to warn the user to use 5000 instead of 5030,5040. Warn, but not fail. So in my opinion it's definitely on the table.

**Comment by ngosang** [comment]
About the "unsupported category" error, the change was intentional. The old code was not filtering categories well and was not informing the user that the settings were incorrect. I'm going to open a PR to include more information about the error.

About categories 5030,5040 a couple of considerations. Before the recent changes in Jackett, the 5000 category did not work properly, now it should work better. We have different categories for UHD content: `5045, "TV/UHD"` and `2045, "Movies/UHD"`. These categories are not enabled in Sonarr/Radarr by default. Clarification: 5045 is not subcategory of 5040, they are at the same level.

In Sonarr/Radarr v3 IMHO we can let the category field empty and force the user to choose at least 1 from the tree. Or set 5000 by default only if it's available in the tree. Show the error returned by Jackett to the user.

In Sonarr/Radarr v2, well, I prefer to not make exceptions in Jackett. In ideal world showing the Jackett error to the user will be enough. If it's not possible, the user can take a look at Jackett log.

**Comment by Taloth** [comment]
> About the "unsupported category" error, the change was intentional. The old code was not filtering categories well and was not informing the user that the settings were incorrect.

Strictly speaking, according to the specs an unknown category should be treated as an category with no releases in it. So `cat=123123` should actually just return an empty result. And `cat=5000,123123` should return just tv. and omitting the `cat` query param is all categories. But that's just the spec and I don't mind it throwing an error.
But if you just did that, then sonarr would say there aren't any releases during validation.

> These categories are not enabled in Sonarr/Radarr by default.

True, back when we determined the defaults there was no UHD. We could ad 5045 as default, I'm not sure but there's an argument there. I just don't want to use 5000 as default since I want to filter out Sports, Anime and Documentaries.
I'm thinking we actually could be a bit more intelligent about categories, like ignore UHD when none of the active release profiles actually have UHD enabled. But that's advanced and not really the subject of today.

> In Sonarr/Radarr v3 IMHO we can let the category field empty and force the user to choose at least 1 from the tree. Or set 5000 by default only if it's available in the tree. Show the error returned by Jackett to the user.
- Not empty, empty means not to search the indexer for regular shows (same as the anime categories).
- I was planning to set it to 5000 if only 5000 is available, or I might just tell the user to change it to 5000 as part of validation. Not sure how yet.
- I'm actually looking into getting the error on the ui right now.

For v3 adding new indexers isn't a problem, I can deal with that. For existing ones it's a 'sonarr v3 is beta, change your indexer settings'. 

I'm not planning to change v2 though for one cosmetic since v2 is in critical hotfixes only mode. (v3 will go release fairly soon, but we keep finding stuff that we want fixed prior to release)
The error jackett sends is logged in System->Logs, just not on the UI. My point here is that the error message Jackett sent is clarified.

**Comment by ngosang** [comment]
> Strictly speaking, according to the specs an unknown category should be treated as an category with no releases in it. So cat=123123 should actually just return an empty result. And cat=5000,123123 should return just tv.

I can do the change if requested, but as you said, they user will get 0 results without further explanations.

>  We could ad 5045 as default, I'm not sure but there's an argument there. I just don't want to use 5000 as default since I want to filter out Sports, Anime and Documentaries.

If you add 5045 as default most trackers will fail because it's only supported in few of them. You can try to set "5030", "5040" and "5045" if they are available in the tree. If none of them is available try to set "5000". if not available neither maybe "8000" ?

> The error Jackett sends is logged in System->Logs, just not on the UI. My point here is that the error message Jackett sent is clarified.

I'm working on it but it's a bit more complicated than I expected. The thing is Jackett is not logging that kind of errors neither. I understand why the users are lost and complaining.

**Comment by ngosang** [comment]
>Strictly speaking, according to the specs an unknown category should be treated as an category with no releases in it. So cat=123123 should actually just return an empty result. And cat=5000,123123 should return just tv.

>I can do the change if requested, but as you said, they user will get 0 results without further explanations.

Well, I'm changing my mind. The specs are clear and I think this is the only way to solve the issues in v2 => https://torznab.github.io/spec-1.3-draft/torznab/Specification-v1.3.html#cat-parameter

I want to hear @garfield69 @ilike2burnthing because this implies several changes in Jackett. Current behavior:
* Without cat parameters => Search in all categories
* `cat = all valid cats` => Search in those cats
* `cat = mixed valid and invalid cats` => Search in the valid cats
* `cat = all invalid cats` => Error

We can change the last two:
* `cat = mixed valid and invalid cats` => Search in the valid cats **and log a warning in Jackett with wrong categories**
* `cat = all invalid cats` => **Return 0 results and log a warning in Jackett with wrong categories (all of them)**

**Comment by Taloth** [comment]
~~I'm a bit torn on this whole thing. As I said, based on the specs you would simply ignore the cats but that would break v2 even more so it's a bad idea. On the other hand they are known categories, you just don't subcategorize releases so there's an argument to treat 5030 as 5000.~~

If I add 5045 as default, it'd be for v3, so we can deal with the cat being absent in the dropdown as part of validation. Or Jackett can treat it as empty. Same story, v3 isn't the issue. I can deal with setting it to 5000/8000 or guiding the user to do so.

> The thing is Jackett is not logging that kind of errors neither. I understand why the users are lost and complaining.

That explains part of it yes. :smile:

You're suggestion would lead to a warning in Jackett _and_ a warning in Sonarr due to empty results. That sounds like a good approach to me.

The `cat = mixed valid and invalid cats` logging a warn isn't strictly required, but it's a good approach, combined with v3 validation and we can push people to the right cats. For v2 ppl are without releases, which might lead to some support questions.
The `cat = all invalid cats` return 0 results, but maybe log an _error_ instead? It's going to be the only spot where the user is explained what's really going on.

Empty response leads to the following validation message in v3: 
![image](https://user-images.githubusercontent.com/6383890/98469305-f31aac80-21de-11eb-8b87-0d1176f063d9.png)

On rss sync there's no warning whatsoever. On Health Check neither. Which is somewhat concerning because if v3 isn't logging a warning on it, then v2 isn't either. And the user never knows somethings wrong.

**Comment by ngosang** [comment]
I'm not proud of the source code but I think it will work as described in the previous comments. Please, do some tests.
Jackett v0.16.2118

![image](https://user-images.githubusercontent.com/10577978/98486029-1d8a5b00-221b-11eb-8db8-62c4721331bd.png)

**Comment by ilike2burnthing** [comment]
Better late than never, but yes, I support all of this (I'm helpful like that).

I let Radarr and Sonarr run their RSS Syncs and actually discovered I'd mistyped 100000 as 10000 for one indexer at some point. Ran some tests specifying non-existent cats or a mix of existent and non-existent cats and got the relevant warnings and errors in Jackett's logs. Also tried impossible cats (e.g. 452592732545) and got the error for it.

Looks good!

Re: Radarr, you need to show advanced settings to change cats.

**Comment by rrrevin** [comment]
Excellent progress all! Thanks!
