### ISSUE TITLE
[Lostfilm] parse error

### ISSUE THREAD

**Issue by stasivanov** [Jackett/Jackett#10146]
### Environment

**Jackett Version**: latest

### Logged Error Messages

[error.txt](https://github.com/Jackett/Jackett/files/5506835/error.txt)

**Comment by ngosang** [comment]
@krin-san could you help us?

**Comment by garfield69** [comment]
@stasivanov  Reporting you are on the **latest** version is subjective to the time you posted, and we update Jackett daily so it's difficult to keep track of the specific version that you were on when you has this issue.
Please access your Dashboard and scroll to the bottom and report the version you are on, so there is no confusion later when we cross check update history.

Note: I am unable to replicate this issue while testing LostFilms today. I'm using 0.16.2118

**Comment by garfield69** [comment]
please report why you closed the ticket?

**Comment by stasivanov** [comment]
Sorry. Now it's working after I updated to latest version. But yesterday it just failed and wrote I'm on latest. And sorry for the thread format. Will do better next time

**Comment by garfield69** [comment]
No problem.
The next time you get a hit like this, turn on the **enhanced** logging in Jackett and repeat your test, to capture as much info as possible while the problem is hot. See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.
Its possible the new-releases page from the site is generating listing for torrents that are incomplete, causing the indexer to crash. But as the torrents details on the site get updated, the indexer starts working again.
It will be nice to see what was missing so we can try to bullet proof the indexer.
Thanks.
