### ISSUE TITLE
Ultradox new public tracker

### ISSUE THREAD

**Issue by SuberSeb** [Jackett/Jackett#10157]
Please add Ultradox http://m.ultradox.org/serial/

**Comment by garfield69** [comment]
Pure Russian language site with no English titles.
Site does not have single tv episodes, just season packs.

Only the latest page has what looks like a standard torrents/magnet list
The moment you want to search for something you end up with a poster grid that has nothing but a link to a page for each details page.
Because of the layout differences between the Latest page and the search page results, this site cannot be processed by yaml, will need an indexer written in C#

**Comment by ilike2burnthing** [comment]
ERR_NAME_NOT_RESOLVED
