### ISSUE TITLE
Jackett not finding episodes because of Case sensitive searches? 

### ISSUE THREAD

**Issue by KBlixt** [Jackett/Jackett#10268]
Hi. 

I'm usually getting my stuff through usenet. But I recently decided to add torrenting as a backup incase of unusual shows/movies that don't get added to usenet. I got it set up using the latest docker image. 

I recently added the latest season of the show Days of our Lives to my sonarr monitoring. And usenet coverage is spotty at best. Unfortunately there seems to be an issue with finding torrents for the show as well. 

Sonarr makes a search query like this "Days of our Lives : S56E24" and nothing is turning up. Doing this search manually on jackett confirms that there are indeed no torrents when searching with that query. 

However modifying the manual search to "Days of our Lives : S56e24" (changing the uppercase E to lowercase) does find correct episodes on both TPB as well as Torrentz2. What's even more confusing is that the name of these torrents uses an uppercase E and not a lower case e in their torrent names. 

This behavior is consistent across most Days or our Lives episodes. What am I missing here? Is there anything I can do about this? Is this an issue with sonarr or the torrent sources? I've tried to search for a similar issue but can't find any solution to my problem. 

Thanks!

**Comment by garfield69** [comment]
Torrentz2 and TPB do not find `days of our lives s56e24` 
because the torrents is actually named `Days Of Our Lives -​ S56 E24 [13963] -​ 2020-​10-​26`
Note the space between S56 and E24
IF on the Jackett dashboard you search torrentz2 or TPB for `days of our lives s56 e24` you will get a match.

FYI: `day of our lives` is a **daily** show.
You will have better matching of episodes on most indexers if you switch your Sonarr _days of our lives_ setting from the default **series type** = _Standard_ to **Daily**
Then you will find that the episode listings page for each season will fill out on Sonarr, and searches will succeed on TPB and TZ2 since the searches will start using the `yyyy MM dd` format rather than the `SxxExx` 

Also, torrentz2 has the DoOL series listed as movies, so remember to add the movies category to your Sonarr indexer definition or you will not get any matches for this title on TZ2.
