### ISSUE TITLE
[REQ] Torrent Arşivi , a Turkish Public site. https://torrentarsivi.com/

### ISSUE THREAD

**Issue by berat1397** [Jackett/Jackett#10286]
Turkish public mix content share torrent site.

Search engine and torrents working.

https://torrentarsivi.com

**Comment by garfield69** [comment]
Search result poster leads to a details page with one or more magnets, which means this indexer will need to be written in C# as it is unsuitable for processing with yaml.
Also, some details pages are missing magnets due to DRM take down so search results can lead to a download link failure.
And finally, cloudflare DDoS protection is in place, so as it stands a Jackett indexer will not work anyway.

**Comment by ilike2burnthing** [comment]
index page
