### ISSUE TITLE
[hachede] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by isnave** [Jackett/Jackett#10290]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
@RicardoVelaC  is the hachede indexer working for you?

**Comment by isnave** [comment]
Yes, i have account in hachede, and it was working fine until yesterday

 �

**Comment by garfield69** [comment]
None of the team have an account.
To have any chance to diagnose we are going to need a full **enhanced** log
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.

**Comment by JorTurFer** [comment]
Hi, 
I tried and the problem comes from here:
https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/CardigannIndexer.cs#L774

I found also that the hachede's cookie changed from the cookie that I have saved :(
My old cookie is like this:
_ga=GAxxxxxxxxxxxxx; **__cfduid=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx**; tsue_member=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; shoutboxChannelID=x; **_gid=GAxxxxxxxxxxxxxx**
And my new cookie is like this:
_ga=GAxxxxxxxxxxxxx; tsue_member=xxxxxxxxxxxxxxxxxxxxxxxxxxxxx; shoutboxChannelID=x

The strong values are missed in the new version.

After the cookie update, all works fine again. I suppose that the problem comes for an update in the tracker backend

**Comment by ngosang** [comment]
Tested, it's working fine. Just copy a new cookie from the web browser.
