### ISSUE TITLE
[Gay-Torrents.net] offline

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#10328]
https://www.gay-torrents.net/latest/ - be right back

**Comment by ilike2burnthing** [comment]
back up

**Comment by soumaisalan** [comment]
this is offline again, please fix

**Comment by garfield69** [comment]
@soumaisalan  the indexer is working for me. If it is not working for you then open a new ticket [here](https://github.com/Jackett/Jackett/issues/new?assignees=&labels=&projects=&template=bug_report.yml)

**Comment by soumaisalan** [comment]
This indexer does not work with Whisparr, only manually, because when Whisparr sends a search command to this indexer via torznab, it appends the information of what is being sent as {Site} + {Release Date}. However, gay-torrents by default does not display release dates on torrents, resulting in no search results in Whisparr. There should be an option to customize how searches are sent to this indexer, as it currently only works in Jackett when using manual search, rendering it completely useless in Whisparr.

**Comment by garfield69** [comment]
So we will change this ticket into an enhancement request and see it we can update the indexer to work with whisparr torznab requests.

**Comment by garfield69** [comment]
actually, we will open a new ticket, as this ticket is used for when the web site is offline. [edit] https://github.com/Jackett/Jackett/issues/14700

**Comment by obertscloud** [comment]
gay-torrents.net is redirecting to other websites  no one can access it

**Comment by garfield69** [comment]
https://www.gay-torrents.net/ 410 Gone

**Comment by obertscloud** [comment]
the behavior is back, i saw it come up but it was blank, now it redirects to other spam sites  maybe to back 12  - 24 hours backup someone must injected code to hijack the site and redirect ?  I dont know I only deal with wordpress sites

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://www.gay-torrents.net/ > 403 Forbidden

**Comment by garfield69** [comment]
online
