### ISSUE TITLE
Jackett migration

### ISSUE THREAD

**Issue by PrzemekSkw** [Jackett/Jackett#10326]
Hi, sorry for posting in issues but don't know where to. 
Is it possible to migrate jackett config from my Ubuntu laptop to my Dietpi server?

Regards,
Przemek

**Comment by garfield69** [comment]
Partially.
While you can copy the Jackett indexers folder (that has the indexer *.json config files), and the ServerConfig.json file (for the Jackett server settings, api key etc) across, there is another folder DataProtection that is required.
The DataProtection folder contains the encryption keys for the passwords used in the indexers *.json files for Private and Semi-private indexers.
However, here is the rub. 
The encryption keys are generated using system attributes, and whatever local encryption library methods used by the system. On a different platform, these keys will most likely not work to decrypt the passwords.
So you may end up having to use your Jackett Dashboard on the new system to edit each indexer config with a password, and update the password field anew in order to create an encrypted password stored locally that can be decrypted properly when Jackett goes to login to the web sites that the indexer accesses.
