### ISSUE TITLE
[magnetdl] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by bodoamat-git** [Jackett/Jackett#10337]
### Environment

**OS**: Windows 10

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**: 

**Jackett Version**: 0.16.2269.0

**Last Working Jackett Version**: 0.16.2269.0

**Are you using a proxy or VPN?** [no]

**Comment by garfield69** [comment]
The indexer works for me using any of the four site links available from the config.
https://www.magnetdl.com/
https://www.magnetdl.org/
https://magnetdl.unblockninja.com/
https://magnetdl.unblockit.app/
So the issue appears to be at your end.

Please provide a full **enhanced** log with the debug and HTML included and maybe we can figure out what is going on.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.
Thanks.

**Comment by jbalcorn** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/5624665/log.txt)
I am having the same problems, here's the debug log of the test using https://magnetdl.unblockit.app/

**Comment by garfield69** [comment]
@jbalcorn  the log shows that your jackett tried to use `2020` as a keyword for the TEST search.
This means that your version of Jackett is older than 0.16.2168 because the indexer was fixed beginning with this version, to stop using that search method.
Access your Jackett dashboard and scroll to the bottom. 
If your Jackett version is 0.16.2168  or older than upgrade because your Jackett is out of date.
If it's reporting a newer version then something is going wrong with your updater. In which case do a complete manual install by following which ever method is appropriate for your platform
https://github.com/Jackett/Jackett#installation-on-windows
https://github.com/Jackett/Jackett#install-on-linux-amdx64
https://github.com/Jackett/Jackett#install-on-linux-armv7-or-above
https://github.com/Jackett/Jackett#installation-on-linux-armv6-or-below
https://github.com/Jackett/Jackett#installation-on-macos
https://github.com/Jackett/Jackett#installation-using-docker

if on linux, then make sure you run the systemd install service step to replace the old script with the new one.

**Comment by bodoamat-git** [comment]
sorry my bad 

today work again

**Comment by jbalcorn** [comment]
Thanks, upgrading did the trick.
