### ISSUE TITLE
[BTF] All Files Sizes are wrong in Bytes 

### ISSUE THREAD

**Issue by Mitnick84** [Jackett/Jackett#10355]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.16.2256.0

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** no

### Description

The Search reflect the wrong filesizes it shows all in a bit Bytes 

For Example: 

The.​100.​S06E08.​German.​DL.​DUBBED.​1080p.​BluRay.​x264-​AIDA  jackett say it has 14 Bytes instead of 3,18 GB (3,414,355,744 Bytes)
--

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]
<img width="1522" alt="filesizewrong" src="https://user-images.githubusercontent.com/55686159/101058140-1beb5300-358d-11eb-8bd7-92687b865f5a.PNG">

**Comment by garfield69** [comment]
The indexer is working for me which suggests the issue is a difference in your account settings on the web site.
![image](https://user-images.githubusercontent.com/6933240/101066715-7b804780-35fb-11eb-9dde-8e0f4fbbef5b.png)
The question is, which of the many settings is responsible for the problem?

Given that both the date (2020y ago) and the size (14 B) is wrong in your results, it has probably something to do with a settings for language or stylesheet or a torrent display option that adds or removes a column so that the indexer cannot find the data it is expecting at the usual offsets.

Lets start with the most likely options that I think could change the view:
Compare your account settings with mine and note any differences and report back. 
stylesheet: radiation
Box Erklärung: checked
Box Torrentfilter: checked
Kategorie-Design: default
Pretime: nur wenn es ein paar Tage sind
Preview: checked
wget-Kommando: not-checked
Crewbanner: checked
Cover: checked
Screenshots: checked
Beschreibung: checked
IMDb: checked
Thumbnails: checked
NFO einfügen: NFO nicht automatisch in die Beschreibung einfügen

**Comment by Mitnick84** [comment]
Hi, i have exact the same settings as you.  Here is my Screenshot from your search.

<img width="1564" alt="files" src="https://user-images.githubusercontent.com/55686159/101071277-a6877e80-359c-11eb-9497-04f225544281.PNG">

**Comment by Mitnick84** [comment]
Update: can closed, 

i changed the Torrentliste to: Modern
and Torrentfilter to: All

now i get the right sizes and dates

**Comment by garfield69** [comment]
Excellent. I will update the indexer config to add that info for future users.
Thanks.
