### ISSUE TITLE
Change Category for sites have been removed at the request of their owners, instead of removal

### ISSUE THREAD

**Issue by rrrevin** [Jackett/Jackett#10403]
I see MagnetDL has been removed at the request of their owners. OK, I'm cool with that. However, 2 things pop to mind..

1) To be pro-active in stopping people from opening cases (magnetdl is not working/hey, can you add magnetdl?), perhaps change the category for the magnetdl entry in "add indexer" to show "No longer supported at the request of the site owner" in lieu of the normal category types, and remove the configure icon on the line. This is a definitive visual queue as to why it no longer works, and is no longer supported.

2) How do they know Jackett is responsible for %99.97 of all non-interactive traffic? If are they just lumping it it with the rest, and perhaps Jackett is only responsible for perhaps 5% of that total..

**Comment by garfield69** [comment]
>change the category for the magnetdl entry in "add indexer"

The magnetDL will not show up in the users add-indexer page after they update to the jackett version that removes it.
If the users do not upgrade their Jackett then there is nothing can be done.
Once the updater bumped my Jackett to the latest release magnetdl vanished from my active list and my add-indexer page.

>How do they know Jackett  is responsible

Don't know, don't care. Whatever excuse they want to use matters not to me. There are plenty other indexer that perform the same job as magnetDL. We will abide by their request and stop publishing that indexer.

**Comment by ilike2burnthing** [comment]
@rrrevin apologies for the confusion, I shortened what they said, "I'm not sure if it's because of Jackett but the server has been getting hit hard, sometimes a sudden influx of about 10,000+ connections all at once."

The traffic has also almost entirely been focused on the pages we have used for keywordless searches, so it's highly likely that Sonarr/Radarr/*arr users, through Jackett, are the bulk of that.

They've also said that if they add an RSS feed in future for us to use they will let me know.

**Comment by STaRDoGG** [comment]
I like his idea #1.
