### ISSUE TITLE
UHDBits Sonarr no results TV

### ISSUE THREAD

**Issue by Paul5656** [Jackett/Jackett#10423]
Not sure how jackett queries UHDBits but sonarr never gets results from UHDBits. Wasn't sure if it was coz of the way they name them or jackett just searching wrong. Manual searching TV show name only (without season number) in Jackett yields results.
Posted issue with sonarr https://github.com/Sonarr/Sonarr/issues/4107 and they said issue was with jackett.

**Comment by garfield69** [comment]
uhdbits does not do individual tv series episodes, so that is never going to work.
they do have full season packs of series.
but when sonarr does a season search (for example looking for season 1 of the mandalorian) sonarr asks Jackett to search for `Mandalorian S01` which does not match anything on uhdbits because they only list torrents as `the mandalorian season 01`

so what we can do is amend the indexer to swap out the `S01` with `Season 01` and we should start seeing results.

**Comment by Paul5656** [comment]
Yea I meant searching season packs not individual episodes but yeah glad the issue will be fixed. Thanks.

**Comment by garfield69** [comment]
Jackett 0.16.2374
