### ISSUE TITLE
Error downloading - Download selector a[href*="{{ .Config.downloadlink }}"] didn't match

### ISSUE THREAD

**Issue by hexleyOlive** [Jackett/Jackett#10448]
### Environment
**OS**: DSM 6.2.3-25426 Update 2
**Jackett Version**: Version v0.17.3

### Description
Error downloading torrent file with indexers below:
GkTorrent
Torrent9 clone (torrent9.ch)
OxTorrent

### Logged Error Messages
Example of errors:

Error downloading. indexer: gktorrent path: https://vww.gktorrent.pw/torrent/14651/tenet-truefrench-bluray-1080p-2020
System.Exception: Download selector a[href*="{{ .Config.downloadlink }}"] didn't match
  at Jackett.Common.Indexers.CardigannIndexer.Download (System.Uri link) [0x0034c] in <e93ff43b9acc42c8a3282c001e254156>:0 
  at Jackett.Server.Controllers.DownloadController.Download (System.String indexerID, System.String path, System.String jackett_apikey, System.String file) [0x0013a] in <d3b9f07211b24a67a04f660fb66568d9>:0 
[log.txt](https://github.com/Jackett/Jackett/files/5662087/log.txt)

**Comment by garfield69** [comment]
Yeah, these sites have replaced the .torrent direct link with a javascript call.
Behind the scenes I am pretty sure that these three site are the same organisation and the engine or the DB that they reference is the same source, because they always seem to change things at the same time and its always the same change to all three at once.

But the magnets links are still legit and switching the config to those still works.

So the only way to provide a .torrent for these indexers now, is going to be to grab the magnet hash and then provide a replacement link, that goes to itorrents.org with that hash and hope that itorrents has that .torrent on tap.

It's either that, or drop .torrent support altogether, and just provide the magnets only.

I'll try out the itorrents option first and see how that pans out.

**Comment by garfield69** [comment]
Nah, cant get what I intended to work. Its just going to have to be hardcoded for magnet only. :-(

**Comment by garfield69** [comment]
torrent9clone is already magnet only and works for me.  you using https://www.torrent9.so/ ?

**Comment by garfield69** [comment]
jackett 0.17.11

**Comment by hexleyOlive** [comment]
Hi,
Thanks for your investigation, answers and changes.
On my side, I never use magnets and use torrent files + blackhole folder in Radarr.
I'll try to find a way to convert magnet in torrent file.

Thanks!

**Comment by Nuke142** [comment]
Something still wrong with that tracker
Some urls is not valid
![image](https://user-images.githubusercontent.com/19406558/166972315-e2a07f7e-fd81-4cf9-9bfb-3061b8de48a6.png)
![image](https://user-images.githubusercontent.com/19406558/166972459-786f5db3-921a-4690-b273-5d06f4144bae.png)
