### ISSUE TITLE
Failed to update from v0.16.2374 to v0.17.x

### ISSUE THREAD

**Issue by eevlogiev** [Jackett/Jackett#10482]
Folks,
I am having issues upgrading Jackett from 0.16.2374 to any v0.17.* version. Details below:

### Environment

QNAP TS-231P2
Firmware: 4.5.1

**OS**: QNAP Arm32

**.Net Runtime**: Mono v5.20.1.19

**.Net Version**:

**Jackett Version**: v0.17.29

**Last Working Jackett Version**: 0.16.2374

**Are you using a proxy or VPN?** no

### Description

When I hit Check for Updates button in Jackett, the updater is failing.
I've also tried to install a new QPKG from QNAP CLUB repo (https://www.qnapclub.eu/en/qpkg/743). Same issue. Cannot start the process because of a dependancy.

### Logged Error Messages
`<.29-637433908489430650/Jackett/JackettUpdater --Path "/share/CACHEDEV1_DATA/.qpkg/JackettdotNET/Jackett" --Type "Console" --Args " --IgnoreSslErrors true --Port 25633" --KillPids "26531"   
/share/CACHEDEV1_DATA/.qpkg/JackettdotNET/tmp/JackettUpdate-v0.17.29-637433908489430650/Jackett/JackettUpdater: /usr/lib/libstdc++.so.6: version 'GLIBCXX_3.4.20' not found (required by /share/CACHEDEV1_DATA/.qpkg/JackettdotNET/tmp/JackettUpdate-v0.17.29-637433908489430650/Jackett/JackettUpdater)
/share/CACHEDEV1_DATA/.qpkg/JackettdotNET/tmp/JackettUpdate-v0.17.29-637433908489430650/Jackett/JackettUpdater: /usr/lib/libstdc++.so.6: version 'GLIBCXX_3.4.21' not found (required by /share/CACHEDEV1_DATA/.qpkg/JackettdotNET/tmp/JackettUpdate-v0.17.29-637433908489430650/Jackett/JackettUpdater)`

After manually installing v0.17.29. Cannot start the process due to some library dependancy:
`[/share/CACHEDEV1_DATA/.qpkg/JackettdotNET/Jackett] # ./jackett --IgnoreSslErrors true --Port 25633
./jackett: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./jackett)
./jackett: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./jackett)`

**Comment by ngosang** [comment]
It looks like you have to install the library `libstdc++` but I don't know much about QNAP. There are similar questions for Synologic

https://github.com/dotnet/runtime/issues/33384
https://www.google.com/search?q=.net+core+libstdc%2B%2B

**Comment by airhawk777** [comment]
I’d be very surprised if the error was the same as above when you tried updating versions on mono, since mono doesn’t use that library
(Unless there is some kind of bug in the jacettupdater)
If you could paste the error you hit on mono, that would be great

Suggestions
1. Report issue about missing library to the qnapclub maintainer as they are best positioned to look at it and it will impact other users as well
2. Your NAS supports docker, rather than trying to run stuff directly on the qnap, I’d use docker since there is a MUCH larger user base, meaning you are less likely to hit issues and if you do there is a lot more help articles around

**Comment by eevlogiev** [comment]
Guys,
Thank you both for the replies. I've already reached out to the QNAP Club maintainer about that. 
If I don't get anything back from them I will just switch to the Docker version as you suggested.

Best wishes!

Evelin
