### ISSUE TITLE
[enhancement] Fix sonar for foreign languages through Jackett

### ISSUE THREAD

**Issue by MGlants** [Jackett/Jackett#10493]
Hello guys are there any methods to fix what Sonarr tries to search Russian serials in English. 
For example, it tries to searh TV series called Метод by using the English name of it "The Method".

The image shows an example of TV Series that doesn't have a name in English.
![image](https://user-images.githubusercontent.com/35956828/102008853-78483280-3d44-11eb-8a44-cbd2211c1831.png)

Maybe we could build a language bridge that will translate a name by using TVDB backward?
ENG -- Russian
ENG -- French

**Comment by ilike2burnthing** [comment]
Sonarr has had this on their to do list for a while, but currently they only perform searches using English metadata. If a series doesn't have an English title, it can't even be added to Sonarr.

I'll leave this open to hear from others, but I'm gonna say this is entirely on Sonarr.

**Comment by MGlants** [comment]
> Sonarr has had this on their to do list for a while, but currently they only perform searches using English metadata. If a series doesn't have an English title, it can't even be added to Sonarr.
> 
> I'll leave this open to hear from others, but I'm gonna say this is entirely on Sonarr.

I agree but the ticket opened in 2017 and nothing yet changed.
Radarr on their side do searches in foreign languages  😀

**Comment by garfield69** [comment]
Definitely not going to provide the equivalent of a Google translate service for apps.
Slippery slope that will be a nightmare to maintain.
Jackett has no way of determining via the torznab query whether an app expects the query to be translated or not, and every app's needs will be different.

**Comment by Atomsk-debug** [comment]
dumbest answer ever to the question, what mglants said is 100% implementable using TMDB, imdb or tvdb id matching the original or english title with the foreign title of choiche if supported by tmdb and others (it is). 0 mantainment since the work is done from tmdb side

**Comment by ilike2burnthing** [comment]
Yes, because as we all know, when you use an external service there's nothing to ever maintain 🙄 

If a tracker supports IMDB et al ID searching then so can Jackett, and Sonarr/Radarr will use that over the title name, so there's no issue there. If not, then the issue is best solved by Sonarr/Radarr implementing alternate/original language titles (Sonarr actually has a request form for alias titles, not quite the same but can be used to bridge this in the mean time).

We're not going to look up other services to pull titles from for some searches some of the time.
