### ISSUE TITLE
[speedcd] Exception (speedcd): Resource temporarily unavailable: Resource temporarily unavailable (speed.cd:443) (Test)

### ISSUE THREAD

**Issue by bosonrolo** [Jackett/Jackett#10612]
I got the above error for several days with no uptime. I logged into Docker and found I could cURL speed.click, but not speed.cd.

Resolution: Change Site Link from https://speed.cd to https://speed.click.

Not sure if there's any action to take on the repo, but wanted the issue logged in case it helps someone else.

**Comment by ilike2burnthing** [comment]
I don't have an account to check, but do you know if this is a permanent change (e.g. is there a post on the site about it)?

---

Note to self: site now using Cloudflare, add note

**Comment by egadsthefuzz** [comment]
It is listed as an alternative in an announcement. I came here cos I got this "Exception (speedcd): Challenge detected but FlareSolverr is not configured: Challenge detected but FlareSolverr is not configured" so i suspect cloudflare oddness

**Comment by ilike2burnthing** [comment]
Yes, currently the site uses Cloudflare DDoS Protection, so you'll have to use FlareSolverr to allow Jackett to bypass it - https://github.com/Jackett/Jackett#configuring-flaresolverr

If there is a further announcement about the site change being permanent (rather than a temporary measure, e.g. due to some issue), please let us know so we can remove the *.cd link.
