### ISSUE TITLE
[empornium2fa] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by adamwinn** [Jackett/Jackett#10646]
### Environment

**Jackett Version**:
Jackett Version v0.17.159

**Last Working Jackett Version**:
n/a

**Are you using a proxy or VPN?** [yes/no]
no

### Description
I configured empornium2fa but no results were shown.  Some html parsing is off because I got a few errors in the logs.

### Logged Error Messages

```
2020-12-28 14:45:40.2686 Error CardigannIndexer (empornium2fa): Error while parsing row '
```
and also

```
System.Exception: Error while parsing field=description, selector=div.tags, value=<null>: Selector "div.tags" didn't match
```

**Comment by ilike2burnthing** [comment]
Please provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by adamwinn** [comment]
@ilike2burnthing Sorry for not providing a log the first time.  It was too big for github and pastebin wouldn't allow it because of keywords.

The log is at:  https://ghostbin.co/paste/7y8ua

**Comment by ilike2burnthing** [comment]
Thanks for that.

None of the maintainers have an account, so if you're up for some quick testing, hopefully we can get this sorted.

Open `empornium2fa.yml`  in a text editor and remove/comment out the lines:
```
    description:
      selector: div.tags
```
Save the file, restart Jackett, and run a test again.

Everything else looks ok, so hopefully that will be all that is needed. If not, post the equivalent error as before:
```
System.Exception: Error while parsing field=description, selector=div.tags, value=<null>: Selector "div.tags" didn't match
```

**Comment by adamwinn** [comment]
I have Jackett installed using docker on my Synology nas.  I can't find `empornium2fa.yml` anywhere.  

I saw this in the logs during boot-up (I think it was) 
```
2020-12-23 12:20:00.8199 Info Attempting to copy empornium2fa.yml from source: /tmp/JackettUpdate-v0.17.159-637443227912782764/Jackett/Definitions/empornium2fa.yml to destination: /app/Jackett/Definitions/empornium2fa.yml
``` 
but I dont have a `/app` dir

Is @garfield69 a maintainer? I saw he got an invite in another issue here

**Comment by adamwinn** [comment]
If it's puking on tags, I have the option turned on in my settings `Hide tags in lists` so maybe looking for tags should be optional.  If I remove the tags code like you referenced above and that fix gets merged in, it might break for other people

**Comment by adamwinn** [comment]
I just turned off `Hide tags in lists` in my profile and it's working now.  Having tags be optional would be best so it works for all users.

**Comment by ilike2burnthing** [comment]
Everyone is away for the holidays, just me holding down the fort at the moment. Not sure if they have an account or not, it's not in 'the list'.

Last bit of testing and then I'll make the change on our end. First, re-enable `Hidetags in lists` on your account.

You should have the volume `/config` mapped for Jackett's container (it has the sub-folder `Jackett` with the logs, config file, indexers, etc.). If not do so, e.g. `/volume1/Docker/Jackett/config` - not sure about Synology's folder structure, so that might need changing.

Navigate to that folder (for me, that's just via a mapped network drive on my computer), create a sub-folder `cardigann`, and a sub-folder within that one `definitions`.

Right-click and download this link ([empornium2fa](https://raw.githubusercontent.com/Jackett/Jackett/master/src/Jackett.Common/Definitions/empornium2fa.yml)), rename to something else, e.g. `empornium2fa-test` and edit these lines:
```
id: empornium2fa-test
name: Empornium2FA-Test
[...]
    description:
      optional: true
      selector: div.tags
```
Save, move the file to `/config/cardigann/definitions`, restart Jackett, add Empornium2FA-Test, enter your details, and run a test. If everything works (honestly I don't see why it wouldn't), I'll make it optional.

**Comment by adamwinn** [comment]
It didn't load the new yml file.  Is `/volume1/docker/jackett/Jackett/cardigann/definitions/empornium2fa-test.yml` the right path?

`/volume1/docker/jackett/Jackett` is the folder with `updater.txt`, `ServerConfig.json`, `log.txt`, `Indexers`, etc

**Comment by ilike2burnthing** [comment]
Remove `/Jackett` - `/volume1/docker/jackett/cardigann/definitions/empornium2fa-test.yml`

**Comment by adamwinn** [comment]
It loaded it and I configured it and I ran a test and it worked!

**Comment by adamwinn** [comment]
@ilike2burnthing Thanks for the fix!

**Comment by ilike2burnthing** [comment]
Thanks for all your help.

You may have to use that temporarily until there's a new build out.

**Comment by ilike2burnthing** [comment]
[v0.17.166](https://github.com/Jackett/Jackett/releases/tag/v0.17.166)
