### ISSUE TITLE
[REQ]fapforfun.net 2D,3D adult content

### ISSUE THREAD

**Issue by berat1397** [Jackett/Jackett#10656]
Public 2D,3D hentai, hentai games sharing torrent site. 

Search engine and magnet links working.

https://fapforfun.net

![1](https://user-images.githubusercontent.com/36575395/103282907-3972d780-49e8-11eb-815d-33194f6bbcb8.JPG)
![2](https://user-images.githubusercontent.com/36575395/103282912-3c6dc800-49e8-11eb-88f6-a694fffe331f.JPG)

engine: WordPress 5.7.3

**Comment by garfield69** [comment]
not all the results have magnets available on the related details pages.
rather, some have several links that take you to 3rd party services, each of which have different click-this or that (and same even have delays that count down before the link is made available) before you get presented, finally with a .torrent href.

Since there does not appear to be a way to detect if a title in the results will lead to a page with a magnet or a 3rd party link, I don't thing we can support an indexer for this site.
if the site only had the .torrents on-site we could at least do a try-magnet then try-torrent download method.
but with the 3rd party services in use the current .torrent download will not yield a .torrent when presented with intermediate click pages and timed countdowns.
