### ISSUE TITLE
[REQ]javtorrent.me Public JAV

### ISSUE THREAD

**Issue by berat1397** [Jackett/Jackett#10657]
Public japan adult video sharing torrent site.

Torrent files from different domain but access available.

https://javtorrent.me

Search engine and torrent files working.

![1](https://user-images.githubusercontent.com/36575395/103283171-d6ce0b80-49e8-11eb-8565-17e72f051f15.JPG)
![2](https://user-images.githubusercontent.com/36575395/103283173-d9306580-49e8-11eb-857e-e2207899c067.JPG)

**Comment by garfield69** [comment]
this site is not suitable for use with jackett. the .torrent download is hosted on a 3rd party service that requires additional page interaction (one the page is presented you have to click on the download-now icon). Jackett expects the download href from the details page to deliver the .torrent file without intervening pages.

besides, since the time of the original opening of this ticket, the page of results now only contains an abbreviated title
![image](https://user-images.githubusercontent.com/6933240/127628846-ecb8898e-cee5-467b-8ecc-065878cb4621.png)
which is even less useful that previously.
I dont think its worth wasting any more time on this one.
