### ISSUE TITLE
magnetdl.com

### ISSUE THREAD

**Issue by robgates** [Jackett/Jackett#1069]
Any chance that http://www.magnetdl.com/ could be included . Not sure if its a tracker but it seems to be a busy site

Thanks

-------------------------------

**Comment by armani316** [comment]
I see that magnetdl.com is already indexed by torrentz2 #1040 which is supported by Jackett.
https://torrentz2.eu/help#indexed

I think it might be safe to close this issue. @kaso17 Thoughts?

**Comment by robgates** [comment]
Cool 👍

**Comment by armani316** [comment]
@robgates The only problem is that torrentz2 removes a lot of torrents after receiving DMCA or EUCD notices, therefore some results from magnetdl.com will not appear on torrentz2. 

There's also the fact that Jackett only returns the results shown on the 1st page on the tracker's website (See issue #975), so not all results from magnetdl.com will be returned upon searching torrentz2. However, there's a plan to resolve this issue in the future.

**Comment by garfield69** [comment]
@kaso17  I need to extract the first character of the first keyword in order to build the correct path for this tracker.     
examples:      
a search for `preacher s01e10` requires a path of: `p/preacher-s01e10/`      
a search for `preacher s01e10` requires a path of: `m/midnight-texas-s01e10/`     

Notice that I also need to replace the space between keywords with a `-`, as encoding `+` or `%20` returns 404.

I have not come across any examples in the current definitions that does something similar.     
Do you have any suggestions?

**Comment by kaso17** [comment]
should be possible with the re_replace template function.
get the first character: `{{ re_replace .Keywords \"(.).*\" \"$1\" }}`
replace space with -`{{ re_replace .Keywords \" " \"-\" }}`

**Comment by garfield69** [comment]
removed at request of author. See https://github.com/Jackett/Jackett/pull/10347#issue-530982565 for more details.
