### ISSUE TITLE
[LearnFlakes] Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by whitesnakeftw** [Jackett/Jackett#10766]
### Environment

**OS**: Windows 10 x64 (10.0.19041.685)

**Jackett Version**: v0.17.207

**Are you using a proxy or VPN?**: no

### Description

Login seems to work fine, but when I "test" the tracker, it always gives me this error.

Every time I search something on Jackett, these failed attempts are recorded by LF, which sends you a PM onsite saying "failed login attempt". The oldest of these PMs I have dates back to December 27.

**Comment by ilike2burnthing** [comment]
From the indexer's config page:
`If you are getting the error 'Found no results while trying to browse this tracker' then first access the site with your browser and check that you are not being forced to change your password because it has expired after 180 days.`

Try signing out and back into the site in your browser to see if you're prompted to change your password. If not, please post an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by whitesnakeftw** [comment]
@ilike2burnthing Signing out and back in fixed the issue, although it did not ask me to change my password. Thanks for the help. :)
