### ISSUE TITLE
Req: (enhancement) Stats

### ISSUE THREAD

**Issue by Tiwas** [Jackett/Jackett#11094]
Is it possible to get stats integrated? If comparing trackers, it would be nice to add several and see which ones perform best for your purposes. Which one has more hits? Is it possible to get data from sickchill/client to see which ones never downloads? Why some files stall?

If this is already in here, or if it's possible to get this info elsewhere I would love some pointers, though :)

**Comment by ilike2burnthing** [comment]
This would probably be better done on SickChill/*arr's end (e.g. Indexer: RARBG, Downloads: 156), as a tracker that is good for films might not be great for TV, and another might be good for music but bad for eBooks. They'd also be able to show the number of failed or blacklisted downloads.

Not sure if this is what you meant by hits, but total returned results will likely never be implemented no matter who does it, because if you get 100 results per request, and a request is made every 30 mins, then you're just shy of 5000 results by day one (and if you wanted the much more useful number of unique results, then you're going to have to cache them for no reason other than to count them).

The closest request to this would be for private trackers only, and would reflect your usage of the tracker as a whole, not just through Jackett - https://github.com/Jackett/Jackett/issues/656

If I've understood this correctly, then are you ok that this is closed?

**Comment by Tiwas** [comment]
Yeah, thanks. I had a suspicion this would have to be done in SC anyway. It would be nice to have some stat of how many hits you'd get, which *could* be gotten from jackett (but also from SC), but the big deal would be to see which were actually snatched, and if they even downloaded. If a provider had lots of hits, but very few completed downloads it would at least signify that some research should be done. So...while some of it *could* be done on this end, it's probably even better on SC :)

Thanks!
