### ISSUE TITLE
[New Tracker REQ] MegafileTUBE

### ISSUE THREAD

**Issue by EffeF** [Jackett/Jackett#1110]
**Indexer Name:**
MegafileTUBE

**Type:**
Movies, Animation, Series, Music, Games, Applications, eBooks, XXX, Other

**Indexer URL:**
http://megafiletube.xyz/

**Indexer Language:**
Italian

**Invite:**
Unnecessary

**Comment by garfield69** [comment]
seeing 
![image](https://user-images.githubusercontent.com/6933240/30682892-6d7e6590-9eff-11e7-95ba-591fd12c603c.png)
when accessing http://megafiletube.xyz/.      

A check on whois confirms the domain has been suspended.     

Does anyone know if the site has moved to another domain?    
Otherwise this ticket can be closed.

**Comment by EffeF** [comment]
Yes, it's suspended. The site is closed.
