### ISSUE TITLE
kickasstorrent.to

### ISSUE THREAD

**Issue by entryb** [Jackett/Jackett#11191]
Jackett Version v0.17.598 

os ubuntu 18.0.4

This indexer doesn't provide the ability to copy magnet links which the site does have, also the download function doesn't work either so its not working properly

**Comment by garfield69** [comment]
Downloads are working for me ATM on https://kickasstorrents.to/
Are you using a different site link?
Do you have a particular torrent that you cannot get a download for?

With regards to magnets, this is not straight forward.
If the magnets were available on the main search results page of the site, then we could easily provide magnets.
But because we have to fetch the individual page of the title you are wanting to download, Jackett can only provide ONE link. ATM we chose to provide the .torrent link, as this is the most popular request.

However, I believe we can provide a Jackett config option for this indexer, to allow you to select to download magnets instad of .torrents (as we do for some other indexers), so I will look at providing that feature.

**Comment by garfield69** [comment]
Hold the phone. I've just checked the code and we are providing magnets for this indexer.
https://github.com/Jackett/Jackett/blob/48ca09983786738478586d201da6e592bdf0c9e6/src/Jackett.Common/Definitions/kickasstorrents-to.yml#L53-L55

this only issue is a visual one on the Jackett dashboard, where the search page results does not show a magnet symbol.
This is because the magnet is on the details page, as I explained earlier, and Jackett at the time that the search results are processed, does not know what type of download will be available on the details page, so it shows a download icon.
But it is a magnet link that is fetched, and as I said earlier, the link is working for me on the main sitelink.

**Comment by entryb** [comment]
Just i saw with another indexer YTS it provides both magnet and download on same search result, problem for me though is that the regular download isn't working either, there's no error in the log when i press the download button also so difficult to point to where to problem might be

**Comment by entryb** [comment]
Im closing this, seems be due to all the indexers being hosted on Cloudflare and im not using Flaresolverr

**Comment by entryb** [comment]
This was not due to Cloudflare either, i dunno how it is your is working, i tried with new config and still no download, again it works for other trackers also on Cloudflare
Cant seem to find anything in logs either https://paste.ubuntu.com/p/QB89HgPVxv/

**Comment by garfield69** [comment]
@ilike2burnthing  can you download magnets from kickasstorrents.to indexer using the https://kickasstorrents.to/ site link?

**Comment by entryb** [comment]
Im able to right click and copy link location to get magnet on https://kickasstorrents.to/ , however the torrent file requires a login to download, could it be that it somehow defaults to the file instead of magnet?

**Comment by garfield69** [comment]
kickasstorrents is a public site, so login should not be required for downloads.
if you are getting a login request then provide proof by showing a screen capture of the event using the web site directly so we can check.

**Comment by ilike2burnthing** [comment]
> @ilike2burnthing can you download magnets from kickasstorrents.to indexer using the https://kickasstorrents.to/ site link?

yep, no issues here

**Comment by entryb** [comment]
![k](https://user-images.githubusercontent.com/44838864/109656576-dbd44600-7b64-11eb-9df2-ab41c69cdb21.jpg)
![k1](https://user-images.githubusercontent.com/44838864/109656579-dd9e0980-7b64-11eb-811f-4ee24f795af5.JPG)

**Comment by entryb** [comment]
First image show the link that download button points to, seems very clear to me thats not a torrent link, magnet link is working though, also when i try to download the torrent file i get as in second image

**Comment by ilike2burnthing** [comment]
The `Download Torrent` button is fake. When you click on it you get that red account button which links to */register/ which is just a spam redirect. Jackett doesn't touch it, so it can't be causing issues for the indexer.

kickass.ws uses mylink for its magnets, which Jackett ignores and just takes the hash from the link.

Both indexers are working fine, and your log shows a magnet link being successfully found, one that works fine here. What issue are you facing?

**Comment by entryb** [comment]
As i initially stated in my first post, im not able to get the magnet link itself by pressing the download icon on result page, instead when pressing the icon or copying its location, the address is not a magnet link but the link below which isnt usable.
"http://someip:9117/dl/kickasstorrents-to/?jackett_apikey=123456789&path=Q2ZESjhJdTJrMGtPWkdwT2dncFZNYVNfUjU0T2pSYllWOFlUaHc4N2VkWnlXMWhjekR0OFBmME8yZ2V3XzVSTG5mMFdTUmkyaW9fVHNtRFRSYkVQaXd5M0tDXzBIR0JCMHBlOG5ncVVKdHlLMjZCMER5MV82SWI4VkVVVEY5WDdNTGNDclZMdXM2TUhJVHMweXF1V0NwU0t4dThYRFo4VVZxRHFtN3o0MHhlRnRuSnhkRk11ZE1XOTI0QmUyOXcxRmJRWnB6cEV2anM0TFNfMEo0aU8xMVZRZ05tbHY4YnpuX2xLamNwQ25OYWh3eHQwNnZ5NGdwVmJ0M1ZMVk5TZk9pcFUzQQ&file=FreeCourseWeb+Udemy+-+Travel+Videography+-+Start+Making+Amazing+Videos"

 Also magnet icon is missing on result pages, though maybe as garfield stated earlier the magnet would be in the download icon instead? My guess since the magnet link is found in the log, its the process of handling it afterwards when pressing the download icon which fails

**Comment by ilike2burnthing** [comment]
Yes, that's the link Jackett uses to fetch the magnet link. You'll see the same for other indexers which have to access the torrent's page before it can access the magnet (e.g. 1337x).

What happens when you click the download icon in Jackett?

What torrent client are you using (any chance it's Transmission)?

**Comment by entryb** [comment]
In jackett it doesnt happen anything as ive not configured any client to handle it locally, im just using jackett to get links then i by hand put them in Transmission, this works for many other indexers in jackett just not seems those i mentioned.

**Comment by garfield69** [comment]
Any web site that requires Jackett to fetch the magnet/torrents link from the web sites **torrent details** page means that Jackett is not able to provide a direct link to that magnet/torrent in its search results page, like it can for those web sites that provide links in their own search results pages.
Instead, Jackett provides a indirect link, that gets resolved only when the user click on that download button in the search page.
This is by design, as jackett is not going to fetch every torrent details page ahead of time while generating the search results page, as this would cause up to 100 additional http requests to the web site, which most sites will interpret as a potential ddos attack.
This means that you cannot achieve what you intend, for those indexers that do not have links it their search page, but have then in individual torrent details pages.
