### ISSUE TITLE
Search results from 160 indexers come in 25 seconds. Is this a normal?

### ISSUE THREAD

**Issue by batuhankrmn** [Jackett/Jackett#11203]
Since I like getting all results from multiple trackers, I added 160 indexers to Jackett. Mixed of public/semi-private/private and I get the search results in 20-25 seconds. I don't have any friend that using Jackett. So I wanted to ask here. Is these waiting times (20-25 seconds) normal for 160 trackers? I mean I'm happy with 20-25 seconds but just wondering that is this delay expected?

**Comment by garfield69** [comment]
many indexers have web sites that perform anti-ddos checking, or perform logins (private,semi-private) and these accumulate to the total response time.
for 160 indexer, 25 seconds total response time is actually very good.
Not unusual for indexers which break because of web sites that are offline/use recaptcha/have overloaded servers which can cause Jackett to wait for a response and time out after 30 to 300 seconds, thus extending to overall response time.

As a side note, IMO, results from all these indexers is just an over the top, overkill, resource wasting effort.
Most web sites have the same content, especially the public ones.
To get an overall view of the torrents available, you really only need a handful of indexes, plus any private specialised sites.
But suit yourself. ;-b
