### ISSUE TITLE
[req] Torrent diamond https://torrentdia.com  public Korean

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#11210]
Torrent diamond https://torrentdia.com  public Korean
spawned from #10663

Torrent Dia (토렌트디아) is down for several days too (perhaps CloudFlare misconfiguration).

**Comment by garfield69** [comment]
https://torrentdia.com/ returning Error 1020 Access denied

**Comment by ilike2burnthing** [comment]
same

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
not for me. still getting 1020, even with vpn on a canadian ip

**Comment by ilike2burnthing** [comment]
huh, briefly worked, but not now

**Comment by ilike2burnthing** [comment]
Site is region blocked. Korean VPN server works. Redirects to https://www.xn--sm2bu1n2xfsllblbca.com/ which isn't region blocked, but provides a link to the actual site https://www.torrentdia3.com/ which is region blocked.

https://www.torrentdia3.com/ tries to present a captcha challenge, but fails with `This web property is not accessible via this address.` because it's meant for `torrentdia.com`.

**Comment by garfield69** [comment]
Closing as unsuitable for indexing. Refer https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing
