### ISSUE TITLE
[REQ] rezka.cc public tracker

### ISSUE THREAD

**Issue by GAS85** [Jackett/Jackett#11316]
Please add public Russian tracker `https://rezka.cc/`
Has links to torrent files in different quality 
![grafik](https://user-images.githubusercontent.com/6813635/111068171-efb66b00-84c7-11eb-9473-5c5381476192.png)

**Comment by garfield69** [comment]
Closing as unsuitable for indexing. Refer https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing

**Comment by dshkoda32** [comment]
Tell me this tracker can not be added in any way? New items are coming out there very quickly and therefore I would like to see it in your jackett

**Comment by garfield69** [comment]
The only way this site can be added is with the use of a C# indexer, for which there are no C# developers available.
In addition, the traffic that the indexer would generate in order to populate the search results page with useful data will increase the load on the sites server such that they may flag your IP as a possible DDoS generator, or potentially, if many users all decide to add this indexer to their stable, may increase the traffic workload on their server to potentially require them to increase their capacity, costing more to keep it running.

**Comment by ArtsiomBelyakov** [comment]
@garfield69 
Hi. Can you tell me if anything has changed for this tracker?

**Comment by garfield69** [comment]
>Hi. Can you tell me if anything has changed for this tracker?

the site remains unsuitable for indexing with Jackett.
