### ISSUE TITLE
scenetime: missing categories

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#11383]
![image](https://user-images.githubusercontent.com/10577978/111914019-a5f1f580-8a70-11eb-9698-89d82465f185.png)
![image](https://user-images.githubusercontent.com/10577978/111914026-adb19a00-8a70-11eb-8f2f-75a5b618ef30.png)
![image](https://user-images.githubusercontent.com/10577978/111914033-b6a26b80-8a70-11eb-975c-d644c6813f95.png)

**Comment by garfield69** [comment]
The site does not have the category href for these torrents.
Will see if I can manage to code a C# handler for this indexer for when the cat is missing, default it to Other.

**Comment by garfield69** [comment]
Bugger. The site does not have an **Other** catId, and I can't just make one up because the site search supports multi cat searching and so the catId needs to be a valid one.
I'll default to MoviesOther (82) the closest match to MDVDR I can find, since that appears to be what all the missing ones have in their title.
