### ISSUE TITLE
selezen: invalid download links

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#11388]
Try to search those torrents in Jackett
* https://mel.selezen.net/relizy-ot-selezen/2529-cikada-3301-kvest-dlja-hakera-dark-web-cicada-3301-2021-bdrip-720p-ot-selezen-itunes.html
* https://mel.selezen.net/relizy-ot-selezen/2533-liga-spravedlivosti-zaka-snajdera-zack-snyders-justice-league-2021-web-dl-1080p-ot-selezen-d-mosfilm-master.html

**Comment by garfield69** [comment]
for registered users only.
since the indexer is set to public and the href is on the details page, there is no way to exclude the torrent from the primary search results in cardigann.
could switch the indexer to semi-private if the registered-only entries are a large proportion of the search results... ?

**Comment by ngosang** [comment]
I can't download torrents from that site. Maybe we should add the login and make it semi-private.

**Comment by garfield69** [comment]
v0.17.788
