### ISSUE TITLE
[speedcd] Exception of type 'System.Exception' was thrown.

### ISSUE THREAD

**Issue by NiNiyas** [Jackett/Jackett#11438]
**OS**: Windows 10 build 19042.621

**Jackett Version**: v0.17.815

**Last Working Jackett Version**: Probably v0.17.810 because arr apps didn't throw this error until today.

**Are you using a proxy or VPN?** : No

### Description

Trying to setup speedcd and ran into this error. 

### Logged Error Messages

[From logs](https://gist.githubusercontent.com/NiNiyas/9cc9da3113ac0265e52e7e5b89168093/raw/496ecece6a16d3d7e53a3aab86e90ed626454063/jackett%2520v0.17.815%2520speedcd)

**Comment by garfield69** [comment]
the indexer is working for me which suggests the problem is at your end.
confirm your credentials in the site are up to date by login in with your browser, and ensure you have a good ratio, and no outstanding alerts, notices, unread PM that may prevent you accessing the torrents search page.
Try using the jackett dashbaord to edit the indexer config and saving with fresh credential info.
try using one of the alternate site links.
try deleing the config and starting a fresh one.
if all fails then provide an **enhanced** log so we can take a closer look at the problem details.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by NiNiyas** [comment]
Working after removing and adding again. Thanks!
