### ISSUE TITLE
[ilcorsaronero] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by PiroX4256** [Jackett/Jackett#11437]
### Environment

**OS**: Synology DSM

**.Net Runtime**: Mono 5.20.1.34-16

**Jackett Version**: 0.17.810

**Last Working Jackett Version**: 0.17.810

**Are you using a proxy or VPN?** no

### Description

The tracker "ilcorsaronero" is no longer working, but if I visit its URL (https://ilcorsaronero-it.cz/), it shows me the valid page and let me search content.

### Screenshots
https://imgur.com/a/vqTDImn

**Comment by garfield69** [comment]
the indexer works for me so the issue is most likely at your end.
try using the Jackett dashboard to edit the indexer config and try any of the alternate sitelinks.
if all fail then provide a **enhanced** log so we can try to discover what  your problem is.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by ilike2burnthing** [comment]
Several people have mentioned https://ilcorsaronero-it.cz/ already, it appears to be a poor clone.

Use the actual site links provided for the indexer and you won't get that error.
