### ISSUE TITLE
Releases name without original dashes

### ISSUE THREAD

**Issue by Bazzu85** [Jackett/Jackett#11449]
### Environment

**OS**: Windows 10

**.Net Runtime**: 

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**: v0.17.826

**Are you using a proxy or VPN?** [yes/no] no

### Description

It seem to happening on all indexers.
Jackett seems to remove all dashes on releases. In some indexers even the dots (rarbg not for example)
ex: 
Showname S02E09 10 iTALiAN MULTi 1080p WEB x264
on torrent site is 
Showname.S02E09-10.iTALiAN.MULTi.1080p.WEB.x264

this cause the issue that sonarr doesn't recognize that is a 2 episode release..

Can you give me some feedbacks?

### Logged Error Messages

no errors

### Screenshots

![2021-03-31_174813](https://user-images.githubusercontent.com/7345587/113173038-4ef6d800-9249-11eb-8fe4-f426c37e43f7.jpg)
![2021-03-31_174803](https://user-images.githubusercontent.com/7345587/113173040-4f8f6e80-9249-11eb-8a6a-51682fa7ad55.jpg)

**Comment by ilike2burnthing** [comment]
It shouldn't be happening for all indexers, just those which use something like:
https://github.com/Jackett/Jackett/blob/58736bd4aa92c628c8b5eda86886f776946a603b/src/Jackett.Common/Definitions/ilcorsaronero.yml#L91-L92

@garfield69 could we just remove hyphens from the re_replace, or would we have to do something like this?
```
        - name: re_replace
          args: ["(?i)S(\\d{1,2})E(\\d+)-(\\d+)", "S$1E$2to$3"]
        - name: re_replace
          args: ["(?i)S(\\d{1,2})-(\\d{1,2})", "S$1to$2"]
        - name: re_replace # replace special characters with " " (space)
          args: ["[\\[!\"#$%&'()*+,\\-.\\/:;<=>?@[\\]^_`{|}~]", " "]
        - name: re_replace
          args: ["(?i)S(\\d{1,2})E(\\d+)to(\\d+)", "S$1E$2-$3"]
        - name: re_replace
          args: ["(?i)S(\\d{1,2})to(\\d{1,2})", "S$1-$2"]
```

**Comment by ilike2burnthing** [comment]
Ah, damn.

@Bazzu85 are there other indexers you're having this issue with that we might be able to fix?

**Comment by Bazzu85** [comment]
@ilike2burnthing 
I'm checking the indexers I'm using. So here's :

Il Corsaro Blu
test case: Romanzo criminale s01e01 02 torrent icb torrent
https://ilcorsaroblu.org/Romanzo_criminale_s01e01_02_torrent_icb_torrent-430391.html
![2021-03-31_222753](https://user-images.githubusercontent.com/7345587/113206953-5da4b580-9270-11eb-938c-161527d8f42f.jpg)




Il Corsaro Nero
test case: Snowpiercer S02E09 10 iTALiAN MULTi 1080p WEB x264 MeM mkv
https://ilcorsaronero.pro/tor/169759/Snowpiercer_S02E09_10_iTALiAN_MULTi_1080p_WEB_x264_MeM_mkv


1337x
test case: Kenan S01E06 You Go Squirrel XviD AFG TGx
https://1337x.to/torrent/4823125/Kenan-S01E06-You-Go-Squirrel-XviD-AFG-TGx/
![2021-03-31_222827](https://user-images.githubusercontent.com/7345587/113207019-6f865880-9270-11eb-927e-1247a7c3b713.jpg)


kickasstorrents.to
I see that dots are replaced, but not dashes...so I think is ok
test case: 
MasterChef S17E13 720p HDTV x264-​DARKFLiX TGx ⭐
https://kickasstorrents.to/masterchef-s17e13-720p-hdtv-x264-darkflix-tgx-t4821801.html
![2021-03-31_222852](https://user-images.githubusercontent.com/7345587/113207090-7dd47480-9270-11eb-9bf5-3b3fb3b8fffe.jpg)


RARBG
I see that none is replaced. dots and dashes remains
Big.​Brother.​Canada.​S09E12.​WEBRip.​x264-​ION10
https://torrentapi.org/redirect_to_info.php?token=0gh1b5dkj4&p=2_4_6_8_5_8_1__092141ddab&app_id=jackett_v0.17.826

**Comment by garfield69** [comment]
there is nothing to fix.
Jackett regularly replaces dots with spaces for most indexers, as they are mostly interchangeable and make no difference to results , usually.
We regularly replace dots with spaces as this makes for more readable titles on the dashboard, and some of the torznab apps don't like dots in titles.
Sonarr does not care, but it is not the only torznab app that can interface with Jackett, so we have to allow for the other apps.

ilcorsaroblu does not return a dash between the split episodes in its search results page, which is the only place that Jackett fetches the results from, not the individual torrent details page.
You can not expect the indexer to add a dash if one was never there in the first place on the results that the web site returns.

and ilcorsaronero truncates titles in the results pages, so that is a stuffed up process to begin with, and you get the best effort of the indexer to provide a full title. If this leads to missing dashes, too bad.

IMO there is nothing worth doing. it is a border line case  and no worth investing effort trying to improve.

**Comment by Bazzu85** [comment]
mmh...
what about the same release on 1337x?
https://1337x.to/torrent/4822618/Snowpiercer-S02E09-10-iTALiAN-MULTi-1080p-WEB-x264-MeM-mkv/
![2021-03-31_234631](https://user-images.githubusercontent.com/7345587/113215580-58009d00-927b-11eb-93a4-6874db0e34ce.jpg)
the indexer has the same problems than ilcorsaronero regarding the titles?

**Comment by ilike2burnthing** [comment]
Similar issue to ilcorsaronero, but this time the title is `Snowpiercer-S02E09-10-iTALiAN-MULTi-1080p-WEB-x264-MeM-mkv` and so the hyphens are removed.

**Comment by garfield69** [comment]
I think you are wasting your time.

when Sonarr send a torznab request for **snowpiercer s02e10** to jackett, its post
`http://127.0.0.1:9117/api/v2.0/indexers/1337x/results/torznab/api?t=tvsearch&cat=5000,5030,5040,5070,5080,8000,8010&extended=1&apikey=MYAPIKEY&offset=0&limit=100&q=Snowpiercer&season=2&ep=10`
to jackett.
This causes the Jackett indexer to request a search in 1337x  using 
`https://1337x.to/sort-search/Snowpiercer%20Rompenieves%20S02E10/time/desc/1/` 

even if we left the dashes in place in the titles that Jackett returns to Sonarr, Sonarr will never see the title
`Snowpiercer-​S02E09-​10-​iTALiAN-​MULTi-​1080p-​WEB-​x264-​MeM-​mkv` in the results that Jackett passes back to Sonarr, because 1337x will only return titles that contain `sonwpiercer S02E10` in respose to that search, which does not include titles that have  `S02E09` in them.

But even if somehow we got `Snowpiercer-​S02E09-​10-​iTALiAN-​MULTi-​1080p-​WEB-​x264-​MeM-​mkv` back to Sonarr, I am not convinced that Sonarr would recognise that this title is a season 2 episode 10 candidate.

**Comment by Bazzu85** [comment]
> I think you are wasting your time.
> 
> when Sonarr send a torznab request for **snowpiercer s02e10** to jackett, its post
> `http://127.0.0.1:9117/api/v2.0/indexers/1337x/results/torznab/api?t=tvsearch&cat=5000,5030,5040,5070,5080,8000,8010&extended=1&apikey=MYAPIKEY&offset=0&limit=100&q=Snowpiercer&season=2&ep=10`
> to jackett.
> This causes the Jackett indexer to request a search in 1337x using
> `https://1337x.to/sort-search/Snowpiercer%20Rompenieves%20S02E10/time/desc/1/`
> 
> even if we left the dashes in place in the titles that Jackett returns to Sonarr, Sonarr will never see the title
> `Snowpiercer-​S02E09-​10-​iTALiAN-​MULTi-​1080p-​WEB-​x264-​MeM-​mkv` in the results that Jackett passes back to Sonarr, because 1337x will only return titles that contain `sonwpiercer S02E10` in respose to that search, which does not include titles that have `S02E09` in them.
> 
> But even if somehow we got `Snowpiercer-​S02E09-​10-​iTALiAN-​MULTi-​1080p-​WEB-​x264-​MeM-​mkv` back to Sonarr, I am not convinced that Sonarr would recognise that this title is a season 2 episode 10 candidate.

I asked to sonarr guys..
If the release contains showname s02e09-10 sonarr can recognize that this is episode 9 AND 10 of season 2 and treat the total release dimension dimension as 2 episode runtime.
The problem now is that sonarr searching for s02e09 recognize that is a single episode release of 8.8gb and reject the download because the size per minute of the release.
I was asking you because the original release name could be handle well by sonarr, if the name was the original one and not the one cleaned by jackett

**Comment by garfield69** [comment]
the RarBG indexer is written in C# because we are obliged by the sysop there to use its API at https://torrentapi.org instead of HTML scraping with yaml via https://rarbg.to/
When the C# indexer was written the author did not think to clean up the titles as is usually done with yaml indexers.
Its as simple as that.

**Comment by Bazzu85** [comment]
> the RarBG indexer is written in C# because we are obliged by the sysop there to use its API at https://torrentapi.org instead of HTML scraping with yaml via https://rarbg.to/
> When the C# indexer was written the author did not think to clean up the titles as is usually done with yaml indexers.
> Its as simple as that.

So for corsaroblu and corsanero is not possible at all mantain the release name as are html scraping..even with a flag in indexer options?

**Comment by garfield69** [comment]
Yes it should be possible. The question has always been whether its worth making the changes and whether anyone would volunteer to do it.

**Comment by Bazzu85** [comment]
> Yes it should be possible. The question has always been whether its worth making the changes and whether anyone would volunteer to do it.

IMHO if rarbg works well without the character replacement can be a worth update to let the user choose to use other indexers in the same way..
If you can do this improvement for corsaroblu and corsaronero , I'll be grateful..

**Comment by garfield69** [comment]
v0.17.830

**Comment by Bazzu85** [comment]
thx a lot @garfield69 
I'm testing right now..
can I ask the same to 1337x?

**Comment by Bazzu85** [comment]
thx a lot..
BTW I'm noticing that your cleanup is only on the episode numering and not all the release name.
I'll attach some examples:
![2021-04-03_011206](https://user-images.githubusercontent.com/7345587/113460677-d430e700-9419-11eb-9f17-381780f09de2.jpg)
has you see for kickasstorrents.to the hyphens are not removed at all.
this is the site name:
![2021-04-03_011150](https://user-images.githubusercontent.com/7345587/113460755-10644780-941a-11eb-9310-04755c8e35a1.jpg)
here's the 1337x release:
https://1337x.to/torrent/4819475/Marvels-Helstrom-S01E07-Cicatrici-ITA-ENG-1080p-HULU-WEB-DLMux-DDP5-1-H-264-MeM-mkv/

so the question, why not leaving the hyphens like kickasstorrents.to?
as you see with the hyphens sonarr recognize correctly that is a WEBDL (kickass), for the other is wrong..

**Comment by garfield69** [comment]
v0.17.838

**Comment by Bazzu85** [comment]
great! thank you!
can I buy you a beer? :D
