### ISSUE TITLE
Jackett won't start 

### ISSUE THREAD

**Issue by Hostground** [Jackett/Jackett#11457]
Hello I'm running Ubuntu 16

It is running using quickbox as manager.

Suddenly jackett locked up yesterday and won't start again.

This is what I get running the exe.

'
vinc1402/.config/Jackett
(1:511)# mono Console.exe

Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'Jackett.Common, Version=0.17.830.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'Jackett.Common, Version=0.17.830.0, Culture=neutral, PublicKeyToken=null'
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'Jackett.Common, Version=0.17.830.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'Jackett.Common, Version=0.17.830.0, Culture=neutral, PublicKeyToken=null'

**Comment by ilike2burnthing** [comment]
Can you install an older version (e.g. [v0.17.828](https://github.com/Jackett/Jackett/releases/tag/v0.17.828)) and see if it works, then try installing v0.17.830 again?

Maybe try jumping back a few versions if v0.17.828 didn't work, because there's no change to Jackett itself between those builds, just some indexers.

**Comment by garfield69** [comment]
Also check if your anti-malware app moved a Jackett module to a quarantine vault or just deleted it as part of a automatic fix.
