### ISSUE TITLE
Search problem for ilcorsaronero indexer

### ISSUE THREAD

**Issue by Bazzu85** [Jackett/Jackett#11471]
### Environment

**OS**: Windows 10

**.Net Runtime**: *

**.Net Version**: *

**Jackett Version**: Jackett Version v0.17.838

**Last Working Jackett Version**: this

**Are you using a proxy or VPN?** no

### Description

searching with some patterns doesn't return expected results.
first, see the screenshots
then, here's the 4 search: 
1. with "Greys Anatomy" -> many results
2. with "Greys Anatomy S17" -> less results excluding the correct ones
3. with "Greys Anatomy S17e" ->more appropriated results
4. with "Greys Anatomy S17e01" -> less results excluding the correct ones
the fourth search is the one used by sonarr (checked in logs) 

Can you give me a feedback? seems a search bug..
thx

### Screenshots

https://imgur.com/a/7cn6zNy

**Comment by ilike2burnthing** [comment]
Caused by:
https://github.com/Jackett/Jackett/blob/88ce1d96ab7cb9300e91a930185fee086590aa6a/src/Jackett.Common/Definitions/ilcorsaronero.yml#L64-L68

Originally added with https://github.com/Jackett/Jackett/commit/af90708faddb11aa78fd52a57d3a382dcd0d1c26 to accommodate for results using `17x01` or `S17.E01` naming format instead of `S17E01`, and `Stagione 17` instead of `S17`.

Modified with https://github.com/Jackett/Jackett/commit/aa3fa8717fcf195539c0468f02e391e689b462c2 (see description for further explanation).

It has been changed a few times since, but does the same thing. The format differences still exist, so that can't be changed, however presumably something has changed with the site itself, as searching for `Greys Anatomy 17` shows only one result `Greys Anatomy S12e15-17`, despite there being 7 results with `17` in their titles for `Greys Anatomy S17`.

I can't find any wildcards which work, but oddly any single digits following a search term seem to just be ignored, e.g. `Greys Anatomy`, Greys Anatomy 1`, and `Greys Anatomy 1 2 3 4 5 6 7 8 9` show exactly the same results. Kinda wondering if we should just remove season and episode numbers in a search altogether.

I'd prefer not to do that obviously, so let me know if you can find a better alternative on the site (not using Jackett).

**Comment by Bazzu85** [comment]
Hi, obviously downloading from the site works..
but this is out of the scope of using Jackett+Sonarr..
let me know if you can fix it!

**Comment by ilike2burnthing** [comment]
Sorry, I think you misunderstood, I'm trying find a way of searching using season and episode numbers on the site which works, so I can translate this to the indexer, otherwise we'd have to remove that ability altogether.

**Comment by Bazzu85** [comment]
ok, let me know when you are able to fix it!
thx

**Comment by ilike2burnthing** [comment]
Do you know of a way to search for season and episode numbers on the site which include those different formats? If not, it will just have to removed as an option from the indexer.

**Comment by Bazzu85** [comment]
> Do you know of a way to search for season and episode numbers on the site which include those different formats? If not, it will just have to removed as an option from the indexer.

Sorry but I don't understand the needing of the S01 to 1 substitution and S01E01 to 1 1.
I read that's for some old release maybe but in the time it's been standardized..
An option to work as actually versus using the stardard search (as done for rarbg for example) can be a solution..
Sorry if I don't understand well how re-replace is working

**Comment by ilike2burnthing** [comment]
Search `greys anatomy` and you'll see `Stagione.xx`, `SxxExx`, `Sxx.Exx`, and `XXxXX` all within the 5 months.

**Comment by Bazzu85** [comment]
> Search `greys anatomy` and you'll see `Stagione.xx`, `SxxExx`, `Sxx.Exx`, and `XXxXX` all within the 5 months.

yes,
but this cases aren't covered by this?
# normalize to SXXEYY format
        - name: re_replace # S01 E01 to S01E01
          args: ["(?i)\\bS(\\d+)\\sE(\\d+)\\b", "S$1E$2"]
        - name: re_replace # 01x01 to S01E01
          args: ["(?i)(\\d{2})x(\\d+)", "S$1E$2"]
        - name: re_replace # 1x01 to S01E01
          args: ["(?i)\\b(\\d{1})x(\\d+)", "S0$1E$2"]
        - name: re_replace # Stagione X --> S0X
          args: ["(?i)\\bStagion[ei]\\s?(\\d{1})\\b|\\bSeason'?s?\\s?(\\d{1})\\b", "S0$1$2"]
        - name: re_replace # Stagione XX --> SXX
          args: ["(?i)\\bStagion[ei]\\s?(\\d{2,})\\b|\\bSeason'?s?\\s?(\\d{2,})\\b", "S$1$2"]
        - name: re_replace # Episodio 4 to E4
          args: ["(?i)\\b(?:[\\/\\|]?Episodio\\s?(\\d+)|Puntata\\s?(\\d+))", "E$1$2"]
        - name: re_replace # Episodi 4 5 to E04-05
          args: ["(?i)\\b(?:Puntate\\s*)(\\d+)\\s?(\\d+)", "E0$1-0$2"]
        - name: re_replace # rimozioni varie
          args: ["(?i)(Serie completa|Completat?a?|in pausa)", ""]

**Comment by ilike2burnthing** [comment]
That renames the results returned by the search. The search term itself is renamed using the block mentioned in https://github.com/Jackett/Jackett/issues/11471#issuecomment-812945895, which changes `S01E02` to `1 2` in a (failed) attempt to return all possible naming variants of season 1 episode 2.

So again, if you know of a way to do this on the site, let me know, otherwise I'll have to remove the ability to search by season and episode number completely.

**Comment by Bazzu85** [comment]
> That renames the results returned by the search. The search term itself is renamed using the block mentioned in [#11471 (comment)](https://github.com/Jackett/Jackett/issues/11471#issuecomment-812945895), which changes `S01E02` to `1 2` in a (failed) attempt to return all possible naming variants of season 1 episode 2.
> 
> So again, if you know of a way to do this on the site, let me know, otherwise I'll have to remove the ability to search by season and episode number completely.

can you make an example of what you mean " a way to do this on the site"?

**Comment by ilike2burnthing** [comment]
Return both `Greys.Anatomy.S17E03` and `Greys.Anatomy.2020.S17.E03` in a single search with no irrelevant results. Same for `GreyS Anatomy S15e01-25` and `Greys.Anatomy.15x01-25`.

**Comment by Bazzu85** [comment]
> Return both `Greys.Anatomy.S17E03` and `Greys.Anatomy.2020.S17.E03` in a single search with no irrelevant results. Same for `GreyS Anatomy S15e01-25` and `Greys.Anatomy.15x01-25`.

now I understand your question..
so...IMHO there's no way to do this in a unique search..
for the first keywords the only way I see is using the pattern `grey's anatomy s17`
for the second ones no common search patterns..

maybe use 2 or more different searches and merging the results?
but is difficult to identify the right searches..
I'm starting to think that the way is searching only for the show name..

**Comment by garfield69** [comment]
v0.17.897

**Comment by Bazzu85** [comment]
great, thx...I see now that the search return many results removing the season and episode..I'll update you if sonarr now will work well with this indexer..

**Comment by albatr0ss** [comment]
You should now remove this block of code


 # remove searching by season and episode due to inconsistent naming #11471    
- name: re_replace # remove S01      
- args: ["(?i)(\\s*s\\d+)", ""]    
- name: re_replace # remove E01      
- args: ["(?i)(\\s*e\\d+)", ""]
- 

because searching "greys anatomy s17" on ilcorsaronero.link now returns all available answers.
At the moment (with this code) sonarr does not use results from ilcorsaronero.link.
If you don't know there has been a complete overhaul on the new indexer and naming convention should now be compliant.

**Comment by garfield69** [comment]
Okely Dokely.

**Comment by albatr0ss** [comment]
Can you please create a new release so that containers over at linuxserver can be updated? Thanks

**Comment by garfield69** [comment]
Next scheduled release is due out in about 20 hours or so. Patience.
This is not a significant change worthy of its own release.

**Comment by albatr0ss** [comment]
Can you please also advertise episodes and seasons?
Like     
tv-search: [q, season, ep]
otherwise sonarr will not pick up the indexer

**Comment by garfield69** [comment]
>Can you please also advertise episodes and seasons?

okely dokely.

**Comment by albatr0ss** [comment]
modified my yml file by hand inside container and can confirm everything is working as expected.
Thanks garfield69!

**Comment by Bazzu85** [comment]
> You should now remove this block of code
> 
> # remove searching by season and episode due to inconsistent naming #11471
> * name: re_replace # remove S01
> * args: ["(?i)(\s*s\d+)", ""]
> * name: re_replace # remove E01
> * args: ["(?i)(\s*e\d+)", ""]
> * 
> 
> because searching "greys anatomy s17" on ilcorsaronero.link now returns all available answers.
> At the moment (with this code) sonarr does not use results from ilcorsaronero.link.
> If you don't know there has been a complete overhaul on the new indexer and naming convention should now be compliant.

can you be more specific? what changed on the indexer?
for example grey's anatomy season 16 has release with wrong naming (es "grey's anatomy 16x")
if you're italian, can reply in italian..

**Comment by albatr0ss** [comment]
I don't know what changed on the server side when it was rebuilt. 
I don't know when you did your tests but as of today searching grey's anatomy s16 gives the following results

SerieTv | GreyS Anatomy S16e01-21 [720p Ita Eng][MirCrewRelease] 
SerieTv | Greys.Anatomy.S16E20-21.WEBMux.ITA.ENG.AC3.XviD-Prometh.. 
SerieTv | Greys.Anatomy.S16E16-19.WEBMux.ITA.ENG.AC3.XviD-Prometh.. 

The problem with sonarr was not the incorrect naming convention but the season and episodes numbers not being advertised by jackett. Sonarr without them completely discarded the indexer.

Anyway the 16x would have been normalized by the following filter:

  - name: re_replace # 1x01 to S01E01         
     args: ["(?i)\\b(\\d{1})x(\\d+)", "S0$1E$2"]

**Comment by ilike2burnthing** [comment]
Nothing has changed with the site, the naming scheme is still as inconsistent as ever, and their search still returns the same results as it always did.

`greys anatomy`
![1](https://user-images.githubusercontent.com/59480337/120723413-9ad43080-c4c9-11eb-87e1-353b18c638ba.png)
`greys anatomy s16`
![2](https://user-images.githubusercontent.com/59480337/120723501-cb1bcf00-c4c9-11eb-8adc-4c79395c0b03.png)
`greys anatomy 16`
![3](https://user-images.githubusercontent.com/59480337/120723504-cbb46580-c4c9-11eb-8c7e-ad5a83f18d16.png)

Either we attempt to fix it in the indexer (which doesn't always work as shown above), or we don't and so guarantee that not all relevant results will be returned (without the user manually doing multiple searches in Jackett). Whichever approach is used, it's not a great indexer for Sonarr.

**Comment by garfield69** [comment]
v0.18.231

**Comment by albatr0ss** [comment]
> Either we attempt to fix it in the indexer (which doesn't always work as shown above), or we don't and so guarantee that not all relevant results will be returned (without the user manually doing multiple searches in Jackett). Whichever approach is used, it's not a great indexer for Sonarr.

Cannot agree less..
Any hint for a good indexer?

**Comment by ilike2burnthing** [comment]
This seems to be all the Italian indexers currently available in Jackett - https://github.com/Jackett/Jackett/search?q=it-it

Nero is the only public one, but it's Blu brother is semi-private (needs an account, but anyone can create one at any time). It has the same inconsistent naming scheme, but at least the search works properly when the `S` from `Sxx` is stripped.
