### ISSUE TITLE
[cinematik] Login Failed, got redirected.

### ISSUE THREAD

**Issue by sz-sketch** [Jackett/Jackett#11470]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: windows10

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:  v0.17.838

**Last Working Jackett Version**: v0.17.617 (not sure)

**Are you using a proxy or VPN?** [no]

### Description

My credentials are fine; can't login to cinematik with jackett anymore since I reinstalled jackett.

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[plz check title of this msg.]

[Make sure you attach the full logs with your personal information removed in case we need more information
[jackett.txt](https://github.com/Jackett/Jackett/files/6252924/jackett.txt)
]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
No one on the team has an account for this site, so we cant independently examine this indexer for you.
@mhendu, does the indexer work for you?

@sz-sketch the log you provided includes just the stack trace and does not provide any more info other than the general error that the login failed.
The error message is Jackett's way of reporting that the login error trap that the indexer has found an error it was not expecting.
This may be due to the site having changed their login page in some way.
What will be useful is for you to switch on the **enhanced** log whose Debug and HTML may provide additional clues for the reason there was a failure.
Read https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket 
Thanks.

**Comment by sz-sketch** [comment]
[jackett 2.txt](https://github.com/Jackett/Jackett/files/6254799/jackett.2.txt)

Thanks for the swift reply !
I attached the (hopefully) enhanced log.
Best
sz

**Comment by garfield69** [comment]
Is this really all that was is in the log?
We need to see all the debug and HTML that happened BEFORE
`Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected.`
or we have no way of progressing the investigation of this issue :-(

**Comment by garfield69** [comment]
I received a direct email from a51 which came with a suggested fix for the cinematik indexer which a51 claims corrects the login problem.
while I prefer not to correspond with emails directly (as all changes to indexer should be recorded in github so they can be tracked), I have reviewed the changes and they make sense to me.
So I will submit a commit shortly.

**Comment by ilike2burnthing** [comment]
[v0.18.7](https://github.com/Jackett/Jackett/releases/tag/v0.18.7)

**Comment by sz-sketch** [comment]
Hi !

 

Thanks for the fix, tested and working great now !

 

Best

Steve

 
 

Sent: Saturday, May 08, 2021 at 9:35 PM
