### ISSUE TITLE
Identify active indexers on manual search results

### ISSUE THREAD

**Issue by costaht** [Jackett/Jackett#11489]
Sometimes when using Radarr/Sonarr you don't get all the results for your search and then we do a Manual Search using Jackett searching not only on the active indexers but all of them. 
I would like to request a feature where the results of active indexers would have a visual identification so we can see if we have any good indexer that is not active.

### Screenshots
Below are some examples of how it could look

### Different background color for active indexers
![Screenshot from 2021-04-06 23-15-37](https://user-images.githubusercontent.com/50637431/113806758-e750f900-9730-11eb-8823-173a914d0b3b.png)

### Green check for active indexers
![Screenshot from 2021-04-06 23-26-24](https://user-images.githubusercontent.com/50637431/113806759-e7e98f80-9730-11eb-9206-5040a9406c96.png)

### Active label for active indexers
![Screenshot from 2021-04-06 23-35-36](https://user-images.githubusercontent.com/50637431/113806760-e7e98f80-9730-11eb-84fe-31070b736a11.png)

Please, let me know if you have any questions.

**Comment by ilike2burnthing** [comment]
What do you mean by `active indexers`? Ones you've added to Sonarr et al?

**Comment by costaht** [comment]
On Jackett when you list all the indexers and add the ones you want, they go to your home screen as active.

**Comment by garfield69** [comment]
So ATM when you use the Jackett dashboard to search using all the indexers that you have on your **configured** page, **only** the ones that **produce results** are displayed by name in the search page in the **Tracker** column.

Any that fail to produce results will not show up in the results page.

There are two reasons for not producing results:
The first is a search-not-found, and that may simply be because what you search for is not available on the web site that the indexer is accessing.

The second is an access error, be that a network issue or a logon issue (for semi and private sites), and these generate an error message on the dashboard as well as the log.

So the addition of a tick or active tag or whatever on the search results page is redundant, because only indexers that returned results will show up in the results page, so **ALL** of those  are technically **active** as you call them and will all have the tick or active tag or whatever.

Not sure where you are going with this...

**Comment by costaht** [comment]
> that you have on your **configured** page

That's embarrassing... I thought the option "All" on the dashboard referred to all the free indexers available on Jackett db, not to (all) the active ones. 
My idea was to able to see where else I was getting search results other than my active indexers, but now I see that I misunderstood the "All" option.
I'm sorry for taking your time.
Thanks for the tool!
