### ISSUE TITLE
[TorrentHeaven] Results found, but wrong filesize, uploaddate and seeds

### ISSUE THREAD

**Issue by Winblackka** [Jackett/Jackett#11494]
**OS**: Linux

**Jackett Version**: v0.17.856

**Last Working Jackett Version**:

### Description:
If searching for a movie, it will be found, but the filesize, uploaddate and seeds are not correct.

Is it possible to fix that?

By the way if you add the Tracker there is Captcha request that is not required/not found.

**Comment by garfield69** [comment]
No one on the team has an account for this site, so we cannot independently research this for you.

Re Captcha: 
When you have used incorrect credentials, then next login attempt requires a Captcha text to be input. 
SOP is for the config to always show the captcha box, and if there is no image then the user is expected to just leave the Captcha text input box empty. 

Re incorrect search result columns:
IF you want us to take a look at this then use your Browser to access the web sites torrent search page and post a HTML dump of that page here.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source

**Comment by Winblackka** [comment]
Thx for the quick response. :)
And thx for the ReCaptcha explanation.

Here is the torrent-search dump:
[index.txt](https://github.com/Jackett/Jackett/files/6277727/index.txt)

**Comment by garfield69** [comment]
It does appear that the HTML for the search results has changed from what the indexer is expecting.
I shall have a go at adjusting the selectors for the C# indexer and see what happens.

**Comment by garfield69** [comment]
The date processing appears at first glace to be correct.
It picks up `Heute 00:13`, `Gestern 22:33` and `06.04.2021 21:03`, parses it through DateTimeUtil.FromUnknown(dateStr) and applies GMT+01:00 offset to it to return a local timezone.
I'm going to leave this as is.

**Comment by ilike2burnthing** [comment]
[v0.17.865](https://github.com/Jackett/Jackett/releases/tag/v0.17.865)

**Comment by garfield69** [comment]
Since this is obviously untested, please post feedback to confirm all is well or if further corrections are required.

**Comment by Winblackka** [comment]
Thx for your work. The filezises and the number of peers are correct now. Just the published time ist still not right.

**Comment by garfield69** [comment]
Please go into more detail about the date.... what do you see, what were you expecting to see?

**Comment by Winblackka** [comment]
Okay, have a look at the screenshot:

The published time is the time for "the last activity" on the tracker, not the date/time when the torrent was added to the tracker.

Thx again and i hope you understand what im talking about. :)
![time](https://user-images.githubusercontent.com/61755926/114164902-226b4c00-992c-11eb-8703-25943de41681.png)

**Comment by garfield69** [comment]
TorrentHeaven: the search results row contains just the one date.
If this happens to be the last-activity date instead of the publish date then there is nothing we can do about it.
I presume you are seeing those two different dates on the torrent details page?
We are not going to fetch every torrents details page just to get the publish date, as this would generate up to 100 additional http GET requests, one for each result on the search page rows, and this additional traffic could cause the web site to ban you as a spammer or DDoS attacker.

FantasticHeaven: the parse-error.txt log snippet you posted is for a different web site.
Open a new ticket if you want this error looked at, and I can take a look.
In the new ticket also include a full **enhanced** log of a search at the site, so that the HTML of the error and the HTML of the full search page are included.
This way I can add new categories to the indexer and look over the category detection in the indexer to check it is working.
