### ISSUE TITLE
[iptorrents] Not all season packs showing

### ISSUE THREAD

**Issue by TheFlath** [Jackett/Jackett#11532]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

Ubuntu 18.04.5 LTS

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

Version v0.17.876 - docker

**Last Working Jackett Version**:

Unknown

**Are you using a proxy or VPN?** [yes/no]

No

### Description

I noticed a lack of results in sonarr for season packs for some shows recently, soni decided to go direct to the tracker to see if there really was just few results for my queries lately. Negative, way more results searching the tracker directly.

Discovered that it was jacket that was simply not finding these results by searching for the series on jacket. The show I've been using to test this is NEW GIRL. The tracker in question (not sure if I'm allowed to specify) has multiple season packs for nearly every one of the 7 seasons. However jacket is only finding the series pack, and is only returning 50 results total.

### Logged Error Messages

 https://file.io/PE3mV4SmZcKH

]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
which indexer is not performing as you expect?

**Comment by TheFlath** [comment]
IPT

**Comment by garfield69** [comment]
I don't have an active account on iptorrents so I cant research this.
But looking at past tickets this site has been problematic with search season results #932 #1467 #1907 #8102
Open ticket #8107 is likely the most relevant atm.
This indexer is written in C# so I am not getting involved further in this, I mostly support the yaml indexers only.

**Comment by element4l** [comment]
I would be willing to hand out an invite to someone who promises to work on this.

**Comment by seeyabye** [comment]
The only way to have all season packs shown is by going through all pages returned by iptorrents via pagination, but https://github.com/Jackett/Jackett/pull/11900 PR was rejected, so I don't think there's a solution to this issue.

Have you tried increasing the total number of torrents return to 100 in IPTorrents? As @garfield69 has pointed out, 100 torrents should be sufficient, or otherwise, you will need to refine your search keywords. Sonarr by default only accepts 100 results returned from Jackett.

Related issues: https://github.com/Jackett/Jackett/issues/975 https://github.com/Jackett/Jackett/issues/250
