### ISSUE TITLE
[eztv] Exception (eztv):  Received an unexpected EOF or 0 bytes from the transport stream.: The SSL connection could not be established, see inner exception. (Test)

### ISSUE THREAD

**Issue by Dativebond** [Jackett/Jackett#11544]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
the indexer works for me so that suggests the problem is at your end.
check if other public indexers are working. 
If it is just eztv that is not working, then you are likely being blocked by your ISP or security app.
edit the config and try the alternate sitelinks until you find one that works.
If all indexers are not working then you have a bigger problem.
