### ISSUE TITLE
[req] Nordic+ https://nordicplus.org/ Danish Private

### ISSUE THREAD

**Issue by mplys3** [Jackett/Jackett#11542]
Hey You amazing guys!

Could you add support for the new danish tracker Nordic+ that would be so great!

Thanks in advance!

https://nordicplus.org/

**Comment by garfield69** [comment]
engine: unit3d

**Comment by garfield69** [comment]
Registration is by invite or by application, which requires a protonmail account and scene history.

Since I only add indexers to Jackett and do not contribute to the scene I have no history to apply with and certainly do not have the time to keep close to 400 sites all happy with my upload and forum activity.

With this in mind, if you send an invite to garfieldsixtynine -at- gmail.com I will build a cardigann indexer.
Otherwise wait for some other volunteer to contribute.

**Comment by KHoegh93** [comment]
> Registration is by invite or by application, which requires a protonmail account and scene history.
> 
> Since I only add indexers to Jackett and do not contribute to the scene I have no history to apply with and certainly do not have the time to keep close to 400 sites all happy with my upload and forum activity.
> 
> With this in mind, if you send an invite to garfieldsixtynine -at- gmail.com I will build a cardigann indexer.
> Otherwise wait for some other volunteer to contribute.

Im on the site - but i dont have an invite.. Is it possible to help you with the information you need without? :)

**Comment by garfield69** [comment]
Since this site appears to be powered by a unit3d engine, then assuming that they have not customised their site too far from the standard build, I should be able to get most of the work done if you provide a HTML dump of the torrent search page.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source for details.

Also visit the Rules and FAQ pages (the download or hit&run sections) to determine what their minimum ratio is (such as keep your ratio to 1:1, or, if you go below a ratio of 0.5 you cant download, etc.), as well as their minimum seed time once downloads are complete (after downloading seed for a minimum of 1 day, 36 hours, 96h or whatever).

**Comment by KHoegh93** [comment]
> Since this site appears to be powered by a unit3d engine, then assuming that they have not customised their site too far from the standard build, I should be able to get most of the work done if you provide a HTML dump of the torrent search page.
> See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source for details.
> 
> Also visit the Rules and FAQ pages (the download or hit&run sections) to determine what their minimum ratio is (such as keep your ratio to 1:1, or, if you go below a ratio of 0.5 you cant download, etc.), as well as their minimum seed time once downloads are complete (after downloading seed for a minimum of 1 day, 36 hours, 96h or whatever).

I have sent you an email :)

**Comment by garfield69** [comment]
v0.17.897

**Comment by garfield69** [comment]
FYI I received an invite for this site today, registration and login successful.
Don't know how long it will last but I can at least complete my independent checks and refine the indexer while the account lasts. :-)

**Comment by garfield69** [comment]
v0.17.907

**Comment by KHoegh93** [comment]
> FYI I received an invite for this site today, registration and login successful.
> Don't know how long it will last but I can at least complete my independent checks and refine the indexer while the account lasts. :-)

Very good! Nice to know that they've sent you the invite. :)

And thanks for you're work!

**Comment by KHoegh93** [comment]
> v0.17.907

I think something messed up.. I've noticed after the update, that when i grabs a release it downloads a .meta file, and not, which dosent do anything.. Its just "hanging" in my DL client.? :(

**Comment by garfield69** [comment]
Nothing is messed up.
are you talking about using the magnet link?
I notice that the magnet links provided by the site have their parameters in a slightly different order than usual, and also uses some valid but uncommon parms.
typical magnet example:
`magnet:?xt=urn:btih:hashinfohashinfo&dn=title-of-the-download&tr=trackerannounce`
nordic+ magnet example:
`magnet:?dn=title-of-the-download&xt=urn:btih:hashinfohashinfo&as=https://nordicplus.org/torrent/download/hashinfohasshinfo&tr=https://nordicplus.org/announce/passkeypasskey&xl=665770889`
Could it be that your DL client is not capable of handling this magnet?
OR 
maybe its just a case of that file not having any seeders, or seeders that are not contactable, so the magnet metafile is not resolved into a torrent that can continue to download.
This is common, a torrent client cannot resolve a magnet metafile until 1 seeders is contacted and responds. 
In either case, if you use the download link instead of the magnet, then you would get the .torrent file, albeit that will still not start downloading is no seeders are connected.

**Comment by KHoegh93** [comment]
> Nothing is messed up.
> are you talking about using the magnet link?
> I notice that the magnet links provided by the site have their parameters in a slightly different order than usual, and also uses some valid but uncommon parms.
> typical magnet example:
> `magnet:?xt=urn:btih:hashinfohashinfo&dn=title-of-the-download&tr=trackerannounce`
> nordic+ magnet example:
> `magnet:?dn=title-of-the-download&xt=urn:btih:hashinfohashinfo&as=https://nordicplus.org/torrent/download/hashinfohasshinfo&tr=https://nordicplus.org/announce/passkeypasskey&xl=665770889`
> Could it be that your DL client is not capable of handling this magnet?
> OR
> maybe its just a case of that file not having any seeders, or seeders that are not contactable, so the magnet metafile is not resolved into a torrent that can continue to download.
> This is common, a torrent client cannot resolve a magnet metafile until 1 seeders is contacted and responds.
> In either case, if you use the download link instead of the magnet, then you would get the .torrent file, albeit that will still not start downloading is no seeders are connected.

Oh well.. It may be my DL client that fails.. Thats weird.. Im using a seedbox with rutorrent. I just tried to copy the magnet link directly from nordicplus, into rutorrent. And same problem.. Just trying to download that "meta" file. (there is seeders on the torrent) 

But is it possible to force it to not use .magnet link? (i guess it didnt do that before you updated? Or i may be wrong :) )

**Comment by garfield69** [comment]
>But is it possible to force it to not use .magnet link?

if you look at the Jackett dashboard search results using the nordic+ indexer, there should be 
 two link icons for every title.
One is a magnet icon, the other is a download icon.
The download icon uses `a[href*="/download/"]` and the magnet icon uses `a[href^="magnet:?"]`

if both buttons return a magnet then that is what the nordic+ web site is providing.
You can confirm this on the web site itself to crosscheck, just look at the web site search results, and on each row there should be a download button, and to its right a black on black button that provides the magnet.

**Comment by KHoegh93** [comment]
> I just tested both buttons on the dashboard search result on an ebook, and my uTorrent gets a .torrent for the download icon, and a magnet for the magnet icon.
> are you getting something different? I don't understand.

Well im using jackett together with sonarr/radarr... So im not downloading directly through jackett interface.. 

Just tested in jackett interface too, and no problems. So sonarr/radarr must be the problem :(

**Comment by garfield69** [comment]
is Sonarr favouring a magnet over a .torrent when Jackett provides both links in its results?
is there perhaps an indexer option to select a preference?

I can remove the magnet if that is the only way you are going to get your rutorrent to work,  but I am sure down the line someone is going to ask for the magnet back at some point.

I suppose I could add an option in the config settings to let the user choose to have one or the other, but it would mean that only one link would ever be available at any one time for all titles.

I'll try to make time tomorrow to update the config and see if that will work out better, but if you find a sonarr setting let me know so I don't waste my time ;-)

**Comment by garfield69** [comment]
v0.17.938

**Comment by garfield69** [comment]
https://nordicplus.org/ returning ERR_CONNECTION_REFUSED
and via VPN its returning ERR_CONNECTION_RESET

Just me or is the site broken, gone, or moved to a new domain?

**Comment by garfield69** [comment]
domain now presenting
```
Welcome to nordic+!
We are changing servers, but the tracker will be up again soon!
We apologize for the downtime, and thank you for your patience.
```

**Comment by ilike2burnthing** [comment]
Login page is back up, but I don't have an account to check anything beyond that, and their cert is still invalid.

**Comment by garfield69** [comment]
![image](https://user-images.githubusercontent.com/6933240/119025323-247afd00-b9f8-11eb-94ab-51cde8d6e973.png)

**Comment by garfield69** [comment]
domain now just presenting `Site Down`
If its not up in another 8 days we can remove it and add it back later if it ever recovers.

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://nordicplus.org/ returning ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
@KHoegh93  are you aware of the status of the nordic+ site, has it gone, or moved to a new domain?
If we don't get any news within the next 7 days we will remove the indexer.
In the event it goes back online after that we can always add it back again.

**Comment by KHoegh93** [comment]
> @KHoegh93 are you aware of the status of the nordic+ site, has it gone, or moved to a new domain?
> If we don't get any news within the next 7 days we will remove the indexer.
> In the event it goes back online after that we can always add it back again.

Site has closed down :(

**Comment by garfield69** [comment]
v0.18.656
