### ISSUE TITLE
[rarbg] detect and apply the torznab limit parameter

### ISSUE THREAD

**Issue by cnstephen** [Jackett/Jackett#11605]
127.0.0.1:9117/api/v2.0/indexers/all/results?apikey=***&Query=web-dl&Category%5B%5D=100044&Tracker%5B%5D=rarbg
This link displays 100 data, what parameters are used to limit the display to 10？
thank you

**Comment by garfield69** [comment]
The `&limit=` parm is supposed to limit the returned results up to the number specified
However in reality, this is totally dependent on the implementation of the indexer for the corresponding web site.
Some indexers check the limit and apply it, others have it hard coded and some ignore it.
RARBG for instance appears to have it hardcoded to 100.
Why is this the case? IDK

**Comment by cnstephen** [comment]
> The `&limit=` parm is supposed to limit the returned results up to the number specified
> However in reality, this is totally dependent on the implementation of the indexer for the corresponding web site.
> Some indexers check the limit and apply it, others have it hard coded and some ignore it.
> RARBG for instance appears to have it hardcoded to 100.
> Why is this the case? IDK

I tried it and it didn't work

**Comment by garfield69** [comment]
>Is there a way to solve？

Only by having a C# dev volunteer to fix the indexer to detect the limit parm and apply it.

**Comment by PNWebster** [comment]
I did some testing to see if I can fix this issue.

@garfield69 You are right that the RARBG indexer has a default limit of 100 for query to RARBG. But Jackett will limit the results afterwards, so specifying a limit of 1 in torznab query will fetch 100 from RARBG but only return 1 result from Jackett.

In my case, when I only have rarbg indexer:
/indexers/all/results/torznab/?apikey=key&q=tenet**&limit=1** -> returns 1 results
/indexers/all/results/torznab/?apikey=key&q=tenet**&limit=2** -> returns 2 results

Also when I have multiple indexers (rarbg & 1337x), limit on my query is correctly applied.

@cnstephen can you retest, perhaps with some example URLs of what you are trying?

**Comment by mikeoscar2006** [comment]
@garfield69 Most indexers have just ignored the limit and @PNWebster is right; if the limit applies eventually then maybe there is no need itself for individual indexers to resolve the limit parameter. The only reason to do that would be to reduce load which shouldn't be that much for 100 results.
If you think it would help, it can be implemented easily otherwise this issue can be closed.

**Comment by garfield69** [comment]
The issue is not so much when the limit is less that what the indexer normally returns, but when the limit is higher.
Then we have the situation where, say, the limit requested is 200, but the indexer only fetches the first page of results and provides a maximum of 100.
to properly implement this would require all the indexer to be capable of fetching as many pages as it takes to fulfil the limit request, which is not straight forward and is a huge undertaking.
I believe there are open tickets open since the dawn of Jackett covering this topic.

**Comment by mikeoscar2006** [comment]
True. Pagination can cause a lot of problems and it needs proper discussion before implementing probably on a dedicated issue. Well, would be happy to contribute whenever it happens :)

**Comment by B1773rm4n** [comment]
We have two cases here:

1. returned results > limit variable
2. returned results < limit variable

About case 1:
If the returned results are more than we want due to our limit variable then
why we don't force the indexer implementation to follow this? Options don't have any meaning if I can't rely that they won't be applied. I would recommend implement a logic to enforcement here.

About case 2:
If the returned results are less than we want due to our limit variable then
it is more complicated. I understand it is a mix between how many results are returned per page (which often can be set on the user settings of the tracker, I tested this by myself) or if it needs several pages then we have a pagination issue. I understand that this is more work but Jackett should offer a way how to implement that in a good way.
The two factors I'm seeing here are:

- Trying to not spam the tracker with requests
-  Give the user the ability to receive a full list for his query
 
And both are somewhat opposing to each other. Lets use three examples:

1. Scenario:
I want to get all current freeleech torrents. The result varies hugely on the tracker. Let's say my tracker just have **110 freeleeches** available right now. Default results per page are 25. In the tracker settings I can enable a maximum of **100 results** per page. So I need a second page in every case. So in the best case we are having 2 requests here. But if I decide to get all torrents then we are having 110 requests anyway.

Result: The pagination is for sure no bombing. This can be accepted

2. Scenario:
Same scenario but with just **1 result** per page in the settings (evil spirited example). So I would have **110 requests** just for the results. 

Result: I would consider that as malicious regarding the user and the tracker (if they mind) should consider the user as the issue - not Jackett. So I would still accept this scenario or implement a way to set the results per page returned to the allowed maximum (additional implementation effort)

3. Scenario:
A more realistic situation would be that I want a full list of all results from one tag. Let's say we will have **50k torrents** as result. Let's take the default **25 results** per page. That would be **2k pages** within a short amount of time.

Solution: This put stress on the client (who does the requests) and the tracker. Not even think if we enable the client to download **50k torrents** as a result then. In this case the user may even be unaware about how intense the result of his actions are. So we should at least give him a way to inform him of this case.
Or we implement some kind of **rate limiting** for big requests. But this  would run into all kind of timeout issues and angered users. Not a big fan of this solution.
I could imagine implementing an **expert/power user mode**. Setting a flag in the settings with a small explainer would enable the functionality to send a big amount of requests. So via default it would not be possible to do mistakes like this. If they will do their research or asking about how to do it we can link them to the expert mode.
