### ISSUE TITLE
Jackett is not yielding results from Sonarr search string for missing season

### ISSUE THREAD

**Issue by desimaniac** [Jackett/Jackett#1164]
Sonarr is sending a specific request when searching for a missing season (`This+is+Us&season=1`) that is not yielding any results by Jackett (for EZTV and Limetorrent).

To experiment, I did some manual searches on Jackett and my results are below...

Search strings that **did not** yielded 0 or few results:
- `This+is+Us&season=1`
- `This+is+Us+s01`
- `This is Us s01`
- `This+is+Us`
- `This%20is&20Us`

The only string that **did** work like it should was: `This is Us` (no `+` or `&20` in between)

So I wanted to know if it would be possible to intercept the string Sonarr is sending (`This+is+Us&season=1`) and convert it to  `This is us` automatically on Jackett's side since that is the most compatible string amongst the trackers I test. 

PS. I opened up a forum issue with Sonarr and posted relevant screenshots that indicate my findings above. Their response is that they can not modify the query themselves because they use the same string across all Torznab apps and perhaps modifying it would break searches for them, indicating this would need to be done on Jackett's side instead ([link to post on Sonarr forums](https://forums.sonarr.tv/t/sonar-is-looking-for-season-pack-eg-s01-instead-of-individual-episodes-for-newly-added-show/14046/7)). 

-------------------------------

Jackett Version 0.7.1146.0
Mono version (if not using Windows):  4.6.2

-------------------------------

**Comment by kaso17** [comment]
+ and %20 are ways to encode spaces in URLs. Can you please post a complete query URL from the jackett or sonarr logs?
http://127.0.0.1:9117/torznab/limetorrents?apikey=xxx&cat=5040,5030&q=This+is+Us&season=1 returns 1 result for me.

The problem seems to be with EZTV/limetorrents.

The resulting URLs from which the results are parsed are these:
https://eztv.ag/search/This%20is%20Us%20S01
https://www.limetorrents.cc/search/all/This%20is%20Us%20S01/

They seem to match on word boundaries (e.g. searching for S01 won't return single episodes, only packs).

EZTV returns unrelated results if there's no match at all (they don't have a season pack).
Limetorrent returns the pack but not the corresponding single episodes.

Do you know any search modifiers/wildcards for EZTV/limetorrents to return e.g. all S01 episodes?

Another question would be the behavior of sonarr. If it's searching for S01, would it download single episodes or does it look only for packs?

For EZTV I've added 71e0ec9ced3e279c6fb5951b48e18463111ce015 to strip SXX tags without episode which should be a suitable workaround as they don't have season packs at all (correct me if I'm wrong).

**Comment by Taloth** [comment]
afaik, Sonarr does use %20 not + (but an url parser should handle both cases transparently). I posted the example query string to emphasis to @desimaniac that sonarr queries by queryparams for the season, and not as part of the title string, and as such isn't involved in generating the search string used for individual sites.

**Comment by desimaniac** [comment]
@kaso17 http://hybridoneconstruction.synology.me:9118/torznab/limetorrents/api?t=tvsearch&cat=5030,5040&extended=1&apikey=xxx&offset=0&limit=100&q=This Is Us 
is returning all episodes available to me. I tried to modify Sonarr to send the tv show name without + or &20, but Sonarr is giving validation errors even though Jackett finds results.

**Comment by kaso17** [comment]
The + and %20 is not your problem, these are just different ways of encoding spaces in URLs.

These URLs will all work and return the same results:
```
http://127.0.0.1:9117/torznab/limetorrents/api?t=tvsearch&cat=5030,5040&extended=1&apikey=xxx&offset=0&limit=100&q=This%20Is%20Us
http://127.0.0.1:9117/torznab/limetorrents/api?t=tvsearch&cat=5030,5040&extended=1&apikey=xxx&offset=0&limit=100&q=This+Is+Us
http://127.0.0.1:9117/torznab/limetorrents/api?t=tvsearch&cat=5030,5040&extended=1&apikey=xxx&offset=0&limit=100&q=This Is Us
```

**Comment by desimaniac** [comment]
Ok. Then it's the S01 or Season1 part that is doing it then.

**Comment by kaso17** [comment]
Yes, see these examples:
https://www.limetorrents.cc/search/all/This%20is%20Us%20S01/
https://eztv.ag/search/This%20is%20Us%20S01
@desimaniac: are you aware of any way to get all season 1 results (season packs and single episodes) using the search on https://www.limetorrents.cc?

**Comment by kaso17** [comment]
@Taloth: do you know how sonarr behaves if a search for a season without episode returns single episodes? Will it download the individual episodes or only packs?

**Comment by desimaniac** [comment]
@kaso17 Cant figure it out a way to do so without having to do every episode (eg s01e01 s02e02 etc)

**Comment by Taloth** [comment]
@kaso17 "&season=1" means "any episode in that season or season pack", so yes. It's expected behavior that the indexer returns season packs and all individual episode releases (including possible S01E01E02 doubles).
Mind you, in newznab (and by extension torznab) this is supposed to be a simple "AND season = 1" in the database backend, fast and easy.... if an site as actually a proper indexer.

**Comment by desimaniac** [comment]
@Taloth So basically individual episodes such as "sXXe01, sxxe02, sxxe03, etc" are triggered by "AND season=1"... 

@kaso17 Can that be hardcoded in to do those individual searches automatically?

**Comment by desimaniac** [comment]
@kaso17 The EZTV update worked! Can we do something similar for LimeTorrents? Just search the name without the SXXEXX format for season searches?

**Comment by kaso17** [comment]
thank you

**Comment by desimaniac** [comment]
No, thank you!
