### ISSUE TITLE
[cpasbien] Exception (cpasbien): Name or service not known: Name or service not known (www2.cpasbien-fr.fr:443) (Test)

### ISSUE THREAD

**Issue by Whisper40** [Jackett/Jackett#11784]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
Hi @Whisper40,

You've created an issue, but haven't provided any details to allow the community to assist you. To prevent issue tracker clutter, this issue will now be closed. Please provide the information needed below and your comment will automatically re-open this issue.

Environment
OS:

.Net Runtime: [.Net-Core/.Net-Framework/Mono]

.Net Version:

Jackett Version:

Last Working Jackett Version:

Are you using a proxy or VPN? [yes/no]

Description
[List steps to reproduce the error and details on what happens and what you expected to happen]

Logged Error Messages
[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

Screenshots
[Place any screenshots of the issue here if needed]

**Comment by Whisper40** [comment]
Os : Docker
Jackett Version v0.18.100
It's not the only tracker to do not work, Torrent 9 too ( url works, but jackett wont connect )
( yes i have flaresolverr)
![image](https://user-images.githubusercontent.com/30440458/119238472-bd1d9400-bb42-11eb-8389-97d38ae316ed.png)
![image](https://user-images.githubusercontent.com/30440458/119238491-d1fa2780-bb42-11eb-8c26-ebbd9afe4ef1.png)

**Comment by garfield69** [comment]
https://cpasbien.to/ and https://torrent9.to/ work in my win10 Jackett indexers OK.
It looks like the docker image is not getting access to your DNS, or the DNS defined on your computer/router is not working, or your ISP is blocking your access to these sites.

https://www.cpasbien.sh/ is a different clone run by a different supplier, it does not use the same web site engine despite the skin looking similar. that is why the indexer does not work there.

Have you tried rebooting your machine?
Do you have DNS set for your container? If so, what? Have you tried others?

**Comment by Whisper40** [comment]
I recreated my container with dns: 1.1.1.1
Tested curl into container : Working 
![image](https://user-images.githubusercontent.com/30440458/119238878-a6c50780-bb45-11eb-8501-0041c8cb9711.png)
But cannot make it works 
![image](https://user-images.githubusercontent.com/30440458/119238897-bcd2c800-bb45-11eb-92c3-2b2bf8ece4bb.png)

**Comment by Whisper40** [comment]
Oh yes you are right, the url that you gave me works..
Yes ok it's a different system
