### ISSUE TITLE
[rutracker] Пожалуйста, введите код подтверждения (символы, изображенные на картинке) (Config)

### ISSUE THREAD

**Issue by carponoid** [Jackett/Jackett#11867]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
The Russian error message Google translates into
```
Please enter the confirmation code (the symbols shown in the picture
```

It appears that you need to edit your RuTracker indexer config and fill in the challenge text.
The config should show you an image with some text/number code that you need to enter.
If you get it wrong, you need to close the config and open a fresh one as the challenge is not refreshed in failure.
If you are not seeing an image in the config but are still getting this error then provide a full enhanced log so we can see if the site has changed the image link and if we need to updat ethe indexer code. See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by carponoid** [comment]
I did actually enter the captcha code on the config page but still it throws error.

I have attached enhanced logs along with short clip showing the error in the link below

 

https://1drv.ms/u/s!AjzCEXkME_NpiaFR4jy7KLhHb-FhTg?e=PzDW00

**Comment by garfield69** [comment]
I have tested adding Rutracker using the captcha and the indexer works for me.
The config only loads the captcha image once. If you make a mistake filling in the code, or used the wrong password or username, then you have to close the config and start again so that you can load the new captcha image for the next login attempt.
I see in your video that you tried several times using the same open config.
Once you get an error you cannot reuse that config attempt.


Here is another method.
1. use your browser to login to Rutracker and fill in the captcha challenge on the browser and complete to login to the web site.
2. now add the RuTracker to Jackett, and the config should not show you an image. So clear(delete) the challenge text and replace the username and password with the same ones you used to login to the web site and see if that works for you.
