### ISSUE TITLE
Obscure.wtf indexer request

### ISSUE THREAD

**Issue by element4l** [Jackett/Jackett#11911]
Any chance of getting an indexer for obscure.wtf? 

Or better yet, any way to manually create an indexer?

**Comment by garfield69** [comment]
this is a Private site requiring an invitiation.
If you send an invite to garfieldsixtynine -at- gmail.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

Alternative you can write your own indexer, see https://github.com/Jackett/Jackett/wiki/Definition-format for the syntax, and look at examples of exisitng private indexers in https://github.com/Jackett/Jackett/tree/master/src/Jackett.Common/Definitions
It can be useful to find a matching engine so you can use a similar indexer as a template.

**Comment by garfield69** [comment]
registration and login successful. Thank you.

**Comment by garfield69** [comment]
v0.18.367

**Comment by garfield69** [comment]
https://www.obscure.wtf/ returning ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
https://www.obscure.wtf/ still returning ERR_CONNECTION_TIMED_OUT
just me, or is the site broken, gone or moved to a new domain?

**Comment by garfield69** [comment]
v0.18.599
