### ISSUE TITLE
Manual search finds releases whereas sonarr does not

### ISSUE THREAD

**Issue by Jalsemgeest** [Jackett/Jackett#11991]
Hello,

I have Sonarr configured to use Jackett with a PrivateHD. I've found that when I manually search for a show within PrivateHD or within Jackett's manual search option I can find releases fine, however when I search from Sonarr there are no results.

When I check the logs for this I see that the manual search indeed has the results but the Torznab search results in 0 releases.

It seems odd that the search is failing when Jackett is called from Sonarr, but succeeding otherwise.

I'll happily provide logs as needed.

**Comment by garfield69** [comment]
Check your sonarr indexer and ensure that it has all the categories defined, not just the TV ones, but the movies ones as well.
Be sure to add all of these to your sonarr indexer so that sonarr does not filter out results when it makes a query to Jackett
![image](https://user-images.githubusercontent.com/6933240/124545062-737fd300-de7c-11eb-9b34-d5bbdb281c1a.png)

**Comment by Jalsemgeest** [comment]
Okay, this actually fixed it. Apologies for the waste of time.

It's worth noting that the reason that it was not working (which doesn't make sense to me) was because I would select the categories after testing the connection. This would then limit the possible categories to the ones that Jackett supported - which makes sense. However, what I did this time was during setup in Sonarr, I selected all of the options from categories, then I input my Jackett config (url, api key, etc). That configuration worked, not sure why, but it did.
