### ISSUE TITLE
[Question] RARBG doesnt update the json result from yesterday 7/12 

### ISSUE THREAD

**Issue by foremtehan** [Jackett/Jackett#12027]
Anyone has the same issue ? RARBG doesnt update the json anymore , the last result is yesteday:

TV Category:

![image](https://user-images.githubusercontent.com/53290883/125429214-42b57cad-bc15-4f15-b480-6d4e55209e62.png)

endpoint:

https://torrentapi.org/pubapi_v2.php?format=json_extended&app_id=jackett_v0.16.23.0&category=18;41&token=TOKEN

**Comment by garfield69** [comment]
yes this can happen occasionally where the rarbg api server does not deliver new stuff for several days in a row.
I also am seeing the same entry as you for the latest fetch from the rarbg api, and I know its not the jackett cache redelivering old stuff because I run with the cache turned off.
we just have to hope the rarbg api servers gets a kick and catches up with the data from the web site, the same as has happened several times in the past.

**Comment by mkolassa** [comment]
I've sent an email to support about it.
