### ISSUE TITLE
Migrate Jackett Install from Windows to UnRAID Docker (Linux)

### ISSUE THREAD

**Issue by jeff15110168** [Jackett/Jackett#12075]
**OS**: Windows 10
**Jackett Version**: v0.18.475

I am in the process of moving over all my media server from Windows to Unraid. I installed the sonarr / radarr dockers and was able to move over the database files and now all that's left is the Jackett installation on WIndows. Does anyone know the step by step for me to move this into my Unraid Docker so my Sonarr/Radarr will pick back up all my previously setup trackers?

**Comment by garfield69** [comment]
there are no prepared notes for this, its not a common activity.
try this:
install your jackett docker
then shutdown the jackett service so you can port over the following:
copy the `C:\ProgramData\Jackett\Indexers` folder and the `C:\ProgramData\Jackett\ServerConfig.json` file over to the corresponding docker `/config` volume location
this will have your jackett server api key and dashboard settings, and all the active indexer json config files.

however, the caveat is that you cannot carry over the dataprotection keys as they are encrypted with a platform specific method.
So startup your docker jackett, access the jackett dashboard, and for any private or semi-private indexers you will need to re-enter the passwords and save in order for them to be encrypted/decrypted on your unraid.
Also, any indexer that uses cookies will need new ones fetched and saved since they will also likely not be accepted by the corresponding web sites. see https://github.com/Jackett/Jackett/wiki/TroubleShooting#your-cookie-did-not-work

I think that is about it, @ilike2burnthing  any additional notes you can contribute? Have I left anything out?

**Comment by ilike2burnthing** [comment]
No, that should cover it. Cookies will be hit and miss, some will be fine, others won't, though so long as your IP address stays the same, it will be more hits than misses.

**Comment by jeff15110168** [comment]
Ah thank you guys - i just copied over those two directories. the two private trackers when i hit "test" seem to be working so does that imply everything is mostly good to go?

I noticed some trackers like RARBG / ETTV / 1337x aren't working but maybe it takes a bit of time for them to refresh to work.

**Comment by garfield69** [comment]
test each indexer individually. if they pass then good. if they fail, then edit the config, and try an alternate sitelink if available or refresh credentials and captcha codes if applicable.
some public sites are using clouddlare HCapcha challenge, so they will fail.
Others may be using the regular cloudflare ddos check, you may need to install the flaresolverr docker and config jackett to use it.

**Comment by jeff15110168** [comment]
> test each indexer individually. if they pass then good. if they fail, then edit the config, and try an alternate sitelink if available or refresh credentials and captcha codes if applicable.
> some public sites are using clouddlare HCapcha challenge, so they will fail.
> Others may be using the regular cloudflare ddos check, you may need to install the flaresolverr docker and config jackett to use it.

I ended up getting most to work but there's a few that I'm having trouble with Flaresolverr to get working. Any idea how to fix the below error? Logs in Flaresolver itself show that it seems to be working.

`Exception (1337x): The cookies provided by FlareSolverr are not valid: The cookies provided by FlareSolverr are not valid`

```
2021-07-27T22:49:27-04:00 INFO FlareSolverr v1.2.8
2021-07-27T22:49:27-04:00 INFO Listening on http://0.0.0.0:8191
2021-07-27T22:49:36-04:00 INFO REQ-1 Incoming request: POST /v1
2021-07-27T22:49:36-04:00 INFO REQ-1 Params: {"maxTimeout":60000,"cmd":"request.get","url":"https://www.1337x.to/cat/Movies/time/desc/1/","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"}
2021-07-27T22:49:39-04:00 INFO REQ-1 Cloudflare detected
2021-07-27T22:49:40-04:00 INFO REQ-1 Challenge solved.
2021-07-27T22:49:40-04:00 INFO REQ-1 Response in 3.81 s
```

**Comment by ilike2burnthing** [comment]
If Jackett and FlareSolverr share the same IP address (i.e. you're not using a VPN), then try disabling IPv6 for both Jackett and FlareSolverr - https://github.com/Jackett/Jackett/wiki/TroubleShooting#your-cookie-did-not-work (see the last bullet point of the Notes section)
