### ISSUE TITLE
[BeyondHD] search by imdbid

### ISSUE THREAD

**Issue by c2af5c5f28e38384295f2fc2af** [Jackett/Jackett#1208]
Currently the BeyondHD indexer doesn't appear to support searching via imdbid. IMDB URL's are required for every upload on BeyondHD, so if searching via imdbid (or IMDB URL) is possible, it's guaranteed to return results if any uploads exist. This is especially important when using services like Sonarr or Radarr, where currently the search string is often too long or unique to return any results, e.g. "rogue one star wars story 2016".

The [x264 indexer appears to search by imdbid and falls back to a search string if no imdbid is found](https://github.com/Jackett/Jackett/blob/master/src/Jackett/Indexers/x264.cs#L123); is it possible to get similar functionality with BeyondHD?

I'm guessing there's already a reason Jackett doesn't support this, but on the off chance there's not, I'd really love to see it implemented.

Jackett version:  0.7.1197.0
Mono version (if not using Windows):  4.8.0

**Comment by RoloSoze** [comment]
@c2af5c5f28e38384295f2fc2af While BeyondHD does require every uploader to enter the IMDb link in the description part of the upload, this is not strictly enforced. Many uploads on BeyondHD do not include the corresponding IMDb ID.

For example, search BeyondHD for the movie The Borune Identity using the title and using its IMDb ID (tt0258463). The first returns 3 results, the 2nd returns only 1. This is only one of many examples of how the IMDb ID search on BHD isn't accurate since he rule isn't enforced. 

I suppose Jackett can support searching BHD using IMDb ID, but do not expect complete results.

**Comment by c2af5c5f28e38384295f2fc2af** [comment]
@RoloSoze In that example, searching by title may return 3 results but those 3 results aren't guaranteed to be the right movie, whereas the 1 result via imdbid is. While it's a bummer the imdb url's aren't as enforced as they should be and that can affect search results, I think it might be more important to ensure accurate results. 

Currently you can simply search for whatever string you want via Jackett (movie title or imdbid) and find what you're looking for. Unless I'm mistaken, adding imdbid support would only affect searches via services like Radarr. Because the BeyondHD indexer doesn't support imdbid's, Radarr searches using the movie title and year. A search for 'rogue one star wars story 2016' will net you 0 results, whereas 'tt3748528' returns 8.

To address incomplete results due to lack of a imdbid's on uploads such as Bourne Identity, there's a feature request for Radarr to add a fallback search based on title (though I'm hoping it'll be added as an option/preference for manual searches and not just a fallback): http://feathub.com/Radarr/Radarr/+114 - please give it a vote if that's something you'd like to see added.

**Comment by RoloSoze** [comment]
@c2af5c5f28e38384295f2fc2af From my experience, the search results on BHD are pretty accurate if you search for the full movie / show title. Personally, I prefer getting more results than less i.e. Searching by title & year, and getting 8 results (5 of which are the movie you're looking for) is better than searching by IMDb ID and getting only 2 out of the 5 results because some of the uploader did not enter the IMDb URL in the torrent's description. 

As for the Rouge One example you mentioned, try searching for 'Rouge One' only, the leave out the 'A Star Wars Story' part. Most uploaders did not include this part in the torrent's name for this particular movie. 

Remember that you can always use the search filter in Jackett as a secondary measure to ensure you're getting the results you want. Anyhow, I'll leave it up to the developers to decide whether to implement the IMDb ID search for BHD.

**Comment by kaso17** [comment]
I agree with @RoloSoze: if movie torrents are regularly missing the IMDB ID we shouldn't enable IMDB search for it.

**Comment by c2af5c5f28e38384295f2fc2af** [comment]
> As for the Rouge One example you mentioned, try searching for 'Rouge One' only, the leave out the 'A Star Wars Story' part. Most uploaders did not include this part in the torrent's name for this particular movie.

@RoloSoze Correct, the issue with Rogue One is all the uploads use the shortened name, and a search via Jackett for 'Rogue One' does indeed return some results. The problem is, I can't change the search string when using a service like Radarr or Sonarr. Radarr for example will use the full title and year if the indexer does not support imdbid. 

When it comes to searching via Jackett's interface - from what I understand - adding imdbid support should have no effect on results. When it comes to searching via Radarr or Sonarr, both methods - be that title or imdbid - have their pros and cons:

**IMDB ID**

- **Pros:**
    - returned results are accurate
    - potential to return results a title search fails to (less reliance on how good or bad the indexer's search is: e.g., `Example and Example` returns results but not `Example & Example`)
- **Cons:**
    - potential to return no results or incomplete results in cases where uploads are missing IMDB ID's

**Title / Year**

- **Pros:**
    - potential to return results that do or don't include IMDB ID's
- **Cons:**
    - potential for inaccurate results
    - potential for no results or incomplete results in cases where a search string is too long or unique, doesn't match, or contains characters the indexer's search doesn't like

I'm honestly not sure what the best route is. Of course, if Radarr/Sonarr supported both methods of search these pros/cons wouldn't apply and it would simply make sense to add imdbid support (another plug for the feathub on that: http://feathub.com/Radarr/Radarr/+114).

> I agree with @RoloSoze: if movie torrents are regularly missing the IMDB ID we shouldn't enable IMDB search for it.

@kaso17 It seems most of them include it as it is an upload rule, but there are certainly some that don't. x264 on the other hand rarely includes imdbid's so that indexer is essentially useless on Radarr/Sonarr. It's a bit ironic that it has imdbid support and BeyondHD doesn't, heh.

Thank you both for hearing me out and sharing your thoughts by the way.

**Comment by c2af5c5f28e38384295f2fc2af** [comment]
After giving it some more thought and testing some more searches, I think I've changed my mind. Until Radarr / Sonarr support both searching by imdbid and title, it's probably best to keep BeyondHD as is. From my tests, while most of the torrents did have imdbids, there were enough that didn't that would have been returned with a title + year search. So, it does seem you're more likely to get incomplete search results with the imdbid than you are with the title.

This begs the question, why does x264 have imdb support enabled? If it makes sense to keep it disabled on BeyondHD - a tracker where imdbid's are far more prevalent than x264 - does it also make sense to disable it on x264? Perhaps this a question for another issue.
