### ISSUE TITLE
[tvvault] Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by 1ColdAssHonkey** [Jackett/Jackett#12096]
**OS**:  

Linux

**Jackett Version**: 

v0.18.496 - linuxserver/jackett docker

**Last Working Jackett Version**: 

Not exactly sure, but it was working ~ 2 weeks ago.

**Are you using a proxy or VPN?** [yes/no] no

The same issue as #10412.  No results when searching tracker with Jackett.

### Logged Error Messages

	Line 21639: 2021-07-28 20:06:18.8496 Info Test search in TV-Vault => Found 0 releases 
	Line 21677: 2021-07-28 20:21:59.1053 Info Test search in TV-Vault => Found 0 releases 

[Make sure you attach the full logs with your personal information removed in case we need more information]

Due to the privacy of this tracker, I will be happy to email the HTML source and logs.  Is the email address the same as in	 issue #10412?

### Screenshots

![error message](https://user-images.githubusercontent.com/66453120/127426999-a6707fab-313f-4c54-b346-2a3ca9d6ddc3.JPG)

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
yes, send to garfieldsixtynine -at- gmail.com and I'll take a looksee.

**Comment by garfield69** [comment]
yes, if you are getting `Excessive automated queries detected.`  then I don't think there is much can be done via Jackett since jackett  does not track how often you make queries nor can it restrict the amount of queries you make over a period of time.
Jackett does have a cache which can mitigate some excessive query cycles for the same torrents but its not fool proof.
If you are using Sonarr or Radarr to automate queries via jackett to the site, then examine how often those apps are set to query and increase their period delay between queries.
IF you are using jackett manually to search then you will just have to slow down. Perhaps take a look at the sites forum to see if there are notices about excessive queries or something.

**Comment by 1ColdAssHonkey** [comment]
I am now sure that the culprit is NZBHydra2.  I don't have TVV enabled in Sonarr/Radarr due to the site's tight economy.

 What I am going to do is to keep it unchecked on Hydra's front search page and only enable it for specific searches.. 

Thanks for getting back to me.

    On Friday, July 30, 2021, 03:32:36 AM PDT, garfield69 ***@***.***> wrote:  
 
 


yes, if you are getting Excessive automated queries detected. then I don't think there is much can be done via Jackett since jackett does not track how often you make queries nor can it restrict the amount of queries you make over a period of time.
Jackett does have a cache which can mitigate some excessive query cycles for the same torrents but its not fool proof.
If you are using Sonarr or Radarr to automate queries via jackett to the site, then examine how often those apps are set to query and increase their period delay between queries.
IF you are using jackett manually to search then you will just have to slow down. Perhaps take a look at the sites forum to see if there are notices about excessive queries or something.
