### ISSUE TITLE
[NEWPCT] Latest Problem

### ISSUE THREAD

**Issue by diegargon** [Jackett/Jackett#12107]
Hi.

Seems Jackett got the latest release from:

https://maxitorrent.com/ultimas-descargas/

But that source for latest skip lots of new release.

The indexer have better source for latest.
Latest Movies: 
https://maxitorrent.com/peliculas/
Latest Shows:
https://maxitorrent.com/series/

That page source really show the latest and have more results.

it would be difficult to change this ?
thanks

**Comment by garfield69** [comment]
The indexer is written in C# and is already one of the more complicated indexer I've has the misfortune to look at.

So there are differences in the HTML between the ultimas page and the series and movies pages, the latter just contain posters and titles, without the file size, so the results from merging the series and movies pages will already be in my view less than useful, since the site already does not present seeders and leechers in search results. 

And instead of requesting one page and getting 1000 torrents back, you are asking to make two requests, and get 80 movies and 200 series returned.
This will double the request traffic and in an era of heightened sensitivity to DDoS may cause the site to black list your IP.
Or it might be fine, it will need testing.

I find it surprising that the ultimas-descargas page does NOT have the latest torrents since that is the whole purpose of the page, but whatever.

Regardless, to implement what you suggest will require a C# volunteer, since I am not a C# dev I'm not going near this complicated indexer, it's just too confusing for me.

**Comment by diegargon** [comment]
thanks it's ok,  this page is a shitty page but lamentably is the best PUBLIC Spanish indexer too. :(

we can live without it and in the future, if someone can improve in the future this will be nice.

**Comment by garfield69** [comment]
no one cares. closing.
