### ISSUE TITLE
RARBG show IMDb search capability missing

### ISSUE THREAD

**Issue by agneevX** [Jackett/Jackett#12127]
### Environment

**OS**: Ubuntu Linux
**.Net Runtime**: Docker install
**.Net Version**: 
**Jackett Version**: 0.18.523
**Last Working Jackett Version**: N/A
**Are you using a proxy or VPN?**: No

### Description

It seems that the RARBG indexer does not support IMDb searching for TV shows or Jackett is incorrectly reporting this.

```xml
<caps>
  <server title="Jackett"/>
  <searching>
    <search available="yes" supportedParams="q"/>
    <tv-search available="yes" supportedParams="q,season,ep"/>
...
  </searching>
</caps>
```

From my testing, RARBG supports this if two parameters are used together, i.e. `search_imdb` for the IMDb query and `search_string` for the remaining torznab query data, e.g. `S02E01`:

`curl "https://torrentapi.org/pubapi_v2.php?app_id=jackett&token=xxx&mode=search&search_imdb=tt10986410&search_string=S02E01"`

Can this be added?

**Comment by garfield69** [comment]
support for tv search in combination with imdb was handicapped by issue #8107 which is still open.

however it should be possible to amend the rarbg indexer if the correct support logic is added, i.e.
if imdb is provided and it a tv search and the season and episode is present then build the correct rarbg api query.

however it should be noted that the official rarbg API docs do not document the use of search_imdb and search_string combo (see https://torrentapi.org/apidocs_v2.txt?app_id=Jackett ) 

anyway, since this is a C# indexer it will require a c# volunteer to provide the necessary code support.

**Comment by mikeoscar2006** [comment]
Got it. Interested in fixing this. Would soon open a PR if it's alright.

**Comment by garfield69** [comment]
v0.18.623
