### ISSUE TITLE
[nyaasi] Season Pack query logic

### ISSUE THREAD

**Issue by bkr32** [Jackett/Jackett#12140]
### Environment

**OS**:Docker

**Jackett Version**:0.18.402

**Last Working Jackett Version**:n/a

**Are you using a proxy or VPN?** no

### Description

Jackett should translate season pack searches from `SXX` to `Season XX` however this is not done and it simply searches as `SXX`.
this was tested using both sonarr search and a manual search within jackett, wherein the manual search found no results or tranlation of query when `SXX` was used, however was able to correctly find releases using `Season XX`

reference pull request https://github.com/Jackett/Jackett/pull/1632

### Logged Error Messages
```

2021-08-08 21:57:19 | Info | Manual search in nyaasi for Show (Year) season 1 => Found 2 releases
-- | -- | --
2021-08-08 21:57:10 | Info | Manual search in nyaasi for Show (Year) s01 => Found 0 releases
```

**Comment by garfield69** [comment]
this Sxx to Season xx is done on a case by case bases as not all indexers use this method to label their season packs.
are you looking to get the nyaasi indexer enhanced with this search season packs support?

**Comment by bkr32** [comment]
@garfield69 actually yes, anime indexers would benefit quite a bit from this

**Comment by garfield69** [comment]
the nyaasi site does not appear to have a standard for season packs
I see from random dipping titles such as:
```
[Hanasaku] ReZero kara Hajimeru Isekai Seikatsu 2nd Season 01-​25 [Web 720p Hi444PP AAC]
[PokeArchive] Pokemon the Series -​ Black and White [Seasons 14-​16] -​ Amazon CBR, PokemonTV
[MagicStar] Junkyouju Takatsuki Akira no Suisatsu Season1 EP01 [WEBDL] [1080p]
[MagicStar] Kodoku no Gurume Season9 EP05 [WEBDL] [1080p] [PARAVI]
[Bunny-​Apocalypse] Zero no Tsukaima ( The Familiar of Zero ) ( BD 1080p FLAC ) All Seasons ( S01 Dual-​Audio, S02+S03+S04 Sub ) 
The Genius: Grand Final 더 지니어스: 그랜드 파이널 S04 (1080p, 60fps)
[Lilith-​Raws] 王者天下 /​ Kingdom S03 -​ 15 [Baha][WEB-​DL][1080p][AVC AAC][CHT][MP4]
```

if we replace Sxx with Season xx on this site you run the risk of missing out on the other packs that use the Sxx scheme

I don't know what proportion of titles use the Sxx versus Season xx scheme,  so if we implement this it may be better to make it optional in the config so that users can decide which method to use overall.

But we cant cover all because we are not going to issue multiple search queries, one for every possible variation of the pack naming available on nyaa.

**Comment by bkr32** [comment]
I agree, it does vary greatly from uploader to uploader, for now I've opted to using a rss feed as a indexer within sonarr,
The optional config sounds like a solid idea

**Comment by garfield69** [comment]
:-(
it is not possible to support the nyaasi `Sxx->Season xx` searching with the current indexer written in yaml, because of an existing problem with the nyaasi web sites search engine.

You see the web site will return partial matches to keywords from other titles, which we need to filter out before presenting the results.
To do this, the indexer has a row andmatch, which excludes any rows of results that do not contain the keywords that were in the original query.
this effectively means, that if we make a search for `Moriarty S01` and replace it with a query to the nyaasi web site  for `Moriarty Season 1` the indexer row andmatch will exclude all those rows returned by the site because none of the titles contain S01.
Its not currently possible to selectively turn on/off the andmatch filter based on config settings.

So to support `Sxx->Season xx` for nyaasi the indexer would have to be rewritten in C#, for which (Based on recent activity) there is no interest from any C# devs (I'm not a C# dev).
