### ISSUE TITLE
Sonarr not getting proper search from jackett when indexing torrentdb.net

### ISSUE THREAD

**Issue by serialbus2** [Jackett/Jackett#12156]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:  

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.18.537

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]
sonarr is not getting the search results that jackett sees when indexing torrentDB.net. 
It seemed like it would show season packs but not episodes or torrents that contained the entire series.

I'm new to jackett and sonarr but on the sonarr discord people were saying that there was a difference between an id search that sonarr does and a text query that happens when you search in jackett itself, and that the possibilities seemed like either torrentdb doesn't support individual episode searches via imdb# or prowlarr is sending season when it should send episode queries.

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
What series are you having problems with? I tried some of the series which had recent single episode releases on the site and they worked fine, apart from one for which Sonarr was adding the year to the search term. Searching for an episode of a series that the site only has season packs for, that failed.

**Comment by bakerboy448** [comment]
@ilike2burnthing I worked with @serialbus2  in sonarr to debug this out this afternoon.

It appears that given the current TorrentDB YML, TorrentDB does not support individual episode searches.

Not sure if the issue is on the YML or with torrentdb itself.

(Borrowing from Prowlarr's logs since it's still cardigann and the same YML is used and I no longer have jackett hooked up to Sonarr | additionally the same results were being returned for the same search in prowlarr and jackett, further confirming it's the same)

Searching for Rick & Morty S05E07 in Sonarr results in the following query to TorrentDB which uses the IMDBid.  This only returns season packs.

Sonarr => Jackett  `/api/v2.0/indexers/torrentdb/results/torznab/api?t=tvsearch&cat=5000,100002&extended=1&apikey=(removed)&offset=0&limit=100&tvdbid=275274&season=5&ep=7`

Prowlarr is materially similar..

Prowlarr logs for what is sent to TorrentDB - (again easier to get given it's easier for me to get; same definition used though) 
`https://torrentdb.net/filter/torrents?categories[]=2&search=2861424&tags=&sorting=created_at&direction=desc&qty=100`

This only returns Season packs.  Further Debugging by @Davo1624 on discord on TorrentDB's site discovered the below.
![image](https://user-images.githubusercontent.com/55419169/129282385-738a8c1d-d9f1-4a5e-9373-ffe3c907240c.png)

Let me know if you need more information.

---
@serialbus2 to make the jackett devs happy, can you follow [the enhanced debug guide](https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket)  and get the detailed logs of jackett's search for S05E07 ?


X- Ref https://github.com/Prowlarr/Prowlarr/issues/416

**Comment by garfield69** [comment]
mostly the issue is with the torrentdb web site and how it performs searching.
The site searches titles and descriptions by default, and if you supply a imdbid, or tvdmid or tmdbid then the site does not support additional search parameters.

so, you can search the site with `Rick and Morty S05E08` and get a particular episode (in this case two torrents), or search with `Rick and Morty` and get whatever episodes are available on the site as well as any season packs available (currently about 31 torrents).
or you can search the site using the imdbid `2861424` which will yield 14 season pack torrents
 but not `2861424  s05e08` which will yield nothing
similarly you can search the site using the tvdbid `275274` which will yield just 7 season packs
 but not `275274 S05E08` which yields nothing.

the Jackett indexer has been coded as best as can be with the following limitations:
the Jackett  dashboard search using the torrentdb indexer will correctly return a full title and episode search
so `Rick and Morty S05E08` yields two results, same as the web site
and `Rick and Morty` yields 31 torrents, same as the web site.
searching for `tt2861424` and the dashboard yields 14 season packs same as searching the site for `2861424`
However, the dashboard does not support searching with the tvdbid `275274` because we use an row andmatch to filter out the irrelevant descriptions hits the site returns

using the torznab query, you can search torrentdb using the tvdbid which will yield 7 torrents same as the site. The indexer ignores the season and episode since the web site does not support adding these to the search query and the indexer does not have the ability to filter out titles based on season and episodes because not all web sites use the same naming scheme (for instance some Italian sites support `5x08`, Russian use `5 сезон 8 серия` etc.

I believe the Jackett indexer is delivering the best possible results given the limitations the web site search engine has...

**Comment by bakerboy448** [comment]
So just to be clear - it is expected that TorrentDB is unable to be searched for any individual episodes and is only able to be searched for the whole series or season packs if Jackett receives a torznab request for a single episode?

**Comment by garfield69** [comment]
>So just to be clear - it is expected that TorrentDB is unable to be searched for any individual episodes and is only able to be searched for the whole series or season packs if Jackett receives a torznab request for a single episode?
>in other words - Jackett does not support single episode searches for TorrentDB for torznab requests and there are no plans to attempt o correct this?

Until torrentdb upgrade their unit3d engine the only way to torznab a single episode request and get some results back from the torrentdb web site  is to use the **standard** query, for example to find `Rick and Morty S05E08` use either
`http://127.0.0.1:9117/api/v2.0/indexers/torrentdb/results/torznab/api?t=tvsearch&cat=5000,100002&extended=1&apikey=myapikey&offset=0&limit=100&Query=Rick%20and%20Morty&season=5&ep=8`
or
`http://127.0.0.1:9117/api/v2.0/indexers/torrentdb/results/torznab/api?t=tvsearch&cat=5000,100002&extended=1&apikey=myapikey&offset=0&limit=100&q=Rick%20and%20Morty&season=5&ep=8`

Using any torznab requests that includes a tvdbid or imdbid parameter will not yield an individual episode for the torrentdb indexer.
And this is a limitation of the torrentdb web site not Jackett.

**Comment by bakerboy448** [comment]
Makes sense! Thanks for the detailed reply.

One last follow up - I'm assuming no way to conditionally do a standard query search if the request is S/E with an ID without doing a rewrite of cardigann logic and adding some sort of search conditionals into the YML?

**Comment by garfield69** [comment]
>One last follow up - I'm assuming no way to conditionally do a standard query search if the request is S/E with an ID without doing a rewrite of cardigann logic and adding some sort of search conditionals into the YML?

correct, because Jackett does not have an imdbid or tvdbid lookup to fetch the title, which would be needed to build a query to the web site that will return results.

**Comment by garfield69** [comment]
I suppose that for the torrentdb indexer,  for the tvsearch, one way to force torznab apps to make standard queries is to drop the indexer support for tvdbid and imdbid. 
so we could change
https://github.com/Jackett/Jackett/blob/12bb70ef4724a3270411a6b9a2ebe0663bd05435/src/Jackett.Common/Definitions/torrentdb.yml#L22
into 
```yaml
    tv-search: [q, season, ep, imdbid, tvdbid]
```
and this would allow for episodes searches to work which is probably the majority of searches for tv on the web site, give that episode packs are usually less common?

**Comment by bakerboy448** [comment]
seems reasonable to me until torrentdb upgrades their api and allows proper support

Thanks for the fix!

**Comment by garfield69** [comment]
v0.18.545

**Comment by austinwbest** [comment]
TorrentDB doesn't use united in a way that can be updated via normal updates so might need to go about this a different way. As it is closed im not real sure if there is an interest in that though.

> I started developing TDB on the UNIT3D base ~4 years ago, mainly because I had no idea how announcers and peers work. I never took any updates ever since (not even their usual updates), and went completely rogue. What we have now is not even 5% similar in code-base with UNIT3D and we cannot share updates between each other.
