### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Login failed: No form found on https://www3.yggtorrent.nz/ using form selector 

### ISSUE THREAD

**Issue by damien2405** [Jackett/Jackett#12168]
**OS**: Windows Server 2012 R2

**.Net Runtime**: .Net-Framework

**Jackett Version**: v0.18.545

**Last Working Jackett Version**: IDK

**Are you using a proxy or VPN?** No

[List steps to reproduce the error and details on what happens and what you expected to happen]

Sometimes i just need to test and it's work, but now after fex hours, nothing, always this error

### Logged Error Messages

![téléchargement](https://user-images.githubusercontent.com/88164999/129474407-cf674390-1b7e-4c13-8249-f44dff3a54c3.png)

**Comment by garfield69** [comment]
The indexer is working for me so the issue appears to be at your end.
provide a full enhanced log and maybe the html and debug messages will give us a clue to what may be going on.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by matthieu-op** [comment]
Same problem here.

**Comment by damien2405** [comment]
Sometimes its work, sometimes not... IDK why

**Comment by garfield69** [comment]
>Sometimes its work, sometimes not... IDK why

the most likely reason will be some kind of intermittent issue on the YGG login server. But you will never find out what until you catch the error while you have the enhanced logging turned on.

**Comment by xxxxxaaaaaaaannnn** [comment]
Same issue, deleted and re-added the indexer and now it works.

**Comment by dr400** [comment]
except that it works just for a couple of hours and fails back again ...

**Comment by damien2405** [comment]
> The indexer is working for me so the issue appears to be at your end.
> provide a full enhanced log and maybe the html and debug messages will give us a clue to what may be going on.
> see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

Sorry, not a lot of time with my work. No problem il will try for that full logs

**Comment by martabal** [comment]
Same problem for me.
Here is the log : 

at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61 Jackett.Common.IndexerException: Exception (yggtorrent): Login failed: No form found on https://www3.yggtorrent.nz/ using form selector #user-login
---> System.Exception: Parse error
---> Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://www3.yggtorrent.nz/ using form selector #user-login

**Comment by garfield69** [comment]
@martabal https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by Potjoe-97** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/7030236/log.txt)
I had the issue this morning, I did a "Test" on the indexer, and recorded the output with enhanced logging. I hope this helps.

**Comment by Alphachoups** [comment]
Same problem here since several Weeks. 

[jackett.log](https://github.com/Jackett/Jackett/files/7030639/jackett.log)

**Comment by samimaarouf** [comment]
Same problem too

**Comment by Razor648** [comment]
Same problem since last week

**Comment by damien2405** [comment]
Hi @garfield69  , i dont have enough Time because of work. 

But @Alphachoups make log. Its good for u?

**Comment by garfield69** [comment]
the logs show that every couple of hours YGG requires a re-login, however intermittently the web site is returning 
www3.yggtorrent.nz | 524: A timeout occurred
which means that Jackett does not get the login form it requested in order to login and hence the error is generated.

I do not think there is anything Jackett can do about this. This is a YGG server issue possibly due to resource limits.

**Comment by damien2405** [comment]
Hum.. ok, but work perfectly fine since few months. And now its every night.. not normal

**Comment by RomLecat** [comment]
I agree, the issue seems widespread and appearing in a consistent matter, while browsing YggTorrent from browser never seems to trigger 524 errors.

Any work that can be done to mitigate the issue ? Considering manual re-login always works, perhaps some retry could be added ?

**Comment by garfield69** [comment]
>perhaps some retry could be added

The yaml processor does not support this option. The indexer would have to be re-written in C#.

**Comment by Alphachoups** [comment]
> which means that Jackett does not get the login form it requested in order to login and hence the error is generated.

The error generated is not the problem, the problem is that Jackett let the tracker in fault until we manually remove/re-add it... 
Do I correctly understand that the problem is that with 1 server timeout response, the Jackett service set the tracker as in fault with no automatic re-login retry? 
Seams to be very strange if a one time timeout of a tracker need a manual delete and re-add of the trackers concerned... Fault tolerance/acceptance is not a new concept in 2021 😄 

Beside this, as already said by @damien2405, the configuration worked fine since few months with several (real) server downtime of Yggtorrent that never requested a manual procedure to re-add the tracker to make it working again... (except for FQDN URL changing purpose of course).
From a logical perspective the problem seams to come from elsewhere or at least more complicated then a simple timeout of the server... 🙏

**Comment by ilike2burnthing** [comment]
@Alphachoups see @garfield69's last comment for why an automatic retry is not performed. All PRs are welcome.

No, a one time timeout of a tracker does not need a manual delete and re-add of the tracker.

There have been intermittent failures on YGG's end for as long as I've used it. There are 14 pages worth of issues spanning the last 3 years when searching for `yggtorrent Login failed No form found`. I also know from personal experience that much of the mess around #10943 and other similar issues at the time was that a fix would work for some but not others.

**Comment by RomLecat** [comment]
Most of the issue previously encountered with YggTorrent were due to the usage of CloudFlare anti-bot mode, which is not used anymore. YggTorrent has been perfectly stable for months since they stopped using it (except for a few url changes since then).

Currently, it fails every few hours and we need to edit configuration and validate the form (no need to remove/re-add it, simply edit configuration and validate settings) and it works back for a few hours, then fails again.

**Comment by Alphachoups** [comment]
@ilike2burnthing, I correctly read the last comment of @garfield69 :

> The yaml processor does not support this option. The indexer would have to be re-written in C#.

But as I already said --> Fault toreance & acceptance is not a new concept in 2021...
And jackett is able to reconnect a temporary unavailable tracker so I don't understand the difference between temporary tracker downtime and one-time login request timeout. 

> No, a one time timeout of a tracker does not need a manual delete and re-add of the tracker.

All the problem is there. In the logs it is intermittent timeout (one time timeout in a period, not for several hours) that is sufficient to put the tracker in failure with no automatic refresh of the tracker. 

> I do not think there is anything Jackett can do about this. This is a YGG server issue possibly due to resource limits.

Sorry but.. no. We just have to refresh the configuration of the tracker in jackett or delete/re-add the tracker in jackett to make it working again so (for once 😄 ) it's not a Yggtorrent problem but a jackett refresh/reload problem.

Said that, i'm not a programmer but infrastructure consultant so it's not my area of expertise and I will not insist 😏

**Comment by dr400** [comment]
workaround so far (for me is) was to reload jackett container every morning ... this has done the job so far ...

**Comment by ilike2burnthing** [comment]
@RomLecat

**Comment by ilike2burnthing** [comment]
@RomLecat the Cloudflare DDoS protection were a completely separate problem and didn't cause `no form found` errors (which as aforementioned have been happening a lot over the past 3 years).

@Alphachoups a new login attempt will be made the next time the indexer is used (or new config is applied). The retry that some C# indexers use is immediately after failure, rather than on next use. In either case, removing and re-adding the indexer isn't required.

**Comment by RomLecat** [comment]
@ilike2burnthing CloudFlare caused some no form found errors. See #4652.

Also, the next use does not make YggTorrent work again. Any "Test" on Jackett fails, or any API call from caller (Sonarr or Radarr, for instance) still reports YggTorrent as broken, no matter how much try we do or for how long.
The only way to restore YggTorrent is indeed to either remove it and re-add it, or to go its settings and validate (without any change).

**Comment by ilike2burnthing** [comment]
Turn on enhanced logging and you should see your search, `relogin required`, a login attempt, confirmation it worked, and (if successful) a new search. Just tried it there, worked fine.

**Comment by RomLecat** [comment]
For some reason the issue did not occured today (yet). It's working for a bit longer than usual, which might indicate the issue is resolved, but I'll keep monitoring and provide logs if the issue occurs again to confirm behaviour when it's broken.

**Comment by Alphachoups** [comment]
Yep, same here, the tracker was still working today so it pass yesterday evening, nigh and this morning without problems.

**Comment by damien2405** [comment]
Hello boys ! For me too,  no problem this night and morning.. Wait&See...

@dr400 what its your solution to refresh Automatically Jackett?

**Comment by dr400** [comment]
@damien2405 : jackett is ruuning in a docker container ... I have a CRON task running each and every day at 5.00 am : docker restart jackett. Pb is, since you guys said that you had no issue in the last few days it does not mean that my workaround is indeed working ... But I do admit that so far "test" of yggtorrent is always green !

**Comment by damien2405** [comment]
Sad, ive got the issue just right now :/

**Comment by samimaarouf** [comment]
Like many of you, I didn't got the problem this night. 
It still works for now.

**Comment by Alphachoups** [comment]
@damien2405  I have just checked and it's still working for me since Yesterday without any intervention.

**Comment by tchirou** [comment]
I just checked and I got the error in all sonates and radarrs. Tested in Jackett and got the parse error. Validating the indexer in the settings then testing again worked as usual then.

**Comment by Alphachoups** [comment]
On my side i'm still good since two days without any changes in jackett/sonarr/radarr🤞

**Comment by damien2405** [comment]
For Windows User. I make an automatic task who restart Jackett Service every 3 hours, Radarr/Sonarr give 6 hours  Because reboot solve the problem. 

Wait & See

**Comment by RomLecat** [comment]
@ilike2burnthing @garfield69 I got the error again this morning, here are the logs: [jackett.log](https://github.com/Jackett/Jackett/files/7046176/jackett.log).

Indeed, some requests seems to trigger "Relogin required", but then I still get "Login failed: No form found on https://www3.yggtorrent.nz/ using form selector #user-login" while it's clearly present in the HTML, which definitely looks like a bug to me.

Please let me know if you need more info/details.

**Comment by RomLecat** [comment]
Got the same issue on another Jackett instance (without enhanced logs enabled, so I won't provide them, they're exactly identical to the ones I provided anyway).

I think the 524 error from @damien2405 was just bad luck, the main issue we have is that even if the login modal is present, Jackett does not seem to grab it for some reason (a race condition ? maybe the parser is called before the page is fully loaded ?).

Can the issue be re-opened please ?

**Comment by damien2405** [comment]
Hi, on the YGGtorrent forum someone would have solved the problem by using on Sonarr and Radarr the YGGTORRENT cookies, not the normal YGG. Maybe a lead?

**Comment by Alphachoups** [comment]
It's not a solution, it's unfortunately only a workaround (temporary because cookie is not as stable as normal login).

I got the problem again today. (need to revalidate the configuration manually in jackett).

> > perhaps some retry could be added
> 
> The yaml processor does not support this option. The indexer would have to be re-written in C#.

Thanks for this advice, I found jackett re-written in C# and specialy sized for Sonarr/radarr ! ----> [Prowlarr](https://www.reddit.com/r/sonarr/comments/ntc3xw/introducing_prowlarr/)

Will see If I encounter the same problem

**Comment by tchirou** [comment]
Thanks for the Info, I just set up prowlarr too to check

**Comment by garfield69** [comment]
don't bother. 
prowler imports their yaml indexers straight from the Jackett github repo source every few days
and has its own flavoured version of the same c# indexer that jackett has
but at least the prowler team have an active c# development team so they may well respond to requests to provide a yggtorrent c# indexder for their app.

**Comment by Alphachoups** [comment]
@garfield69 "Don't bother, don't bother"... -> I confirm that Prowlarr is not impacted by this bug and is working great.

Jackett was again in failure into Sonarr & Radarr. A little "Test" in jacket and it confirmed that the Yggtorrent tracker is again down since several hours.
No error in Sonarr & Radarr for the Prowlarr Indexer. To be sure i make a connection to Prowlarr and force a check of the Yggtorrent tracker and the test passed without any problems. I also made a moovie search on Sonarr & Radarr to be sure that the Prowlarr tracker is working fine and that the "test" was not a false positive --> The search was getting results without any problems

So it's again (if such were necessary) a proof that the problem is comming from Jackett and that it's possible to enhance the reliability of the indexer because Prowlarr is not impacted by the intermittent login timeout of the tracker (if the problem comes from there.. not confirmed at all) especially knowing that Prowlarr imports their yaml indexers from the jackett repo.

**Comment by garfield69** [comment]
Excellent. so all that remains is for a C# dev volunteer to analyse why the Jackett C# modules involved with processing the ygg yaml cant cope with whatever is causing the issues. PR's are welcome!

**Comment by bossovitch** [comment]
> @garfield69 "Don't bother, don't bother"... -> I confirm that Prowlarr is not impacted by this bug and is working great.
> 
> Jackett was again in failure into Sonarr & Radarr. A little "Test" in jacket and it confirmed that the Yggtorrent tracker is again down since several hours.
> No error in Sonarr & Radarr for the Prowlarr Indexer. To be sure i make a connection to Prowlarr and force a check of the Yggtorrent tracker and the test passed without any problems. I also made a moovie search on Sonarr & Radarr to be sure that the Prowlarr tracker is working fine and that the "test" was not a false positive --> The search was getting results without any problems
> 
> So it's again (if such were necessary) a proof that the problem is comming from Jackett and that it's possible to enhance the reliability of the indexer because Prowlarr is not impacted by the intermittent login timeout of the tracker (if the problem comes from there.. not confirmed at all) especially knowing that Prowlarr imports their yaml indexers from the jackett repo.

Ok the search in prowlarr is working fine for me too, but I can't download a correct torrent file, prowlarr is downloading a file, but it is not recognized by the torrent client as a correct file.
When i disable the flaresolverr proxy, prowlarr search correctly, and download the correct torrent file.
I believe jackett produces errors less often when flaresolverr is disabled
(alphachoups did this test I think), so the problem seems to be with flaresolverr?

**Comment by RomLecat** [comment]
I reproduced the issue regarding YggTorrent/FlareSolverr on Prowlarr and raised a bug: https://github.com/Prowlarr/Prowlarr/issues/478

**Comment by Alphachoups** [comment]
@RomLecat

1) On Yggtorrent the FlareSolverr is no more necessary, you can juste avoid it and it's Working fine
2) When I removed the FlareSolverr Proxy configuration in Jackett I confirm that the issue was less present but it does not disapear. With Flaresolverr not used and the issue still present, it mean that the issue/bug (tracker in failure) is not comming from the Flaresolverr Proxy but the bug is just exacerbated by the Flaresolverr proxy (seams logical because it's a timeout related issue)
3) Be carefull that Prowlerr is not compatible with Flaresolverr : 
![image](https://user-images.githubusercontent.com/60063291/131554006-c0221cfc-0d64-4fc2-b8b6-3af05b2d53d5.png)
It's maybe linked to your torrent file problem?

**Comment by RomLecat** [comment]
This is not really the place to discuss that, but:
1. I'm well aware, it's not necessary until the next time CloudFlare anti-bot is enabled
2. I've never been able to trigger the issue with FlareSolverr disabled, while it's consistently happening when it's enabled. Are you sure you don't have any cache issue or similar ?
3. This is a warning that has never been removed because FlareSolverr was only implemented two weeks ago on Prowlarr, it's just a leftover.

**Comment by Alphachoups** [comment]
Exception for my last point, we are still speaking about the timeout issue in jackett so it is the right place for me..

1) Yep I agree
2) I'm sure that the issue is still present without FlareSolverr configured. I removed the FlareSolverr configuration for more then 1 Week and the problem continue to appear (but less then every 6 hours). As previously said, the problem is clearly a timout problem that is not correctly handled by the Indexer. Since Flaresolver is a proxy and add an extra login process time, it's logical that the problem occure more often with Flaresolver then without.
3) Ok, I admit that I only saw the warning but I haven't been more in depth since I don't use it for instance.

**Comment by RomLecat** [comment]
My bad, I misread your comment. I thought we were talking about Prowlarr in point 2, not Jackett.

**Comment by Alphachoups** [comment]
@bossovitch  Nope, I confirm that there is no bug/issue with prowlarr without Flaresolverr. 
But on my side, I left Jackett configured with only Yggtorrent as indexer and without flaresolverr for 2 weeks now and the issue continue to appear every day only on Jackett. So I confirm that it's not a Yggtorrent problem but clearly a Jackett issue (certainly just a rearm after timeout issue).

**Comment by charly925** [comment]
> I'm trying to restart automatically the jackett docker every hour or so. I'll let you know if that works.

This works.

**Comment by protectxme** [comment]
Hi 
Have you got news fort thaïs issue ? The problem is already on

**Comment by PanduxM** [comment]
Hi, 
I have had the same problem for a while but it has been even worse for a few days since YGG enabled Cloudflare protection... I mainly use this tracker, hope you find a solution. Thanks in advance.

**Comment by hot22shot** [comment]
Same here, I scheduled a script to restart the docker every hour but now that solution is also failing.

**Comment by martabal** [comment]
No problem with using YGGcookie indexer. But that's not a permanent solution.

**Comment by tchirou** [comment]
> No problem with using YGGcookie indexer. But that's not a permanent solution.

Does it download the .torrent file. It never does on my jackett with yggcookie

**Comment by ilike2burnthing** [comment]
Make sure you're logged in and pull a new cookie, reconfigure the indexer with it and try again.

**Comment by Lyliya** [comment]
Same issue, restarting the docker every hour does not work anymore, someone has a fix ?

**Comment by PanduxM** [comment]
> Same issue, restarting the docker every hour does not work anymore, someone has a fix ?

As long as Cloudflare is activated on the YGG website, you will need to use the YggCookie tracker instead of YggTorrent.
Make sure that Jackett is updated with the latest version.
Hope there will be more stable solutions in the future :)

**Comment by almottier** [comment]
You may switch to Prowlarr, it doesn't fix the cloudflare issue, but
yggcookie is working great without the need of restarting every hour.

**Comment by Lyliya** [comment]
YGGTorrent/YGGCookie give me this error even if i can access it from my browser :/

Message: Cloudflare Error: Cloudflare has blocked this request. Probably your IP is banned for this site, check in your web browser.: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Cloudflare Error: Cloudflare has blocked this request. Probably your IP is banned for this site, check in your web browser.

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/234

Only current solution is to keep retrying.

**Comment by Lyliya** [comment]
It look like they disabled it because someone has flood with prowlarr :(
Sad because its the only big one we have in France. Time to configure some US indexers with bazarr until it work again :'(

**Comment by ilike2burnthing** [comment]
The UA bypass that meant FlareSolverr wasn't even needed is what they 've disabled, it is used by yggcookie.

~You can still use yggtorrent and FlareSolverr, and while it will fail most of the time, it _should_ eventually work with enough retries (and a lot of patience).~
I've been trying this for the past 10mins without success 😐 ymmv

**Comment by garfield69** [comment]
for comparison, both yggtorrent and yggcookie indexers failed to pass the cloudflare check just now.
but after I reverted the yggcookie useragent=YggRobot and used the full useragent from the config, I can now use yggcookie to search on my win10 jackett without problems.

**Comment by mushuthecat** [comment]
HI,

It works for me by configuring again my cookie and installating the last flaresolverr version 2.1.0 + the last Jackett version  https://github.com/FlareSolverr/FlareSolverr/releases/tag/v2.1.0

**Comment by focheur91300** [comment]
I on my side full update jackket, FlareSolverr, cookies and user-agent too.
Still the problem of connection to the account.
![image](https://user-images.githubusercontent.com/25317272/145784677-c6690ed4-0403-489e-a139-67a013f55a0a.png)
![image](https://user-images.githubusercontent.com/25317272/145784795-bce13a6f-da40-48ab-b7ab-79defdf2e5d0.png)

**Comment by ilike2burnthing** [comment]
Switch to yggtorrent

**Comment by mushuthecat** [comment]
> I on my side full update jackket, FlareSolverr, cookies and user-agent too. Still the problem of connection to the account. ![image](https://user-images.githubusercontent.com/25317272/145784677-c6690ed4-0403-489e-a139-67a013f55a0a.png) ![image](https://user-images.githubusercontent.com/25317272/145784795-bce13a6f-da40-48ab-b7ab-79defdf2e5d0.png)

your jackett is running on docker ?
In my configuration im using the user agent from my flaresolver configuration:
![image](https://user-images.githubusercontent.com/83928911/145888237-44c1c020-2a22-4d79-9c1d-0224a40219bc.png)

**Comment by JigSawFr** [comment]
For more info, please take a look at this comment: https://github.com/FlareSolverr/FlareSolverr/issues/596#issuecomment-1369270315
Should also work with Jackett ;)
