### ISSUE TITLE
[muziekfabriek] Login failed: Selector

### ISSUE THREAD

**Issue by nssatlantis** [Jackett/Jackett#12234]
### Environment

**OS**:
Windows
**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]
Unsure
**.Net Version**:
Unsure
**Jackett Version**:
Latest as of this date
**Last Working Jackett Version**:
Unsure, did not use before.
**Are you using a proxy or VPN?** [yes/no]
None.
### Description

 An error occurred while updating this indexer
Login failed: Selector ":has(a[href="logout.php"])" didn't match
Click here to open an issue on GitHub for this indexer.

### Logged Error Messages
 An error occurred while updating this indexer
Login failed: Selector ":has(a[href="logout.php"])" didn't match
Click here to open an issue on GitHub for this indexer.

Refreshing for new cookie code didn't work.

**Comment by garfield69** [comment]
The indexer works for me.
The site uses a DDoS prevention check which means you need to use cookies to start a Jackett session with the web site otherwise access is denied.
The login failed message means that the cookies you provided from your browser did not pass the web site test when Jackett tried to use them.

Read https://github.com/Jackett/Jackett/wiki/TroubleShooting#your-cookie-did-not-work and in particular the Notes section to see if any of it applies to you.

**Comment by nssatlantis** [comment]
Aha, thanks for that one. Seeing the first argument "Do this on the same browser you use jackett from" made me facepalm, and now it all works! My apologies, was trying to get things in a little too quick and end up just browsing to it from another machine.
