### ISSUE TITLE
[REQ] Great Poster Wall

### ISSUE THREAD

**Issue by xiNeRoar** [Jackett/Jackett#12245]
it is a new private tracker for chinese content, please add it to the support list. Thank you very much

**Comment by garfield69** [comment]
This is a Private Chinese site and registration is currently invites only.

If you send an invite to garfieldsixtynine -at- gmail.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by xiNeRoar** [comment]
It is on public registration now until 2021.09.03 24:00 (GMT+8). You can register your account today.

**Comment by garfield69** [comment]
![image](https://user-images.githubusercontent.com/6933240/131784611-b857bdc7-c16f-4c22-a214-a73bc57764ae.png)

???

**Comment by xiNeRoar** [comment]
sorry the site had closed by now...i did not have any invite at the moment so i think we might need to stop here until someone got an invite can send you.

**Comment by garfield69** [comment]
no worries. If you should happen to spot the open registration again let us know and I can try again. ;-)

**Comment by xiNeRoar** [comment]
thank you very much 👍

**Comment by BusiBeaver** [comment]
I tried, but really can't find an invite for you.

Next wave of open registration window time is:
https://www.timeanddate.com/worldclock/fixedtime.html?msg=GPW+Open+Signup&iso=20211001T00&p1=237
only 500 spots available. probably be gone within 4 hours like last time.

**Comment by garfield69** [comment]
Registration and login completed.

**Comment by garfield69** [comment]
read rules 2.4 and 5.2
renamed title to Seals and dropped url.
because we have to use the API we will need to code the indexer in C# and since the engine is gazelle we can use the GazelleAbstract to simplify coding.

notes: 
MR 1.0 MST 48 hours
engine: gazelle
API docs: https://github.com/WhatCD/Gazelle/wiki/JSON-API-Documentation#torrent-search
has 2FA: true

**Comment by garfield69** [comment]
@mikeoscar2006  I could use your guidance/help.

This site does not have categories, so I need prevent categories from being used in the search query, and I need to map the releaseType  from the group response to my category map so I can tag the torrents as movies or tv.
```C#
            AddCategoryMapping(1, TorznabCatType.Movies, "Feature Film");
            AddCategoryMapping(2, TorznabCatType.Movies, "Short Film");
            AddCategoryMapping(3, TorznabCatType.TV, "Miniseries");
            AddCategoryMapping(4, TorznabCatType.TV, "Stand-up Comedy");
            AddCategoryMapping(5, TorznabCatType.TV, "Live Performance");
            AddCategoryMapping(6, TorznabCatType.Movies, "Movie Collection");
```

- So how do I code an override to the GazelleTracker abstract to stop it trying to code categories for search queries?
https://github.com/Jackett/Jackett/blob/494331b5fd601eb2b43adbc42085a0a2fb256358/src/Jackett.Common/Indexers/Abstract/GazelleTracker.cs#L191-L192

- And similarly, how do I override the release.category section
https://github.com/Jackett/Jackett/blob/494331b5fd601eb2b43adbc42085a0a2fb256358/src/Jackett.Common/Indexers/Abstract/GazelleTracker.cs#L352-L356
to remove it since I'm going to provide my own category processing in the indexer?

- And finally given the indexer code at the bottom, how do I replace the string "Miniseries" with a reference to the releaseType var from earlier in the GazelleTracker abstract code
https://github.com/Jackett/Jackett/blob/494331b5fd601eb2b43adbc42085a0a2fb256358/src/Jackett.Common/Indexers/Abstract/GazelleTracker.cs#L219

my indexer so far
```C#
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Threading.Tasks;
using Jackett.Common.Indexers.Abstract;
using Jackett.Common.Models;
using Jackett.Common.Services.Interfaces;
using Jackett.Common.Utils.Clients;
using NLog;

namespace Jackett.Common.Indexers
{
    [ExcludeFromCodeCoverage]
    public class Seals : GazelleTracker
    {
        public Seals(IIndexerConfigurationService configService, WebClient wc, Logger l, IProtectionService ps,
            ICacheService cs)
            : base(id: "seals",
                   name: "Seals",
                   description: "Seals is a CHINESE Private site for MOVIES / TV",
                   link: "https://greatposterwall.com/",
                   caps: new TorznabCapabilities
                   {
                       TvSearchParams = new List<TvSearchParam>
                       {
                           TvSearchParam.Q, TvSearchParam.Season, TvSearchParam.Ep
                       },
                       MovieSearchParams = new List<MovieSearchParam>
                       {
                           MovieSearchParam.Q, MovieSearchParam.ImdbId
                       }
                   },
                   configService: configService,
                   client: wc,
                   logger: l,
                   p: ps,
                   cs: cs,
                   supportsFreeleechTokens: true,
                   imdbInTags: false,
                   has2Fa: true,
                   useApiKey: false,
                   usePassKey: false,
                   instructionMessageOptional: null
                  )
        {
            Language = "zh-CN";
            Type = "private";

            AddCategoryMapping(1, TorznabCatType.Movies, "Feature Film");
            AddCategoryMapping(2, TorznabCatType.Movies, "Short Film");
            AddCategoryMapping(3, TorznabCatType.TV, "Miniseries");
            AddCategoryMapping(4, TorznabCatType.TV, "Stand-up Comedy");
            AddCategoryMapping(5, TorznabCatType.TV, "Live Performance");
            AddCategoryMapping(6, TorznabCatType.Movies, "Movie Collection");
        }

        protected override async Task<IEnumerable<ReleaseInfo>> PerformQuery(TorznabQuery query)
        {
            var releases = await base.PerformQuery(query);
            foreach (var release in releases)
            {
                release.MinimumRatio = 1;
                release.MinimumSeedTime = 172800; // 48 hours
                release.Category = MapTrackerCatDescToNewznab("Miniseries");
            }
            return releases;
        }
    }
}
```

if this is getting to complex let me know, it may just be easier to let you borrow my creds and leave you to it, I am already regretting spending so much time on an indexer that is rapidly burning my candle and my grey cells ;-)

**Comment by mikeoscar2006** [comment]
I can think of three basic ideas for now:
1. Maybe have a look at Oppaitime indexer since it also doesn't have categories.
2. You can just copy-paste the PerformQuery function definition from the GazelleTracker abstract and remove the specific portions you mentioned above since you are overriding.
3. We can add a parameter (categoriesPresent = true/false) to the GazelleTracker abstract to exclude those portions automatically which can help future cases too and leads to a better code.

I'll be happy to help with whichever idea you'll choose or we can think of more ideas if you dislike all of them. Let me know :)

Note: Sorry, I couldn't understand your last point, the Miniseries one.

**Comment by garfield69** [comment]
v0.18.891

**Comment by garfield69** [comment]
just noticed that the director of movies is shown in the titles at the beginning, for example
`Keishi Ohtomo -​ Rurouni Kenshin Part II: Kyoto Inferno [2014] [Feature Film] 1080p /​ MKV /​ x264 /​ 0`
and while this is not a problem for Jackett dashboard searches, it will cause radarr to mismatch preventing automatic DL.

I will see if I can override the gazelleTracker abstract to shift the director (or maybe even drop it altogether) after the movie title for the next release of Jackett.

**Comment by garfield69** [comment]
v0.18.896

**Comment by garfield69** [comment]
No torrents on web site. Just me?

**Comment by ilike2burnthing** [comment]
Not sure if it was just you, but there are torrents there now.

**Comment by garfield69** [comment]
yes Its working for me too now.

**Comment by ilike2burnthing** [comment]
Torrents page showing 0 results.

**Comment by garfield69** [comment]
torrents are back. wonder what is causing that...

**Comment by ilike2burnthing** [comment]
https://greatposterwall.com/torrents.php - zero torrents

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://greatposterwall.com/ - Web server is down - Error code 521

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
I'm being redirected to https://kshare.club/ which gives 404 Not Found nginx
Just me?

**Comment by ilike2burnthing** [comment]
Happening to me as well, but still working in Jackett. I'm assuming they closed their login page, which is unfortunate as I don't appear to have active cookies other than on Jackett.

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/13641#issuecomment-3699852013
https://greatposterwall.com/ > cloudflare  Web server is down Error code 521

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://greatposterwall.com/ > Error code: 521 No Reason Phrase

**Comment by garfield69** [comment]
online
