### ISSUE TITLE
[cathoderaytube] Login Failed, got redirected.

### ISSUE THREAD

**Issue by angelfire76** [Jackett/Jackett#12253]
**OS**: Windows 8.1 64 Bit

**.Net Runtime**: .Net-Framework 3.5 & 4.5

**.Net Version**: ASP .NET 4.5

**Jackett Version**: v0.18.648

**Last Working Jackett Version**: None

**Are you using a proxy or VPN?** [yes/no] YES

### Description

When I try to login with https://www.cathode-ray.tube/ address, It always returns "Login Failed, got redirected." error.
It's like that since CRT has been added. I'm able to login with browser.

### Logged Error Messages

Login Failed, got redirected.

### Screenshots

![](https://i.imgur.com/QEZEWeU.png)

**Comment by garfield69** [comment]
The indexer is working for me so the problem appears to be at your end.
Please provide a full **enhanced** log. Perhaps the debug and HTML in that log will give us a clue to what may be going on during your Jackett login attempt.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by angelfire76** [comment]
@garfield69 The issue might be originated from 2FA.
2021-09-04 08:21:51.2771 Debug WebClient(HttpWebClient2): Returning Redirect => https://www.cathode-ray.tube/twofactor/login 0 bytes

**Comment by garfield69** [comment]
Ah. the indexer does not support 2FA.

if you enable 2FA on this site,  is https://www.cathode-ray.tube/twofactor/login a replacement for the standard login page,
or do you get the standard login page first followed by the twofactor page ?

**Comment by angelfire76** [comment]
Site redirects me to "https://www.cathode-ray.tube/twofactor/login" page in the browser.

**Comment by garfield69** [comment]
ok, but do you first see this page
![image](https://user-images.githubusercontent.com/6933240/132087341-d4587326-6b0d-49a2-81ee-1c814e3b10c8.png)
after which you get the twofactor page?

**Comment by garfield69** [comment]
I am going to assume that everybody gets the standard login page first, and then after you enter your credentials, the site presents the 2FA page for you to complete your login.
So because 2FA is a separate page that appears after you login using the standard login page, the Jackett indexer is not able to support 2FA.
So you can either turn off 2FA for this site, or if you want to continue using 2FA for your browser visits to the site, then I can create a clone of the current indexer, call it CRT2FA, and have it use the cookie method to access to site.
But this option works best if you are not a docker user, and your browser runs on the same computer where you run Jackett.
Do you want me to provide this alternative indexer?

**Comment by angelfire76** [comment]
@garfield69 Of course I'm seeing default login page, then it redirects to 2FA page.
If you won't bother much, cookie method would be better I think. I'm also using the same method in other trackers.
Thanks for your efforts. I appreciate that.

**Comment by garfield69** [comment]
v0.18.656
