### ISSUE TITLE
[REQ] (REAL) NewPCT public Spanish https://www.newpct.me

### ISSUE THREAD

**Issue by Quemandoacromo** [Jackett/Jackett#12284]
The (REAL) NewPCT :

> **https://www.newpct.me** (**public**)

**Comment by garfield69** [comment]
>The (REAL) NewPCT :

Unlikely to be the original.
The first domain used when the newpct indexer was first added to Jackett was added to DNS lookup on 2018-02-15T11:40:56Z
while https://www.newpct.me was added on 2019-09-22T19:59:38Z

Regardless, I will take a look and see if I can build a yml indexer for this domain, since at first glace it appears different, and the domain does not work with the existing indexer so it is clearly from a different publisher using different HTML.

**Comment by garfield69** [comment]
is it just me or can you also not access the series page, or when searching for a episode (eg papel 1x02) and click in that episode poster to get to the details page, you end up with the browser complaining about too many redirects and failing to bring the page up?
no such problems with  movies.

**Comment by garfield69** [comment]
since we cannot get to the details pages of series in order to fetch the .torrent/magnet I am only supporting movies for now.

**Comment by garfield69** [comment]
v0.18.729

**Comment by garfield69** [comment]
https://www.newpct.net/ returns Site Not Found
![image](https://user-images.githubusercontent.com/6933240/177057631-ace68081-4277-45aa-b496-234333f38840.png)

**Comment by garfield69** [comment]
v0.20.1992
