### ISSUE TITLE
[lostfilm] {

### ISSUE THREAD

**Issue by okiryanoff** [Jackett/Jackett#12290]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
lostfilm is working fine here, so there's an issue on your end. See the troubleshooting page for common issues. If your problem continues, provide the requested information.

**Comment by DeadMozay** [comment]
I am facing the error too
```
An error occurred while updating this indexer
Exception (lostfilm): Length cannot be less than zero. Parameter name: length: Parse error
```
Jackett Version v0.18.761

**Comment by garfield69** [comment]
I am seeing this too right now. After the indexer performs a login it check it can access the torrents, but there appears to be a torrent that is missing some info and the indexer is choking on it.
I'll take a look in deeper and see if I can figure it out.
Likely, at some point the torrent record gets filled in properly, and that may be why usually by the time we get told of it the problem is gone ;-D

**Comment by garfield69** [comment]
notes to self, since this is a C# indexer which is not my normal cup of tea.

so the indexer looks up a torrent's date field and from
```html
	<div class="left-box">
		Дата выхода ru: <span data-proper="0" data-released="14 сентября 2021">14 сентября 2021</span> г.<br/>
		Дата выхода eng:  TBA <br/>
	</div>
``` 
get the following:
`Дата выхода ru:14 сентября 2021 г. Дата выхода eng:  TBA`
which translates in english as 
`Released ru: 14 September 2021 Released eng: TBA`

and the indexer's routine 
```C#
                    var dateString = document.QuerySelector("div.title-block > div.details-pane > div.left-box").TextContent;
                    dateString = TrimString(dateString, "eng: ", " г."); // '... Дата выхода eng: 09 марта 2012 г. ...' -> '09 марта 2012'
                    DateTime date;
                    if (dateString.Length == 4) //dateString might be just a year, e.g. https://www.lostfilm.tv/series/Ghosted/season_1/episode_14/
                    {
                        date = DateTime.ParseExact(dateString, "yyyy", CultureInfo.InvariantCulture).ToLocalTime();
                    }
                    else
                    {
                        date = DateTime.Parse(dateString, new CultureInfo(Language)); // dd mmmm yyyy
                    }
```
ends up with 
```
Error on 20210916070444 for LostFilm.tv.txtSystem.ArgumentOutOfRangeException: Length cannot be less than zero. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Jackett.Common.Indexers.LostFilm.FetchEpisodeReleases(String url) in D:\a\1\s\src\Jackett.Common\Indexers\LostFilm.cs:line 466
```
so I am thinking because the date after the _eng_ is **TBA** it is breaking the routine.
OK, so now to figure out how to code a fix, by detecting _TBA_ after _eng_ and using the date for **ru** instead.

**Comment by garfield69** [comment]
v0.18.767

**Comment by DeadMozay** [comment]
> v0.18.767

Thank you, the error has been fixed.
