### ISSUE TITLE
[HDTorrentsIt] Couchpotato could not match anything

### ISSUE THREAD

**Issue by rafuz** [Jackett/Jackett#1230]
As mentioned in #1043 the plugin does not match the year correctly when Couchpotato searches something:

![image](https://cloud.githubusercontent.com/assets/22271829/24543937/bd444d2e-1601-11e7-98ec-d064cc2d9ac6.png)

Even when matching no details are returned for the torrent (as BDRIP, Bluray, quality, audio) just the name of the movie.

**Comment by kaso17** [comment]
To me it looks like HDTorrents.it needs brackets around the year in the search?
Can you please confirm the searches against their website search engine?
What happens if you search for `Assassin's Creed 2016` vs `Assassin's Creed (2016)`
What happens if you search for `Assassin%s%Creed%2016` or `%Assassin%s%Creed%2016%`

maybe @bonny1992 can help with this.

**Comment by ngosang** [comment]
@garfield69 can be closed?
