### ISSUE TITLE
[req]: Support Database (Save Settings into Database)

### ISSUE THREAD

**Issue by foremtehan** [Jackett/Jackett#12328]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

It would be great if you insert settings into database, I mean some PaaS app like heroku doest persist data into disk (it's get deleted after 24hr)

So rather than saving settings on the disk it would be great if there was a option to take them into our databases something like PostgresSQL or MySQL

**Comment by mikeoscar2006** [comment]
Interesting, but generally, something small as settings or preferences aren't stored in databases for numerous reasons but yeah, eager to hear what others think.

**Comment by foremtehan** [comment]
Something i forget, the heroku deletes all of the files (the app itself) so i dont know if it possible to accept db setting at build time

**Comment by garfield69** [comment]
I'm not sure I understand the basis for this request.
Are you saying that you are running Jackett on an heroku cloud image, and that because heroku does not persist its disk storage  you would like Jackett to store the settings and indexer configs in a database?
and where would this database be stored if not on the heroku image ... that does not persist disk storage?

**Comment by mikeoscar2006** [comment]
I'm assuming the author wants the ability to maybe provide a way to save preferences in the database and this DB can be remote also like tons available online which provide the standard interfaces like jdbc. However, I can't think of a large use case. It's too specific and as I mentioned above, there are a lot of reasons why something such small should not be stored in a db.

**Comment by garfield69** [comment]
Jackett already has the ability to store its configs at a different location other than the default path, it is, after all, how the docker images persist their settings.
Surely the heroku image config that launches Jackett allows start-up parameters to be defined, so by using the Jackett command line switches described at https://github.com/Jackett/Jackett#command-line-switches , you could add -d or --DataFolder to point to a user volume rather than the read-only one in the image.
