### ISSUE TITLE
[req]: Renegade

### ISSUE THREAD

**Issue by ClandestineClout** [Jackett/Jackett#12325]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: Renegade torrent tracker
- URL: https://renegade-tracker.com
- Description: Hungarian general tracker for TV, movies, xxx, etc.
- Minimum Seeding Time and Minimum Ratio (if Private): MST 48h, MR unclear/ratioless
- Additional Comments:
```

**Comment by garfield69** [comment]
hmm. rules conflict.
rules.php state
You must seed the downloaded torrent until your ratio reaches 0.7, or the 5 days mandatory seed time has elapsed since the download!
but H&R page seedkotelezettseg.php has
you need 48 hours of seed time or a ratio of 0.7

I'll set the H&R since that would seem to be the page most visited when someone is in trouble with downloads.

**Comment by garfield69** [comment]
v0.18.791

**Comment by ilike2burnthing** [comment]
http://renegade-tracker.com/ - down for maintenance

**Comment by ilike2burnthing** [comment]
http back up, https still refused, check back later to see if this gets resolved

**Comment by ilike2burnthing** [comment]
[v0.19.266](https://github.com/Jackett/Jackett/releases/tag/v0.19.266)

**Comment by garfield69** [comment]
https://renegade-tracker.com/ returning DNS_PROBE_FINISHED_NXDOMAIN and http redirects to https
just me or is the site broken, gone or moved to a new domain?

**Comment by ilike2burnthing** [comment]
[v0.20.184](https://github.com/Jackett/Jackett/releases/tag/v0.20.184)
