### ISSUE TITLE
[yggtorrent] Login Failed, got redirected. (Config)

### ISSUE THREAD

**Issue by JulioQc** [Jackett/Jackett#12338]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
- OS: Debian 10
- .Net Runtime: [.Net-Core/.Net-Framework/Mono]
- .Net Version: latest
- Jackett Version: latest
- Last Working Jackett Version: unknown
- Are you using a proxy or VPN? [yes/no] no
```

### Description

Error message. Login works on website. 

### Logged Error Messages

An error occurred while updating this indexer
Login Failed, got redirected.
Click here to open an issue on GitHub for this indexer.

**Comment by garfield69** [comment]
the indexer is working for me which suggests the problem is at your end.

- please do not say you are on the **latest** version, as this is not useful. access your Jackett dashboard, scroll to the bottom and report the version please.
- enable enhanced logging so that we can see more details on the failure. hopefully the included debug and HTML in the log will give a clue to your problem.
- see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by JulioQc** [comment]
what's the easiest way to see where it's actually redirected? Might point
me to what the error actually is...

**Comment by garfield69** [comment]
as I said earlier, turn on the enhanced log. there should be the http get and response recorded there. its just a matter of reviewing the full log of the event.

**Comment by JulioQc** [comment]
Thanks, I'll check it out.
