### ISSUE TITLE
[1337x] Exception (1337x): connection closed gracefully: The SSL connection could not be established, see inner exception. (Test)

### ISSUE THREAD

**Issue by amokster88** [Jackett/Jackett#12340]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
- OS: Mac OS 11.5.1
- .Net Runtime: [.Net-Core/.Net-Framework/Mono]
- .Net Version:
- Jackett Version: v0.18.812
- Last Working Jackett Version: v0.18.812
- Are you using a proxy or VPN? [yes/no] no
```

### Description

All the indexers are saying testing failed.
This wasn't happening earlier.

### Logged Error Messages

2021-09-27 12:45:52.3808 Info Jackett startup finished in 6.418 s 
2021-09-27 12:49:13.9118 Error Jackett.Common.IndexerException: Exception (1337x): connection closed gracefully
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+AppleCrypto+SslException: connection closed gracefully
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---

**Comment by garfield69** [comment]
`connection closed gracefully` sounds very polite ;-)

I'm not a Mac user, but I do have a Big Sur 11.0b image running under my win10 virtual box that I use to test Jackett occasionally.
I can run Jackett 0.18.815 and access the 1337x indexer without issue which suggests the problem is at your end.

if all the indexers are failing with the same error then you are probably looking at a network issue or perhaps a library update issue.
can you access https://1337x.to/ with your Big Sur browser?
are you .net core libraries up to date?
have you had a Big Sur update recently?
could some firewall or anti-malware app be blocking jackett's access to the web?

**Comment by amokster88** [comment]
Yes, I tried connecting the indexers with my mobile data and they got connected and when I am connecting through VPN then also they are getting passed successfully. Thanks for the response. I am closing the issue.
