### ISSUE TITLE
[magico] Exception (magico):  change domain from trellas.info to https://trelas.club

### ISSUE THREAD

**Issue by vlevas** [Jackett/Jackett#12349]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
- OS:
- .Net Runtime: [.Net-Core/.Net-Framework/Mono]
- .Net Version:
- Jackett Version:
- Last Working Jackett Version:
- Are you using a proxy or VPN? [yes/no]
```

### Description

Hello the tracker change domain from trellas.info to the new: https://trelas.club can you change the domain please?

thanks

### Logged Error Messages

cant login because tracker change the domain name

**Comment by garfield69** [comment]
Absolutely. Thank you for reporting.
If you want to use the club domain right now simply access your Jackett dashboard and edit the indexers' config and change the site link to the new domain.
I'll update the indexer shortly for a more automated updated, but we are not due to push out a new release for another 22 hours or so.

**Comment by vlevas** [comment]
thanks for this but for some reason doesnt work :S
https://prnt.sc/1u38gy8

Jackett Version v0.18.845

**Comment by vlevas** [comment]
i put https://trelas.club/?p=home&pid=1 and it works @garfield69

**Comment by garfield69** [comment]
v0.18.851
