### ISSUE TITLE
[req]: Search through Private Tracker requests page

### ISSUE THREAD

**Issue by PrivatePasta** [Jackett/Jackett#12366]
### Is there already a request for your feature?

- [ ] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

I was wondering whether it's possible for Jackett to search through the requests page of private trackers. If this were possible, someone could probably make a tool to check for those requests in other trackers. I'm not sure if this exists already, but I've searched for some time and couldn't find anything.

**Comment by garfield69** [comment]
Unlikely.
The primary function of Jackett is to respond to app's torznab API queries, by processing the incoming torznab search parameters and returning results in the torznab expected response structure.
The specs for the torznab API assumes that all the searches will take place on a web site's **Torrent** search page, since that is the torznab's primary design.
So all of Jackett's indexers are hard coded to use their respective web sites' torrent search engines.
There are currently no parameters on torznab queries to indicate that the search should be done on  the _Request_ page instead of the **Torrent** page.
If the torznab specs were ever expanded to include a query for search-requests then Jackett indexer could be modified to search a website's request page and return those results in response to such a torznab query.
The wheels of change in the torznab specs world are very slow to turn, I doubt that a search-requests definition will ever be included.
