### ISSUE TITLE
[hdonly] The SSL connection could not be established, see inner exception.: Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'. (Config)

### ISSUE THREAD

**Issue by Mamacito473** [Jackett/Jackett#12374]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: clientType
Using FlareSolverr: Disabled or a url
Using proxy: Disabled or HTTP/SOCKS4/SOCKS5
App config/log directory: folder path
Running in Docker: No/Yes
Jackett variant: variantType
OS version: platform n.nn (32bit/64bit)
Environment version: n.n.nn (folder path)
Starting Jackett vn.nn.nn
```

### Description

trying to log to hd only

### Logged Error Messages

https://i.imgur.com/TVtUScr.png

### Screenshots

https://i.imgur.com/TVtUScr.png

**Comment by BusiBeaver** [comment]
I also encountered this issue. Here is a report with debug log:

### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2021-11-01 21:37:45.3732 Info Starting Jackett v0.19.108 
2021-11-01 21:37:46.0753 Info Environment version: 5.0.11 (D:\Jackett\) 
2021-11-01 21:37:46.0773 Info OS version: Microsoft Windows NT 6.1.7601 Service Pack 1 (64bit OS) 
2021-11-01 21:37:46.0773 Info Jackett variant: CoreWindows 
2021-11-01 21:37:46.0773 Info Running in Docker: No 
2021-11-01 21:37:46.0773 Info ThreadPool MaxThreads: 682 workerThreads, 1000 completionPortThreads 
2021-11-01 21:37:46.0773 Info App config/log directory: C:\ProgramData\Jackett 
2021-11-01 21:37:46.0773 Info Using proxy: Http 
2021-11-01 21:37:46.0773 Info Using FlareSolverr: No 
2021-11-01 21:37:46.0773 Info Using HTTP Client: HttpWebClient2 
```


### Description

1. Add HD-Only indexer
2. Input username and password
3. Click OK
Expected Result: indexer added successfully
Actual Result: `An error occurred while updating this indexer. The SSL connection could not be established, see inner exception.: Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'. Click here to open an issue on GitHub for this indexer.`

### Logged Error Messages

https://p.teknik.io/Simple/1mhpD

### Screenshots

_No response_

**Comment by ilike2burnthing** [comment]
Likely related to you using Windows 7 - https://octopus.com/blog/dotnet-and-windows-ciphers
