### ISSUE TITLE
[req]: Blues-Brothers.biz

### ISSUE THREAD

**Issue by ClandestineClout** [Jackett/Jackett#12633]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: Blues-Brothers
- URL: https://blues-brothers.biz
- Description: General
- Minimum Seeding Time and Minimum Ratio (if Private): 36h
- Additional Comments: ~~open reg~~
```
Blues-Brothers is a Private Torrent Tracker for MOVIES / GENERAL
engine TBD

**Comment by garfield69** [comment]
I created an a/c on the 5th Dec but then had to leave for a week for personal reasons.
now my account has been apparently deleted (with no email warning) and registration is now closed.

If you send an invite to garfieldsixtynine -at- gmail.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by ilike2burnthing** [comment]
I'll get this done if I get some free time this weekend.

**Comment by garfield69** [comment]
v0.20.159

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://blues-brothers.biz/ - Connection timed out - Error code 522

**Comment by garfield69** [comment]
v0.20.2122
