### ISSUE TITLE
[Pornolab] Weird stuff

### ISSUE THREAD

**Issue by masterofobzene** [Jackett/Jackett#12705]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2021-12-13 18:43:10 	Info 	

Using HTTP Client: HttpWebClient2

2021-12-13 18:43:10 	Info 	

Using FlareSolverr: No

2021-12-13 18:43:10 	Info 	

Using proxy: Disabled

2021-12-13 18:43:10 	Info 	

App config/log directory: C:\ProgramData\Jackett

2021-12-13 18:43:10 	Info 	

ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads

2021-12-13 18:43:10 	Info 	

Running in Docker: No

2021-12-13 18:43:10 	Info 	

Jackett variant: CoreWindows

2021-12-13 18:43:10 	Info 	

OS version: Microsoft Windows NT 10.0.19044.0 (64bit OS)

2021-12-13 18:43:10 	Info 	

Environment version: 6.0.0 (C:\ProgramData\Jackett\)

2021-12-13 18:43:10 	Info 	

Starting Jackett v0.20.162
```

### Description

Search engine is acting weird. I've been having issues with pornolab but I thought it was something with the qbittorent plugin.
Now I see a strange behaviour when searching directly from jackett.

TEST Search terms "kenzie reeves" and filter "seduces"

Gives no pornolab results:
![imagen](https://user-images.githubusercontent.com/94469116/145894995-1be58d6b-c235-4753-ad9a-31aee5041657.png)

TEST Search terms "kenzie reeves seduces" and filter is empty.

Gives pornolab results:
![imagen](https://user-images.githubusercontent.com/94469116/145895465-a9bfd689-db78-4328-82fe-d98a54861814.png)

### Logged Error Messages

na

**Comment by garfield69** [comment]
there is nothing mysterious at all
pornolab provides 50 results per page sorted by default by date-added.
when you search for just `kenzie reeves` it so happens that results that include `seduces` are not in the first 50 results provided by the web site, the first 50 results with that term all were added within 112 days ago.
it is only when you search for `kenzie reeves seduces` you find the specific results, and the first entry was added 290 days ago.

**Comment by masterofobzene** [comment]
So Jackett will never be able to get older results from pornolab?

**Comment by garfield69** [comment]
correct.
using your example of searching for `kenzie reeves` there are a total of 14 pages with results on this web site.
if jackett were to make 14 request to pornolab to fetch all the pages available, I expect very quickly that jackett would be flagged as a DDoS bot in these days of super alertness and get blocked.

Having said that, I see that the web site does provide a sort option while the indexer does not.
so we could add the sort options to the indexer config, such that you could choose to get the oldest hits first.
but this would still not really provide the complete set since sorting in both directions would only return 2 pages out of the complete set of 14.

**Comment by masterofobzene** [comment]
I see... I suppose the same applies to all trackers too. 
Well... I will rely on manual search I guess. 

thanks.
