### ISSUE TITLE
[req]: guid based on pubdate or someelse, and not by link

### ISSUE THREAD

**Issue by Akior** [Jackett/Jackett#12737]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Some periodic indexers doesn't recreate new link for torrent update. 
Basically, RSS autouploaders look to xml guid for compare changes

as example kinozal rss query:

    <item>
      <title>1883 (Йеллоустоун: 1883)  1883 - S1E1-2 - rus ПМ (LostFilm) WEBDL</title>
      <guid>http://kinozal.tv/download.php?id=1883316</guid>
      <jackettindexer id="kinozal">Kinozal</jackettindexer>
      <comments>http://kinozal.tv/details.php?id=1883316</comments>
      <pubDate>Fri, 24 Dec 2021 20:14:00 +0300</pubDate>
      <size>1642824960</size>
      <description />
      <link>URL</link>
      <category>5000</category>
      <category>100046</category>
      <enclosure url="URL" length="1642824960" type="application/x-bittorrent" />
      <torznab:attr name="category" value="5000" />
      <torznab:attr name="category" value="100046" />
      <torznab:attr name="seeders" value="15" />
      <torznab:attr name="peers" value="17" />
      <torznab:attr name="minimumratio" value="1" />
      <torznab:attr name="downloadvolumefactor" value="1" />
      <torznab:attr name="uploadvolumefactor" value="1" />
    </item>
    
 <guid>http://kinozal.tv/download.php?id=1883316</guid> will not changed if torrent updated.

### Describe the solution you'd like

 Can we manage with guid = convert pubDate to int ( and for uniq + size ) or something like that?

**Comment by garfield69** [comment]
In order to reduce unnecessary traffic caused by auto-repeating apps that use Jackett to query for the latest torrents at frequent intervals, and to help prevent the site from black flagging your IP as a spammer/DDoS generator, the cache is used to return the same requested data within the cache lifetime.

Among other uses, the guid is used as the index to cached torrents.
Generating a date-stamped guid defeats the purpose of the cache.

If you are using the Jackett Cache, then for a particular indexer, when using torznab apps such as Sonarr, turn off cache for that indexer by adding the &cache=false parm.

If you are not using torznab queries, then the alternate is to turn off the cache altogether, but be aware that in these times of heightened alertness for DDoS attacks, most sites patience for repeat queries in a short period of time is very short.

**Comment by Akior** [comment]
Alright, i should try. Thanks
