### ISSUE TITLE
mejortorrent Could not find releases from this URL

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#12792]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
latest
```

### Description

I can not test the official domain because it's blocked in my country.
Both alternative links are not returning results:
* https://mejortorrent.nocensor.biz/
* https://mejortorrent.unblockit.how/

Could we make it work work both?

### Logged Error Messages

*

**Comment by garfield69** [comment]
all the alternate domain do work.
the issue here is that the keywordless search (and therefore the TEST) use the latest-torrent page, ( https://www.mejortorrentes.net/secciones.php?sec=ultimos_torrents ) but occasionally the web site has no rows on this page
![image](https://user-images.githubusercontent.com/6933240/148693007-b7bba7ff-20b4-4516-bc75-d93e8d073f94.png)
so a TEST fails. 
But by manually adding the relevant domain to the indexer config, I can do a search for `boba fett` on all 3 domains and get results.
