### ISSUE TITLE
[hdspace] Test search in HD-Space => Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by D3ZOXY** [Jackett/Jackett#12862]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
.
```

### Description

.

### Logged Error Messages

```text
.
```

### Screenshots

.

**Comment by garfield69** [comment]
the indexer is working for me which suggest the issue is at your end.
If you want help with this please fill in the form above properly and provide an enhanced log so we have a shot at finding clues to the problem.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
