### ISSUE TITLE
[newpct] Found 0 releases! (Config)

### ISSUE THREAD

**Issue by Persival321** [Jackett/Jackett#12930]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett Version v0.20.529
```

### Description

When I try to add in Jackett the newpct indexer does not let me and the error appears:
An error occurred while configuring this indexer
Found 0 releases!

### Logged Error Messages

```text
.
```

**Comment by garfield69** [comment]
The indexer is working for me so this suggests the problem is at your end.
Please turn on **enhanced** logging, repeat the test and provide the full log including the _Debug_ and _HTML_. It may provide the clue to understanding your issue.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
