### ISSUE TITLE
[Newpct] cant download torrent files

### ISSUE THREAD

**Issue by pelagrellas** [Jackett/Jackett#12958]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-02-17 16:52:14	Info	
Using HTTP Client: HttpWebClient2
2022-02-17 16:52:14	Info	
Using FlareSolverr: http://192.168.2.4:8191
2022-02-17 16:52:14	Info	
Using proxy: Disabled
2022-02-17 16:52:14	Info	
App config/log directory: C:\ProgramData\Jackett
2022-02-17 16:52:14	Info	
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
2022-02-17 16:52:14	Info	
Running in Docker: No
2022-02-17 16:52:14	Info	
Jackett variant: CoreWindows
2022-02-17 16:52:14	Info	
OS version: Microsoft Windows NT 10.0.17763.0 (64bit OS)
2022-02-17 16:52:14	Info	
Environment version: 6.0.2 (C:\ProgramData\Jackett\)
2022-02-17 16:52:13	Info	
Starting Jackett v0.20.574
```

### Description

Indexer find releases but fail when try to download torrent file

### Logged Error Messages

```text
Error downloading. indexer: newpct path: https://atomixhq.art/descargar/serie-en-hd/el-joven-wallander/temporada-2/capitulo-05-al-06/
System.Exception: BencodeParser failed
 ---> BencodeNET.Exceptions.InvalidBencodeException`1[BencodeNET.Objects.IBObject]: Failed to parse IBObject. Invalid beginning character of object. Found '<' at position 0. Valid characters are: 0-9, 'i', 'l' and 'd'
   at BencodeNET.Parsing.BencodeParser.Parse(BencodeReader reader)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Stream stream)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Byte[] bytes)
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in D:\a\1\s\src\Jackett.Server\Controllers\DownloadController.cs:line 78
   --- End of inner exception stack trace ---
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in D:\a\1\s\src\Jackett.Server\Controllers\DownloadController.cs:line 85
```

### Screenshots

![image](https://user-images.githubusercontent.com/85077900/154519086-231711ac-7234-4749-9457-ff632fb1aa3d.png)

**Comment by malomehi** [comment]
It seems that the download link is now dynamic. It changes on every click of the download button.

The generated links look like the following, including a query string with `md5` and `expires` values (which change on each click). Example:

https://atomixhq.art/t_download/temp/17022022/168553/El-joven-Wallander---Temporada-2--HDTV-720p-AC3-5-1.torrent?md5=6w0As_7Xfl26oAwN5PLXqA&expires=1645137032

So it seems that some validation has been implemented on the server side.
The `expires` value is an epoch time, in the example above this would be `Thursday, 17 February 2022 22:30:32 UTC` which indicates that the link would not be valid after that time.

How the `md5` value is generated I have no idea. This is generated on server side when the POST request is sent to the server when the download button is clicked.
But it must be related to the browser session or something like that because if this link is pasted on a separate tab in the browser it will not work.

**Comment by mikeoscar2006** [comment]
Few things to note:
1. The Expiry time is quite short, like just a couple of seconds.
2. Since the url format has changed, indexer is not properly processing the download link which can be the problem.
3. The main problem I'm facing is I haven't been able to download the torrent manually even from the site and I always get 404.  Don't think I should continue on this unless I am able to download the file atleast once manually.

**Comment by ilike2burnthing** [comment]
Torrent downloads are working ok for me. Seemingly only recent torrents are working though, just in case that was the issue for you - https://github.com/Jackett/Jackett/issues/12914#issuecomment-1032766641

**Comment by pelagrellas** [comment]
at the begining, in the case you said, last updates was working, but at this time not work anyone. i have to separate instances, one in wondows with flaresolverr and another one in a docker and connected with a VPN, doesnt work on any of two instances, no with old releases or new releases

this test is made with latest releases in indexer


![image](https://user-images.githubusercontent.com/85077900/154815719-668187b7-f04b-410f-b1f4-8ea4f17a78d6.png)


![image](https://user-images.githubusercontent.com/85077900/154815727-edcd5e4a-6459-4dc8-a91c-83854e95951f.png)

**Comment by ilike2burnthing** [comment]
Sorry, I should have been clearer, that was in response to point 3 of https://github.com/Jackett/Jackett/issues/12958#issuecomment-1046019493.

Torrent downloads are working for me on the tracker site, not Jackett.

**Comment by garfield69** [comment]
v0.20.629

**Comment by ilike2burnthing** [comment]
They've implemented a Cloudflare check when trying to download, results in the error, `Unimplemented POST Content-Type: application/x-www-form-urlencoded`.

Reopened unresolved FlareSolverr issue - https://github.com/FlareSolverr/FlareSolverr/issues/77#issuecomment-1048487916
