### ISSUE TITLE
[req]: Feature Request - select multiple results to copy download links at together

### ISSUE THREAD

**Issue by swannie-eire** [Jackett/Jackett#12964]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

at the moment if you do a search from the Jackett UI you can see the results but you can not select the download link of multiple at once.

this mean you have to copy each one and paste them into your torrent client and this can take forever.

unfortunelty auto downloaders like Sickchill, sonarr etc.. dont always find things as naming conventions can be crap on some sites e.g Show A Complete First series, Show B Season Three episode 6 etc... In these cases you may have to do manual searches from the UI to find the episodes/episodes.

### Describe the solution you'd like

being able to select multiple torrents at once and then copy all the download links for them at once so we can all all episodes/seasons at once instead of 1 by one.

**Comment by ilike2burnthing** [comment]
Presumably this when you're not doing a local download, hence having to copy and paste rather than just click to download? Are you able to use the blackhole directory instead?

What torrent client are you using that allows you to copy and paste multiple torrents links at once?

**Comment by swannie-eire** [comment]
yes not local.

is the blackhole feature not for saving torrent files to? how would that work with a search when there is only a few you want to download. would all of the results of the search not be saved to blackhole.


so currently using qbittorrent. I can add multiple with qbittorrent with the search plugin but the search plugin can be limited with filtering and does not provide you with the info of which trackers/indexers the search completed on and failed on. also the results have to be next to each other in the list of results. e.g you cant select result 1, 5. 10 etc..

**Comment by ilike2burnthing** [comment]
Add a BH directory, perform a search, you'll now be presented with an additional download button for each result:
![bh](https://user-images.githubusercontent.com/59480337/154807250-1fa5ed39-30d0-422d-8124-1505a14f42ed.png)
When clicked, rather than downloading the torrent file in the browser you're using, it will be downloaded directly to that folder on the device Jackett is running on (magnets are downloaded as .magnet files which can be opened by most torrent clients).

Configure your torrent client to watch that blackhole directory and they will automatically open all .torrent and .magnet files added to it. So you can click download on multiple torrents in Jackett's search results, and they will be added to your client without any interaction.

As far as I can tell (from a quick test of major clients) only qBit can add multiple torrents in a single C&P, the rest either only add the first, or break.

While I can add this as a feature request, there is no telling when it would be addressed, and I'm pretty sure what you want to accomplish can be done with BH.

**Comment by swannie-eire** [comment]
No unfortunely blackhole wont work for me as i have multiple qbit instances being feed from jackett. If i use blackhole it will mean that i either will still have to copy and paste for some instances or end up with dupe torrents on multiple instances.

It is something i will just have to live with as i know i have a unusual setup so i closed out this ticket.

Thanks for the help
