### ISSUE TITLE
[torrentbd] Login failed: Selector

### ISSUE THREAD

**Issue by AmazingYan-1** [Jackett/Jackett#12961]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Info Starting Jackett v0.20.529 
Info Environment version: 6.0.1 (/home/abc/Jackett/) 
Info OS version: Unix 5.4.0.26 (64bit OS) (64bit process) 
Info Jackett variant: CoreLinuxAmdx64 
Info File /etc/issue: Ubuntu 20.04.2 LTS \n \l 
Info Running in Docker: No 
0Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
Info App config/log directory: /home/abc/.config/Jackett 
Info Using proxy: Disabled 
Info Using FlareSolverr: No 
Info Using HTTP Client: HttpWebClient2
```

### Description

This is very similar to https://github.com/Jackett/Jackett/issues/6761

Not sure of i should reopen or not that why posting here. Adding this tracker is not working. While adding cookies we are getting this error - 

An error occurred while updating this indexer
Login failed: Selector "button[href="account-logout.php"]" didn't match

Let me know if you need any further details. 

### Logged Error Messages

```text
An error occurred while updating this indexer
Login failed: Selector "button[href="account-logout.php"]" didn't match
```

### Screenshots

https://ibb.co/580XrFF

**Comment by garfield69** [comment]
the indexer is working for me which suggests the issue is at your end.
- use the trashbin on the jackett indexers page to remove your active indexer.
- use your browser to login afresh to the website. Make sure you have the **remember me** _ticked_ and the **log me out if ip changes** _unticked_.
- fetch the whole cookie and add the indexer afresh with the wrench on the jackett add-indexer page and see if you can make it work.
- If it fails then read https://github.com/Jackett/Jackett/wiki/TroubleShooting/#your-cookie-did-not-work carefully , especially the notes to see if anything there applies to you.

**Comment by AmazingYan-1** [comment]
thanks @garfield69 unticking log me out if ip changed options resolved the issue. May be consider adding this as a small warning when it fails?

**Comment by garfield69** [comment]
Pointless to add it when it fails as there are a multitude of reasons why a cookie may not work.
However I could add it to the indexer config as a info box to remind users of the best settings for login.
