### ISSUE TITLE
[MorethanTV][mtv] torrent size wrong if more than 1 result per season/episode.

### ISSUE THREAD

**Issue by swannie-eire** [Jackett/Jackett#12977]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
docker container.
Jackett Version v0.20.590
```

### Description

If more than one episode/pack is available MTV seems to show the combined size.

Im not sure if it will be possible for jackett to parse each packs size instead of the combined size as this info does not seem available unless you go into the search result in MTV but if not maybe it would be a better idea instead of showing the combined size for multiple packs/episodes to show their sizes as 0 instead of giving incorrect results
![Screenshot 2022-02-21 at 11 13 44](https://user-images.githubusercontent.com/57441681/154946098-940509ff-205d-4d1b-a0bc-eadeceefcf69.png)
![Screenshot 2022-02-21 at 11 22 21](https://user-images.githubusercontent.com/57441681/154946120-e9cf1e28-610a-4665-911f-e0e261cc17b0.png)
![Screenshot 2022-02-21 at 11 13 59](https://user-images.githubusercontent.com/57441681/154946127-c908bd3d-d8e2-47e1-9d35-8ad915da9b0a.png)
.

### Logged Error Messages

```text
none
```

**Comment by ClandestineClout** [comment]
I doubt I can add more information but I can confirm MTV results always show up at the top of the sorted file size list with results showing double the file size or something that they actually are on site.

**Comment by garfield69** [comment]
The mtv torrent search page only contains a group summary of the seeds, leechers, size, files and date for each title group, followed by a .torrent download link for each individual torrent associated with the group.
To get the individual data for each torrent in the group we would need to make an additional http GET request for each group title, to fetch the relevant details page, and process the individual torrent data presented there.
This would mean that in addition to the one http GET we make of the torrent search page, we would need to make an additional 100 http GET requests, one for each of the title groups details pages present in the torrent search page, in order to process the full individual torrents data details.
For obvious reasons this is impractical, and would most likely quickly have your account suspended as a potential DDoS spammer.

providing 0 byte sizes for torrents is not a good idea, as many torznab apps that make requests to Jackett indexer will ignore returned torrents of 0 size, treating them as incomplete and un-downloadable torrents.

While mtv continues to use their hybrid luminance engine, without providing a personal setting to display each torrent individually in results (as most other luminance and gazelle engine sites are capable of doing), there is little that can be done from the Jackett side of the session.
