### ISSUE TITLE
[req]: JSON result support

### ISSUE THREAD

**Issue by B1773rm4n** [Jackett/Jackett#13108]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

I'm using Jackett standalone and doing my requests directly via curl to it.
The results I'm receiving are XML - which are bothersome to handle.

### Describe the solution you'd like

Example API call:

`https://jackett.domain.com/api/v2.0/indexers/indexer/results/torznab/api?apikey=myapikey&t=search&format=json`

And then I receive the results as JSON.
I am aware this would not be Torznab compatible but it's an optional feature for user which interact directly with Jackett.

### Describe alternatives you've considered

Else I have to handle XML which is unusual for most user since JSON is a defacto standard. If I would have a jq for XML that would be fine. But sadly there is no universal and convenient for XML as there is for JSON with jq.

**Comment by garfield69** [comment]
re: json response: https://github.com/Jackett/Jackett/issues/921#issuecomment-271276823
that comment was back in 2017 when the author was still available. He has left the project not long after.
Since then there has not been any C# volunteers available or interested in implementing this.
I'll leave this open as an enhancement request, perhaps this fresh ticket will inspire some to contribute.

**Comment by B1773rm4n** [comment]
Main issue: #921
