### ISSUE TITLE
[req]: RuDub release name parser improvements

### ISSUE THREAD

**Issue by SuberSeb** [Jackett/Jackett#13102]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

RuDub.TV changed their naming logic, release names in Jackett looks like this '(The Resident)s05e01-16 (HD 1080p WEBDL) - rus'. From time to time Sonarr can't recognize the title.

### Describe the solution you'd like

Final result should looks like this ' The Resident - s05e01-16 (HD 1080p WEBDL) - rus'. I think this title should be recognized by Sonarr correctly. Or we should return to previous release name format - 'Big Sky s01e01-05 HD 1080p WEBDL - rus'

**Comment by garfield69** [comment]
You forgot to mention that the reason there are brackets around the title now is because the official title on the web site is prefixed with the Russian title first, English in brackets, etc.
And the reason you are seeing what you reported is because you have enabled the strip-Russian option in the indexer config.
![image](https://user-images.githubusercontent.com/6933240/161370321-947154d9-6b39-48f4-976a-c2b4ba890feb.png)
Still, it should be a simple matter to replace the brackets with spaces and trim the title to remove leading spaces.
I'll amend the indexer for the next release.

**Comment by SuberSeb** [comment]
Thank you Garfield.

**Comment by ilike2burnthing** [comment]
[v0.20.788](https://github.com/Jackett/Jackett/releases/tag/v0.20.788)

**Comment by SuberSeb** [comment]
Parsing for RuDub is broken. Release name example: Chicago Fire 10 01-18 HD 1080p WEBDL - rus. Sonarr can't recognize that release.

**Comment by garfield69** [comment]
The site previously used: 
`Лучше звоните Солу (Better Call Saul) s06e01-02 (WEBRip XviD) (Обновляемая) (Золото)`
now:
`Лучше звоните Солу (Better Call Saul) Сезон 6 Серии 01-02 (WEBRip XviD) (Обновляемая) (Золото)`

**Comment by garfield69** [comment]
v0.20.932

**Comment by SuberSeb** [comment]
@garfield69 can you please check parsing for Rudub? Seems we have issue with brackets and russian letters not trimmed.

Example: 
![image](https://user-images.githubusercontent.com/49331864/232666462-74c57d2d-28dd-4027-b383-f8e0286dbf44.png)

**Comment by garfield69** [comment]
@ilike2burnthing  you last made update to rudub via #14245 a week or so ago, please cross check. thanks.

**Comment by ilike2burnthing** [comment]
Well timed, just firing up Windows Sandbox ;)

**Comment by ilike2burnthing** [comment]
Oh, I don't need it, it's working fine. @SuberSeb reconfigure the indexer, enable `Strip Cyrillic Letters`, click `Okay` and test again.

**Comment by SuberSeb** [comment]
@garfield69 @ilike2burnthing confirmed. Thank you guys
