### ISSUE TITLE
可以搜索种子，但是无法正常下载种子

### ISSUE THREAD

**Issue by remember-ma** [Jackett/Jackett#13179]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
ENV 	
AUTO_UPDATE 	true
HOME 	/root
HOST_OS 	Unraid
LANG 	en_US.UTF-8
LANGUAGE 	en_US.UTF-8
PATH 	/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PGID 	100
PUID 	1000
RUN_OPTS 	run options here
TERM 	xterm
TZ 	Asia/Shanghai
UMASK 	000
XDG_CONFIG_HOME 	/config
XDG_DATA_HOME 	/config
```

### Description

springsunday可以搜索种子，但是无法正常下载种子

### Logged Error Messages

```text
04-19 12:27:49 Error Error downloading. indexer: springsunday path: https://springsunday.net/download.php?id=309460

System.Exception: BencodeParser failed

 ---> BencodeNET.Exceptions.InvalidBencodeException`1[BencodeNET.Objects.IBObject]: Failed to parse IBObject. Invalid beginning character of object. Found '<' at position 0. Valid characters are: 0-9, 'i', 'l' and 'd'

   at BencodeNET.Parsing.BencodeParser.Parse(BencodeReader reader)

   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Stream stream)

   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Byte[] bytes)

   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 97

   --- End of inner exception stack trace ---

   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 97
```

**Comment by garfield69** [comment]
Have you downloaded anything from the springsunday web site before?
The first time you download using the web site you are presented with a first-time-download page which you must accept before continuing.
If you have not done so, then you will not be able to use the Jackett indexer for this site, since it expects the download link to lead directly to a torrent.
If you have downloaded before, and you are still getting this error with the indexer, then please provide a full enhanced log so we can take a look at the HTML and debug messages, which will hopefully give a clue to what is going on.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.

**Comment by remember-ma** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/8510548/log.txt)

**Comment by garfield69** [comment]
When Jackett follows the download link found at the web site, instead of a torrent the web site presents:
Returning Redirect => https://springsunday.net/downloadnotice.php?torrentid=309460&type=firsttime 49557 bytes
Which means that you have not previously downloaded a torrent using the web site and accepted the download notice correctly.

**Comment by remember-ma** [comment]
> When Jackett follows the download link found at the web site, instead of a torrent the web site presents: Returning Redirect => https://springsunday.net/downloadnotice.php?torrentid=309460&type=firsttime 49557 bytes Which means that you have not previously downloaded a torrent using the web site and accepted the download notice correctly.

事实上，我已经在web页面下载了很多个种子

**Comment by remember-ma** [comment]
> > When Jackett follows the download link found at the web site, instead of a torrent the web site presents: Returning Redirect => https://springsunday.net/downloadnotice.php?torrentid=309460&type=firsttime 49557 bytes Which means that you have not previously downloaded a torrent using the web site and accepted the download notice correctly.
> 
> 事实上，我已经在web页面下载了很多个种子

我点开刚刚的页面后，确实跳出第一次下载的提示页面，然后我重新下载了这个种子。目前我使用正常了

**Comment by remember-ma** [comment]
> > When Jackett follows the download link found at the web site, instead of a torrent the web site presents: Returning Redirect => https://springsunday.net/downloadnotice.php?torrentid=309460&type=firsttime 49557 bytes Which means that you have not previously downloaded a torrent using the web site and accepted the download notice correctly.
> 
> 事实上，我已经在web页面下载了很多个种子

**Comment by garfield69** [comment]
When you get the download notice, do not jump out, but click on the ok button or what ever button it presents that lets you start the download. 
Once the site has registered that have have accepted the notive it will not present it again, and you then should be able to start using the jackett indexer for downloading.
I am guessing that since you have now closed this ticket, you have figured this out ;-)
