### ISSUE TITLE
[req]: https://tmghub.org/

### ISSUE THREAD

**Issue by coolvicky2** [Jackett/Jackett#13184]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: TmGHuB
- URL: https://tmghub.org/
- Description: Indian Regional and Bollywood Content
- Minimum Seeding Time and Minimum Ratio (if Private): 2 Hour Minimum
- Additional Comments:
```
Engine: Xbtit
TmGHuB (TH) is an INDIAN Private Torrent Tracker for MOVIES / TV / GENERAL
MR 0.7 MST 2h

**Comment by garfield69** [comment]
There is an application for membership form, but I'm not jumping through those hoops since I since have a presence on the scene.
If you send an invite to garfieldsixtynine -at- gmail.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by coolvicky2** [comment]
i don't have invite however i can lend you my account if you don't mind
doing that , invite are closed they've closed them so unfortunately i'm
unable to get it done , tried for few days and i'm unable to get it done

**Comment by garfield69** [comment]
Sure. Email me details and I'll have a go building the indexer.

**Comment by coolvicky2** [comment]
http://tmghub.org
user:  johndel
password:  milla2147

**Comment by garfield69** [comment]
The indexer will get published in the next release of Jackett due out in about 23 hours.
Please change your account password to restore privacy.

**Comment by garfield69** [comment]
v0.20.986
