### ISSUE TITLE
[req]: kufirc.com

### ISSUE THREAD

**Issue by tn9ae** [Jackett/Jackett#13191]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: Kufirc
- URL: https://www.kufirc.com/
- Description: Kufirc is is a HUNGARIAN Private tracker for 3X
- Minimum Seeding Time and Minimum Ratio (if Private): Mandatory rate is calculated based on the amount of data downloaded - max 0.5, no MST
- Additional Comments: engine - Luminance
```

**Comment by ilike2burnthing** [comment]
@garfield69 why do some 3X-only indexers have `tv-search` and `movie-search` modes, while others do not?

**Comment by garfield69** [comment]
>why do some 3X-only indexers have tv-search and movie-search modes, while others do not?

Apart from Whisparr (and I don't know what this 3X Arr app uses for its Torznab queries), I expect (but never research to confirm) that you could not add 3X titles to Sonarr or Radarr so adding TV and Movie search caps seemed pointless.
If any indexer dedicated to only 3X, has TV and/or Movie search caps then this is more than likely included only because a regular indexer was initially used as a template.

That said, if you want to check what Whisparr uses, or if you find that Sonarr or Radarr could be used to search for 3x titles, then I suppose we should add the relevant torznab search caps.

**Comment by ilike2burnthing** [comment]
At one point they were purposefully added, so I had wondered about some sort of application compatibility - fa9db90d56361a6c17f9e09f820dff8419c0c299

Best just to remove them then?

**Comment by garfield69** [comment]
I'd forgotten I did that, don't remember why I did. There's not PR or ticket so it wasn't a request. %-/
Getting old, memory fading, must be too much porn watching rotting the mind. ;-b
Leave them for now until I take a look at Whisparr and see what it's torznab requirements are.

**Comment by garfield69** [comment]
@Qstick  is whisparr vaporware or is there a windows package repo someplace?
was wondering what torznab queries this arr makes and if we should be adding movie and/or tv search support to our Jackett 3x indexers. Thanks for any info.

**Comment by Qstick** [comment]
Hehe, not vaporware, we have nightly builds. Currently it makes only t=search inquiries. Since movie searches were hit or mis with adult content I disabled them.

**Comment by garfield69** [comment]
>Best just to remove them then?

yes

**Comment by garfield69** [comment]
v0.20.985
