### ISSUE TITLE
[req]: Sort by Oldest (age) or Smallest (size) from all torrents

### ISSUE THREAD

**Issue by B1773rm4n** [Jackett/Jackett#13192]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

I want to have a list either the oldest torrents or the smallest torrents (filesize) from all available torrents from one tracker.

Make a wildcard/empty search and then sort by size/age and get the first page of results then

It's currently not possible with Jackett since it uses the first page of a specific search result in most cases.

### Describe the solution you'd like

Enable to make a search based on age or size. It is possible on the website of most/all tracker

**Comment by garfield69** [comment]
This is already available from most indexers.
Use your Jackett dashboard to edit the config for your indexer, and as long as the config supports the `Sort Requested From Site` option, you can select `created` or `size` in `asc` or `desc` order.
This will include your sort settings in your search query to the indexers corresponding web site.
If the indexer does not have these options, then specify the indexer, as the options may well be available on the web site but not added to the indexer yet, and we will see if the indexer can be updated.
Note that if you are using the Jackett dashboard to view search results, then you may want to align its sort presentation to match your indexer settings. The dashboard sort is applied after the results are fetched from the site, the default presentation is created desc, i.e. newest torrents first.

**Comment by B1773rm4n** [comment]
Thank you for the very good response.
Is there a way in which I don't have to reconfigure the indexer?
An alternative approach might be to add the indexer multiple times with different sorting - would that be possible?

Why is that part of the indexer config and not of the search query? Similar with the freeleeches. It doesn't make sense from a UI perspective that I have to change it in the indexer instead to choose it to the searches I want to do.

**Comment by B1773rm4n** [comment]
I just see it's blocked to add the same indexer a second time. Why?

**Comment by garfield69** [comment]
>Why is that part of the indexer config and not of the search query? Similar with the freeleeches 

The sort settings are specific to each indexer, as not all the web sites provide exactly the same method and sort options. So its not practical to drive it from the dashboard search page, because that page has to have a universal presentation for all the indexers, and since the parameters are going to be different from web site to web site there will not be one constant sort parameter that applies.
For instance, some site use keyword name such as sort, order, sortby and labels such as published, added, created etc. and sort direction could be type, direction, order, and labels line asc/desc, or new/old or a/d  etc.
Same with the freeleech. Each site may have different ways to flag a freeleech and only the indexer is configured specifically for the web sites knows the specific requirements. Adding a freeleech parm to the dashboard search page is not practical.

>Is there a way in which I don't have to reconfigure the indexer?

Possible for the yml indexers but cumbersome. Not simple for the C# indexer.
for yaml, you could  copy the source in the definitions folder, give it a unique source name, edit the source and alter the id and name, and you should be good to go.
However, only the original indexer will get updates, so you will need to maintain your clones yourself. Cumbersome.

>I just see it's blocked to add the same indexer a second time. Why?

the internal id of the indexer is what identifies it to Jackett and has to be unique. Clones of indexers need a unique id to differentiate it from the others otherwise cache control and serialisation of resources will get cross contaminated by the other indexers with the same id.

**Comment by B1773rm4n** [comment]
Thank you for the detailed information. So what I need is not possible right now.
