### ISSUE TITLE
Provider T411 new domain name .al

### ISSUE THREAD

**Issue by Miloune** [Jackett/Jackett#1325]
Hello,

Wanted to try Jackett today, with T411 provider but they apparently changed their domain name again..
Insted of "t411.ai" it's "t411.al".
I tried to change "Site Link" value to https://t411.al but i can see in Jackett log it try to connect to the old domain name : 05-03 19:43:39 Debug IWebClient.GetString(Url:https://api.t411.ai/auth)

Can you help me? 
Thanks in advance.

Jackett version:  0.7.1321.0
Mono version (if not using Windows):  4.8.1

**Comment by siwon** [comment]
#1326

**Comment by PlqnctoN** [comment]
Yep, now we just need to wait until the maintainers decide to compile and release a new version with this change included! I don't really know much about the inner working of the project but what would be great is to be able to modify the domain name ourselves from the interface because the Hadopi (a french government agency) is really trying to block t411 in france (by asking ISPs to block the domain name) so they often change their domain.

**Comment by kaso17** [comment]
there's anew pre release containing the change. T411 is a little special due it it's API usage (ignoring the configured URL). If it keeps happening we should be able to fix that.

**Comment by OppieTV** [comment]
Hi,

See few posts about T411 but i'm confused : yesterday, everything alright on my jackett. 
Today, fresh install of new server and jackett
T411 on indexer's list with right url but when i try to add T411, i have this : 

" Configuration failed: Found no results while trying to browse this tracker"

Jackett version : 0.7.1477.0

Any idea ?

**Comment by PlqnctoN** [comment]
@OppieTV T411 is dead, see here: http://www.numerama.com/politique/270988-t411-lenquete-internationale-qui-a-mis-fin-a-un-des-plus-importants-reseaux-de-piraterie.html

**Comment by raspdealer** [comment]
t411 is down

**Comment by JigSawFr** [comment]
T411 busted, definition will be wiped.
