### ISSUE TITLE
1337x.to is broken System.Exception: Download selectors didn't match

### ISSUE THREAD

**Issue by silverbullettruck2001** [Jackett/Jackett#13260]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /home/worktruck/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
File /etc/issue: Ubuntu 20.04.4 LTS \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.13.0.44 (64bit OS) (64bit process)
Environment version: 6.0.5 (/opt/Jackett/)
```

### Description

When I try search for releases to download from `1337x.to`, errors are thrown saying `System.Exception: Download selectors didn't match` and the download is unsuccessful.  If I manually go to the site that was identified for `1337x.to` it works fine.

### Logged Error Messages

```text
-05-27 14:34:50	Error	
Error downloading. indexer: 1337x path: https://1337x.to/torrent/5268503/Stranger-Things-S04E05-720p-WEB-x265-MiNX-TGx/
System.Exception: Download selectors didn't match
   at Jackett.Common.Indexers.CardigannIndexer.Download(Uri link) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1879
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 56
2022-05-27 14:34:50	Error	
CardigannIndexer (1337x): Download selectors didn't match:
2022-05-27 14:34:49	Error	
CardigannIndexer (1337x): An exception occurred while trying selector ul li a[href^="http://itorrents.org/"], retrying with next available selector
2022-05-27 14:34:49	Error	
Failed download response:
2022-05-27 14:34:49	Error	
Failed download cookies: 
2022-05-27 14:34:21	Info	
Torznab search in 1337x => Found 20 releases (from cache)
```

### Screenshots

**Comment by garfield69** [comment]
This is not the indexer's fault. 
If you visit https://1337x.to/torrent/5268503/Stranger-Things-S04E05-720p-WEB-x265-MiNX-TGx/
and click in the **torrent download** link to expand the list, then click on the **itorrents mirror** you get redirected to https://www.limetorrents.lol/home which is itorrents.org fallback when it does not have the magnet converted to a .torrent in its database.
This occurs because it can take itorrents.org up to 4 hours to be up to date with the latest releases.

You can either postpone your downloads for a while ant try later, or you can edit the 1337x indexer config using your Jackett dashboard and switch the order of the download links to do magnet first instead of itorrents.
