### ISSUE TITLE
Aggregate fails when one indexer fails

### ISSUE THREAD

**Issue by raspdealer** [Jackett/Jackett#1332]
I think this is my problem as T411 is dead, all aggregate get error 500.
Sounds logic but need some security I guess.

17-5-4 21:05:14.0|Trace|HttpClient|Res: [GET] http://192.168.1.116:9118/torznab/all/api?t=search&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100&q=fargo%201996: 500.InternalServerError (5899 ms)
17-5-4 21:05:14.0|Warn|HttpClient|HTTP Error - Res: [GET] http://192.168.1.116:9118/torznab/all/api?t=search&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100&q=fargo%201996: 500.InternalServerError
17-5-4 21:05:14.1|Warn|Torznab|Jackett HTTP request failed: [500:InternalServerError] [GET] at [http://192.168.1.116:9118/torznab/all/api?t=search&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100&q=fargo%201996]
17-5-4 21:05:14.1|Debug|NzbSearchService|Total of 0 reports were found for [Fargo] from 1 indexers

**Comment by chibidev** [comment]
@raspdealer thanks for the report. This had been already addressed in #1324 . @kaso17 will merge it and your issue will be resolved.

**Comment by robgates** [comment]
Guys , think I have missed something how to you get it to use the Aggregate index ?

**Comment by raspdealer** [comment]
Just add /all instead of the tracker name

**Comment by raspdealer** [comment]
Thanks guys for the fix

**Comment by chibidev** [comment]
@raspdealer please confirm, but I think the issue can be closed.

**Comment by adamwinn** [comment]
Can we get a button on the main GUI for this?  Without that, I don't think people are going to even know this exists.

**Comment by chibidev** [comment]
@adamwinn TBH it was never my intention to give a full-fledged solution for this, as it's still unclear to me whether this feature is actually wanted in Jackett or not. I personally liked @kaso17's idea about the possibility to group configured indexers and provide more metaindexers other than just the all one, however I don't know whether that's decided upon (although if yes, I would happily jump in to implement it).
In my opinion there're still quite a few questions to answer about the /all feed being actually usable in the long run, so for me I think it's ok that it exists in a quite invisible way. I'd make it visible once it becomes more mature.
My next thing to do is to give a little performance boost for the /all feed (if you have many indexers configured it tends to become rather slow).

**Comment by raspdealer** [comment]
@chibidev I agree with your point of view. About grouping, I think one other interesting feature could be the ordering.

Currently I have 5 separated Jackett source  in my Sonarr client.
Sonarr don't want to introduce a priority order in term of source because of them it's just about getting result.
But I really need to check some indexers before others.

It will be great to order aggregate results by Tracker order (define by the user, not alpha)

This will let user give priorities to the aggregated feed.

**Comment by kaso17** [comment]
@chibidev I still consider a grouping feature useful and if you're willing to implement it that would be highly appreciated. I also agree that we should keep the current implementation invisible.

My personal approach of implementing it was to make significant changes to the core instead of implementing it as a new indexer. Essentially adding a PerformQuery(List<IIndexer>) method to IndexerManagerService which takes care of querying multiple indexers. The current approach of comparing the SiteLink with the Download link to find the original indexer is a little hackish to. We should just store a reference to the corresponding indexer for each result item.
I would also use an indexer name prefix to avoid future name conflicts e.g. "group-all" instead of just "all". And probably another prefix for user defined groups "group-custom-xyz".

**Comment by chibidev** [comment]
@kaso17 Out of curiosity, is there a specific reason you'd be going in this direction? I'm interested because I might go in a different direction, but if there's a good reason you'd argue implementing it this way I have no problem doing so.
The main reason I went with a special type of Indexer with the Aggregate is that I associated the main functionality of any Indexer with PerformQuery, and so it made sense not to associate another type/class with that to keep SRP.

**Comment by kaso17** [comment]
For pagination (torznab limit/offset) support we'll probably have to do similar core changes anyway. But I've no problem with the current MetaIndexer approach either (Except of the Download link/Site link matching).

**Comment by chibidev** [comment]
@kaso17 yes, that's something that's been bugging me ever since I started contributing, I just didn't want to focus on small details until the approach was mature enough. But expect improvements in that regards and the results provided by the meta indexers (that's my current focus; after that I'll finish the grouping feature).
