### ISSUE TITLE
Indexer "torrentdownloads" search results are all published "1 min" ago.

### ISSUE THREAD

**Issue by jobrien2001** [Jackett/Jackett#13344]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Docker: Yes, Linuxserv
Jackett Version v0.20.1261
```

### Description

According to jackett, Indexer "torrentdownloads" search results are all published "1 min" ago.

If you check the link of each result, you can see the real "Torrent added" date at "torrentdownloads" website.

### Logged Error Messages

```text
No errors, just inaccurate information displayed
```

### Screenshots

![image](https://user-images.githubusercontent.com/12868319/177677539-a1a64a5b-a299-4bd8-9635-8f40940a6532.png)

**Comment by garfield69** [comment]
that is because this site does not present the date in their search results
![image](https://user-images.githubusercontent.com/6933240/177683899-80ffd076-4676-4df2-87cd-2a7407b6108b.png)
so Jackett adds a `now` date, which can be 0m ago but sometimes `1m ago` if it takes Jackett a little longer to get a response from the site from the time the request was made.
