### ISSUE TITLE
Anime search not working with T411

### ISSUE THREAD

**Issue by Olived-fr** [Jackett/Jackett#1339]
Hello,

I just wanted to know if it was normal that the anime search with the provider T411 isn't working. Even after adding the category in Sonarr, it doesn't find anything.

Thank you  in advance.

Jackett Version 0.7.1340.0
Mono Version 4.6.2.7-8

**Comment by wilfriedarma** [comment]
For anime search, use category 5070 in the anime field. Afterwards, for t411, it has always been capricious for anime, because it has no specific title format, for example: use the title or the languages.
If you use jakett, since the domain change, it no longer works with T411 even when changing the domain name, I personally use the cardigann proxy.

**Comment by kaso17** [comment]
@wilfriedarma with the latest pre release it should work (after changing the URL/re configuring it)
