### ISSUE TITLE
[req]: add genres to the caps for torznab

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#13405]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Currently the use of genre on torznab queries does not follow the specifications, in that the torznab capabilities section does not contain a list of valid genre that the indexer supports and that the apps using torznab can reference when determining what genre they are allowed to use in queries to the indexer.

### Describe the solution you'd like

To properly support genre, we should be following the torznab specs, which specifies that the torznab capabilities section should contain a list of the individual genre that the indexer supports accepting queries for, and which coincidentally can be used to validate what is returned in the release.genres too (for those sites that may not have their genre buttoned down properly like krazyzone).

So the idea here is that, for example, the yaml definition would have in the caps section a genres block with a string containing a comma delimited list of the genre the site supports searching for, or presenting in its torrent row results, and the torznab t=caps would contain this list so that apps know which genre it is allowed to use on the torznab queries it makes to the indexer.

To implement this properly is currently beyond my ken, this needs a proper understanding of C# and the torznab *.cs parts that comprise the whole enchilada.
I could hack something up but I feel it would break a whole bunch of common standards that should be followed when doing this stuff.

### Describe alternatives you've considered

@Qstick @bakerboy448 @ngosang volunteers?

**Comment by Qstick** [comment]
I can appreciate wanting to stay tight to newznab spec, In this case I’d question the necessity of this for a few reasons.

1. it’s adding extra complexity that you have to manage on a per indexer level, with really no current use case outside of manual search.
2. I’m not sure that leaving genre search as a string or string list really hurts anything, searching stays easy, results stay easy
3. Genre search handling arr app side is unlikely to become a thing. And if it does, it’ll just be a string. Otherwise we have to handle and normalize the set of genres from each indexer. What happens when a /all search is performed. This would essentially need to be setup like categories with standardization and mapping, and it seems like more trouble than it’s worth given it’s never been requested on any of our apps.

Do you guys have users that are pushing for this?

**Comment by garfield69** [comment]
>Do you guys have users that are pushing for this?

Nah, no user requests so far.
I thought it would help us with implementing unit3d genre searching and validating responses from krazyzone, but I appreciate that the task would not be a simple matter (otherwise I would have done it myself ;-)

But in this period where C# devs for this project are scarce, fair enough, I'm going to close it, and who knows, if popular demand develops for the genre search we can always revisit. Thanks.

**Comment by Qstick** [comment]
Agree, we can visit it. It's doable, I just hate to see you have to manage genres on 500 Indexers if it's not going to be used.
