### ISSUE TITLE
[req]: New indexer MarcianoTorrent [ES]

### ISSUE THREAD

**Issue by octaviz** [Jackett/Jackett#13503]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: MarcianoTorrent
- URL: https://marcianotorrent.com
- Description: TV Shows & Movies torrents
- Minimum Seeding Time and Minimum Ratio (if Private): 
- Additional Comments: It could be a simple indexer to implement, no pop-ups, no ads, no crazy multi-windows, click +click, Spanish language torrents, similar to DonTorrent indexer.
```

**Comment by garfield69** [comment]
site uses a one-poster-many-torrents design, so it is not suitable for indexing.
the main search returns just posters, with no title, seeders, leechers, grabs, published date, size, rjust a description, a poster image and a link to the details page.
we are not going to fetch the details page of every poster in the search results in order to populate the jackett indexer search page with the required data, as that would mean fetching a minimum of 50 details pages every time a keywordless search is performed.
closing as no suitable.
