### ISSUE TITLE
[req]: GGN API

### ISSUE THREAD

**Issue by ItsME6969** [Jackett/Jackett#13544]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Would like to request GGN API. Already on prowlarr so I think it can be brought over too.
https://github.com/Prowlarr/Prowlarr/commit/efffeebe7c2c09f48c9b400883b5ebc22cd0a9ed

### Describe the solution you'd like

API requests instead of scraping which the site is not a fan of

**Comment by garfield69** [comment]
Unlike the yml indexers which can be ported between Prowlarr and Jackett freely, indexers requiring C# are not as straight forward to port, due to the different design philosophies between the two.
Replacing the current GazelleGames C# html scraper with one that uses the site's API will require a volunteer C# dev.

**Comment by mikeoscar2006** [comment]
Hey Everyone, It's been a long time and wanted to look into some issues.

So there is a GazelleTracker BaseClass which is based on Orpheus's API Documentation but the GGn API is considerably different ( following the same pattern at most places but still different at rest).

My first idea was to make the base tracker class more adaptable so both the trackers can share a similar codebase but the differences continue on increasing.
Hence I'm facing the following dilemma:
1. Completely build a separate GGn API Indexer class (Would feel like a lot of code redundancies though)
2. Continue adapting the base GazelleIndexer class so that future indexers can take benefit too

Would be interested in knowing your views @garfield69 @ilike2burnthing

**Comment by ilike2burnthing** [comment]
Awaiting testing upon next release before closing this issue.

**Comment by ItsME6969** [comment]
sorry was waiting for the linuxserver to update and been abit caught up...anyway...searches seem fine to me although 
1) the results are still encoded eg Assassin&#39;s Creed
2) (the pedant in me) the tracker appears as GazelleGamesApi instead of Gazelle Games (API) like the other trackers with an api
I'll keep on testing and will report back in time otherwise it works fine to me

**Comment by ilike2burnthing** [comment]
@mikeoscar2006 can you add a urldecode filter to the titles, and make that minor edit to the indexer name?

**Comment by ilike2burnthing** [comment]
Ta Mike.

@ItsME6969 fix will be in the next release, due out in ~19hrs, and the linuxserver image updates are typically within an hour of that. If you have any further issues, feel free to let us know.

**Comment by ItsME6969** [comment]
Np thanks alot everyone.

**Comment by garfield69** [comment]
v0.20.2019

**Comment by ItsME6969** [comment]
@mikeoscar2006 For some time now I haven't been able to use the API can you confirm yours still works? I've tried regenerating new keys but all I'm getting is Parsing errors `Your API Key did not work: Parse error`. Thanks

**Comment by Smoukus** [comment]
> @mikeoscar2006 For some time now I haven't been able to use the API can you confirm yours still works? I've tried regenerating new keys but all I'm getting is Parsing errors `Your API Key did not work: Parse error`. Thanks

I get the same error.

**Comment by ilike2burnthing** [comment]
@Qstick do you have an account? @mikeoscar2006 is the only one of us who does and they're not available at the moment. Would you be able to take a look?

**Comment by Qstick** [comment]
I do not, sorry

**Comment by PNWebster** [comment]
Working for me, using freshly generated API keys and Jackett v0.20.2297

**Comment by garfield69** [comment]
v0.20.4207

**Comment by ilike2burnthing** [comment]
https://gazellegames.net/login.php - 502 Bad Gateway
https://gazellegames.net/register.php - working

https://ggn.trackerstatus.info/ shows as offline for the last 6hrs

**Comment by garfield69** [comment]
status page indicates the site is back online, can you confirm?

**Comment by garfield69** [comment]
https://gazellegames.net/ > Site is currently down for maintenance! Please check back soon.

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
@mynameisbogdan according to my topTBdev news feed, GGN may have updated their P2P release types, which may mean that the categories could need updating. Can you check and update if necessary? thanks.
