### ISSUE TITLE
[mteamtp] (updating) The operation was canceled.

### ISSUE THREAD

**Issue by yjiawqgj** [Jackett/Jackett#13561]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-09-20 21:02:03	Info	Using HTTP Client: HttpWebClient2
2022-09-20 21:02:03	Info	Using FlareSolverr: http://10.10.10.100:8191
2022-09-20 21:02:03	Info	Using proxy: Disabled
2022-09-20 21:02:03	Info	App config/log directory: /config/Jackett
2022-09-20 21:02:03	Info	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2022-09-20 21:02:03	Info	Running in Docker: Yes (image build: v0.20.1915-ls77)
2022-09-20 21:02:03	Info	File /etc/issue: Ubuntu 20.04.4 LTS \n \l
2022-09-20 21:02:03	Info	Jackett variant: CoreLinuxAmdx64
2022-09-20 21:02:03	Info	OS version: Unix 4.4.180.0 (64bit OS) (64bit process)
2022-09-20 21:02:03	Info	Environment version: 6.0.9 (/app/Jackett/)
2022-09-20 21:00:21	Info	Starting Jackett v0.20.1915
```

### Description

Sites with image verification codes can be added normally, but this site has been getting various errors.

### Logged Error Messages

```text
System.OperationCanceledException: The operation was canceled.
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 179
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 221
   at Jackett.Common.Indexers.BaseWebIndexer.RequestLoginAndFollowRedirect(String url, IEnumerable`1 data, String cookies, Boolean returnCookiesFromFirstCall, String redirectUrlOverride, String referer, Boolean accumulateCookies, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 549
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 562
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 992
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 113
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

### Screenshots

![image](https://user-images.githubusercontent.com/71002956/191467023-0701fae7-aa90-4845-8830-54df35269f7c.png)

**Comment by ilike2burnthing** [comment]
Sign out of the tracker's site and sign back in. Delete the indexer from Jackett, restart the Jackett container, and try adding the indexer again.

If you have enabled 2FA, you will instead need to use the MTeamTP2FA indexer.

**Comment by njunghausz** [comment]
I'm getting the same error with TorrentDB. Even the configure/add goes to timeout.

Sep 21 17:38:14 host jackett[1488066]: 09-21 17:38:14 Error Jackett.Common.IndexerException: Exception (torrentdb): A task was canceled.
Sep 21 17:38:14 host jackett[1488066]:  ---> System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
Sep 21 17:38:14 host jackett[1488066]:  ---> System.TimeoutException: A task was canceled.
Sep 21 17:38:14 host jackett[1488066]:  ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
Sep 21 17:38:14 host jackett[1488066]:    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
Sep 21 17:38:14 host jackett[1488066]:    at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Sep 21 17:38:14 host jackett[1488066]:    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
Sep 21 17:38:14 host jackett[1488066]:    at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Sep 21 17:38:14 host jackett[1488066]:    at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Sep 21 17:38:14 host jackett[1488066]:    at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Sep 21 17:38:14 host jackett[1488066]:    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
Sep 21 17:38:14 host jackett[1488066]:    --- End of inner exception stack trace ---
Sep 21 17:38:14 host jackett[1488066]:    --- End of inner exception stack trace ---
Sep 21 17:38:14 host jackett[1488066]:    at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
Sep 21 17:38:14 host jackett[1488066]:    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
Sep 21 17:38:14 host jackett[1488066]:    at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 179
Sep 21 17:38:14 host jackett[1488066]:    at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 186
Sep 21 17:38:14 host jackett[1488066]:    at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 512
Sep 21 17:38:14 host jackett[1488066]:    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1414
Sep 21 17:38:14 host jackett[1488066]:    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 310
Sep 21 17:38:14 host jackett[1488066]:    --- End of inner exception stack trace ---
Sep 21 17:38:14 host jackett[1488066]:    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 322
Sep 21 17:38:14 host jackett[1488066]:    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 677
Sep 21 17:38:14 host jackett[1488066]:    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 309
Sep 21 17:38:14 host jackett[1488066]:    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
Sep 21 17:38:14 host jackett[1488066]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Sep 21 17:38:14 host jackett[1488066]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Sep 21 17:38:14 host jackett[1488066]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Sep 21 17:38:14 host jackett[1488066]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Sep 21 17:38:14 host jackett[1488066]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Sep 21 17:38:14 host jackett[1488066]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Sep 21 17:38:14 host jackett[1488066]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Sep 21 17:38:14 host jackett[1488066]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Sep 21 17:38:14 host jackett[1488066]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Sep 21 17:38:14 host jackett[1488066]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Sep 21 17:38:14 host jackett[1488066]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Sep 21 17:38:14 host jackett[1488066]:    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26 Jackett.Common.IndexerException: Exception (torrentdb): A task was canceled.
Sep 21 17:38:14 host jackett[1488066]:  ---> System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
Sep 21 17:38:14 host jackett[1488066]:  ---> System.TimeoutException: A task was canceled.
Sep 21 17:38:14 host jackett[1488066]:  ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
Sep 21 17:38:14 host jackett[1488066]:    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
Sep 21 17:38:14 host jackett[1488066]:    at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Sep 21 17:38:14 host jackett[1488066]:    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
Sep 21 17:38:14 host jackett[1488066]:    at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Sep 21 17:38:14 host jackett[1488066]:    at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Sep 21 17:38:14 host jackett[1488066]:    at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Sep 21 17:38:14 host jackett[1488066]:    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
Sep 21 17:38:14 host jackett[1488066]:    --- End of inner exception stack trace ---
Sep 21 17:38:14 host jackett[1488066]:    --- End of inner exception stack trace ---
Sep 21 17:38:14 host jackett[1488066]:    at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
Sep 21 17:38:14 host jackett[1488066]:    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
Sep 21 17:38:14 host jackett[1488066]:    at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 179
Sep 21 17:38:14 host jackett[1488066]:    at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 186
Sep 21 17:38:14 host jackett[1488066]:    at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 512
Sep 21 17:38:14 host jackett[1488066]:    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1414
Sep 21 17:38:14 host jackett[1488066]:    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 310
Sep 21 17:38:14 host jackett[1488066]:    --- End of inner exception stack trace ---
Sep 21 17:38:14 host jackett[1488066]:    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 322
Sep 21 17:38:14 host jackett[1488066]:    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 677
Sep 21 17:38:14 host jackett[1488066]:    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 309
Sep 21 17:38:14 host jackett[1488066]:    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
Sep 21 17:38:14 host jackett[1488066]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Sep 21 17:38:14 host jackett[1488066]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Sep 21 17:38:14 host jackett[1488066]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Sep 21 17:38:14 host jackett[1488066]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Sep 21 17:38:14 host jackett[1488066]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Sep 21 17:38:14 host jackett[1488066]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Sep 21 17:38:14 host jackett[1488066]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Sep 21 17:38:14 host jackett[1488066]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Sep 21 17:38:14 host jackett[1488066]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Sep 21 17:38:14 host jackett[1488066]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Sep 21 17:38:14 host jackett[1488066]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Sep 21 17:38:14 host jackett[1488066]:    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
Sep 21 17:39:01 host CRON[1488209]: (root) CMD (  [ -x /usr/lib/php/sessionclean ] && if [ ! -d /run/systemd/system ]; then /usr/lib/php/sessionclean; fi)
Sep 21 17:39:01 host systemd[1]: Starting Clean php session files...
Sep 21 17:39:01 host systemd[1]: phpsessionclean.service: Succeeded.
Sep 21 17:39:01 host systemd[1]: Finished Clean php session files.
Sep 21 17:40:01 host CRON[1488317]: (root) CMD (if [ -x /usr/bin/mrtg ] && [ -r /etc/mrtg.cfg ] && [ -d "$(grep '^[[:space:]]*[^#]*[[:space:]]*WorkDir' /etc/mrtg.cfg | awk '{ print $NF }')" ]; then mkdir -p /var/log/mrtg ; env LANG=C /usr/bin/mrtg /etc/mrtg.cfg 2>&1 | tee -a /var/log/mrtg/mrtg.log ; fi)
Sep 21 17:40:02 host systemd[1]: Starting system activity accounting tool...
Sep 21 17:40:02 host systemd[1]: sysstat-collect.service: Succeeded.
Sep 21 17:40:02 host systemd[1]: Finished system activity accounting tool.
Sep 21 17:40:32 host jackett[1488066]: 09-21 17:40:32 Error Exception in GetConfigurationForSetup (torrentdb): System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
Sep 21 17:40:32 host jackett[1488066]:  ---> System.TimeoutException: A task was canceled.
Sep 21 17:40:32 host jackett[1488066]:  ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
Sep 21 17:40:32 host jackett[1488066]:    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
Sep 21 17:40:32 host jackett[1488066]:    at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Sep 21 17:40:32 host jackett[1488066]:    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
Sep 21 17:40:32 host jackett[1488066]:    at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Sep 21 17:40:32 host jackett[1488066]:    at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Sep 21 17:40:32 host jackett[1488066]:    at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Sep 21 17:40:32 host jackett[1488066]:    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
Sep 21 17:40:32 host jackett[1488066]:    --- End of inner exception stack trace ---
Sep 21 17:40:32 host jackett[1488066]:    --- End of inner exception stack trace ---
Sep 21 17:40:32 host jackett[1488066]:    at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
Sep 21 17:40:32 host jackett[1488066]:    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
Sep 21 17:40:32 host jackett[1488066]:    at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 179
Sep 21 17:40:32 host jackett[1488066]:    at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 186
Sep 21 17:40:32 host jackett[1488066]:    at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 512
Sep 21 17:40:32 host jackett[1488066]:    at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 910
Sep 21 17:40:32 host jackett[1488066]:    at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 889

**Comment by ilike2burnthing** [comment]
@njunghausz please see https://github.com/Jackett/Jackett/issues/13562#issuecomment-1253674728

**Comment by ilike2burnthing** [comment]
You also deleted the indexer from Jackett, restarted the Jackett container, and tried adding the indexer again?

Do you have 2FA enabled?

Are you manually entering your credentials (i.e. not using autofill)?

**Comment by ilike2burnthing** [comment]
Manually enter the credentials when adding to Jackett, to ensure you're not accidentally using an old password.

If that doesn't work, please see the troubleshooting steps here - https://github.com/Jackett/Jackett/wiki/Troubleshooting/#the-operation-was-cancelled

If they don't resolve your problem, please provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting/#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by yjiawqgj** [comment]
> Manually enter the credentials when adding to Jackett, to ensure you're not accidentally using an old password.
> 
> If that doesn't work, please see the troubleshooting steps here - https://github.com/Jackett/Jackett/wiki/Troubleshooting/#the-operation-was-cancelled
> 
> If they don't resolve your problem, please provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting/#how-to-provide-a-jackett-enhanced-log-for-a-ticket

At the beginning, MTeamTP2FA was added, which was successful, but when logging in to the web page on the computer, jackett would not call the site to search, but could only delete the search site. After reading the solution you gave, it was too troublesome, so I didn't try it. Then delete MTeamTP2FA, retry to add MTeamTP, it was successful. But it feels unstable.

**Comment by garfield69** [comment]
if you are using 2fa, then every time you login to the web site and set your 2fa code for the login, you invalidate the cookie that you previously saved in the Jackett mteamtp2fa indexer config.

Once you have logged into the mteamtp  web site, is it really necessary for you to logout?
Can you not leave the web site logged in on your browser, grab that cookie and use the Jackett indexer at the same time?

**Comment by yjiawqgj** [comment]
> Once you have logged into the mteamtp web site, is it really necessary for you to logout?
> Can you not leave the web site logged in on your browser, grab that cookie and use the Jackett indexer at the same time?

After using MTeamTP2FA, logging into the website will invalidate Jackett. So this is not a good way. After retrying MTeamTP it works. Hope there will be no problems in the future.
