### ISSUE TITLE
[Mikan] enhancement: use the latest page for keywordless queries

### ISSUE THREAD

**Issue by daiwt** [Jackett/Jackett#13722]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Http
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.20.2182-ls81)
File /etc/issue: Ubuntu 20.04.4 LTS \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.15.64.1 (64bit OS) (64bit process)
Environment version: 6.0.11 (/app/Jackett/)
```

### Description

https://github.com/Jackett/Jackett/blob/12ce27da7fd2c907740c7643e3d7a0813269f933/src/Jackett.Common/Definitions/mikan.yml#L24

Indexer `mikan` is using `.Today.Year` as the default searching keyword for lastest feed. Episodes without year in their title are missing. https://mikanani.me/Home/Search?searchstr=2022

This website has a "Listing mode" page (列表模式), listing the latest updates, which may be better for this use: https://mikanani.me/Home/Classic
(However only 100 results are listed per page).

The html selector might also need to be changed, as css of rows on this page is a little different.

### Logged Error Messages

```text
No
```

**Comment by garfield69** [comment]
Usually a yaml indexer is set up to process a single search page layout, which is why the current indexer is written the way it is.
The classic page selectors are quite different from the search page selectors, but I will see if I can get the indexer to handle both page layouts.
Otherwise the only other option would be to write the indexer in C#, and since C# devs are hardly ever available, that option is unlikely to ever get completed.

**Comment by ilike2burnthing** [comment]
[v0.20.2260](https://github.com/Jackett/Jackett/releases/tag/v0.20.2260)
