### ISSUE TITLE
[yggtorrent] (updating) Login failed: No form found on https://www6.yggtorrent.lol/ using form selector #user-login

### ISSUE THREAD

**Issue by markettepigeon** [Jackett/Jackett#13792]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Windows Serveur 2016 64bits
```

### Description

Hello,

Today I can't connect to Yggtorrent with Jackett.

Cordially,

### Logged Error Messages

```text
An error occurred while updating this indexer
Login failed: No form found on https://www6.yggtorrent.lol/ using form selector #user-login
Click here to open an issue on GitHub for this indexer.
```

### Screenshots

![jacket](https://user-images.githubusercontent.com/34884922/208608058-4f9c4de4-7ff1-4fa8-a2aa-4029cc801986.PNG)

**Comment by garfield69** [comment]
The indexer is working for me which suggests the issue is most likely at your end.
The environment section in your post is lacking the usual required data, so its difficult to offer the correct advice.
See if https://github.com/Jackett/Jackett/wiki/TroubleShooting/#login-failed-selector helps you figure out the issue.
Otherwise please provide a full enhanced log, perhaps the debug and HTML included in the log will give us a clue to your issue.
See https://github.com/Jackett/Jackett/wiki/TroubleShooting/#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.
