### ISSUE TITLE
[Req] Bitturk.net

### ISSUE THREAD

**Issue by fevkalbeser** [Jackett/Jackett#1415]
**Indexer Name**
Bitturk

**Type**
Movies, TV Shows

**URL**
http://www.bitturk.net

**Indexer Language**
Turkish

**Invite** 
Available

**Comment by garfield69** [comment]
registrations currently closed. invite needed.
If you send an invite to garfield69 at outlook.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by fevkalbeser** [comment]
Currently I don't have an invite. It might take a while to obtain one. 
I can share with you my username/password temporarily, if it's OK.

**Comment by fevkalbeser** [comment]
@garfield69 I've just got the invite and sent to you. Thank you for your effort.

**Comment by garfield69** [comment]
registration and login successful. Thank you.

**Comment by garfield69** [comment]
Try Jackett pre-release v0.10.802

**Comment by fevkalbeser** [comment]
@garfield69 Thank you, works perfectly!

**Comment by ilker-aktuna** [comment]
On bitturk TV series numbers start from 1 and goes up without going back to 1 on each season.
So for example, if there are 25 episodes in season 1 , first episode of season 2 is named 26
But sonarr search for 2x1
is there a solution to search with incremental episode number ?

**Comment by ilker-aktuna** [comment]
I could not make it work with Sonarr or Radarr
So neither movies nor tv series work for me.
But above requester "fevkalbeser" wrote that it works perfectly for them.
what am I missing ?

**Comment by garfield69** [comment]
Did you follow the layout info in the BitTurk Jackett indexer config page, about using classic list and English language?
For the Sonarr indexer did you include **TV** as one of the cats and not just the default **TV/HD** ?

works for me.

**Comment by garfield69** [comment]
and for RadarrV3 I selected all the Movie cats (SD,HD,UHD,Bluray,3D,DVD,WEB-DL and the main movie cat) and that works for me as well.

**Comment by ilker-aktuna** [comment]
well, I did all of these but I can not get Turkish movies series
seems like Sonarr is requesting in a format which is not found on Bitturk.

when I check sonarr's log I see it search like "BLM 55" for example , I don't know why.
is this configurable ? (on Sonarr or any other place)

**Comment by ilker-aktuna** [comment]
below is  the log from Sonarr for a specific search:

21-4-1 17:44:40.9|Info|NzbSearchService|Searching 5 indexers for [Mucize Doktor : S02E26]
21-4-1 17:44:44.0|Error|Torznab|An error occurred while processing feed. http://192.168.254.20:9117/api/v2.0/indexers/bitturk/results/torznab/api?t=tvsearch&cat=5000,5040,100049,100051,100056,100057&extended=1&apikey=(removed)&offset=0&limit=100&q=Mucize%20Doktor%2049%20BLM%2011%2002&season=2&ep=26

[v3.0.6.1196] NzbDrone.Core.Indexers.Torznab.TorznabException: Torznab error detected: Jackett.Common.IndexerException: Exception (bitturk): Error: An error has occured!There are no results found.
 ---> System.Exception: Parse error
 ---> Jackett.Common.ExceptionWithConfigData: Error: An error has occured!There are no results found.
   at Jackett.Common.Indexers.CardigannIndexer.checkForError(WebResult loginResult, IList`1 errorBlocks) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 517
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1348
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 757
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1664
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 391
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 391
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 734
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in D:\a\1\s\src\Jackett.Server\Controllers\ResultsController.cs:line 432
   at NzbDrone.Core.Indexers.Torznab.TorznabRssParser.PreProcess(IndexerResponse indexerResponse) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Indexers\Torznab\TorznabRssParser.cs:line 42
   at NzbDrone.Core.Indexers.RssParser.ParseResponse(IndexerResponse indexerResponse) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Indexers\RssParser.cs:line 55
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 308
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(Func`2 pageableRequestChainSelector, Boolean isRecent) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 143

21-4-1 17:44:46.4|Info|NzbSearchService|Searching 4 indexers for [Mucize Doktor : S02E27]
21-4-1 17:44:50.1|Info|DownloadDecisionMaker|No results found
21-4-1 17:44:51.4|Info|DownloadDecisionMaker|No results found
21-4-1 17:44:51.4|Info|EpisodeSearchService|Episode search completed. 0 reports downloaded.

following url does not bring any results:
http://192.168.254.20:9117/api/v2.0/indexers/bitturk/results/torznab/api?t=tvsearch&cat=5000,5040,100049,100051,100056,100057&extended=1&apikey=(removed)&offset=0&limit=100&q=Mucize%20Doktor

but if I remove the part after name of the series (%2049%20BLM%2011%2002&season=2&ep=26) and add the episode number as "55" it lists the correct file.

**Comment by garfield69** [comment]
Firstly, I don't use BitTurk regularly, nor do I use Sonarr regularly, so I only set it up for a quick test after doing updates for this Jackett indexer.
I tested Sonarr using the BitTurk Jackett indexer, and searched for the series `Doğu` season 1 episode 1 and got a result.
I tested `Snowpiercer` and searched for se 2 ep 1 and got results.

Which is all I need to prove that the basic setup for the indexer functions as expected.

However, I can not get Sonarr via Jackett to fetch episodes for `Mucize Doktor` either.
I see on the web site that some of the episodes for the series are in the BTRG category, so you will need to add the movies category to the Sonarr indexer in order to pick them up.

But basically it comes down to BitTurk not being a particularly friendly web site for use with Sonarr.

There are several things coming into play here.
The first is that BitTurk generates an error when a search fails rather than just respond with plain not-found message or a search page without results, like most other sites do.
If Jackett passes this error to Sonarr (as it currently does) too many times in a row,  then Sonarr will mark the Sonarr indexer as broken and not use it again, until you either reset Sonarr or use the Sonarr settings indexer, open the indexer and save, to reset the error state.
Sonarr is a bit misleading here, if the indexer is not being used, Sonarr will still just return not-found in searches, without telling you that the indexer you wanted to use is not available :-(

I will update the Jackett indexer to prevent Sonarr disabling the indexer when ever it fails to find a search result.

The second issue is that `Mucize Doktor S02E26` does not yield results because that series is loaded on BitTurk with absolute numbering, and so there is a mismatch since there is no such torrent on BitTurk with that name.

But what is confusing you is that you are also seeing Sonarr search for `q=Mucize%20Doktor%2049%20BLM%2011%2002&season=2&ep=26`

But this is **not** Sonarr looking for `Mucize Doktor` with episode absolute number 49, rather it is Sonarr retrying the search using the **Alternate Title**, which is loaded on Sonarr as `Mucize Doktor 49 BLM 11 02` 
![image](https://user-images.githubusercontent.com/6933240/113355541-6cd55180-939d-11eb-80b4-ebc6058f10b6.png)

but this will not work on BitTurk since it's search engine expects terms to be in order, and also does an AND match (All terms must be present).

So a search for `Mucize Doktor BLM 49` works, but `Mucize Doktor 49 BLM 11 02` does not, and neither does `Mucize Doktor 49 BLM`

And this is, I believe, your source of confusion.
And there is nothing we can do in Jackett about this.

**Comment by garfield69** [comment]
v0.17.830

**Comment by ilker-aktuna** [comment]
thanks. automatically updated.
thanks for all the detailed information and analysis.
I get it, and I understand that the problem comes from incompatibility between Sonarr and Bitturk and Jackett can not do anything about it.

**Comment by ilike2burnthing** [comment]
https://bitturk.net/ - Error 524 - A timeout occurred

**Comment by garfield69** [comment]
I had this too the first time I tried today.
Then I used the wrench to open the config and saved, and now its working again for me.

**Comment by garfield69** [comment]
https://bitturk.net/ cloudflare Web server is down Error code 521

**Comment by garfield69** [comment]
online
