### ISSUE TITLE
Exception (btdigg): Got redirected to another domain. Try changing the indexer URL to https://www.domflow.it/.: Parse error

### ISSUE THREAD

**Issue by Woody-Stock** [Jackett/Jackett#14198]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Windows 10 x64 22H2 19045.2728
Jackett v0.20.3717 but has been happening for several weeks
Flaresolverr deactivated as it doesn't work with proxies in its latest versions
HTTPS5 proxy activated (the targeted website isn't accessible without it).
```

### Description

Testing the BTDIGG index returns an error.

### Logged Error Messages

```text
Exception (btdigg): Got redirected to another domain. Try changing the indexer URL to https://www.domflow.it/.: Parse error
```

**Comment by Woody-Stock** [comment]
Forgot to add that this seems the same issue as [12601](https://github.com/Jackett/Jackett/issues/12601) which was solved at the time.

**Comment by ilike2burnthing** [comment]
Working ok here. Try several different proxies/VPN servers if you're still having the issue.

**Comment by Woody-Stock** [comment]
Tried with several different proxies and the result is always the same.
If that helps I'm using Privado proxies.

**Comment by ilike2burnthing** [comment]
Using the same proxies, are you able to access https://btdig.com/ in browser?

**Comment by Woody-Stock** [comment]
Hello, yes, I can access it via the proxy in Firefox.

**Comment by ilike2burnthing** [comment]
BTDigg is working on Linux/Docker Jackett but not Windows. Unfortunately, the usual solution (spoofing the User-Agent) isn't working. Doesn't matter if I use Linux Jackett UA, a slightly modified one, or my browser's UA.

Using the Windows Jackett UA in browser does not result in a redirect, so while I'm not sure what is causing it, it doesn't seem to be the UA.

I tried adding every request header being used in browser, with and without the UA, no luck. The site doesn't appear to use cookies, so there's nothing to try there.

Using a VPN, rather than Jackett's proxy settings, also doesn't work.

@Woody-Stock if BTDigg is a must for you, the only solution right now would be using Docker on Windows for a Jackett container.

@garfield69 any ideas what else it could be?

**Comment by Woody-Stock** [comment]
OK thanks for the answer, I will try that but never used Docker, so it will be a learning curve.

**Comment by garfield69** [comment]
>any ideas what else it could be?

none whatso ever ;-(
ever the .onion link which works in a TOR browser does not work with the .ly or web2tor.to proxies.

**Comment by Woody-Stock** [comment]
> > any ideas what else it could be?
> 
> none whatso ever ;-( ever the .onion link which works in a TOR browser does not work with the .ly or web2tor.to proxies.

Yes those TOR links stopped working a while ago but if this can be any indication, I think the regular link (https://btdig.com/) stopped working before that over a proxy (well the ones from Privado at the very least).

It is when those TOR links stopped working that I reverted back to the regular link and saw it didn't work. I always try to use the "real" link over alternate ones, so if I had configured TOR links at the time, it's probably because the original one didn't work for me. I honestly don't remember. I first assumed that this will be fixed in a next release but when it wasn't and saw on here it wasn't flagged I decided to open the issue.

Since then the TOR links were removed from BTDigg's Jackett indexer and not replaced unfortunately.

**Comment by ilike2burnthing** [comment]
Just tried changing the UA in BrowserUtil.cs in case it was somehow picking up that the UA was spoofed, but no.

Also tried adding `webclient.EmulateBrowser = false` to Cardigann, didn't help.

Leaving this open for some future bright spark to solve, but I wouldn't hold your breath.

**Comment by sponnify** [comment]
facing the same issue, using windows ver. with Flaresolverr activated; therefore no proxies.

**Comment by ilike2burnthing** [comment]
Newly added *.tor2web.link mirror working on Windows Jackett - https://github.com/Jackett/Jackett/pull/14238

**Comment by Woody-Stock** [comment]
The TOR link doesn't seem to work anymore so we're back to square one...

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/4907#issuecomment-1509241990

**Comment by RileyXX** [comment]
So has btdig implented something to detect jacket searches somehow? What is the relation to domflow.it? 

Seems to me that btdigg is intentionally redirecting jackett searches to a dummy domain, probably to force people to use their site directly. It's possible that the redirect is happening at the cloudflare level. To fix this will probably require changing the way jackett indexes btdigg to avoid detection. 

Can someone point me in the right direction on where in the jackett repository we should be looking in order to modify the code for how jackett uses btdigg? I'd like to take a crack at this. Thanks

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Definitions/btdigg.yml

**Comment by garfield69** [comment]
you may find https://github.com/Jackett/Jackett/wiki/Definition-format useful

**Comment by ilike2burnthing** [comment]
To rule out some dead ends for you:
https://github.com/Jackett/Jackett/issues/14198#issuecomment-1491806580
https://github.com/Jackett/Jackett/issues/14198#issuecomment-1492894159

**Comment by RileyXX** [comment]
Is the following code relevant? In https://github.com/Jackett/Jackett/blob/bf5b24a5a76712104018bd9547cabe6961c356bc/src/Jackett.Common/Indexers/BaseIndexer.cs#LL512C1-L536C1

I was trying to skim through the code for jackett to figure out how btdig could be identifying requests coming from jackett. Maybe this will give some clues. I don't think the definitions will be helpful. The core code probably needs to be modified in order to avoid detection for this indexer. Perhaps btdig is able to identify the requests coming from jackett via referer or request type? Or maybe when emulateBrowser is null? Possibly a combination of things including the user-agent.

Hard to say, but the code is a bit steep for me since I am not proficient in CS. I'm curious how the requests coming from jackett look in cloudflare because that's probably where the redirect is coming from. Admins of btdig probably setup some redirect rules to match requests coming from jackett. Someone with more knowledge will have to investigate further.

```cs
        protected virtual async Task<WebResult> RequestWithCookiesAsync(
            string url, string cookieOverride = null, RequestType method = RequestType.GET,
            string referer = null, IEnumerable<KeyValuePair<string, string>> data = null,
            Dictionary<string, string> headers = null, string rawbody = null, bool? emulateBrowser = null)
        {
            var request = new WebRequest
            {
                Url = url,
                Type = method,
                Cookies = cookieOverride ?? CookieHeader,
                PostData = data,
                Referer = referer,
                Headers = headers,
                RawBody = rawbody,
                Encoding = Encoding
            };

            if (emulateBrowser.HasValue)
                request.EmulateBrowser = emulateBrowser.Value;
            var result = await webclient.GetResultAsync(request);
            CheckSiteDown(result);
            UpdateCookieHeader(result.Cookies, cookieOverride);
            return result;
        }
```

**Comment by ilike2burnthing** [comment]
I did try playing with UA and `EmulateBrowser` but didn't get anywhere. I assume that's where the issue lies, but 🤷

**Comment by Woody-Stock** [comment]
If this can be any help, I have the exact same error from Prowlarr.
So it seems this comes from BTDigg, rather than Jackett itself.
As someone suggested, it may be on purpose.

**Comment by RileyXX** [comment]
Today I noticed this indexer is working again. Can anyone else confirm? 

I am getting successful tests in Jackett dashboard and successful searches/downloads in sonarr.

**Comment by return42** [comment]
I assume btdigg uses some kind of [TLS fingerprint](https://www.zenrows.com/blog/what-is-tls-fingerprint)?
