### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Altansar69** [Jackett/Jackett#14504]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
.
```

### Description

Sorry, it's just a question but I didn't know where to ask it. Some trackers require you to log in every X amount of time in order not to get banned. 
If we use jackett, does every time we do a search on it count as if we had logged in to the tracker since we put our credentials?

### Logged Error Messages

```text
.
```

**Comment by ilike2burnthing** [comment]
Annoyingly the answer is 'it depends'; some work that way, others don't.

Some don't because we're using their APIs instead of scraping the sites, some lock your account if you haven't recently logged in despite the current session still being valid (although to me that's poor design and is an issue for all users, not just those who use Jackett), some (very few) require regular seeding/leeching and not just activity on the site, some heavily push the social aspects of the site (forums, competitions, games, chat, etc.) that you essentially have to use the site, and I'm sure some will check the user-agent and not count Jackett activity.

**Comment by Altansar69** [comment]
oh okay, thanks. Too bad it would have been handy. Hell with trackers that require regular activity. 
But yes, I know that some of them ask you to download from their site, like the asiatorrents sites (avistaz etc...). What a hell this kind of site.
