### ISSUE TITLE
[yts] (testing) Exception (yts): Connection reset by peer: The SSL connection could not be established, see inner exception.

### ISSUE THREAD

**Issue by maheshnandyala** [Jackett/Jackett#14503]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
An error occurred while testing this indexer
Exception (yts): Connection reset by peer: The SSL connection could not be established, see inner exception.
```

### Description

An error occurred while testing this indexer
Exception (yts): Connection reset by peer: The SSL connection could not be established, see inner exception.

### Logged Error Messages

```text
An error occurred while testing this indexer
Exception (yts): Connection reset by peer: The SSL connection could not be established, see inner exception.
```

### Screenshots

![Screenshot 2023-06-25 at 10 34 51 PM](https://github.com/Jackett/Jackett/assets/22831994/c7a9a43c-b07c-49af-9220-4c734e059076)

**Comment by garfield69** [comment]
The environment section of this ticket is not where you paste your error message, its there to provide information about your platform and Jackett configuration details. Fill in that section so we can make inform decisions on how to help you best.
Since all we have to work with is a general connection error, read this wiki https://github.com/Jackett/Jackett/wiki/TroubleShooting#a-connection-attempt-failed and see if this helps.
Otherwise provide an enhanced log of the event which may contain more info about the inner exception that could be useful. See https://github.com/Jackett/Jackett/wiki/Troubleshooting/#how-to-provide-a-jackett-enhanced-log-for-a-ticket for how-to.

**Comment by maheshnandyala** [comment]
Can you share me? How can I share Full log

**Comment by maheshnandyala** [comment]
![Screenshot 2023-06-25 at 11 10 45 PM](https://github.com/Jackett/Jackett/assets/22831994/bcf2a354-eb21-4826-9578-74d435ae3401)

**Comment by ilike2burnthing** [comment]
See the links provided above. Follow the troubleshooting steps in the first one. Only if none help should you provide an enhanced log using the instructions in the second link.
