### ISSUE TITLE
[req]: Add option to search with and without single quote

### ISSUE THREAD

**Issue by provalinf** [Jackett/Jackett#14559]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

This problem occurs with some titles such as :  
The Devil's Hour => The Devils Hour
Problem on torrent website (Ygg for example), we have 3 entries results with this single quote and without 22 entries.  
Idem Stan Lee's Lucky Man => Stan Lees Lucky Man

### Describe the solution you'd like

So for some trackers, there should be an option to concatenate a search with and without quote.

### Describe alternatives you've considered

In the meantime I've done something dirty that solves my problem and can potentially interest other people:  
This modification launches the current search and another by deleting singles quotes and concatenates the results so the grabs are unique to avoid duplicates. (Only works for the Torznab API call)

In Jackett.Server/Controllers/ResultsController.cs, replace line 431 (07/13/2023 current revision):  
`resultPage.Releases = proxiedReleases.ToList();`  
by this:  
```
IEnumerable<ReleaseInfo> proxiedReleasesWithoutQuote = new List<ReleaseInfo>();
                if (CurrentQuery.SanitizedSearchTerm.Contains('\''))
                {
                    var currentQueryWithoutQuote = CurrentQuery.Clone();
                    currentQueryWithoutQuote.SearchTerm = currentQueryWithoutQuote.SearchTerm.Replace("'", "");
                    var resultWithoutQuote = await CurrentIndexer.ResultsForQuery(currentQueryWithoutQuote);
                    proxiedReleasesWithoutQuote = resultWithoutQuote.Releases.Select(r => MapperUtil.Mapper.Map<ReleaseInfo>(r)).Select(
                        r =>
                        {
                            r.Link = serverService.ConvertToProxyLink(r.Link, serverUrl, r.Origin.Id, "dl", r.Title);
                            r.Poster = serverService.ConvertToProxyLink(r.Poster, serverUrl, r.Origin.Id, "img", "poster");
                            return r;
                        });
                }

                resultPage.Releases = proxiedReleases.Concat(proxiedReleasesWithoutQuote)
                                                     .GroupBy(info => info.Grabs)
                                                     .Select(infos => infos.First())
                                                     .ToList();
```

**Comment by ilike2burnthing** [comment]
As most of our indexers are in YAML, currently the only way to do this would be running double the searches, one which would remove `'` and one which wouldn't. However, as https://github.com/Jackett/Jackett/issues/14514 is yet to be added, that would mean that for almost all searches would be exactly the same, resulting in duplicate results.

While for most that would mean going from one request to two, for YGG, as you mentioned it, that could result in a ridiculous number of requests:

https://github.com/Jackett/Jackett/blob/dfc1cc5fb96d2dbc71706cb84e2db2d410666d3d/src/Jackett.Common/Definitions/yggtorrent.yml#L196-L344

Even if https://github.com/Jackett/Jackett/issues/14514 was added, it still seems like a lot of waste to accommodate a few edge cases caused by inconsistent naming from uploaders.

A much simpler solution (working for YGG at least) would be to remove `'s` from your search query.
