### ISSUE TITLE
[req]: Add YGG option_saison[] attributes request

### ISSUE THREAD

**Issue by provalinf** [Jackett/Jackett#14565]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

I see that sonarr expects to receive all episodes of a season when the episode number is not specified. This is essential for partial or complete seasons with no packs available. I have this problem on many series, including the one below.  
According to the feedback, this is how a lot of trackers work, and it's also the case for YGG, except that you don't have to concatenate the season number in the query, but add a specific param.

Example:
![image](https://github.com/Jackett/Jackett/assets/15704455/810ca581-d4bd-4bd0-89d7-86a4f18ffc49)
=> return 0 results

![image](https://github.com/Jackett/Jackett/assets/15704455/62c8a97f-856f-4f30-a676-87e409456b00)
=> return 29 results

### Describe the solution you'd like

`name=9-1-1%3A+Lone+Star&description=&file=&uploader=&category=2145&sub_category=2184&option_saison%5B%5D=7&do=search`
```
name: 9-1-1: Lone Star
description: 
file: 
uploader: 
category: 2145
sub_category: 2184
option_saison[]: 7
do: search
```

The problem is that you have to remap or add to calculate the number of this parameter.

``` 
<select name="option_saison[]" style="height:200px" multiple="" tabindex="-1" class="select2-hidden-accessible" aria-hidden="true">
          <option></option>
            <option value="1"> Série intégrale</option>
            <option value="2">Hors saison</option>
            <option value="3">Non communiqué</option>
            <option value="4">Saison 01</option>
            <option value="5">Saison 02</option>
            <option value="6">Saison 03</option>
            <option value="7">Saison 04</option>
            <option value="8">Saison 05</option>
            <option value="9">Saison 06</option>
            <option value="10">Saison 07</option>
            <option value="11">Saison 08</option>
            <option value="12">Saison 09</option>
            <option value="13">Saison 10</option>
            <option value="14">Saison 11</option>
            <option value="15">Saison 12</option>
            <option value="16">Saison 13</option>
            <option value="17">Saison 14</option>
            <option value="18">Saison 15</option>
            <option value="19">Saison 16</option>
            <option value="20">Saison 17</option>
            <option value="21">Saison 18</option>
            <option value="22">Saison 19</option>
            <option value="23">Saison 20</option>
            <option value="24">Saison 21</option>
            <option value="25">Saison 22</option>
            <option value="26">Saison 23</option>
            <option value="27">Saison 24</option>
            <option value="28">Saison 25</option>
            <option value="29">Saison 26</option>
            <option value="30">Saison 27</option>
            <option value="31">Saison 28</option>
            <option value="32">Saison 29</option>
            <option value="33">Saison 30</option>
        </select>
``` 
And since my YML skills are limited, I'm not sure it can be done directly.

**Comment by ilike2burnthing** [comment]
If the values for season or episode (also available) actually matched up to their respective number (e.g. season 1 had a value of 1, instead of 4), this would be fairly simple, but instead we have this complicated mess.

Although, even if that were the case, we'd still run into a problem with any show with a season higher than 30 or episode higher than 60 (see soaps and anime).

We could instead strip season numbers if they're alone, but I'll looks at this if I have some free time tomorrow.

**Comment by JdAlix** [comment]
This change has created problems when searching for a series that has many seasons, typically Grey's Anatomy, the only season that comes up is S19 or Station 19 because it's the most recent, while the 18 previous seasons can't be found because the season number has been removed from the search.

Why not add an option to enable or disable this limitation? So that everyone can find what they're looking for in the end.

**Comment by garfield69** [comment]
v0.21.643
