### ISSUE TITLE
我用的私密的PT站点，使用手动搜索的时候，标签为any情况，搜索结果没有XXX，必须手动标签全选，才有XXX

### ISSUE THREAD

**Issue by wang923345843** [Jackett/Jackett#14594]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
任意版本的jackett
```

### Description

怎么样才能使用any搜索时能够出现XXX内容

### Logged Error Messages

```text
1
```

### Screenshots

![image](https://github.com/Jackett/Jackett/assets/100781270/023fa0e4-6da2-4822-884e-d8b7a7c5db58)
![image](https://github.com/Jackett/Jackett/assets/100781270/27a676cf-7fc0-487b-b8ba-758d612543c0)

**Comment by ilike2burnthing** [comment]
Yes, this is intentional for this indexer (`default: true` vs `default: false`):

https://github.com/Jackett/Jackett/blob/b7b15c435e0fa4d90bc1f8c5feb96a5e3074a1d2/src/Jackett.Common/Definitions/mteamtp.yml#L15-L51

This is to reduce the number of requests being performed on a default search (2 vs 3):

https://github.com/Jackett/Jackett/blob/b7b15c435e0fa4d90bc1f8c5feb96a5e3074a1d2/src/Jackett.Common/Definitions/mteamtp.yml#L116-L123
