### ISSUE TITLE
[lostfilm] (updating) Exception (lostfilm): Object reference not set to an instance of an object.: Parse error

### ISSUE THREAD

**Issue by Vinticb** [Jackett/Jackett#14638]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.21.653-ls133)
File /etc/issue: Welcome to Alpine Linux 3.18
Jackett variant: CoreLinuxMuslAmdx64
OS version: Unix 6.0.0.0 (64bit OS) (64bit process)
Environment version: 6.0.21 (/app/Jackett/)
Starting Jackett v0.21.653
```

### Description

LostFilm.tv
An error occurred while addig or testing this indexer

### Logged Error Messages

```text
An error occurred while updating this indexer
Exception (lostfilm): Object reference not set to an instance of an object.: Parse error
```

### Screenshots

![2023-08-16_11-03-09](https://github.com/Jackett/Jackett/assets/83859796/14321561-83f0-4fa2-85ea-8cc0433ffacd)

**Comment by garfield69** [comment]
If you edit the indexer config via the Jackett dashboard, are you seeing a captcha image?
If not, then this usually means you are being blocked by your ISP/firewall/router/malware apps

have you tried any of the other alternate sitelinks?
remember, as you switch to a new sitelink you need to CLOSE then edit again so that you load the captcha from the new sitelink.

IF none of the alternates work then given that the indexer is working for me this suggests the problem is at your end.
Please turn on **enhanced** logging, repeat the test and provide the full **enhanced** log file which includes the _Debug_ and _HTML_. Hopefully this will provide the clue to understanding your issue.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.

**Comment by garfield69** [comment]
And BTW the environment section is not where you place a copy of the error message, this is not helpful.
Please fill in the environment section of this ticket, by restarting Jackett, viewing the log, scrolling to the bottom, and copy/paste the last 10 lines in the log,

**Comment by Vinticb** [comment]
[garfield69](https://github.com/garfield69), thank you!
> If you edit the indexer config via the Jackett dashboard, are you seeing a captcha image? If not, then this usually means you are being blocked by your ISP/firewall/router/malware apps

Yes, i see captcha image and it's work fine.

> have you tried any of the other alternate sitelinks? remember, as you switch to a new sitelink you need to CLOSE then edit again so that you load the captcha from the new sitelink.

I tried. There is the same error on the any sitelink. Previously the indexer worked fine, the error began to appear about a week ago.

> IF none of the alternates work then given that the indexer is working for me this suggests the problem is at your end. Please turn on **enhanced** logging, repeat the test and provide the full **enhanced** log file which includes the _Debug_ and _HTML_. Hopefully this will provide the clue to understanding your issue. See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.

[log2.txt](https://github.com/Jackett/Jackett/files/12366758/log2.txt)

> And BTW the environment section is not where you place a copy of the error message, this is not helpful.
Please fill in the environment section of this ticket, by restarting Jackett, viewing the log, scrolling to the bottom, and copy/paste the last 10 lines from the log,

done

**Comment by garfield69** [comment]
Fascinating!
the log shows that you are able to access the web site, fetch the latest releases page, but as the indexer is processing the 
series `Just Like That S02E09 (И вот так просто, 2 сезон, 9 серия)` you do not get given a list of the torrents available for that show, but instead are presented with
```
ВНИМАНИЕ!
Контент недоступен на территории Российской Федерации*. Приносим извинения за неудобства.
Определение местоположения пользователя осуществляется по IP-адресу компьютера.
```
google translation
```
ATTENTION!
Content is not available in the Russian Federation*. We apologize for the inconvenience. 
The location of the user is determined by the IP address of the computer.
```
which the indexer interprets as an error
```
2023-08-17 10:33:07.7489 Debug > Parsing 0 releases
2023-08-17 10:33:07.7605 Error Error on 20230817103307 for LostFilm.tv.txtSystem.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.LostFilm.FollowTrackerRedirection(String url, TrackerUrlDetails details) in ./Jackett.Common/Indexers/LostFilm.cs:line 722
```
since the indexer was not expecting this.

I on the other hand, don't get that message (as I am using a non Russian IP), and are able to view the full new releases results.


We will need to amend the indexer to ignore those results and continue processing the rest of the new releases page.

**Comment by garfield69** [comment]
The next Jackett release is not due for another 21 hours but once published please report back success or failure, since I do not have access to a RF IP so cannot test my fix. It continues to work for my regular IP so that much is tested :-)

**Comment by garfield69** [comment]
v0.21.662

**Comment by Vinticb** [comment]
> v0.21.662

It works fine, no error with lostfilm. Thank you!
