### ISSUE TITLE
eThor.tk - Wrong download link to the client with magnet

### ISSUE THREAD

**Issue by OXYDER** [Jackett/Jackett#14630]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
When Radarr or Sonarr send the download information to the client, it is in magnet form which unfortunately does not work.

Is it possible to send via .torrent?
```

### Description

Adding manually a season of episode of a serie to the client by Radarr or Sonarr. Magnet link is wrong and won't start download.

A .meta remaining in the client without action.

C9B4E6C9AB1FAA075E3635FE54ED3EABD72C6D8C.meta with 0 bytes.

### Logged Error Messages

```text
11:03pm	DownloadService	Report sent to rTorrent. Les.Testeurs.2011.S05.FRENCH.1080p.WEB.H264-TFA	
11:03pm	RTorrent	rTorrent could not resolve magnet within 5 seconds, download may remain stuck: magnet:?xt=urn:btih:c9b4e6c9ab1faa075e3635fe54ed3eabd72c6d8c&dn=Les.Testeurs.2011.S05.FRENCH.1080p.WEB.H264-TFA.torrent&private=1&tr=https://odin.ethor.tk/announce/(removed).
```

### Screenshots

![magnet](https://github.com/Jackett/Jackett/assets/1058557/9b07a898-45de-4e8c-a985-149db397cc6f)

**Comment by garfield69** [comment]
thorsland indexer provides both .torrent and magnet links.
which one you use is up to you to choose. 
The Jackett dashboard manual search using this indexer shows two icons in the DL column,
![image](https://github.com/Jackett/Jackett/assets/6933240/37903995-2ef4-4b10-9fff-6291b333522c)
click on the first one for the .torrent link and the second one for the magnet.

If the magnet link does not work then that is nothing to do with Jackett, the magnet is fetched untouched from the thorsland web site.

**Comment by OXYDER** [comment]
The magnet work in Jackett when I'm click on and open with qBittorrent. But why is not working in Sonarr and Radarr when is added in rutorrent?

**Comment by garfield69** [comment]
If the magnet works with qbittorrent but not with rutorrent then clearly the issue is with the set up of rutorrent.
Your screen shot shows that the magnet was accepted by the app, but that none of the seeders connected in order to resolve the meta and begin the download of the data.
in any case, I do not believe this has anything to do with Jackett.

@ilike2burnthing @mynameisbogdan  any insights you can add to this ticket?

**Comment by OXYDER** [comment]
I made another test, copy the exact magnet link in Jackett. Instant start with qBittorrent but not with ruTorrent.

Same problem. Stuck with the .meta in torrent title and no information was taken from peers because no peers is show.

**Comment by ilike2burnthing** [comment]
If the magnet works in one client but not the other, and the same thing happens when using the magnet directly from the tracker's site, then the issue is with ruTorrent.

As for *arrs, they prefer magnets over torrents.

To give you some direction for some further troubleshooting:
- do any private magnets work in ruTorrent?
- do any public magnets work in ruTorrent?
- you will likely find more help looking at rTorrent more generally, e.g. https://github.com/rakshasa/rtorrent/issues/602

**Comment by RaymondMD766** [comment]
The installation Jackett, Radarr and Sonarr works well with other indexers.
The addition in rutorrent by Sonarr and Radarr is a .torrent and not a magnet link.

This magnet link contains a public dht:// which does not work for a private tracker. 
Other indexers return a .torrent that have no dht://

Thank you

**Comment by OXYDER** [comment]
Is it possible to use default .torrent link instead of magnet link for Radarr and Sonarr and other software through Jackett?

Update Jackett to use only .torrent when automatic parse is used?

**Comment by garfield69** [comment]
>Considering it's a private tracker, I would go with torrent first and magnet second like I did with hellashut

I will update the indexer to favour .torrents first.

**Comment by garfield69** [comment]
v0.21.655
