### ISSUE TITLE
[torlock] (testing) Test search in Torlock => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

### ISSUE THREAD

**Issue by rrrevin** [Jackett/Jackett#14636]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
-
```

### Description

Looks like something changed with torlock?
Used to work fine up until a few weeks ago.

### Logged Error Messages

```text
System.Exception: Test search in Torlock => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.
```

**Comment by garfield69** [comment]
The indexer is working for me so this suggests the problem is at your end.
Have you tried using any of the alternate sitelinks for the indexer, do they all return no results?

Please fill in the environment section of this ticket, by restarting Jackett, viewing the log, scrolling to the bottom, and copy/paste the last 10 lines in the log,

Please turn on **enhanced** logging, repeat the test and provide the full **enhanced** log file which includes the _Debug_ and _HTML_. Hopefully this will provide the clue to understanding your issue.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.

**Comment by rrrevin** [comment]
Don't know what happened.. between the time I reported this, and now, it now works. I literally did not change a thing.

Now worries.. closiing issue.

**Comment by AARON8888** [comment]
Problem remains for me.

Environment:
HTTP client: HttpWebClient
FlareSolverr
Proxy: HTTP
App: C:\ProgramData\Jackett
Docker: No
Jackett variant: CoreWindows, 64 bits
---

See full log: 
[full log.txt](https://github.com/user-attachments/files/16201366/full.log.txt)

**Comment by AARON8888** [comment]
Problem remains.
