### ISSUE TITLE
jackett misreading seeds

### ISSUE THREAD

**Issue by thaynos** [Jackett/Jackett#14659]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2023-08-23 16:42:06	Info	Using HTTP Client: HttpWebClient2
2023-08-23 16:42:06	Info	Using FlareSolverr: http://192.168.1.136:8191/
2023-08-23 16:42:06	Info	Using proxy: Disabled
2023-08-23 16:42:06	Info	App config/log directory: C:\ProgramData\Jackett
2023-08-23 16:42:06	Info	ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
2023-08-23 16:42:06	Info	Running in Docker: No
2023-08-23 16:42:06	Info	Jackett variant: CoreWindows
2023-08-23 16:42:06	Info	OS version: Microsoft Windows NT 10.0.19045.0 (64bit OS)
2023-08-23 16:42:06	Info	Environment version: 6.0.21 (C:\ProgramData\Jackett\)
2023-08-23 16:42:05	Info	Starting Jackett v0.21.68
```

### Description

jackett falsely reports seeds to qbit, even though often these torrents have 0 seeds
its not my issue as i can download other torrents fine
![image](https://github.com/Jackett/Jackett/assets/83282129/a3cc66f9-59e6-45f4-af7b-eb05d1fe1f7e)
![image](https://github.com/Jackett/Jackett/assets/83282129/8a7edc97-1ccb-46b7-b028-2d9b05408eb7)

### Logged Error Messages

```text
none
```

**Comment by garfield69** [comment]
If I go to the bitsearch web site and search with
https://bitsearch.to/search?q=revo%20uninstaller%20pro&sort=date&order=desc&limit=100
I get (showing the first nine in my screen shot below)
![image](https://github.com/Jackett/Jackett/assets/6933240/e3b33caf-197f-45f8-abb9-009763fe6c05)
and Jackett shows
![image](https://github.com/Jackett/Jackett/assets/6933240/0b2c8fb7-3ac4-483e-ba88-347db5dff5e9)

the only one its get wrong is the 1K which comes out as 100 instead of 1000 but otherwise its correct.

and solid torrents uses the same engine so same results.

the indexer code takes the seeders, removes the dot, and replaces the K with 00 and M with 00000 which is why it does not get the 1K correct. I can fix that.
But otherwise I don't see any other issues. Do you disagree? Then please provide single example. Thanks.

**Comment by garfield69** [comment]
Oh, and any difference between what the web site reports as seeders, and the actual REAL seeders once the magnet or .torrent is used by qBt or any other torrent client for that matter, is not something Jackett can influence.

**Comment by thaynos** [comment]
> Oh, and any difference between what the web site reports as seeders, and the actual REAL seeders once the magnet or .torrent is used by qBt or any other torrent client for that matter, is not something Jackett can influence.

thank you for your response! dont you think that adding websites that dont truthfully list seeders should be removed? why does this disrepancy happen?

**Comment by garfield69** [comment]
>dont you think that adding websites that dont truthfully list seeders should be removed? 

BitSearch and SolidTorrents are a class of web site defined as metasearch, which is basically an engine that aggregates the magnets results from other sites rather than rely on torrents loaded by their users.
And as long as a site is not tagged as being a malware distributor or a fishing/spam generator then we accept any of these site that users suggest we create indexers for.

As for accuracy of the seeders count or the file size, we have multiple indexes that fail in that regard, and since users keep asking us to add indexers for these site it seems others don't think this is reason enough to stop using them.

>why does this disrepancy happen?

Because those two sites apparently do not refresh their records once gathered.
