### ISSUE TITLE
Wrong indexer name

### ISSUE THREAD

**Issue by sunbroke555** [Jackett/Jackett#14686]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
docker
```

### Description

Indexer details page: The Chinese name for hhanclub (https://hhanclub.top/) should be "憨憨" instead of "猪猪"

### Logged Error Messages

```text
no logs
```

### Screenshots

![%8R$M0Z`I}H0% R6~W~GIRD](https://github.com/Jackett/Jackett/assets/74763419/b928f832-a8d0-4eb0-b2d2-895d8f409e22)

**Comment by ilike2burnthing** [comment]
Looks like this was accidentally copied across from PigNetwork:

https://github.com/Jackett/Jackett/blob/d1e8e20c41658f7d22bc38a9a5d4bb9a6d6577e5/src/Jackett.Common/Definitions/pignetwork.yml#L4

The same has happened with CarPT.

HHanClub and CarPT seem to only use an English name for their tracker, so I think the best option is to just remove the Chinese name altogether, rather than adding our own.

**Comment by garfield69** [comment]
v0.21.784
