### ISSUE TITLE
[req]: gay-torrents.net update indexer to support whisparr v2 torznab requests

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#14700]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

whisparr add the release year to its torznab request query to the gay-torrents indexer, but the site does not have this date in its titles so no results are returned.

### Describe the solution you'd like

check by using whisparr to see if dropiing the year from the search sent to the web site will return results that whisparr will accept

**Comment by garfield69** [comment]
there is nothing to fix.
I set up whisparr to use the gay-torrents.net indexer, and added `heatstroke 2013` to the whisparr collection and then did a search and found 4 results.

**Comment by garfield69** [comment]
@soumaisalan if you are not getting results take a look at your whisparr indexer categories, you may inadvertently be excluding results. I set my test up using XXX(6000), Other(8000) and Movies(2000) with everything else unticked.

**Comment by soumaisalan** [comment]
We all know that this is not how Whisparr works. Instead of specifying a particular movie or scene, it requires the website, and you add the content company or studio.

![image](https://github.com/Jackett/Jackett/assets/45512649/b11c8fc6-4f6e-49e7-8f35-126957bd6db3)

You can see that when submitting it to Jackett, it pulls the studio first and then the release date, as per the log.

![Captura de tela 2023-09-17 205240](https://github.com/Jackett/Jackett/assets/45512649/8a4f0a52-dad2-4da6-8fbc-f0124b999b5b)

On the Gay Torrents website, none, absolutely none of the content includes release dates, so it will never return anything when using Whisparr.

![Captura de tela 2023-09-17 205502](https://github.com/Jackett/Jackett/assets/45512649/3edfba59-872a-43bb-a4ca-61c65b4b5895)

**Comment by garfield69** [comment]
I'm not familiar with using whisparr. I assumed its just like Radarr, add movies to your collection, define an indexer that uses the Jackett URL to connect to a Jackett indexer and let whisparr search and fetch torrents via that API.
So I went to the movies/add new,  and added a movie, and then did a search for that movie and got results.

How do you add a content company or studio to whisparr?

**Comment by garfield69** [comment]
>We all know that this is not how Whisparr works.

Well, no actually, this is how my whisparr works ;-b

However I have done some research, and it turns out that the version of whisparr that I have is v1, and even though I click the check-for-updates nothing newer was presented.

Finally found the prowlarr wiki link and discovered that there is a v2 version that is a completely revamped release of whisperr.

So I should now be able to research further into your request now that I am on the same version as you.

**Comment by garfield69** [comment]
v0.21.826

**Comment by garfield69** [comment]
[@dou](https://github.com/Jackett/Jackett/commit/3e3a6a2b6814c15a233359b01e8ba73579fcd5c2#commitcomment-128761983)

**Comment by garfield69** [comment]
@douglas24 are you using whisparr v1 or v2?
Can you give me an example of the search so I can replicate? 
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by obertscloud** [comment]
the site is down redirecting to other spammy sites when you go to it

**Comment by garfield69** [comment]
Tah. See #10328
