### ISSUE TITLE
[req]: babytorrent

### ISSUE THREAD

**Issue by saw1543** [Jackett/Jackett#14748]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: babytorrent
- URL: https://babytorrent.bio/
- Description: movie and tv series torrent
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): public
- Additional Comments: movie, tv-series
```

**Comment by ilike2burnthing** [comment]
As far as I can see this is just a clone of YTS and pulls series torrents from EZTV. There are other near identical clones such as yts-official.org

**Comment by garfield69** [comment]
Yeah, it does not seem worth the bother, especially since it will require a C# dev to write an indexer.
The results page has nothing but a poster and a details link, and we would need to fetch every posters details page to pick up the multiple magnets for each title, generating lost of requests to the site.
I'm going to close it as not suitable.
