### ISSUE TITLE
[animeworld] only returning imdb movies in radarr

### ISSUE THREAD

**Issue by virusperfect** [Jackett/Jackett#14776]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /config
Running in Docker: Yes (image build: unknown)
Jackett variant: CoreLinuxMuslAmdx64
OS version: Unix 5.15.0.86 (64bit OS) (64bit process)
Environment version: 6.0.23 (/app/)
Starting Jackett v0.21.1033
```

### Description

The AnimeWorld indexer works perfectly fine when using manual search in Jackett. However, in Radarr, only the results with an "IMDB" id show up when i search for the movie. As an example, in the screenshot below, only the first 5 entries will actually show up in Radarr.

### Logged Error Messages

```text
none
```

### Screenshots

![grafik](https://github.com/Jackett/Jackett/assets/68875496/bfb02bfe-9a46-4271-8b3c-74e84d036716)

**Comment by ilike2burnthing** [comment]
IIRC the *arrs will perform ID searches first (if the indexers support it), and only if no valid results are returned do they then search by name.

@garfield69 if a tracker's ID search is imperfect like this, should we still support it?

**Comment by garfield69** [comment]
The use of imdbid or tmdbid is generally preferred when using torznab t=movie over defaulting back to t=search, because the use of the id is supposed to eliminate title name variations (for example when a torrent's name is in German instead of English), and/or when there are different releases by producers using the same title but on different (or even on the same) release year.

In this particular case, I think we we could remove imdbid from the movie caps in the indexer, because the site appears to favour tmdbid, and once the Sonarr's indexer is deleted, the Sonarr app is shutdown and restarted to clear its indexer cache, and the Sonarr indexer is defined afresh to pick up the new caps, then Sonarr will start using the t=movie with the tmdbid instead, which should achieve the desired goal.

**Comment by garfield69** [comment]
v0.21.1043

**Comment by virusperfect** [comment]
Thank you that works perfectly

**Comment by ilike2burnthing** [comment]
The next release will have the same setting we added to RocketHD, to disable IMDB and TVDB ID searching, for AnimeWorld.

**Comment by garfield69** [comment]
v0.24.704
