### ISSUE TITLE
Tapochek error: Exception (tapochek): Got redirected to another domain

### ISSUE THREAD

**Issue by AARON8888** [Jackett/Jackett#14813]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: yes
Using proxy: Enable
Running in Docker: No
Starting Jackett: v0.21.1124
```

### Description

 An error occurred while testing this indexer
Exception (tapochek): Got redirected to another domain. Try changing the indexer URL to http://tapochek.net/.: Parse error

### Logged Error Messages

```text
See attached full log.
```

### Screenshots

[Full log.txt](https://github.com/Jackett/Jackett/files/13250911/Full.log.txt)

**Comment by garfield69** [comment]
The indexer is working for me so this suggests the problem is at your end.
Try using the Jackett dashboard to edit the tapochek config and click Okay to see if the login works, and then try the test again.
if it still fails, then provide an enhanced log so we can take a looksee.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.

**Comment by AARON8888** [comment]
Hi @garfield69
You can close ticket.
The problem only was at "Test" in Jackett. And I fit it myself changing in my account of tracker: date format in setting: 

Where it says: Y-m-d
It should say: d-m-Y

**Comment by garfield69** [comment]
ok. I will add an info box to the indexer config to remind users that the **Ymd** setting should be left as `Y-m-d H:i`
