### ISSUE TITLE
Pantsu.cat has full support of torznab and eztv

### ISSUE THREAD

**Issue by ewhal** [Jackett/Jackett#1493]
Pantsu.cat has full torznab and eztv rss feed support
Can be found at https://nyaa.pantsu.cat/feed/torznab and https://nyaa.pantsu.cat/feed/eztv

**Comment by chibidev** [comment]
@kaso17 @flightlevel I think we should remove the yml based implementation and use one of these instead. What do you think?

**Comment by ewhal** [comment]
We also have a json api if that's preferable.
https://dev.pantsu.cat/apidoc

**Comment by kaso17** [comment]
@ewhal I would like to migrate to the torznab API.
I noticed that your caps endpoint (https://nyaa.pantsu.cat/feed/torznab?t=caps) specifies various (custom) categories. But these aren't used in the returned items (https://nyaa.pantsu.cat/feed/torznab).
I would have expected one or more `<torznab:attr name="category" value="5070"/>` attributes for each item. Is this intentional?

**Comment by ilike2burnthing** [comment]
dead - https://github.com/Jackett/Jackett/pull/12434
