### ISSUE TITLE
Jackett removes my configuration files at startup

### ISSUE THREAD

**Issue by DarkFighterLuke** [Jackett/Jackett#15006]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
01-21 15:10:54 Info Starting Jackett v0.21.1566
01-21 15:10:55 Info Environment version: 6.0.26 (/app/Jackett/)
01-21 15:10:55 Info OS version: Unix 6.7.0.3 (64bit OS) (64bit process)
01-21 15:10:55 Info Jackett variant: CoreLinuxMuslAmdx64
01-21 15:10:55 Info File /etc/issue: Welcome to Alpine Linux 3.18
01-21 15:10:55 Info Running in Docker: Yes (image build: v0.21.1323-ls243)
01-21 15:10:55 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
01-21 15:10:55 Info App config/log directory: /config/Jackett
01-21 15:10:55 Info Using proxy: Disabled
01-21 15:10:55 Info Using FlareSolverr: http://172.23.0.9:8191
01-21 15:10:55 Info Using HTTP Client: HttpWebClient2
```

### Description

Jackett removes indexers configuration files at startup saying they are old.

### Logged Error Messages

```text
01-21 15:10:55 Info Removing old configuration file: /config/Jackett/Indexers/`indexer_name_here`.json.bak
01-21 15:10:55 Info Removing old configuration file: /config/Jackett/Indexers/`indexer_name_here`.json
```

**Comment by garfield69** [comment]
This message is generated when Jackett examines the id of a config file and does not find a corresponding  indexer with that same id.
Indexers are often removed when the web site has been offline for around 30 days, or because the web sites admin have requested Jackett not be used on them.
Once the indexer is removed, the corresponding config file in the `/config/Jackett/Indexers/` folder is also removed.

**Comment by DarkFighterLuke** [comment]
So is there any way to keep them in case they are still working bu requested for removal?

**Comment by garfield69** [comment]
Not that I can think of. We try not to antagonize web site admins by continuing to provide an indexer that the site clearly does not want us to access via Jackett. And continued use may lead to admins blocking/disabling your web site account (for private/semi private sites).

**Comment by DarkFighterLuke** [comment]
Ok thanks.
Using an older version can allow to use the old indexers, or are they removed independently of the version in use?

**Comment by ilike2burnthing** [comment]
You could use an older version of Jackett (although then you'll miss out on new indexers and updates to Jackett), or you can create your own indexer definition files (just download the old one from before it was removed) and change the ID to `indexer_name_here-backup` and filename to `indexer_name_here-backup.yml` (you'll also need to update the indexer as the site makes changes).

Again though, indexers are removed because either the site is dead, no longer compatible with Jackett, or the site admins have asked for it to be removed, so doing the above will either be pointless or run the risk of getting your IP address and/or accounts banned.

**Comment by DarkFighterLuke** [comment]
Thank you guys, got it.
