### ISSUE TITLE
[req]: Comando-Torrent/Bludv

### ISSUE THREAD

**Issue by bartche** [Jackett/Jackett#15030]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: Comando-Torrents and Bludv
- URL: https://vlambdas.oci.darklyn.online/
- Description: Brazilian indexers for movies and TV shows.
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): 
- Additional Comments: The URL provided is an indexer for both trackers. Returns JSON.
Base URL: https://vlambdas.oci.darklyn.online/
Search Comando-Torrents: https://vlambdas.oci.darklyn.online/indexers/comando_torrents?q={search_param}
Search Bludv: https://vlambdas.oci.darklyn.online/indexers/bludv?q={search_param}
```

**Comment by garfield69** [comment]
Both https://bludv.xyz/ and https://comando.la/ are sites that have a one-title-many-torrents structure, in other words, the search results on the sites only present a poster and some details, but you then have to navigate to the details page of every result in order to fetch the list of one or more magnets.
We try to avoid accessing site like this because of the heavy load on the sites servers as a result of multiple http GET requests, one for the results page, and up to 100 others for the torrent details pages from the results.

Therefore this 3rd party indexer service has to also be performing something similar.
The question i have is, does this 3rd party indexer store the results in its own database but running regular fetches on a scheduled basis, or is it performing the fetches live in response to queries?

In any case I'm reluctant to rely on a 3rd party service to front end a couple web sites to perform a task that Jackett would normally do directly for itself to the source web sites, if only they were not O-T-M-T structured.
@ilike2burnthing  thoughts?

**Comment by ilike2burnthing** [comment]
So this is using https://github.com/felipemarinho97/torrent-indexer, and appears to be a test site.

I'd want to hear from @felipemarinho97 before doing anything with it, as I don't want it to suddenly get 10K requests every 15mins and we end up crippling someone's home server. It also hasn't been touched in 4mths, and before that for 2yrs, so if it's not actively maintained then even if we don't break it, a change to either site could.

And yes, it mentions caching, but I'd want to know what is actually being cached, because if it's still just crawling pages like we would, then there's not much point is using a midde-man.

**Comment by ilike2burnthing** [comment]
@felipemarinho97 has only made 3 contributions since October last year, and their profile shows they are 'on vacation'. If they come back with an answer we can revisit this.

**Comment by felipemarinho97** [comment]
Hey @ilike2burnthing ! You are right, this site was not designed to be accessed by many people and there is no guarantee that I will not change the operating behavior, DNS address, etc in the future. Also, when receiving many requests from my server IP, Cloudflare protection from BluDV and Comando may start demanding captcha. So, the ideal scenario is to someone self-host both the Jackett and TorrentIndexer in their PC or server.

It may be possible to implement this directly in jackett, but I think will be hard and the performance will be very low.

My suggestion: add a guide suggesting that users deploy jackett + [torrent-indexer](https://github.com/felipemarinho97/torrent-indexer) locally
