### ISSUE TITLE
[wolfmax4k] (updating) Could not find releases from this URL

### ISSUE THREAD

**Issue by esguti** [Jackett/Jackett#15076]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Docker
```

### Description

An error occurred while adding the indexer with a valid URL https://wolfmax4k.com/

### Logged Error Messages

```text
[wolfmax4k] (updating) Could not find releases from this URL
```

**Comment by garfield69** [comment]
The indexer is working for me so this suggests the problem is at your end.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting/#could-not-find-releases-from-this-url
If you cannot figure out the issue then please turn on **enhanced** logging, repeat the test and provide the full **enhanced** log file which includes the _Debug_ and _HTML_. Hopefully this will provide the clue to understanding your issue.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.

**Comment by highfredo** [comment]
It seems that Telefonica has blocked the domain 🙁

**Comment by garfield69** [comment]
>It seems that Telefonica has blocked the domain
 
Then see the second item at https://github.com/Jackett/Jackett/wiki/Troubleshooting/#could-not-find-releases-from-this-url and if that does not work your only other option is item 3

**Comment by dam1d19Mayayo** [comment]
I have the same problem. In jackett the site https://wolfmax4k.com/ don´t work but with google chrome or firefox it´s working.
I don´t have VPN
