### ISSUE TITLE
Masters-TB - Login failed: Selector "a[href="logout.php"]" didn't match

### ISSUE THREAD

**Issue by AARON8888** [Jackett/Jackett#15075]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: yes
Using proxy: Enable
Running in Docker: No
Starting Jackett: v0.21.1819
```

### Description

See attached full log.
[error.txt](https://github.com/Jackett/Jackett/files/14372863/error.txt)

### Logged Error Messages

```text
Error: Login failed: Selector "a[href="logout.php"]" didn't match
```

**Comment by garfield69** [comment]
The indexer is working for me which suggests the problem is at your end.
Unfortunately you have only provided the enhanced log from after the login attempt, so we cannot see what responses were generated that lead to the site presenting the login page again instead of the index page which was expected.
I suggest you turn on enhanced logging again and use your Jackett dashboard to edit the masters-tb config and save to generate a fresh full log and provide the complete trace from the time the takelogin post was made.

**Comment by garfield69** [comment]
Interesting. The error was `Error: Please check the the captcha form`
So I looked at the web browser and found that the login page now has a reCAPTCHA on it, which explains the failure.
Funny how I was not getting that issue yesterday when I was using the indexer to do a fresh config save.
But now I am seeing this issue too. (Cache maybe?)
Since Jackett cannot solve a reCAPTCHA (even with the Flaresolverr app), I have switched to using the cookie method for the login.

**Comment by garfield69** [comment]
v0.21.1832

**Comment by mario-g98** [comment]
The same error happened once again.

[logs.txt](https://github.com/user-attachments/files/19547383/logs.txt)

**Comment by garfield69** [comment]
I test the masters-tb indexer daily, and I have to fetch a fresh cookie every time.
This is because the login page does not have a remember-me option, and the web site clearly wants to make you log in regularly.
And while previously we were able to auto-login the indexer using the login form, now that the login page has a turnstile captcha the cookie method is the only way to access the site via Jackett and there is nothing we can do about it.

**Comment by mario-g98** [comment]
I am adding the cookie following the "How to get the Cookie" instructions and still get this error. Maybe I am doing something wrong?

**Comment by ilike2burnthing** [comment]
Does your cookie look like this?

> SOCS=CSVR354th9df24SDFGf42rfweff4F4tu6gw424reHJF342jerE24S; cf_clearance=I686Hsfsgsh9DeUdlbXq.S3e96_Z3lSBxvqsfgwrKAgw-1735985825-1.2.1.1-8ey46noJ.ObRzAY07mvVdRTGgFQqXNxF0egw355tgtIY4yqUpBLHQXeSYCGdmnWN7bCRy9kMNTL8k1PsTIHWJT8vZ_TVragY6KaCp.iA_FkMjEqIEhoXFEeuiRaf2ktYysbmQkUKahKEEqlGzkUE8_7Yf2762xlTNiG.5MkpsS0QZaEsBfdg5tww4eIUw8ICKZp0hwsg9stgh5ts4FTWaiY894luCpCOH4ZEpUk8cVAc8n3GdoHAodl_5oCA.uY9WrIPVTkZoI3eQiAqcUIPyIjSSamJA2KRG45TERGA_LBhDNV_tND23jk1bT.Cka51X76Btnrsgw344f9Im1xdxqL4DV3ZXOkiL48laW4FzuXDyrwnQo54MdhbkI3pp7Dt6g; uid=123456; pass=sdv2r85u9c923hfw023wdf03289hdfu9

**Comment by mario-g98** [comment]
Not quite?
 
screenwidth=1920; screenheight=1200; uid=810157; pass=b04f2bf8470111bcd167eb3102da2874; cf_clearance=G2OMlUxF2Sqajh669hQI6DIu6LQ_OcoYcfGugg98AU8-1743508251-1.2.1.1-0Ne4LT9IzJ6UcGLDOGBb9wDFLMUhKHJr73g6dBCcu4CFDq7rFE5hz5.xs6abCdINk7ACdzs0H65AbknXdFptHqmzCFTaW.aGImMXnfhCquT7Gzu19IduYylms24ksz40kr9LF1nAwHS9XinWmzHZ_BPRrR2VLF4VPL9_TpISmC0eP4qA8rRd6YC.e0Qvfl3jRP0wy1mm9tAaMicxJKpTcpSXQCtxbJSknXCgs14m9RX8SRGZpC3YHp3LV6Zrf59Po21UKqfT42wOiYMdZgeg8xmLLADPf8nzBKqw4sMmxbx.egHoNp5ZhtYPKEY4FcTvlrqP5dZgsL3Hb6SI91GBQYHJOlpUXtX4T3znGgZDqeQ

This cookie is from the browse.php page.

**Comment by garfield69** [comment]
There are quite a few possibilities as to why your cookie may not have been accepted by masters-tb, see **Notes** section at https://github.com/Jackett/Jackett/wiki/TroubleShooting/#your-cookie-did-not-work and check if anything applies to you.

**Comment by mario-g98** [comment]
The problem was I was getting the cookie from another machine.
Now it worked. Thank you for the help!
