### ISSUE TITLE
Jackett does not start in windows 7 sp1

### ISSUE THREAD

**Issue by Juesto** [Jackett/Jackett#15135]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Windows 7 SP1 x64
```

### Description

unfortunately due to microsoft changes in .net, it no longer functions under windows 7, what version would you suggest me to try? latest has this issue probably all versions that use .net (core) have the issue?
it didn't install the service likely due to the same issue

### Logged Error Messages

```text
Failed to create CoreCLR, HRESULT: 0x80004005
```

**Comment by garfield69** [comment]
Jackett is still on .net 6 as far as I know (unless some dependents have snuck in an upgrade to .net 8 which would definitely break on win7)
have a try by following the answer to https://stackoverflow.com/questions/73560837/failed-to-create-coreclr-hresult-0x80004005-while-running-a-net-6-console-app
and see if that helps.
Otherwise my only other suggestion is to install windows docker desktop and run Jackett as a docker image.
let me know how you go.

**Comment by Juesto** [comment]
unfortunately there isn't much i can do because i have a lot of .net versions installed
docker does not work on windows 7

**Comment by Juesto** [comment]
figured this out
turns out i had some .net 7 gcname things set to clgrc.dll and stuff without .net 7 installed
environment variables, DOTNET_GCName, ComPlus_GCName and DOTNET_EnableWriteXorExecute=0

**Comment by garfield69** [comment]
\o/
