### ISSUE TITLE
[req]: 电影天堂

### ISSUE THREAD

**Issue by zY3unxTUEqszn7w** [Jackett/Jackett#15190]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: dytt （电影天堂）
- URL: https://www.dytt89.com/
- Description: dytt is a public tracker for all kinds of films, TVs and anime resources (SFW).
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): 
- Additional Comments:
```

**Comment by garfield69** [comment]
this site is not suitable for indexing with Jackett because search results do not contain categories, size, seeds or leech.
links on the details page may not contain a magnet but instead have a direct-play or 3rd party link to direct-downloads, or may have multiple magnets.
But the biggest issue is that the system also limits the search interval to 30 seconds makes it impractical for torznab queries.
