### ISSUE TITLE
[req]: some Chinese BT site

### ISSUE THREAD

**Issue by lemon66789** [Jackett/Jackett#15236]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

there are some Chinese BT sites here. Currently, all the Chinese BT sites in the software are animation sites. Now these are relatively richer. Can they be added?
https://www.rarbt.fun/
https://skrbttu.top/
https://www.btbtt12.com/
https://www.1bt0.com/
https://www.btnull.net/
https://www.btdx8.vip/
https://www.clgod.xyz/
https://www.dyttcn.com/
https://www.pianbar.net/

### Describe the solution you'd like

jackett has many Chinese users. I hope the above sites can be added to improve the user experience. Thank you very much.

**Comment by garfield69** [comment]
Maybe. But we are not going to implement this list as it stands, because we cannot keep track of which sites may be suitable, which get implemented, and which may eventually get deleted, from within the one ticket you have raised.

Please open an individual new indexer ticket for each site by using the indexer request form at https://github.com/Jackett/Jackett/issues/new?assignees=&labels=&projects=&template=indexer-request.yml&title=%5Breq%5D%3A+

**Comment by garfield69** [comment]
Oh, and before you get too carried away raising tickets, please read https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker so you have a better idea of what makes a suitable site for indexing.
