### ISSUE TITLE
[torrentleech] (testing) Exception (torrentleech): Login failed: No form found on https://www.torrentleech.org/user/account/login/ using form selector form[name="login-form"]: Login failed: No form found on https://www.torrentleech.org/user/account/login/ using form selector form[name="login-form"]

### ISSUE THREAD

**Issue by muppet3000** [Jackett/Jackett#15327]
Getting this error since this morning with jackett, I'm running a version from a few months ago (v0.21.1594) but can't find any recent release with a 'fix' for this in the change logs. 
I'm away from my system currently so can't test jumping straight to latest very easily. 

Logging the bug in case this is a new issue, but feel free to just tell me to upgrade to latest if that'll fix it.

**Comment by garfield69** [comment]
The  indexer is  working for me  which suggests the problem is at your end.
Please provide the environment data (restart jackett, view log, scroll the the bottom, copy the last 10 lines).
Then turn on enhanced logging on the dashboard, repeat your test and upload the full log.Hopefully the html and debug in the log will give a clue to your issue.

**Comment by muppet3000** [comment]
Thanks for the swift response, all it took was a restart, odd given that it has been running for 4 months without issue. 
All good now though. I need to bump the version at some point though, it's now completing that in running an out of date version.
