### ISSUE TITLE
[eztv] (testing) Test search in EZTV => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

### ISSUE THREAD

**Issue by moose999** [Jackett/Jackett#15387]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://192.168.1.159:8191/
Using proxy: Disabled
App config/log directory: /var/lib/jackett/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
File /etc/issue: Ubuntu 22.04.4 LTS \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 6.8.4.3 (64bit OS) (64bit process)
Environment version: 8.0.6 (/opt/Jackett/)
Starting Jackett v0.22.76
```

### Description

Test EZTV.
I am using https://eztv.ninjaproxy1.com/ as the EZTV URL, which works on browsers on other PCs on my network. 

### Logged Error Messages

```text
Test search in EZTV => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.
```

**Comment by garfield69** [comment]
Yes I get this too. 
It appears that the none of the ninja alternate domains are allowing the show-links button to display the download links in the rows, so the indexer returns zero results.
The indexer supplies the correct cookie ` layout=def_wlinks` to enable the site to show magnets and torrents links in the results, but these sites are not working. 
You can test this for yourself by using the browser at https://eztv.ninjaproxy1.com/home and clicking on the show-links button.

Ideally we want both DL links on the main results page rather than having to fetch the details pages, because using the details page the indexer will only be capable of showing one of the download links.
@ilike2burnthing  I am inclined to just remove any alternate domains that do not abide by the layout=def_wlinks cookie?

**Comment by ilike2burnthing** [comment]
Yea, get rid of them, no problem with that.

In checking the proxies, it looks like https://abcproxy.org/ is gone completely. Same for you?

**Comment by garfield69** [comment]
yes.
