### ISSUE TITLE
rptscene login error

### ISSUE THREAD

**Issue by tzatzamira** [Jackett/Jackett#15380]
### Have you checked our Troubleshooting page for your issue?

- [ ] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [ ] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [ ] I have read the Contributing Guidelines

### Environment

```markdown
-
```

### Description

Name: RptScene
- URL: https://rptscene.xyz
- Description: RPTScene is a Private Torrent Tracker for MOVIES / TV / GENERAL
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): MST 4 days, global ratio 0.5
registration currently open

### Logged Error Messages

```text
ERR_CONNECTION_TIMED_OUT
ERR_CONNECTION_REFUSED
ERR_ADDRESS_INVALID
DNS_PROBE_FINISHED_NXDOMAIN (DNS Lookup Error)
Error 503: Service Unavailable
```

**Comment by garfield69** [comment]
The rptscene indexer is working for me which suggests that the problem is at your end.
You selection of errors is of little use on its own, other than to point you to our trouble shooting wiki [here](https://github.com/Jackett/Jackett/wiki/Troubleshooting)
If you want relevant help, the please open the correct report [here](https://github.com/Jackett/Jackett/issues/new?assignees=&labels=&projects=&template=bug_report.yml) and fill in **ALL** the requested data, and if you include a full enhanced log this may give a clue to what is going on.
The form you used in this ticket is for raising a request for a new indexer and will be closed.
