### ISSUE TITLE
[req]: CRT2FA to filter results

### ISSUE THREAD

**Issue by NLZ** [Jackett/Jackett#15400]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Cathode-Ray.Tube's CRT2FA search sometimes returns irrelevant results

### Describe the solution you'd like

I know that Jackett filters the search result for some trackers like SpeedApp.
Would it be possible to enable it for CRT2FA as well?

**Comment by garfield69** [comment]
yes I think we can.
at the moment we are using the web site's `Search Terms` query so that we can support both a query for imdbid and a query for keywords,
but `Search Terms` is a general search which includes titles and description.
But if we put an andmatch on the rows, then that will break searching for imdbid so that is not suitable.
we could change the indexer so that we use `Search Terms` for the imdbid search, and `Title` for the keywords 
and I think this should achieve what you want.

**Comment by garfield69** [comment]
v0.22.106

**Comment by NLZ** [comment]
Thank you
