### ISSUE TITLE
[req]: DenOfSimps

### ISSUE THREAD

**Issue by wagerbomb** [Jackett/Jackett#15460]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: DenOfSimps
- URL: https://denofsimps.club/
- Description: DenOfSimps (DoS) is a Private site for 3x Fansite content only.
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): 5 day MST
- Additional Comments: DoS is running on UNIT3D v8.1.3
```
Registration is invite only ATM

**Comment by garfield69** [comment]
If you send an invite to `garfieldsixtynine [at] gmail [dot] com` I will build the cardigann indexer.

Alternatively, given that the site is using unit3d we can usually build an indexer using a template, but we will need to see the html content of the torrents page in order to set the categories.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source

**Comment by wagerbomb** [comment]
Invite has been sent by the owner.

**Comment by garfield69** [comment]
v0.22.275

**Comment by garfield69** [comment]
https://denofsimps.club/ ERR_CONNECTION_REFUSED

**Comment by garfield69** [comment]
@wagerbomb do you have any info on the state of denofsimps?
If the site does not come online in 7 days time or there is not replacement domain or other info we will remove the indexer soon afterwards.

**Comment by garfield69** [comment]
v0.22.985
