### ISSUE TITLE
Bitru and NNMclub[req]: 

### ISSUE THREAD

**Issue by bylampa** [Jackett/Jackett#15475]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
NNMclub перестал проходить тест, flaresolver рабочий, версия 3.3.17. Так же и bitru стал на него ругаться
```

**Comment by bylampa** [comment]
ошибка вот такая

**Comment by bylampa** [comment]
Exception (noname-club): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.

**Comment by garfield69** [comment]
I am seeing lots of different indexers that rely on flaresolverr failing to pass the challenge since yesterday. I believe this is a flaresolverr problem with a change that cloudflare have made that is not being recognised by flaresolverr at the moment.
Keep an eye out on https://github.com/FlareSolverr/FlareSolverr and update your flaresolverr when 3.3.22 is released, whenever that happens.
Not a problem with Jackett, so I am closing this ticket.
