### ISSUE TITLE
knaben --> Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by AARON8888** [Jackett/Jackett#15496]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
HTTP client: HttpWebClient
FlareSolverr
Proxy: HTTP
App: C:\ProgramData\Jackett
Docker: No
Jackett variant: CoreWindows, 64 bits, last version
```

### Description

Only for "Test": Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

However, "Search" option is running well.
See full log: 
[full log.txt](https://github.com/user-attachments/files/16201345/full.log.txt)

### Logged Error Messages

```text
See above full log.
```

**Comment by shoyrock** [comment]
I'm having the same problem but I'm using it on unraid

**Comment by ilike2burnthing** [comment]
Working ok here. Temp issue?

Looks like you've trimmed too much from the log, I'd need to see everything from the moment you search to when no results are returned.

**Comment by shoyrock** [comment]
this is my log file 
[log.txt.20240713.00000.txt](https://github.com/user-attachments/files/16202972/log.txt.20240713.00000.txt)

**Comment by garfield69** [comment]
The indexer is working for me so this suggests the problem is at your end.
@shoyrock  Please turn on **enhanced** logging, repeat the test and provide the full **enhanced** log file which includes the _Debug_ and _HTML_.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.

**Comment by shoyrock** [comment]
Here you go 
[log.txt](https://github.com/user-attachments/files/16210445/log.txt)

**Comment by garfield69** [comment]
v0.22.328

**Comment by garfield69** [comment]
Yeah, I'm not entirely sure what is going on, but it appears that you are not getting cached results from knaben when you do the test as the indexer expects. Instead you are getting live results. So the row tags start with Checked instead of Cached, hence the indexer show no results.
I've bypassed the issue by coding the indexer to expect either tag, but ideally someone can properly diagnose the variation causing the original discrepancy in results.

**Comment by shoyrock** [comment]
Thanks a lot if this happens again. Disabling Cache could be able to fix the problem

**Comment by garfield69** [comment]
we are not talking about the Jackett cache, but the knaben web site cache, in other words, the torrent search pages live search versus fast search 
![image](https://github.com/user-attachments/assets/b24ffd6f-cd4a-477c-97d5-98e41c4534bc)

**Comment by shoyrock** [comment]
OK, gotcha. Thanks for the clarification

**Comment by AARON8888** [comment]
Now, working for me too. Many thanks all :)
