### ISSUE TITLE
LastFiles --> Authentication failed because the remote party sent a TLS alert: 'ProtocolVersion'.

### ISSUE THREAD

**Issue by AARON8888** [Jackett/Jackett#15516]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
HTTP client: HttpWebClient
FlareSolverr
Proxy: HTTP
App: C:\ProgramData\Jackett
Docker: No
Jackett variant: CoreWindows, 64 bits, last version
```

### Description

error: Authentication failed because the remote party sent a TLS alert: 'ProtocolVersion'.
See full log: 
[full log.txt](https://github.com/user-attachments/files/16417222/full.log.txt)

### Logged Error Messages

```text
See above full log.
```

**Comment by garfield69** [comment]
We've come across ProtocolVersion issues with other indexers in the past. It appears to be a windows .NET issue, because while my win10 Jackett indexer fails with ProtocolVersion my ubuntu image running under my win10 VirtualBox works fine.
Browsers on both platforms can login fine, although I notice that on both platforms (which use the same chrome 127 version) I have to login twice, as the first login accepts my creds but presents the login page again and the second login presents the home page.

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/14451#issuecomment-1595214698

Linking older relevant issue here, as linking this issue to the LF staff.

**Comment by garfield69** [comment]
My win10 Jackett is working with the lastfiles indexer today. have you tried again?

**Comment by AARON8888** [comment]
Hey! I´ve just checked and successfully :)
Why now it´s ok? tbh idk
Very strange, but now I´m happy.

**Comment by ilike2burnthing** [comment]
Resolved by LF staff, seemed happy to help.
