### ISSUE TITLE
[req]: NewHeaven

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#15527]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: NewHeaven
- URL: https://newheaven.nl/
- Description: NewHeaven is a GERMAN Private tracker for MOVIES / AUDIO / TV / GENERAL
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): 0.8
- Additional Comments: 
replace C# torrentheaven with yaml newheaven
original source from PR https://github.com/Prowlarr/Indexers/pull/477
corrected for schema standards and fixed up
Engine: Aeonflux
registration: Invitation only
```

**Comment by garfield69** [comment]
v0.22.425

**Comment by Bretterteig** [comment]
Thanks for picking this up. This got a few issues though.

The input "time" is an absolute value for days since release. Change wording:
`# 0 any, 1 1day, 2 1week, 3 30days, 4 90days`
to
`days since upload, 0 for all`

The selector for "title" and "details" requires the dual attribute selector. Please change to 
`a[href^="index.php?strWebValue=torrent&strWebAction=details&id="][href$="&view=1"]`

The html table does not contain the download url. We have to build it.
Extract the id of the torrent from the details url:
```    
id:
  selector: a[href^="index.php?strWebValue=torrent&strWebAction=details&id="][href$="&view=1"]
  attribute: href
  filters:
    - name: querystring
      args: id
```

and build the download string (always the same):
```
download:
  text: "index.php?strWebValue=torrent&strWebAction=download&id={{ .Result.id }}"
```
For the *volumefactors they use images and text. Please use these:
```
downloadvolumefactor:
  case:
    div:contains("50% DL"): 0.5
    div:contains("25% DL"): 0.25
    img[src$="/freeleech.png"]: 0
    img[src$="/onlyup.png"]: 0
    "*": 1
uploadvolumefactor:
  case:
    img[src$="/freeleech.png"]: 0
    div:contains("200% UP"): 2 
```

The new date mechanism you added does not work and only returns "now". I tried adding strdump but it never returned anything. Any idea? Selectors and processing seem fine to me

**Comment by garfield69** [comment]
Ah, well I guess that's what I get from using as source a C# indexer that does not work and an HTML dump that is clearly well out of date ;-)
It would be very useful if you could provide a fresh HTML dump of the web sites' torrent search page for me to examine.
See  https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source for details.
Thanks.

**Comment by Bretterteig** [comment]
[NewHeaven.txt](https://github.com/user-attachments/files/16566180/NewHeaven.txt)

I tried to build a search with as many flags as possible. Only one missing, 50% DL, which behaves the same as 25% DL

**Comment by garfield69** [comment]
Excellent. thank you.

**Comment by garfield69** [comment]
v0.22.431

**Comment by Bretterteig** [comment]
One more issue with dateparse:

The current format cannot be parsed because of a missing whitepsace:
`Error while parsing DateTime "08.08.2024 20:01+01:00", using layout "dd.MM.yyyy HH:mm zzz" (dd.MM.yyyy HH:mm zzz): String '08.08.2024 20:01+01:00' was not recognized as a valid DateTime.`

Does it not present an issue when there are multiple matches to title title, details and _id selector?
![selectorresult](https://github.com/user-attachments/assets/6b0767b5-45a0-43f5-9cbe-c8956c03a44d)

The validation fails in Prowlarr when onlyup is selected because the first 100 results mostly not contain an onlyup torrent

**Comment by garfield69** [comment]
Making progress ;-)
The date_year is an easy fix, I'll push a release as soon as the builds are complete.

As for the prowlarr onlyup test fail, there is nothing can be done about this. This is because the web site does not appear to support a search for onlyup, so the indexer does a filter after the web search results are returned.

**Comment by garfield69** [comment]
>Does it not present an issue when there are multiple matches for the title, details and _id selector?

No it does not present a problem, because the document processor selector lands on the first match and returns that href to the indexer. 
And having checked the row result content, the first match is always the one in the title, which gives us both the text for the title, and the details link, so its constant throughout all rows.
Its a standard method we use for most indexers.

**Comment by garfield69** [comment]
v0.22.432
