### ISSUE TITLE
[req]: torrent911.eu

### ISSUE THREAD

**Issue by rom1du29** [Jackett/Jackett#15553]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: torrent911
- URL: https://torrent911.eu
- Description: torrent911 est un torrent en français films series musiques ebooks logiciels et jeux
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): 
- Additional Comments:
```

**Comment by garfield69** [comment]
We used to have an indexer for this site back when they presented search results in a list format, with title, category, date, size, seeds, leech, and DL link.
But back in June they switched to a poster format, which only has the title, and all the other details are on the torrent details page.
For this reason this site is no longer suitable for indexer with Jackett.

**Comment by GuillaumeCisco** [comment]
Hello, why not scrapping also details per page and limit it to first 50 results for example?
Is there any issues due to rate limit or other restrictions possible?
Trying to understand to find a solution 😄

New urls are https://www.torrent911.ke/ or https://www.torrent911.lol, usually only accessible via vpn or dns tweaks.

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing
