### ISSUE TITLE
52bt can only crawl 20 results on the first page, and cannot crawl the second page.

### ISSUE THREAD

**Issue by szicely** [Jackett/Jackett#15598]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
52bt can only crawl 20 results on the first page, and cannot crawl the second page.
```

### Description

52bt can only crawl 20 results on the first page, and cannot crawl the second page.

### Logged Error Messages

```text
52bt can only crawl 20 results on the first page, and cannot crawl the second page.
```

**Comment by garfield69** [comment]
Usually when a site only presents 20 rows, its because of one of two reasons: their server has low specs, or they want more users click so they can present more ads.
I will add a fetch for a second page, but also add a 2 second delay in between, so as not to trigger an overload that might cause the site to start adding cloudflare BOT protection, 'cause that will suck and we are not in the business of making sites fail.

**Comment by garfield69** [comment]
v0.22.604
