### ISSUE TITLE
[yggtorrent]  List topday torrent

### ISSUE THREAD

**Issue by Syspoke** [Jackett/Jackett#15604]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Hello,
Is it possible to list the torrents of the topday torrent webpage (ygg.re/top/day), because the list is refreshed more quickly than via the normal search of the site, if we want for example to monitor the immediate availability of an episode?

### Describe the solution you'd like

I tried to modify the yggtorrent.yml code but I can't list the torrents :(

Can you add this option or give me an example of code to follow to list this topday page?
Thanks

**Comment by garfield69** [comment]
This is not possible using the current indexer design.
This is because the search page returns results in a HTML page with all the HTML tags filled in.
While the top/day page is a HTML shell with just the headers, and the data comes from a subsequent JSON response which your browser using the sites JavaScript's will format into a display on your browser page dynamically.
The indexer cannot run the JavaScript so it does not see the JSON response.

**Comment by Syspoke** [comment]
Indeed, I understand better, thank you.

But going through this query:
/engine/ajax_top_query/day

We manage to have the list of topday torrents with the necessary information.

Only I can't parse the result of the query by playing with rows and field to list the torrents :p

I'll try to dig into it.
