### ISSUE TITLE
Api for test all indexers

### ISSUE THREAD

**Issue by hillaliy** [Jackett/Jackett#15657]
### Have you read our current Readme and Wiki?

- [X] I have read the Wiki

### Is there already a request for this change?

- [X] I have checked older issues, open and closed

### Readme or Wiki?

Wiki

### Details

```markdown
Hi I’m from Homarr team. I’m looking your api for test all indexers.
```

**Comment by garfield69** [comment]
Probably the most reliable way would be to first query which indexers are configured on the users Jackett server
```
http://localhost:9117/api/v2.0/indexers/all/results/torznab/api?apikey=your-jackett-api-key-here&t=indexers&configured=true
```
and then once you've extracted the IDs of the configured indexers, perform a keywordless search (which is what a TEST does on the Jackett dashboard for an indexer) over each active indexer
```
http://localhost:9117/api/v2.0/indexers/<an_Indexer_Id_Here>/results/torznab/api?apikey=your-jackett-api-key-here&?t=search&q=
```

I would not recommend doing a keywordless search using the aggregate indexer ALL (as used in the first example above), because any indexer whose corresponding web site is out of service or running slow will delay the response such that your app may timeout waiting on a response.

Hopefully I've understood your question, feel free to rephrase if this is not what you were after.

**Comment by hillaliy** [comment]
this url return indexers json - http://192.168.0.12:9117/api/v2.0/indexers/all/Results?apikey=XXXXXXXXXXXXXX
About Test all button - 
<img width="546" alt="Screenshot 2024-10-18 at 13 06 44" src="https://github.com/user-attachments/assets/89b5d149-0618-4e3d-876e-20de686e1de3">
what url you're using?

**Comment by garfield69** [comment]
The URL you mentioned is used by the Jackett Dashboard to communicate to the Jackett server and the JSON response is used by the Dashboard to present the Dashboard results and error messages.  It is an undocumented internal API, which could be changed at any time to suit the needs of Jackett's requirements.
Admittedly the internal API has not changed in some time, and you can uses it if you wish, at your own risk.

The official Torznab API used by 3rd party apps (such as *arr apps like Sonarr, Radarr, etc) to make queries to Jackett is documented in the README, a summary of which is available at this wiki page https://github.com/Jackett/Jackett/wiki/Jackett-API
