### ISSUE TITLE
[ex-torrenty] (updating) Login failed: Selector "a[href^="/logout.php"]" didn't match

### ISSUE THREAD

**Issue by NeGroRA** [Jackett/Jackett#15660]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown

```

### Logged Error Messages

```text
An error occurred while updating this indexer
Login failed: Selector "a[href^="/logout.php"]" didn't match
```

**Comment by NeGroRA** [comment]
![image](https://github.com/user-attachments/assets/6a916579-051d-47d7-9553-bd709772fd25)

**Comment by garfield69** [comment]
The indexer is working for me which suggest the issue is at your end.
Placing the error message in the environment section is not helpful so I'm going to direct you to a general help page that should help you to figure out your issue.
See https://github.com/Jackett/Jackett/wiki/TroubleShooting/#login-failed-no-form-found-on-url

In the event you cannot resolve it on your own, provide the **environment details**,
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-environment-details

And a **full Enhanced log**, perhaps the additional debug and HTML in the enhanced log will give us a clue to what is going on.
See https://github.com/Jackett/Jackett/wiki/TroubleShooting/#how-to-provide-a-jackett-enhanced-log-for-a-ticket
