### ISSUE TITLE
[yggcookie] (updating) Address not available (www.ygg.re:443): Address not available

### ISSUE THREAD

**Issue by Recreabox** [Jackett/Jackett#15688]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using Flaresolverr
```

### Description

When I want to add Yggtorrent or Ygg Cookies on Jackett, I get the error message: 
`An error occurred while testing this indexer
Exception (yggtorrent): Address not available: Address not available (www.ygg.re:443)`

### Logged Error Messages

```text
`An error occurred while testing this indexer
Exception (yggtorrent): Address not available: Address not available (www.ygg.re:443)`
```

**Comment by Morchipon** [comment]
#15686

**Comment by garfield69** [comment]
You left out a properly filled in environment section so this makes it difficult to tailor the response ;-(
Take a look at https://github.com/Jackett/Jackett/wiki/Troubleshooting#a-connection-attempt-failed and see if this help you.
May also be related to https://github.com/Jackett/Jackett/issues/15534 but I cant be sure, because you provided no environment details, so take a look and see if its relevant to you.

Failing all this the please provide a full enhanced log.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
It may provide a clue to what is going on. Or not ;-b
