### ISSUE TITLE
katcr.co log in with passkey  work for a short period of time

### ISSUE THREAD

**Issue by bubez81** [Jackett/Jackett#1589]
jackett version 0.7.1594.0 it works for two or three times then i receive this message:
Login failed, got redirected

**Comment by thebluepotato** [comment]
Thanks for opening the issue. From what I could gather, KAT has now implemented a redirect from the torrent login page to the community login page. The current workaround is to log into the community with your browser (https://katcr.co/show/community/index.php?action=login). Then try the login again with Jackett and it should work.
The more long term solutions that I or someone else will have to implement are:

- Have a two-step login : probably not possible with the YAML definition alone
- Have the user log in and input the cookie (complicated to get but should work well enough once set up)
- Prevent redirection?

**Comment by thebluepotato** [comment]
To provide a short update: I've created a version of the KAT definition using cookies and it works (i.e. connection and testing succeed). I'm waiting for the current definition to fail again and then I'll see if the cookie version still works (which it should). Setup is not overly complicated, just not as elegant as username and passkey alone.

**Comment by thebluepotato** [comment]
Longer update: KAT's two-step login really is an obstacle here. I've tried various combinations:
 - Cookies: this works for some time but they end up being somehow invalid after sometime and they work again once you've logged yourself into the Community page with your browser... I.e., it fails when the current implementation fails (and works when it works too).
 - I've tentatively tried to at least log into Community with Jackett but there the password is hashed twice using a salt and that needs scripting that I really don't think YAML provides...

Therefore all that's left, for now, is to either fully write KAT's definition in C# or try again without the logins (because I've yet to see the captchas again).

**Comment by kaso17** [comment]
Closing this for now as it should work for the time being.
