### ISSUE TITLE
[Scenefz] Configuration Failed

### ISSUE THREAD

**Issue by panoramasecret** [Jackett/Jackett#1679]
Myself and several other users we cannot add indexer scenefz. 

The original issue #1398 dated 20 May 2017 was not sorted out. On 30 May 2017 I add a comment asking if anybody sorted out this issue, but no feedback, therefore, I opened new issue #1453 on 6 June 2017 which was closed as a duplicate for #1398. 
On 8 June I added a new comment to #1398 asking again if anybody looking into this issue.

Today passed **3 months** since the original issue was brought to your attention and we still don't have any feedback if this problem will be sorted out.

**Comment by JigSawFr** [comment]
I want to say that Jackett is an OpenSource project, we are not employees.
We try to do our best to maintain this application on free time.
You can sponsorise a feature to accelerate solving your problem.
https://www.bountysource.com/issues/48351476-scenefz-duplicate-issue

**Comment by chibidev** [comment]
@panoramasecret I understand that the tracker not working is frustrating, however as @JigSawFr mentioned Jackett is an open-source project. We are all working on making it better, but we have limited resources as well. One of the advantages of being an open-source project is that anyone can contribute. I do believe that eventually we'll look into the issue, but we have other priorities, so don't take out your frustration on us.
If you want speed it up instead of rampaging ask us how you could help.  As I'm looking the original issue there's not much of a description about what's happening. Here's what the template for a new issue says:
```
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting
```

**Comment by panoramasecret** [comment]
Hi,



OpenSource noted, my mistake, you are right. I’ve made a donation to help
the project. My frustration was only for lack of feedback.



All my respect for your efforts.



*From:* JigSaw [mailto:notifications@github.com]
*Sent:* 17 August 2017 12:03
*To:* Jackett/Jackett <Jackett@noreply.github.com>
*Cc:* panoramasecret <panoramasecret@gmail.com>; Author <
author@noreply.github.com>
*Subject:* Re: [Jackett/Jackett] Scenefz duplicate issue (#1679)



I want to say that Jackett is an OpenSource project, we are not employees.
We try to do our best to maintain this application on free time.
You can sponsorise a feature to accelerate solving your problem.
https://www.bountysource.com/issues/48351476-scenefz-duplicate-issue

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Jackett/Jackett/issues/1679#issuecomment-323011886>,
or mute
the thread

**Comment by JigSawFr** [comment]
Need to be recreated from scratch.

**Comment by JigSawFr** [comment]
Almost finished, maximum infos are grabbed.

**Comment by JigSawFr** [comment]
Pull Request merged.
