### ISSUE TITLE
Cannot open/access Jackett

### ISSUE THREAD

**Issue by Richard-Riddick** [Jackett/Jackett#1691]
I'm trying to use Jackett on macOS 10.12.6 using the instructions found in the ReadMe file, but when I try to access it in a web browser, I receive err_connection_refused messages.

Jackett version: 0.8.67
Mono version: 4.8.0
Browsers tried: Chrome 60.x, Firefox 55.x, Safari

When I run mono --debug JackettConsole.exe, it tells me to use mono-service instead. When I do, I get the following:

`08-19 17:16:48 Info App config/log directory: /Users/XXXX/.config/Jackett 
08-19 17:16:48 Info Starting Jackett 0.8.67.0 
08-19 17:16:48 Info Environment version: 4.0.30319.42000 (/Library/Frameworks/Mono.framework/Versions/4.8.0/lib/mono/4.5) 
08-19 17:16:48 Info OS version: Unix 16.7.0.0 (64bit OS) 
08-19 17:16:48 Info ThreadPool MaxThreads: 400 workerThreads, 400 completionPortThreads 
08-19 17:16:48 Info mono version: 4.8.0 (mono-4.8.0-branch/8f6d0f6 Thu Mar  9 11:59:17 EST 2017) 
08-19 17:16:48 Info Using HTTP Client: HttpWebClient 
08-19 17:16:48 Info Loading Cardigann definitions from: /Users/XXXX/.config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /Library/Frameworks/Mono.framework/Versions/4.8.0/lib/mono/4.5/Definitions 
08-19 17:16:48 Info Adding aggregate indexer 
08-19 17:16:48 Info Starting web server at http://*:9117/ 
08-19 17:16:48 Error Top level exception System.MissingMemberException: The server factory could not be located for the given input: Microsoft.Owin.Host.HttpListener
  at Microsoft.Owin.Hosting.Engine.HostingEngine.ResolveServerFactory (Microsoft.Owin.Hosting.Engine.StartContext context) [0x00045] in <f9c6a24237684643b127a582774aa6dc>:0 
  at Microsoft.Owin.Hosting.Engine.HostingEngine.Start (Microsoft.Owin.Hosting.Engine.StartContext context) [0x00042] in <f9c6a24237684643b127a582774aa6dc>:0 
  at Microsoft.Owin.Hosting.Starter.DirectHostingStarter.Start (Microsoft.Owin.Hosting.StartOptions options) [0x0000c] in <f9c6a24237684643b127a582774aa6dc>:0 
  at Microsoft.Owin.Hosting.Starter.HostingStarter.Start (Microsoft.Owin.Hosting.StartOptions options) [0x0002e] in <f9c6a24237684643b127a582774aa6dc>:0 
  at Microsoft.Owin.Hosting.WebApp.StartImplementation (System.IServiceProvider services, Microsoft.Owin.Hosting.StartOptions options) [0x0004b] in <f9c6a24237684643b127a582774aa6dc>:0 
  at Microsoft.Owin.Hosting.WebApp.Start (Microsoft.Owin.Hosting.StartOptions options) [0x00014] in <f9c6a24237684643b127a582774aa6dc>:0 
  at Microsoft.Owin.Hosting.WebApp.Start[TStartup] (Microsoft.Owin.Hosting.StartOptions options) [0x00023] in <f9c6a24237684643b127a582774aa6dc>:0 
  at Jackett.Services.ServerService.Start () [0x00071] in <11946a10c443404598a467665d80690e>:0 
  at JackettConsole.Program.Main (System.String[] args) [0x005f5] in <8f2a1723976445f1a4ec57a554c5ebff>:0`

I do not see mono running in Activity Monitor. I've tried running it from my Downloads folder as well as Applications. Please help, thank you all!

**Comment by thebluepotato** [comment]
I think I know why it fails: the log loads definitions from `/Library/Frameworks/Mono.framework/Versions/4.8.0/lib/mono/4.5/Definitions` but this should actually be `/path/to/Jackett/Definitions`, in my case `/Applications/Jackett/Definitions`. My guess is that the working directory when you call Jackett isn't Jackett's but Mono's. That's why it can't locate the server and doesn't load any definitions.
First of all, how are you calling Jackett from Terminal? Do you `cd` to Jackett's folder and then run `mono --debug JackettConsole.exe` or do you directly run `mono --debug /path/to/Jackett/JackettConsole.exe`?
I've tested both possibilities and both work on my Mac... But maybe it changes something for you?

In any case, there's a way to use Jackett as a service on Mac that I find waaay easier once set up.
I might add it to the README but here's the steps:
 - Create a file called `org.Jackett.plist`
 - Paste following content, editing the paths where needed:
````
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>org.user.Jackett</string>
	<key>ProgramArguments</key>
	<array>
		<!-- Path to Mono -->
		<string>/Library/Frameworks/Mono.framework/Versions/Current/Commands/mono</string>
		<!-- Path to JackettConsole.exe -->
		<string>/Applications/Jackett/JackettConsole.exe</string>
	</array>
	<key>WorkingDirectory</key>
	<!-- Path to Jackett -->
	<string>/Applications/Jackett/</string>
	<key>RunAtLoad</key>
	<true/>
	<key>LaunchOnlyOnce</key>
	<true/>
	<key>KeepAlive</key>
	<true/>
</dict>
</plist>
````
 - Save the file at /Users/[username]/Library/LaunchAgents/org.Jackett.plist

Now it will load on the next startup but you can always and already launch it using:
`launchctl load ~/Library/LaunchAgents/org.Jackett.plist`
And stop it using:
`launchctl stop org.user.Jackett`
These command don't show success or failure but you'll see if mono's running in the Activity Monitor. Logs and config are located, as before, in `~/.config/Jackett/`.
Hope this can help you!

**Comment by thebluepotato** [comment]
@Richard-Riddick Please check the new instructions in the README on `master`. The script should make things easier now.
