### ISSUE TITLE
Request - script to check if all is working

### ISSUE THREAD

**Issue by Jorman** [Jackett/Jackett#1795]
Hi, I open this little request, I hope some people need this too and we can make it all together

Jackett works with many programs like couchpotato, sonarr, radarr etc etc..

Is possible to make a "external" script to check if the all programs, Jackett included are working and if not restart the service?
I know that this script must be installed like a service, but in my opinion can help.

I've a qnap with jackett and some other program that use Jackett, and I don't know why and when but sometimes I found Jackett or cp or sonarr or other that are not working so I need to restart it manually.

So my idea is to make a script and put it under a cronjob, so if the service is freezed or not working the script restart it.... Naturally every machine and every system must have to edit the configuration file to adapt some command/path

What do you think about it?

**Comment by kaso17** [comment]
I suggest that you use an init system with automatic restart support e.g. (systemd).
I personally only had one jackett freeze in several years of usage and I blame that on the libcurl integration. Since I moved to mono 5 and it's native httpclient I never had a freeze.

If you plan to setup a watchdog script I would suggest to simply setup a simple wget/curl based script to see if the web gui is still responsive.

**Comment by Jorman** [comment]
Tnx for your suggest! Not a bad idea to check the port!
I don't know what is, mono 5 is not available for qnap model, right now, so I can't try it. Only 4.8.1 but I don't know if is a good idea switch to it.

**Comment by flightlevel** [comment]
@Jorman Script would have to be something you write yourself, going to be very different for every user
