### ISSUE TITLE
Please add filelist 4K category

### ISSUE THREAD

**Issue by sahara101** [Jackett/Jackett#1951]
Hi, 

I am running Jackett 0.8.147.0 on QNAP. Can you please add filelist 4k category?

Thank you

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  
Mono version (if not using Windows):  

-------------------------------

**Comment by sahara101** [comment]
They now have 3 new categories:

Movies 4K - cat=6 (encodes from Blu-Ray 4K discs etc)
Movies 4K Blu-Ray - cat=26 (Blu-Ray 4K discs and remuxes)
TV Shows 4K - cat=27

**Comment by sahara101** [comment]
Hello?

**Comment by sahara101** [comment]
I understand that these are not instant changes. But a reply would be nice.

**Comment by garfield69** [comment]
>Hello?      

Hello.    

>I understand that these are not instant changes. But a reply would be nice.      

Most of the team is either on holiday, on walkabout, working on other projects, having a life, or not interested in this topic. Nothing personal.     

I could make these changes for you, but I would not be able to test that they work (other than to confirm that the source compiled cleanly) because FileList is a private site and I don't have a login.     
On that basis, do you want me to make the changes you requested, or would you prefer to wait for a dev that has an invite?

**Comment by sahara101** [comment]
Just wanted to know that my request is being taken into account. I could send you an invite, but no idea how (don't see any PM on github).

Thanks.

**Comment by kaso17** [comment]
fixed via d0342019bcef66b2025b675f6bf4c1e43338a506
