### ISSUE TITLE
[Minor/Cosmetic issue] JackettTray: Odd, empty window popping up

### ISSUE THREAD

**Issue by twiz-ahk** [Jackett/Jackett#1959]
Jackett Version 0.8.259.0
OS: Windows 10 (x64)

![](https://i.imgur.com/A0qJCHe.png)

I think it only happens when the tray app is started.
I believe it to belong to the "JackettTray.exe" process.

**Comment by garfield69** [comment]
what platform is this? looks like windows xp?

**Comment by twiz-ahk** [comment]
It's Windows 10 (x64 if it matters).
It looks a bit similar to to Windows 8/8.1, but [Windows XP](http://winsupersite.com/content/content/128001/showcase/xp_n_04.jpg) looks considerably older and has round corners on just about everything.

**Comment by garfield69** [comment]
And I take it that the window stays open and you have to close it manually?

**Comment by twiz-ahk** [comment]
Correct.
If I'm not mistaken, it belongs to "JackettTray.exe". I noticed I don't have the process running, and tray icon isn't showing either, so it might have closed when I closed the window.
Jackett seems to be running fine, just no tray icon.

**Comment by garfield69** [comment]
Yes, so you will have installed Jackett in Server mode then...     
The tray just provides a menu to do a few commands, such as access the web ui, stop the server, etc.     
I don't use myself, I bookmarked the Jackett Dashboard url on my Browser, since I use that the most.      
But as a point of difference, I just started the tray up, and I don't see a window. But I'm on win7, so apples and oranges.     
I'll nosy around the code a bit and see if I spot something obvious.

**Comment by PapaMichael** [comment]
For me the window doesn't visibly appear until I alt+tab to it, for what that's worth.

**Comment by garfield69** [comment]
@PapaMichael  and what platform are you on?

**Comment by PapaMichael** [comment]
Windows 10 just like him, sorry

**Comment by flightlevel** [comment]
Made a change to prevent it appearing in ALT + TAB, will go out with the next release
Let us know if it doesn't fix the issue

**Comment by flightlevel** [comment]
Now released
