### ISSUE TITLE
[gktorrent] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by alex7614** [Jackett/Jackett#1995]
IWebClient: Returning MovedPermanently => http://www.nextorrent.tv/recherche/ <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="http://www.nextorrent.tv/recherche/">here</a>.</p>
</body></html>

Jackett version:  Last

-------------------------------

**Comment by garfield69** [comment]
Curious, because I can access gktorrent at `http://www.gktorrent.com/` just now.
I see that their WhoIs domain record was updated yesterday so its possible there was a conflict.
Access your Jackett Console, click on the wrench icon for gktorrent and check that your SiteLink is  `http://www.gktorrent.com/`. Overwrite it if it is not. Perform you test again and see if it works for you now.
