### ISSUE TITLE
BTDB returns only a fraction of the results

### ISSUE THREAD

**Issue by TomArrow** [Jackett/Jackett#1999]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  0.8.277.0
Mono version (if not using Windows):  

-------------------------------

When I only use BTDB for a search, I get only a fraction of the results I should be getting. For example searching "blue ruin 2013" on btdb.to gives a lot of results, but doing the same in Jackett gives mixed success. When used in combination with other engines, it displayed 10 results (the number in the brackets). Searching only on BTDB I got actually zero results.

BTDB has a lot of results typically. I am not sure if Jackett is only grabbing the first result page, but if so, that is not really enough because of the vast amount of stuff on btdb.

**Comment by garfield69** [comment]
AFAIK, (and @kaso17  can correct me if I am wrong), this is a limitation caused by the fact that BTDB only displays the first 10 results on its page, (with navigation buttons which the user can use to fetch additional pages), and the inability of the current implementation of the Cardigann definition to be able to request additional pages after the first one has been delivered.
If this is the case, I don't think there is much we can do, other than perhaps replacing the definition with one written in c#, which I presume, could do further requests.

**Comment by kaso17** [comment]
yes, most trackers (including BTDB only get the results from the first page), see #975
