### ISSUE TITLE
[REQ] New Indexer: Torrentkim

### ISSUE THREAD

**Issue by jfgoncalves** [Jackett/Jackett#2017]
Tracker Name : Torrentkim
Type : Movie, TV, Music, Anime, Games, Software, Other
Public tracker.
Has torrent files and magnet links
Indexer URL : https://torrentkim10.net
Indexer language : Korean

Hosts pretty much everything Korean.

**Comment by kaso17** [comment]
If you know a little HTML/CSS you can try to add it yourself.
See https://github.com/Jackett/Jackett/wiki/Definition-format for details.
If you've any questions feel free to ask.

If the tracker already provides some kind of API (e.g. gazelle based trackers) please let us know. Then the Cardigann definition approach might be not not the best solution

**Comment by Growiel** [comment]
I just want to voice my support for Torrentkim, and point that it now runs from https://torrentkim12.com/ (the old one being redirected there).

**Comment by Growiel** [comment]
So I just went ahead and did it:  #2620.

This site is pretty awful, most of the search list differs from one another and the best list is hidden, using the search bar on top only returns google results that are un-usable.

Still, it should be working pretty great for a first release.

Please note:

1: The site does not provide a correctly formatted list for "newest" releases and when you make an empty search, you are redirected to the google search page. As such, when doing the "test" from Jackett's webUI, we will be searching for 미운우리새끼 because I know for a fact that results are available.

2: For the seeds / peers, I'm not 100% sure what the first number is and what the second is since I wasn't able to find a torrent with enough activity to confirm. I went with my guts feeling. Might need to be updated later on.

3: My ONLY goal with this tracker is to download the show 미운우리새끼 so that's pretty much all I tested so I'm only releasing it with the variety shows, dramas and american series categories enabled.
Adding the other ones shouldn't be too hard if needed.

Extra note: If you want to use this tracker with Sonarr through Jackett, an additional intermediate script is required because Sonarr is extremely limited in its Korean handling.
This is not the Sonarr github so I won't elaborate more, feel free to contact me.
