### ISSUE TITLE
[REQ] Create a LazyLibrarian Host

### ISSUE THREAD

**Issue by raspdealer** [Jackett/Jackett#21]
@philborman is working on LazyLibrarian https://github.com/DobyTang/LazyLibrarian.git
and would like to add support for using Jackett/torznab as a search option. Is there any documentation on your api? The jackett server has a page that searches all the configured providers in one call, which would be cool to integrate.

**Comment by raspdealer** [comment]
You should look at this https://github.com/RuudBurger/CouchPotatoServer/wiki/CouchPotato-Torrent-Provider
to understand one couchpotato has to receive the feed from Jackett to be able to understand it.

I guess that if your app can understand the same format, you could use the CouchPotato format.
Otherwise, you have to give the format you need and some have to create the interface (a new host)

**Comment by WhatFox** [comment]
Couchpotato its for movies only so that'll not get you too far,  Torznab is what you want and the spec is here: https://github.com/Sonarr/Sonarr/wiki/Implementing-a-Torznab-indexer

Given the project is based on headphones which already supports Jackett/Torznab I suggest you just pull those changes @philborman.
