### ISSUE TITLE
[zooqle] Exception (zooqle): Object reference not set to an instance of an object.: An error occurred while sending the request (Test)

### ISSUE THREAD

**Issue by chatainsim** [Jackett/Jackett#2133]
Almost all tracker failed.
Jackett version:  0.8.409.0
Mono version (if not using Windows):  Mono JIT compiler version 5.4.0.201

-------------------------------

**Comment by chatainsim** [comment]
[log.txt.tar.gz](https://github.com/Jackett/Jackett/files/1465202/log.txt.tar.gz)

**Comment by kaso17** [comment]
System.Net.Http.HttpRequestException: An error occurred while sending the request ---> System.Net.WebException: Error: TrustFailure (Object reference not set to an instance of an object.) 

This is often caused by missing CA certificates.
Try reimporting the certificates:
   - On Linux (as user root): `wget -O - https://curl.haxx.se/ca/cacert.pem | cert-sync /dev/stdin`
   - On macOS: `curl -sS https://curl.haxx.se/ca/cacert.pem | cert-sync --user /dev/stdin`

**Comment by chatainsim** [comment]
Thanks, that's solved my issue.
