### ISSUE TITLE
Public Trackers are not bad

### ISSUE THREAD

**Issue by PartTimeLegend** [Jackett/Jackett#215]
Downloading torrents is not illegal, downloading illegal content is. However this is down to the individual to decide how they act. As developers of tools we can only act in good faith that they will not be abused.

As it is clear there is a wish for there to be public trackers, and the maintainers of Jackett do not currently wish to manage this. I have proposed a fork called [Coatt](https://github.com/Coatt/Coatt) (did you see what I did there?

If you want public trackers, we will accept all working trackers regardless of how they operate.

In addition to this whilst Jackett has concentrated on video sources, Coatt is willing to take on other trackers such as what.cd if they ever enable the API again.

This is not an affront to the Jackett team, just a derivative work in the FOSS world to give the users what they want.

**Comment by duramato** [comment]
@PartTimeLegend Plans on opening the issue tracker on your repo?

**Comment by PartTimeLegend** [comment]
@duramato *facepalm.jpeg* opened up now.

**Comment by Azerelat** [comment]
Yes its up to users what they do with the application, it could be use for rights holders to monitor their content but the problem is some people may use it for illegal files.  Public trackers tend to host such files and in a way that is highly monitored and likely to get the user in trouble and it would be irresponsible of us to support such activity.  

Feel free as per he licence to fork but @raspdealer has already done what you are proposing.   If you do continue with your own then please try to use different directories so the apps don't conflict as is done in that fork. The download stats on there show there really isn't any interest in public trackers from users too.
