### ISSUE TITLE
Unable to search indexers

### ISSUE THREAD

**Issue by rossdargan** [Jackett/Jackett#2161]
I keep getting this error on jackett (running on Ubuntu 14)

Could not load file or assembly 'SocksWebProxy, Version=1.0.5.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.

Mono version: Mono JIT compiler version 5.4.0.201

To fix the issue I download an really extract the files, bounce the box and everything works for about 24 hours.

I have updated disabled as I assumed maybe that was breaking it.

I'm at a bit of a loss as to what could be causing this issue and suspect it's probably not the app but thought I'd see if anyone else was having the issue.

**Comment by drewbitt** [comment]
Do you have a SocksWebProxy.dll in your main Jackett folder? That error is usually from the dll not existing

**Comment by rossdargan** [comment]
The file is missing, but my issue is more why. I can replace it and jackett will work fine for 24 hours then it goes missing again

**Comment by kaso17** [comment]
The jackett update service runs every 24 hours, but even if it would run (which is not the case as you disabled automatic updates) it shouldn't delete files...
What happens if you run a manual update check (click in "Check for Updates" in the jackett UI)? Does it result in a broken jackett with deleted file?
If not I suspect it's something else on your system deleting the file (some fancy security scanner)?

**Comment by garfield69** [comment]
It's been nearly a month since the last reply, I'm closing this one.
