### ISSUE TITLE
[bt-scene] Exception (bt-scene): Method 'Array.Empty' not found.: The type initializer for 'Microsoft.CSharp.RuntimeBinder.Semantics.BSYMMGR' threw an exception. (Test)

### ISSUE THREAD

**Issue by nijode999** [Jackett/Jackett#2189]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:   0.8.450.0
Mono version (if not using Windows):  5.4.1.6

-------------------------------

**Comment by garfield69** [comment]
I don't have any trouble using bt-scene from my win7 Jackett Dashboard. What platform are you using?     
Please provide the full enhanced log file. You will find the instructions for enabling enhanced logging and the locations of the log file at https://github.com/Jackett/Jackett#troubleshooting.

**Comment by garfield69** [comment]
Also, are you using one of the pre-assembled Jackett packages from this GitHub, or are you compiling your own from source?    
Because the most common reason for this type of error is when an old library is being used, which might occur for example, if mono was upgraded from 4.6 to 5.4 but paths to 4.6 still exist, or references to 4.6 libraries were still active.

**Comment by garfield69** [comment]
nearly two months and no reply. Closing.
