### ISSUE TITLE
[yggtorrent] An error occurred while sending the request: Error: TrustFailure (Object reference not set to an instance of an object.) (Config)

### ISSUE THREAD

**Issue by Psychoteur** [Jackett/Jackett#2194]
Jackett version:  0.8.450.0
Mono version (if not using Windows):  

Mono JIT compiler version 5.4.1.6 (tarball Wed Nov  8 21:23:55 UTC 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       normal
	Notifications: epoll
	Architecture:  armel,vfp+hard
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen (concurrent by default)
-------------------------------
Hello,
I'm trying to add yggtorrent inside jackett but I always got the following error:

`An error occurred while sending the request: Error: TrustFailure (Object reference not set to an instance of an object.)`

Thanks.

[log.20171126.00000.txt](https://github.com/Jackett/Jackett/files/1503888/log.20171126.00000.txt)

**Comment by garfield69** [comment]
This is often caused by missing/outdated CA certificates.
  Try reimporting the certificates in this case:
   - On Linux (as user root): `wget -O - https://curl.haxx.se/ca/cacert.pem | cert-sync /dev/stdin`
    or `sudo wget -O - https://curl.haxx.se/ca/cacert.pem | sudo cert-sync /dev/stdin`
   - On macOS: `curl -sS https://curl.haxx.se/ca/cacert.pem | cert-sync --user /dev/stdin`
  - On QNAP refer to #2111

and reboot (or just restart all Jackett services) after the imports are completed.

**Comment by Psychoteur** [comment]
Hello,
I don't know what happened but I did it before I posted the issue.
So I did it again and now it works.
Thanks.
