### ISSUE TITLE
[danishbits] Exception (danishbits): Dine API settings er ikke korrekte!: Dine API settings er ikke korrekte! (Test)

### ISSUE THREAD

**Issue by and992** [Jackett/Jackett#2272]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  
Mono version (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
Please provide the full enhanced log file. You will find the instructions for enabling enhanced logging and the locations of the log file at https://github.com/Jackett/Jackett#troubleshooting.

**Comment by garfield69** [comment]
previous similar tickets show that the most common reason for this error is that you are using your login password instead of the passkey.     
Note about Passkey: This is not your login Password. Find the Passkey by logging into DanishBits with your Browser, and under your account page you'll see your passkey under the 'Personal' section on the left side.

**Comment by and992** [comment]
Hey
They have change there API to https://danishbits.org/couchpotato.php?user=****&passkey=****&search=“The_search”

Max 250 hit Per Day for normal users og 1000 for vip

**Comment by and992** [comment]
Hmm. I can’t get it manuel to work. I Will return, then i get it work

**Comment by garfield69** [comment]
are you on the latest Jackett v0.8.500 ?      
upgrade and then check on your jackett dashboard with the wrench icon that your danishbits sitelink is using **https** and **not** http.

**Comment by and992** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/1553077/log.txt)
yes and yes :)

**Comment by garfield69** [comment]
what were you searching for in that test? the url used was `https://danishbits.org/couchpotato.php?search=%25&passkey=**redacted**&user=**redacted**` ?

**Comment by and992** [comment]
The new RSS link

https://danishbits.org/rss.php?id=0&auth=“a number i dont know why”&passkey=“mypasskey”&authkey=“mykey”

**Comment by garfield69** [comment]
was that the result of using the *test* button on the jackett dashboard?

**Comment by and992** [comment]
Yes

**Comment by garfield69** [comment]
thanks. I'll pass this one onto @kaso17  to take a look.

**Comment by and992** [comment]
I have look a the forum.
Only “Medusa” work with the new API :’(

I try i look for a solution

**Comment by and992** [comment]
If you can Danish: https://danishbits.org/forums.php?action=viewthread&threadid=32768

**Comment by kaso17** [comment]
@and992 DB works fine for me (with the limitations of the new API).
What happens if you open the link from the log in your browser?
 `https://danishbits.org/couchpotato.php?search=%25&passkey=**redacted**&user=**redacted**` 

So far this error was triggered 100% of the time by users having used their passwords instead of their passkey or had some extra white spaces in the passkey.

**Comment by and992** [comment]
It say wrong API setting.
Ty for your time. It works now. My jackett version was updated on the admin page. But then i look at the files. It was still the old. It help to delete the service and database and make a clean install.

Ty for your time
