### ISSUE TITLE
[zamundanet] Login Failed, got redirected (Config)

### ISSUE THREAD

**Issue by pehota** [Jackett/Jackett#2393]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  
Mono version (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
can you access the site directly from your browser?
I get redirected to a blockchain site:
![image](https://user-images.githubusercontent.com/6933240/34752773-373927d8-f619-11e7-8e7a-08f65f588e91.png)
but than might be because my ip address is not bulgarian according to https://opentrackers.org/zamunda/
If you can access the site from your Browser, then try again from Jackett, but first, please provide the full enhanced log file. You will find the instructions for enabling enhanced logging and the locations of the log file at https://github.com/Jackett/Jackett#troubleshooting.
Remember to redact any personal details first, usernames, passwords, passkeys, hashes etc.

**Comment by pehota** [comment]
Hi, 
```
WebClient(HttpWebClient): Returning Redirect => http://foreign.zamunda.net/ <html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx/1.8.1</center>
</body>
</html>
```
I guess I will need a Bulgarian proxy or VPN in order to access the site. Is there a possibility of adding a proxy to Jacket?
Thanks

**Comment by kaso17** [comment]
yes, proxies are supported, see command line options/GUI options
