### ISSUE TITLE
[Bug] Jackett keeps crashing

### ISSUE THREAD

**Issue by zero77** [Jackett/Jackett#2455]
Jackett keeps randomly crashing where the process is still running but unresponsive by api or web-ui. After killing the process, it restarts and works ok again, although the logs in the web-ui seems to have been reset at that point.

**Comment by kaso17** [comment]
~/.config/Jackett
How often is this happening?
Does the integrated jackett updating mechanism work?

**Comment by kaso17** [comment]
Just released v0.8.618, please try "check for updates" and see if it "crashes".

**Comment by zero77** [comment]
That worked fine I am now running v0.8.618

**Comment by zero77** [comment]
Log of before i restarted Jackett
https://pastebin.com/2EpSV6TP

**Comment by zero77** [comment]
It seems to be getting more frequent, as now its at least twice a day.

**Comment by alxlaxv** [comment]
@zero77 did you tried with the last version?

**Comment by zero77** [comment]
Yes, it is happening less regularly now but it still sometimes happens.

**Comment by lincalinca** [comment]
Has this issue been resolved? I had radarr running really smoothly at first, then it would crash about once every couple of days, now it won't run for more than a minute or two.

**Comment by flightlevel** [comment]
@lincalinca 

- Stop the Jackett service
- Close the Jackett tray
- Kill every Jackett process 
- From Windows Add/Remove programs Uninstall Jackett (you won't lose your trackers)
- Go to `C:\ProgramData\Jackett` and make sure there is no exe or dll files present, only config and log files should remain after uninstalling
- Download the latest Jackett release and install via the Windows installer

If the issue is still occurring after that, please post the log.txt (enhanced version)

In future, create a new issue when your problem is different, you're running Windows not Mono
