### ISSUE TITLE
[1337x] Exception (1337x): The handshake failed due to an unexpected packet format.: An error occurred while sending the request. (Test)

### ISSUE THREAD

**Issue by TTLucian** [Jackett/Jackett#2489]
Error on testing https://1337x.to. It seems it doesn't work

**Comment by garfield69** [comment]
I have no problems testing the 1337x indexer on my win7 platform Jackett Dashboard.
if you are not on windows then:
This is often caused by missing/outdated CA certificates.
  Try reimporting the certificates in this case:
   - On Linux (as user root): `wget -O - https://curl.haxx.se/ca/cacert.pem | cert-sync /dev/stdin`
    or `sudo wget -O - https://curl.haxx.se/ca/cacert.pem | sudo cert-sync /dev/stdin`
   - On macOS: `curl -sS https://curl.haxx.se/ca/cacert.pem | cert-sync --user /dev/stdin`
  - On QNAP refer to #2111

and reboot (or just restart all Jackett services) after the imports are completed.

**Comment by TTLucian** [comment]
Nevermind. MalwareBytes blocks access to 1337x.to. Added an exclusion and now it works fine.
