### ISSUE TITLE
Jackett as a library

### ISSUE THREAD

**Issue by hoshsadiq** [Jackett/Jackett#2588]
This app seems great! I wonder what would be the best way to use it as a library? I presume there would need to be a port. What would be the core that is needed to be ported if I wanted to use this as a library in either Python or Go?

Any pointers would be appreciated.

**Comment by kaso17** [comment]
Jackett is written in C#, so using it as native library in go or python is probably very difficult.
I believe it's best to keep jackett running as standalone/separate process. Due to the high update rate bundling it with a more stable software makes little sense to me. Your application can just use the torznab API provided by jackett (independent of the programming language).

**Comment by flightlevel** [comment]
If you wanted to port to Go, I'd start with looking at https://github.com/cardigann/cardigann
But as @kaso17 says its a massive job
No work for Jackett here, so closing
