### ISSUE TITLE
[yggtorrent] An error occurred while sending the request: Error: TrustFailure (One or more errors occurred.) (Config)

### ISSUE THREAD

**Issue by Wells83** [Jackett/Jackett#2596]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
This is often caused by missing/outdated CA certificates.
  Try reimporting the certificates in this case:
   - On Linux (as user root): `wget -O - https://curl.haxx.se/ca/cacert.pem | cert-sync /dev/stdin`
    or `sudo wget -O - https://curl.haxx.se/ca/cacert.pem | sudo cert-sync /dev/stdin`
   - On macOS: `curl -sS https://curl.haxx.se/ca/cacert.pem | cert-sync --user /dev/stdin`
  - On QNAP refer to #2111

and reboot (or just restart all Jackett services) after the imports are completed.

**Comment by Cosa67** [comment]
Hi all,

I get the same issue when I try to configure Jackett on my Synology DS413j with Yggtorrent tracker. The problem is that I'm a noob and really don't know how to try the commands above.

I've noticed that when I try to add the tracker, the Yggtorrent default URL used by Jackett is https://ww1.yggtorrent.com/ but the current URL is https://yggtorrent.com/ 
Could it be a reason of my error message ?

**Comment by kaso17** [comment]
@Cosa67 make sure you're running the latest jackett version (check the footer of the jackett page, ignore the version from the package center).
That should update the URL and might solve your issue.
Are other https indexers working?

**Comment by Cosa67** [comment]
@kaso17 You're right, the version downloaded (and running) from Package Center is 0.8.490.0 but how can I install the last release ? (I can't test with other https indexers, my only torrent account is on YggTorrent)
