### ISSUE TITLE
[yggtorrent] Login Failed, got redirected (Config)

### ISSUE THREAD

**Issue by falkin** [Jackett/Jackett#2638]
yggtorrent doesn't seems working on synology. 

**Jackett version**:   0.8.490.0
**Mono version** (if not using Windows):  5.8.0.108-11

-------------------------------

**Comment by garfield69** [comment]
Upgrade to the latest Jackett, currently v0.8.716.
There have been updates to the yggtorrent definition since 0.8.490 came out.

**Comment by pbertra** [comment]
I am on v0.8.716: Exception (yggtorrent): Login failed: Selector

Still not working

**Comment by garfield69** [comment]
@pbertra the `Login failed: Selector` message is usually due to your password having been expired by yggtorrent, which they did to all uses a while back for security.
So login to yggtorrent directly through your browser and check if you are required to change your password. Then update your jackett yggtorrent definition.
Also make sure you are not using your email address as a username, as yggtorrent changed this requirement a while ago as well.

**Comment by pbertra** [comment]
Deleting the indexer and re-adding it solved the issue, though my login and password were still correct... Anyway, issue solved.

**Comment by falkin** [comment]
Yes it's works with last version thx 👍

**Comment by akpdionne** [comment]
I did try to delete and recreate. Filled my user and PW (i did test them on the yggtorrent.is site and i do login perfectly.
Try with the same values in jackett give me and error

**Comment by garfield69** [comment]
@akpdionne  yggtorrent upgraded their site a few days ago. The next (pre)release of Jackett (whenever that gets released) will contain a fix for the new site layout.
