### ISSUE TITLE
[xthor] Exception (xthor): Object reference not set to an instance of an object: Object reference not set to an instance of an object (Test)

### ISSUE THREAD

**Issue by alxlaxv** [Jackett/Jackett#2649]
Hello,

Error with the last version in date.
No significant error in the logs

Thanks for help

```



Feb 28, 2018 07:59:58 PM | Error | {0}
-- | -- | --
Feb 28, 2018 07:59:58 PM | Info | ApiExceptionHandler ExecuteExceptionFilterAsync
Feb 28, 2018 07:59:58 PM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync
Feb 28, 2018 07:59:58 PM | Info | JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Test()'
Feb 28, 2018 07:59:58 PM | Info | RequiresIndexerAttribute OnActionExecutedAsync
Feb 28, 2018 07:59:58 PM | Info | RequiresIndexerAttribute OnActionExecutedAsync Action filter for 'Test()'
Feb 28, 2018 07:59:58 PM | Error | ApiControllerActionInvoker InvokeActionAsync
Feb 28, 2018 07:59:58 PM | Error | ReflectedHttpActionDescriptor ExecuteAsync


```

**Comment by garfield69** [comment]
This is often caused by missing/outdated CA certificates.
  Try reimporting the certificates in this case:
   - On Linux (as user root): `wget -O - https://curl.haxx.se/ca/cacert.pem | cert-sync /dev/stdin`
    or `sudo wget -O - https://curl.haxx.se/ca/cacert.pem | sudo cert-sync /dev/stdin`
   - On macOS: `curl -sS https://curl.haxx.se/ca/cacert.pem | cert-sync --user /dev/stdin`
  - On QNAP refer to #2111

and reboot (or just restart all Jackett services) after the imports are completed.

**Comment by kaso17** [comment]
it's unlineky an TLS error.
Please provide the full log file from the file system (not via the jackett gui) with enhanced logging enabled

**Comment by alxlaxv** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/1770171/log.txt)

**Comment by alxlaxv** [comment]
Resaving settings solved it... Weird.
