### ISSUE TITLE
[nexttorrent] Exception (nexttorrent): Got redirected to another domain. Try changing the indexer URL to http://www.nextorrent.site/.: Parse error (Test)

### ISSUE THREAD

**Issue by phenixzr** [Jackett/Jackett#2742]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
Fixed by b1a93612214b3f92a102dcb9412f03ad4d957d7a which will be included in the next (pre)release of Jackett whenever that gets published.
In the mean time you can fix this for yourself by using the wrench icon on your Jackett Dashboard to edit the nextorrent indexer's site link to `http://www.nextorrent.site/`
