### ISSUE TITLE
[torrentday] Your cookie did not work: Your cookie did not work (Config)

### ISSUE THREAD

**Issue by GazzaHazza** [Jackett/Jackett#3032]
My cookie isnt working since torrentday changed from torrentday.it -> torrentday.com ... I think it might be down to my ISP blocking torrentday.com, is there a way to set it back to torrentday.it?

**Jackett version**:  0.8.490.0
**Mono version** (if not using Windows):  5.17.1-8

-------------------------------

**Comment by maZuFC** [comment]
i have the same issue...

cant do a test to torrentday.

error log shows the following.

Apr 27, 2018 11:07:28 AM | Error | On attempt 1 checking for results from TorrentDay: An error occurred while sending the request.
-- | -- | --
Apr 27, 2018 11:07:18 AM | Error | System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 104.27.210.30:443    at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)    at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)    --- End of inner exception stack trace ---    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)    at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)    --- End of inner exception stack trace ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at CloudFlareUtilities.ClearanceHandler.<SendAsync>d__20.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)    at Jackett.Common.Utils.Clients.HttpWebClient.<Run>d__7.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)    at Jackett.Common.Utils.Clients.WebClient.<GetString>d__18.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Jackett.Common.Indexers.BaseWebIndexer.<RequestStringWithCookies>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Jackett.Common.Indexers.TorrentDay.<GetConfigurationForSetup>d__18.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Jackett.Controllers.IndexerApiController.<Config>d__9.MoveNext() in C:\projects\jackett\src\Jackett\Controllers\IndexerApiController.cs:line 76 --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__1`1.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__17`1.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__17`1.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()



i cannot browse to .com
but .it still works ok.


im also not able to configure my torrentday indexer... it does not open when clicking on the configure button.

**Comment by kaso17** [comment]
with v0.8.928 .it is the default again, you probably have to re-add the indexer

**Comment by seanvree** [comment]
I still can't re-add TorrentDay:

```
Your cookie did not work: Got a redirect to https://torrentday.it/t.json?29;28;42;20;30;47;43;25;11;5;3;21;22;13;44;48;1;17;23;41;16;27;45;4;18;8;10;9;24;32;31;33;46;14;26;7;34;2;6;15;q=, please adjust your the alternative link

```

**Comment by maZuFC** [comment]
same here.. i cant even modify the existing torrentday settings

**Comment by maZuFC** [comment]
ok fixed it.

removing torrentday and readdding it resolved the issue.
but i did have to get new cookie details.

once i did that test worked and sonarr and radarr both working again.

thanks!

**Comment by Quiksmage** [comment]
hmm, I still can't get it working maZuFC

I haven't had any issues with my cookie in a while, but can you confirm that your cookie looks like the following?

__cfduid=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; PHPSESSID=xxxxxxxxxxxxxxxxxxxxxxxxxx; uid=xxxxxxx; pass=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

**Comment by maZuFC** [comment]
my cookie info in jackett looks like this

__cfduid=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; PHPSESSID=xxxxxxxxxxxxxxxxxxxxxxxxxxxxx;

i do not have the uid part.
but... when looking at the cookie details in chrome i see the following

cookie: uid=xxxxxx; pass=xxxxxxxxxxxxxxxxxxxxxxxxxxx; __cfduid=xxxxxxxxxxxxxxxxxxxxxxxxxxx


so i copied everything from UID straight into jackett
to clarify i copied the following

uid=xxxxxx; pass=xxxxxxxxxxxxxxxxxxxxxxxxxxx; __cfduid=xxxxxxxxxxxxxxxxxxxxxxxxxxx

once copied, saved the details and tested.. confirmed ok.

hope that helps
