### ISSUE TITLE
Episode torrents with AnimeBytes show as Unknown Series in Sonarr

### ISSUE THREAD

**Issue by totallyfake** [Jackett/Jackett#3039]
I just installed Jackett and have been trying to get downloads working with animebytes but all individual episode torrents are showing as Unknown Series. This causes Sonarr to reject the torrent, rendering the indexer essentially useless. I saw that the API was updated very recently and read through the discussion in a now-closed issue so I suspect it may be a new bug in that. BTN and PTP work fine for me so it is definitely an AnimeBytes specific issue.

Using Jackett 0.8.929.0 with Mono 5.10.1.47 on Ubuntu Server 16.04 LTS

**Comment by darthShadow** [comment]
Working perfectly fine for me.

* Any particular series?
* Was it working with the earlier implementation?

**Comment by darthShadow** [comment]
This is not an issue in jackett. Jackett only provides the episodes and it's up to Sonarr to recognize it correctly.

My Hero Academia S3 needed a thexem mapping because of which it failed to recognize it. I requested it to be added yesterday and its working fine now. Can you try the following steps:

* Go to System -> Tasks -> Update Scene Mapping.
* Refresh Series Info.

This should fix your issue. Probably something similar needs to be done for Steins Gate. Can you share a screenshot after performing a manual search for any episode in Steins Gate? I will ask the devs to add the required mapping.

**Comment by totallyfake** [comment]
Thanks, that appears to be working now. Just my luck both shows had the same issue. Where is this mapping added? Is it done by the tracker, sonarr, or jackett? Forgive me if it seems dumb, I'm very new to all this software (except the tracker part). I've attached a screenshot of the steins;gate 0 manual search.

![screenshot-2018-4-29 steins gate 0 - sonarr](https://user-images.githubusercontent.com/1245424/39411044-d84cb10e-4bc7-11e8-8864-dfa42f1514e0.png)

**Comment by darthShadow** [comment]
Don't have BTN, so can't comment on its Anime retention & variety. I am not sure myself why "Steins;Gate 0" is not matching. It should have been able to parse it correctly based on the name. You can try the sonarr subreddit for help.

**Comment by kaso17** [comment]
I assume this has been identified as "not a jackett issue", closing
