### ISSUE TITLE
[animebytes] Parse error: missing username param (Config)

### ISSUE THREAD

**Issue by TimIsOverpowered** [Jackett/Jackett#3071]
Getting "System.Exception: Parse error ---> System.Exception: missing username param" for animebytes

The animebytes api requires the username parameter (case sensitive) along with passkey as well.

Jackett version: Jackett Version 0.8.929
Mono version: Mono JIT compiler version 5.10.1.47

**Comment by MrTimscampi** [comment]
Getting the same error here.

**Comment by flightlevel** [comment]
@TimIsOverpowered  @MrTimscampi 
This is because AnimeBytes now require a username as per https://github.com/Jackett/Jackett/issues/3008#issuecomment-386653227

I've added username but am not a member to test it. Can you try custom build from here https://ci.appveyor.com/project/Jackett/jackett/build/0.8.951/artifacts and see if that fixes it. If it works, it can be added to the regular release

**Comment by corey88** [comment]
Just tested the build and confirm it is working with animebytes.

It was a short test but manual search and a search with radarr worked perfectly fine

**Comment by flightlevel** [comment]
Thanks @corey88 
Fixed in latest release https://github.com/Jackett/Jackett/releases/tag/v0.8.953

**Comment by TimIsOverpowered** [comment]
@flightlevel can you say that its case sensitive otherwise it would send out a "user not found" error
