### ISSUE TITLE
[speedcd] Exception (speedcd):         Speed.cd        .checkBox{color:

### ISSUE THREAD

**Issue by thekogut** [Jackett/Jackett#3140]
Speed.CD asking for verification...

-------------------------------

Exception (speedcd): Speed.cd .checkBox{color:#000;margin:80px auto;text-align:left;width:650px}.checkBox .boxContent{min-height:541px}#logintab .loginWarp{display:inline-block;padding:10px 50px}.uInfo{padding:15px} Javascript is disabled or is not supported by your browser. Please upgrade your browser or enable Javascript to navigate the interface properly. Not Kogut? Identify Your Account Log in as: Kogut We could not recognize your account properly. Mind if we double check that? It's for your own security. Security Question Question: What's Shan's dog's name? Secret Answer:   Password:   Continue Request a login token by Email Email me a link to reset my IP lock settings. t******t@gmail.com Type the full email Address:   Continue Login: Speed.cd .checkBox{color:#000;margin:80px auto;text-align:left;width:650px}.checkBox .boxContent{min-height:541px}#logintab .loginWarp{display:inline-block;padding:10px 50px}.uInfo{padding:15px} Javascript is disabled or is not supported by your browser. Please upgrade your browser or enable Javascript to navigate the interface properly. Not ####? Identify Your Account Log in as: ##### We could not recognize your account properly. Mind if we double check that? It's for your own security. Security Question Question: ##########? Secret Answer:   Password:   Continue Request a login token by Email Email me a link to reset my IP lock settings. #******#@gmail.com Type the full email Address:   Continue Login

**Comment by Rycore** [comment]
I had the same problem, turns out that if you're logged in on another system and then test speed, jackett fails to login with that error. My server and home system share the same ip, the only thing I did that fixed this for me was log out of speedCD from my home computer then try to login again through jackett.

So if you're having this isue either you or someone else might be logged in to the website while jackett is trying to gain access, try changing your password [speed.cd/checkout](https://speed.cd/checkpoint/), logout and then try to login via jackett.
