### ISSUE TITLE
Bad logo resolutions

### ISSUE THREAD

**Issue by zone117x** [Jackett/Jackett#324]
This is a pretty minor nitpick but its bothering me. The tracker logos are being stretched past their original resolution and appear really low quality. I like the new design of the logos covering the whole tile with rounded corners but either the tiles need downsized or all the tracker logos need updated. 

PS: This is the first time I've used Jackett since a couple months before this fork, and I'm super impressed by how well you guys have been maintaining the project. It worked flawlessly when I added several of my old trackers. Keep up the good work!

btw I just searched reddit for Jackett and found this recent thread and thought you'd all be interested: https://www.reddit.com/r/sonarr/comments/4eddob/shoutout_to_the_jackett_team_for_being_1_year/

**Comment by JigSawFr** [comment]
Hello @zone117x ! Nice to see you here again !
We know that logos are in a bad resolution, that's why a new resolution must be provided with provider PR (see #319 for example).
I think a new PR to replace them all could be great.

As i can say, we are working on a new major version of Jackett that is working without mono on all plateforms (core .net) and with some new technologies for front end and parsing. :gift: 

Thanks from all members of Jackett Team.

**Comment by flightlevel** [comment]
Latest version no longer contains logos

**Comment by exikyut** [comment]
FWIW, the logos are still being rendered in the XML - https://github.com/Jackett/Jackett/blob/69125add3e6c8c686c318629b65eecad8875494c/src/Jackett.Server/Controllers/ResultsController.cs#L407

Figured you'd want to know. (Was fiddling around making a small context-specific dashboard thingy and was like "oh cool, logo images!", heh)

**Comment by ilike2burnthing** [comment]
@ngosang something niggly to remove?

**Comment by ngosang** [comment]
Fixed in #10837

**Comment by ilike2burnthing** [comment]
[v0.17.311](https://github.com/Jackett/Jackett/releases/tag/v0.17.311)

**Comment by exikyut** [comment]
Wow, that was a quick fix :) cool
