### ISSUE TITLE
Search Missing Valid Results

### ISSUE THREAD

**Issue by georgeurbane** [Jackett/Jackett#326]
Doing a search for RuPauls Drag Race S08E08 returns 0 results:
![screenshot 2016-04-30 15 28 00](https://cloud.githubusercontent.com/assets/17436505/14938214/69f0d698-0eea-11e6-83f0-e929cf149129.png)
Doing a search for Drag Race S08E08 returns 1 correct result:
![screenshot 2016-04-30 15 27 42](https://cloud.githubusercontent.com/assets/17436505/14938215/69f1689c-0eea-11e6-9c1a-38f821515fdd.png)

Presumably, the result shown should also match for the above search (which is what Sonarr searches for).

**Comment by flightlevel** [comment]
Jackett simply returns the information supplied by your provider.
eg. go to TTN website and search for `RuPauls Drag Race S08E08` and no results will be found, that is exactly what Jackett is returning, its not losing any valid results.
The second search works because there is an apostrophe is RuPaul's

If this is a regular scene name for the show, you could look at https://github.com/Sonarr/Sonarr/wiki/FAQ#why-cant-sonarr-import-episode-files-for-series-x--why-cant-sonarr-find-releases-for-series-x otherwise its just a badly named release
