### ISSUE TITLE
automatically disable index site if automated run of test fails.

### ISSUE THREAD

**Issue by binhex** [Jackett/Jackett#3292]
Hi so im making use of the aggregated 'all' feature for jackett, and for the most part it works well. However if one or more enabled index sites stop responding, or go offline then this can cause a long delay before the index site times out and moves onto the next index site in the list, this then results in the metadata downloader timing out for the jackett 'all' feed resulting in no matches. 

The user would then need to login to jackett, click on the test all button to confirm which index sites are now down, and delete them (would love a  disable option) in order to get things working again, and of course if the index site ever came back online the user would then need to re-add the index site.

What i propose is a automated run of tests for enabled index sites, you set the period of say 4 hours and jackett automatically does a background test of all enabled index sites, if any index site is found to be unresponsive then its disabled, if on the next test period it becomes responsive again then it's re-enabled, thus ensuring the 'all' aggregated feed carries on working during index site outages.

**EDIT 2021/05/10**
So with the addition of 'tags' for indexers ( thanks @ilike2burnthing ) the issue of timeout on feeds due to use of the 'all' feed has been reduced but not completely removed. 

I still feel there is merit in Jackett automatically testing and (on failure) disabling indexers to prevent timeouts on the metadata downloader, it would also help the user identify badly behaving indexers (disabled) and possibly help in removing the unstable index sites. @ilike2burnthing do you think this feature would be relatively simple to implement, and do you have the time to look at it?.

**Comment by kaso17** [comment]
For this and other reasons it's not recommended to use the all feed.

A disabled/enable feature was already requested in #661

I'll mark this as enhancement (for implementing a automatic disabled for X hours on failure feature)

**Comment by binhex** [comment]
Thanks @kaso17

**Comment by cocokola** [comment]
I would love to see this feature as well.  I would also add that every 24 hours the automated test check the disabled trackers to see if they can be re-enabled.  Perhaps make each (4 hours/24 hours)  variables the user can set.  This is a manual process I do every other day to keep things running smoothly. thanks devs!

**Comment by nydave69** [comment]
would love to see a disable button on each provider, also if a provider is having issues then auto disable the provider for say 4 hours (setting adjustable) then enable to see if its fixed..

**Comment by dairefagan** [comment]
I would like to see this feature.

**Comment by kkuhle** [comment]
This would be neat.  It has taken longer than I'd like to admit to realize this is what has caused search from various areas to be slow/unreliable.

**Comment by ilike2burnthing** [comment]
All credit for the work on tags goes to @alecsg77, I just offered a few suggestions and did some testing. I have next to no C# knowledge, so this would have been entirely beyond me 😋 

Onto this req. As far as I see it, there could be two main ways to accomplish it:
1. as you suggested, running periodic tests and disabling on failure
2. disabling on failure from any normal request

Method 1 has the benefit of testing all configured indexers, useful for those not using the `all` feed and who either don't use automation applications like RSS feed readers or Sonarr et al, or who do use these but not with all their configured indexers.

The possible downside would be that you run into conflicting simultaneous searches, re-login attempts, or FlareSolverr requests, however given that this is already potentially caused by using multiple automation applications (e.g. Sonarr + Radarr), and I'm not aware of anyone complaining about something like that happening, this can probably be ignored.

A more likely possible downside would be for those who have a high number of indexers configured and are running on low spec hardware (e.g. a Raspberry Pi or an old/cheap NAS), as this could periodically cripple those systems. The obvious solution here would be to have an `Enable Indexer Healthcheck` setting, which they could disable.

Method 2 would reverse these pros and cons - may not test all indexers, but no conflicts with other searches, and no additional resource usage and traffic.

There's also a few questions that would need answering (not necessarily from you, just generally, but if you have any thoughts then by all means):
1. do we allow the schedule to be user configurable (e.g. 1hr, 2hrs, 6hrs, 12hrs, 24hrs, 48hrs, or a textbox similar to the cache's TTL)?
2. does the schedule run from application start time or midnight local time?
3. do we also have user configurable options for `Action on Indexer Heathcheck failure`, e.g. `Disable` (default), `Notification` (some sort of icon, maybe a yellow alert triangle instead of the red one, but the indexer would remain enabled), `Log Only`?
4. does the healthcheck test disabled indexers and re-enable them on successful tests, or skip them and rely on the user to retest and re-enable?
5. do we add a manual enable/disable button?
6. does the healthcheck use Jackett's test function (therefore bypassing the cache), or just use a keywordless search (would in essence double as a way to preload the cache, but would also fetch from it if the TTL and results limit hasn't been exceeded)?
7. how does the API respond to a search using a disabled indexer?
8. probably some other things I can't think of

Finally, as for how easy this would be to implement, for me it would be impossible, but generally... 🤷

**Comment by binhex** [comment]
thanks for the reply @ilike2burnthing my thoughts on your questions/ponderings:-

1. i think a user configurable period to test would be ideal.
2. i would expect running from startup is a reasonable thing to do, but i could see a situation where people only want indexers tested at a set time, so thats a tricky one, perhaps an option to specify?.
3. sounds reasonable to have user configurable options for failure yes, your suggested options sound good to me.
4. my personal preference here would always be to have automated re-enablement, but perhaps this could be an option for the user to decide the action to take on a index site coming back online.
5. this is slightly out of scope for this particular enhancement, but i could see it being VERY useful, if the user did disable an index site then it should be skipped from any subsequent testing and potential automated re-enablement, as the user made the decision to mark it disabled.
6. you def do not want any caching going on. but other than that whichever is the lightest on bandwidth.
7. hmm a good question, perhaps you could use the new tagging system and allocate disabled indexers with a 'disabled' tag, this tag would then be ignored for all defined tags, including the 'all' aggregated feed, on re-enablement the tag is removed.

**Comment by alecsg77** [comment]
Hi

as far as I get from the conversation, here I see two problems:

1. How can I avoid using an unhealthy indexer in my aggregated search?
2. How can I automate the health checking?

I think that the new filter feature can help on point 1.
We create new filters based on the healthy of the indexer (`healthy:true`|`healthy:false` or `status:healthy`|`status:error`)
On API side, we can have an endpoint like `/api/v2.0/indexers/status:healthy/results/torznab` as aggregation only healthy indexer  (actually nothing can avoid that one of them go in error during that search)
On UI side, we can apply the opposite filter (`status:error`) before performer a `Test All` to manually recheck unhealthy indexers

About point 2, I have to investigate a bit more the current implementation to be able to make a concrete solution.
An idea will be:
- if the indexer is healthy, we check his status after k minutes/hours of the last successful request.
- if it is unhealthy, we check his status in incremental time progression after the last tentative (y minutes, 2*y minutes, 4*y minutes,... once per day).
This approach can reduce the number of requests on indexers uses very often and dead indexers.

**Comment by binhex** [comment]
> * if it is unhealthy, we check his status in incremental time progression after the last tentative (y minutes, 2_y minutes, 4_y minutes,... once per day).
>   This approach can reduce the number of requests on indexers used very often and dead indexers.

yeah i like this idea with a backoff that doubles the time period to wait, my only concern with this is that it could take a long period of time before it retries the indexer if it has been down for a long period, perhaps you could implement a maximum retry wait time to prevent having super long retry wait times due to multiple backoff's? e.g. maxRetryWaitMinutes=3600

**Comment by ilike2burnthing** [comment]
Sonarr et al handle indexer failures in a similar way:
> Errors occurs while Sonarr tried to use one of your indexers. To limit retries, Sonarr will not use the indexer for an increasing amount of time (up to 24h).

https://wiki.servarr.com/System_status#indexers_are_unavailable_due_to_failures

**Comment by ilike2burnthing** [comment]
Ah, that's actually brought up a question for me, is the indexer's health status independent of manual tests, or can it be supplemented/updated by them?

So if someone has the healthcheck set to 24hrs, and at the last one the indexer was healthy (e.g. 12am), but later (e.g. 5pm) they run a manual test and it fails, would the status still be healthy?

If not, so manual tests can amend the health status, then I agree that option 'b' `test:{passed|failed}` would be appropriate. But if it would, so we're keeping the healthcheck and manual tests separate, then I'd say 'a' `status:{healthy|error}` is probably the better option, so as to avoid any conflating of the two.

**Comment by ilike2burnthing** [comment]
As far as I can see it uses the `LastError` field from the indexer's .json -
https://github.com/Jackett/Jackett/blob/03709cccea4e7a30f28f5015b8ca336fa98cc271/src/Jackett.Common/Utils/FilterFuncs/TestFilterFunc.cs#L21-L24

So in other words, anything which would be deemed a failure by Jackett. As for what length of a timeout constitutes a failure for Jackett - 100s.

This implementation is using Method 2 from https://github.com/Jackett/Jackett/issues/3292#issuecomment-836576277 (disabling on failure from any normal request), rather than running its own tests.

**Comment by binhex** [comment]
> No persistence and no configuration are required for the first release, right?

as far as im concerned, that's fine by me.

**Comment by cocokola** [comment]
1) how can I test this version? I am using pre-release from the main install currently.

2) the biggest issue I run into is sites that just don't respond in 60+ seconds, I would love the ability to set a time limit to give up on a site's response, especially when using _all .   Typically there a site that for some day's response gets REALLY LONG then it gets better.   

Will this solution address this, or only ones that NEVER respond based on what your master timeout is?
thanks!

**Comment by cocokola** [comment]
If it helps:

more info: I typically add EVERY US-EN site movies/TV, run a test then remove ones that take more than 40 seconds.  If red x, I leave it as it doesn't slow down when adding tons of shows or seasons.

**Comment by ilike2burnthing** [comment]
The current PRs for this are https://github.com/Jackett/Jackett/pull/11705 and https://github.com/Jackett/Jackett/pull/11706.

The former uses the format `http://<ip>:9117/api/v2.0/indexers/test:passed/results?apikey=<apiKey>&Query=<search>` (or `test:failed`).

The latter uses `http://<ip>:9117/api/v2.0/indexers/status:healthy/results?apikey=<apiKey>&Query=<search>` (or `status:failing` or `status:unknown`).

The latter also uses `test:passed`, so you could have `http://<ip>:9117/api/v2.0/indexers/!status:failing,test:passed/results?apikey=<apiKey>&Query=<search>` which will query all the configured indexers not `failing` or which `passed` its last test.

This does not alter the global timeout of 100s, but any indexers which previously failed a test will not be reused.

**Comment by cocokola** [comment]
Tried following doc, but failed to get it to work, until I went back to your example above.  Based on the doc (and It might be entirely me!) I tried to use 
http://mainpc:9117/api/v2.0/indexers/test**=**passed/results/torznab/

when what works is:
http://mainpc:9117/api/v2.0/indexers/test:passed/results/torznab/

Looking at the doc, it is current, I looked at the example " you can also add configured=true/false as a query parameter."  and tried using + instead of :  .  I wasn't thinking in URI terms at the moment.

I hate to be the latecomer to this wonderful improvement, but is there a way to force using (or not using) "test=passed" where the response was over xx seconds?  On my windows system it, I have 41 sites configured I leaned it pulls about 17 of them, then pauses for threads to finish before continuing to look up the rest.

Unfortunately, many of these time out at 60 seconds.  These are what grinds other apps to halt whist the timeouts happen.  I have been able to leave failed ones just fine with no time penalty.  It is the ones that don't respond in a responsible period that I would like to be flagged as failed.  I read through this thread but didn't get the impression this was the case.

thanks SO much for addressing this issue!

**Comment by ilike2burnthing** [comment]
`configured` is a completely separate thing and is used with `t=indexers` to show the capabilities of the different indexers.

When wanting to use filters, only refer to - https://github.com/Jackett/Jackett#filter-indexers

> This does not alter the global timeout of 100s, but any indexers which previously failed a test will not be reused.

There is an open enhancement issue to allow timeout to be configurable per indexer (though whether that's meant to be user-configurable or not I don't know) - https://github.com/Jackett/Jackett/issues/10203

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/pull/11706

**Comment by garfield69** [comment]
v0.18.379

**Comment by binhex** [comment]
Excellent, thanks for all the effort put into this issue, I really appreciate it

**Comment by Nuke142** [comment]
Excuse me. May I ask, how controlled when indexer from `status:failing` returns to `status:healthy` ? How it checks?

**Comment by ilike2burnthing** [comment]
Double whatever your `Cache TTL` is set to in Jackett.

**Comment by Nuke142** [comment]
We can't yet to control how long to wait indexer response, right? Timeout.

**Comment by ilike2burnthing** [comment]
It's just the standard length, 100s - https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.timeout?view=net-6.0

I doubt that's ever going to be user customisable.

**Comment by SanteR1** [comment]
@ilike2burnthing 
status:healthy
I am also interested in whether it is automatically checked upon request or after a period of time?

**Comment by ilike2burnthing** [comment]
There's no periodic check, it's based on the last request. That status (`healthy` or `failing`) lasts for double the length of your cache TTL, after which it reverts to `unknown`.

**Comment by ilike2burnthing** [comment]
It was discussed and rejected, Jackett is not going to automate indexer tests. If you're using software such as Sonarr et al., this will accomplish the same thing anyway.

**Comment by SanteR1** [comment]
I only use jackett and here I look for workarounds for this

**Comment by binhex** [comment]
> It was discussed and rejected, Jackett is not going to automate indexer tests. If you're using software such as Sonarr et al., this will accomplish the same thing anyway.

That's a bit sad, your competition (Prowlarr) does automated testing of indexers.

**Comment by ilike2burnthing** [comment]
@bakerboy448 / @Qstick does Prowlarr do periodic testing of indexers?

**Comment by bakerboy448** [comment]
If full sync is enabled yes Starr would test them at sync time

**Comment by ilike2burnthing** [comment]
Apologies for my ignorance, but does this only work alongside Sonarr/Radarr/whatevarr, or can it also function on its own?

**Comment by bakerboy448** [comment]
That's just prowlarr sync logic pushing to / updating Starr for full sync.

There's no automated testing like OP asked that exists that Prowlarr does.  It's part of the sync task

for Starrs checking it'd be part of the check health task for when indexers are down


Given the original premise of this request was due to the `/all` endpoint and associated issues and the jackett team recommend it not be used / it cannot be used in Starrs - I don't see what benefit automatically hammering every indexer to test it would do.   Starrs and downstream apps handle single indexer failures without issue - so don't see what benefit a periodic test would add

**Comment by binhex** [comment]
> There's no automated testing like OP asked that exists that Prowlarr does.

I would disagree, Prowlarr tests each indexer automatically, if a index site is found to be in a bad state (down, unresponsive etc) then it will mark the index site as failing, if it tests again and the index site is still found to be in a bad state then the index site is disabled and set to be re-tested at a later date, this is exactly the behaviour I was after in Jackett, maybe I wasn't clear enough in the OP.
