### ISSUE TITLE
MejorTorrent doen't show anything with Radarr

### ISSUE THREAD

**Issue by kaiserssosse** [Jackett/Jackett#3310]
I am using the latest Mono version and Radarr version.
Is any way to run MejorTorrent to search movies in Radarr?

Thanks in advanced

-------------------------------

**Comment by kaiserssosse** [comment]
For the Tv Show part works perfectly with Jackett and Medusa.

**Comment by ivandelabeldad** [comment]
Really interesting. I didn't know about Medusa, so tomorrow I'll give it a try because I was thinking about to write a workaround so Sonarr can detect the downloaded episodes. If Medusa is capable of detect the strange naming patterns (or simply ignore them) then that will be way easier.

Thank you for the info.

**Comment by kaiserssosse** [comment]
The thing now is that newpct doesn't download any tv show or films that is why I was interested in mejortorrent. If you need any test with medusa or radarr and jackett tell me.
