### ISSUE TITLE
Jackett Service spawns multiple cmd.exe and conhost.exe

### ISSUE THREAD

**Issue by Jimmy03** [Jackett/Jackett#3335]
Win7 64

I only noticed it in the latest version, July 3-4.

My Task Manager will have 20  instances each of cmd.exe and conhost.exe

**For some reason the Jackett service spawns a new instance of these once per hour.**

When I disabled the Jackett service it stopped happening
Process Explorer handle-viewer showed that it was Jackett causing this

Jackett Service would create a new instance of both cmd.exe and conhost.exe, and then an hour later it would create another instance of these, but not close the previous ones, leaving them all in ram.

**Comment by dougbenham** [comment]
Also encountered this on Windows 10 x64

**Comment by pauljmelia** [comment]
Also encountered on Windows Server 2019 Insider Preview build 17677

**Comment by flightlevel** [comment]
Can't reproduce this here

Can you please 
- Stop the Jackett service
- Close the Jackett tray
- Kill every Jackett process 
- From Windows Add/Remove programs Uninstall Jackett (you won't lose your trackers)
- Go to `C:\ProgramData\Jackett` and make sure there is no exe or dll files present, only config and log files should remain after uninstalling
- Download the latest Jackett release and install via the Windows installer

If the issue is still occurring after that, please post the log.txt, updater log, tray log and service log

**Comment by flightlevel** [comment]
@Jimmy03 @dougbenham @pauljmelia 
Did the above resolve the issue for you?

**Comment by pauljmelia** [comment]
Hi there @flightlevel, sorry for not adding more. Followed your suggestions and so for I don't have the issue.

Cheers,
P.

**Comment by Jimmy03** [comment]
@flightlevel 

Followed your instructions, seems to be resolved now.

Thanks
