### ISSUE TITLE
Danishbits/Sonarr: Cat 5000 not returning results.

### ISSUE THREAD

**Issue by supremacy2k** [Jackett/Jackett#3467]
Jackett version: 0.8.* to 0.9.16.0

When adding Danishbits to jackett and then adding it to Sonarr, testing on category 5000 (TV), returns no results.

Category 2000 (Movies) or 7000 (Other) is required to get results, and successfully add the indexer to Sonarr.

**Comment by flightlevel** [comment]
Not a member, can you check their website against Jackett https://github.com/Jackett/Jackett/blob/3e5e48c3a03423c0a3c654997ea1e515ff50ab00/src/Jackett.Common/Indexers/DanishBits.cs#L42-L44
If movies are being flagged correctly, compare that to tv
Also, if you perform a manual search in Jackett, what category do TV shows get?

**Comment by supremacy2k** [comment]
When doing a manual search in Jackett, tv shows are listed as TV.
Movies are listed as Movies, and the rest is listed under Other.

It works perfectly when used in Sonarr (it finds tv shows correctly, it just fails the test, for some reason.

**Comment by kaso17** [comment]
The indexer is working fine.
The problem with the failed sonarr test is that the test does a empty search.
Due to danishbits API limitations this will result in 20 oldest torrents. Non of them is a TV show, resulting in an empty search result with cat=5000. The DB API needs to be fixed first.

**Comment by supremacy2k** [comment]
kaso.. we both know that's not gonna happen. :/

**Comment by ngosang** [comment]
related to #2233

**Comment by RoloSoze** [comment]
@ngosang @cadatoiva @garfield69 There seems to be 3 open issues related to DanishBits - This one, #2233, & #2657. I understand from @kaso17 that changes need be made to the DB API by the DB staff with to help solve these issues, but they didn't seem to be motivated to fix things: https://github.com/Jackett/Jackett/issues/2233#issuecomment-348949910 

I don't know if things have changed since December 2017, but I just realized I have a spare invite there. It's a C# tracker (sorry @garfield69) so if someone is willing to restart the conversation with the staff in attempt to solve DB's pending issues, I can send them an invite. I won't be starting the conversation myself because it's not a priority tracker for me personally.

If there is no interest to do so, please disregard this message.

**Comment by ngosang** [comment]
@RoloSoze Send me invites for Danishbits & HD-Space. I will take a look with low priority, I'm working in something more interesting for this project. :)

**Comment by RoloSoze** [comment]
> 
> 
> @RoloSoze Send me invites for Danishbits & HD-Space. I will take a look with low priority, I'm working in something more interesting for this project. :)

Sent for both to your Gmail, @ngosang. Accept before they expire, please :)

**Comment by garfield69** [comment]
closed due to #9949
