### ISSUE TITLE
Kestrel working directory traversal

### ISSUE THREAD

**Issue by kaso17** [Jackett/Jackett#3522]
@flightlevel any idea how we can make Kestrel stop doing a directory traversal of the working directory?
If it's not possible I'd suggest we change the working directory within jackett itself.
Not sure if that might cause any updater trouble in some odd configs.

**Comment by flightlevel** [comment]
@kaso17 That was a bit of mine field, was sure it was Mono doing something dodgy, but nope

Turns out, the default WebHostBuilder 
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-2.1
`Sets the content root to the path returned by Directory.GetCurrentDirectory.`

https://stackoverflow.com/questions/41052866/dotnetcore-content-root-path-is-changing-when-using-systemd-on-ubuntu16-04

At least that explains what was happening

@marcelpaulo 
As the resident systemd expert can you please try with the latest pre-release v0.10.5 to see if systemd now works without a working directory?

Linked issue: https://github.com/Jackett/Jackett/issues/3509

**Comment by marcelpaulo** [comment]
> Sets the content root to the path returned by Directory.GetCurrentDirectory

Nice catch ! It does explain what we found out in #3322.

> please try with the latest pre-release v0.10.5 to see if systemd now works without a working directory

f00d8e192ad01d6999c939f5e7d742d47ed19ba3 squashed the bug ! **v0.10.5** is working fine without setting `WorkingDirectory` in the systemd service file (_~/.config/systemd/user/jackett.service_):

```
[Unit]
Description=Jackett Daemon

[Service]
ExecStart=/usr/bin/mono --debug /opt/Jackett/JackettConsole.exe --NoRestart
Restart=always
RestartSec=2
TimeoutStopSec=5
SyslogIdentifier=jackett

[Install]
WantedBy=xfce.target
```

Well done !

**Comment by flightlevel** [comment]
Thanks @marcelpaulo good to hear

@kaso17 think we're slowly edging towards a general release, maybe see how it is by the end of the week, this one should fix a lot of issues
The other issue I can see popping up is reverse proxy configuration, but can't really see any easy fix. At least the majority aren't using a reverse proxy 
Didn't realize you had added reverse proxy in the readme, copied Microsoft docs and Ombi for the page in Wiki. Anyway, might be best just getting user feedback before changing. I tried IIS and nginx, both seemed okay for me, but don't actually use a reverse proxy so no that familiar with them

https://api.github.com/repos/Jackett/Jackett/releases
```
        "size": 10267352,
        "download_count": 5654,
        "created_at": "2018-07-31T10:23:42Z",
        "updated_at": "2018-07-31T10:23:45Z",
        "browser_download_url": "https://github.com/Jackett/Jackett/releases/download/v0.10.1/Jackett.Binaries.Mono.tar.gz"
````
5,000 downloads of 0.10.1, so even if a percentage of that are active users, hopefully got some ARM, Synology and QNAPs in there
