### ISSUE TITLE
Jackett keeps uninstalling 

### ISSUE THREAD

**Issue by QT31416** [Jackett/Jackett#3539]
My Jackett keeps uninstalling. Everyday I install it. When I get back home, I see tons of reds on my calendar due to Jackett being down again. The timing of uninstalling is totally random. Jackett is the only program I have that uninstalls randomly.

Operating system: Windows 10 64-bit
Other github projects installed: Sonarr, Radarr, Tautilli, Ombi, Qbittorrent

**Comment by flightlevel** [comment]
So its completely gone from Windows Add/Remove programs?

Please turn on enhanced logging from the dashboard and click save.
When it next happens, provide the log files plus updater.txt plus servicelog.txt

**Comment by QT31416** [comment]
I checked the control panel, the Jackett entry is still in the Add/Remove programs list. It's just all of a sudden, the web ui isn't working, sonarr and radarr can't reach my indexers.

I'll provide the log files, updater.txt, and servicelog.txt when it happens again. Tell me if you need any other information from me. Thanks!

**Comment by QT31416** [comment]
It went down again some time over night.

log txt
[log.txt.20180812.00000.txt](https://github.com/Jackett/Jackett/files/2281348/log.txt.20180812.00000.txt)


servicelog txt
[ServiceLog.txt](https://github.com/Jackett/Jackett/files/2281350/ServiceLog.txt)

I can't seem to find the updater txt

**Comment by flightlevel** [comment]
Can you try again, but this time with enhance logging switched off. It had too much detail that it missed part of the day

**Comment by garfield69** [comment]
are you still experiencing this issue? 
and are you by any chance using AVAST as your virus/malware protection?

I have had a recent experience where during the Jackett auto-update, AVAST silently quarantines the updated jackettconsole.exe, which means that the Jackett service does not get restarted.
this would match your symptoms.
I have to continually check my virus chest, select the quarantined file, flag an exception and restore the program.
I have set my AVAST to *Ask me* instead of defaulting to *move*, so at least mow I get a heads up when it happens.
I have regularly submitted the file for analysis and as a false-positive to AVAST but they have yet to sort this out.
