### ISSUE TITLE
limetorrents bad link

### ISSUE THREAD

**Issue by Delerium** [Jackett/Jackett#3627]
limetorrents points to limetorrents.io which is a dead link.  it's moved to limetorrents.cc (which redirects to limetorrents.me). 

I'd change this on my personal copy, but for some reason every time I configure the indexer, it pops up saying it was successful, but no changes are actually saved.  Wasn't sure which of these two to report, so I settled on the dead link because I wasn't sure if manual configuration was disabled on purpose or not.  If it's a bug, well a fix for that would be awesome too. lol

**Comment by garfield69** [comment]
Despite the address on the web page stating .cc, the actual url to get to it is .me
Updated the indexer definition to reflect this, and the next (pre) release in jackett should include the fix ;-)

**Comment by garfield69** [comment]
@Delerium either use the jackett dashboard to edit the limetorrents configuration and set the sitelink to .me and save, 
Or
Edit your personal copy and move the .io to the legacy sites section, and put .me as the main site link. Then restart the jackett service to pick up the change.

**Comment by Delerium** [comment]
That was my point in my first post that the configuration function in the dashboard isn't actually saving any changes despite it saying that it does when I click save.  When I go back into configure, it shows the old address instead of the new one I put in

**Comment by garfield69** [comment]
@Delerium no sorry, we are miss-communicating.
If you are using the dashboard, you dont need to restart the jackett service.

 But you do have to use the .me link in your dashboard update, which is the correct new link. 
If you try to save the .cc link, this will not work,as the definition auto changes it back to .io because .cc was the original link before they switched to .io 

When I talked about restarting the service in the second option I gave in my original reply, that was only  if you took the choice to manually edit the limetorrents.json indexer file directly, using a plain text editor. That is what I though you meant in your first post, but I see now that you we talking about using the dashboard all along, so please ignore  my second option suggestion. ;-)

**Comment by Delerium** [comment]
Oh ok. I'll try the .me option when I get home from work. Thanks for your help! I'll post more if I still can't get it to save the change
