### ISSUE TITLE
Jackett.ExceptionWithConfigData when creating new indexer

### ISSUE THREAD

**Issue by Codehhh** [Jackett/Jackett#370]
When testing my implementation of PTP indexer I get the following error when trying to log in. What is causing this?
```
 Configuration failed: Exception of type 'Jackett.ExceptionWithConfigData' was thrown.
```

[My Fork](https://github.com/Codehhh/Jackett/tree/master/src)

**Comment by flightlevel** [comment]
Not sure where that error is coming from, have you tried with breakpoints to see roughly where it comes from?

Had a look at your code and looks good. Just one minor thing
https://github.com/Codehhh/Jackett/blob/master/src/Jackett/Indexers/PassThePopcorn.cs#L76
Line 76 I think you mean `!= "Error"` instead of `== "Error"`
This may be causing the exceptionwithconfigdata as Jackett would have only saved your details if they were incorrect.
Hopefully that fixes the problem, if not let me know, its very difficult to debug when you don't have access to the tracker

**Comment by Codehhh** [comment]
I just tried changing the `!= "Error"` to `== "Error"`, and now I get a response `"Configuration failed: Found no results while trying to browse this tracker"` but only when I put incorrect login credentials.

Is there a better way I should be doing this since PTP has an API?

**Comment by flightlevel** [comment]
I think you are going about it the right way. I don't have access to PTP but couchpotato implementation looks pretty similar https://github.com/CouchPotato/CouchPotatoServer/blob/1477ec27bfec30bfcaf9cb9f720a5239019e9a15/couchpotato/core/media/_base/providers/torrent/passthepopcorn.py
Are you deleting the tracker each time from Jackett Dashboard page when you try something different just so that the config file gets thrown out?
Also, confirming you changed it TO `!= "Error"` instead of other way round.
Also, I'd try putting a breakpoint in so that you can capture the response variable on line 74 so that you can see what the response is when you are getting 'Found no results'

**Comment by Codehhh** [comment]
When trying to add the tracker it doesn't continue so I'm adding it fresh each time.
Hahaha, I did change it to `!= "Error"`, not the other way around. 
What is the best way for me to see what the response variable is? I tried using `Console.WriteLine` (running from Jackett Console) but it didn't write.

**Comment by flightlevel** [comment]
In Visual Studio click the spot where the red dot in the below image is
https://snag.gy/wu3BTa.jpg
This will make the code halt at that point (breakpoint), you can then view the values for the code above that line. To view the values, hover the mouse over the word response like below, then over the arrow
eg.
https://snag.gy/Wrt6fg.jpg
I'm getting a CloudFlare error, so it might be smart enough to block me for using the wrong details a few times or PTP might be having issues

You can add as many break points as you want, gives you get idea of where its getting stuck.

Also a good idea, goto Debug at the very top of visual studio then windows > exception settings and tick Common Language Runtime Exceptions

**Comment by Codehhh** [comment]
Looks like PTP just went down, so I'll update this when it's up and I have more time to work.
