### ISSUE TITLE
NoName Club download not works

### ISSUE THREAD

**Issue by JulyIGHOR** [Jackett/Jackett#3786]
**Jackett version**:  0.10.164.0
**Mono version** (if not using Windows):  unRAID docker

Searching with NoName Club works fine, but when I press download torrent button I got blank page.
I have test other search providers, download works fine there.
Please advice how to fix.

**Comment by garfield69** [comment]
I believe that the site requires users to have a login in order to download. 
have you registered, and added the username and password in your Jackett nnc config?
if you have done all that and it still does not work, then 
Please provide the full enhanced log file. You will find the instructions for enabling enhanced logging and the locations of the log file at https://github.com/Jackett/Jackett#troubleshooting.
Remember to redact any personal details first, usernames, passwords, passkeys, hashes etc.

**Comment by JulyIGHOR** [comment]
Yes, I'm sure it logged in and password is correct.
There is lots of logs and I found this:
![image](https://user-images.githubusercontent.com/3390357/45590629-d48d3380-b93c-11e8-8ead-8e9a7c6adc86.png)
Also urls generated to download torrent file is valid, and I can use them via authorized browser.
Do you still need more logs or it is enough?

**Comment by garfield69** [comment]
provide the search string you used, and indicate which torrent you tried to download. I'll see if I can recreate the problem.

**Comment by garfield69** [comment]
strange. I have no problems downloading from nnc on my win10 platform, and I am not sure what is going on with your download requests on your docker image.
I'm going to invite @kaso17  and @flightlevel  to help out.

**Comment by kaso17** [comment]
it'a a new variant of the mono relative redirect bug only affecting mono users.
Should be fixed via 7a2c0bf260541f3385fd142d4b4dfc2501150cd0
