### ISSUE TITLE
Questions about configuring Jackett manually.

### ISSUE THREAD

**Issue by Swainoo** [Jackett/Jackett#3798]
In the README it mentions "You may also download the zipped version if you would like to configure everything manually."

The reason I want to do this is my indexer often gets blocked by UK IPS's so the link that works changes and sometimes it takes a while for someone to make a pull request for the new links to be added.

I'm a tad confused on how to manually configure myself, do I download the binaries zip or the source code zip? The binaries zip has the definitions folder but there isn't a torrentday.ylm in there for me to edit.

The source code zip has the indexers folder where I can edit the torrentday.cs file to include a new link but then i'm not sure how to get the amended source code into a working version of jackett.

**Comment by garfield69** [comment]
there are two kinds of indexers on jackett, those written in yaml, and those written in c# (yaml  support was introduced later, but there are still some indexers that need the custom logic that the c# code can provide).

if you are looking to make changes to the c# indexers, consider the following:
1. in most cases you can adjust the site link by simply using your jackett dashboard and editing the indexer config and replacing the site link with the one you require.
2. however, there are some c# indexers that are not coded to support config changes, so in that case you could 
a. report it so that we can make the necessary support changes (because that benefits everyone) or
b. download the Visual Studio community SDK and code your own solutions. see https://github.com/Jackett/Jackett#windows.

**Comment by Swainoo** [comment]
> there are two kinds of indexers on jackett, those written in yaml, and those written in c# (yaml support was introduced later, but there are still some indexers that need the custom logic that the c# code can provide).
> 
> if you are looking to make changes to the c# indexers, consider the following:
> 
> 1. in most cases you can adjust the site link by simply using your jackett dashboard and editing the indexer config and replacing the site link with the one you require.
> 2. however, there are some c# indexers that are not coded to support config changes, so in that case you could
>    a. report it so that we can make the necessary support changes (because that benefits everyone) or
>    b. download the Visual Studio community SDK and code your own solutions. see https://github.com/Jackett/Jackett#windows.

Thanks for the response.

Another user has posted about the issues with TorrentDay where I have posted the working links, hopefully it gets resolved soon.

https://github.com/Jackett/Jackett/issues/3796#issuecomment-421009197

**Comment by kaso17** [comment]
#1473 contains instructions how to change the site link manually for any indexer
