### ISSUE TITLE
Horriblesubs not downloading selected quality

### ISSUE THREAD

**Issue by bootymcjudy** [Jackett/Jackett#3841]
Hey!
Sorry I'm new to github but I do a lot of my own home projects so please bare with me.
So the issue is sonarr is searching for an anime (my hero academy) and only downloads the 480/SD files. Which makes sense when I set the quality to ANY; however I would like to download the 1080p files, and so I set the tv series to be 720/1080p and it doesn't download it. Now I check the logs of jackett and it seems to make the requests when its ANY and shows the following:

Info | Found 3 releases from Horrible Subs for: Boku no Hero Academia 61

So that tells me its finding all 3 releases of the same anime (480, 720, and 1080). So when I choose the quality to be 720 or 1080 it shows instead of found 3 it shows it found 0.

Looking through the logs theres also something I've noticed although it doesn't happen all the time. Sometimes its looking for "boku no hero academia s3 61" and I have a feeling (although unconfirmed) that it may be knowing that episode 61 is in s3 but s3 doesn't have an episode 61. (this is due to anime being numbered either ABSOLUTE numbering or Seasoned numbering) I don't know if that does make a difference

using jackett Version 0.10.198.0 and Sonarr Ver. 2.0.0.5228 both running off docker

**Comment by garfield69** [comment]
the horriblesubs indexer was not creating a **G**lobal **u**nique **id**entification (Guid) entry in the  results it returns. A **null** Guid in all results meant that Sonarr would accept the first result, but the rest were discarded as duplicates of the first). Happens that the 480p record is the first generated, so the 720p and 1080p ones were ignored by Sonarr.
This will be fixed in the next (pre)release of Jackett whenever that gets published.
