### ISSUE TITLE
[magico] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by Hackerpcs** [Jackett/Jackett#3846]
**Jackett version**:  0.10.198.0

-------------------------------

https://pastebin.com/TX7ggbN0

**Comment by garfield69** [comment]
the log you provided appears to be a regular log, which is not much use.
 Could you repeat the test with *enhanced logging* enabled please?
note that the *enhanced logging* is reset whenever you restrt jackett.

**Comment by Hackerpcs** [comment]
Hm, did I forget to turn on enhanced logging?

https://pastebin.com/XZ9J1VQe

**Comment by garfield69** [comment]
it looks like the HTML you are getting from the magico site is a bit different to what the jackett magico indexer is expecting.
I've made what I hope are the correct amendments, but since I do not have a login It is untested.
please upgrade to pre-release 0.10.225, and if it does not work then provide the full enhanced log so I can hopefully see what I did wrong.
Thanks.

**Comment by garfield69** [comment]
actually we are making progress ;-)
in your first pastebin, we were not even finding the torrent records.
in your second pastebin, we have the records, but one of the required fields (category) was using a different selector than expected. I've modified the indexer to use a more generic selector.
try out 0.10.227

**Comment by Hackerpcs** [comment]
All good! Test and a sample search worked.

**Comment by garfield69** [comment]
fantastic!
