### ISSUE TITLE
[xthor] replace MULTI by FRENCH

### ISSUE THREAD

**Issue by nyanloutre** [Jackett/Jackett#3847]
This is a suggestion.

It would be nice to have the same option that is present in yggtorrent that allow to replace MULTI in the search results by another string like FRENCH or MULTI.FRENCH

I looked into the source code and Xthor seems to be configured by some custom code instead of a YAML definition so I don't know how to implement this functionality.

**Jackett version**:  0.10.198
**Mono version** (if not using Windows):  5.8.0.108

**Comment by danyboy666** [comment]
ok now I just found out why I can't fetch anything from a certain torrent tracker... I have a regex that searches for MULTi x264. It never returns anything byt when I look in jackett I find the proper torrent in the search result but with FRENCH in the tag instead of MULTi. This is a bad design in my opinion it should not be affectiing global search but only per tracker options. How can I change this behavior?

**Comment by mrhydejc** [comment]
You can close this issue.

**Comment by evolfox** [comment]
Hello, Can you add this option for any other French tracker?

**Comment by garfield69** [comment]
@evolfox  list the french trackers you want this multi replacement feature and I will try to implement.

**Comment by evolfox** [comment]
@garfield69 ok thanks, I was thinking about Abnormal.

**Comment by garfield69** [comment]
try out jackett pre-release v0.11.294 and see if i have the abnormal indexer correctly set up to process the multi option. I don't have a login for this site so I cannot test it myself.

**Comment by evolfox** [comment]
@garfield69 it works, thank you ;-)
