### ISSUE TITLE
Idope Clone Seeders and Leechers Aren't Shown

### ISSUE THREAD

**Issue by rebekah65** [Jackett/Jackett#3914]
The number of seeders and leechers for Idope Clone are always shown as 999 for all results.

This creates problems when the result with the highest number of seeds are automatically downloaded, also it makes it hard to no what to pick when you don't no the real number of  seeders or leechers.

Log: 
https://pastebin.com/FsEWNqz1

**Jackett version**:  0.10.265.0
**Mono version** (if not using Windows):  5.14.0.177

![screenshot_2018-10-04 attraction - radarr](https://user-images.githubusercontent.com/43880872/46535726-2ffb7300-c8a4-11e8-8f89-e5b8825837b7.png)

**Comment by garfield69** [comment]
The problem is that the idopeclone web site does not have seeders and leechers in its results. 
![image](https://user-images.githubusercontent.com/6933240/46549193-b0b28180-c92d-11e8-9e5e-2fdbcc835432.png)

Since some apps that use Jackett as a proxy require require a value for seeders or else they reject the results, it was decided to set a default number of seeders and leechers in the results that Jackett returns for this site.

I will happily accept suggestions on how to improve this situation :-)

**Comment by zero77** [comment]
I don't currently have a solution but, it may be helpful to drop the number to one or something smaller then the current number.

**Comment by restalfep** [comment]
I strongly agree with zero77, with it as 1 then at least it could be filtered out by minimum seeders 2 or higher but as 999 then it basically requires turning that tracker completely off, or risk it downloading torrents that really have 0 seeders and just hang. Not sure if better way to do that though.

**Comment by garfield69** [comment]
jackett pre-release v0.10.269 has the requested amendment.
