### ISSUE TITLE
[btdb] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by JynxLee** [Jackett/Jackett#3994]
First time user.  Just added BTDB as first and only tracker.  Error on test.
Jackett version 0.8.490-6 from synocommunity.

**Comment by garfield69** [comment]
the btdb indexer in your jackett version 0.8.460 uses https://btdb.to/recent  for the test, but the btdb site currently returns *Down for Maintenance, We Will Be Back Soon*

however regular search work.

so as long as the indexer shows up in your jackett dashboard, go ahead and use it for searching. just don't use the *test* button.

alternately, upgrade jackett to at least v0.10.273 to get the fix for the test.
