### ISSUE TITLE
[zamundanet] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by fevkalbeser** [Jackett/Jackett#4068]
Like the title says, zamunda.net test fails. User login is OK.
The site works when accessed directly.
Jacket is latest version (0.10.365.0)

**Comment by garfield69** [comment]
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

**Comment by fevkalbeser** [comment]
Here's the log.
[log.txt](https://github.com/Jackett/Jackett/files/2519032/log.txt)

**Comment by garfield69** [comment]
looks like there has been significant changes to the results html.
@pidov are you able/willing to update? thanks.

**Comment by pidov** [comment]
As far as I can tell the html that is described in the definition file and the html served by the tracker are matching. I am also getting consistent test and search results running 0.10.250.0.  
Not sure what's causing the issue on OP's end. The html in his log file is very suspicious. It is indeed very different from the definition.

**Comment by garfield69** [comment]
@pidov  thanks. maybe it has to do with the language the OP has set. What lang are you using? 
there seems to be a choice of bg, en, ru, tr.

**Comment by fevkalbeser** [comment]
I am using it in English.

**Comment by fevkalbeser** [comment]
Any thoughts? @garfield69

**Comment by garfield69** [comment]
sorry, no clue. @kaso17  we could use your expertise on this ticket. thanks.

**Comment by kaso17** [comment]
The HTML from the log is very different from what the definition selectors are expecting.
Given the comment from @pidov (definition is working perfectly fine) I would assume that there's some config option to change between different styles/layouts causing these massive differences.

**Comment by fevkalbeser** [comment]
Thanks anyway :) @garfield69 @pidov @kaso17

**Comment by garfield69** [comment]
@fevkalbeser  did you ever get figure out what profile change was needed to make your zamunda.net Jackett indexer return results for you?

**Comment by fevkalbeser** [comment]
@garfield69 unfortunately no, I couldn't get it to work. Changed every possible setting in the profile with no luck. 
The site is actually free to sign up now. You may sign up and check if you already don't have an account.

**Comment by garfield69** [comment]
Hmm. confusing.
OK. from what I can gather it looks like zamunda was split into two. (according to a comment on https://opentrackers.org/zamunda/

http://zamunda.net for me redirects to  http://foreign.zamunda.net/ which returns 403 forbidden 
it seems zamunda.net and zamunda.ch are restricted to Bulgarian IP Addresses only.
![image](https://user-images.githubusercontent.com/6933240/52806007-cf4f3300-30ec-11e9-9bca-1525f53beb43.png)

I'm not in Bulgaria ;-)

http://zamunda.se also know as http://zelka.org is open, and I have registered there but its html for torrent search results is different from your log and different from the jackett zamunda indexer as well.
![image](https://user-images.githubusercontent.com/6933240/52805990-bfcfea00-30ec-11e9-9b6a-44869327086a.png)

So that make three flavours of zamunda that we have got so far.

@fevkalbeser  if you use your browser to access http://zamunda.net where do you end up now?

I wonder when you tried using this site in Oct 2018 if you might have been caught up in the split?

**Comment by fevkalbeser** [comment]
I end up at http://zamunda.net/. It does not redirect me to http://foreign.zamunda.net/. 

I am not in Bulgaria either :) But it seems like my country's ip addresses (Turkey) are also allowed (there's also an option to view the site in Turkish). 

I don't recall ever signing up at zamunda.se or zelka.org. I've also come accross a message sent from zamunda.net team to its users (back in 2013):
"friends, a group of hackers have downloaded a backup of the site and it is possible to pick up a few sites with similar design and information from previous days.
do not worry about passwords are encrypted and no one can see them in pure form.
therefore, it is difficult to enter the site near 2 days. we're working on fixing the problems and we apologize for the inconvenience.

team zamunda.net!
team zamunda.net does not recommended for you to type your account and password in similar or copying zamunda.net pages.
zamunda.net is only one, but we can not guarantee the security of your account in case you stumble and logged in hacking a copy of our web site."

I also read some comments that say zelka.org is a separate and fully functioning site now. Maybe it can also be added to the list of indexers for Jackett.

If you have a vpn that can connect you from Bulgaria or Turkey, you may try signing up for zamunda.net perhaps. That's all I can think of right now. 

Please let me know if I can help you in any other way.

**Comment by garfield69** [comment]
The Zelka.org indexer was added to Jackett in Jul 2017.
I don't have access to any VPN, I have never need one in my region for the sites that I access.

The only option that I can see here, assuming you really want to use your flavour of the zamundanet web page with Jackett, is for you to have a personal indexer built.
I could mock up one based on the html you have in the log, but because I cannot test it live, it may take several iterations of you testing my code, and then you providing enhanced log files whenever something does not work, followed by my providing another update till I get it right.

Assuming you are prepared to put up with this we can have a go. 

Alternatively we can just close this ticket as unsolved.
Up to you.

**Comment by fevkalbeser** [comment]
That would be too much work for little gain I guess :)
I've just added zelka.org instead of zamunda.net. I think you may close this ticket.

**Comment by elboletaire** [comment]
I've just registered to zamunda.net and I can't get any search results. I've been checking my settings and I've them set by default:

- Language is set as english
- Page theme is set as classic

zelka.org is not accessible from my location (I'm from Barcelona, Spain).

Here's my detailed output log for a direct search in zamunda.net using jackett:

[zamunda-jackett.log](https://github.com/Jackett/Jackett/files/3219344/zamunda-jacket.log)

Am I doing anything wrong? :confused:

**Comment by garfield69** [comment]
I don't have access to zamunda.net (I get 403 forbidden) so I cant check this out directly myself.
However, looking at the log you provided I think I see that the torrent results are being listed in **GRID** view.
login directly from a browser and see if you have a profile option that switches the torrent results to **LIST** view.
If it is not a profile option, then try switching it on the torrent search page itself, there appears to be a button/link that switches it there.

**Comment by elboletaire** [comment]
Thanks! Apparently it was that. There's no direct option in settings to change it, but nearby the list there's a button which, curiously, has an arrow without any description pointing to it:

![imatge](https://user-images.githubusercontent.com/153305/58375317-4730c300-7f50-11e9-8171-15cac262f84d.png)

Although it's always colored as grid, after changing to list the style changed and searching in jackett worked perfectly. Thanks @garfield69 😃

**Comment by garfield69** [comment]
@fevkalbeser  maybe switching to list view will also solve your problem. see post above.

**Comment by fevkalbeser** [comment]
@garfield69 Yes, I am now able to use zamunda.net. Thank you all!

**Comment by pidov** [comment]
Wow can't believe what caused the issue. 

@garfield69 I'm not very familiar with Jackett's inner workings but do you think it's possible to support both GRID and LIST views? I'm willing to make a PR, but need some directions (if it's actually reasonable).

**Comment by garfield69** [comment]
@pidov  it should be possible. all you need to do is append to the selectors, comma delimited.
for example:
```yaml
      title:
        selector: td:nth-child(2) > a[href^="/download.php"], div > a[href^="/download.php"]
        attribute: href
```
and for any fields that are only on grid, or only on list, you can add the _optional: true_ statement.
