### ISSUE TITLE
[yggtorrent] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by Wells83** [Jackett/Jackett#4131]
**Jackett version**:  Version 0.8.490.0
DSM 6.2.1-23824 Update 1   DS415+
**Mono version** (if not using Windows):  5.8.0.108-11

-------------------------------
Hi, all my tracker return "Found no results while trying to browse this tracker (Test)"

I dont touch anything so i dont understand why :(

**Comment by garfield69** [comment]
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

**Comment by garfield69** [comment]
the problem here is that your version  of Jackett 0.8.490 is well out of date.
the yggtorrent indexer you are  using does not match the current yggtorrent html the site is producing.
the site changed this back in april 4th so tests should have been failing since this time.

upgrade your jackett to the latest version to fix this. the yggtorrent indexer has gone through 27 commits since your version was published ;-)
also, you may need to upgrade your mono to the lastest versions 5.16+ for matching features support.

**Comment by Wells83** [comment]
in my synology, i dont have a new version of jackett :(

where i can download it ?

on synology community (https://synocommunity.com/packages) the last version is v0.8.490

?????

**Comment by garfield69** [comment]
i dont know for sure since its not my scene, but perhaps you could try using a docker image from https://hub.docker.com/r/linuxserver/jackett/ which may work on on platform ... maybe?
@flightlevel  @kaso17  any comments re: syno and docker compatibility?

**Comment by Wells83** [comment]
ok i'am stupid, they are a button "update" on the interface ^^

is good now, thx
