### ISSUE TITLE
YGG torrents disappeared 

### ISSUE THREAD

**Issue by Nemrod7** [Jackett/Jackett#4187]
**Jackett version**:  0.8.490-6
**Mono version** (if not using Windows):  5.8.0.108-11

-------------------------------

**Comment by garfield69** [comment]
try upgrading to the latest jackett and mono.
otherwise 
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

**Comment by Nemrod7** [comment]
A log ? I can't see the tracker in the list.

**Comment by garfield69** [comment]
We have not deleted it so it should be there someplace.
The log would show the indexer being loaded if it was there.
If it is not in your active list on your jackett dashboard, check you are not filtering by having something in your search box.
If it's not that, then look at the add-indexer page, and also check you are not filtering that page with anything in the search box.
Still cant find it?

**Comment by garfield69** [comment]
@kaso17  can you take a look at this ticket please?

**Comment by kaso17** [comment]
@Nemrod7 based on the log/HTML you  posted YGG was loaded fine and you actually configured a filter to show only the YGG indexer. There are also some successful searchs. Everything is looking fine to me.

**Comment by Nemrod7** [comment]
Ok, thanks @kaso17, I'm not sure to understand why I'm not seeing it but I'll check again.
