### ISSUE TITLE
[Speed.cd] When clicking on a result it gives a .torrent download instead of opening the torrent page

### ISSUE THREAD

**Issue by whitesnakeftw** [Jackett/Jackett#4285]
Basically it should be: https://speed.cd/t/xxxxxx

instead of: https://speed.cd/download.php?torrent=xxxxxx

**Comment by garfield69** [comment]
not so straight forward.
 current c# code
```c#
                    Uri link = new Uri(SiteLink + torrentData.Find("img[title='Download']").First().Parent().Attr("href").Trim());
```

I'm going to need to see the HTML in the **full enhanced log** file so that I can see what the selector is for the torrent link 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.

**Comment by garfield69** [comment]
better yet, If you send an invite to garfieldsixtynine @ gmail.com I can then complete the post code change testing to be sure I've got it right, otherwise its going to be a code-and-dash commit with a medium probability it will fail ;-)

**Comment by whitesnakeftw** [comment]
@garfield69 Sadly I don't have any invitations as I barely use that tracker. Btw I'm attaching the log, all I did was selecting speed.cd only and searching for "avengers". As you can see there's a bunch of: `<a href="download.php?torrent=xxxxxxx">` that I believe shouldn't be there, and instead should be replaced by `<a href="t/xxxxxxx">`.

Also, I can confirm that the printed results on speed.cd itself don't show any weirdness as each release name correctly links to its details page (/t/xxxxxxx).

Thanks.

[log.txt](https://github.com/Jackett/Jackett/files/2853182/log.txt)

**Comment by garfield69** [comment]
I've updated the categories, and made an attempt to point the title description link to the details page.
But since I can't test this, I just have to hope I got it right.... did I ?
Try out Jackett pre-release 0.10.741

**Comment by whitesnakeftw** [comment]
@garfield69 That was it! But unfortunately there's an extra slash in the URL before the 't':

> `https://speed.cd//t/xxxxxxxx`

After that the issue can be closed. :)
