### ISSUE TITLE
New categories in AlphaRatio tracker not showing up

### ISSUE THREAD

**Issue by ModelSD** [Jackett/Jackett#4333]
AR recently updated their categories and added new ones. Including "MoviesUHD" which houses all 4k/8k releases. Radarr/Sonarr is not able to search these because I do not know the category number associated with them and it is not listed in Jackett. When will this be updated?

**Comment by garfield69** [comment]
Since AR is private and I dont have a login, you have two choices:
1. wait for @kaso17 who may have a login, and when he has the time to lookup the cats and add them to the indexer
2. or you can provide the info now and I can add the cats for you

If you enable **enhanced logging** and thus capture the html produced by the site when you do a search with AR, I should be able to add the new cats using that info.
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. do a search wth just AR
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here.
Thanks.

**Comment by ModelSD** [comment]
I have the log file but I do not know which information to redact. How can I protect my personal details?

**Comment by ModelSD** [comment]
[Venom - AR search log.txt](https://github.com/Jackett/Jackett/files/2691672/Venom.-.AR.search.log.txt)
Try this. I searched for 'Venom.'
![image](https://user-images.githubusercontent.com/45953189/50173080-53cb3400-02ab-11e9-96a3-6b873251c057.png)

**Comment by garfield69** [comment]
a more general search would have been better, so I had to take some educated guesses for the missing UHD cats (tv and movie uhd packs, tv uhd, etc). so we shall see how that goes.
 if you get any more missing cats again, you now know what to do :-)
release 0.10.525 should contain this fix.

**Comment by ModelSD** [comment]
Fantastic. Thank you.

**Comment by kaso17** [comment]
there were more changes than just new categories. Fixed via d239197f0fee0149484ece9584cf11d8bd5f64a5
