### ISSUE TITLE
Error quality and search

### ISSUE THREAD

**Issue by FabioCastilho** [Jackett/Jackett#4414]
Mono last version
Jackeet: Version 0.10.589.0
Raspberry pi 3

Some errors are happening.

1 - Several films without relationships are appearing
2 - Not finding quality
Manicomio Share and BJ share
![screenshot_4](https://user-images.githubusercontent.com/21134162/50798456-93d87200-12bf-11e9-97fe-e54089a43ecb.jpg)

**Comment by leomoty** [comment]
I have the same issue:

```
 Error bjshare: Error while parsing row
```

**Comment by leomoty** [comment]
So I dug a little deeper, compiled jackett myself, made a breakpoint, whenever I make a search from Radarr by pressing "Search" under any movie I have listed, I get:

Both `query.SearchTerm` and `query.IsImdbQuery` as false here:

https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/BJShare.cs#L139

Thus is just retrieves the daily results instead of performing a search.

My error instead is related to the fact that: 

https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/BJShare.cs#L166

This line is not guaranteed to be non-null, since it also has non-video content.

And subsequently crashes here:

https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/BJShare.cs#L201

**Comment by leomoty** [comment]
Hey @garfield69, now that I solved the "non-issue", do you have any idea why `SearchTerm` would be empty?  

I'll try to debug further when I get home, but when I tried to fill the `SearchTerm` in the breaking point, it worked properly.

**Comment by garfield69** [comment]
possibly this:
https://github.com/Jackett/Jackett/blob/5389995b6df21d518c2aae6a8b3095bf7f7f5e24/src/Jackett.Common/Indexers/BJShare.cs#L131
