### ISSUE TITLE
[HorribleSubs] : search not working

### ISSUE THREAD

**Issue by ade05fr** [Jackett/Jackett#4426]
i tried to search with horriblesubs

the keyword "castlevania" => no result
here is what i have in the jackett log file

2019-01-09 18:42:55.0549 Info Manual search for "horriblesubs + castlevania" on nyaasi with 0 results.
2019-01-09 18:43:41.2647 Info Manual search for "castlevania" on horriblesubs with 0 results.

if i test on the horriblesubs.info site in the search bar it works.

Jackett version: 0.10.97
Mono version (if not using Windows): 5.14.0.177

**Comment by ade05fr** [comment]
In fact i tried to update the comment block thats why i recreate it.
Can you reopen it  ?

**Comment by kaso17** [comment]
@gerdus @CodeMonkey626 can you have a look at this?

**Comment by CodeMonkey626** [comment]
`https://www.horriblesubs.info/api.php?method=search&value=castlevania` does return the two expected results:
- `10/26/18Castlevania S2 - 01-08
SD720p1080p`
- `07/07/17Castlevania - 01-04
SD720p1080p`

It may be because these are batches and not individual episodes and that is causing the parsing to fail.

**Comment by CodeMonkey626** [comment]
PR incoming shortly that fixes this issue (and several other) with HorribleSubs indexer.
