### ISSUE TITLE
1337x magnets not being detected

### ISSUE THREAD

**Issue by brandonscript** [Jackett/Jackett#4572]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

When searching 1337x, it appears most magnet links are being treated as direct download links. For example:

<img width="1344" alt="screen shot 2019-01-30 at 9 29 33 am" src="https://user-images.githubusercontent.com/1480253/52029576-a150d880-24c8-11e9-955b-81986ab60637.png">

The blackhole link sends a .magnet file to the blackhole (which is maybe expected?) but there's no magnet link option in the list of actions.

**Jackett version**: 0.10.681.0
**Mono version** (if not using Windows): 5.8.0.108-11

-------------------------------

**Comment by garfield69** [comment]
strange. i only ever see 1 download link for each entry, regardless of the preference being set to magnet or itorrent.org in the config. (I'm on windows 10).
and when set to magnet, while the icon displayed may not be a U, clicking it generates a magnet download that my torrent client accepts.
But I will add a hard-coded magnet link so you can get the proper icon. watch this space for updates.

**Comment by garfield69** [comment]
ok, fly in the ointment. 1337x does not put the magnet link on the primary results page, but has them on the torrent details page of each result.
the current cardigann implementation in jackett does not support a magnet definition from the downloads page.
this is why the icon displayed is not a U but a download-link icon.
However, when the 1337x config is set to magnet, clicking the icon generates a magnet link, so other than the cosmetic look of the button, it functions as expected.

**Comment by brandonscript** [comment]
Ahhh, that makes sense. Thanks for looking into it.

**Comment by 07416** [comment]
For months (as long as I've had the indexer installed) only torrent files have been available for 1337x.

**Comment by garfield69** [comment]
@07416  are you aware that you can config the Jackett 1337x to download using  either the 1337x details page's magnet link or the itorrent link?
just use the wrench icon on your Jackett dashboard to edit the config and select the download link you want to use.

if you are referring to the fact that the download link icon for 1337x search results on the Jackett dashboard is never a magnet icon for this indexer, then that is simply because the download link is not in the 1337x search results page, but on the details page of each search results entry, so Jackett does not know what type of download link it is.
