### ISSUE TITLE
[Torrentz2] Wrong magnet links returned?

### ISSUE THREAD

**Issue by a575606** [Jackett/Jackett#4574]
This seems similar to #3116, but with Torrentz2. All magnets returned are similar to this format:

magnet:?xt=urn:btih:<< some long hash>>&dn=<<urlencoded torrent name>>.torrent

I understand these are supposed to be resolved by DTH? Do you mean DHT? If so, I have that enabled both on a linux transmission package and qbittorrent running on windows and neither seem to resolve or download the torrent. They just hang in the queue with no seeders. 

Maybe I missed a setting or am doing something wrong?

Browsing to the actual site and manually finding the same release eventually leads to a typical magnet link that works

**Jackett version**:  Version 0.10.665.0
**Mono version** (if not using Windows):  5.18.0.240

-------------------------------

**Comment by garfield69** [comment]
yeah, torentz2 does not provide the magnet links on the primary results page, it has them buried in the torrent details page for each result.
so jackett builds the magnet from the hashkey that is on the primary results page.
And yes, in ticket 3116 kaso17 was referring to the distributed hash table (DHT).

The other option that is useful to enable on most torrent host apps the Peer Exchange (PEX).

And for magnets that are fresh or very popular, the torrent host apps use of the DHT and PEX to find the first peer is usually enough, and once the first peer is connected, it will provide the meta-data from which to boot-strap the torrent contents details of the magnet and enable downloading of the associated files of the torrent.

But finding that crucial first peer using just the DHT and PEX can sometimes take a while, and as the torrent ages that becomes more difficult as peers for the torrent become scarce.

So its really helpful sometimes to have a good peer tracker to kick things off in a more timely manner.

I don't see a problem with adding a few default trackers  such as udp://tracker.coppersurfer.tk:6969 udp://tracker.leechers-paradise.org:6969 and udp://tracker.opentrackr.org:1337 to the magnets that the torrentz2 indexer builds, so that is what I'm going to do.
check this space for updates.

**Comment by a575606** [comment]
Great, thanks for the feedback. I'll keep a look out for that, although I have tried manually adding those trackers and it doesn't always help. I just thought something was going wrong because the torrent details page magnets often do find seeds. Anyway, you have such a massive list to maintain, I don't know how you guys do it. Thanks for what you're doing.

**Comment by garfield69** [comment]
check out Jackett pre-release  0.10.686.
