### ISSUE TITLE
RARBG: Not delivering the newest entries

### ISSUE THREAD

**Issue by faulander** [Jackett/Jackett#4583]
Jackett Version 0.10.678.0
Mono JIT compiler version 5.18.0.240 (tarball Wed Jan 16 09:13:03 UTC 2019)

-------------------------------
Searchresult on Jackett is 8 days old. Already tried restarting Jackett, didn't help.
Here are the screenshots of the searchresults: https://imgur.com/a/J9Uc8zw
and here's the searchterm used: http://localhost:9117/api/v2.0/indexers/rarbg/results/torznab/api?apikey=APIKEY&t=search&cat=&q=IMAGESET

**Comment by garfield69** [comment]
RarBG provides an API service at https://torrentapi.org/ for apps to fetch search results. (The RarBG.to web site actively prevents apps web scraping the site).

The RARBG API server appears to have no new results since the start of Feb 01.

I can get search results for episodes prior to this date (Arrow s07e11, Black Lightning s02e11, Magnum P I s01e14) but not for (The Flash s05e12, Riverdale s03e11, The Magicians s04e02, Vikings s05e20) although I can get previous episodes (The Flash s05e11, Riverdale s03e10, The Magicians s04e01, Vikings s05e19)

Nothing to do but wait to see if it gets fixed. In the mean time you can try switching to another DuckieTV search engine.

I've sent an email to support@rarbg.to but I dont know if this will get a response.

**Comment by garfield69** [comment]
support@rarbg.to have responded and solved the issue, your RarBG searches should be back to normal now.

**Comment by faulander** [comment]
thanks for the reply and your intervention. 1 day in your case is bearable - in my case it's already 8 days without an update ...

**Comment by faulander** [comment]
didn't see your last comment - it works again! thanks so much for your help! :)
