### ISSUE TITLE
[QXR] Incexer shows every torrent available

### ISSUE THREAD

**Issue by angelss197200** [Jackett/Jackett#4724]
QXR indexer dont searh, just show every torrent available(2855 aprox). This causes performance issues in browser

 Jackett Version 0.10.796.0

**Comment by garfield69** [comment]
that is how they have designed their website. it dumps the whole library then filters the results.
nothing i can do to improve the indexer.

**Comment by ldexterldesign** [comment]
I discovered this issue today and won't be using the indexer because it clutters results

Admittedly I should have discovered the issue sooner but IMHO if the indexer didn't exist I wouldn't have installed and spent 30 minutes diagnosing why I'm getting hundreds of pointless results in Sonarr

Regards

Ping #2980
