### ISSUE TITLE
[zooqle] Exception (zooqle): Request to https://zooqle.com/search?s=dt

### ISSUE THREAD

**Issue by DarExc** [Jackett/Jackett#4766]
I think zooqle may now require a login ID for RSS feeds.

An error occured while testing this indexer
Exception (zooqle): Request to https://zooqle.com/search?s=dt&v=t&sd=d&q=%20* failed (Error Forbidden) - The page is protected by an Cloudflare reCaptcha. The page is in aggressive DDoS mitigation mode or your IP might be blacklisted (e.g. in case of shared VPN IPs). There's no easy way of making it usable with Jackett.: Request to https://zooqle.com/search?s=dt&v=t&sd=d&q=%20* failed (Error Forbidden) - The page is protected by an Cloudflare reCaptcha. The page is in aggressive DDoS mitigation mode or your IP might be blacklisted (e.g. in case of shared VPN IPs). There's no easy way of making it usable with Jackett.

**Comment by garfield69** [comment]
no. 
what is happening is that Zooqle is under a DDOS attack, and their service provider Cloudflare have enabled anti-DDOS measures, which involve a intermediate page which requires a human to solve a captha challenge to prove its not a bot accessing the site.
However, this means that Jackett is prevented from accessing Zooqle since the captcha cannot currently be solved with automation.
So until the attack is over and cloudflare lift the protection, you cannot use Jackett with Zooqle.

**Comment by DarExc** [comment]
Ah, that's great, thanks a lot for the quick response!
