### ISSUE TITLE
Kinozal + Sonarr

### ISSUE THREAD

**Issue by arwnd** [Jackett/Jackett#4767]
Indexer don't have russian convertation map for series and episodes (like as nnm-club), and queries get empty results.

Jackett Version 0.10.828.0

**Comment by imm21** [comment]
The search by season and series does not work. Most likely because the kinozal and nnm-club have different formats for creating titles. 

For example

NNM-CLUB: Настоящий детектив / True Detective (2019) WEB-DL [H.264/1080p-LQ] **(сезон 3, серии 1-8 из 8**) TVShows

KINOZAL: Настоящий детектив (**3 сезон: 1-8 серии из 8**) / True Detective / 2019 / ПМ (Novamedia), СТ / WEB-DL (1080p)

They have a different format of the season and series: (сезон 3, серии 1-8 из 8) and (3 сезон: 1-8 серии из 8). 

Thank you.

![2019-03-13](https://user-images.githubusercontent.com/10806691/54269882-cbf67c80-45b0-11e9-85a3-e00f8567570b.png)

**Comment by imm21** [comment]
In sonarr does not work, I think because of the brackets in the results. :)

(S03E01-08)

**Comment by garfield69** [comment]
try out jackett pre-release v0.11.45 and see if were getting closer to signing this one off ;-)

**Comment by imm21** [comment]
Still does not work, do not even know why.

**Comment by garfield69** [comment]
I've moved the season/episode to the end of the title, and a few other tricks to get kinozal to return results that Sonarr can digest. try out pre-release 0.11.48

**Comment by imm21** [comment]
It works! Thank you very much!

**Comment by imm21** [comment]
Lastly. It would be great to remove the zeros from the seasons and series, including the nnm-club (just S1E1) and add the replacement "Кубик в Кубе" to "Kubik".

Thank you! :)

**Comment by garfield69** [comment]
try out jackett v0.11.53

**Comment by imm21** [comment]
strange things. when searching in the sonarr by the nnm-club and kinozal in the list shows the series are unknown, but when searching by rutracker this does not happen, although the series are visible in both cases. I think that the automatic search will not work, but thanks anyway!
![2019-03-16](https://user-images.githubusercontent.com/10806691/54465743-47be1800-47af-11e9-91c9-fd696e52f839.png)

**Comment by garfield69** [comment]
that's because rutracker  takes
`Лучше звоните Солу / Better Call Saul / Сезон: 4 / Серии: 1-10 из 10 (Винс Гиллиган, Адам Бернштейн, Томас Шнауз) [2018, США, драма, криминал, WEBRip 720p] MVO (AMS) + Original`
and returns `Better Call Saul - S4E1-10 - rus WEBRip 720p MVO (AMS) + Original`
so its dropping the year which i think causes sonnar issues because it does not like the torrent year in the title not matching what it thinks is the series published year.

I can try applying the same rutracker logic to nnm-club and kinozal and see what happens.

**Comment by imm21** [comment]
I will wait thank you

**Comment by garfield69** [comment]
try out jackett pre-release v0.11.56

**Comment by imm21** [comment]
looks like it works. ran into a couple of problems:

when searching for a game of thrones, I get an empty result in sonarr, but in the Jackett I get the result. if i disable the nnm-club in sonarr - results are displayed. with other serials this is not.

trying to search for "miracle workers", I get the result, but again I come across unknown series, now it concerns all the results. there is nothing suspicious in sonarr logs. maybe a sonarr bug?

**Comment by garfield69** [comment]
if a sonarr indexer stops returning results then that usually means that sonarr has disabled that indexer because of perceived errors (usually because the indexer took too long to respond).
you can reactivate the sonarr indexer by going to the sonarr setting indexer and editing the indexer and doing a test and save.

I get results for GOT 

I don't know why miracle workers is being flagged as unknown series, other than the fact that there are two series with the same name, the 2019 and a previous version in 2006. perhaps in this case sonarr is looking for the 2019 to tell them apart and because we are stripping the year its confused.
catch 22. 
We are trying to shoe horn non English trackers with different torrent naming schemes to fit an English naming standard that sonarr wants to work with. we are not going to get a perfect match for every series.

**Comment by imm21** [comment]
no, there are no results from the nnm-club in sonarr, and according to the GOT, results from any trackers are output if nnm is activated at the same time in any other series, requests with the nnm-club are displayed. Mystic.

Tracker exactly working :)

I make a query in jackett "Game of Thrones S06" and get 136 results consisting of all seasons in the nnm-club. Maybe this is the problem?
