### ISSUE TITLE
Jackett Won't Update on Synology

### ISSUE THREAD

**Issue by anBlair** [Jackett/Jackett#4858]
The version available through the official SynoCommunity channel is 0.8.490-6. This isn't a big deal, as Jackett has an auto updater. However, the update is failing with this new release.

The log gives me the error message:
"Cannot open assembly '/tmp/JackettUpdate-v0.11.8-636878440573584310/Jackett/JackettUpdater.exe': No such file or directory."

After logging this, Jackett crashes.

In going and looking in /tmp, the package was successfully downloaded. However, the file that I _suspect_ is supposed to have the .exe extension just doesn't have it. I'd love to rename the file, but on restarting Jackett, it then removes the files from /tmp/JacketUpdate-v0...

**Comment by flightlevel** [comment]
Didn't think about this scenario. Essentially if your Jackett version is more than 2 months old, the self updater is broken due to the simplistic logic we previously had https://github.com/Jackett/Jackett/commit/a90ed2601a632b1ca78527dc776f9c205ecd51e8#diff-6df16c457c13864865c44ee4079eba57L226

We don't maintain the Syno package, have logged an issue here though: https://github.com/SynoCommunity/spksrc/issues/3653

Workarounds in the meantime, Stop Jackett, Download the latest release here: https://github.com/Jackett/Jackett/releases/download/v0.11.8/Jackett.Binaries.Mono.tar.gz Copy the files over the top of your current ones. Start Jackett and you will be on the latest version and the updater will now function correctly. Other option, if you have Docker on the Synology would be to use that

**Comment by anBlair** [comment]
Where exactly in the filesystem do the files from that tar go? I can't say I've ever put the time in to figure out Docker.

**Comment by bolhaskutya** [comment]
@anBlair 
The syno package is being fixed. You can download the new Mono and Jackett at the link below. Please report back there if it is working. Thanks.
https://github.com/SynoCommunity/spksrc/issues/3470#issuecomment-470410393

**Comment by jeremymeyers** [comment]
@defaultsecurity is there a person at synocommunity you talked to in order to get it fixed? it still at 0.16

**Comment by defaultsecurity** [comment]
@jeremymeyers
No need. Here is the latest package below, it is working and does not require mono. By default it is version v0.16.979.0, but it can currently be updated to v0.17.284 using the Jackett's internal updater.
https://github.com/SynoCommunity/spksrc/issues/3697#issuecomment-671318950

**Comment by jeremymeyers** [comment]
@defaultsecurity looks like they did it on the syno side too https://github.com/SynoCommunity/spksrc/issues/3797#issuecomment-761620509

**Comment by defaultsecurity** [comment]
@jeremymeyers
Great find! Although those releases still require mono. Jackett has a standalone version, which is preferable, but not required. Nevertheless Jackett's internal updater works perfectly in those releases as well.
