### ISSUE TITLE
[REQ] BTDigg DHT Tracker

### ISSUE THREAD

**Issue by zero77** [Jackett/Jackett#4907]
Tracker Name : BTDigg
Public tracker
Supports: magnet
Indexer URL : https://btdig.com/
Indexer language : English

https://github.com/btdig/dhtcrawler2

**Comment by zero77** [comment]
@garfield69 
Thanks

**Comment by garfield69** [comment]
currently returning ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
the btdigg server is actively processing fetch-metadata request headers in order to determine if the search request came from a browser/user interaction or a bot like jackett.
https://w3c.github.io/webappsec-fetch-metadata/#fetch-metadata-headers describes the process.

the sec-fetch-* metadata headers are secure headers, meaning they cannot be set by javascript apparently

the point being that I cannot find a way to make btdigg accept jackett's search requests and currently get a bad-gateway response when I try. 
I've tried setting user-agent, accept and accept-encoding headers but this does not help.
I cannot be bothered spending anymore time trying to get this to work.
so I am going to remove this indexer.
if someone else wants to have a go they can submit a PR to reinstate the indexer with the working code.

**Comment by zero77** [comment]
@garfield69 
Thanks for having a look.

**Comment by conferno** [comment]
> the btdigg server is actively processing fetch-metadata request headers in order to determine if the search request came from a browser/user interaction or a bot like jackett.
> way to make btdigg accept jackett's search requests and currently get a bad-gateway response when I try.

No, it does not try to filter out the bots.
Likely, your experiments interferred with server heavy load or backend's restart.

**Comment by conferno** [comment]
Ah, I found the issue.
There is nothing against `Jackett` or bots in general, just matched the `Jackett` access pattern with the abuse massages and dmca sent by policy enforcers after the visits.
So while those annoyng bots are leveraging `Jackett` in their work, `Jackett` will likely get 502 error in response.
Sorry.

**Comment by garfield69** [comment]
@conferno  Oh I see. Thanks for looking into this.

So because Jackett does 5 HTTP GETs per search request, in order to fetch up to 50 torrents per search, we are tripping the anti-bot protection.
In that case I will add the BTDIGG indexer back in, but drop the multi page requests, and restrict it to using the one search request, and be satisfied with the 10 results we get back. 
its better than nothing ;-)
Jackett 0.11.709 restores the modified btdigg indexer.

**Comment by ilike2burnthing** [comment]
https://btdig.com/ redirects to https://archive.ph/

Onion site still up.

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
note that both alternate domains are not working. I check the original onion link on a TOR browser and it is not working
check back in a month and drop those alternates if still down.

**Comment by garfield69** [comment]
using the TOR browser to get to the .onion link worked this time, however the certificate is invalid (domain)
but the site was btdigg and searching for 2022 returned results.
however the *.ly and tor2web.to alternate links still do not work on the regular browser, perhaps due to the invalid CA
adding a certificates to the indexer, and switching to http did not help the indexer get results.

**Comment by garfield69** [comment]
the onion alternates are both working again.

**Comment by garfield69** [comment]
onion alternates are not working again, same reason as described in https://github.com/Jackett/Jackett/issues/4907#issuecomment-1356111189

**Comment by garfield69** [comment]
well that did not last long. https://btdigggink2pdqzqrik3blmqemsbntpzwxottujilcdjfz56jumzfsyd.tor2web.link/ Origin is unreachable Error code 523

**Comment by ilike2burnthing** [comment]
Looks like https://tor2web.link/ itself is down. Hopefully not for long.

**Comment by ilike2burnthing** [comment]
https://btdig.com/ - ERR_CONNECTION_CLOSED
Only up for 10 of 42 Uptrends checkpoints.

**Comment by garfield69** [comment]
32 of 43 uptime now online, working for me.

**Comment by garfield69** [comment]
BTDigg has started actively blocking Jackett and Prowlarr traffic from linux platforms. 
This follows a period in March https://github.com/Jackett/Jackett/issues/14198#issuecomment-1491806580 which went on until August. While windows traffic is a smaller percentage of total Jackett users, linux (via docker or native) is a much larger user base.
There seems little point trying to access this site from Jackett so I shall remove this indexer.

**Comment by garfield69** [comment]
v0.21.867

**Comment by Hrxn** [comment]
Not down for me at the moment, is there some dark magic going on?

**Comment by RileyXX** [comment]
> BTDigg has started actively blocking Jackett and Prowlarr traffic from linux platforms. This follows a period in March [#14198 (comment)](https://github.com/Jackett/Jackett/issues/14198#issuecomment-1491806580) where just windows was blocked which went on until August. While the windows traffic is a smaller percentage of total Jackett users, linux (via docker or native) is a much larger user base. There seems little point trying to access this site from Jackett so I shall remove this indexer.

Should leave the indexer in jackett so windows users can use it atleast. I don't see the reason for removing it entirely if it is still working for some users. It may start working again for linux at some point like it was previously with windows.

**Comment by ilike2burnthing** [comment]
We're not always able to directly communicate with site owners/admins, and in those cases we take hints that we're not wanted. This is one such case.

**Comment by RileyXX** [comment]
Jackett features & user experience should take priority over uncooperative site owners/admins. 

If they want to attempt to block jackett traffic entirely then so be it, but if it still working for some users why not just leave it and let the user decide if they want to use it.

**Comment by ilike2burnthing** [comment]
Our userbase (and by extension, that too of Prowlarr) is large enough that we have the ability to (accidentally) DDoS sites. If a small site that is useful to the community, but is just being run off a NAS in someone's bedroom, is taken offline due us being wilfully ignorant, that serves no one. 

We do not have an adversarial approach to trackers, where possible we want to work with them, improve the experience of their users, and we have made plenty of changes in the past to accommodate their needs.

If there's no easy way to communicate with site owners/admins, and we run into some change that stops Jackett from functioning properly (e.g. blocking our UA or a `latest` page), we will generally try to work around this a few times (as steps like these can often be automated rather than purposeful), but after after several attempts we will take the hint and remove the indexer.

**Comment by return42** [comment]
FYI we have the same problem .. you can track it here:

- https://github.com/searxng/searxng/issues/3068#issuecomment-1868478012
