### ISSUE TITLE
[ImmortalSeed] Exception (ImmortalSeed): Value cannot be null.Parameter name: uriString: Parse error (Config)

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#4956]
I get the following error message when trying to configure ImmortalSeed:
Exception (ImmortalSeed): Value cannot be null. Parameter name: uriString: Parse error

Enhanced log:
[log.txt](https://github.com/Jackett/Jackett/files/3000710/log.txt)

**Jackett version**: 0.11.115.0
**Mono version**: N/A

**Comment by garfield69** [comment]
Hmm. looking at the logs it seems you logged in OK and got a browse response back full of torrents.
and pairing the selectors with the html by eye it would appear all still matches.
so I've switched to https (since this seems to be the preferred method in all the links within the html) and added a bunch of missing categories.
So try out Jackett pre-release v0.11.134 and see if it works now.
If it still fails then I will need an invite sent to garfieldsixtynine @ gmail.com to properly research the issue.

**Comment by ldexterldesign** [comment]
Hey @garfield69,

> I've switched to https (since this seems to be the preferred method in all the links within the html) and added a bunch of missing categories

Just trying to help diagnose this issue...

Bit confused what you've done here - where have you made this switch because both the latest release configs look the same?:

<img width="1440" alt="Screenshot 2019-03-25 at 15 09 06" src="https://user-images.githubusercontent.com/1715809/54926263-38a63b00-4f10-11e9-9b9b-bf5be1746871.png">

Hope to hear back

Cheers

**Comment by kaso17** [comment]
fixed via c830a59d58e1d0b63decc76b84f3c1588aec9ed7

**Comment by RoloSoze** [comment]
@kaso17 Thank you, and welcome back!

**Comment by garfield69** [comment]
@ldexterldesign  huh? I dont know what you were looking at but my changes are detailed in https://github.com/Jackett/Jackett/commit/6d23341f06d05edb1d016fc56ca629305cd43c6f
anyway its acedemic now since kaso17 fixed the issue correctly (always helpful to have a login so you can see and test for yourself :-) ).

**Comment by ldexterldesign** [comment]
@garfield69

> So try out Jackett pre-release v0.11.134 and see if it works now

You implied / I inferred your changes were in a release so my screenshot is a comparison of the latest two releases (inc. v0.11.134) where there are, evidently, no changes to the immortalseed configuration

I did think it was strange you were referring to an old release, considering v0.11.136 exists

I should have known what you meant but it would have been far clearer if you'd have mentioned your commit in your original comment, as you did in your last comment

Cheers
