### ISSUE TITLE
No "Apostrophe" in french search.

### ISSUE THREAD

**Issue by sbeaudoin** [Jackett/Jackett#4974]
Trying to search for movie "l'exorcisme de hannah grace" from sonarr return nothing with jackett 0.11.115.0 targetting indexer "Torrent9".  But if I search from the jackett web interface, it finds many results.  The log indicate the search string used from sonarr is "l exorcisme de hannah grace", note the missing single quite after the "l".

**Comment by garfield69** [comment]
don't see what this has to do with Jackett. the problem is with Sonarr. Let me expand.
Torrent9 the website strips the apostrophe when searching.
So searching `l'exorcisme de hannah grace` gets the same results as `lexorcisme de hannah grace`
and the Jackett Dashoboard returns the same results.
The problem is that Sonarr asks Jackett to use `l exorcisme de hannah grace` and with the space instead of the apostrophe the torrent9 site returns nothing. And so does Jackett.
