### ISSUE TITLE
EliteTorrent.biz Error when searching something without results

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#5009]
EliteTorrent.biz Error when searching something without results
```
Error on 20190401232629 for EliteTorrent.biz.txtJackett.Common.ExceptionWithConfigData: Error: No se han encontrado resultados para "sublime text"
						
							Asegúrese de que todas las palabras estén escritas correctamente.
							Pruebe con diferentes palabras clave.
							Prueba palabras clave más generales.
```
Latest version

**Comment by garfield69** [comment]
this is by design.
https://github.com/Jackett/Jackett/blob/859da99442c6ff95d4731b31f1e3a3c23d71428d/src/Jackett.Common/Definitions/elitetorrent-biz.yml#L41-L45

without the error trap, elitetorrentbiz returns "you may like the following" in response to a failed search
![image](https://user-images.githubusercontent.com/6933240/55364469-3ca01180-553d-11e9-903c-ee6d391b40c6.png)
![image](https://user-images.githubusercontent.com/6933240/55364494-5b060d00-553d-11e9-82a6-9fdc0fb408b5.png)
