### ISSUE TITLE
[torrentleech] Exception (torrentleech): Object reference not set to an instance of an object: Parse error (Config)

### ISSUE THREAD

**Issue by pazwicker** [Jackett/Jackett#5094]
Both Radarr and Sonarr returned a tracker error for torrentleech. I verified that I can log into torrentleech's site, but multiple tests through Radarr, Sonarr, and Jackett yield errors. I have not had an issue with torrentleech before up until now. I'm running version 0.11.228.0.

Thanks!
[log.txt.20190417.00002.txt](https://github.com/Jackett/Jackett/files/3092948/log.txt.20190417.00002.txt)

**Comment by garfield69** [comment]
as you may know, for torrentleech we process a json block provided by the site instead of the usual method of scraping the HTML search results page.
but there is something different in the json currently returned that we are not expecting, and the processor is flagging an exception.
I'll try to step through the json data and see if I can figure out what tripping the json parser.

**Comment by garfield69** [comment]
I can replicate this at the moment.
is it still happening to you?
if it is, can you please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

**Comment by pazwicker** [comment]
The issue is no longer happening for me. Nothing changed, it just all of a sudden started working again.

Thanks for your help! I will follow up if the issue pops up again and include a full enhanced log file.
