### ISSUE TITLE
Season pack found only 1 out of available 6 indexers

### ISSUE THREAD

**Issue by syluccy** [Jackett/Jackett#5147]
Jackett Version 0.11.256.0
Mono Version 5.20.1.19

-------------------------------

I'm using Sonarr and I’ve found out there are couple of tvshows, which aren’t downloaded, even though I know they are available on several indexers, I use.
Started to test it, by searching on jackett, and Sonarr with manual search.

For instance, I searched for American Crime Story - 2x09.

![Sonarr](https://forums-sonarr-tv.s3.dualstack.us-east-1.amazonaws.com/original/2X/7/754613b1dcdff8383e4fdc916aeba9c2bef36ccd.png)

And here is Jackett, foundig it much more indexers.

![Jackett search](https://forums-sonarr-tv.s3.dualstack.us-east-1.amazonaws.com/original/2X/b/b0d27a44d5ad7f1596a938ce3c27bcc0b32daf5d.png)

For some reason everytime I tested it, Sonarr found full seasons only at Morethan TV. :confused:
The reason, why I think Jackett might be mistaking is, the logs showing results only for MoreThanTV

![Jackett logs](https://forums-sonarr-tv.s3.dualstack.us-east-1.amazonaws.com/original/2X/a/a68c182ce909e81c97cdb38f5878c82a35ed68ef.png)

Btw…in other cases these indexers work well, so it shouldn’t be an indexer configuration problem.

![Episod search](https://forums-sonarr-tv.s3.dualstack.us-east-1.amazonaws.com/original/2X/8/864a137f3005c942cf442d6ed0c2df86d97b75a4.png)

**Comment by syluccy** [comment]
could anyone responsible respond to this? :)

**Comment by syluccy** [comment]
@garfield69 I saw your activity in other tickets. Could you please help me about this?

**Comment by garfield69** [comment]
Since I do **not** have accounts on Nebulance, PrivateHD, nCore, BitHUmen, or UHDBits, I am unable to research into this myself.

I think a research path you can try is the following: 
1.  enable **enhanced** logging on jackett
  - access your jackett dashboard
  - scroll to the bottom
  - click to tick the **enhanced logging** check box
  - scroll up a bit 
  - click on the **apply server settings** button
2.  now perform your search on Sonarr as you did in your first post.
3.  then open all the log.txt in a plain text editor and search for the search Urls being used for each indexer. 
- the log entries search Urls you are interested in looks similar to 
`WebClient(HttpWebClient).GetString(Url:https://1337x.to/sort-search/american%20crime%20story%20s02e09/time/desc/1/)`
- in the example above, the part you want to keep aside is the http(s) Url 
`https://1337x.to/sort-search/american%20crime%20story%20s02e09/time/desc/1/`
- The log.txt files should be stored in `%ProgramData%\Jackett` on Windows and `~/.config/Jackett/` on Linux/macOS.
- (note, you may need to look at the other log.txt.* split files, to collect all the search Urls being used. 
4.  then with your browser login to each of the five web sites directly, and paste the jackett search Urls you collected for each site in turn in the address box of the active web session of the corresponding website and take a look at what that search result generated. 

if you can show that those search Urls produce search results on the websites, and that jackett did not show results for those indexers, then you have a case for us to look into this further.

if however, those search UIrls do not produce results on the websites directly, then this is a case of how Sonarr does its search requests via Jackett, and I don't think there is anything the Jackett team can do to help with this.

**Comment by syluccy** [comment]
I don't think that would be the solution.

https://www.morethan.tv/torrents.php?searchstr=American+Crime+Story+S02E09&tags_type=1&order_by=time&order_way=desc&group_results=1&action=basic&searchsubmit=1

<img width="1155" alt="Screenshot 2019-05-28 at 21 17 37" src="https://user-images.githubusercontent.com/8645712/58505975-88161b00-818e-11e9-81e8-aedc6cdc2ef8.png">


https://www.morethan.tv/torrents.php?searchstr=100+S06E04&tags_type=1&order_by=time&order_way=desc&group_results=1&action=basic&searchsubmit=1

<img width="1136" alt="Screenshot 2019-05-28 at 21 17 48" src="https://user-images.githubusercontent.com/8645712/58505997-95cba080-818e-11e9-8cb6-1a376690a339.png">

As you can see, the American Crime Story search didn't go through, unlike the The 100, which has separate episodes on the tracker.
And we know, that American Crime Story is working on MoreThanTV.

How about this ticket?

https://github.com/Jackett/Jackett/issues/1813#issuecomment-337302685

Seems to be very similiar, and @kaso17 seems to be added something special feature for MoreThanTV. Did he?

**Comment by garfield69** [comment]
The **research** I asked you to do was not a **solution**, but simply an effort to find out what sonarr is asking jackett to do.

what you just provided is a single episode search for MTV, which does not show how sonarr was able to find ACS s02 on MTV via jackett.

you need to find the search url that sonarr caused jackett to create when searching for ACS on MTV, and then show that a similar Url search on one of the other sites was made.

**Comment by syluccy** [comment]
Sorry, I wasn't available for a while.
Can I send you the full logs? Cause I can't find anything like you said.
I'm not sure if those logs contain anything private.

**Comment by morpheus133** [comment]
Because several sites use only season packs instead of single episodes.
Eg. the release what you searched for only in seasonpacks in ncore and in bithumen.
And none of these indexer give seasonpack as a result for an episode search. (And Sonarr not support to download one episode from pack so this has no meaning...)

**Comment by RoloSoze** [comment]
> 
> 
> Because several sites use only season packs instead of single episodes.
> Eg. the release what you searched for only in seasonpacks in ncore and in bithumen.
> And none of these indexer give seasonpack as a result for an episode search. (And Sonarr not support to download one episode from pack so this has no meaning...)

@garfield69 All but one (BitHUmen) of these trackers now have active maintainers. Should this issue be looked at or does the comment above address it?

**Comment by garfield69** [comment]
I think morpheus133 hit the nail on the head.
if the web site that the indexer is searching only provides for some series the season packs instead of individual episodes, then there is nothing jackett can do about it.
