### ISSUE TITLE
[REQ] Add coldfilm new public tracker

### ISSUE THREAD

**Issue by SuberSeb** [Jackett/Jackett#5228]
Coldfilm is a popular russian tracker. It has a lot of TV shows and this tracker release new episodes very quickly.

http://coldfilm.biz/

**Comment by garfield69** [comment]
does coldfilm provide torrents?
I am unable to find torrents search page.
if it only provides watch-online then it is not suitable for inclusion as a Jackett indexer.

**Comment by SuberSeb** [comment]
Yes, there are torrents. They are under the video.

**Comment by garfield69** [comment]
this site is not suitable for processing by the cardigann processor. the indexer will need to written in c#
this is because there are multiple torrents links in each entry's details pages, one for each quality, eg 1080p 720p 400p etc.
also movies in particular are subject to copyright removal and may not have any download links at all.

**Comment by SuberSeb** [comment]
Can any of C# devs add this indexer? It has a lot of tv shows.

**Comment by garfield69** [comment]
Closing as unsuitable for indexing. Refer https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker#what-makes-a-site-suitable-or-not-suitable-for-indexing
