### ISSUE TITLE
[xktorrent] Exception (xktorrent): Error: L′atribut username est requis.: Parse error (Test)

### ISSUE THREAD

**Issue by valentinbourqui** [Jackett/Jackett#5294]
connect on the website with "save my login" activated. 
Copy/past full cookie : laravel_cookie_consent=1; remember_web_ ......
Connection successful but after a few hours/days connection gone wrong with this error. This is not the first time. If I put back cookie it's working again then again I receive this exception.

 **Jackett version**:  0.11.340.0
 **Mono version**: 2.18.0.240-12

-------------------------------

**Comment by garfield69** [comment]
that is normal with some cookies, which expire and have to be renewed.
but since xktorrent have dropped their cloudflare protection at the moment, you should be able to login using your username/password.
but first you will need to upgrade to jackett v0.11.348
after which edit your xktorrent config on your jackett dashboard, and you should be able to save your username/password instead of a cookie.
