### ISSUE TITLE
Can’t connect to siambit through jackett

### ISSUE THREAD

**Issue by xpirat** [Jackett/Jackett#5296]
No connection to siambit through jackett

**Comment by xpirat** [comment]
It worked the first couple of days. But not working anymore

**Comment by garfield69** [comment]
works for me.
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

**Comment by garfield69** [comment]
now that my **VIP** account has expired and I am a **normal** user now, I'm getting 0 results on my search.
@xpirat  I assume this is what you meant by `No connection to siambit through jackett` although your comments are not clear to me.

I'm not seeing results because for normal users the download link is no longer available on the results page, but only on the details page for each torrent.
I'll code a solve once I also figure out how to resolve the say_thank click that needs to happen before downloads are allowed.

**Comment by garfield69** [comment]
with jackett pre-release v0.11.358 you should at least be able to do searches again.
but the download link is still yet to be fixed.

**Comment by xpirat** [comment]
Yes that’s exactly what happened to me to. When my VIP expired. 

So we are experiencing the same issue, so I will not give log as you answered my late answer :p

Ps: keep up the good work my friend :)

**Comment by garfield69** [comment]
jackett pre-release v0.11.362 should have working download links.
