### ISSUE TITLE
Operation cancelled for Sonarr and Radarr

### ISSUE THREAD

**Issue by sljdhl** [Jackett/Jackett#5320]
Hi, im getting similar problems to this: https://github.com/Jackett/Jackett/issues/5067, operation canceled in jacket and sonarr+radarr says "All rss-capable indexers are temporarily unavailable due to recent indexer errors". Restarting the docker container works for a short time.

Jackett logs: https://pastebin.com/zVsVVJcn
Jackett docker stats: https://pastebin.com/wjMfxZyL

It doesnt seem to be any memory limit problem right?

**Comment by sljdhl** [comment]
anyone?

**Comment by ngosang** [comment]
@sljdhl Is this fixed?
Sonar makes requests to all indexers every few minutes. If one of the indexers fails, Sonarr stops making requests to that indexer for some time.

**Comment by sljdhl** [comment]
@ngosang No, atm the indexer fails

**Comment by ngosang** [comment]
Which indexers do you have configured?
Are you adding them in Sonarr one by one or all together using the `all` indexer?

**Comment by sljdhl** [comment]
in jackett? Asgaard, Nordicbits, nyaa,si and superbits. The other trackers have never failed. The ones I use in sonarr are added separetly.

**Comment by ngosang** [comment]
The error `The operation was canceled` happens when the site is down or slow. Some trackers are not reliable and we can't do anything about that.
I recommend you to add 5-10 trackers in Sonarr because they can fail. I think Sonarr tries to connect again after a while to failed trackers and if they are working, it hides the error.
May I close?

**Comment by sljdhl** [comment]
ok I'll add more trackers, thanks for the help! You may close
