### ISSUE TITLE
[torrentseeds] Error: Username or password incorrect (Config)

### ISSUE THREAD

**Issue by popookitty** [Jackett/Jackett#5339]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

(At the bottom of your Jackett Dashboard page) **Jackett version**:  
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**:

-------------------------------

Despite logging in successfully the first two times ive changed the password, I still get this error

**Comment by garfield69** [comment]
works for me. 
what version of jackett are you on and what platform?
you say you have changed the password....you mean you changed it using your browser on the torrentseeds website?
have you logged out of that account since making the change, and logged back in to confirm all is ok?
Once you have done that, then edit your jackett torrentseeds config and use the new password and click OKAY.
