### ISSUE TITLE
[transmithenet] Exception (transmithenet): String was not recognized as a valid DateTime.: Parse error (Test)

### ISSUE THREAD

**Issue by poplolnman** [Jackett/Jackett#5496]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.

none

2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.

latest

3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

https://pastebin.com/J3udjEmc

(At the bottom of your Jackett Dashboard page) **Jackett version**:  v0.11.420
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**:

-------------------------------

**Comment by garfield69** [comment]
there is a setting called *time style* in your profile.
try changing it to the alternate option.

**Comment by gribboa** [comment]
> there is a setting called _time style_ in your profile.
> try changing it to the alternate option.

This worked for me.

Username > Settings > Time style > Display times as date and time (time since is displayed as tooltip)

**Comment by garfield69** [comment]
can someone with an account on nebulance try out jackett pre-release v0.11.428, to check that my latest change can handle both date option settings? thanks.

**Comment by mouzzampk2014** [comment]
Hi, thank you so much for looking into this. Is .428 already out?

**Comment by garfield69** [comment]
its a pre-release. what platform are you on? (win, linux, macos). if linux, using docker?

**Comment by mouzzampk2014** [comment]
Linux docker

**Comment by garfield69** [comment]
a bit complicated for docker users to test a pre-release. 
https://hub.docker.com/r/linuxserver/jackett/ has instructions someplace about pulling a development version rather than the latest release.
but if you cant figure it out then you might be better off just using your browser to login directly to nebulance and setting Username > Settings > Time style > Display times as date and time (time since is displayed as tooltip)

**Comment by mouzzampk2014** [comment]
Hip hip hooray fixed. I just went to profile and changed the time. Thank you but I can use linuxserver/jackett:development too to pull the latest release which is very easy. Thank you so much dear. You guys always so helpful

**Comment by garfield69** [comment]
@mouzzampk2014  I don't have an account on nebulance which is why I released the fix as a pre-release.
if you could grab the docker development for .439 and test the nebulance setting both ways to prove that the jackett indexer works with either setting, then I can publish a full release which would be really helpful. thanks.

**Comment by mouzzampk2014** [comment]
Fixed I moved back Nebulance Time Settings to Display times as time since (date and time is displayed as tooltip) and then updated to development branch and its working fine. Thanks dear 

![4](https://user-images.githubusercontent.com/44548525/59968527-e71f4380-9532-11e9-842d-26481bfdced0.JPG)

**Comment by garfield69** [comment]
thank you.
