### ISSUE TITLE
Torrents.csv

### ISSUE THREAD

**Issue by jriker1** [Jackett/Jackett#5539]
I am using DuckieTV with Jackett and when I click on their "i" icon it usually pulls up a webpage but there are some search results that when you click on "i" it doesn't open up a webpage, it opens up the option to open it in my torrent.  Best I can tell, even though in DuckieTV I'm not using it in the search results, it seems like Torrents.csv is the one causing this.  Did a manual search in Jackett and that one as closely as possible for seeds and leaches and that seems like it's the one that is causing this.

JR

**Comment by garfield69** [comment]
yes, the torrents.csv web site is a magnet crawler, and it does not have a details page for each of the torrents it returns in its results page. 
clicking on the titles on its web results page returns magnet links.
Although jackett uses the API provided by the site and processes the returned JSON, this jackett c# indexer is coded to present results in a similar way to the web site.
I will take a look at some of the other c# indexers and see if I can find out what they return when there is no details link.

**Comment by garfield69** [comment]
since the results returned by the site's API does not include a details or comments link, and the web site does not have one either, and returning a download link in its place is contrary to user expectations, we just link to the web site home page, because a link of some kind must be provided to conform to torznab specs.
pre-release 0.11.445 begins including this change.
