### ISSUE TITLE
Beyond-Hd category regex broken

### ISSUE THREAD

**Issue by zotanmew** [Jackett/Jackett#5603]
The beyond-HD category selector seems to be broken. I've been getting `System.Exception: Error while parsing field=category, selector=a[href*="/categories/"], value=<null>: Selector "a[href*="/categories/"]" didn't match` spammed in my journalctl log for the last week or so.

Jackett version: **0.11.463.0**:

**Comment by garfield69** [comment]
Looks like for some results in the torrent listing Beyond-HD have introduces a **Stream** play link  instead of the category field.
Searching with the browser directly on the site and filtering for the special **stream optimised**, it appears that only Movies qualify for Streaming, so I will alter the jackett indexer for this site to default the category to Movies when it finds the categories field is missing from the results.
fixed with jackett v0.11.471
