### ISSUE TITLE
[desireleasers] Exception (desireleasers): Error: The username field is required.: Parse error (Test)

### ISSUE THREAD

**Issue by mouzzampk2014** [Jackett/Jackett#5631]
Hi, everyday I have to copy the cookie value to let jackett successfully test. Is there anyway we can fix this issue. Thank you

**Comment by garfield69** [comment]
no there is not. they are expiring the session cookie daily. 
if their login did not have the i-am-not-a-robot check, then we would be able to use the user/pswd login which would resolve the issue.
but because that have the robot check, we use the cookie to bypass. however the session id is short lived, unfortunately.

**Comment by mouzzampk2014** [comment]
Thanks for the update
