### ISSUE TITLE
[mejortorrent] captcha

### ISSUE THREAD

**Issue by perikin88** [Jackett/Jackett#5632]
The page Mejortorrent seems to be using now a captcha, and for that reason the indexer is not working, returning always "Sequence contains no elements".

**Comment by garfield69** [comment]
i dont see a captcha. are you using http://www.mejortorrentt.org/ ?

**Comment by garfield69** [comment]
oh. they are forcing http:
i'll reverse PR #5583 

but we are still going to get no elements as one of the pages the indexer pulls http://www.mejortorrentt.org/secciones.php?sec=descargas&ap=contar_varios is empty which happens when the site has been down for a day or more. 
nothing we can about it but wait for the page to populate again.
the switch back to http will be included in the next release of jackett, when ever that gets published.

**Comment by tkdrob** [comment]
Don't we need a cookie field for this then?
