### ISSUE TITLE
Changing API Key everytime it updates

### ISSUE THREAD

**Issue by MiguelNdeCarvalho** [Jackett/Jackett#5747]
Hey, 
First of all I am using jackett running on Docker, and using WatchTower to update docker images automatically. Everytime it updates, API Key changes and I need to reconfigure sonarr and radarr again. Is it possible to make it like "static" or not changing after updating?
Thanks,
Miguel de Carvalho

**Comment by garfield69** [comment]
this means that you are not saving your config in a location outside of the docket package, so that when you upgrade your docker you wipe out your config and thus cause jackett to generate a new key.
Talk to the docker support people about the watchtower package.
The Jackett team has nothing to do with supporting the docker suite.
