### ISSUE TITLE
problems with l337x

### ISSUE THREAD

**Issue by Zhangsun321** [Jackett/Jackett#5777]
having problems with the 'codes' given to me to feed into my rss reader..

t=search&cat=100002,100001,100054&q= is returning me tv shows, when it should be just movies.

https://i.imgur.com/AemYspX.png  screenshot..    any link to the 'current'   # list?

**Comment by garfield69** [comment]
the problem is not with your categories.

the issue is that 1337x only adds the categories column for searches with keywords.
and since 1337x does not allow empty searches, we use the trending page https://1337x.to/trending when you request a search with no keywords. (this is geared to satisfying the TEST process for setting up the config since 1337x does not have a combined recent page that lists TV & MOVIES like most other sites.)

The trending page  currently does not have a categories column, which means jackett cannot filter out your rss search by category when you do not supply any keywords :-(
absolutely nothing we can do about this.

as for a link to the current categories list, access your jackett dashboard and edit the 1337x config. all the categories for that indexer are listed there.

**Comment by garfield69** [comment]
came up with an idea which I just tested successfully,
when an empty search is requested we can fetch the first page of both the movies library and tv library pages and present those combined results instead of the trending page.
these pages have categories, so your filter should work.
try out jackett pre-release 0.11.560

**Comment by Zhangsun321** [comment]
ok downloaded the prelease .560

went to install
https://i.imgur.com/zJHPJ7n.png  got that error... even ran in admin mode...   now going to download the latest pre release... as I assume it will include .560..

**Comment by Zhangsun321** [comment]
installed pre release and playing with it now... thank you so much :)
