### ISSUE TITLE
GazelleGames: adjusting the search

### ISSUE THREAD

**Issue by 07416** [Jackett/Jackett#5790]
The GazelleGames indexer commonly returns several hundred results, if the search term matches a torrent's file list the torrent is displayed. Additionally "ROM sets" (compilation of games for a platform and region) are problematic as thousands of games can be included

Can we at least get an option to search titles only?

- - -

 Jackett Version 0.11.566.0

**Comment by garfield69** [comment]
I don't have an account so I can't test this for myself.
but a look at this c# indexer shows that it using the *basic* search option.

if you provide the **full enhanced log** file
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at, I may be able to determine what additional search options to enable to restrict the search to titles only.

or you can wait for a c# dev with an account on GG to volunteer.
Thanks.

**Comment by 07416** [comment]
@garfield69 To clarify, this is not a bug in the indexer, Jackett just returns all torrents instead of the torrent groups, which aren't expanded on GGn.

Before providing a log file, can you tell if Jackett is able to search from titles only? This feature would entirely resolve the issue for me and likely others as well.

**Comment by garfield69** [comment]
>can you tell if Jackett is able to search from titles only? 

No I cant, since I have no idea what the GGn web site looks like, I have no reference to begin understanding what you really talking about.
The request for the enhanced logs was a way to start getting a handle on it, since the log would hopefully contain the html from the search request to GGn.

This indexer is written in C# and I am not a C# dev.
I specialise in the yaml indexers.
So unless the change is fairly simple, I usually pass it on to C# developers that can code properly.

The C# code for the GGn indexer looks fairly complex. 
Up to now, Kaso17 and flightlevel have been making updates to this indexer. 
But flightlevel has left github, and kaso17 does not contribute either.

The problem here will be waiting on a c# volunteer that has a login on GGn so they can properly code a solution and test it.

**Comment by 07416** [comment]
> No I cant, since I have no idea what the GGn web site looks like, I have no reference to begin understanding what you really talking about.

I meant in general, with all and every indexer, using syntax such as `title:`

GazelleGames search:

![Browse Torrents GazelleGames net](https://user-images.githubusercontent.com/14923168/69373545-b7749300-0cac-11ea-950f-d432bd0e358a.png)

I'm sure you get the gist now.

> This indexer is written in C# and I am not a C# dev.
> I specialise in the yaml indexers.
> So unless the change is fairly simple, I usually pass it on to C# developers that can code properly.
> 
> The C# code for the GGn indexer looks fairly complex.
> Up to now, Kaso17 and flightlevel have been making updates to this indexer.
> But flightlevel has left github, and kaso17 does not contribute either.

I see, I try to get the log ready with personal information removed.

**Comment by garfield69** [comment]
Jackett 0.16.1600
