### ISSUE TITLE
[thepiratebay] Irrelevant Search Results

### ISSUE THREAD

**Issue by aaronth07** [Jackett/Jackett#5802]
When adding TBP as an indexer in Radarr, I am getting some irrelevant search results. For example, searching 10 Cloverfield Lane (which was made in 2016), I get other movies made in 2016, but never actually 10 Cloverfield Lane (but when searching TBP itself there are a lot of results for that movie). Or when searching for Dragon Ball Z: Battle Of Gods, I get a lot of results with the same words in the title (such as Alita: Battle Angel or How to Train Your Dragon), or movies that came out the same year, but never the actual movie itself (even though when searching in TPB there are a lot of results for that movie).

I have tried with both search by title and remove year from search (within the Radarr settings) and the results are the same.

Logs: https://pastebin.com/e49egi0s

**Comment by garfield69** [comment]
The official TPB at https://thepiratebay.org/ does not have this issue.
And the Jackett Indexer only supports the official site.

this problem is a result of you using https://thepiratebay.asia/ which it appears, has a terrible search engine.

If you cannot use the official site then I suggest you find an alternate TPB proxy/mirror, one that works properly.
Try out any of the proxy/mirrors from the list at https://proxybay.app and see if any are accessible to you and if they do a better job.
