### ISSUE TITLE
[REQ] Immortus Life

### ISSUE THREAD

**Issue by TheUltimateC0der** [Jackett/Jackett#5815]
https://immortuos.life/

**Comment by garfield69** [comment]
Registration complete. Pending admin approval. 
Cannot login currently, getting Validation Error Credentials do not match.

**Comment by garfield69** [comment]
admin approval granted. login successful.

**Comment by garfield69** [comment]
a bit confused by the layout. I am unable to see a torrent listing or torrent search page?

**Comment by garfield69** [comment]
Oh wait. seems I am registered on the forum rather than the tracker?

I accessed https://immortuos.life/login and clicked on the ANIMELDEN link and that took me to https://forum.immortuos.live/member.php where I completed the registration.

but while I can login to https://forum.immortuos.live/ with my credentials, those credentials are no good at https://immortuos.life/login where I get {"username":["Diese Anmeldeinformationen stimmen nicht mit unseren Datensätzen überein."]}

I am Confused. Help.

**Comment by garfield69** [comment]
I suspect the tracker site registration is closed and registration is by invitations only.
the forum may be open but is hardly the useful in this case.

**Comment by FilmjunkieGF** [comment]
I requested this two moths ago https://github.com/Jackett/Jackett/issues/5588
If you could provide me an eMail I can send you a working account for the tracker (immortuos.life)!

**Comment by garfield69** [comment]
duplicate of #5588
