### ISSUE TITLE
Torrentdownloads isn't recognizing the "Movies" categories

### ISSUE THREAD

**Issue by crazy4ever** [Jackett/Jackett#5833]
Jackett says the categories "2000,100004" should be used for movies, but once i add them into Radarr as an Indexer and test them it gives me the message: 

> No results were returned from your indexer, please check your settings.

This test won't show up in the logs, even with "Enhanced logging" checked.

The TV categories "100008,5000" work normally, once i add them into Sonarr or Radarr the test succeeds and the indexer can be saved.

v0.11.566 Mono

**Comment by garfield69** [comment]
that's because torrentdownloads does not allow empty search strings.
So for TEST, instead of using https://www.torrentdownloads.me/search/ 
Jackett has to use 
https://www.torrentdownloads.me/today/

but here is the rub. 
torrentdownloads displays the first 100 results on the *today* page for each category, displaying TV first, Movies second, and other cats like music etc after.
but the torznab interface Radarr  uses to talk to Jackett has a default limit of 100 torrents.
so Radarr is never presented with the movie results because the first 100 are TV.

so here is what you need to do: bump the torznab limit to 200 so that Radarr can get some movies and pass the indexers test phase.

1. set the Radarr **advanced settings** to **show**
![image](https://user-images.githubusercontent.com/6933240/62849324-521b1880-bd33-11e9-9f70-af982d5e885c.png)
2. when adding torrentdownloads to your Radarr indexer,  
add `&limit=200` to your indexer's **additional parameters**
![image](https://user-images.githubusercontent.com/6933240/62849540-17fe4680-bd34-11e9-8b46-e4111246c343.png)

and away you go.
