### ISSUE TITLE
[vizuk] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by Shutruk** [Jackett/Jackett#5858]
Can't test or search for Vizuk's torrents.
I Can see and download everything from the website, not on jackett.

Jackett Version 0.11.598.0
Enhanced log attached

[log.txt](https://github.com/Jackett/Jackett/files/3504333/log.txt)

**Comment by garfield69** [comment]
It looks like the Jackett Vizuk indexer is set up for Spanish users.
Your Vizuk account profile would appear to be set to English, so the date parsing is miss-matched and fails to process the torrent search results.

I could try to adjust the indexer to handle both languages, but since I do not have an account I cannot test my changes and this makes it difficult to get it right.

try setting the language to Spanish and see if the indexer starts working.

Alternatively, if you can provide an Invite I certainly should be able to alter the Indexer to be dual language capable.

**Comment by Shutruk** [comment]
Changing the language to Spanish fixed the problem. Thanks man! If i get an invite I'll make you know.
