### ISSUE TITLE
can't search or rss specific indexer with sonarr any longer (other indexers work)

### ISSUE THREAD

**Issue by s0mm3rb** [Jackett/Jackett#5860]
**Jackett version**:  0.11.589.0
**Mono version**:   5.20.1.34
-------------------------------
jackett suddenly stopped providing results to sonarr only from https://dragonworld-reloaded.net
others work fine
maybe they changed something on their site?

radarr still works
but on sonarr i get:
`Invalid request Validation failed:`
`  -- No results were returned from your indexer, please check your settings.`

in jackett log I get messages like this
`Found 0 (1 new) releases from Dragonworld Reloaded`

I've updated both jackett and sonarr but still the same
regards

**Comment by garfield69** [comment]
From the Jackett dashboard, click on the TEST button for DWR.
if it works then the issue is with your Sonarr indexer. 
On the Sonarr Settings>Indexer panel, edit your DWR indexer and click on the TEST button.
if it works then try your Sonarr episode search again.

**Comment by s0mm3rb** [comment]
> From the Jackett dashboard, click on the TEST button for DWR.
> if it works then the issue is with your Sonarr indexer.
> On the Sonarr Settings>Indexer panel, edit your DWR indexer and click on the TEST button.
> if it works then try your Sonarr episode search again.

I already did that
it works for radarr but not for sonarr

this log is after testing in sonarr
notice the "Found 0" but "1 new" releases
I'd say that can't be right? 
but I don't know how you count that
> in jackett log I get messages like this
> `Found 0 (1 new) releases from Dragonworld Reloaded`

it just stopped working over night
since nothing has changed (no updates installed what so ever)
I can only imagine that there might have been a change on DWRs html?

regards

**Comment by garfield69** [comment]
fine.
Then please provide the **full Jackett enhanced log** file. 

with this I can at least see the html that DWR produces when Jackett sends a request and check that the Jackett indexer has the correct selectors for the results. The other debug messages in the log may also be useful.
But before performing the test, go into sonarr and disable all the other indexers apart from the jackett DWR. (in the Sonarr settings>indexers edit each indexer and set the RSS and Search options to OFF and save).
This will reduce the chaff so I get just the wheat off the DWR test ;-)

1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. perform a Sonarr search for an episode.
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

**Comment by s0mm3rb** [comment]
I don't know why but it works again -.-
just as suddenly as it stopped working ...

can I get the enhanced log of yesterday somehow?
there's only todays log in the folder

thanks for trying
I'll open a new issue if it happens again

regards

**Comment by s0mm3rb** [comment]
happened again

here's the log
https://pastebin.com/RAdRfXvJ

thanks
regards

**Comment by s0mm3rb** [comment]
this is the command sonarr invokes
`127.0.0.1:9117/jackett/api/v2.0/indexers/dragonworldreloaded/results/torznab/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100`

and this is the (pretty empty) response from jackett
```
<?xml version="1.0" encoding="UTF-8"?>
<rss version="1.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:torznab="http://torznab.com/schemas/2015/feed">
  <channel>
    <atom:link href="http://127.0.0.1:9117/jackett/" rel="self" type="application/rss+xml" />
    <title>Dragonworld Reloaded</title>
    <description>Dragonworld Reloaded is a GERMAN Private Torrent Tracker for MOVIES / TV / GENERAL</description>
    <link>https://dragonworld-reloaded.net/</link>
    <language>en-us</language>
    <category>search</category>
    <image>
      <url>http://127.0.0.1:9117/jackett/logos/dragonworldreloaded.png</url>
      <title>Dragonworld Reloaded</title>
      <link>https://dragonworld-reloaded.net/</link>
      <description>Dragonworld Reloaded</description>
    </image>
  </channel>
</rss>
```

thanks

**Comment by garfield69** [comment]
OK.
I've take a  look at the data you have provided and here is my analysis:
1. in response to Sonarr's request for the latest torrents, DWR returned 15 results, which contained 14 movies and 1 game.
2. since Sonarr DWR indexer is interested in only categories 5030 (TV/SD) and 5040 (TV/HD), Jackett returned an empty list.
3. the Jackett Indexer selectors are all up to date and match the HTML presented by DWR.

so the question is: has DWR always only ever returned 15 results per page for you?

Most sites allow you to change the default number or torrents returned in searches per page, by altering the torrents number in the account profile someplace...
Logon to DWR directly from your browser and check your profile settings.

You may be able to get DWR to return 100 results per page (a typical max setting on most sites), and that would increase your chances of getting at least one TV episode in the results returned.
But it is always in the realms of possibility, that if no one has uploaded any tv episodes to RWR within the most recent 15 (or 100) torrents, then Jackett and Sonarr are always going to find nothing, and that is perfectly normal.

**Comment by s0mm3rb** [comment]
it was the results per page settings
sorry...
