### ISSUE TITLE
(1337x)  An error occured while testing this indexer

### ISSUE THREAD

**Issue by newgithubuser2019** [Jackett/Jackett#5863]
Exception (1337x): certificate validation failed: [Subject] O=Internet Widgits Pty Ltd, S=Some-State, C=AU [Issuer] O=Internet Widgits Pty Ltd, S=Some-State, C=AU [Serial Number] 00F5BA2E609C91DBB4 [Not Before] 10/13/2014 4:46:03 PM [Not After] 11/12/2014 3:46:03 PM [Thumbprint] 5D8A25EB8B9C46981F007D105007113B97CA9BE6 : An error occurred while sending the request.
___________________________________________________________________________________________________
Jackett Version 0.11.608.0 
[log.txt](https://github.com/Jackett/Jackett/files/3509647/log.txt)

**Comment by garfield69** [comment]
that certificate that your jackett is being presented is not the official one from the https://1337x.to/ site.
since you did not provide an **enhanced** log, I cannot see what Site Link your 1337x indexer is set to, but my guess is that either:
1. you are being blocked by your ISP and routed to a dead end with an CA that expired in 2014
or
2. your Site Link on your Jackett 1337x Indexer is pointing to a 1337x proxy/mirror that has now closed or being routed to a click bait site or something like that, which has a CA that has expired.

in case 1) then your best bet is to switch your DNS from the one provided by your ISP to one of the public ones from say Cloudflare 1.1.1.1 or Google 8.8.8.8 
in case 2) use the official 1337x site if you have access to it, or find another proxy that works with the jackett 1337x indexer

**Comment by newgithubuser2019** [comment]
(LimeTorrents) An error occured while testing this indexer
Exception (limetorrents): certificate validation failed: [Subject] O=Internet Widgits Pty Ltd, S=Some-State, C=AU [Issuer] O=Internet Widgits Pty Ltd, S=Some-State, C=AU [Serial Number] 00F5BA2E609C91DBB4 [Not Before] 10/13/2014 4:46:03 PM [Not After] 11/12/2014 3:46:03 PM [Thumbprint] 5D8A25EB8B9C46981F007D105007113B97CA9BE6 : An error occurred while sending the request.
_____________________________________________________________________________________________________
 Jackett Version 0.11.608.0 
[log.txt](https://github.com/Jackett/Jackett/files/3511673/log.txt)

**Comment by garfield69** [comment]
same thing. the CA you have found is the same one you got when you tried accessing 1337x which probably means that limetorrents is also being blocked by your ISP
in fact you latest log shows that only ettv worked for you https://www.ettv.to/

to confirm this you can open a browser on the same system that you run jackett on, and access 
https://1337x.to
and 
https://www.limetorrents.info/
and see what you get.

**Comment by newgithubuser2019** [comment]
I can't open https://www.limetorrents.info/ and https://1337x.to. However i can open https://www.1337x.to

**Comment by garfield69** [comment]
as I have said before try switching your DNS or invest in a VPN
https://www.tomsguide.com/us/cloudflare-dns-1.1.1.1-set-up,news-26964.html
