### ISSUE TITLE
Please add new indexer (torlook)

### ISSUE THREAD

**Issue by newgithubuser2019** [Jackett/Jackett#5917]
https://torlook.info/
It's a meta-search engine for popular russian torrent trackers

**Comment by garfield69** [comment]
the site generates results using dynamic html built via javascript calls.
as such it is not compatible with the cardigann processor which can handle only static html.
this indexer will need to be written in c#.

**Comment by garfield69** [comment]
Have looked at this again, and discovered that while the results are not available under the *DOC* HTML returned, it is available under the *XHR* HTML which can be processed by Cardigann.
So I will be able to add a yaml indexer for this.

**Comment by garfield69** [comment]
Darn.
the download link is some kind of obfuscated magnet which will need decryption with an ajax call
looks like this:
```html
<span class="magnet">
  <a class="magneto" data-fancybox data-type="ajax" data-src="dl/617/RctLDsIgEADQ23RZWqAfSIhnGYbBGutgJkOitzdduX_vBXcmjbePpi4csz6OCB4t1lpdcDDj6kJZHITJbqWusHvymXZcwA2FkzYRYh3zd1BJh-o7GiOkAvgkGc-GcBpgbp2RLtLLJf4t2m2efg" href="javascript:;">
  </a>
</span>
```
so back onto the c# queue

**Comment by uchuu-me** [comment]
@garfield69 
Add data-src value to url "https://gw1.torlook.info/" so it will look like "https://gw1.torlook.info/dl/617/RctLDsIgEADQ23RZWqAfSIhnGYbBGutgJkOitzdduX_vBXcmjbePpi4csz6OCB4t1lpdcDDj6kJZHITJbqWusHvymXZcwA2FkzYRYh3zd1BJh-o7GiOkAvgkGc-GcBpgbp2RLtLLJf4t2m2efg" and parse response
```
<html>
...
<body>
...
<script>
    $(function(){
        var item        = $("div.item:eq(10)").find("a:first");
        var topic_title = item.text();
        var topic_url   = item.attr("href");

        var topic = $("#topic");
        topic.html(topic_title);
        topic.attr("href", topic_url);

        $("#seconds_timer").countdowntimer({
            seconds: 10,
            timeUp: function() {
                $("#seconds_timer").html("<a href='magnet:?xt=urn:btih:401061B940E80134B3435C3392A750904910A5A3'>Download</a>");
            }
        });
    });
</script>
</body></html>
```

**Comment by garfield69** [comment]
Ah. Well we are still going to need an indexer written in C#
This is because cardigann does not support multi-stage downloads from the search results page download link.
A download link on the results page has to be either a direct url to a .torrent or magnet URI or a link to the details page where further processing of the download link can be done.
if the download was on the details page I could pre-fetch the url, then process the returned script and grab the magnet.
but since torlook does not have details pages of its own (it supplies links to the details pages of the sites its trawling the results from) we stuck again on a c#.
Onother small fly in the soup is the lack of categories on this site. Can identify if a torrent is TV, MOVIE or OTHER :-( 

@uchuu-me Thank you for the info on using the data-src attribute.

**Comment by garfield69** [comment]
recent enhancements to cardigann may mean this can now be done. I shall have another go.

**Comment by garfield69** [comment]
v0.19.124

**Comment by garfield69** [comment]
torlook appears to be responding to year query with a not-found
2021, 2020, etc down to 2012.
2022 and 2011, 2010, 2009 and so forth, return results.

I guess we can wait until after Dec 31 and see if 2022 remains available, but if that starts to fail then we can assume the site is actively flagging repeat queries as unwanted and we may want to consider dropping the indexer.

**Comment by garfield69** [comment]
https://gw1.torlook.info/ returning ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://gw1.torlook.info/ returning
![image](https://user-images.githubusercontent.com/6933240/151918146-3cd483f3-ae03-40c0-897d-e3081a2b33d1.png)

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://gw1.torlook.info/ returns ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
v0.20.2384
