### ISSUE TITLE
JackettUpdate took all left space on my qnap /tmp folder

### ISSUE THREAD

**Issue by ade05fr** [Jackett/Jackett#5929]
Hi 

I have always a problem in my QNAP TS-251 NAS due to JackettUpdate process. I have always a temporary folder JackettUpdate which is not cleaned by Jackett and stay on my NAS. It impacts the behavior of my router (problem to store infos for my FAN infos).

Is it possible to change the default temporary path to another ? if not, is it possible to delete the folder JackettUpdate after the execution. 

**Jackett version**:   0.11.493.0

**Comment by khaosx** [comment]
The problem isn't so much that Jackett is using the /tmp directory, as that's exactly the place it should be using. The problem is QNAP's sizing of the /tmp directory. You'll be a lot happier overall if you go to Control Panel -> Hardware, General tab, and click "Run User Defined Processes During Startup". Once selected, click "View autorun.sh", and add the following line:

`mount -o remount,size=256M /tmp`

**Comment by Heeere-GittyGitty** [comment]
> 
> 
> The problem isn't so much that Jackett is using the /tmp directory, as that's exactly the place it should be using. The problem is QNAP's sizing of the /tmp directory. You'll be a lot happier overall if you go to Control Panel -> Hardware, General tab, and click "Run User Defined Processes During Startup". Once selected, click "View autorun.sh", and add the following line:
> 
> `mount -o remount,size=256M /tmp`

Can you please explain what resizing TMP partition has to do with uncleaned folder? Does it fail to update with the default 64MB and works OK with 256? is that it?

Thanks, if I understand correctly, I'll have the same problem

Cheers

**Comment by khaosx** [comment]
I used to have the exact same problem with both Jackett and Sonarr. The problem is that 64MB of space gets eaten up very quickly, especially when the apps update. Giving them some breathing room will allow them to do the update and finish the run without breaking anything. In the case of Sonarr, the upgrade had to finish and restart in order to clean the upgrade folder out. I don’t know if Jackett has the same issue, but resizing /tmp will give you a buffer. Even if it doesn’t solve the problem, it will keep everything running and give you time to address the space before processes fail.

**Comment by Heeere-GittyGitty** [comment]
I tried to mannually run the mount command you gave before, but the mount gives an error of bad option..

**Comment by Heeere-GittyGitty** [comment]
forget it, now it's working :) thanks for the tip

**Comment by khaosx** [comment]
Sure thing.  Glad it works and hope it helps!

**Comment by garfield69** [comment]
the updater process does have a cleanupTempDir step. so if this is not being completed it would probably be because the temp dir being full would crash the updater and prevent the cleanup.
