### ISSUE TITLE
[diablotorrent] Can password login be done instead of cookie login

### ISSUE THREAD

**Issue by BurhanDanger** [Jackett/Jackett#5963]
Diablotorrents cookie expire very quickly ( probably within a week ). They don't need ￼captcha on login page, so can this tracker be configured with username and password.

**Comment by garfield69** [comment]
this indexer is written in yaml and has a form based login coded.
https://github.com/Jackett/Jackett/blob/1bce9beb4fda085261d8257bcd141f7b3f2f6c1d/src/Jackett.Common/Definitions/diablotorrent.yml#L61-L74
However, the cardigann processor spots the 
```html
			<div class="form-group" id="recaptca_group" style="display:none;">
				<label class="control-label col-sm-5"></label>
				<div class="col-sm-5">
					<div class="g-recaptcha" data-sitekey="6LcIzA0UAAAAAAkwH2E8TJt5DNAVJDt7ehRInCyj"></div>
				</div>
			</div>
```
within the html of the sites login form, and since it cannot know if the captcha is activated it presents a cookie login instead.

sorry, don't think there is anything we can do about this. @kaso17  am i right?

**Comment by garfield69** [comment]
I think I have enhanced the Cardigann processor's ability to recognise if a recaptcha is active or not, and thus whether a cookie login is required.
I've tested this against freetorrent, desireleasers  and diablotorrent, which are three sites that I know have the recaptcha is each variation: active, not present, present but inactive.
while I have logins for freetorrent and desireleasers I don't have one for diablotorrent so I have not actually completed the login process for that indexer. But the jackett indexer config displays the username and password now, while prior versions displayed the cookie, so I'm hopeful it will work.
Try out jackett pre-release 0.11.762

**Comment by BurhanDanger** [comment]
Looking good here.
