### ISSUE TITLE
[iptorrents]  (Config) An error occured while updating this indexer

### ISSUE THREAD

**Issue by jaredfaulkner** [Jackett/Jackett#5984]
An error occured while updating this indexer
**Jackett version**:  0.11.687.0

Tried configuring from the web interface (unable to save the indexer), then created a JSON file (unable to update or use the indexer, although it appears in the web interface; file attached and renamed to .txt for convenience.
[iptorrents.json.txt](https://github.com/Jackett/Jackett/files/3611349/iptorrents.json.txt)
).

-------------------------------
[log.txt](https://github.com/Jackett/Jackett/files/3611354/log.txt)

**Comment by wgehalo** [comment]
Hey Jared,

I had this same issue. I fixed it by removing and re-adding IP torrents as a tracker after updating.
It's changed where you have to grab cookie information rather than give it user/password due to a new captcha on their login.

Once I logged in and grabbed my cookie string from a subsequent request it worked in Jackett after pasting the string into the IPTorrents config.

**Comment by jaredfaulkner** [comment]
Resolved by inserting cookie information into JSON indexer file.
