### ISSUE TITLE
Newpct tracker missing results

### ISSUE THREAD

**Issue by panfri787** [Jackett/Jackett#6030]
Hello,

I've done a search into Newpct and I think is missing HD results. Attach images.

Results in jackett:
![image](https://user-images.githubusercontent.com/1939950/65408502-b676d080-dde5-11e9-8689-dd9f1542d7f5.png)

Results in website directly:
![image](https://user-images.githubusercontent.com/1939950/65408522-c2fb2900-dde5-11e9-9efa-54b5da2cfa57.png)

Could you review it? Thanks a lot!

**Comment by garfield69** [comment]
yeah, @snamds  and @javierjp93 have been maintaining this indexer.
while the descargas2020.org website is returning 12 aladdin results, this is not the site that the indexer seems to be using, because when the indexer tries to process the request it is getting null results (something about the way the descargas website is set up prevents jackett from fetching results). 
Probably something to do with the gazillion redirects and popups that the site generates.
So the indexer picks one of the standby alternate links, and it is currently using  www.tvsinpagar.com as a standby,  and this is returning only 3 hits.
Mind you, tvinspagar has just as many redirects and popups, but clearly it at least returns something.
Since this indexer is written in c# I am not getting involved. 
but I don't think there is much that can be done.
Guys, do you have any feedback or corrections to what i've said feel free to contribute, or submit a PR with improvements.

**Comment by tooljose88** [comment]
I'm trying to fixit. I have seen that really the Form from searcher isn't not working, it's redirecting to the homepage. The submit button has a listener (JS) that executes an AJAX function to the url "/get/result/" and not in "/buscar". In that URL shows a JSON with all results

**Comment by snamds** [comment]
Yep, I'm already working on it. Let me fix it if you don't mind

**Comment by tooljose88** [comment]
All yours, thanks for the help

**Comment by panfri787** [comment]
Thanks for the support. I will be expecting.

**Comment by snamds** [comment]
Solved. 
https://github.com/Jackett/Jackett/pull/6055

**Comment by garfield69** [comment]
fix included in jackett 0.11.733
