### ISSUE TITLE
[AniRena] Results don't link to the torrent page

### ISSUE THREAD

**Issue by whitesnakeftw** [Jackett/Jackett#6075]
Results from AniRena all link to exactly: http://127.0.0.1:####/UI/Dashboard

**Comment by garfield69** [comment]
that is because the anirena web site does not have a details page for each torrent result.
so a details link was not defined in the yaml and is appears the cardigann's default action is to link to  the jackett dashboard.
if you access the anirena website https://www.anirena.com/ you will see that if you clink on the name of any  torrent result you get a dropdown with details.
most sites would direct you to a dedicated torrents detail page.
not sure there is anything that can be done about this.
