### ISSUE TITLE
Bj-Share - Search system wont work

### ISSUE THREAD

**Issue by sergiogns** [Jackett/Jackett#610]
The program is unable to return results, in case the search string is something like this "The Walking Dead s07e01". The only way to find at least something about the series is search "The walking dead", which return too many wrong results.

Thank you.

**Comment by kaso17** [comment]
This solution now strips SXX and EXX from the search string and filters the result later.
If you've a full list of Tags (MP4 / H.264 / AAC / WEB-DL / Dublado / HD, ...) we could do the same for them.

**Comment by regisdepret** [comment]
Some search results come with string Name Year S99E99. when it happens, sonarr is unable to identify the correct match.
![image](https://cloud.githubusercontent.com/assets/20420844/23910943/05a836f2-08ba-11e7-8e3e-978df7a3a8e3.png)


Other results come as Name S99E99 Year, and work correctly, how to fix it?

**Comment by kaso17** [comment]
Please post the sonarr log of the manual search.

**Comment by regisdepret** [comment]
![image](https://cloud.githubusercontent.com/assets/20420844/23913370/8b345b96-08c1-11e7-955f-5d720a5106e4.png)

![image](https://cloud.githubusercontent.com/assets/20420844/23913399/a8255fb6-08c1-11e7-8f0f-16e9d4254903.png)

**Comment by regisdepret** [comment]
I think during the string creation for sonarr, the problem occurs, but i don´t know who create the string, if Sonarr, Jackett to Sonarr, or BJ to Jackett.

**Comment by kaso17** [comment]
Please check the files section for a more detailed log.
I think the problem is that sonarr searches without year and can't handle results containing the year.

**Comment by regisdepret** [comment]
Kaso17,

Since yesterday i´m trying to adjust sonarr, but i cant find any configuration with naming syntax.

In other side i´m thinking about something:

Look at images below, the year information comes during the jackett search.

I don´t know why, feud comes without year, and it works in sonarr, but legion comes with year, and don´t work in sonarr.

Looking at bj-share for both series profile, the year info is correctly configured.

There is any possibility the problem is inside the connector component from jackett to bj-share?

![image](https://cloud.githubusercontent.com/assets/20420844/23950972/8774d5c6-096b-11e7-923b-f0429815c781.png)

![image](https://cloud.githubusercontent.com/assets/20420844/23950989/963c8fa4-096b-11e7-87ff-3d068c357694.png)

**Comment by regisdepret** [comment]
Same issue when using Radarr.

![image](https://cloud.githubusercontent.com/assets/20420844/23952191/5df5ffe6-096f-11e7-9f5a-62c12a2a40d9.png)

**Comment by regisdepret** [comment]
May be possible the problem is the syntax of year not coming between []???

2016 - Wrong
[2016] Correct

Just thinking.

**Comment by regisdepret** [comment]
Looking at https://github.com/Jackett/Jackett/blob/87d3fd9443afb65789ccc32703d3cfa97ff7c0a9/src/Jackett/Indexers/BJShare.cs

I believe found the place where the string is created, but i´m not a developer, just an enthusiast.
![image](https://cloud.githubusercontent.com/assets/20420844/23953008/1881dc8e-0972-11e7-826a-8f59bf4b4c1f.png)

Could be the problem?

**Comment by regisdepret** [comment]
I think i found the solution. In BJ profile configuration we have an option to group search results.
![image](https://cloud.githubusercontent.com/assets/20420844/23954378/e106b55a-0975-11e7-925a-cd3dd73e4ff9.png)

I deactivated the option to group, jackett now brings different information.
![image](https://cloud.githubusercontent.com/assets/20420844/23954510/3c29c9f4-0976-11e7-8093-869a4f2da01a.png)

And sonarr can now parse the tv show.
![image](https://cloud.githubusercontent.com/assets/20420844/23954549/5a859dd8-0976-11e7-9af8-4a6fbcb63a37.png)

I think, in code, the section where jackett parse grouped results are returning wrong.

**Comment by kaso17** [comment]
The default format (with grouping) is fine for sonarr.
The problem is that sonarr can't handle the always present year (if the year is behind the episode tags it's ignored). I've opened https://github.com/Sonarr/Sonarr/issues/1768 for it.

A hacky workaround on the jackett side would be to remove the year from the title if it's not present in the search string. But fixing it on the sonarr side is the much cleaner option.

For Radarr I assume a similar parsing issue (It can't handle the duplicate/translated title). Please share a trace log for the parsing (I didn't have time to migrate to Radarr yet).

**Comment by regisdepret** [comment]
how can i trace this log to send you?

**Comment by kaso17** [comment]
in Sonarr it's at "System/Logs/Files"

**Comment by regisdepret** [comment]
[radarr.txt](https://github.com/Jackett/Jackett/files/847819/radarr.txt)

**Comment by kaso17** [comment]
Please increase log level to Trace (settings > general > logging) and post the update log again.

**Comment by regisdepret** [comment]
[radarr.txt](https://github.com/Jackett/Jackett/files/852397/radarr.txt)

**Comment by kaso17** [comment]
Seems like there's an DNS problem (Error: NameResolutionFailure)?
17-3-18 09:17:29.4|Warn|Torznab|BJ-Share http://regisdepret.no-ip.org:8517/torznab/bjshare/api?t=search&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100&q=rogue%20one%20star%20wars%20story%202016 Error: NameResolutionFailure

**Comment by regisdepret** [comment]
i made some adjustments in Jackett address to localhost:9117.

now i have success for some movies.
![image](https://cloud.githubusercontent.com/assets/20420844/24098814/2eb12848-0d4b-11e7-9e4e-2dd3415c862e.png)
There is an error but download button is available.

And some movies keep unparseable.
![image](https://cloud.githubusercontent.com/assets/20420844/24098861/58595486-0d4b-11e7-8b30-6181f16ab40f.png)

[radarr.txt](https://github.com/Jackett/Jackett/files/854866/radarr.txt)
[radarr.debug.txt](https://github.com/Jackett/Jackett/files/854867/radarr.debug.txt)
[radarr.trace.txt](https://github.com/Jackett/Jackett/files/854868/radarr.trace.txt)

**Comment by kaso17** [comment]
`17-3-20 08:59:14.2|Debug|ParsingService|No matching movie Resident Evil 6O Capítulo Final [Resident EvilThe Final Chapter`
As expected Radarr doesn't handle the duplicate (english+foreign title) correctly.
I'll try to add some option to rewrite it to the corresponding name.
Does Radarr expect the foreign title or the english original one?
Additionally it seems like the HD and Full HD tags are used incorrectly, do you know the BJ rules regarding them?

**Comment by regisdepret** [comment]
I believe radarr expects english title, because during "add movie" action, this is the results of search:
![image](https://cloud.githubusercontent.com/assets/20420844/24116678/4ff726d4-0d86-11e7-8638-3537a8418e25.png)

This youtube video was made to teach how upload into bj, i believe the information about tag rules is inside it.
https://www.youtube.com/watch?v=j-36j9bsgi0&feature=youtu.be

**Comment by regisdepret** [comment]
What if you use IMDB/TVDB number instead of name? BJ demands uploaders to put the identify uploads with this information?

**Comment by kaso17** [comment]
@regisdepret AFAIK BJ doesn't support searching by IMDB/TVDB ID, if they do please let us know.

**Comment by regisdepret** [comment]
I think it does, because when anyone upload a file, has to inform imdb/tvdb
id, is mandatory.
Since i´m not from BJ dev team, how can i ask them with technical
information you need.

Em sex, 10 de nov de 2017 às 13:33, kaso17 <notifications@github.com>
escreveu:

**Comment by kaso17** [comment]
If the tracker would support searching via IMDB/TVDB IDs (using the normal website search form) this could be used.
