### ISSUE TITLE
Search by imdbid in 0.11.786 doesn't work

### ISSUE THREAD

**Issue by fryfrog** [Jackett/Jackett#6114]
In version `0.11.760`, the following URL correctly returns many results. In version `0.11.786` it returns only the tracker header. Searches *not* using imdbid, like a search query w/ season/episode that Sonarr does still work fine.

`http://10.0.1.2:9117/jackett/api/v2.0/indexers/iptorrents/results/torznab/api?t=movie&cat=2000,2010,2030,2040,2060,2070&extended=1&apikey=(redacted)&offset=0&limit=100&imdbid=0443649`

**Comment by garfield69** [comment]
oops.
sorry about that.
I thought the `return "tt" + ((int)imdbid).ToString("D7");` would truncate an 8 digit imdbid so I automatically set it to D8
but reading the docs now, I see that D7 only pads leading zeroes, so if it gets 8 digits it will simply not add any additional zeroes at the front and return the 8 digits.
fixed in jackett 0.11.787

**Comment by addisonbabcock** [comment]
Updated to the latest and confirmed that this appears to be fixed. Thanks for the quick response!
