### ISSUE TITLE
How do you uninstall Jackett from Ubuntu Server?

### ISSUE THREAD

**Issue by acollien** [Jackett/Jackett#6169]
Had Jackett running on Ubuntu Server 18.04LTS. Recently (I suspect a permission issues) it stopped working (i.e. would not run) so I am trying to uninstall it, and will reinstall.

I installed using the https://github.com/Jackett/Jackett#install-on-linux-amdx64 method - as a service.

I've tried `sudo apt-get remove --purge jackett`, but it returns 'E: Unable to locate package jackett'.

Not sure what to do here.

Side note - I noticed Jacket was using a pretty unreasonable amount of physical memory - 4gig+. And it only had 2 indexers... not sure if this is normal? but even plex doesn't use that much when streaming...

**Comment by garfield69** [comment]
there are 3 components:
1. systemd script (optional)
stop jackett with `systemctl stop jackett.service`
cd to `/etc/systemd/system/` and delete the `jackett.service` script.
but the next time you run the `sudo ./install_service_systemd.sh` you will overwrite this script file anyway.
2 configs (optional)
if you want to remove the indexer profiles and jackett settings, logs and whatnot then cd to `~/.config` and delete the `Jackett` folder
or you could just delete `ServerConfig.json` if you want to only reset the jackett settings.
3 binaries.
since all the files in the .tar.gz archive you downloaded for here, were copied to a location of your choosing, the binaries are where ever you put them. locate that folder and delete it.
typical location is: `/opt/Jackett` but i've seen `~/Jackett` used too.

**Comment by acollien** [comment]
> there are 3 components:
> 1. systemd script (optional)
> 2. configs (optional)
> 3. binaries.

Thanks for that. All went smoothly. Any idea re: the memory usage? or is it just an unually hungry app?

**Comment by garfield69** [comment]
not a clue. I'm not a c# dev and don't know the inner workings of this app.
current tickets open for high memory: #4720 #4088 #4966
