### ISSUE TITLE
magnet link missing from results

### ISSUE THREAD

**Issue by wellloaded** [Jackett/Jackett#6237]
It looks like when looking for content certain sites prefer to provide the link to the torrent.

I personally work on magnet only so every time i need to open the page found in the result and click the magnet from there.

Can Jackett have a preference to display magnets instead (or as a multiple record)?

Example:
- search  indochine

- look at the ETTV result:
https://www.ettv.to/torrent/58503/indochine-4k-remastered-1992-1080p-bluray-x264-dtshd-5-1-ddr

**Comment by garfield69** [comment]
if you access your jackett dashboard and edit the ETTV indexer config, you can switch the download link to magnet.

if you know of any other sites that use magnets for which the corresponding jackett indexer does not either:
a) provide a magnet link in the search results or
b) have an option in the config to switch from .torrent to magnet 
then raise a request and I will take a look at see if I can add it to the indexer.

**Comment by wellloaded** [comment]
Thanks for the comment. in the interest of other users as well, could the indexer files be providing duplicated results by default and report both magnet and torrent links?

Thanks

**Comment by garfield69** [comment]
unfortunately, that is not possible for some of the sites that jackett supports.

it all depends on whether the web site presents the download links for .torrent and magnet on the **primary search results page** or only on the **individual torrent details page**.

if they are both in the search results page, then no problem, since the links are there as jackett processes that page and builds the search results table.
(BTW, if you know of any site that has both magnets and .torrents on the search page results and jackett is not displaying both, then feel free to raise a ticket to get the corresponding indexer updated).

But if the two links are on the individual torrent details page, then Jackett does not know (when it is processing the search results page) what kind of download links are available, because the individual torrent details pages are only accessed when the user clicks on the download icon in the results table that jackett generated.

And before you ask why doesn't jackett pre-fetch the details pages for all the torrents in the search results page, the answer is: because that would add up to 100 additional request to the site each time you did a search, and the extra network load will be miss-interpreted by most sites as a DDoS attack and flag your IP address as a bad actor.
