### ISSUE TITLE
[aniRena] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by nhsqr** [Jackett/Jackett#6239]
https://www.anirena.com/ is opening in the browser without any problem.

(At the bottom of your Jackett Dashboard page) **Jackett version**:   Jackett Version 0.12.863.0 
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**: Mono JIT compiler version 5.18.0.240 (tarball Tue Mar 19 06:36:09 UTC 2019)
[log.txt](https://github.com/Jackett/Jackett/files/3767449/log.txt)

-------------------------------

**Comment by garfield69** [comment]
yeah. 
AniRena have implemented a anti-bot cookie test script from Power2All which means that the current Cardigann indexer written in yaml can not be used to solve the puzzle, since the cardigann processor cannot run the js and solve the challenge.
The AniRena .yml indexer will need to be re-written as a c# by a volunteer :-(

**Comment by garfield69** [comment]
https://www.anirena.com/ currently returning cloudflare 523 Origin is unreachable

**Comment by garfield69** [comment]
anirena is back up and they have dropped the cookie test, so the jackett indexer is working again.
