### ISSUE TITLE
problem cant download torrent file no error on console Greekteam tracker

### ISSUE THREAD

**Issue by vlevas** [Jackett/Jackett#6240]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

(At the bottom of your Jackett Dashboard page) **Jackett version**:  
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**:

-------------------------------
Jackett in docker Jackett Version 0.12.863.0

Error in sonarr:

> Downloading torrent file for episode 'True.Detective.S02E07.HDTV.x264-BATV' failed since it no longer exists (http://ip:9117/dl/greekteam/?jackett_apikey=(removed)&path=Q2ZESjhBc3RlRjJRTmx4S3ZnMFg5XzRFUUNXRUVDc3FCY2N4Q18zUHRKdlh3ZFpPVGdQbnVQczNDLURfWFZxVEtSa1N3WW1Qb2kzLWtPaTRkWURmYlVZNi1KdVhpSVJTcmtoNnk1LW9lUzY1eXpFVFpnTkJTcUtTMTlwQzZaOFY2MUFfSmJVcFlCOEMtbFdoOHlIZVZqNEoxNEZfbXV4cVdhYUk1VFJWY1VxNE1EMVRmS1dNa2xKQWxsQTV5MF9kU0RlTUxR&file=True.Detective.S02E07.HDTV.x264-BATV): HTTP request failed: [404:NotFound] [GET] at [http://ip:9117/dl/greekteam/?jackett_apikey=z03ixokiu0qulyomdjj1v9zndiuzjrpd&path=Q2ZESjhBc3RlRjJRTmx4S3ZnMFg5XzRFUUNXRUVDc3FCY2N4Q18zUHRKdlh3ZFpPVGdQbnVQczNDLURfWFZxVEtSa1N3WW1Qb2kzLWtPaTRkWURmYlVZNi1KdVhpSVJTcmtoNnk1LW9lUzY1eXpFVFpnTkJTcUtTMTlwQzZaOFY2MUFfSmJVcFlCOEMtbFdoOHlIZVZqNEoxNEZfbXV4cVdhYUk1VFJWY1VxNE1EMVRmS1dNa2xKQWxsQTV5MF9kU0RlTUxR&file=True.Detective.S02E07.HDTV.x264-BATV]

> NzbDrone.Common.Http.HttpException: HTTP request failed: [404:NotFound] [GET] at [http://ip:9117/dl/greekteam/?jackett_apikey=z03ixokiu0qulyomdjj1v9zndiuzjrpd&path=Q2ZESjhBc3RlRjJRTmx4S3ZnMFg5XzRFUUNXRUVDc3FCY2N4Q18zUHRKdlh3ZFpPVGdQbnVQczNDLURfWFZxVEtSa1N3WW1Qb2kzLWtPaTRkWURmYlVZNi1KdVhpSVJTcmtoNnk1LW9lUzY1eXpFVFpnTkJTcUtTMTlwQzZaOFY2MUFfSmJVcFlCOEMtbFdoOHlIZVZqNEoxNEZfbXV4cVdhYUk1VFJWY1VxNE1EMVRmS1dNa2xKQWxsQTV5MF9kU0RlTUxR&file=True.Detective.S02E07.HDTV.x264-BATV]
>   at NzbDrone.Common.Http.HttpClient.Execute (NzbDrone.Common.Http.HttpRequest request) [0x00131] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Http\HttpClient.cs:100 
>   at NzbDrone.Common.Http.HttpClient.Get (NzbDrone.Common.Http.HttpRequest request) [0x00007] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Http\HttpClient.cs:271 
>   at NzbDrone.Core.Download.TorrentClientBase`1[TSettings].DownloadFromWebUrl (NzbDrone.Core.Parser.Model.RemoteEpisode remoteEpisode, System.String torrentUrl) [0x00024] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\TorrentClientBase.cs:134

**Comment by garfield69** [comment]
have you tried logging onto the GreekTeam web site from your browser and seeing if you can download True.Detective.S02E07.HDTV.x264-BATV from there directly?

the error message you posted implies that the web site's download link is not valid anymore, as would be the case, for instance, if the site dropped the download link as a result of DMCA takedown request.

If the file is no longer on the site, but they kept the torrent listing for that torrent, then that would explain the issue.
If however you can still download the file, then that points to an issue with the Jackett indexer being out of date due to changes to the site's download link html.

**Comment by vlevas** [comment]
thanks for the reply @garfield69 yes manually from browser i can download it..

**Comment by vlevas** [comment]
maybe this can help u? is the html of page of that specific torrent file
https://pastebin.com/8SWi1JDm

download link is for regular or freelech double if needed etc

	<tbody><tr><td align="right" class="colhead3" width="1%"><b></b></td><td align="left" class="details-row"><a style="vertical-align: bottom;" rel="balloon3" class="index" href="**download2.php?torrent=98288**"><img src="/pic/download_torrent.png" alt="Download Torrent without Freeleech Slot!"></a> or&nbsp;<b>Use:</b> 
<a class="index" href="**download2.php?torrent=98288&amp;slot=free**" style="vertical-align: bottom;" rel="balloon1" onclick="return confirm('Are you sure you want to use a freeleech slot?')">
<img src="/pic/freeslots.png"></a>&nbsp;or&nbsp;<b>Use:</b> 
<a class="index" href="**download2.php?torrent=98288&amp;slot=double**"

**Comment by garfield69** [comment]
actually, what I really need is a copy of the HTML from the search results page.
the download link that the indexer uses is not the one from the torrent-details page.
it is instead built by concatenation of `download2.php?torrent=` with the id taken from the a.torname selector.
this may have changed, so a look at the search results HTML will be useful.
Thanks.

**Comment by vlevas** [comment]
http://www.greek-team.cc/browse.php?incldead=0&search=TRUE+DETECTIVE+S02E07&blah=0

i hope this is it: https://pastebin.com/AzZ0F2pw

**Comment by garfield69** [comment]
well, I cannot see what the problem is. The download link generated by the indexer should look exactly like the first download link in the torrent details page you provided:
`download2.php?torrent=98288`
so this is what I would like you to try next, please.
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. using just the Jackett dashboard (lets keep Sonarr out of it to simplify things) search for the episode and click on the download.
4. then find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

The full debug log may contain additional info that could shed light into what it going in in between the search and download steps.

Thanks.

**Comment by vlevas** [comment]
for some reason now it works and downloads.. let me close it and if the problem will appear i will post it again here.. i dont underestand why.. 3-4 days was unable to download :S from jackett and from automatic way sonarr/radarr etc..
