### ISSUE TITLE
blank page on localhost:9117

### ISSUE THREAD

**Issue by adylim** [Jackett/Jackett#6244]
hi all,

recently trying to remove old Jackett and upgrade to the new one, I'm doing this on a Mac
I removed the old directory in ./config and with the newest binary ran ./install_service_macos

I get the green "Agent successfully installed and launched!"

go to localist:9117 and get a blank page!

log.txt doesnt show much (attached here

so I ran the installer again..and in subsequent logs (log.txt.201910250001) shows the error that the port is already in use...

killing the PID (after finding out with lsof) and trying to just run ./jackett brings me to the blank page again..

any ideas?

thanks!
[log.txt](https://github.com/Jackett/Jackett/files/3771281/log.txt)

**Comment by garfield69** [comment]
I think you deleted the wrong folder. the ./config/Jackett held the active settings including the api key and indexer configs. You could have left this alone and the new install would have been happy to load your prior settings.
what you probably wanted was to delete was the folder that has the old binaries and the old startup script that invoked the old mono version.

regardless, it is likely that you may have left the old mono service running out of the original binary library, which is likely why port 9117 is taken.

try to shutdown the mono service from a terminal with with the command `systemctl stop jackett.service` and then removing the startup script at `/etc/systemd/system/jackett.service` and deleting the content of the `/Applications/Jackett` folder.

Then install from the https://github.com/Jackett/Jackett#installation-on-macos notes afresh, and see how you go.

**Comment by adylim** [comment]
Thanks!

However, there’s no systemctl(command not found)! Running macos 10.13.6

**Comment by garfield69** [comment]
oh. my bad.
maybe launchd is auto-starting the pid after you kill it, so you may need to disable that service.
so perhaps from a terminal, try `lsof -i 4tcp:9117` to get the pid of the service that has the port open, 
use `launchctl list` to view the launchd services, and find the label of the service with that pid.
hopefully it is **not** called `org.user.jackett` because that is the new coreMacOs jackett label.
then try `launchctl stop <label>` and/or `launchctl remove <label>` and/or `launchctl disable <label>`

and see if you can get that old service to say down. perhaps reboot the mac after that and see if the new jackett service has been started successfully and the if the dashboard is available via the browser.

**Comment by adylim** [comment]
it is called org.user.jackett!

anyways after a reboot, the service does not seem to be running at all..
I did try the install script again (following the instructions) and still nothing! (cannot find server this time instead of a blank page)...

**Comment by garfield69** [comment]
so does running manually with the ./jackett work now?

**Comment by adylim** [comment]
nope! that gives me a blank page....

**Comment by adylim** [comment]
I've got to be doing something wrong..

**Comment by garfield69** [comment]
if you used the launchctl disable, then that service will not start again until you do an launchctl enable followed by a `launchctl load ~/Library/LaunchAgents/org.user.Jackett.plist`

but as to why you are getting a blank page instead of the dashboard, that is a puzzle.
take a look at the `~/.config/Jackett` folder.
is there a file called `ServerConfig.json` ?
edit it and check it again my default one which looks like this:
```json
{
  "Port": 9117,
  "AllowExternal": false,
  "APIKey": "**your unique api key***",
  "AdminPassword": null,
  "InstanceId": "***some long hex string***",
  "BlackholeDir": "",
  "UpdateDisabled": false,
  "UpdatePrerelease": false,
  "BasePathOverride": "",
  "OmdbApiKey": "",
  "OmdbApiUrl": "",
  "ProxyUrl": "",
  "ProxyType": 0,
  "ProxyPort": null,
  "ProxyUsername": "",
  "ProxyPassword": "",
  "ProxyIsAnonymous": true
}
```
what does yours look like?

**Comment by adylim** [comment]
doh! of course if I disabled I'd need to reenable it!

here's my Serverconf.json

{
  "Port": 9117,
  "AllowExternal": true,
  "APIKey": "**removed but it was there**",
  "AdminPassword": null,
  "InstanceId": "**yup was a long hex string",
  "BlackholeDir": null,
  "UpdateDisabled": false,
  "UpdatePrerelease": false,
  "BasePathOverride": null,
  "OmdbApiKey": null,
  "OmdbApiUrl": null,
  "ProxyUrl": null,
  "ProxyType": 0,
  "ProxyPort": null,
  "ProxyUsername": null,
  "ProxyPassword": null,
  "ProxyIsAnonymous": true
}

**Comment by adylim** [comment]
oh wait! I did another restart and I just got to the admin screen!

**Comment by garfield69** [comment]
\o/

**Comment by adylim** [comment]
launchctl shouldnt need a restart should it?

**Comment by adylim** [comment]
amazing, I'm 1 beer in and ready to totally break this again...umm I mean setup properly ....

thanks!

**Comment by garfield69** [comment]
>launchctl shouldnt need a restart should it?

don't know for sure, I'm not a regular macos user.
good luck.
