### ISSUE TITLE
[torrent9] Exception (torrent9): Request to https://ww1.torrent9.sx/top_torrent.php failed (Error Forbidden) - The page is protected by an Cloudflare reCaptcha. The page is in aggressive DDoS mitigation mode or your IP might be blacklisted (e.g. in case of shared VPN IPs). There's no easy way of making it usable with Jackett.: Request to https://ww1.torrent9.sx/top_torrent.php failed (Error Forbidden) - The page is protected by an Cloudflare reCaptcha. The page is in aggressive DDoS mitigation mode or your IP might be blacklisted (e.g. in case of shared VPN IPs). There's no easy way of making it usable with Jackett. (Test)

### ISSUE THREAD

**Issue by Komagain** [Jackett/Jackett#6245]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
I can access to the site but if I try https://ww1.torrent9.sx/top_torrent.php a captcha is shown, after that I ma redirected to the homepage
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
Checked for a updated release but none was found. Current: v0.12.863 Latest: v0.12.863
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting
-------------------------------
[log.txt](https://github.com/Jackett/Jackett/files/3772012/log.txt)
[updater.txt](https://github.com/Jackett/Jackett/files/3772013/updater.txt)

**Comment by garfield69** [comment]
the reason you are getting a reCaptcha challenge is because there is no such page as **top_torrent.php** on the **ww1.torrent9.sx** web site.

ok, lets recap. 
there are two web sites, one of the **.sx** domain and another on the **.is** domain.
while they may look the same, they are run by two different managers, and you can tell the different between the sites by looking at which page the sites go to, when you click on their respective *Top Torrents* link.

the **.sx** site uses https://ww1.torrent9.sx/top and the **.si** site uses https://ww1.torrent9.is/top_torrent.php

to access the **.sx** site with jackett, use the **torrent9 clone** indexer.
to access the **.si** site with jackett, use the **torrent9** indexer.

so somehow, you have the wrong address loaded in the indexer you are using.
access your jackett dashboard, and use the wrench icon to edit the **torrent9** indexer.
paste `https://www.torrent9.is/` into the **Site Link** box and click **OKAY**
for the **torrent9 clone** indexer,  set the **Site Link** to `https://ww1.torrent9.sx/`

and you should be good to go.
