### ISSUE TITLE
[1337x] Network error when downloading torrent

### ISSUE THREAD

**Issue by annomatik** [Jackett/Jackett#6257]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

(At the bottom of your Jackett Dashboard page) **Jackett version**:  0.11.802.0 on a RPi 3B+ / Raspbian Stretch
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**: using the ARM 32 version

-------------------------------

When I search via 1337x or Torrent Downloads, I get proper search results but the Torrent download does not work. Instead, I get a "Network Error" when trying to add the torrent.

Steps to reproduce:

1) Search for something with 1337x or Torrent Downloads (both behave the same) , e.g. "Black Jesus"
2) Right Click on the Download Icon and say "Torrent Control --> add torrent" (or just click on it; I'm using Torrent Control in Firefox for adding torrents which works nicely for other search engines)
3) Get the "Failed to add torrent. Network error." -- for all of the results.

Error with 1337x+Torrent Downloads:

![image](https://user-images.githubusercontent.com/28311452/67634934-d35d6280-f8c1-11e9-828e-ebfe4935d9ec.png)

![image](https://user-images.githubusercontent.com/28311452/67635024-a1003500-f8c2-11e9-939f-199e7a46468c.png)

Working nicely with others, e.g. RARBG:

![image](https://user-images.githubusercontent.com/28311452/67635060-d9077800-f8c2-11e9-841b-2416b3c1c9d7.png)

**Comment by garfield69** [comment]
works for me. 
but I don't use right clicking on the download icon, or firefox.
I'm a windows  chrome user, but I do not know if that is relevant or not. (that is, I don't know if it a issue with arm32 platforms, firefox or torrent control).

what I do know is that both 1337x and torrent-download do not have a download link on their primary search results page.
instead they have one in the individual torrent-details page.
this means the download link is not resolved until you click on the download icon on the jackett search results page. (I don't know if that is relevant either, but it is a point of difference with other torrent web sites).

both sites also provide magnet and .torrent downloads, however the .torrent links are not in house, they offloaded to other services, such as http://itorrents.org/ and/or http://torrage.info/ and/or http://btcache.me/

the default setting for these jackett indexers is to use the magnet link.

So if you are using the magnet link, you may want to try switching to one of the .torrent links instead.
using your jackett dashboard, edit the config and set the download link to one or the other options other than magnet and see if that helps.

OR

if you are already using the .torrent links, then note that these .torrent services that 1337x and download-torrent use may not have the .torrent file available at the time that the torrent is added to 1337x/download-torrent web sites, it can take up to four hours or more before they show up  on itorrents/torrage/btcache


so its possible your network error is due to the itorrents/torrage/btcache services failing to provide a .torrent file.

in any case, I don't think there is anything else jackett can do for you.

**Comment by annomatik** [comment]
Thanks. Similar for Isohunt2. Apparently, there, the links are somehow protected... :-(
