### ISSUE TITLE
TeamHD: search with Apostrophe or colon

### ISSUE THREAD

**Issue by Lonli-Lokli** [Jackett/Jackett#6259]
Is it possible to make this work on TeamHD with Radarr?
Devil's advocate and Die Hard: With a Vengeance cannot be found when Radarr used.
I understand that it's the behavior from Radarr, is there workaround from Jackett? If not, what should be changed on site search side?

**Comment by garfield69** [comment]
i don't have access to teamhd so I cannot do any testing.
but removing radarr from the picture for a moment, does searching directly with jackett on the dashboard using the teamhd indexer, can you get results there searching for those movies using the full movie name?
and if not, if you drop the quote or colon do you get hits?
for devil's does devils work or only devil?
understanding what search string works may help with working out if there is anything that can be done on the teamhd jackett indexer side of the fence.

**Comment by Lonli-Lokli** [comment]
Sure!
1. Devil's advocate
Jackett search: 
Devil's advocate : results exists
Devil s advocate - zero results
Devils advocate zero results
Site search is the same

2. Die hard
Jackett: 
Die Hard: With a Vengeance - results exists
Die Hard With a Vengeance 
Results are empty
Site results are the same

**Comment by garfield69** [comment]
so what you are saying is that, if you search with the full proper name using the jackett dashboard you get results, just as you would with the web site directly.
but dropping colon or quote (which apparently is what radarr is doing) causes no results from jackett, which is what happens on the web site too.

if the above is true, then what you are saying is that jackett returns exactly what the web site does.
and if that is the case, I don't see how we can make jackett help out your radarr problem, since what you are effectively asking for, is that jackett somehow insert back the missing quote or colon when doing its searches with the indexer... not possible..

**Comment by Lonli-Lokli** [comment]
@garfield69 I was asking mostly because Radarr do not return results for this film and I think you are familiar with Radarr search as well, like are they removing these symbols or replacing them with space - to try to adopt teams search engine.

**Comment by garfield69** [comment]
if you want to see what radarr is asking jackett to search for, simply go to the jackett dashboard, enable the **enhanced loging** checkbox, click on the **apply server settings** and then perform your radarr search.
then look at the jackett log and you should see that the searcg request was that radarr sent to jackett to use to use the teamhd indexer search with.

**Comment by Lonli-Lokli** [comment]
@garfield69 Thank you!
