### ISSUE TITLE
[1337x] Exception (1337x): No connection could be made because the target machine actively refused it 193.113.9.167:443: An error occurred while sending the request. (Test)

### ISSUE THREAD

**Issue by jayrey85** [Jackett/Jackett#6293]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

(At the bottom of your Jackett Dashboard page) **Jackett version**:  
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**:

-------------------------------

**Comment by jayrey85** [comment]
im trying to use jaackett and idexer 1337x and when testing its failing

**Comment by garfield69** [comment]
the error message you posted tells me that instead of being directed to https://1337x.to/ you are being directed to 193.113.9.167
using a browser, you can see that IP 193.113.9.167 is the address to http://www.ukispcourtorders.co.uk/ and displays the following:
![image](https://user-images.githubusercontent.com/6933240/68145031-b992de00-ff99-11e9-9c06-3a8f164366c4.png)

so your ISP is blocking your access to 1337x and there is nothing Jackett can do about it.
you could try switching from using the DNS provided by your ISP to one of the public ones, such as cloundflare's 1.1.1.1 or googles 8.8.8.8,  or if your ISP has that coveredm then use a VPN.
