### ISSUE TITLE
Jackett Site doesn't load

### ISSUE THREAD

**Issue by DatsiK96** [Jackett/Jackett#6304]
Provide a description of the feature request or bug, the more details the better.
Jackett installs perfectly, by all accounts it should be working, no errors present when running the service or console, but the website cannot be visited locally or remotely from the network.

Setup is on Windows Server 2019.

Simply installed, told setup to launch Jackett, told the trey to start the service, all appears to be running, but can't visit.
Log file here: [Jacketlog.txt](https://github.com/Jackett/Jackett/files/3816931/Jacketlog.txt)

Things cut from the log file were keys, and the tracker loading.

Logs report that the service is listening, but it doesn't actually load up in a browser. IE reports too many redirects.

(At the bottom of your Jackett Dashboard page) **Jackett version**:  0.12.924.0

-------------------------------

**Comment by garfield69** [comment]
can you start another browser (firefox, chrome) and see if you can access http://127.0.0.1:9117/UI/Dashboard?
report back with a screen-capture of the error the browser presents.

**Comment by DatsiK96** [comment]
Doing some further testing, noticed that using the PowerShell command Test-NetConnection localhost -port 9117 -- showed that only the "pseudo loopback" interface was able to receive packets to that port. So it seems that Jackett is listening on the wrong interface.

I ran jackettconsole.exe -x and it works now...
![image](https://user-images.githubusercontent.com/15705306/68351268-c60d5880-00b7-11ea-8452-3576aaf68b8e.png)

Once I did the -x, I could also connect to it remotely on the network.

What's the recommended action here? What do I need to do?

**Comment by garfield69** [comment]
unusual situation, most windows users do not need to set up the external access switch when using the 127.0.0.1 (localhost) address, because any browser running on the same machine that is running jackett can use localhost without going in/out of the LAN/WAN.
so I guess this is something specific to the way your (any?) server 2019 is set up.

I suggest that you shutdown the service, edit the `ServerConfig.json` file in `C:\ProgramData\Jackett` with a plain text editor and set the `AllowExternal` keyword to **true** and start the service up again.
