### ISSUE TITLE
[corsaro.red] Radar: Found 0 releases from Corsaro.red

### ISSUE THREAD

**Issue by cappannonno** [Jackett/Jackett#6307]
Hi,
corsaro.red is not working with radarr. In jackett logs I get a "Found 0 releases from Corsaro.red (film title)" but, if i search directly from Jackett web interface, it works very well. 
On Sonarr i'm having no problem with Jackett-corsaro.red integration.
Because of i can fetch corsaro.red results from jackett interface while it fails from Radarr, I guess it's related to categories. I have tried to change them but I had no success.
Any suggestions?

**Comment by garfield69** [comment]
Sorry, no idea. 

What I do know is that searching with categories does not work with this indexer.
you can see this for yourself by using the Jackett dashboard search  for this indexer.
the moment you specify a category on the search panel, you get no results, whether you are searching for south park (with cat=5000) or captain america (with cat=2000)

the corsaro.red indexer is written in c# because it's using the site provided API at https://corsaro.red/api/search

I'm not a c# dev,  and looking at the code I cannot figure out how it is any different to the YTS c# indexer, and why one works and the other does not. 
Nor do I understand why Sonarr is able to get a result from tv searches, and Radarr does not doing movies.

But clearly there is a disconnect between how corsaro.red is using categories and how torznab is using them.

We are going to need a c# dev to debug this one. Ping to any volunteers, can you help?

**Comment by cadatoiva** [comment]
So, this one is actually kinda complicated. When searching the API requires just one category and it's not from the same list of categories that get returned. Right now, Jackett tries to send a comma separated list of all categories that are related to the search to the API, causing it to send nothing back. Sonarr works because it doesn't map a category, so the category sent is "0" (which is the valid "all categories" option). Same with when you use the jackett interface without specifying a category. Radarr and category search end up bringing in 5-12 categories into the API, leading to zero results. 

To make things more confusing, Corsaro doesn't return just those 7 valid API categories, it sends the ones listed in the C# file, so if you just try to flat rewrite the category mappings to fit the API, then all the results get filtered out as incorrect category by Jackett when searching.

I'm working on a fix that will have to look at the categories given by jackett and send a best guess API category call, while maintaining the jackett search categories for filtering after results are returned.

**Comment by garfield69** [comment]
Jackett 0.12.1470
