### ISSUE TITLE
[iptorrents] Exception (iptorrents): Object reference not set to an instance of an object: Parse error (Config)

### ISSUE THREAD

**Issue by Cylae** [Jackett/Jackett#6308]
Can't add IPTorrents : 

`[iptorrents] Exception (iptorrents): Object reference not set to an instance of an object: Parse error (Config)`

Jackett Version 0.12.926.0

Thank you for your help :)

**Comment by garfield69** [comment]
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.

**Comment by Cylae** [comment]
Here are the logs : 

https://pastebin.com/5eGMaBsW

I'm on Debian 10

**Comment by garfield69** [comment]
hmm. 
you have clearly got the correct username and password because the log shows you are being presented with the default search results of a browse request with no search query.
But your html results from iptorrents look different from mine, which may explain why the iptorrents indexer is failing, because the indexer is not being presented a results page in the format it is expecting to process.

try the following:
use a browser to login to iptorrents directly, and access the **settings** menu.
set the following:
torrent category column=icons
torrents show new tags=ticked
torrents show files count=ticked
show xxx torrents=ticked
torrents per page=100
browser default categories= all of them are not highlighted with a green dot, that is none of them are selected.
click on update, and logout.
then try to add the indexer again.
let me know how it goes.
