### ISSUE TITLE
[yts] The SSL connection could not be established, see inner exception.: Authentication failed because the remote party has closed the transport stream. (Config)

### ISSUE THREAD

**Issue by OliPassey** [Jackett/Jackett#6318]
An error occured while updating this indexer
The SSL connection could not be established, see inner exception.: Authentication failed because the remote party has closed the transport stream.

Trying to get the  YTS tracker going but im getting the above error.
Using  Jacket: Version 0.11.723.0
Under docker on Unraid

I can get to the  site via chrome, but not via jacket, guessing from other posts that this might be a mono issue with  SSL? Is there a way i can fix this?

Cheers for any advice you can offer

**Comment by garfield69** [comment]
are you using a proxy? seen some instances where there is a certificate mismatch on which protocol to use, because of proxy use. Have not come across a solution for this as yet. 
if you are on docker and on 0.11.* then you are no longer using mono so that will not be an issue.
Jackett switch to .net core around the 0.10.* mark.
You could upgrade your docker image to the latest 0.12.* which might help.

**Comment by OliPassey** [comment]
Will take a look at 0.12 - and not using a reverse proxy, but it is routed out via a VPN.
Thanks for the advice.

**Comment by ngosang** [comment]
@OliPassey is this fixed? It's working fine for me.

**Comment by OliPassey** [comment]
Yeah, sorry shouldve closed this. 
It was blocked by ISP, VPN had dropped.
