### ISSUE TITLE
Jackett not returning Torrent or Magnet links for some indexers

### ISSUE THREAD

**Issue by nafr1** [Jackett/Jackett#6319]
Hello,

I am trying to use Jackett as backend API for finding torrents. I am not getting Torrent or Magnet links for some of the indexers (let's say limetorrents). Instead I am getting a link that takes me back to the Jackett Server and it has a path parameter (that I guess get's resolved on the server). Is there any way instead of that Server link, I can get torrent or magnet link for those indexers?

Thanks.

**Comment by garfield69** [comment]
>Is there any way instead of that Server link, I can get torrent or magnet link for those indexers?

nope, I don't believe you can.
you get these intermediate links for certain indexers, because the web sites the indexers are scraping do not provide the magnet or .torrent link in their primary results page.
instead, they are available only on the corresponding torrents' detail page.
this means that when jackett is compiling a list of torrents from the results page, it cannot resolve the link until you click on the download button, at which time the torrent details page is fetched and the link fetched.
you may ask why jackett does not pre-fetch the torrent's details page and resolve the download link?
the answer is that this would mean that jackett would have to fetch the details page of every torrent listed in the search results, and the additional network hits on the web site could cause said site to think you are generating a DDoS attack and blacklist your IP.
