### ISSUE TITLE
LimeTorrents not returning Proper torrent link when selected "iTorrents.org" option

### ISSUE THREAD

**Issue by nafr1** [Jackett/Jackett#6344]
LimeTorrents indexer is not returning the torrent file link when iTorrents.org is selected in the settings option. Although the LimeTorrents website search page does provide direct link to .torrent file (on the first page).

**Comment by garfield69** [comment]
when you search for something on limetorrents, and you get search results, the download link limetorrents provides is for itorrents.org
![image](https://user-images.githubusercontent.com/6933240/68711113-dbc1d700-05fd-11ea-952c-c76febd3c077.png)

but because limetorrents does not allow empty search queries, when you use the jackett dashboard search, or click on the indexer's TEST button, we go to the /index.php?page=latest100 on limetorrents to get the latest torrents, so that the TEST does not fail, and empty searches can show the latest torrents instead of an error.
however the latest100 page does not have download links in the search results.
![image](https://user-images.githubusercontent.com/6933240/68712354-6d324880-0600-11ea-94d2-863f4a7449bd.png)

so for this reason, we rely on the torrents details page in limetorrents  to get the .torrent link they provide. The torrent-details page also has the magnet link, which is not available on any of the search results pages of limetorrents.

the .torrent link on the limetorrents torrents-details page is exactly the same as the one on the torrents search results page.

the only reason why it may not work sometimes on limetorrents, is that they are using the itorrents.org service, which does not guarantee that the magnet hashkey you request from them is available.
it can take itorrents.org sometime to load the .torrent file on their database from the moment a torrent is posted on the web (anecdotally, up to 4 hours from web posting to available in their DB).

So when you do a search for a particularly recent torrent, using the itorrents.org download link may fail to fetch a .torrent file, and it does not matter if you used the link on the limetorrents search result page, or the one from the torrent-details page.

But once itorrents.org have it on the DB, then it should work, as will the jackett download link for that indexer.

there is nothing jackett can do about this.
