### ISSUE TITLE
New Autoupdate failed to restart service/Causing to crash.

### ISSUE THREAD

**Issue by neuman1812** [Jackett/Jackett#6363]
Jacket failed to restart after update:  Logs are attached.
[jackup.txt](https://github.com/Jackett/Jackett/files/3844288/jackup.txt)

[jacklog.txt](https://github.com/Jackett/Jackett/files/3844291/jacklog.txt)

A manual update to Version 0.12.990.0  worked.  I have turned off auto-update.

**Comment by garfield69** [comment]
when was the last time you ran the systemd install script?

**Comment by neuman1812** [comment]
Im not sure what script you are talking about.  The last time I upgraded jacket was with issue #5208.  

I just downloaded the gz and copied over the files.  It's how I always installed it.

**Comment by garfield69** [comment]
im talking about `install_service_systemd.sh` script

are you manually starting jackett up  with the `./jackett` command, or are you using systemd to autostart the jackett service when ever you boot your system up?

**Comment by garfield69** [comment]
FYI the reason i am asking how you launch jackett is because this has a bearing on the updater.
you see, if you launch jackett manually, then there is a chance that you may start it up while an auto-update is still in progress. in which case this could interfere with the update, and cause jackett to subsequently crash with missing modules.

if you are using systemd to launch the jackett service, then part of the fix for #5208 was to update the jackett systemd script, which should prevent the service from being started while the updater is busy updating.
to update (or install the systemd service) you open a terminal, cd to the jackett binaries folder `/opt/Jackett` and run the script `sudo ./install_service_systemd.sh`

**Comment by neuman1812** [comment]
> FYI the reason i am asking how you launch jackett is because this has a bearing on the updater.
> you see, if you launch jackett manually, then there is a chance that you may start it up while an auto-update is still in progress. in which case this could interfere with the update, and cause jackett to subsequently crash with missing modules.
> 
> if you are using systemd to launch the jackett service, then part of the fix for #5208 was to update the jackett systemd script, which should prevent the service from being started while the updater is busy updating.
> to update (or install the jackett service systemd script), you open a terminal, cd to the jackett binaries folder `/opt/Jackett` and run the script `sudo ./install_service_systemd.sh`

sorry,  yes I use systemd to start it,  and I did use the install_service from #5208.   But Im pretty sure I made a mistake on my end.   

I had to move my config's due to a drive failure.  when I did, the original jackett.service file was copied back.  my execstart line had the  mono jackett.exe .... it looks like your script changes that over to a jacket_launcher.sh which fixes the issue.

Sorry about that. . my bad.
