### ISSUE TITLE
Search incomplete on Xthor

### ISSUE THREAD

**Issue by virtualfrancky** [Jackett/Jackett#6392]
Hi, I have a strange problem going on since several weeks now, the search on Xthor, doesn't give me back the full answer, for example, if I give a search on " The Walking dead", on Xthor I only receive matches for French or Multi.French, and only from the lastest 15 days. Of course a search on Xthor directly, give me all the episode available.
I dont have the problem on other trackers.

Jackett version : 0.12.1007.0

**Comment by garfield69** [comment]
I don't have an account on Xthor so I can not research this.
I do note that the xthor config has options for setting the way MULTI, ACCENT, ENHANCED ANIME SEARCH, and FREELEECH affect results.
is it possible any of these configs are making a difference to your results?

@Tawagot0  as the last contributor (28 days ago) to make a change, would you like to research and assist this user? (see OP for details).

**Comment by virtualfrancky** [comment]
What can I do to help you solved this.
Actually I have just activated the option replace Multi by Multi.French and that's all I can try again by removing this option, and will let you know.

**Comment by garfield69** [comment]
if Tawagot0 does not respond in a timely manner for you, then I guess you could send an invite to garfieldsixtynine @ gmail.com 

But be aware that if the site requires me to actively contribute to their community, then I may well get my account disabled eventually, because since I am supporting over 200 indexers, I don't have the time to keep any private sites happy with uploads/downloads/ratio maintenance/whatever.
So as long as that does not impact your status on the site as the invitee, then go ahead.

Also, as this indexer is written in c#, while I can do research and possibly discover the problem, unless its a fairly simple c# change, I may not be able to provide a fix if it turns out to require significant c# coding.
My speciality is supporting the yaml indexers and I am not a c# dev.
But I will certainly give it a go if I can manage it.

**Comment by virtualfrancky** [comment]
Ok let's wait a few days, and if there is no answer, I ll give you an invite so that you can have a look at the problem.

**Comment by evolfox** [comment]
Hello,

I have the same problem. For example, when I search for "Zombieland", it finds the first film but not the second film.

**Comment by evolfox** [comment]
Ok sorry i found. This is the "Accent" setting which was set to 1. It says "Accent is the french accent you want. 1 for VFF (Truefrench) 2 for VFQ (FRENCH, canada). When one is selected, the other will not be searched. "

**Comment by RoloSoze** [comment]
@JigSawFr Can you provide an Xthor invite for @garfield69 to resolve this issue?

**Comment by garfield69** [comment]
I would rather not waste an invite.
Xthor is c#, best left to the c# specialists.
if an invite is available ask @cadatoiva  or @ngosang  is they are interested.

**Comment by RoloSoze** [comment]
> 
> 
> I would rather not waste an invite.
> Xthor is c#, best left to the c# specialists.
> if an invite is available ask @cadatoiva or @ngosang is they are interested.

My bad. I should have double-checked what type of tracker it is :)

**Comment by JigSawFr** [comment]
I can take a look, but this problem is not new! It seems related to the API itself :/

**Comment by obyy** [comment]
The API's xthor limit 1 request every 2 seconds. 
If I enable cache developer in jackett, it's works for me 🙂

**Comment by RoloSoze** [comment]
> 
> 
> The API's xthor limit 1 request every 2 seconds.
> If I enable cache developer in jackett, it's works for me 🙂

@JigSawFr Does this fix the issue for you?

**Comment by Tawagot0** [comment]
Sorry for the delay @garfield69, i didn't read my emails attached to this GitHub account.
I just looked for a good hour, the problem is completely normal now.

If you look closely, when you search with Jackett the number of results is limited to 32 results:

![firefox_5eJ86XtucX](https://user-images.githubusercontent.com/26726263/83179263-10245d00-a122-11ea-9fc8-bcb9e469ffb4.png)


According to the Xthor API documentation, 32 results correspond to a result page, so it is normal that you cannot find French with Jackett, because directly with the XThor API on page 0 (or without parameters for "page") it will find nothing.

However, by modifying the page parameter by setting it to 1:
`https://api.xthor.tk/?passkey=XXXXX&search=the%20walking%20dead&category=&freeleech=&tmdbid=&size=&accent=&price=&page=1`

It does find French audio, quite simply because these results exceed the first 32.

This is therefore another problem, it would be necessary to implement the possibility of having all the results for a given search, the problem is that there is nowhere indicated the number of pages for this search.

I'll contact the one who took care of the API to see what we can do, I'll keep you posted!

**Comment by Tawagot0** [comment]
No way to add in the API for the moment to add the number of results for a search or the number of pages.

There is surely a way to retrieve most of the results for a search in:

- [ ] Looping through the pages and incrementing a variable for the number of pages until the API no longer returns an object: torrents

- [ ]  Putting a timeout of 2000ms between each page change
- [ ] Limit the number of pages so that the search for performance concerns (search too long compared to the number of pages)

To take an example, a general search for "the walking dead", there are 49 pages with a "torrent" object, so if you had to search everything with the timeout it would take more than 100 seconds to have all the results.

Maybe needs C# dev (@ngosang who will surely be able to give better ideas than mine)
I can gladly provide an invitation or documentation if needed.

**Comment by ngosang** [comment]
In some trackers you can change the number of torrents per page in the profile configuration. If it's possible, increase the number to 100 (we can add a note in Jackett). If there are unrelated results in the response, maybe we can improve the matches searching only in title or something like that.

> Looping through the pages and incrementing a variable for the number of pages until the API no longer returns an object: torrents
Limit the number of pages so that the search for performance concerns (search too long compared to the number of pages)

We are doing this in some trackers, but it's only feasible if 2 o 3 pages are enough. We can't DDoS the website.

> Putting a timeout of 2000ms between each page change (due to limit 1 request every 2 seconds)

This can be done automatically by Jackett if required. https://github.com/Jackett/Jackett/blob/e00861b9ec495bc3bcd104f74109d2321479e51f/src/Jackett.Common/Indexers/YTS.cs#L55

**Comment by Tawagot0** [comment]
Thanks for your help @ngosang !
PR is available: #8815 
Surely changes to be made, i limited the number of results to 100.

**Comment by awsms** [comment]
I bump this issue because there is another thing about the search on xthor: Jackett can't find dead torrents (even if "Show dead torrents" is ticked).

**Comment by Tawagot0** [comment]
> 
> 
> I bump this issue because there is another thing about the search on xthor: Jackett can't find dead torrents (even if "Show dead torrents" is ticked).

The API doesn't return any results with dead torrents.
Regarding the merge request I will work on it again in a short while, sorry!

**Comment by ngosang** [comment]
I can work on this if someone sends me an invitation.

**Comment by RoloSoze** [comment]
@ngosang Check your Hotmail.

**Comment by ngosang** [comment]
@RoloSoze I looked at the code and I can't fix this issue without changes in their side. The website allows to increase torrents per page to 100, but we are using the api and that change doesn't apply. There is no way of request 100 torrents in the api. It's possible to request several pages but they have a limit in the number of requests per second and we will have to wait... I don't like it, if there is a limit is because they don't have enough resources to serve the requests.

Could you ask in this forum if they can add a new parameter called `max_results` so we can request 100 torrents in one call? You are better than me with words. Thank you!
https://xthor.tk/forums.php?action=view_topic&topic_id=5456&page=3

**Comment by RoloSoze** [comment]
> 
> 
> @RoloSoze I looked at the code and I can't fix this issue without changes in their side. The website allows to increase torrents per page to 100, but we are using the api and that change doesn't apply. There is no way of request 100 torrents in the api. It's possible to request several pages but they have a limit in the number of requests per second and we will have to wait... I don't like it, if there is a limit is because they don't have enough resources to serve the requests.
> 
> Could you ask in this forum if they can add a new parameter called `max_results` so we can request 100 torrents in one call? You are better than me with words. Thank you!
> https://xthor.tk/forums.php?action=view_topic&topic_id=5456&page=3

@JigSawFr Are you willing to help us out with this using your connection over at Xthor? I don't speak french unfortunately :(

**Comment by ilike2burnthing** [comment]
Got you covered 😋 
```
Pouvons-nous avoir une option pour 100 torrents par page s'il vous plaît?
```
No...? Ok maybe not...
