### ISSUE TITLE
[nostalgic] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by mouzzampk2014** [Jackett/Jackett#6405]
Hi team, 
Was working fine few days ago. I restarted the system and remove the docker but same output. 
Thank you

**Comment by garfield69** [comment]
works for me on my win10 jackett 0.12.1014
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.

**Comment by garfield69** [comment]
had this happen to me today.

I've take a look at the site's login form and I see that they have removed the option `keeploggedin` 
which means that the current version of the jackett indexer does not think it needed to login since the cookie was still good as far as it was concerned, but the site is obviously expecting jackett to login again and returning not-authorised when jackett tried to do the torrent search.

I have dropped the keeploggedin option from the indexer with jackett 0.12.1024

after upgrading, you may need to trashbin the nostalgic indexer and add it afresh to ensure that the old cookie is dropped.

then we shall see in a couple of days if that has solved the issue,

**Comment by mouzzampk2014** [comment]
Thanks @garfield69 working fine here. Thanks again. Much appreciated
