### ISSUE TITLE
[tekno3d] Login Failed, got redirected. (Config)

### ISSUE THREAD

**Issue by waring192** [Jackett/Jackett#6430]
When logging in via the website there is a captcha that asks you to identify an object followed by clicking on an X i.e. - - X- - - -

This captcha is redirecting me so I cannot login to use the tracker via the Jackett settings.

**Comment by garfield69** [comment]
the cardigann processor should be able to automatically solve the simplecaptcha challenge, as well as the X in a box, so it does not bother to display these in the indexer's login config.
so something else is going on.
But since I do not have an account on this site I cannot test this for myself.
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

The enhanced log may yield a clue to what may be going on.
Thanks.

**Comment by waring192** [comment]
This is my log from when trying to add it. I deleted the log just before clicking add. 

https://pastebin.com/T6aj6NxE

**Comment by waring192** [comment]
Not sure if the last had Enhanced Logging enabled but this one deffo does:

https://pastebin.com/tPYyuD4a

**Comment by garfield69** [comment]
use your browser to login to tekno3d and clear any outstanding private mail and any outstanding alerts/notifications.
the jackett login is being redirected by the site to the `pm_system.php` page instead of the expected `browse.php` page, so the jackett post-login-test fails.

**Comment by garfield69** [comment]
Oh, BTW, anytime you see entries with `date-time Debug` in them you know you're looking at an enhanced log ;-)
