### ISSUE TITLE
[Windows] Starting Jackett service after update when running as Virtual Service Account

### ISSUE THREAD

**Issue by rg9400** [Jackett/Jackett#6435]
After learning about best practices for application services in a Windows environment, I realized that running services as `LocalSystemAccount` is akin to running the service as `root` on Linux. I wanted to create a more secure environment, so I modified to Jackett service to run as a Virtual Service account, i.e. `NT Service\Jackett`

Jackett works fine as such, but when it updates, it fails to start the service back up. The update itself is successful. I looked into the event logs, and noticed the below error when Jackett failed to start back up. The IDs correspond to `Immersive Shell`. Is this something that could be fixed at Jackett's end, or is it essential to run the service as an Admin/LSA?

```
The machine-default permission settings do not grant Local Activation permission 
for the COM Server application with CLSID {RedactedID} 
and 
APPID {RedactedID} 
to the user NT SERVICE\Jackett SID (RedactedID)
```

Jackett Version 0.12.1038.0

**Comment by garfield69** [comment]
you are breaking new ground as no one has previously tried running the windows jackett service with a non-admin privileged account before.
I suggest you try Googling `machine default permission settings do not grant Local Activation permission` and see if you can decipher some of the microsoft help support hits that supposedly show how you could grant permission to that a/c you've chosen to use for jackett if you customise those notes correctly. The ones I've found look complicated to me, and I don't have the free time to spend on this one.

**Comment by rg9400** [comment]
That's totally fair. It would help to know how Jackett is restarting itself after an update on Windows. The update itself is successful, so the issue seems to be isolated to starting the service back up again after shutting it down and updating. Hopefully, it's just a simple permission to add to the VSA. In the meantime, I am just going to run it as an admin account.

**Comment by garfield69** [comment]
>It would help to know how Jackett is restarting itself after an update on Windows.

I'm the wrong person to ask about that, I did not write the C# code and am not a C# dev.
best I can do is point you to the updater code that appears to have something to do with starting the service, using what appears to be several methods depending on set up conditions.
https://github.com/Jackett/Jackett/blob/1337129cb6f6874704142b5fe7f75f39b689bd11/src/Jackett.Updater/Program.cs#L397-L455

**Comment by ultnrg** [comment]
I've just installed Jackett and configured it with a limited windows account (one that only has "log on as a service rights") and run into the same issue. The user account has full access to start/stop/restart the service (granted using subinacl) but does not have admin rights to the box.

Looking at the code, it seems like it's checking if the user is an admin and if not, trying to run the console. Then if it fails running the console (probably because the user account has no interactive logon rights), it spits out an error saying failed to get admin rights.

I'm no c# expert but the windowsService.Start() method should probably be wrapped in a try/catch block rather than checking if admin exists or not.

**Comment by garfield69** [comment]
Jackett  0.16.1138
