### ISSUE TITLE
[BTDB] Is not returning results

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#6448]
Search mp3 in https://btdb.eu returns 476,824 results
Search mp3 in Jackett return 0 results.

The same happens with all searches in Jackett for this site.
The test button is working but shouldn't be. It's a good idea to make a search that we now returns results and check the results list is not empty.

 **Jackett version**:  0.12.1042.0

**Comment by garfield69** [comment]
looks like btdb have shortened their **search** keyword to just **s**
so https://btdb.eu/?search=mp3&sort=time is now https://btdb.eu/?s=mp3&sort=time

and because btdb does not allow an empty search string like https://btdb.eu/?s=&sort=time the jackett indexer had to resort to using https://btdb.eu/recent as a way of checking that the site is up and to get some search result back.
the TEST button is the equivalent of a search with no keywords.

but when jackett does a **http get** with the url https://btdb.eu/?s=mp3&sort=time the btdb site does not respond and the request times out. I do not understand what is going on.
btdb is happy for jackett to issue https://btdb.eu/recent so that is confusing.

**Comment by ngosang** [comment]
https://btdb.eu/?s=mp3&sort=time is protected by Cloudflare. Just open the link in private mode.

**Comment by garfield69** [comment]
yeah what?
I just code the jaml statements for the cardigann processor. I don't amend the cardigann c# code.
would not have a clue how to change the cardigann processor to do a http get in private mode.

**Comment by ngosang** [comment]
I explain bad myself. I don't want you to open private mode with Jackett.
The url https://btdb.eu/?s=mp3&sort=time is working but it has Cloudflare.
It's possible to keep Cardigann but bypass Cloudflare?

**Comment by garfield69** [comment]
see if btdb works for you with Jackett 0.12.1053 when you search for mp3

**Comment by ngosang** [comment]
It's working. Thank you!
