### ISSUE TITLE
1337x does not return results in any category of music or games

### ISSUE THREAD

**Issue by 97carmine** [Jackett/Jackett#6462]
All categories show results except for music and games

**Jackett version**:  0.12.1053.0

**Comment by garfield69** [comment]
this is another site that does not support searching without keywords.
so as a compromise we lookup the latest pages for movies and tv and present those.
we do not pull up the latest for the the other category pages because too many requests at one time could trigger an anti-ddos block.
but if you know what you are looking for the searches can pull results for music or games.
