### ISSUE TITLE
Corsaro Nero Issue

### ISSUE THREAD

**Issue by apathetic6** [Jackett/Jackett#6463]
Hello, i have an issue with Corsaro Nero Index.

Works well for any episode form 1 to 9, becose the query will be "Westworld 2 9" and when there are only numbers with one digit corsaro nero ingnore them and return all results....

Es:
https://ilcorsaronero.pro/advsearch.php?&category=15;5;&search=Westworld%202%209&order=data&by=DESC&page=0

For number > 10 this does not work becose the search query is "Westworld 2 10" and corsaro nero try to match 10 as single word for the search results

Es:
https://ilcorsaronero.pro/advsearch.php?&category=15;5;&search=Westworld%202%2010&order=data&by=DESC&page=0

It is possible to fix it ? Like for example do not send numbers to corsaro nero so we get all result ?
Thx

**Comment by garfield69** [comment]
@jorman you've been making updates to this indexer, care to take a look?

**Comment by Jorman** [comment]
Ok, I'll take a look, maybe a bad regex

**Comment by Jorman** [comment]
@apathetic6 
What are you trying to achieve?
Because if I search Westworld 2 10 is because I'm searching season 2 episode 10 but
I just noticed that if I search Westworld 2x10 I get the right result

I'll make some test to see if possible to handle S01x01 and S01E01 in one shot

@garfield69 do you remember some other traker with same schema?

**Comment by garfield69** [comment]
pretty much all the Italian ones I guess
passionetorrent.yml, arabafenice.yml, hdtorrentsit.yml, girotorrent.yml, ilcorsaroblu.yml, shareisland.yml

**Comment by apathetic6** [comment]
I'm doing also some test and the name formata is not always the same:

Es.

2x10
s02e10
s02x10

**Comment by apathetic6** [comment]
IMHO the safeest option is to not pass any number to corsaro nero.

**Comment by Jorman** [comment]
@garfield69 
I see, but all with the same "problem"

@apathetic6 
Is the main problem, on Italians trackers (surely on other trackers), the releases are not so well formatted, so you can find various kind of releases, for that reason the main concept is to
Take the search query that is S01E01
Remove S and E
And later filter the results back again
Is the main reason because I ask, some time ago, on sonarr to modify a little the query in order to make Jackett do the dirty works with a kind of replacement table language by language. But sonarr guys never wanted this, I don't know why. You can find the discussion here:
https://github.com/Sonarr/Sonarr/issues/2779

If garfield have some better idea ... maybe is the right time to make or ask for changes

**Comment by apathetic6** [comment]
Can we pls do not send any numbers and only the Title of the serie to Corsaro Nero search query?

This will be a quick workaround :) 

We will get all the result for the current serie like when we query with single numbers (Becose Corsaro Nero Ignore single number in search query), but Sonarr is able to display only the right result.

**Comment by garfield69** [comment]
sure, you'll get results for the current series, but you will prevent anyone else who want to fetch older episodes from getting results, because if the series has multiple seasons, then older episodes may well be beyond the first page that jackett fetches.
IMO sites that don't enforce a standard format for their episode listing are a pain in the backside. You are never going to be able to code for all variations. The best you can do is pick the one most popular format and code for it. The rest is just not worth the time and effort to handle.

**Comment by apathetic6** [comment]
So Is It possible to map variations ? Is It possible to do from configuration or a source code change Is required?

**Comment by garfield69** [comment]
in most instances it requires changes to source code because the cardigann processor is not coded to provide conditional blocks.

**Comment by Jorman** [comment]
@apathetic6 
I can tell you how to remove the numbers but:
1. you've to manual modify your definition files
2. each update you'll lost the modification
3. consider what garfield said, you'll have difficult to find older episode

**Comment by garfield69** [comment]
to that end, there is nothing preventing you from having your own custom version of the ilcorsaronero indexer.
just change the **site** andthe **name** keys to mycn in the yaml code, the **filename** to mycn.yml and jackett will load it the next time you restart. and the updater will leave it alone too, since its not part of the official set.

**Comment by apathetic6** [comment]
Thx guys :) I removed the numbers and now works great :)
