### ISSUE TITLE
[req] chdbits.co

### ISSUE THREAD

**Issue by killerqueen619** [Jackett/Jackett#6475]
I am req the CHDBIT.co
web : https://chdbits.co

**Comment by garfield69** [comment]
this indexer already exists. find it in the add-indexers page under **CHDBits**

**Comment by killerqueen619** [comment]
http://prntscr.com/q5dv6o
there no CHD i have find it

**Comment by garfield69** [comment]
odd, the indexer has been in jackett since 31 Dec 2016

Please provide the **full enhanced log** file so I can take a look at your jackett startupo and see if I can spot any reasons.
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.

**Comment by killerqueen619** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/3915028/log.txt)

**Comment by garfield69** [comment]
the log shows that chdbits.yml was loaded.
```
2019-12-03 06:23:59.3981 Info Starting Jackett v0.12.1061.0 
2019-12-03 06:24:06.6848 Info Loading Cardigann definition C:\ProgramData\Jackett\Definitions\chdbits.yml 
```
so if it is not in the add-indexer page, then this means you have already added it.
have you checked your Jackett dashboard active page for it?

**Comment by killerqueen619** [comment]
sir its fixed
thank u!
i try uninstall and re-install
