### ISSUE TITLE
[yggcookie] Login Failed, got redirected. Try changing the indexer URL to https://www2.yggtorrent.ws/. Updated site link, please try again. (Config)

### ISSUE THREAD

**Issue by chripink** [Jackett/Jackett#6531]
Hi, 

Since YGG changes it's domain to yggtorrent.ws I have this error. 
The URL is adapted by jacket itself in the configuration but I still have tis issue
![image](https://user-images.githubusercontent.com/17579251/70387772-96e55200-19a9-11ea-8627-cf9990a6caac.png)
Any idea ?
YGG seems to be really hard to integrate : o :( 

Thank you,
Christophe

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/6473#issuecomment-560978023

**Comment by bxlouis** [comment]
@garfield69 This is not the same error. The news url worked for a couple of days but now this error is thrown.

**Comment by garfield69** [comment]
works for me.
![image](https://user-images.githubusercontent.com/6933240/70392721-e4180100-1a47-11ea-8a4f-218b7d025d79.png)

suggest you do the following:
1. make sure you are on at latest jackett 0.12.1084 , preferably the latest on 0.12.1099
2. use your jackett dashboard to trashbin your yggcookie from the active page.
3. use your browser to access https://yggtorrent.ws/
4. login
5. access the search page https://www2.yggtorrent.ws/engine/search?do=search&attempt=1
6. grab the cookie
7. add the yggcookie to your jackett dashboard by clicking on the wrench on the add-indexer page
8. make sure the **Site Link** to set to `https://yggtorrent.ws/` and 
9.that the **Search and download URL** is set to `www2.yggtorrent.ws`
10. paste the cookie
11. Click **OKAY**
12. if you get an error, click **CLOSE** then edit again and click OKAY. it should save the second time.


OR
you could just use the YGGTorrent indexer which is simpler.

**Comment by bxlouis** [comment]
I'm using the YGGTorrent indexer, not the cookie one.
I am doing exactly what you are suggesting, retried multiple times and still got the "Login Failed, got redirected" error. 
Not sure what's wrong with YGG Torrent as every month there is a new error with Jackett. All other indexers work perfectly though!

**Comment by garfield69** [comment]
>I'm using the YGGTorrent indexer, not the cookie one.

@bxlouis  OK, you confused me because you chose to comment on a ticket open for YGGCookie.

however, no problem.
if you want me to help with this I am going to need to see your enhanced log so I can take a look at the problem in more details.

Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.

>Not sure what's wrong with YGG Torrent as every month there is a new error with Jackett

YGGTorrent in particular is a pain in the backside, because unlike the other 400 indexer that I maintain on Jackett, YGGTorrent is the **only one** that uses two different addresses for its site, one for the login, and another for the searches. :-(

**Comment by bxlouis** [comment]
@garfield69 Thank you for your support!

> @bxlouis OK, you confused me because you chose to comment on a ticket open for YGGCookie.
Yes, sorry about that, I saw the issue on github and did not want to open a duplicate, I should have mentioned it!

Please find the log file below.

I first had an error, closed, reopened the settings and got the "got redirected". Cf. screenshot below.

![Screenshot 2019-12-08 at 20 48 14](https://user-images.githubusercontent.com/4128333/70395190-99bd6280-19fc-11ea-83ee-32904c5dffdf.png)

I am running Jackett v0.12.1099.0 with Docker on a Synology NAS. 

[log.txt](https://github.com/Jackett/Jackett/files/3937080/log.txt)

**Comment by garfield69** [comment]
@bxlouis  the log shows `2019-12-08 20:40:45.6256 Debug WebClient(HttpWebClient2NetCore): Returning TemporaryRedirect => https://www2.yggtorrent.ws/user/disabled`

looks like your account has been disabled :-(

**Comment by bxlouis** [comment]
@garfield69 indeed this is true. The sad part is that I could have guessed it by myself but I am so used to having error with YGGTorrent - and you explained why - that I did not even think about checking my ratio, which is the reason why the account was disabled.

![Screenshot 2019-12-09 at 01 36 24](https://user-images.githubusercontent.com/4128333/70399438-54ad2680-1a24-11ea-96d0-d704c50920bc.png)

Do you think it would be possible to provide the user with a clearer error message in this case, ie. "Your account is disabled."? Based on my experience with Jackett, it is not the first time similar errors are raised on Github with the same root cause. I am sure it would lower the number of YGG-related tickets and save you a lot of time!

Anyways, thank you very much for your quick support and keep the good job going!

**Comment by garfield69** [comment]
unfortunately  not.
YGGTorrent's own login page has a perfectly good error message layout which jackett's ygg indexer is set up to trap
```yaml
    error:
      - selector: "#login_msg_pass[style=\"\"][style] > center"
      - selector: "#ban_msg_login[style=\"\"][style] > center"
      - selector: "#login_msg_mail[style=\"\"][style] > center"
      - selector: a[href$="/user/disabled"]
```
but the web site chooses not to use any of them, instead performing a redirect which jackett's cardigann processor interprets as a general login failure, since it was not delivered the search page it was expecting.

Jackett can only work with what it is given and the reality is that the YGGTorrent site is poorly designed :(

**Comment by chripink** [comment]
> [#6473 (comment)](https://github.com/Jackett/Jackett/issues/6473#issuecomment-560978023)

Hi Garfield, 

Thank you for your answer. I have tried another time and now it's working. I don't understand why it was not working the firsts times... 
Sorry for disturbing you. And thank you for your reactivity :)

Christophe

**Comment by bxlouis** [comment]
@garfield69 Thank you very much for you detailed response!
Really nice to get a full understanding on what is going on.
Cheers!
