### ISSUE TITLE
Torrent9 (and its clone) not working with sonarr

### ISSUE THREAD

**Issue by pasnox** [Jackett/Jackett#6559]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
It's not possible to add torrent9 based indexers to sonarr, test always fails. It works fine from radarr.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

(At the bottom of your Jackett Dashboard page) **Jackett version**:  0.12.1099.0
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**:

-------------------------------

**Comment by garfield69** [comment]
this is because torrent9 does not support empty searches. 
so the Jackett indexer fetches the top_torrents page from the site instead.
however, this page returns just movies (torznab category 2000) and Sonarr is expecting TV (Torznab 5000).
so, to fool Sonarr into passing the test you need to set your Sonarr Indexer categories to `2000,5000`

**Comment by pasnox** [comment]
Thanks
