### ISSUE TITLE
[Torrentland] Episodes not showing at Sonarr

### ISSUE THREAD

**Issue by vinanrra** [Jackett/Jackett#6570]
When i do a manual search at Jackett if found the episodes:

![imagen](https://user-images.githubusercontent.com/4247187/70528696-18c2b000-1b4f-11ea-8a7c-9d19f1b69b36.png)

But when i do search at Sonarr never find me an Episode:

![imagen](https://user-images.githubusercontent.com/4247187/70528721-2841f900-1b4f-11ea-9f90-ad70b5bc704b.png)

Its seems like there is a problem with episode format because Torrentland uses:

La materia oscura (2019) **T01E06** AMZN WEBDL 1080p ESP AC 3 5 1 ING E AC 3 5 1 x264 Eml HDTeam Series

And i think that need a change before reach Sonarr.

I have been trying to fix myself but i have 0 idea of how to do it and didnt fix it.

**Comment by garfield69** [comment]
yes, the Torrentland indexer does not currently have any support for converting Txx into Sxx for searches, and converting the results back again.
I do not have an account on this site so I cannot research this, or test my changes.
I have added this straightforward swap with jackett pre-release 0.12.1133, try it out. 
But if there are more complications then I cannot help without an invite or account to test with.

**Comment by Jorman** [comment]
@garfield69 
I saw,by pure chance, this issue and is the perfect example on why we need a simple and unique conversion table, for each tracker in order to stop to try to make it works every time.
Maybe you know Marcus on Sonarr side, to try to speak with it?

**Comment by vinanrra** [comment]
> yes, the Torrentland indexer does not currently have any support for converting Txx into Sxx for searches, and converting the results back again.
> I do not have an account on this site so I cannot research this, or test my changes.
> I have added this straightforward swap with jackett pre-release 0.12.1133, try it out.
> But if there are more complications then I cannot help without an invite or account to test with.

I will test it and I think I have invites so if it's not working I can send you one.

**Comment by garfield69** [comment]
@jorman nope, I am not involved with Sonarr and don't know marcus.
And please don't be offended, but I really don't care to get involved in this kind of thing. 
IMO there are not consistency with any of the non-English torrent sites in how they present their titles, and trying to get an common table of conversions for Spanish, Russian, Italian and Chinese sites is just a headache that will suck what little enthusiasm I have for this project away.

**Comment by vinanrra** [comment]
@garfield69 Im writing the owner of the site and will see if he can invite you, and where should i send the invite?

**Comment by Jorman** [comment]
@garfield69 
Not offended at all, sorry if I asked you, you know I'm not a programmer, so maybe I think that one thing is easy to do, but in reality is not. Just to speak, I don't "want" a common table, I just hope in a table where the user itself specify all the conversion for the tracker, in order to always use the unified convention S01E01. In that way is the user that have to specify that S01 for that tracker became T01 and so on. But, like I said maybe is not so simple.
I trust in your experience.

**Comment by garfield69** [comment]
@vinanrra  send an invite to garfieldsixtynine @ gmail.com

**Comment by garfield69** [comment]
@jorman im not a c# developer either.
While I can do simple fixes to C# code, I am not up to, or interested in leaning how the complicated Jackett app works or dealing with the complicated c# indexers that exist for some of the sites (mejortorrent springs to mind) that look like a confusing pile of spaghetti in a smelly sauce.

But in general I think asking the **user** to maintain a table is the wrong approach. It should not be up to the user to fix an indexer, they can expect it to work out of the box, after all, that is what jackett is providing, a proxy to allow other apps to access sites so that they themselves do not have to code solutions for.

And as far as Sonarr is concerned, I'm certain that they are only interested in maintaining the indexer that they have built into Sonarr. Any Indexers that a user adds to Sonarr via Jackett, would, as far as Sonarr is concerned, be Jackett's problem if they don't work.
Sonarr is geared for the English language and for English torrent naming standards and they probably do not care about the rest.

As for Jackett, any indexers that we create for non-english sites, are mostly customised by adding the regexp terms to the yaml. And in most cases that is good enough.
There is room for improvements, but if they require amending the cardigann processor that handles the yaml indexers, then we are back into C# coding territory and that is out of my experience or interest.

**Comment by RicardoVelaC** [comment]
@garfield69 I send you an invitation check your inbox

**Comment by garfield69** [comment]
registration and login successful. thank you.

**Comment by vinanrra** [comment]
@garfield69 thx for the fix now it's working flawless.

**Comment by garfield69** [comment]
I haven't published the jackett release yet... are you running from your own source compilation ;-) ?

**Comment by vinanrra** [comment]
Yes :yum:

**Comment by Jorman** [comment]
@garfield69 
Understood, like always, thank you for your works!
