### ISSUE TITLE
Redesign tracker list

### ISSUE THREAD

**Issue by kaso17** [Jackett/Jackett#658]
In my opinion the current tracker overview (3 trackers per row) is pretty annoying.
The tracker logos just take away a lot of space and many are simply to small to read.
I would prefer a simpler list/table view (1 tracker - 1 row) with no logos at all.

**Comment by ideaprison** [comment]
I agree. And I'd be willing to think up a better design.

**Comment by kaso17** [comment]
I've started to work on an alternative list view:
http://i.share.pho.to/fa38cfc8_o.png

@flightlevel and @JigSawFr and everyone else: Would appreciate your opinions.

Anyone likes the current view?
If not I would completely remove it.

**Comment by kaso17** [comment]
Here's a screenshot of the "add tracker" dialog:
http://i.share.pho.to/0381fc0f_o.png

**Comment by flightlevel** [comment]
Looks great @kaso17 
I agree the list is better. When there were only a dozen trackers the logos worked well because of the limited options but Jackett has definitely outgrown that now.

Tracker list: Great

Add Tracker: I'd be inclined to drop the Description column, 90% of the descriptions are pretty meaningless eg. Your home now, Modern indexer, ILT, PassThePopcorn, Friendliness are all useless and just make it look a bit untidy. Other options, try and fix the descriptions, not that easy to describe some trackers though. Other option maybe we just use the Torznab parent categories as the description eg TV, movies eg TV ???

**Comment by armani316** [comment]
@kaso17 While I do miss the logos/banners, I have to agree with @flightlevel. This is a much more practical design, and yes, the empty space should be used to specify whether a tracker is ratio-based or ratioless, and detail key stats (ratio, total uploaded, total downloaded, BP's). 

I also think the descriptions in the 'add tracker' dialog are random and meaningless. Maybe replace that with 'Category' instead?  i.e. HD, Movies, TV, General, etc.

**Comment by kaso17** [comment]
the latest pre release contains the new interface, would appreciate some feedback if anyone notices any bugs with it.

**Comment by flightlevel** [comment]
Works great here @kaso17 
Nice job!
