### ISSUE TITLE
[torrentland] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by IvanpAEG** [Jackett/Jackett#6595]
**Jackett version**:   Jackett Version 0.12.1146.0 (Docker inuxserver / jackett tag arm32v7-latest)

When I try to test tracker by clicking "test"button, I get the following error
[log.txt](https://github.com/Jackett/Jackett/files/3957890/log.txt)

![imagen](https://user-images.githubusercontent.com/34457043/70749313-5466a100-1d2c-11ea-9bd8-7803671c221b.png)

Neither can search for anything using manual search:

![imagen](https://user-images.githubusercontent.com/34457043/70749371-75c78d00-1d2c-11ea-9e8b-462fd46493dd.png)

**Comment by garfield69** [comment]
you are not getting anything because your html presentation is different than what the indexer is expecting. Seems you are a default style **xbtit_default** ...
When I am logged in to torrentland, I see two styles available, and I've tried both which seem to work  with jackett, **EML HDTEAM** and **Eml Black**.
But maybe if you have not actively chosen either one, you get a third default hidden style, **xbtit_default** ?
So logon to torrentland pull down the **Mi Panel** and click on either the **EML HDTEAM** style or **Eml Black** style then once you get the new presentation, logout.
try Jackett and see if it make a difference.

**Comment by garfield69** [comment]
OH, and BTW, torrentland does not have any episodes from **how to get away with murder**, so that was a bad example to choose ;-)

**Comment by IvanpAEG** [comment]
> 
> 
> you are not getting anything because your html presentation is different than what the indexer is expecting. Seems you are using a default style **xbtit_default** ?!?
> When I am logged in to torrentland, I see two styles available, and I've tried both which seem to work with jackett, **EML HDTEAM** and **Eml Black**.
> But maybe if you have not actively chosen either one, you get a third default hidden style, **xbtit_default** ?
> So logon to torrentland pull down the **Mi Panel** and click on either the **EML HDTEAM** style or **Eml Black** style then once you get the new presentation, logout.
> try Jackett and see if it make a difference.

Worked, so, issue is solved :)
