### ISSUE TITLE
[REQ] TV-Vault

### ISSUE THREAD

**Issue by savahu** [Jackett/Jackett#660]
Tv-vault.me is a tracker specialized in older TV-shows. (2011 and earlier at this moment). 

Please add this into Jackett

**Comment by kaso17** [comment]
Please send an invite to kaso1717 -at- gmail.com and I'll add it.

**Comment by kaso17** [comment]
got it, thank you.

How do you intend to use it?
Which search field should be used best?
Torrent name seems to return a lot of garbage
I currently would tend to strip SXXEXX from the search string and just use the show name search and filter season/episode manually.
Due to the extra processing this is going to be a native Jackett tracker (not a cardigann definition).

**Comment by savahu** [comment]
If I add an old TV show to Sickrage/Sonarr, it would do a search for 'Showname S01E01' to the Jackett indexer, but the search query on TVV seems to only return results for the showname. If you could filter season/episode manually on the page, so that Sickrage/Sonarr integration works that would be great!

I first tried to make this as (my first) Cardigann definition, but struggled with this.

**Comment by kaso17** [comment]
It's "medium" difficulty for Cardigann definitions, definitely not the easiest start.
And in the end it won't work as expected due to the search limitations.
I'll implement it as a native indexer in Jackett and take care of the season/episode translation.

**Comment by kaso17** [comment]
The current implementation now removes SXXEXX from the search string and then uses the show name search.
Results aren't filtered/rewritten currently, please let me know if there are any problems.

**Comment by garfield69** [comment]
removed #12496
