### ISSUE TITLE
[elitetorrent]: Relogin required

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#6602]
Jackett Version 0.12.1175.0
Tracker elitetorrent

The tracker is working fine, but I see this message in the logs after each search. I don't know if we can do something to avoid relogin so often. Btw, it's a public tracker without login :S
```
CardigannIndexer (elitetorrent-biz): Relogin required
```

**Comment by garfield69** [comment]
the site returns up to 30 torrents per page
the indexer attempts to fetch page 2 and page 3 to boost the number returned to 90
however, if page 2 or 3 is not available, the site returns a redirect to main.
the info/debug message for relogin is a result of the redirects.

cannot prevent cardigann logging these, as redirect is a legit response the processor needs to handle.

since its not an error message, I am inclined to ignore it.
