### ISSUE TITLE
[Torrent Downloads] wrong published date

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#6606]
Jackett Version 0.12.1175.0
Tracker Torrent Downloads
Search: gentoo

Torrent Downloads doesn't prove published date. In that cases I think we should put 99y. You are already doing that in Zoogle

**Comment by garfield69** [comment]
the 99y in zooqle is in response to a date of `long ago`.
since zooqle provides dates, this is the only response in this case.

torrentdownloads does not provide ANY dates at all.
the common standard so far in this case is to supply a default datestamp of `now` which is represented as `0m ago` i.e. zero minutes.

IMO I believe is this is an appropriate response to no dates, and better than 99y

**Comment by ngosang** [comment]
@garfield69 My usecase is to have a lot of trackers enabled, search for a tv show and order by published to get latest episodes. Torrent Downloads is flooding the list with a lot of old results because the published time is 2min, lower than real dates from other trackers.
That only happens in this tracker and in those #6607 for different reason.
If you think this case is not common, or that could break third party programs just let as it is. I will disable that tracker.

**Comment by garfield69** [comment]
Since you cannot tell fresh results from old results from torrentdownload after a date-time sort, 
putting its results at the bottom of your list, would in your case, would be tantamount to not having any results from that indexer at all... I would remove that indexer from your list as it has little value to 
 you in your use-case scenario.

The option to return a null or empty publishing date is not advisable as this would break the torznab standard. I believe apps like Sonarr for example, would reject the results.
