### ISSUE TITLE
Wrong published date in some trackers

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#6607]
Jackett Version 0.12.1175.0

When you search "gentoo" in that sites:
* Isohunt2
* TorrentProject2
* KickAssTorrent (kat.li)

Some results have the published date in the web page "just now" and you are setting 2 min. These torrents are really old, I think this is a bug in the sites. Furthermore, they only use the word "just now" in weird torrents. In recent torrents they show "5 minutes"* https://torrentproject.cc/?t=720p

I think we should map "just now" to 99y only in those trackers.

![image](https://user-images.githubusercontent.com/10577978/70837033-834f4680-1e02-11ea-828b-4fe3f7e87585.png)

**Comment by garfield69** [comment]
torrentproject, Isohunt, katli.
Interesting.
All three seem to use `just now` on the main search results page, for torrents whose details page has not yet been browsed.
Once someone has browsed the details page, then a refresh of the main search returns the date.

this means that even fresh torrents (1 second old) could show up with the `just now` tag, not just older torrents.

tricky. 

My first instinct is that since most users look for the latest torrents, treating `just now` as a 0m date would seem a good compromise.

It only becomes a problem when you are looking for older torrents.

Not sure there is a solution here, just a bad fudge:  mark all `just now` torrents as 99y, or leave them as 0m.

Opinion?

**Comment by ngosang** [comment]
@garfield69 I don't know which one is better. Let it as it is.
