### ISSUE TITLE
[enhancement] disable/enable tracker button

### ISSUE THREAD

**Issue by oskameDEV** [Jackett/Jackett#661]
I'd like to suggest a feature where you can disable a tracker from showing up results. 

For example when your ratio is low and you want to control it by only uploading and not adding new downloads.

Added concept below. Depending on the devs interpretation of this feature, you could either see it as putting the tracker off/offline. Or hiding it from the results.

![jackett-buttons](https://cloud.githubusercontent.com/assets/140623/20094724/99a1d6f6-a546-11e6-9eea-3eec8f67af8f.png)

Another option is the filter (funnel) icon, but perhaps most users won't get that one?

*The order is purely to quickly make a concept for this idea.

**Comment by armani316** [comment]
@ideaprison In #813, I proposed allowing users to choose which trackers they'd like search. Not sure if it's relevant to merge these two? If the stats are displayed next to each tracker (#658), the user can decide which trackers to untick/hide.

**Comment by armani316** [comment]
The ratio display part of @ideaprison's suggestion is related to #656. The tracker enable/disable part of the suggestion is related to #813

**Comment by raspdealer** [comment]
Very interested in this one too. Currently a tracker not working well is filling my results with 💩 results.
It will be nice to just have a way to disable it.

**Comment by flightlevel** [comment]
Is this still a request since now you can tick in manual search which indexers you want to search?

**Comment by akaleeroy** [comment]
Yes this is still a request.

Scenario: any specialized private tracker. You have to configure it because of the username and password. But never need to use it for global searches. Only specialized searches where you select it specifically.

Currently the Manual Search solution has too much UI friction for this use case:

1. Enter search query
2. Click Tracker dropdown
3. Tick ☑ **Select all**
4. Hunt down your specialized private tracker (scroll or search)
5. ☐ Untick it
6. Click search

This is way too much user interaction for a search box, especially for software built for search.

Adding this feature would make it possible to do just this:

1. Enter search query
2. Click search

**Comment by cocokola** [comment]
Nov 2016 was the request, it is still not implemented.  Is this because you are only in break/fix mode?   new features don't seem to be a priory, at all.

I have some programming background and could possibly continue, if that is all that is keeping us.

**Comment by RoloSoze** [comment]
@cocokola Yeah it's basically up to the availability & free time of volunteering developers. If you're able to implement this, may I suggest also looking at issue #4804? 

I believe implementing both at the same time will be excellent & will offer great flexibility - The ability to enable/disable individual trackers from the list of configured indexers AND the ability to organize & save them into groups.

I also suggested #4787 which I imagine should be fairly simple to implement. 

Let me know what you think. I'm happy to discuss further! Thank you for your help!

**Comment by nydave69** [comment]
any status?

**Comment by RoloSoze** [comment]
Until this is implemented, what I did as a workaround is that I saved shortcuts for every set / group of indexers that I like to search at any given time.

E.g. Let's say I have a top 10 list of indexers out of all my configured trackers. What I did is just manually searched these for, say, Avengers Endgame 2019, and then saved the URL of that search.

Now next time when I want to search for something else, say, The Irishman 2019, and I only want to search those 10 trackers, I'd open the shortcut I previously saved. The downside is that shortcut will first perform my old/original search (i.e. Avengers Endgame 2019), and when it's done with that, I'll then search those trackers for The Irishman 2019.

I know it's not as smooth & straightforward as enabling/disabling trackers and saving multiple profiles of trackers (https://github.com/Jackett/Jackett/issues/4787#issuecomment-478291833), but at least by saving that shortcut, I don't have to pick those same 10 trackers every time I want to search them specially.

**Comment by akaleeroy** [comment]
Nice workaround, thanks!  
For using as Chrome search engine navigate to `chrome://settings/searchEngines` and Add new search engine:

> Search engine: **Jackett**  
> Keyword: `jackett`  
> URL with %s in place of query:  `http://127.0.0.1:9117/UI/Dashboard#search=%s&tracker=kickasstorrent-kathow%2Crarbg%2Cthepiratebay`  

This is the URL for the general torrent search, using KAT, RARBG and PirateBay trackers, searching all categories.

I would then add search engine entries for specialized private trackers, ones I wouldn't query for regular searches.

**Comment by RoloSoze** [comment]
> 
> 
> Nice workaround, thanks!
> For using as Chrome search engine navigate to `chrome://settings/searchEngines` and Add new search engine:
> 
> > Search engine: **Jackett**
> > Keyword: `jackett`
> > URL with %s in place of query:  `http://127.0.0.1:9117/UI/Dashboard#search=%s&tracker=kickasstorrent-kathow%2Crarbg%2Cthepiratebay`
> 
> This is the URL for the general torrent search, using KAT, RARBG and PirateBay trackers, searching all categories.
> 
> I would then add search engine entries for specialized private trackers, ones I wouldn't query for regular searches.

@akaleeroy Thank you for this. Yes, @buhandanger has already explained this hack to me here: https://github.com/Jackett/Jackett/issues/4787#issuecomment-574751661

While I quite like this workaround, ideally what I want to happen is this:
https://github.com/Jackett/Jackett/issues/4787#issuecomment-575668005

This is because for every Jackett shortcut (i.e. for every set/group of trackers), I assigned a button on the following device:

https://www.elgato.com/en/gaming/stream-deck

I use this deck for a few things, and Jackett's shortcuts is just one of them. Ideally, at least until this feature is properly implemented in Jackett, I want to be able to click on a button on Stream Deck, and have it open Jackett's manual search page, with the set of trackers that I have saved. It does that right now but it first has to search the original search term that I had saved (see https://github.com/Jackett/Jackett/issues/661#issuecomment-574404283), and when it's done with that, then I can search those trackers for what I want. I want to be able to skip that part.

**Comment by dairefagan** [comment]
+1

**Comment by ilike2burnthing** [comment]
[v0.18.7](https://github.com/Jackett/Jackett/releases/tag/v0.18.7) - tags can now be added to indexers to group them together however you want (e.g. in the case of this issue, `enabled` and `disabled`).

You can then filter indexers for searches by these tags. Indexers can also be filtered by type (public, semi-private, and private). The API can also filter by language.

See more info here - https://github.com/Jackett/Jackett#filter-indexers

**Comment by garfield69** [comment]
closing. superseded by tags.
