### ISSUE TITLE
Cannot add MoviesDVDR tracker to Radarr

### ISSUE THREAD

**Issue by 97carmine** [Jackett/Jackett#6613]
After reporting the error in Radarr https://github.com/Radarr/Radarr/issues/3946.

When returning the data does not add the size which prevents it from being added to Radarr.

**Comment by garfield69** [comment]
the web site does not provide the size, seeders, leechers, and date on the search results.

They are buried in the torrent details page, which Jackett does not fetch since that would mean generating 15 or more additional http network requests every time you do a search. 
You could get flagged as a DDoS generator by the site and be black listed.

The current indexer is really only suitable for use with the Jackett dashboard search.

But looking through some other indexer I find that we have provided default values for these, so that they can pass muster for other apps.

The next release of Jackett, when ever that gets published later today, will include these amendments.

**Comment by garfield69** [comment]
several caveats for using the indexer with Radarr:

The moviesdvdr web site does not list the year in the title of the search results.
so when setting up the indexer on Radarr you need to choose to turn on the **remove year from search string** using the **advanced settings** option on the Radarr indexers page.

Also, be aware that the web site searches not just the title, but the description too.
so a search for the movie **logan** will return lots of other movies too.

Nothing Jackett can do about this.

**Comment by garfield69** [comment]
try out jackett 0.12.1213
