### ISSUE TITLE
magnet link missing from results

### ISSUE THREAD

**Issue by wellloaded** [Jackett/Jackett#6614]
There are few plugins that have an option to provide magnet link (manually set by myself) but they default the results to torrent download link any ways. Other plugins don't have this option and on a plugin basis some provide torrent download other magnet. However for all the cases if I click the link to the Jackett result it will open the tracker page and there there's always a magnet link. So I suppose it's just a plugin thing...

Am I the only one experiencing this?

Is there any way to have them all providing magnets only?

Many thanks for the great software! :-)

**Comment by garfield69** [comment]
I'm a little confused about your use of the word **plugin**. 
I assume you are taking about Jackett **indexers** and how some indexers have magnet links available, others only .torrents, and some both.
within that context, the answer is that it all depends on what the torrent web site provides.

But If the torrent web site provides magnets and the corresponding Jackett indexer for that site does not, then simply let us know, and we can check if the indexer can be altered to support magnets for that site.

**Comment by wellloaded** [comment]
Correct I referred to what Jackett call indexer, sorry for the confusion.
And  again correct, the torrent web page does indeed have magnet links where the Jackett results not always do (some indexer do other not)

[https://ibb.co/0DPMXGR](url)

**Comment by garfield69** [comment]
>Out of the indexers I have enabled these are affected and provide always torrent download icon instead of magnet link: ETTV, LimeTorrents, Torrentz2, 1337x

Ah. you are referring to the download **icon** on the Jackett dashboard.
Some web sites provide the download link (whether its .torrent or magnet or both) on their **primary search results** page, while others only provide the download links once you have navigated to the individual **torrent details** page.

for those sites that have DL links on the **primary results** page, Jackett knows what the links are and can show the appropriate icon (download arrow for .torrent and magnet icon for magnets).

But for those sites that require you to visit the **torrent details** page its different.
This is because if Jackett took a look at each torrent details page it would generate up to 100 additional http get requests, one for each torrent in the search page, and the flood of requests to the site may get you flagged as a DDoS attack. Your IP could get black listed and banned.

So for those sites, Jackett displays a download link, since while Jackett is processing the results it does not know what links are available in the details page. It is not until you click the button that you fetch the download link.

Usually, if the details page offers multiple choices for download links, the indexer config allows you to pick which download link you prefer to get when you click on the Jackett dashboard download icon.

ETTV, Limetorrents and 1337x use the details page, and the indexers config provides a choice in their configs as to which link you use.
if you choose magnet, you will get a magnet when you click on the download icon.

TorrentZ provides only magnets on their primary results page so you will see the U icon on that indexer.

>I noticed that in the result table the UL Factor and Download columns can not be sorted despite the icon suggesting so 

the page only sorts what results are displayed. In your case, you have the **show** selector set to **20** results.
if the DLVF are all 0 then sorting **asc** or **desc** is not going to change that.
Set the **Show** selector to **ALL** and if those columns have different values then they should sort when you click the sort button.
If this is not the case, then show me an example so I can check it out.

**Comment by wellloaded** [comment]
> 
> 
> > Out of the indexers I have enabled these are affected and provide always torrent download icon instead of magnet link: ETTV, LimeTorrents, Torrentz2, 1337x
> 
> Ah. you are referring to the download **icon** on the Jackett dashboard.
> Some web sites provide the download link (whether its .torrent or magnet or both) on their **primary search results** page, while others only provide the download links once you have navigated to the individual **torrent details** page.
> 
> for those sites that have DL links on the **primary results** page, Jackett knows what the links are and can show the appropriate icon (download arrow for .torrent and magnet icon for magnets).
> 
> But for those sites that require you to visit the **torrent details** page its different.
> This is because if Jackett took a look at each torrent details page it would generate up to 100 additional http get requests, one for each torrent in the search page, and the flood of requests to the site may get you flagged as a DDoS attack. Your IP could get black listed and banned.
> 
> So for those sites, Jackett displays a download link, since while Jackett is processing the results it does not know what links are available in the details page. It is not until you click the button that you fetch the download link.
> 
> Usually, if the details page offers multiple choices for download links, the indexer config allows you to pick which download link you prefer to get when you click on the Jackett dashboard download icon.
> 
> ETTV, Limetorrents and 1337x use the details page, and the indexers config provides a choice in their configs as to which link you use.
> if you choose magnet, you will get a magnet when you click on the download icon.
> 
> TorrentZ provides only magnets on their primary results page so you will see the U icon on that indexer.
> 

That makes sense, no problem I'll leave with this was just wondering if that was a feature ;-)

> > I noticed that in the result table the UL Factor and Download columns can not be sorted despite the icon suggesting so
> 
> the page only sorts what results are displayed. In your case, you have the **show** selector set to **20** results.
> if the DLVF are all 0 then sorting **asc** or **desc** is not going to change that.
> Set the **Show** selector to **ALL** and if those columns have different values then they should sort when you click the sort button.
> If this is not the case, then show me an example so I can check it out.

Switching to show all doesn't change the behaviour and again the columns  unable to sort are always the last ones, the e.g. size works fine

**Comment by garfield69** [comment]
give me an example. provide a search string and which indexers you used. so I can see what you mean.

**Comment by wellloaded** [comment]
Can you see this?
[https://imgur.com/vQSPGN3](
https://imgur.com/vQSPGN3)

**Comment by garfield69** [comment]
your capture supports what I said earlier, but perhaps I was not clear so I will rephrase.

the `DL Factor` column cells in your search results show that every row has the value `0`.
the `UL Factor column cells in your search results show that every row has the value `1`.
and the `Download` columns is just for icon picture buttons.

It will not make any difference is you sort the `DL Factor` column in DESC or ASC order, if all the values are the same in that column, there is not going to be a visual difference in the reorder.
Same goes for the `UL Factor` column.
And of course the `Download` column is just icons, there is little point sorting those.

I am not sure what you expected to see?

**Comment by wellloaded** [comment]
> 
> 
> your capture supports what I said earlier, but perhaps I was not clear so I will rephrase.
> 
> the `DL Factor` column cells in your search results show that every row has the value `0`.
> the `UL Factor` column cells in your search results show that every row has the value `1`.
> and the `Download` columns is just for icon picture buttons.
> 
> It will not make any difference when you sort the `DL Factor` column in DESC or ASC order, if all the values are the same in that column, there is not going to be a visual difference in the reorder.
> Same goes for the `UL Factor` column.
> And of course the `Download` column is just icons, there is little point sorting those.
> 
> I am not sure what you expected to see?

My point was about the Download column only.
If you put a sorting icon on a column header you would expect it to work. Even if the download is just an icon why can't it order by magnet icon Vs Torrent icon? As mentioned I do prefer magnet so this would be indeed a value.

Thanks!

**Comment by wellloaded** [comment]
> Ah. you are referring to the download **icon** on the Jackett dashboard.
> Some web sites provide the download link (whether its .torrent or magnet or both) on their **primary search results** page, while others only provide the download links once you have navigated to the individual **torrent details** page.

Ok let me expand this point: say Jackett finds a list of records via the torrent webpage **primary search result** where magnet links are not available as you rightly spotted.
At this point, without doing this automatically for each and every record, if the user clicks on the download icon within the Jackett result table, could Jackett go into the specific torrent webpage and fetch the magnet from there? So this "go and find magnet link" would only happen once and not for every result.
 
That would be a precious click saver!

Thanks :-)

**Comment by garfield69** [comment]
I think you misunderstood what I was saying.
I was trying to explain what prevents Jackett from displaying the appropriate download icon in the download column of the dashboard.
This is no way impacts whats happens when the user actually clicks on the button.
Whatever URL the indexer has prepared for that button is passed to http. 
if that URL is a magnet URL or a .torrent URL, the magnet or torrent is returned.
there is not click savings to be had.
or have I misunderstood what you asking?

**Comment by garfield69** [comment]
regarding the sorting of the download column:
the panel invokes the standard JavaScript .sort() function, which the docs state can only handle alphabetic or numeric sorting.
The column headers are build with a recursive routine that labels and tags all headers as sort-able.
I'm not interested in spending time writing a custom sort for icons or fiddling with this panel's html.
It's just not my cup of tea.
I see little benefit in this. I already stated previously how the magnet icon only shows up if the site being searched has the link in the primary search page.
If the site has the magnet in the details page, then Jackett will display the local-download icon.
which means IMO, that sorting this column is pointless since many sites use the details page for download links.

If you really want to be able to sort the download column then open a fresh enhancement request and we shall see if any volunteers contribute a solution.

**Comment by wellloaded** [comment]
> I think you misunderstood what I was saying.
> I was trying to explain what prevents Jackett from displaying the appropriate download icon in the download column of the dashboard.
> This is no way impacts whats happens when the user actually clicks on the button.
> Whatever URL the indexer has prepared for that button is passed to http.
> if that URL is a magnet URL or a .torrent URL, the magnet or torrent is returned.
> there is not click savings to be had.
> or have I misunderstood what you asking?

First of all many thanks for taking the time. I really appreciate!

I think we're on a slightly different page here. Let see if I can do a better job explaining myself.

> But for those sites that require you to visit the torrent details page its different.
This is because if Jackett took a look at each torrent details page it would generate up to 100 additional http get requests, one for each torrent in the search page, and the flood of requests to the site may get you flagged as a DDoS attack. Your IP could get black listed and banned.

What you're saying is: for those sites where magnet is not provided directly as part of the torrent website main search result page, Jackett will not go into the individual torrent detail pages to get the magnet link as this will generate a huge amount of requests towards the site. Fair enough and I do agree with this.

However, what I suggested is: Can Jackett actually do this job of going into the torrent detail page BUT only at them moment I click on the Jackett download icon?

So right now:
- download icon = get the torrent file
- magnet icon = fetch magnet link

Suggested new behaviour:
- single download icon (or additional one really not important) and when clicked
a) give me the magnet if available out of the box
b) have jackett silently going for me into the torrent detail page and fetch the magnet for me
c) if a and b failed give me the torrent

Essentially a slightly different behaviour that will always try to provide magnets whenever possible.

Again I guess I'm not doing a great job explaining myself. What I currently do manually clicking here and there could be automated by the software. So bottom line if Jackett can give me magnets out of a single click it is indeed a huge amount of time saving.

Please let me know your thoughts.

**Comment by wellloaded** [comment]
> regarding the sorting of the download column:
> the panel invokes the standard JavaScript .sort() function, which the docs state can only handle alphabetic or numeric sorting.
> The column headers are build with a recursive routine that labels and tags all headers as sort-able.
> I'm not interested in spending time writing a custom sort for icons or fiddling with this panel's html.
> It's just not my cup of tea.
> I see little benefit in this. I already stated previously how the magnet icon only shows up if the site being searched has the link in the primary search page.
> If the site has the magnet in the details page, then Jackett will display the local-download icon.
> which means IMO, that sorting this column is pointless since many sites use the details page for download links.
> 
> If you really want to be able to sort the download column then open a fresh enhancement request and we shall see if any volunteers contribute a solution.

Ok thanks for the explanation, it makes sense and I do agree this really is a minor point.

**Comment by garfield69** [comment]
I believe jackett is already doing this.
so if the magnet needs to be fetched from the details page, when you click on the download icon on the jackett search page, jackett goes to the details page, and returns with the magnet.

**Comment by wellloaded** [comment]
> I believe jackett is already doing this.
> so if the magnet needs to be fetched from the details page, when you click on the download icon on the jackett search page, jackett goes to the details page, and returns with the magnet.

Not on the version I'm running:  Jackett Version 0.12.1213.0 

I have indexers like: ETTV, LimeTorrents, Torrentz2, 1337x, where Jackett provides the link to a torrent download by default as part of the result display. if i click on the download icon it will download the torrent file.
However if I click on the Jackett result page "torrent name" it will open the torrent page description and there I do find the magnet.

**Comment by garfield69** [comment]
> Not on the version I'm running: Jackett Version 0.12.1213.0
> I have indexers like: ETTV, LimeTorrents, Torrentz2, 1337x, where Jackett provides the link to a >torrent download by default as part of the result display. if i click on the download icon it will >download the torrent file.
>However if I click on the Jackett result page "torrent name" it will open the torrent page description >and there I do find the magnet.

Only because you have not gone into the Jackett indexers config and chosen the magnet option.
If you set the relevant config to fetch a magnet, then (despite the Jackett dashboard presenting a download icon instead of a magnet) you will be given a magnet URI.

example:
![image](https://user-images.githubusercontent.com/6933240/70976319-a6cf0580-2110-11ea-80df-dba867b62b14.png)

**Comment by wellloaded** [comment]
They are all set to Magent already. e.g.:

![image](https://user-images.githubusercontent.com/46318040/70976809-e8c66000-20ac-11ea-8a97-6b6a506aa170.png)

**Comment by garfield69** [comment]
so whats the problem then. I click on the download button and the magnet uri is fetched, the browser recognises its a magnet and passes it to the system default app for magnets, in my case utorrent and away I go.
works for me.

**Comment by wellloaded** [comment]
Wow you are right thanks for confirming this!
I have also found the issue.
I have a plugin called torrentcontrol installed on my firefox which I use to send torrent download info to a LAN connected torrent client (qBittorrent).
This plugin was installed with the option "Catch Torrent URLs" which sounds somehow right to be enabled, however disabling this makes Jackett work exactly as you explain.

Many thanks for the support guidance! 👍 👍 👍 

:-D

**Comment by garfield69** [comment]
\o/
