### ISSUE TITLE
Jackett Docker

### ISSUE THREAD

**Issue by mouzzampk2014** [Jackett/Jackett#6620]
Hi,
I just reinstalled my machine but I created a backup of Jackett. 
Jackett is up and running but I don't want to add all the indexers again. What I need from previous backup to restore the indexers? 
Thank you so much
![2](https://user-images.githubusercontent.com/44548525/70868804-1d86ca00-1f7c-11ea-8ad5-68684856f50f.jpg)

**Comment by garfield69** [comment]
the indexer folder contains all the active indexer configs
you may need the dataProtection folder too
and the ServerConfig.json file contains your dashboard settings and APIkey.

But if try to use one of the indexer and it complains the password is incorrect, then its possible that if the new install uses a different encryption key, so you will have to enter the passwords in each indexer config again from the jackett dashboard, in order to encrypt them all correctly.
