### ISSUE TITLE
[TorrentLeech] not show as Freeleech if it hasn't freeleech tag

### ISSUE THREAD

**Issue by InnerPeaceKR** [Jackett/Jackett#6624]
I searched with the keyword 'complete bluray'. I notice that some freeleech doesn't have freeleech tag.

**Comment by garfield69** [comment]
this was added 5 days ago with 226fdfd03c7b8d5a883af4a962c0a6bbbb56bc42
are you on the latest Jackett version?

**Comment by InnerPeaceKR** [comment]
for example [https://i.imgur.com/0I40LvW.png](url)

**Comment by garfield69** [comment]
the Jackett torrentleech indexer uses 
https://www.torrentleech.org/torrents/browse/list/query/anjunabeats
to fetch a json list of results to process, rather than
https://www.torrentleech.org/torrents/browse/index/query/anjunabeats
which is what the browser site search uses.

there appears to be a discrepancy between the two requests
```json
{"fid":"1247417","filename":"Label Anjunabeats (1).torrent","name":"Anjunabeats Label Collection  2000 - 2016 FLAC (495 releases) ","addedTimestamp":"2019-01-26 12:16:20","categoryID":31,"size":97281717436,"completed":9,"seeders":0,"leechers":0,"numComments":3,"tags":["nonscene"],"new":false,"imdbID":"","rating":0,"genres":"","tvmazeID":"","igdbID":"","download_multiplier":0,"uploader":"om3ga"},
```
clearly has not FREELEECH tag
where as 
![image](https://user-images.githubusercontent.com/6933240/70917818-e7803d80-2082-11ea-8208-b59e86891f15.png)
does.

I presume Jackett is not allowed by the site to use the html scrape method and so the indexer was written to use the API provided by the site, but clearly the site keeps different servers for each and the results don't always sync.

this is not within jackett's control :-(

**Comment by InnerPeaceKR** [comment]
"download_multiplier": 0

Doesn't this mean freeleech?

**Comment by garfield69** [comment]
Hah!
you are absolutely right. Well spotted. 🥇 
much better than looking for the FREELEECH tag which is obviously unreliable.
`"download_multiplier": 0`=free `"download_multiplier": 1`=notfree
I'll amend the indexer shortly.

**Comment by garfield69** [comment]
jackett 0.12.1245
