### ISSUE TITLE
[REQ] videolenta.biz

### ISSUE THREAD

**Issue by Lonli-Lokli** [Jackett/Jackett#6637]
New Russian tracker https://videolenta.biz/

**Comment by garfield69** [comment]
this public site is not suitable for the cardigann processor which expects search results to contain a one to one relation between the title and a torrent/magnet.
Since this site presents results where one title leads to multiple torrents listed in the details page, the indexer for this site will need to be written in C#.

**Comment by garfield69** [comment]
this redirects to https://t.lafa.site/
closing as a duplicate of #12594
