### ISSUE TITLE
[nostalgic] Login failed: No form found on https://vhstapes.org/login using form selector form[action=

### ISSUE THREAD

**Issue by skuizy** [Jackett/Jackett#6686]
After being redirected to vhstapes.org (Exception (nostalgic): Got redirected to another domain. Try changing the indexer URL to https://vhstapes.org/.: Parse error), I can't login anymore

**Comment by garfield69** [comment]
23 days ago nostalgic went offline with this message:
`Server kept getting overloaded and bogging out due to lack of resources. Going to make adjustments. tracker online.`

that vhstapes address that nostalgic.is redirects to is a dead end that just has `irc.dejatoons.net #nostalgic` on it.

looks like the site's original address is gone.

anyone have an irc a/c and can find out if nostangic has moved to a new domain or had closed for good?

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/3795#issuecomment-569118040

**Comment by revotus** [comment]
The vhstapes.org domain is up and running and I'm seeing

`<form method="POST" action="/login" />`

but Jackett is giving the error:

`Login failed: No form found on https://vhstapes.org/login using form selector form[action="/login"]`

**Comment by garfield69** [comment]
I updated nostalgic for the new domain 3 days ago.
it works for me.
Have you logged in with your browser and checked your a/c details?
are you using a jackett versions 0.12.1582 or newer? current latest is 0.12.1605.

the login failed is usually an indication that your login attempt has failed and you were redirected back to the login page, when jackett was expecting to see the torrents search page.
if you cant work it out, try enabling the enhanced log, and attempting to login again.
then look at the log carefully, there may be a clue to the problem.

**Comment by revotus** [comment]
All apologies. Jackett was installed as part of a larger package and the version was nowhere near up to date. All good now. Thank you so much for the quick response.
