### ISSUE TITLE
[demonoid] is not returning results

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#6716]
is this tracker still public?

**Comment by garfield69** [comment]
works for me
![image](https://user-images.githubusercontent.com/6933240/71549699-b7dc1880-2a26-11ea-8c7b-b9cbbad0a88b.png)
![image](https://user-images.githubusercontent.com/6933240/71549719-08ec0c80-2a27-11ea-8a9e-882ab0353acd.png)

**Comment by garfield69** [comment]
there is this note:
![image](https://user-images.githubusercontent.com/6933240/71549731-405ab900-2a27-11ea-923a-71c97fb3f5d7.png)

**Comment by ngosang** [comment]
still not working for me. i will try again tomorrow

**Comment by garfield69** [comment]
I am seeing this too now. Strange how it took a day or more for it to affect me. caching perhaps.

yes, while Demonoid is experiencing server connectivity they have restricted access to users with a/c only.
But since they are using cloudflare's reCaptcha on their login form, I'm going to have to use a cookie login.
