### ISSUE TITLE
[SkyTorrentsClone] missing category

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#6721]
Tracker: SkyTorrentsClone
Search: bello vivir

The last result doesn't have category. Maybe we should set other in that case. => https://www.skytorrents.lol/?query=bello+vivir

**Comment by garfield69** [comment]
it does not appear to be possible within the current cardigann design.

The processor has the **optional:true** clause to handle when a selector is **not found**
so normally I can provide a default for the field, and if the optional selector is found it overwrites the default.

But the **category** field is not a **string** or an **integer**, but a **list**.
if I provide a default of **other** then when the optional selector is found the value is appended to the list.

the Search results page will end up looking like this:
![image](https://user-images.githubusercontent.com/6933240/71548897-bc4e0480-2a19-11ea-92ec-08183b5efd9a.png)

I cannot find a way to provide a default category and handle missing selectors for this situation.

**Comment by ngosang** [comment]
@garfield69 thank you for trying to fix it. This is not blocking for me, just let it open. Maybe in the future someone improves the Cardigann parser.

**Comment by ngosang** [comment]
I found another 2 sites that some torrents don't have any category.
Trackers: 
* KickAssTorrent (kat.li)
* Torrent9 clone (torrent9.ch)
Search: 720p

Show all results, some of them don't have category.

**Comment by ngosang** [comment]
@garfield69 what do you think will be the best solution?
1. add a flag to disable append in list => you can set de default value as usual
2. add a special flag for default category => if the category list is empty, we use the default value
3. another

**Comment by garfield69** [comment]
at first take, I thought option 2 would be good, becuase I would not have to code anything extra in the indexers yaml.
But on further reflection, defaulting to a cat when none is found would hide the fact that for other indexers that usually have all the cats available, not finding one is an exception that indicates its time to refresh the category table for that indexer.

so I think option 1. this way, we code the default in the indexer because we know that indexer may have missing cats, and we still get an exception for indexers that usually have all the cats but the indexer cat table is out of date. 

so to be clear, are we looking at something like:
```yaml
    fields:
      category:
        text: Other
      category:
        selector: td
        optional: true
        append: false
```
?
