### ISSUE TITLE
Can't use 2000 category in Jackett with Radarr

### ISSUE THREAD

**Issue by logos88** [Jackett/Jackett#6736]
I can't put inside the indexer Jackett the category 2000. When I add this category and press test button says "Unable to connect to indexer, check the log for more details"
This category is needed for some indexer like MejorTorrent or Elitetorrent which use it for almost everything.

Mono Version: 6.4.0.198-1

Debug Logs:
https://pastebin.com/T6z469Hb

**Comment by garfield69** [comment]
Huh?
I cannot make sense of what you are reporting.
Which Jackett indexer are you trying to add to Radarr?

**Comment by logos88** [comment]
In Raddar I added all my Jacket indexers with: http://localhost:9117/torznab/all
Between the ones I use there are Isohunt2, elitetorrent or mejortorrent which need the category 2000

**Comment by garfield69** [comment]
I see.
OK, I have several recommendation/suggestions for how to get the most out of Radarr with Jackett.
1. do not use the jackett aggregate indexer **All**. You may think you are saving setup time, but this is not an appropriate indexer to use with Sonarr/Radarr. The reason is, that these days, it is common for many sites to have temporary issues, or them having to enable anti DDoS protection. When any of the active indexer in jackett take too long to respond, or are broken or have DDoS protection, the aggregate indexer can take too long to respond, and Radarr will give up waiting and flag the whole search as a failure.
2. turn on the Show Advanced option in your Radarr Indexer page, so you can see and edit the categories that the indexers you add to Radarr need.
3. Take the time to add your favourite Jackett indexers to Radarr individually. Don't get greedy, You don't need more than a handful. Most will only provide duplicate search results anyway, wasting time and resources, slowing down your search times and loading your network and computer with pointless http traffic. You also get the benefit of faster response times in results as you take advantage of parallel processing, and should any individual indexer have a problem it will not stop Radarr getting results from the other indexers.
4. as you add each Jackett Indexer to Radarr, first access the jackett dashboard and edit the config for the indexer you are working on. Look at the categories that the indexer supports. Jackett can only provide the Torznab categories that the web site it represents is capable of using. Remove any categories from the Radarr indexer that are not supported and add any that relate to movies. This may include custom torzhab categories (in the 100000 number range).
5. Mejortorrent is a mess right now. I would not bother with this one. The have enabled the cloudflare Anti DDoS ReCaptcha which Jackett cannot solve. 

Hopefully this will get you going.
