### ISSUE TITLE
Some trackers are providing magnets instead of torrents

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#6744]
If I make a search in Monova or in BTSOW, the Jackett UI shows thw torrent download icon, but it's a magnet link.

**Comment by ngosang** [comment]
I think you are doing it because you have to make another call with jackett to get the magnet link.

**Comment by garfield69** [comment]
this is a limitation of the jackett cardigann processor.
when a site is searched, if the results from the primary search page contains either .torrent url or magnet uri, then the corresponding icon is displayed on the jackett dashboard.

if however, the download link (whether .torrent or magnet or both) is only available in the torrent details page, then the dashboard shows the download icon, since cardigann will have to fetch the details page to process the link and action the download.

I see you answered the question before I could complete my reply ;-)
