### ISSUE TITLE
[tigers-dl] Exception (tigers-dl): Login failed: No form found on https://www.tigers-dl.net/index.php?page=login using form selector form[action=

### ISSUE THREAD

**Issue by Astrem2005** [Jackett/Jackett#6760]
An error occured while testing this indexer
Exception (tigers-dl): Login failed: No form found on https://www.tigers-dl.net/index.php?page=login using form selector form[action="index.php?page=login"]: Parse error

The website change. There is the URL:
https://www.tigers-dl.net/index.php

I got last version of Jackett
Jackett Version 0.12.1391.0

[Log.txt](https://github.com/Jackett/Jackett/files/4013608/Log.txt)

**Comment by garfield69** [comment]
jackett does not support the tigers-dl indexer, it was removed back in august when the new version of the site came back online after being offline for over a month.

Its not supported because the titles for the search result posters are abbreviated, and the site does not provide the full titles anyplace in the results.
