### ISSUE TITLE
Error performing update

### ISSUE THREAD

**Issue by maZuFC** [Jackett/Jackett#6788]
hi

ive just noticed an error with my jackett install and that its not updating...

i get the following notification

**Your version of Jackett v0.10.890.0 is very old. Multiple indexers are likely to fail when using an old version. Update to the latest version of Jackett.**

when i click on check for updates, it finds the latest update but then fails to update....
this is what i see in the log

**Jan 03, 2020 03:06:59 PM | Error | Error performing update.
-- | -- | --
Jan 03, 2020 03:06:59 PM | Info | New release found.  Current: v0.10.890 New: v0.12.1402**

can anybody advise on how to resolve this?

cheers,

**Comment by garfield69** [comment]
you did not specify which platform you are on, but I am going to assume you are using Linux and not using a Docker image, since it's that combo that I usually see these kinds of tickets for.

In this case I think you should manually upgrade to the latest Jackett package for your platform, and in addition, if you are using systemd to launch the service, then also run the systemd installer script (which will fix clashes between the updater and the service getting in the way of each other during auto-updates or manual check-for-updates).
see https://github.com/Jackett/Jackett#install-on-linux-amdx64 or https://github.com/Jackett/Jackett#install-on-linux-armv7-or-above

this should allow future auto-updates to work.

if this does not apply to you then tell me which platform and flavour of Jackett you are running.

**Comment by maZuFC** [comment]
hey mate

sorry completely skipped my mind to add in what platform im using! 

im running server 2012R2 and i downloaded the jackett windows installer.

let me know if theres anything else you need to know


cheers!

**Comment by garfield69** [comment]
in that case manually install the latest windows Jackett from https://github.com/Jackett/Jackett/releases/download/v0.12.1415/Jackett.Installer.Windows.exe and follow https://github.com/Jackett/Jackett#installation-on-windows (I recommend installing as a  window service) and hopefully you should be good to go.
let me know how it goes.

**Comment by maZuFC** [comment]
ok great

can i simply install over the top or should i uninstall the old version first?

**Comment by garfield69** [comment]
First shut the service down (if you are using the tray icon, you can right click on it and select the **Stop background Service**, and then also click on the **close Tray Icon**, so that you don't have and file locks on binaries open on active tasks.

Then run the installer and is should be able to install over the top.

At least that is what happens on my windows 10 home system. Hopefully the win 2012 Server will behave the same way.

**Comment by maZuFC** [comment]
stopping the service and reinstalling jackett has fixed the issue


cheers
