### ISSUE TITLE
[leporno] search is returning less results than the website

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#6798]
Tracker: leporno
Searches:
* Cherry Kiss => 30 results
* cherry kiss => 0 results

**Comment by garfield69** [comment]
I've no idea how to capitalize the first letter of every word using regex
may need to create a new Cardigann function (similar to tolower, or toupper) so it can be done in C#

**Comment by ngosang** [comment]
@garfield69 I don't think that will be necessary to do capitalization. That can cause another problems...
I'm more concern about Jackett is returning less results than the website. If you search `cherry kiss` in http://leporno.org/tracker.php#results you get 9 results and 0 in Jackett. I think that torrents are dead, but the user should get that too and decide himself.

**Comment by ngosang** [comment]
@garfield69 I changed the request/title. Forget about the lower case, take a look at the previous message.

**Comment by garfield69** [comment]
no that is not it.
on the website using http://leporno.org/tracker.php to search for `Cherry Kiss` returns over 5 pages of 100 hits each, and `cherry kiss` just 9 hits.
But the site also does a keyword OR, so many titles only have one of the keywords.

The Jackett indexer uses the same search settings that the web site defaults to, the only difference is that we also add the row andmatch filter to get rid of titles that do not have both keywords.
this results in 0 for cherry kiss because there are no titles with both those words returned by leporno for that search.
If I remove the and match I get the same results the web site does.

**Comment by ngosang** [comment]
All clear. Thank you for the time to answer. I think we can't do much more...
