### ISSUE TITLE
unable to add IPTorrent - Exception in GetConfigForm

### ISSUE THREAD

**Issue by maZuFC** [Jackett/Jackett#680]
im not able to add IPTorrent into jacket... 

when i select IPTorrent it doesnt pop up with the configuration menu
it looks like a similar issue to what was happening with Torrentday which was resolved by allow us to enter in a manual url.

i posted my torrentday issue here.. https://github.com/Jackett/Jackett/issues/580

i am using the latest version.

can we please get a custom field for IPTorrent ?

thanks

**Comment by kaso17** [comment]
I assume https://iptorrents.com/ is blocked by your ISP?
IPT has an alternative URL but for the initial attempt it uses https://iptorrents.com to check for any captcha.
What happens if you try to access https://iptorrents.com/ in your browser, does it load forever?
Please send the log output when running "jackettConsole.exe -t"
Which IPT mirror side is working for you?

**Comment by maZuFC** [comment]
yeah isp has blocked it and some must seem to load forever.
most dont load for me... the only one working at the moment is https://ipt-update.com/login.php

**Comment by archangel00uk** [comment]
Hi,

Thanks for adding ipt-update.com as an alternative source on #682.

Was wondering how do I get the change for the Windows release? sorry new to the whole Github world.

**Comment by kaso17** [comment]
Just published v0.7.577 which contains the change. Try that one.

**Comment by maZuFC** [comment]
thanks.. will check it out

**Comment by archangel00uk** [comment]
latest change fixed the issue.

Thanks for prompt change

**Comment by razzamatazm** [comment]
running into this issue again.
