### ISSUE TITLE
[hdreactor] unrelated results

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#6806]
Tracker: hdreactor
Search: morty 405

Add the match filter.

**Comment by garfield69** [comment]
can't use the **andmatch** filter because we are doing **SxxExx** substitutions on the search keywords to match Russian **Сезон xx Серии xx** and the **andmatch** would drop all results before we can convert the titles back to **SxxExx** again.

But I can adjust the search to look in **article titles**. the default (when this option is left out of the search query) was to look in **articles** which presumably included description, comments, etc.
