### ISSUE TITLE
[hdarea] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by killerqueen619** [Jackett/Jackett#6808]
ss error : http://prntscr.com/qj6mg5

**Comment by garfield69** [comment]
I don't have an a/c on this site so I cannot test for myself.
the picture you provided is of no help whatsoever, it is the equivalent of going to the doctor and saying, `i'm not well`. ;-D
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.

**Comment by killerqueen619** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/4021624/log.txt)

**Comment by garfield69** [comment]
Ah no. this is not an **enhanced** log, as there are no Debug messages.
its just the regular log sorry, it is of no use to me.
please read my prior post and try again.
thanks.

**Comment by killerqueen619** [comment]
I've sent you login data in your mail!
please check

**Comment by garfield69** [comment]
Thank you for the email.
The problem is that you have an important message that must be read before you can access the torrent search page. This prevents the Jackett indexer from successfully fetching the search results page.

You can see this for yourself, if you use your browser to login to the site and try to access the torretn search page.

So login to the web site with your browse and clear all notices and unread email and and then logout.
Then try the Jackett indexer again and see if it works.

Let me know how it goes.
Thanks.

**Comment by killerqueen619** [comment]
Still not work sir.

**Comment by killerqueen619** [comment]
its work now lol
thank u!
