### ISSUE TITLE
1337x, no audio results

### ISSUE THREAD

**Issue by Daptonic** [Jackett/Jackett#6841]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

(At the bottom of your Jackett Dashboard page) **Jackett version**:   0.12.1470.0
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**:

-------------------------------

When trying to add 1337x to Lidarr, no results return for anything audio. 3000, 3010, 3020, 3030, 100022. Same happens when using the search button in Jackett itself. HD TV Shows return results...

**Comment by garfield69** [comment]
yeah. 1337x does not support multicategory searches, so the indexer has been set up favouring TV and Movies.
a keyword-less search will call up the TV and Movie pages and if you use the jackett category filter, then the results from those two pages will be filters.
But since they don't contain music you will get 0 results.
if I do a general search for say `junstin beiber` i will get music results.

But since the indexer does not have the lidarr music-search parm, lidarr will not get any results.

I'll experiment, and see if I can add the music-search and some music support.

**Comment by garfield69** [comment]
managed to get results. its not perfect. but better than nothing.
I'll post when the the next Jackett gets published with the enhancement, tomorrow some time.

**Comment by Daptonic** [comment]
What is strange is that it used to work. I had to re-do my Jackett installation over the weekend and from then on lidarr wasn't able to return music results. But prior to I had it there.

**Comment by Daptonic** [comment]
Thanks for the update.

**Comment by garfield69** [comment]
Jackett 0.12.1486
