### ISSUE TITLE
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) Aborted (core dumped)

### ISSUE THREAD

**Issue by fcmircea** [Jackett/Jackett#6856]
Have updated to the latest version (v0.12.1486) by copying over the older version.

Now Jackett won't start either as a service or directly and displays:

`Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) Aborted (core dumped)`

Ubuntu 18.04 and Jackett v0.12.1486

**Comment by fcmircea** [comment]
After some overwriting from one folder to another, the issue seems to have resolved.

I unpacked the latest in a separate folder, ran it once then copied the previous files over then moved everything in the initial location on my system.

jackett now starts properly as a service

**Comment by garfield69** [comment]
is there a reason you are not using the updater for this?

have you refreshed the systemd startup script to apply the fix for preventing service and updater clashing? It was a problem goes back several months ago, but has been fixed with just running the systemd install script just this one more time. 
open a Terminal, cd to the jackett folder and run `sudo ./install_service_systemd.sh`. You need root permissions to install the service script.
