### ISSUE TITLE
[BTNext] Tracker returns (Error) whenever there are 0 search results

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#6897]
Instead of simply returning (0), BTNext returns an (Error) whenever there are no results found. The website itself actually does the same. It returns "An error has occurred! There are no results found."

Can this be corrected in Jackett so that simply a (0) is displayed instead of (Error)?

Enhanced log attached. 

[log.txt](https://github.com/Jackett/Jackett/files/4044893/log.txt)

Jackett version:  0.12.1494.0
Mono version: N/A

**Comment by garfield69** [comment]
the error capture trap was added deliberately by kaso17 back in Mar 2017 with 7f648d19a56924f31ba3435309ef10875618fcd8 so it clearly is required.
But in Aug 2017 kaso17 amended the trap 4b021412509e641e1b2700467d98bf5c731f3b30 to look for 
`Não existem resultados encontrados.`

where as your log shows you are getting `There are no results found.`

I will add this string to the trap. 
But since I don't have an account on this site I cannot pre-test so I'll just publish blind and you can report back if it works later.

**Comment by RoloSoze** [comment]
> 
> 
> the error capture trap was added deliberately by kaso17 back in Mar 2017 with [7f648d1](https://github.com/Jackett/Jackett/commit/7f648d19a56924f31ba3435309ef10875618fcd8) so it clearly is required.
> But in Aug 2017 kaso17 amended the trap [4b02141](https://github.com/Jackett/Jackett/commit/4b021412509e641e1b2700467d98bf5c731f3b30) to look for
> `Não existem resultados encontrados.`
> 
> where as your log shows you are getting `There are no results found.`
> 
> I will add this string to the trap.
> But since I don't have an account on this site I cannot pre-test so I'll just publish blind and you can report back if it works later.

Will do. Thanks!

**Comment by garfield69** [comment]
Jackett 0.12.1539
