### ISSUE TITLE
[REQ] Rustorka

### ISSUE THREAD

**Issue by dimqua** [Jackett/Jackett#6899]
Rustorka is a RUSSIAN Semi-Private Torrent Tracker for 0DAY / GENERAL.

Link: http://rustorka.com/

**Comment by garfield69** [comment]
Jackett 0.12.1572

**Comment by garfield69** [comment]
https://rustorka.com/ cloudflare Gateway time-out Error code 504

**Comment by garfield69** [comment]
https://rustorka.com/forum/tracker.php?f returns no torrents

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://rustorka.com/ redirects to https://e.radikal.host/2024/07/19/gghhhgggg.jpg
its an image with text so I cannot use google translate but it probably says the domain is suspended

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://rustorka.com/ > cloudflare Web server is returning an unknown error Error code 520

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/6899#issuecomment-2462658876

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
rustorka are using a dynamic cookie key to validate sessions, looks something like this: `3200102d22edf3fad3a23548db2629ff=st232`
the problem is that every day the site generates a new key, but does not delete the old one from the cookie.
I foresee that at some point we will reach maximum cookie length if they don't sort this out. 
Short term solve is to occasionally delete the cookie and login afresh.
