### ISSUE TITLE
[nitro] error in download link

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#6926]
Tracker: nitro
Search: 720p

You are setting http://.... in `MagnetUri` field. You should put that link in `Link` field.

```
Manual search for "" on nitro with 50 results. ERROR MSG: Bad MagnetUri
{"FirstSeen": "0001-01-01T00:00:00", "Tracker": "Nitro", "TrackerId": "nitro", "CategoryDesc": "Movies", "BlackholeLink": null, "Title": "Zab\u00f3jcza przysi\u0119ga - Deadly Vows (2017) [720p] [WEB-DL] [XviD] [AC3-H1] [Lektor PL]", "Guid": "http://nitro.to/torrent/zabjcza_przysiga_-_deadly_vows_2017_720p_web-dl_xvid_ac3-h1_lektor_pl_875492", "Link": null, "Comments": "http://nitro.to/torrent/zabjcza_przysiga_-_deadly_vows_2017_720p_web-dl_xvid_ac3-h1_lektor_pl_875492", "PublishDate": "2020-01-11T00:00:00", "Category": [2000, 100002], "Size": 2244120320, "Files": null, "Grabs": null, "Description": null, "RageID": null, "TVDBId": null, "Imdb": null, "TMDb": null, "Seeders": 0, "Peers": 0, "BannerUrl": null, "InfoHash": null, "MagnetUri": "http://nitro.to/download_magnet.php?id=875492", "MinimumRatio": 1.0, "MinimumSeedTime": 172800, "DownloadVolumeFactor": 0.0, "UploadVolumeFactor": 1.0, "Gain": 0.0}
```

**Comment by garfield69** [comment]
if I put the extracted url into the download field instead of the magnet field, then clicking on the download button on the jackett dashboard indexer search page does not work, I get `This 127.0.0.1 page can’t be found, etc....`
the issue here is that the magnet hash is not available in the results page, so I use the sites download_magnet.php after hacking the provided href to replace `/__DWNMAGNET__?` with `download_magnet.php?`.
I think there is a hash in the torrent details page, but I would have to build the complete magnet URI myself.
I cant use the proper .torrent href as this is only available to registered members.

**Comment by garfield69** [comment]
more in #5949

**Comment by ngosang** [comment]
take a look at #6931
