### ISSUE TITLE
Unable to add indexer: TorrentDay (The handshake failed due to an unexpected packet format)

### ISSUE THREAD

**Issue by benjy182** [Jackett/Jackett#6937]
When trying to configure TorrentDay as an indexer I'm getting the error: Request to Jackett server failed.

This was previously working, have tried uninstalling and reinstalling and I'm getting this error on the latest version. Attached error from the logs.

System: Windows 10
Jackett Version: 0.12.1539.0
[JakettErr.txt](https://github.com/Jackett/Jackett/files/4050857/JakettErr.txt)

**Comment by garfield69** [comment]
if you still have the torretnday indexer on your jackett dashboard in the active list,
try removing it with the trashbin icon.
then for good measure, reboot machine to clear any temporary caches and what not.
then add the indexer afresh.
if it still does not work, then all the google hits I have found point to issue involving ports, with 
what looks like a ssl error. 
so Google `System.IO.IOException: The handshake failed due to an unexpected packet format.` and follow some of the threads and see if anything there applies to you.

**Comment by benjy182** [comment]
Rebooted and issue persists.
I've run a netstat and there is only one entry for port 9117 which is Jackett. I've also been able to add other indexers. Whenever I try with TorrentDay it throws an error before the config window loads.

**Comment by garfield69** [comment]
ok. well the stack trace you provided is not much help, maybe a full enhanced log will provide more details, especially just prior to the exception.
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.

**Comment by benjy182** [comment]
I've tried a couple of other trackers and I'm getting similar problems so I guess there is something wrong with my setup. Any more help would be grrat.
Enhanced log attached.
[EnhancedLog.txt](https://github.com/Jackett/Jackett/files/4051357/EnhancedLog.txt)

**Comment by garfield69** [comment]
Hmm.
I see Jackett doing the http request for url https://torrentday.cool/login.php
and then the error _The underlying connection was closed: An unexpected error occurred on a send. The handshake failed due to an unexpected packet format_ straight afterwards.

can you access the above url from a browser on the same machine that is running Jackett?
it looks to me like either a local app (firewall, anti-malware, other network monitor) is interfering, or perhaps your ISP is doing something...?

**Comment by benjy182** [comment]
So it looks like it's my ISP. I'm in the UK so all torrent sites are blocked by ISPs but you can get around that with a VPN. Just tried to setup the TorrentDay indexer from behind a VPN and it worked. If I drop off the VPN the test connection fails, reconnect to it and it's successful. It didn't used to be like that so I'm assuming my ISP have rolled out some new type of "protection".
