### ISSUE TITLE
Centos 7 cannot start jackett version  v0.12.1590

### ISSUE THREAD

**Issue by warhansen** [Jackett/Jackett#6976]
I get the error:

```
01-19 10:29:42 Info Starting Jackett v0.12.1574.0
01-19 10:29:42 Error System.BadImageFormatException: Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Core, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The module was expected to contain an assembly manifest.
File name: 'Microsoft.AspNetCore.Mvc.Core, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

```
-------------------------------

**Comment by garfield69** [comment]
which jackett package did you install and from where?
looks like you were bitten by the old service/updater clash, where the updater is unable to replace files because they are still actively locked by the service.
Knowing which package you are using is needed so we can point you to the correct install instructions.

**Comment by warhansen** [comment]
Hi, 

I installed the Jackett.Binaries.LinuxAMDx64.tar.gz

**Comment by garfield69** [comment]
in that case, manually install the latest amdx64 from https://github.com/Jackett/Jackett/releases
using the service notes from https://github.com/Jackett/Jackett#install-on-linux-amdx64
and in particular, be sure to run the systemd installation script to replace the one you currently are using.
the new systemd script ensures that the service and the updater do not run at the same time preventing the updater from replacing all the binaries.
