### ISSUE TITLE
TorrentDay faulty URL

### ISSUE THREAD

**Issue by hk21x** [Jackett/Jackett#6998]
https://torrentday.cool/ is blocked across many places in the World and therefore, Jackett connections are failing. Can this be updated to https://tday.love or a way of modifying this be created?

**Comment by garfield69** [comment]
tday.love was put on the legacylink list because #6880 reported that torrentday had lost control of this domain, and when the domain registrar disabled it the domain address could no longer be resolved.
So we set the indexer to auto replace tday.love with torrentday.cool which was the next site link in the alternate domains list.
I did not expect this domain to be resurrected.
But I see now that it is back again, so I will reverse the change.
Once that is done, you will be able to edit the indexer config and select tday.love as a site link again.

**Comment by garfield69** [comment]
jackett 0.12.1632
