### ISSUE TITLE
[filelist] Access to the path 'C:\ProgramData\Jackett\Indexers\filelist.json.bak' is denied. (Config)

### ISSUE THREAD

**Issue by petercontact** [Jackett/Jackett#7001]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

(At the bottom of your Jackett Dashboard page) **Jackett version**:  
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**:

-------------------------------

**Comment by petercontact** [comment]
filelist used to to work fine on jackett, but on the newer versions it doesn't, i can log in on my browser without a problem, i try checking the url, the username and the password without success, i can look and see which version worked if you like

**Comment by garfield69** [comment]
the filelist indexer was changed 17 days ago, beginning with Jackett 0.12.1470, because of #6782
the site has changed their login check and the indexer need to be adjusted to cope.

but your error msg in the title of this ticket points to a permission problem ?
what version are you on?

Get on the latest version, and try using the trashbin icon on the jackett dashboard to delete the active filelist indexer and add it afresh from the add-indexer page and see if that helps.
