### ISSUE TITLE
Unexplained crashes after few hours

### ISSUE THREAD

**Issue by Killerherts** [Jackett/Jackett#7025]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

(At the bottom of your Jackett Dashboard page) **Jackett version**:  
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**:

-------------------------------
My jackett seems to be crashing randomly during and I cannot seem to tell what is going on from the log file. I have updated to  Jackett Version 0.12.1635.0 but i cannot see in my log why things are crashing to me it looks like the service was just stopped.
[log-error.txt](https://github.com/Jackett/Jackett/files/4113925/log-error.txt)
according to all my sonarr and radarr logs it crashed around 23:00 01/25.

**Comment by garfield69** [comment]
are you using a proxy or vpn?
there is nothing in the logs relating to an incident around 23:00 01/25

I see a variety of errors, a couple you can fix straight away, but I don't think they are responsible for your report. 
I suggest deleting and re-adding your *crazycorner* and *channelx* configs, as they are trying to use encrypted passwords that you no longer have a key for. 

The biggest headline grabber is with *Torrenting*, which seems to be throwing many *socket errors* causing query cancellations because jackett did not receive a timely response.
Also it is generating many *The response ended prematurely* errors, as part of a EstablishProxyTunnel circuit, so its likely your issue stem from the proxy session being dropped or interrupted, leading to the timeouts downstream.

Additionally, it looks like you are having trouble logging into *torrentleech* so I would review your account on that site and renew the jackett config for that indexer just in case.
But its possible the site's web server is also not working properly, I see quite a few *Error Bad Gateway* messages. So on reflection it may be that the problem is at their end.

And finally, at one point, you also had a glitch accessing the DNS, with a *Resource temporarily unavailable* error, which prevented jackett from starting on 2020-01-25 12:45:46

so my guess is that your problems mostly stem from issue with your proxy. I don't think there is any underlying issue with jackett in this case.

**Comment by Killerherts** [comment]
Issue did appear to be the proxy I moved the whole computer to a vpn and deleted the invalid config files and had no issues running all night.
