### ISSUE TITLE
[SceneHD] Implement passkey support

### ISSUE THREAD

**Issue by cadatoiva** [Jackett/Jackett#7034]
From the Jackett Discord, this tracker has passkey/API support. I've seen a couple other trackers be switched to this format, so maybe we should switch to this one from requiring a cookie line for more reliable access.

https://scenehd.org/browse.php?api&passkey=[passkey-here]&download=/

**Comment by Daikaro** [comment]
Guy who posted on discord here, the download link should look like this
https://scenehd.org/download.php?id=123&passkey=abc123
And search like this 
https://scenehd.org/browse.php?api&passkey=abc123&search=

123= Torrent ID
abc123=passkey

**Comment by ngosang** [comment]
I will take a look if someone invites me. ngosang @ hotmail .es

**Comment by Daikaro** [comment]
> I will take a look if someone invites me. ngosang @ hotmail .es

At the moment invites aren't open, I can give you an invite as soon as they open them but that could take a while. Any way I can assist you without giving you an invite?

**Comment by ngosang** [comment]
This is a big change and I can't do it blind. This will have to wait until some developer get access.

**Comment by Daikaro** [comment]
> This is a big change and I can't do it blind. This will have to wait until some developer get access.

I get that and I'll send you an invite as soon as they open them. I thought about giving you my account but I kinda don't want to risk it since it's over 12 years old and don't wanna risk loosing it.
I would be open to you connecting to my PC via teamviewer and using my account. Or join a discord together and then I can relay whatever info you require to make this work.

**Comment by RoloSoze** [comment]
@cadatoiva Making a note here for myself, and you, about this tracker :)

**Comment by garfield69** [comment]
Jackett 0.16.324
