### ISSUE TITLE
Fatal error on jackett start

### ISSUE THREAD

**Issue by AlessandroBerrone** [Jackett/Jackett#7039]
Hi, Jackett won't start on my machine.
Log says:

> 

Jan 29 11:22:53 vps177332.ovh.net systemd[1]: Starting Jackett Daemon...
Jan 29 11:22:53 vps177332.ovh.net systemd[1]: Started Jackett Daemon.
Jan 29 11:22:54 vps177332.ovh.net jackett[1324]: Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11
Jan 29 11:22:54 vps177332.ovh.net jackett[1324]: File name: 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
Jan 29 11:22:54 vps177332.ovh.net jackett[1324]: Aborted

>

I installed Jackett as a service, OS is Debian.

-------------------------------

**Comment by garfield69** [comment]
which jackett package did you install (mono, amdx64, arm32, arm64, docker, other ( please specify) ?

**Comment by AlessandroBerrone** [comment]
Sorry. it is amdX64.

**Comment by garfield69** [comment]
So it looks like you have been bitten by and old bug where the Jackett Service and the Updater clash.
This was fixed a long while ago, but does require and manual step on your part in order to ensure the fix gets applied.
So, follow the install as a service notes from https://github.com/Jackett/Jackett#install-on-linux-amdx64 and in particular, do the systemd script install, to replace the script which has been fixed to prevent the service being started while the updater is active.

**Comment by AlessandroBerrone** [comment]
Thank You @garfield69 I confirm it worked.
