### ISSUE TITLE
TorrentDay Issues

### ISSUE THREAD

**Issue by PureSp1r1t** [Jackett/Jackett#7049]
Hey, I've searched through the recent issues, but according to the responses, TorrentDay should be working fine. 

I'm running Jackett version 0.12.1638.0 and I can't edit my current TorrentDay entry, and TorrentDay isn't coming up in search when trying to add a  new indexer. It hasn't been working for a long time for me, is this something I'm doing wrong?

I can get the logs, but as TorrentDay is missing from the search entirely, I don't see the point atm.

Also, sorry if this isn't how this works. I am not a good GitHub user.

**Comment by garfield69** [comment]
I am not entirely clear on what you are reporting.
from the main Jackett dashboard, on your **configured indexers** page, if you enter **day** in the search box, do you get the Torrentday indexer showing up? (in my example below torrentday is not in my active indexers list).
![image](https://user-images.githubusercontent.com/6933240/73520344-4994d680-4468-11ea-877f-0aef6dfbf526.png)

if not there, then from the add-indexer page, if you enter **day** do you get the Torrentday showing up? (in my example below, torrentday is in my add-indexers list).
![image](https://user-images.githubusercontent.com/6933240/73520325-3f72d800-4468-11ea-86bf-602ba1f473c6.png)


it has to be in one or the other of these two pages, since this indexer is written in c# it is part of the Jackett.Common.dll so there can be no question of the indexer being missing from your build.

**Comment by PureSp1r1t** [comment]
Fingers crossed replying as an email works, first time! I currently have it
in my active list. I'll try removing it and adding it again and get back to
you!

**Comment by PureSp1r1t** [comment]
Sorry it took me a couple days, but all is working well. Thankyou!
