### ISSUE TITLE
[REQ] tfa.tf private tracker

### ISSUE THREAD

**Issue by Token00** [Jackett/Jackett#7072]
tfa.tf is a german private tracker.
I was surprised it's not added yet, it's been around since years.
Would be a great additional source for Sonarr.
You can try getting in by submitting a request for invite at https://tfa.tf/invite_ask.php
Otherwise I will provide my account, let me know how to safely give you the details.

**Comment by garfield69** [comment]
nah, I'm not jumping hoops trying to pretend i'm an active user that will contribute to the site.
with 400 sites to maintain, there is not enough time in the day to keep all these site's ratios satisfied.

if you are willing to loan then send details to garfieldsixtynine @ gmail.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task. I'll let you know.

or you can wait for another volunteer to register and build the indexer ;-)

**Comment by garfield69** [comment]
Jackett 0.12.1815
