### ISSUE TITLE
Rollback .Net-core version targeting

### ISSUE THREAD

**Issue by cadatoiva** [Jackett/Jackett#7086]
I know it's generally good to keep on the latest versions of things, but in order to migrate FreeBSD from Mono to .Net-Core we'd need to rollback the supported version. FreeBSD and adjacent have .Net-Core in ports/packages, but it's currently only version 2.0.1.

If there's no features specific to v3.1 we're using, it would be helpful towards removing the mono dependency entirely if we target v2.0 instead for now. I can make the changes and submit the PR, I just want to make sure that the effort won't be rejected for one reason or another before I put in the work.

**Comment by junglebus** [comment]
The nice thing is we are already multi-targeting. About half of Jackett users are running .NET Core and the other half on full framework(they are using 2.2 libraries) . So it wouldn't be hard to target .NET Core 2.0 as well.
See here for conditional references https://github.com/Jackett/Jackett/blob/master/src/Jackett.Server/Jackett.Server.csproj#L31 and there was very few breaking changes between 2.0 and 3.0 so I think there is only one class with framework dependent code here https://github.com/Jackett/Jackett/blob/master/src/Jackett.Server/Startup.cs#L57

We definitely shouldn't be just downgrading everyone to .NET Core 2.0. It was end of life more than a year ago, there has been many improvements and we will screw the ARM users (ARM support added in 2.1 and improved in 3.0)

Before even considering merging it I would recommend trying it locally for a month and see what the stability is like. If you look at the dotnet repo they've done a lot of fixes for FreeBSD since 2.0 (and a lot of unit tests were failing on FreeBSD) so I wonder what the quality would be like and whether its worse than Mono today. Do you know of any open source projects currently running on the FreeBSD .NET Core port?

Other option might be to wait a few months for Microsoft to make an announcement about .NET 5. Current announcement sounds promising, but very high level https://devblogs.microsoft.com/dotnet/introducing-net-5/

**Comment by cadatoiva** [comment]
According to the [definitive guide](https://www.freshports.org/lang/linux-dotnet-runtime/) of the freebsd repository, exactly zero applications use dotnet-core.

The entire mono & dotnet system appears to be abandoned right now. There's only one person trying to pick up the project.

**Comment by junglebus** [comment]
Someone has created a 3.0 runtime here, so that might be worth trying https://github.com/jasonpugsley/core-sdk/wiki/.Net-Core-3.0.0-for-FreeBSD#runtime

But looks like there is still test failures https://github.com/dotnet/runtime/issues/14537#issuecomment-552590690
Practically think it will need MS to support it

**Comment by cadatoiva** [comment]
I think at this point it's just better to leave the status quo then, and wait for FreeBSD team & Microsoft to make the necessary changes for compatibility.
