### ISSUE TITLE
yggtorrent - new address https://www2.yggtorrent.se/

### ISSUE THREAD

**Issue by aarsenca** [Jackett/Jackett#7095]
yggtorrent just moved to https://www2.yggtorrent.se/.

I am running Version 0.12.1669.0.

I had never used YGGcookie before but it now seems to be the only way to configure yggtorrent in jackett. So I added YGGcookie as a new indexer, changed "ws" to "se" in both fields, found and copied the cookie and it tested OK right away. Is this the way to do it?

Thanks.

**Comment by garfield69** [comment]
Yes, **yggtorrent** is such a **pain in the backside** whenever they change their domain.
Normally you would be able to use the Jackett Dashboard to edit the yggtorrent config and update the **Site Link** to the new domain.
But because the yggtorrent.ws domain is returning ERR_NAME_NOT_RESOLVED instead of the usual redirect, the Jackett yggtorrent indexer config is broken, so you cannot easily fix the  Site Link yourself using the Jackett dashboard.
So using **yggcookie** is a good way to continue access to the yggtorrent site via Jackett, until we publish the next release with the fixed yggtorrent indexer, after which you will be able to go back to using the regular yggtorrent indexer again.
I'll will post an update here with instructions as soon as I've built the fix and published the next release of Jackett.

**Comment by garfield69** [comment]
the **YGGTorrent** website has changed their domain to **.se**

You should be able to get the Jackett **YGGTorrent** _Indexer_ working again as follows:

1. update Jackett to 0.12.1681 _(or newer)_
2. access your jackett dashboard and use the _wrench icon_ to edit your **YGGTorrent** indexer config.
3. Check/Set the **Site Link** to `https://yggtorrent.se/` and
4. Set the **Search and download URL** to `www2.yggtorrent.se`
5. Click **OKAY**
6. if you get an error, click **CLOSE** then edit again and click **OKAY**. it should save the second time.

Works for me.

if you are unable to upgrade to the latest Jackett for some reason, this backdoor method will allow you to edit the yggtorrent config directly to get it going.
1. shut down the Jackett service
2. edit with a plain text editor (linux/macos) `~/.config/Jackett/Indexers/yggtorrent.json` (windows) `C:\ProgramData\Jackett\Indexers\yggtorrent.json`
3. change the _sitelink_ **value** to `https://yggtorrent.se/`
```json
  {
    "id": "sitelink",
    "type": "inputstring",
    "name": "Site Link",
    "value": "https://yggtorrent.se/"
  },
```
4. change the _searchanddownloadurl_ **value** to `www2.yggtorrent.se`
```json
  {
    "id": "searchanddownloadurl",
    "type": "inputstring",
    "name": "Search and download URL",
    "value": "www2.yggtorrent.se"
  },
```
5. save your changes
```json
  {
    "id": "sitelink",
    "type": "inputstring",
    "name": "Site Link",
    "value": "https://yggtorrent.se/"
  },
```
6. start the Jackett service

**Comment by ngosang** [comment]
@garfield69 Could you add the backup links? https://www2.yggtorrent.se/engine/domains?attempt=1

**Comment by garfield69** [comment]
@ngosang  there is little point. the backup links are just redirects to the principal domain.

**Comment by bartounet16** [comment]
the key icon on yggtorrent leads to an error with me

 An error occured while updating this indexer
Login failed: Selector "div#top_panel:contains("Déconnexion")" didn't match
Click here to open an issue on GitHub for this indexer.

**Comment by ngosang** [comment]
> I cannot re add it...
the key icon on yggtorrent leads to an error with me

This has been fixed in the latest version of Jackett. Please, update and try to re-add.

**Comment by computeur** [comment]
https://ww3.yggtorrent.si/ https://www2.yggtorrent.se nothing works (host error 404)
Same with the Tor adress

**Comment by ilike2burnthing** [comment]
Open a new issue and provide the requested information.
