### ISSUE TITLE
[yts] Clearance failed after 30 attempt(s). (Config)

### ISSUE THREAD

**Issue by missingbeacon** [Jackett/Jackett#7129]
### Environment

**OS**: ubuntu 16.04

**.Net Runtime**: [Mono/.Net-Core/.Net-Framework]

**.Net Version**:

**Jackett Version**: Jackett Version 0.12.1732.0

### Description
Adding YTS gives this error : An error occured while configuring this indexer
Clearance failed after 30 attempt(s).
Click here to open an issue on GitHub for this indexer

**Comment by garfield69** [comment]
It seems an IP in your region was used to mount a DDoS attack on the YTS API server.
Your IP address must be in the same block as the offender, so it has been temporarily blacklisted by cloudflare (the service provider for YTS) and requires you to enter an anti DDoS reCaptcha challenge to prove you are human.
if you use your browser on the same machine that is running Jackett to access https://yts.mx/api/v2/list_movies.json you may see the recaptcha challenge before being presented with the json results `{"status":"ok","status_message":"Query was successful","data":{"movie_count" etc etc`

There is no free automated way for Jackett to solve the ReCaptcha so until YTS lift their DDoS protection you will just have to browse the web site instead of using Jackett.

**Comment by Hotwheels86** [comment]
stop

**Comment by missingbeacon** [comment]
> stop

?

**Comment by missingbeacon** [comment]
> It seems an IP in your region was used to mount a DDoS attack on the YTS API server.
> Your IP address must be in the same block as the offender, so it has been temporarily blacklisted by cloudflare (the service provider for YTS) and requires you to enter an anti DDoS reCaptcha challenge to prove you are human.
> if you use your browser on the same machine that is running Jackett to access https://yts.mx/api/v2/list_movies.json you may see the recaptcha challenge before being presented with the json results `{"status":"ok","status_message":"Query was successful","data":{"movie_count" etc etc`
> 
> There is no free automated way for Jackett to solve the ReCaptcha so until YTS lift their DDoS protection you will just have to browse the web site instead of using Jackett.

Claasic Hetzner users!!! Will try load jackett on a different host and see what happens
