### ISSUE TITLE
[Orpheus] "Use Freeleech Tokens when available" broken

### ISSUE THREAD

**Issue by sevensz** [Jackett/Jackett#7136]
If i have this option checked lidarr will not download from this tracker, "Getting release from indexer failed"

**Comment by garfield69** [comment]
@sentriz as the contributor who built this indexer, are you able to take a look at this ticket?

**Comment by garfield69** [comment]
@sevensz  it will be useful if you can provide an enhanced log of a test where you use Lidarr to download from Orpheus that fails.

Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. use Lidarr to attempt to download a single file from Orpheus that you know will fail (avoid using the Jackett aggregate indexer _ALL_, and turn off any other Lidarr indexers that are Jackett dependant by editing their Lidarr Indexers Settings and un-ticking the enable-RSS, enable-AS, enable-IS check boxes, to avoid excessive logging of events we are not interested in).
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

(Note: When you restart Jackett the enhanced-log switch will be turned off. This prevents performance hits during normal operations).

Thanks.

**Comment by garfield69** [comment]
@lukewowo are you able to confirm that freeleech token usage works on Orpheus using the Jackett Orpheus indexer?
If you have the FLT option ticked on the Orpheus indexer config, the download url that Jackett creates includes the &usetoken=1 parm, and if unchecked it uses &usetoken=0.
Also, if &usetoken=1 is used but the download is rejected by the Orpheus web site, the indexer is supposed to retry using the &usetoken=0 when it spots either the "You do not have any freeleech tokens left." or "This torrent is too large." responses.

I have a user here that has run into problems but since I don't have an account on the site I've no idea if this is a user error or if FLT usage is broken. Any help/info appreciated.

**Comment by lukewowo** [comment]
> @lukewowo are you able to confirm that freeleech token usage works on Orpheus using the Jackett Orpheus indexer?
> If you have the FLT option ticked on the Orpheus indexer config, the download url that Jackett creates includes the &usetoken=1 parm, and if unchecked it uses &usetoken=0.
> Also, if &usetoken=1 is used but the download is rejected by the Orpheus web site, the indexer is supposed to retry using the &usetoken=0 when it spots either the "You do not have any freeleech tokens left." or "This torrent is too large." responses.
> 
> I have a user here that has run into problems but since I don't have an account on the site I've no idea if this is a user error or if FLT usage is broken. Any help/info appreciated.

Been working fine for me here, across 2 different boxes (one is Linux, one is Windows).

**Comment by garfield69** [comment]
@sevensz  please log into Orpheus with your browser and check that your account is free from outstanding alerts, notices and unread emails, and also check you have a good ratio.
It is looking like the issue is restricted to your account and not actually a problem with the Jackett Orpheus indexer.
My earlier request for an enhanced log may be useful to determine this if you are unable to spot anything with your account.

**Comment by garfield69** [comment]
@yuri-moens has found the problem and provided a fix with #7179

**Comment by garfield69** [comment]
jackett 0.12.1795
