### ISSUE TITLE
Allow Multiple Instances of same tracker

### ISSUE THREAD

**Issue by lukewowo** [Jackett/Jackett#7163]
I think this would be useful for example Orpheus, where you could have one that has "Use Freeleech when available" ticked, and one not, so we can decide whether to use the FL token on search

**Comment by ngosang** [comment]
That implies a huge refactor in Jackett and I don't think this is useful for most users. Note that almost all private trackers will ban you if you configure 2 accounts with the same IP. There are few trackers based in tokens, most of them use ratios and you can spend your tokens to improve your ratio.

**Comment by ikki4** [comment]
@ngosang I can think of another use case for this. Let's say I'm in many trackers and I added them all to Jackett to be able to search for content in all my trackers using Jackett. Let's say I want to use only one of those trackers (let's call it tracker X) with Sonarr/Radarr because tracker X has plenty of freeleech and I want to allow Sonarr/Radarr to download freeleech torrents only. If I configure tracker X on Jackett to search for freeleech only, then Sonarr/Radarr will work as I want, but tracker X's non freeleech content would not come up when I decide to use Jackett's search. If I configure tracker X to not search for freeleech only, then the searches would be complete, but Sonarr/Radarr would not work as I want. If I could configure two separate instances of tracker X, one freeleech only and one not, then I would be able to do everything I want.

This will still not be useful for most people, though. But I don't know if you guys thought about this issue during the last 3 years, so I'm just sharing a thought here.

**Comment by ilike2burnthing** [comment]
As most indexers are written in YAML, this is easily done by copying the definition file to one of the alternative locations^, editing the filename, indexer ID and name, saving, restarting Jackett, and adding your modified indexer. You would need to monitor the original indexer for any updates and make them to your modified indexer.

Alternatively, if you're using Docker, just spin up a second instance of Jackett.

^ for alt locations, see the the log entry at startup which will include something like:

> Loading Cardigann indexers from: /config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /app/Jackett/Definitions

**Comment by ikki4** [comment]
> As most indexers are written in YAML

Looks like the one I wanted is not written in YAML lol

Inside the Indexers folder, I find the trackerX.json file, if I have configured the tracker on Jackett. If I haven't configured it, I can't find the tracker file anywhere in `C:\ProgramData\Jackett` (no json, no yaml, nothing). And just copying and renaming that json file is not enough, as the copy gets deleted from the Indexers folder when Jackett restarts.

**Comment by ilike2burnthing** [comment]
The definition files are in the Definitions folder.
