### ISSUE TITLE
RTorrent API Integrations / Categories

### ISSUE THREAD

**Issue by Goob00000** [Jackett/Jackett#7169]
### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

Please add support for the RTorrent API so files can be submitted directly from jackett in addition to the blackhole method. The blackhole method is great except when a remote seedbox is used which requires me to push the file using resilio or other methods.

A simple watcher service (maybe this is a separate package) that would simply push the files from the blackhole folder with tags added to achieve the same thing.

Ideally it would be nice to set the following parameters via a tag submitted to rutorrent:

Tracker name as a tag
Category as a tag (such as music)
Arbitrary tag (user defined)
Manual tag with upload
Prompt for tag features

Notify when the file was successfully submitted or not submitted.

The intent is just to help organize files submitted into the remote RTorrent instance. The blackhole method is rather limiting unfortunately. 

Oh yeh and Jackett is incredible.

**Comment by cadatoiva** [comment]
As far as I'm aware, Jackett isn't really meant to be a push interface for applications. As such, I'm not sure if or when this kind of request would even begin work. Especially since if we do this for one client, how many others will we end up needing to support and update if their interface changes?

It's already a full time job keeping our trackers up to date and running. I'm not saying it won't happen ever, but it's not something that'll happen anytime soon.

**Comment by ngosang** [comment]
I agree with @cadatoiva
Related requests: add subfolders in blackhole #6993 , add tags #7170 I think if we can create folders based in tags you can configure your external client to apply different configurations based on the folder. Don't expect this soon.
