### ISSUE TITLE
[pier720] Specified argument was out of the range of valid values.Parameter name: index (Config)

### ISSUE THREAD

**Issue by larrysharon** [Jackett/Jackett#7190]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
works for me. no details no help.

**Comment by larrysharon** [comment]
That’s weird. The same username and password that successfully logs in to the pier720 site is kicking back an error in Jackett.

Kindest Regards,

Larry Anthony Sharon
p: 917-385-1044
f:  954-281-5438
e: larrysharon@gmail.com

**Comment by garfield69** [comment]
suggest the following: using your jackett dashboard, trashbin your 720pier config, and add a fresh one with your current credentials and see if that works.

**Comment by garfield69** [comment]
I am seeing temporary outages from the site. a search attempt returned ERR_CONNECTION_TIMED_OUT
so its possible the server at 720pier is overworked and generating intermittent errors.

**Comment by garfield69** [comment]
@cadatoiva  on a related issue to 720pier, I'm occasionally seeing in my enhanced log the following:
```html
2020-02-12 12:14:19.0618 Error pier720: Error while parsing row '<li class="row bg2">
  <dl class="row-item announce_unread">
    <dt title="Unread posts">
      <a href="./viewtopic.php?f=34&amp;t=17920&amp;view=unread#unread" class="row-item-link"></a>
      <div class="list-inner">
        <a class="unread" href="./viewtopic.php?f=34&amp;t=17920&amp;view=unread#unread">
          <i class="icon fa-file fa-fw icon-red icon-md" aria-hidden="true"></i><span class="sr-only">New post</span>
        </a>
        <a href="./viewtopic.php?f=34&amp;t=17920" class="topictitle">NBA - ??????????</a>
        <br>
        <div class="responsive-show" style="display: none;">
          Last post by <a href="./memberlist.php?mode=viewprofile&amp;u=547" class="username">UnderArmour</a> « <a href="./viewtopic.php?f=34&amp;t=17920&amp;p=117054#p117054" title="Go to last post">Today, 07:43</a>
          <br>Posted in <a href="./viewforum.php?f=34">NBA</a>
        </div>
        <span class="responsive-show left-box" style="display: none;">Replies: <strong>3357</strong></span>							
        <div class="responsive-hide left-box">
          by <a href="./memberlist.php?mode=viewprofile&amp;u=2" style="color: #AA0000;" class="username-coloured">admin</a> » 31 Jan 2018, 12:30 » in <a href="./viewforum.php?f=34">NBA</a>
        </div>
        <div class="pagination">
          <span><i class="icon fa-clone fa-fw" aria-hidden="true"></i></span>
          <ul>
            <li><a class="button" href="./viewtopic.php?f=34&amp;t=17920">1</a></li>
            <li class="ellipsis"><span>…</span></li>
            <li><a class="button" href="./viewtopic.php?f=34&amp;t=17920&amp;start=3260">164</a></li>
            <li><a class="button" href="./viewtopic.php?f=34&amp;t=17920&amp;start=3280">165</a></li>
            <li><a class="button" href="./viewtopic.php?f=34&amp;t=17920&amp;start=3300">166</a></li>
            <li><a class="button" href="./viewtopic.php?f=34&amp;t=17920&amp;start=3320">167</a></li>
            <li><a class="button" href="./viewtopic.php?f=34&amp;t=17920&amp;start=3340">168</a></li>
        </ul>
        </div>
      </div>
    </dt>
    <dd class="posts">3357 <dfn>Replies</dfn></dd>
    <dd class="views">462430 <dfn>Views</dfn></dd>
    <dd class="lastpost">
      <span>
        <dfn>Last post </dfn>
        by <a href="./memberlist.php?mode=viewprofile&amp;u=547" class="username">UnderArmour</a>
        <a href="./viewtopic.php?f=34&amp;t=17920&amp;p=117054#p117054" title="Go to last post">
          <i class="icon fa-external-link-square fa-fw icon-lightgray icon-md" aria-hidden="true"></i><span class="sr-only"></span>
        </a>
        <br>Today, 07:43
      </span>
    </dd>
  </dl>
</li>':
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.Pier720.<PerformQuery>d__9.MoveNext() 
```
if the post does not have a download link then the post should be skipped.
this check should be one of the first checks to be done, before looking at seeders and peers and grabs, which in this instance are also missing, as are probably many other standard torznab required fields in this post.
Could you amend the 720pier indexer accordingly? Thanks.

**Comment by cadatoiva** [comment]
Yeah, I'll get that taken care of.

**Comment by larrysharon** [comment]
So I did what you suggested, trashed it in the Jackett dashboard and added a fresh one using the working credentials and this screenshot is what I’m getting now.

Kindest Regards,

Larry Anthony Sharon
p: 917-385-1044
f:  954-281-5438
e: larrysharon@gmail.com

**Comment by garfield69** [comment]
you did not include the screenshot ;-)
for me 720pier is down at the moment
![image](https://user-images.githubusercontent.com/6933240/74300744-9efcac00-4db5-11ea-81d7-6126ff2fa7cd.png)

**Comment by larrysharon** [comment]
Can you see it now?


Kindest Regards,

Larry Anthony Sharon
p: 917-385-1044
f:  954-281-5438
e: larrysharon@gmail.com

**Comment by garfield69** [comment]
no. email attachements are not propagated to the github.
you need to either embed the picture into the body of the email or use the github website directly.

**Comment by larrysharon** [comment]
<img width="736" alt="Screen Shot 2020-02-12 at 10 28 36 AM" src="https://user-images.githubusercontent.com/6014612/74349594-75765d00-4d82-11ea-88d8-19cd884943a0.png">

**Comment by larrysharon** [comment]
Sometimes it will say tracker added and but when I test it hangs and gives me a timed out message.

**Comment by garfield69** [comment]
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

(Note: When you restart Jackett the enhanced-log switch will be turned off. This prevents performance hits during normal operations).

Thanks.

**Comment by larrysharon** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/4194109/log.txt)

**Comment by larrysharon** [comment]
Hope I did it correctly.

**Comment by garfield69** [comment]
the log shows that your Jackett login to pier720 is being rejected
`Вы ввели неверный пароль. Проверьте его и попробуйте ввести ещё раз. Если проблема со входом останется, то сообщите об этом`
google translation: `The password you entered is incorrect. Check it and try typing again. If the login problem persists, then report it`

use your browser to login and check your account credentials
then reenter your login credentials in your Jackett pier720 config.

**Comment by larrysharon** [comment]
So strange.  I just tried it again and it added the tracker successfully (using same credentials).  Then I test the tracker and it comes back successful as well.  However when I run a manual search ie. ESPN or 30 for 30, the search comes up empty.  Here's another log:

**Comment by larrysharon** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/4194320/log.txt)

**Comment by garfield69** [comment]
if I search for `espn` from jackett's 72pier indexer I also get no results, so that matches what you are finding.

that is because the jackett 720pier is only looking at **topics**.

if I use the 720pier site from my browser, using the advanced search, I get the same no-results if i search **topics** for `espn`

But if I change the search to look at **posts** then I get results.

searching for `30 for 30` returns
 `The following words in your search query were ignored because they are too common words: 30 for 30.`

@cadatoiva  when you are next working on the 720pier indexer, can you also look into whether we need to change the search from topics to posts ?
there may be a valid reason why we are only looking at topics, but I cant think of a reason at the moment

@larrysharon  ok, so I suggest for now that you hold off using 720pier until we get the time to look into the use of topics versus posts, and sort out a few issues with the indexer.
we will post back when the research/fix is available.

**Comment by larrysharon** [comment]
Thanks guys!

Kindest Regards,

Larry Anthony Sharon
p: 917-385-1044
f:  954-281-5438
e: larrysharon@gmail.com

**Comment by cadatoiva** [comment]
Looking through it, it looks like we search topics because those are the individual torrents. For typical English forums they mean the following:

topics = forum threads
posts = thread comments

as such, since we are looking in titles of threads and not at individual comments inside threads to get the right download.

**Comment by cadatoiva** [comment]
Also, I'm having trouble getting the website to behave for testing (in my browser) and am reluctant to touch the code further for the moment as a result. I'll keep the parsing issue in mind going forward if anything else about this tracker breaks in the future.

**Comment by larrysharon** [comment]
Thanks for the update.

Hopefully this gets resolved at some point and the searches work better for this tracker.

Kindest Regards,

Larry Anthony Sharon
p: 917-385-1044
f:  954-281-5438
e: larrysharon@gmail.com

**Comment by cadatoiva** [comment]
Ok, I'm having a couple of problems trying to figure out how to work on this one. For one, searching posts instead of topics removes all torrent data from the results, such that you have to click a link to get the torrent data, which I suppose is fine since we already make a call to the details page anyway to finish up the torrent data with this one.

Second, I can't seem to find a search term that returns results on this tracker in our current search method, so the only reference to the old way I have is the empty search which brings up "latest topics" (https://720pier.ru/search.php?search_id=active_topics for reference)

The reason for the error in #7877 is because in "latest topics" there is a post that's discussing the off season that has no torrent attached to it, and since the code currently assumes every entry is a torrent, it fails on those entries that aren't torrents.

Looks like I'm just going to have to split the entire search logic to do one thing for empty and another thing entirely for keyword search. Fun...

**Comment by garfield69** [comment]
Jackett 0.14.358
