### ISSUE TITLE
[p2pelite] Error: Login failed!Username or password incorrect (Config)

### ISSUE THREAD

**Issue by AnthonyBe** [Jackett/Jackett#7201]
### Environment

**OS**: Windows 10

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**: .NET FW 4.8 Windows 10 May 2019 Update (CLR:4.0)

**Jackett Version**: 0.12.1811.0

**Last Working Jackett Version**: n/a

**Are you using a proxy or VPN?** yes (but also fails with VPN disabled)

### Description

When configuring the p2pelite tracker, after entering username and password, error is produced and tracker cannot be added

### Logged Error Messages

Error: Login failed!Username or password incorrect 

Full error from logfile - https://pastebin.com/PJNMB1NL

**Comment by garfield69** [comment]
Are you using a username or password that contains cyrillic characters?

**Comment by AnthonyBe** [comment]
Nope. But it does contain symbols such as @ / $ : _ % > @ -

**Comment by garfield69** [comment]
well those are withing the utf-8 set, so should not be a problem.
strange, because the error is very specific, either the username or the password is incorrect.
I have no problems logging into p2pelite with my win10 Jackett, and I just tested a password containing specials and brackets without problems.

Have you changed your password recently? 
did you logout of the site before using the password in the Jackett config?
(some sites do not save the password to their db until you logout...)

**Comment by AnthonyBe** [comment]
Interesting. So I went to the website, logged out, in, out just to verify:

1. I had correct username/password, and
2. the last action was to logout via website

I then went into Jackett and it allowed me to set it up!
