### ISSUE TITLE
[REQ] torrentazo.com

### ISSUE THREAD

**Issue by 97carmine** [Jackett/Jackett#7211]
Spanish public tracker of movies, TV, games, software, music and documentaries

https://www.torrentazo.com

**Comment by garfield69** [comment]
this site has titles that lead to multiple torrents in the details page.
this is not compatible with the cardigann yaml processor which expects a 1 title 1 torrent relationship.
this indexer will need to be written in c#.

**Comment by danimart1991** [comment]
What is the behavior with Indexers that has no info in search page and has "one title - many torrents". Are multiple calls allowed?

**Comment by garfield69** [comment]
>What is the behavior with Indexers that has no info in search page and has "one title - many torrents". Are multiple calls allowed?

My inclination is that if the site does not have an API we can use, then its probably better to just not bother coding an indexer for it, since in these days of DDoS protection, must sites will react negatively to multiple calls to fetch details pages to build a results page, even if the calls are spaced out.
@ngosang  Any thoughts on this?

**Comment by ngosang** [comment]
We try to make as few requests as possible. In most indexers all information in the search result page so 1 Jackett request = 1 site request. Spanish indexers are different from English sites because when you search a tv series, "mandalorian" for example. They only return 1 result and we have to request the "mandalorian" page to grab the episodes. We are already doing that in mejortorrent, divxtotal and newpct but the code for all these logic is a bit complicated. In a regular search 1 Jackett request = 2 or 3 site requests. I think that as long as the number of requests is low it is acceptable.

**Comment by 97carmine** [comment]
I close, redirect to https://www.madeintorrent.com #10455
