### ISSUE TITLE
[torrentdownloads] Exception (torrentdownloads): Clearance failed after 30 attempt(s).: Clearance failed after 30 attempt(s). (Test)

### ISSUE THREAD

**Issue by nydave69** [Jackett/Jackett#7229]
It's been failing for a week now, figured i would bring it to your attention.

**Comment by nydave69** [comment]
what good it posting test failures if it's just getting closed right away.

**Comment by garfield69** [comment]
your IP address appears to be in a block of IP addresses that Cloudflare (the service provider for the torrentdownloads web site) has blacklisted temporarily, due to a DDoS attack coming from that IP block.
While Cloudflare's anti DDoS protection is active, it requires you to solve a ReCaptcha challenge to prove you are human.
Jackett cannot automatically solve these ReCaptcha challenges.
Until torrentdownloads lift their protection you will have to forego using Jackett and just use your browser to view torrentdownloads search results.
