### ISSUE TITLE
[thepiratebay] Exception (thepiratebay): Request to https://thepiratebay.org/recent failed (Error 522) - The tracker seems to be down.: Request to https://thepiratebay.org/recent failed (Error 522) - The tracker seems to be down. (Test)

### ISSUE THREAD

**Issue by raysmoove93** [Jackett/Jackett#7256]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

How can I fix this issue?

**Comment by garfield69** [comment]
dunno. works for me right now.
its not Jackett.
Therefore its a genuine issue with TPB and there is nothing you can do about it.

**Comment by dskvr** [comment]
@garfield69 Of course it can be fixed. TBP often switches domain names. For example https://thepirate-bay.org/home11 is up, while thepiratebay.org is not. It's TPB tradition

**Comment by garfield69** [comment]
These are not **official** domains for TPB.
Seems most other unofficial proxies steal the TPB feed and present what appears to be TPB look, but behind the scenes the HTML is not the same or have intrusive ads and other click bait that prevent the Jackett Indexer from using the site.

But I've no problem adding unofficial proxies if they work with the Jackett indexer.

I will add https://tpb.bike/ to the SiteList as an alternate.

Do you know of any other that work as well as the .bike domain does?

**Comment by ilike2burnthing** [comment]
@garfield69 
A few quality and faithful alt sites can usually be found here - https://proxybay.github.io/

Current examples include https://thepiratebay.vip/ and https://pirateproxy.page/

A more recent addition to the torrent proxy scene is https://root.yt/

Not all of the sites work perfectly (see list of [issues](https://www.reddit.com/r/website/comments/fdhbxh/rootyt_tpb_proxy_and_other_torrent_websites/fksc5ve/) I have found so far), but its TPB proxy is what I currently use in DuckieTV, and would use in Jackett too were it not for the redirect issue (you can use https://tpb.root.yt/?ckattempt=1/ instead of https://tpb.root.yt/ as a workaround).
