### ISSUE TITLE
[scenetime] Your cookie did not work: The 'Value'='login,donateok' part of the cookie is invalid. (Config)

### ISSUE THREAD

**Issue by ronoray** [Jackett/Jackett#7274]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
works for me.
your cookie should look something like this:
`__cfduid=d***********0; PHPSESSID=3*********0; uid=4****8; pass=2*********9; acopendivids=login,donateok; acgroupswithpersist=nada`
but if you are on a Linux system, it will need to remove the `acopendivids=login,donateok;` because that cookie value get rejected on that platform.
