### ISSUE TITLE
Titles problem on newstudio.tv

### ISSUE THREAD

**Issue by imm21** [Jackett/Jackett#7331]
NewstudioL (and i think lostfilm too) have a problem with series titles that contains numbers like "Avenue 5", it have 05 (like a season) instead just 5. It make a problem in sonarr and series not detecting correctly. 

![jackett 2020-02-26 12-17-50](https://user-images.githubusercontent.com/10806691/75316942-4dfeb480-5899-11ea-878f-f1946f7ea5ba.png)

Second, if it possible, please add in titles of these both trackers series year. It should be fix for elements that have the sames titles and have issues in sonarr.
![years](https://user-images.githubusercontent.com/10806691/75316966-59ea7680-5899-11ea-82e8-3d4083cba0a6.png)

Thanks :)

**Comment by garfield69** [comment]
lostfilm web site does not have Avenue 5 in its catalogue, so this is not relevant.

the newstudio indexer does appear to be turning 5 into 05, as part of its season/episode processing.
I think I can fix this so it does not accidentally alter titles like Avenue 5 by focusing on the SxxExx pattern.

we drop the year deliberately because the CW series The Flash started in 2014, so the official title is `The Flash 2014`.
if we put the year of the current season 2019, then Sonarr will not match the title.

I'll post a fix when I've sorted the SxxExx pattern matching.

**Comment by garfield69** [comment]
Jackett 0.13.222
