### ISSUE TITLE
[HDArea] Login failed, got redirected (Config)

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#7368]
### Environment

**OS**: Windows 10 64-bit

**.Net Runtime**: N/A

**.Net Version**: N/A

**Jackett Version**: 0.13.228.0

**Last Working Jackett Version**: N/A

**Are you using a proxy or VPN?** No

### Description

The error occurs when I try to configure HDArea in Jackett

### Logged Error Messages

An error occurred while updating this indexer
Login failed, got redirected.

### Screenshots

N/A

### Enhanced Log
[log.txt](https://github.com/Jackett/Jackett/files/4269775/log.txt)

If an invite is required, signups are currently open, but not for long:
https://www.hdarea.co/signup.php

**Comment by garfield69** [comment]
Works for me.
admittedly, the hdarea indexer is a little out of date, and does not trap the login failed like it should, so it ends up failing at the torrent search page, causing a redirect to the login page.
but your logs show that the error is a login failure due to incorrect username or password.
```html
<h2>登录失败！</h2>
<b>错误</b>: 用户名或密码不正确！或者你还没有通过验证<br /><br />忘记了密码？
```
google translation
```html
<h2> Login failed! </ h2>
<b> Error </ b>: The username or password is incorrect! Or have you not verified yet <br /> <br /> Forgot your password?
```
I recommend you login to hdarea with your browser and confirm that your credentials are valid, that you do not have any outstanding alerts, notices or unread mail, and that your ratio is good.  
If you changed your password recently, make sure you logout of hdarea, as some sites do not save your account until you logoff.
then with your jackett dashboard, trashbin your hdarea indexer, add a fresh one, re-enter your credentials (even if they appear pre-loaded) and see if it works.

Meantime, I shall update the indexer to trap the login failure, and bring it up to date with the current nexusphp engine they are now using, as well as add the uhd movie category that they have added, and imdb support, and config sort options.... basically a total refresh ;-)
let me know how you go.

**Comment by garfield69** [comment]
Jackett 0.13.280

**Comment by RoloSoze** [comment]
> 
> 
> Jackett 0.13.280

Everything works fine now! Thank you, @garfield69

**Comment by RoloSoze** [comment]
@garfield69 Did you get the chance to implement IMDb ID support? It doesn't seem to be working at the moment.

**Comment by garfield69** [comment]
I added the standard imdbid support that all the other nexusphp 1.5b4 have.
But I did not bother testing it.
Just checked the the web site, and it does not find using &search=tt90302&search_area=4
but &search=90302&search_area=4 works, so i will amend the indexer to use the shortened imdbid.

**Comment by garfield69** [comment]
Jackett 0.13.378

**Comment by RoloSoze** [comment]
I just tested this and it still doesn't work. I tried searching multiple IMDb IDs via Jackett and none worked. Searching the same IDs via the website works fine. The tracker accepts the full ID format (ttxxxxxx). I'm using the latest version.

**Comment by garfield69** [comment]
Bugger, keep forgetting to add the imdbid to the modes! too many post-it notes on my terminal and a memory like a sieve. Sorry bout that. I'll upload an update shortly.

**Comment by garfield69** [comment]
Jackett 0.13.581
