### ISSUE TITLE
[demonoid] Exception (demonoid): Request [...] failed (Error Forbidden) - The page is protected by an Cloudflare reCaptcha

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#7495]
Main - Docker container - v0.13.446

Tests:
- Windows sandbox install - v0.13.446 & v0.13.378
- browser with same NordVPN server - presented with reCaptcha

Proxy - NordVPN (fails without due to ISP/country DNS blocking)
[Enhanced log - Demonoid.txt](https://github.com/Jackett/Jackett/files/4286299/log.-.Demonoid.txt)

```
Exception (demonoid): Request to
https://www.demonoid.is/files/?seeded=2&language=0&quality=0&to=on&query=
&sort=added&order=desc failed (Error Forbidden) - The page is protected by 
an Cloudflare reCaptcha. The page is in aggressive DDoS mitigation mode or your IP 
might be blacklisted (e.g. in case of shared VPN IPs). There's no easy way of making it 
usable with Jackett.: Request to https://www.demonoid.is/files/?
seeded=2&language=0&quality=0&to=on&query=&sort=added&order=desc failed 
(Error Forbidden) - The page is protected by an Cloudflare reCaptcha. The page is in 
aggressive DDoS mitigation mode or your IP might be blacklisted (e.g. in case of 
shared VPN IPs). There's no easy way of making it usable with Jackett.
```

From that warning I assume it won't be fixable in Jackett (feel free to close if so), but thought I'd post just in case. As far as I'm aware this is a recent change to Demonoid, as it only started failing yesterday.

**Comment by garfield69** [comment]
If you are seeing this then that means the IP address you are using is part of an IP block that has been blacklisted by cloudflare because of a (ongoing) DDoS attempt.
Jackett has not automated way to resolve the Cloudflare ReCaptcha challenge so there is nothing that can be done.
Your only option is to
a) wait for the protection to be dropped, 
b) see if the VPN you are using can choose another IP from a server in a different region 
c) use another VPN.
The Jackett Demonoid indexer works for me, so this is not a global block.
