### ISSUE TITLE
[Limetorrents] Error downloading limetorrents ; On attempt 1 - 3 downloading from LimeTorrents: The operation was canceled.

### ISSUE THREAD

**Issue by brianmathew** [Jackett/Jackett#7510]
OS: Windows 10
Jackett Version: 0.13.446.0
Are you using a proxy or VPN?: Yes

Description:
I get this error every time I search for a torrent manually. The browser keeps thinking for a while and it eventually times out with a 404 error. I also get the same error while downloading through RSS feeds.

Logged error messages:

When attempting a manual search, I get the following error with Limetorrents:

2020-03-05 17:54:35 | Error | Error downloading limetorrents https://limetor.com/Narcos-Mexico-Season-2-S02-720p-NF-WEB-DL-x265-HETeam-torrent-14242829.html
-- | -- | --
2020-03-05 17:54:35 | Error | On attempt 3 downloading from LimeTorrents: The operation was canceled.
2020-03-05 17:52:52 | Error | On attempt 2 downloading from LimeTorrents: The operation was canceled.
2020-03-05 17:51:09 | Error | On attempt 1 downloading from LimeTorrents: The operation was canceled.

The browser hangs up and then it displays this error:

This 127.0.0.1 page can’t be foundNo webpage was found for the web address: http://127.0.0.1:9117/dl/limetorrents/?jackett_apikey=cfq9ew1bw6ufw4dz8oxsdjxi2vl99t8b&path=Q2ZESjhGY2U3SmRiTGRGSnBxNDV5Q25GUHZwUDZJZWVaWS1sSUt5Vy1GeWc0WG1yTGd5Z3RzdjZpZ1pYUHNJWWRqLUVHYm01SnI4YnE2SjcxZ2NUVEZ2WG85S2l0US1vcjE1enV3SGc3aWhWVG9VTnhjSGlOLVcyTTR0cVhsVmlTbk5rdEZIXzA5U2ZJb3cxQmZGeURTNVJtX0lndElMSjVfUHpCc3Z4ZzZ6eHhDQlBZck1ZcUo5RHVIc2JXM0xYV3NoSjd2NEhQUDBuTXZGSUx6YTFud2RtalhBb3hNZWFmSGthS0JlTlpNSFRMNUZV&file=Narcos+Mexico+Season+2+S02+720p+NF+WEB-DL+x265-HETeam

**Comment by garfield69** [comment]
If your browser has problems downloading .torrent files from this site why would you expect Jackett to do any better? The issue is at the site.

Limetorrents use for their .torrent files a host service called itorrents.org
It is this service which is breaking and there is nothing you or I or Jackett can do about this.


But there is an alternative. 
Limetorrents also provide magnets.
You can switch to using magnets in the limetorrents Jackett indexer by editing the config with your Jackett dashboard and selecting the magnet from the download link pull-down.

**Comment by cadatoiva** [comment]
It looks like he's talking about his browser failing to download from the manual search in the Jackett UI, not on the tracker's webpage. I could be mistaken though
