### ISSUE TITLE
[spiritofrevolution] Login Failed, got redirected. (Config)

### ISSUE THREAD

**Issue by Winblackka** [Jackett/Jackett#7512]
I have followed the description how to login, but it doesn't work.

i have copied different options: (numbers and letters replaced by xxx, only here)

Cookie: JAVA=OK; PHPSESSID=xxxxxxxxxxxxxxxxxxxxxxxxxxx
 JAVA=OK; PHPSESSID=xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
PHPSESSID=xxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxx

**Comment by garfield69** [comment]
the cookie string is everything after the `cookie: ` header. 
on my win10 chrome browser the cookies looks like this 
`PHPSESSID=xxxxxxxxxxxxxxxxxxxxxxxxxx; JAVA=OK`
note: make sure to use a browser running on the same computer that is running Jackett.

**Comment by Winblackka** [comment]
> note: make sure to use a browser running on the same computer that is running Jackett.

That's the problem, I have tried to login from a different device

**Comment by cadatoiva** [comment]
You should be able to get the same effect by connecting through your server via ssh proxy. https://www.systutorials.com/proxy-using-ssh-tunnel/

**Comment by garfield69** [comment]
The web site uses a dynamic login method which builds selector names for the username and password dynamically at every login.
So I chose to use the cookie method as the quickest way to make the indexer available since this is a common method of bypassing login challenges.

But I see that the wiki for the Cardigann login processor (the engine that processess the yaml indexer that I build for this site) does apparently support some kind of dynamic selectors, but its not particularly clear to me how that works, and there are no existing active indexers that use this method that I can use as an example, so I will have to experiment and see if I get lucky.

**Comment by garfield69** [comment]
\o/ cracked it.
We can now use the method=form login for this indexer, so once the next Jackett version is published you can use your standard credentials to login with this indexer.

**Comment by cadatoiva** [comment]
720-pier was doing the same thing, so I might need to look at the code in the Cardigann indexer to see if there's a better way than what I ended up doing.

**Comment by garfield69** [comment]
Jackett 0.13.483

**Comment by Winblackka** [comment]
Thx again for your fantastic work. There is just a little problem:

Everytime Jackett is looking for something and im browsing the Website of the tracker - it logs me out. Could this be fixed? 

Thx again!

**Comment by garfield69** [comment]
It looks like SoR is only allowing one login session-id at a time. 
I think that this is the first site I've come across that behaves in this way, they must take their security very seriously ;-)

the only way to fix this is to switch the indexer to use the cookie method to access the site rather than performing a login.
Stand by I'll upload the change within the next half hour.

**Comment by garfield69** [comment]
Jackett 0.14.459

**Comment by Winblackka** [comment]
Im copying this one: 

JAVA=OK; PHPSESSID=XXXXXXXXX

Now i get this message again. :(

Login Failed, got redirected. (Config)
#7512

**Comment by garfield69** [comment]
Jackett 0.14.476

**Comment by Winblackka** [comment]
And again, thx thx thx. :)
