### ISSUE TITLE
[tvchaosuk] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by ericbogs** [Jackett/Jackett#7535]
It looks like #7327 is still happening. Not sure if the admins at TV Chaos UK are continuing to tweak the site. Thanks for your help!

### Environment

**OS**: Ubuntu

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.13.483.0

**Last Working Jackett Version**: Hasn't been working for 3-4 weeks. I saw @garfield69's fix in 0.13.211 and decided to upgrade (to latest 0.13.483), hoping the issue would resolve. Unfortunately, it hasn't.

**Are you using a proxy or VPN?** no

### Description

TVChaosUK started failing Jackett tests recently:

"An error occured while testing this indexer
Found no results while trying to browse this tracker"

### Logged Error Messages

System.Exception: Error while parsing field=description, selector=a[href*="/categories/"] div i, value=<null>: Selector "a[href*="/categories/"] div i" didn't match 

at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1575

Please see 
[Untitled 4.txt](https://github.com/Jackett/Jackett/files/4299362/Untitled.4.txt)

--

### Screenshots

n/a

**Comment by ericbogs** [comment]
Note a duplicate. Issue remains in 0.13.483

**Comment by garfield69** [comment]
works for me.
if you are still seeing 
```
System.Exception: Error while parsing field=description, selector=a[href*="/categories/"] div i, value=<null>: Selector "a[href*="/categories/"] div i" didn't match 
```
then this means that your tvchaosuk indexer is not up to date.

since you are on ubuntu, the most likely explanation is that you are running into an old problem that cropped up a long while ago, with the Jackett service and the updater clashing during updates.

please manually install the latest Jackett from https://github.com/Jackett/Jackett/releases by following https://github.com/Jackett/Jackett#install-on-linux-amdx64
And in partucular, make sure to run the systemd install script. 
It is this script that updates the systemd startup to ensure that the service and the updater do not run together.

**Comment by ericbogs** [comment]
Thanks for your helpful reply. That did the trick! Thanks again.
