### ISSUE TITLE
TehConnection (TEH) - Blank search results under the 'name' column

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#754]
Hey guys!

A picture is worth 1000 words in this case:

![teh](https://cloud.githubusercontent.com/assets/23747425/20652550/7f386cfa-b50c-11e6-86bb-935b9201c611.jpg)

![teh 2](https://cloud.githubusercontent.com/assets/23747425/20652576/d7d332c8-b50c-11e6-93ce-394bbe60ed61.jpg)

Just a couple of examples of how the name/hyperlink is blank for some search results. Seems to occur randomly.

**Comment by kaso17** [comment]
To fix it I would need an invite (kaso1717 -at- gmail.com)

**Comment by armani316** [comment]
Unfortunately, I'm yet to earn an invite there. I hope someone else can help out!

**Comment by depraved22** [comment]
Invite sent.

**Comment by kaso17** [comment]
@depraved22 I didn't receive anything (already checked spam)

**Comment by kaso17** [comment]
got it, thank you.

The problem is that the original release title is simply not available for some releases.

If you use the little miss sunshine example:
https://tehconnection.eu/torrents.php?id=920
Click on the first two releases to expand the description:
x264 / Matroska / Standard Def / DVD   (1.37 GB)
x264 / Matroska / 720p / Blu-ray   (10.19 GB)

For the second one "Little.Miss.Sunshine.2006.720p.BluRay.DD5.1.x264-CtrlHD" is set, for the first one it's empty.

To fix it I would suggest to build the title from the available information if there's no real release title.
E.g. in the example jackett would return the following title instead of the blank title:
Little Miss Sunshine (2006) - x264 / Matroska / Standard Def / DVD

Is that ok with you?

**Comment by armani316** [comment]
@kaso17 Just noticed that there are no titles for some torrents with a movie. You're right. 
If there's no solution, I guess building the title from the available info works for me. Thanks!
