### ISSUE TITLE
[PrivateHD] [CinemaZ] [AvistaZ] Add missing categories

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#7593]
Example search: `The Beast in Heat`

**Comment by garfield69** [comment]
this indexer uses the abstract avistaztracker and needs some desperate c# attention.
the whole movie category processing sucks, look at this ugly results page
![image](https://user-images.githubusercontent.com/6933240/76251226-919aea80-62ab-11ea-9d28-de4c7c89e01a.png)
Can't we do better?

**Comment by ngosang** [comment]
I will take this one

**Comment by ngosang** [comment]
I don't know how to map this... they have 3 main categories, movies, tv and music. An then filters by video quality and source.
Should I keep only the 3 main categories?
All the torrents in this site are HD, so the category should be Movies or Movies/HD?
For example, in Sonarr the default categories for search are `5030,5040` but we are only mapping `5000 / TV`. Jackett knows what to do in that case?
![image](https://user-images.githubusercontent.com/10577978/76365967-f183a680-6328-11ea-8c0f-e1fcefb46753.png)

**Comment by garfield69** [comment]
Before I answer this, I would like to see what Avistaz and CinemaZ look like, which are the other two avistaztracker abstract dependants.

@RoloSoze  can you provide a screencapture of the advanced search page, just like ngosang did, for Avistaz and CinemaZ so that we can cross check with how PrivateHD looks ? Thanks.

**Comment by RoloSoze** [comment]
@garfield69 Here you go:

AvistaZ:
![image](https://user-images.githubusercontent.com/23747425/76369732-df930b00-630a-11ea-97f9-c4508182cedd.png)

CinemaZ:
![image](https://user-images.githubusercontent.com/23747425/76369755-fd607000-630a-11ea-805b-e64407e8cf25.png)

**Comment by RoloSoze** [comment]
> All the torrents in this site are HD,
@ngosang In very rare examples, you'll find SD content on PHD, but those are exceptions, and even those will be mostly under the 720p category, or the 1080p category for mixed packs.

Try searching for DVDRip.

**Comment by garfield69** [comment]
> in Sonarr the default categories for search are 5030,5040 but we are only mapping 5000 / TV. Jackett knows what to do in that case?

yes it does. I tested the Sonarr indexer for PrivateHD with categories set to 5030,5040 and it received results without issue. 
you can see this for yourself using the Jackett Dashboard search. If you filter only for 5030,5040 and do a search, you still receive all TV results.

I think this is because 5030 and 5040 are subcategories of 5000 and so pass the filtering.
***
OK.
So it looks like the categories/quality of AvistaZ == CinemaZ and PrivateHD is a subset. (only missing quality=sd and and few rip-types which we are not interested in).

The ideal scenario is for only one category to be allocated per torrent.
but I see no reason why we should not include the quality to refine the categories.

So I propose the following:
alter the avistaztracker abstract so that we leave the main cats 1, 2, 3 (but drop the movie subcats from cat1)
then add the movie and tv subcats found via their quality tags

So the mappings would look like this:
```c#
            AddCategoryMapping(1, TorznabCatType.Movies);
            AddCategoryMapping(2, TorznabCatType.TV);
            AddCategoryMapping(3, TorznabCatType.Audio);
            AddCategoryMapping(4, TorznabCatType.MoviesUHD);
            AddCategoryMapping(5, TorznabCatType.MoviesHD);
            AddCategoryMapping(6, TorznabCatType.MoviesSD);
            AddCategoryMapping(7, TorznabCatType.TVUHD);
            AddCategoryMapping(8, TorznabCatType.TVHD);
            AddCategoryMapping(9, TorznabCatType.TVSD);
```
and we extract the base category from `row.QuerySelectorAll("td:nth-of-type(1) i").First().GetAttribute("class")` by regex the number (instead of the pokey sequence of replace statements which will always be subject to getting out of date) and assigning it to var `cat` ( will be either 1, 2 or 3)
and then for cat=1 and cat=2, we look for the first extra-badge and replace the cat as required
so `<span class="badge-extra">2160p</span>` for cat=1 would result in cat=4

Sonarr users who set their indexer category to 5000 will get everything.
Those that left it to the default will get only 5030 and 5040 (they will miss out on UHD unless they add 5045 to their Sonarr indexer config).

**Comment by garfield69** [comment]
Jackett  0.14.501
