### ISSUE TITLE
[estrenosdtl] add banner and files

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#7600]
* banner is available only in the new torrents page
* set files = 1 always

**Comment by garfield69** [comment]
this indexer does not access the new torrents page as its layout is different from the search page.
however, the search page with the empty search returns the content of the new torrents page anyway, only in grid layout rather than poster layout.
So no posters.

Its not common to provide a default value for files. if the site does not provide any then this is usually left null which is within the torznab specs.

**Comment by ngosang** [comment]
> Its not common to provide a default value for files. if the site does not provide any then this is usually left null which is within the torznab specs.

But if we know it's always 1 I think it's right.

You are right about the banner.
