### ISSUE TITLE
[moecat] Exception (moecat): Error: 姿势不正确两步验证码未输入！: Parse error (Test)

### ISSUE THREAD

**Issue by budgetfermium** [Jackett/Jackett#7644]
To reproduce:
1. Enable two factor authentication
2. Attempt to login

Logged Error Messages:
Jackett.Common.IndexerException: Exception (moecat): Error: 姿势不正确
两步验证码未输入！

Since two factor authentication can't be disabled once enabled on this private tracker, could you please add two factor authentication support?

**Comment by garfield69** [comment]
None of the team have an account on this site so we cannot test our changes.
Registration is currently invite only
But access may not be necessary if you can answer the following:.

I see that the moecat login has a 2-step verification code box
![image](https://user-images.githubusercontent.com/6933240/76674730-5be16300-6617-11ea-9f0a-e498e24b61f2.png)
Is it simply a matter of entering the code as part of the login, or is there a further challenge afterwards?

If everything you need to login can be entered in the first login panel, then it is any easy matter to add the field to the existing config, and users without 2fa can leave it blank.

But if there is an additional check after filling in the login panel, then I will need to clone this indexer as moecat2fa and use the cookie method.

However, if the cookie method does not work , then since Jackett's Cardigann processor (with processes the current moecat.yml indexer code) does not support multi step logins, then the indexer will need to be migrated to one written in C#, at which point an account will be necessary for testing.

so I await your reply with interest ;-)

**Comment by budgetfermium** [comment]
@garfield69, it is indeed simply a matter of entering the code as port of the login. There is no further challenge afterwards.

**Comment by garfield69** [comment]
Jackett 0.14.12
