### ISSUE TITLE
[New Tracker REQ] Torrent-BD (TBD)

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#766]
Hello! It would be great if this tracker can be added to the list of supported indexers! 

Site: http://www.torrentbd.com/torrent/index.php

An invite has just been sent to -removed-

Invite expires in 5 days, so better sign up ASAP. Thank you!

**Comment by kaso17** [comment]
Thank you for the invite.
Did you have to solve a cloudflare recaptcha challenge for the first time you accessed the website too?
Or must it be solved regularly?

**Comment by ShahadatRD** [comment]
you just need to solve this once from a ip. if your ip is blacklisted, then you have to solve the captcha each time.

**Comment by kaso17** [comment]
ok, that makes the login more complicated.

**Comment by ShahadatRD** [comment]
not at all. that for a security issue though.

**Comment by kaso17** [comment]
The problem is that Jackett has to solve it. It's the first tracker which requires a cloudflare captcha.
I should be able to implement it just like the other recaptcha trackers. But for seedbox users accessing jackett not via 127.0.0.1 getting the cookies will be annoying. They'll have to setup a VPN/proxy via their servers and fake their useragent to get a valid cloudflare cookie.
To make it easy for remote Jackett users I'll have to look into a way of completely proxying the recaptcha.

**Comment by ShahadatRD** [comment]
as i said, the captcha issue will not make you bore untill your ip is blacklisted. so, it might not gonna create any issues while accessing from seedbox. whatever, for making sure about this, you can do a implement. if your concern is right, then their must be way to bypass/resolve this.

**Comment by kaso17** [comment]
Should be implemented with 88002d4b53c3612facf556d8a6f34e36ed28c1bb

**Comment by ShahadatRD** [comment]
well, lets have a try...

**Comment by kaso17** [comment]
With my IP I've to solve the cloudflare captcha every few hours making the tracker integration completely useless.

**Comment by armani316** [comment]
It's been working fine for me since it was added in the last update. No problem at all.
