### ISSUE TITLE
[enhancement] Improve query.MatchQueryStringAND to handle accents

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#7673]
The current implementation of `query.MatchQueryStringAND` doesn't handle accents. => https://github.com/Jackett/Jackett/blob/fe3fcda35632a119f7f92a23620d2fc56284defa/src/Jackett.Common/Models/TorznabQuery.cs#L149

For example, in Spanish is typical to perform a search without accents `termopilas` and get results with and without accents `las temópilas`. That is right because in most languages the words mean the same with or without accents.

Several trackers have their own implementation because `query.MatchQueryStringAND` doesn't work for them. For example, I wrote [this method](https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/DivxTotal.cs#L330) for Spanish trackers (but it should work well for other languages too). It's used by DivxTotal, Mejortorrent and EpubLibre.

I'm proposing to add a parameter in `query.MatchQueryStringAND` to chose if you want to remove accents or not (by default I think it should be yes). And use an improved version of the code that I wrote. The performance of that code can be increased by caching regex, etc...

The method `query.MatchQueryStringAND` is used by Cardigann indexers too, so it can help to fix some indexers. I saw weird text replacements in some .ymls. => https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/CardigannIndexer.cs#L1587

This is optional, but will be a good idea to add some unit tests in the `Jackett.Test` module so we assure that this code is not broken in the future.
| Search | Title        | Return |
|--------|--------------|--------|
| harry  | harry potter | true   |
| harry  | Harry Potter | true   |
| harry  | Dark soul    | false  |
| temopilas  | las temópilas    | true  |
| temópilas  | las temopilas    | true  |
| harry potter  | Harry Potter    | true  |
| potter harry  | Harry Potter    | true  |
| harry pato  | Harry Potter    | false  |

UPDATE: In this PR are some tips to improve performance => #7669

**Comment by cadatoiva** [comment]
Found this already in the source code. Might help with this issue:
https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Utils/StringUtil.cs#L29-L42

**Comment by cadatoiva** [comment]
Moving the discussion here.

Looks like I'll be making an enum to pass in what should and shouldn't be removed so there's more options. Default to strip everything, and you can make it less strict on request. Diacritics, punctuation, letters only but keep diacritics, strict. 

And then add args for Cardigann to utilize all of the same.

**Comment by RoloSoze** [comment]
Not related to accents per se, but garfield69 mentioned that the issue I raised here #8230 might be related to how MatchQueryStringAND is handled in TorrentLeech.

**Comment by cadatoiva** [comment]
I'll keep it in mind when I get to this project.

**Comment by RoloSoze** [comment]
> Not sure what I can do about that though, as the system will need to understand whether a punctuation mark is supposed to split into multiple words or not.

To be honest, I couldn't deduce the logic behind the underscore in #8230; I was hoping you guys might have seen something similar before.

**Comment by ngosang** [comment]
@cadatoiva I'm expert in information retrieval. This code has low performance, but the goal is to archive similar functionality. => https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/DivxTotal.cs#L330
We have to remove some characters like ``` ` , '  and . ```, split words, remove non meaningful words (stopwords like the, of, a, an...), remove accents... but don't get mad removing too many things because the Unicode standard has more than 100.000 characters and that is not going to work. Most modern languages already have NLP functions (Normalization, Tokenization, Stopwords, ...) that are Unicode compatible and have good performance. Take a look at https://stackoverflow.com/questions/249087/how-do-i-remove-diacritics-accents-from-a-string-in-net
Just put me as reviewer when you have something.

**Comment by RoloSoze** [comment]
@ngosang This is a great point because I remember raising the issue of special characters with @kaso17 around 2017. Different trackers have different ways of processing special characters such as the ones you mentioned. What makes things worse is that different uploaders name their releases differently when there are special characters in the title.

For example, `Where'd You Go, Bernadette 2019` was a nightmare for me when I was looking for it. Some trackers require you to enter the title exactly as it is. Other trackers will remove only one of the special characters but not the second, and some trackers removed both, so you end up with 3 variations other than the exact title, and searching with one doesn't guarantee to return all relevant releases if the spelling is different:

`Where'd You Go, Bernadette 2019` OR
`Whered You Go, Bernadette 2019` OR
`Where'd You Go Bernadette 2019` OR
`Whered You Go Bernadette 2019` 

This is why I started placing so much emphasis on the IMDb ID because it's just easier to search with it when the tracker uses it correctly.

**Comment by cadatoiva** [comment]
Yeah, I was going to implement something using the static functions of `char` such as `char.IsLetterOrDigit(char c)` or `char.IsPunctuation(char c)` which uses the Unicode character description classes to make that determination. Combined with first using `string.Split()` which uses `char.IsWhiteSpace()` to split words, this would make for a largely language agnostic and relatively quick way to start. (Benchmarking shows code similar to `for (char c = 0x0000; c <= 0xFFFF; c++) if (char.IsLetter(c)) Console.Write(c);` takes < .015 seconds for the entire unicode character space)

But that doesn't help with diacritics or non-whitespace word separators. Being language agnostic also means that due to logographic writing systems (like Chinese) we wouldn't be able to filter by word length like in DivxTotal.cs necessarily.

Your stack overflow link has some good secondary information linked in its answers, I'll look deeper into that before I come up with a solution to test.

**Comment by ngosang** [comment]
Should fix this too #8215

**Comment by ilike2burnthing** [comment]
[v0.20.3236](https://github.com/Jackett/Jackett/releases/v0.20.3236)
