### ISSUE TITLE
[RARBG] Missing results in torrent search

### ISSUE THREAD

**Issue by alfablac** [Jackett/Jackett#7693]
### Environment

**OS**: gentoo 4.13

**Jackett Version**:
latest

**Are you using a proxy or VPN?**
no

### Description

Using the RARBG indexer, choosing all categories, some results are missing from the search. In the PC/Games category none of the "repacks" come in the result, while in the website, scene and repack releases they all come in the same category (PC/Games)

### Logged Error Messages

No errors shown.

**Comment by garfield69** [comment]
I'm not sure I am seeing what you are reporting.
It would be clearer for me if you could provide a couple of screencaptures, one of the RARBG web site that shows the results you are expecting, and one of the Jackett Dashboard search of RARBG that shows the issue you a reporting.
Thanks.

**Comment by MaDTaZ** [comment]
I am think that he is saying that when he search 
![image](https://user-images.githubusercontent.com/12501760/76812722-08a41780-67b3-11ea-928d-d7d12c072edf.png)

But if you look that section is not in the catagories


![image](https://user-images.githubusercontent.com/12501760/76812809-515bd080-67b3-11ea-96b6-fb6cd96ff2b7.png)

Categories look like this

http://rarbg.to/torrents.php?category=2;27;28;29;30;31;32;40;53

**Comment by garfield69** [comment]
Jackett is constrained by the Torznab categories numbering system as specified in the [nZEDb numbering specifications](https://github.com/nZEDb/nZEDb/blob/dev/docs/newznab_api_specification.txt#L608-L695).

Because the RARBG categories 2;27;28;29;30;31;32;40;53 do not have a direct corresponding Torznab category, they are mapped to the **custom** categories in the 100000 range.
So for instance, the RARBG category **Games/PC ISO (27)** is mapped to **100027**.
Here is the mapping table that lists the RARBG categories with the Torznab ones:
https://github.com/Jackett/Jackett/blob/889a8da4e5f046d029d86aa34b35f2854c9f67ed/src/Jackett.Common/Indexers/Rarbg.cs#L81-L104

So to filter the Jackett RARBG indexer results to include, for instance, only **Games/PC ISO**, you select from the pull-down **100027**.
![image](https://user-images.githubusercontent.com/6933240/76814924-07312880-6861-11ea-8c8f-b4145c4a9153.png)

What may be confusing is that the indexer results for that category you just filtered are displayed not as the custom number, but as the parent category number **PC/Games**. That is a Torznab requirement.

**Comment by alfablac** [comment]
Wowza. At first, I would agree I'm crazy, but I'm trying to find the URL I was browsing the other day. RARBG (it was indeed rarbg, I double-checked okay) was showing me non-scene results in the search, but right now it only shows scene results, which makes Jackett works as it should. Weird is because most of the scene content works through their tracker, despite not being available in the search.
