### ISSUE TITLE
[Demonoid] Clearance failed after 30 attempt(s) - cookie method used

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#7850]
Docker container and Windows sandbox install of v0.14.275

My steps:
1. turn on NordVPN, same server as used for Jackett proxy (otherwise I can't access Demonoid due to ISP DNS block)
2. open configuration for Demonoid in Jackett
3. open demonoid.is in new tab
4. click 'Torrents' and complete Captcha challenge
5. open DevTools, refresh, copy cookie
6. return to Jackett tab, paste cookie, click Okay
7. wait for a few seconds until it fails

[log - NAS Docker.txt](https://github.com/Jackett/Jackett/files/4382489/log.-.NAS.Docker.txt)
[log - Windows Sandbox.txt](https://github.com/Jackett/Jackett/files/4382490/log.-.Windows.Sandbox.txt)

Not sure if it's connected or intentional, but I noticed that demonoid.json wasn't updated with the cookie. I tried adding it manually and restarting Jackett (service for Windows, container for Docker), but no luck, testing gives the same result.

Anything I'm doing wrong?

**Comment by garfield69** [comment]
the demonoid.json is only updated if the testing of the config is successful. 
There is little point saving the config if it does not work ;-)

its definitely something to do with how vpn's operate.
without vpn the cookie I grab from my browser works on my demonoid jackett indexer too.

I don't normally use vpn but I installed hide.me VPN just as a control for your testing, on my win10 devbox.
after activating and connecting the vpn, I cannot get the jackett indexer cookie from the browser to work either.
I am guessing that the vpn is using a different path for each session it opens, so that something is  unique enough for each session that the cookie from one session on the browser is not valid for the session for jackett.

**Comment by ilike2burnthing** [comment]
That makes sense. I'll leave this open for a bit, just in case anyone has a good idea of to get around this, but doesn't seem like an easy one. If not then I'll close it, not exactly like I haven't put enough on your plates recently 😋

**Comment by ilike2burnthing** [comment]
Closing as unresolved (for anyone coming across this). As you said, it's likely just a downside to using a VPN.
