### ISSUE TITLE
Torrents.csv

### ISSUE THREAD

**Issue by pauloloks** [Jackett/Jackett#7859]
how to change Torrents.csv from en-us to pt-br ?

**Comment by garfield69** [comment]
the language for https://torrents-csv.ml in its web site html is `<html lang="en">`
are you using a custom SiteLink?

**Comment by pauloloks** [comment]
Yes, it is a script that can run on the computer itself
I'm using it at the local address that I translated, so I would like to put it on pt-br for Radarr don't say it's a movie in English

**Comment by garfield69** [comment]
Jackett does not provide a method to customise the indexer language.
So your best option is to clone your local indexer under a different filename so you can customise its source to your needs.
To show you how, I first need to know what platform you are on (windows, macos, linux, whatever) ?
and which Jackett package you installed (amdx64, arm64, arm32, mono, docker, etc) ?

**Comment by pauloloks** [comment]
Linux amdx64

**Comment by garfield69** [comment]
Oh wait, just realised that torrents.csv is not a yml indexer but one written in c#.

Anyway, the language of the indexer html page is not relevant in this case. The indexer is not web scraping html, it is processing JSON.

Changingthe web page language to pt-br will not have any effect on how the JSON is converted to a torznab response and return to Radarr.

If your local script is generating Brazilian Portuguese titles, and you want Radarr to pick them up, you just need to add some BP profiles in your Radarr settings and then set your Radarr movie profiles to use then instead of the default English ones.

**Comment by pauloloks** [comment]
OK thank you
