### ISSUE TITLE
TehConnection (TEH) - Unable to login

### ISSUE THREAD

**Issue by savahu** [Jackett/Jackett#786]
When I add TEH as indexer, I get the following error:

> 'Configuration failed: Unable to login to TehConnection'.

I see the following messages in the log:

> 2016-12-02 15:49:41.4910 Error got NotImplemented/InternalServerError
> 2016-12-02 15:49:41.5053 Error request.Method: POST
> 2016-12-02 15:49:41.5053 Error request.Url: https://tehconnection.eu/login.php
> 2016-12-02 15:49:41.5053 Error request.Cookies:
> 2016-12-02 15:49:41.5053 Error request.Referer: https://tehconnection.eu/
> 2016-12-02 15:49:41.5053 Error request.RawPOSTDdata:
> 2016-12-02 15:49:41.5064 Error cookies:
> 2016-12-02 15:49:41.5064 Error headerString:

**Comment by kaso17** [comment]
The problem is caused by their webserver configuration, see https://tehconnection.eu/forums.php?action=viewthread&threadid=7392

To workaround the problem you can install the missing let's encrypt certificate on your system.
Alternatively you can disable certificate validation by starting jackett with "--IgnoreSslErrors  true"

**Comment by savahu** [comment]
Ah thank you!

**Comment by savahu** [comment]
Editing the Jackett service to run Jackett with '--IgnoreSslErrors true' solved this issue :)
