### ISSUE TITLE
[yts] Parse error: Count cannot be less than zero.Parameter name: count (Config)

### ISSUE THREAD

**Issue by fellipeisensee** [Jackett/Jackett#7867]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
this can happen when the indexer does not get a response from the YTS API server, either due to 
- the server being out of service or because the response was prevented by a network issue, 
- or because you are being blocked by your ISP, 
- or the site is usingthe Cloudflare anti-DDoS ReCaptcha challenge, 

just to list a few examples.
To check this for yourself, use a browser that is running on the same machine as Jackett via the same VPN/proxy if you are using one on Jackett, and click on this link
https://yts.mx/api/v2/list_movies.json
you should get a JSON response that looks a bit like this
```json
{"status":"ok","status_message":"Query was successful","data":{"movie_count":15856,"limit":20,"page_number":1,"movies":[{"id":16240,"url":"https:\/\/yts.mx\/movie\/sudsy-slim-rides-again-2018","imdb_code":"tt5941336","title":"Sudsy Slim Rides Again",
[etc etc etc]
```
if you dont get this then there is your problem and it has nothing to do with Jackett.
If you do get this, and you want to pursue the issue further then provide the requested info in the first post of this ticket and especially the enhanced log so that we can look into this further for you.

**Comment by garfield69** [comment]
BTW, the YTS indexer is working for me on my win 10 Jackett 0.14.287
