### ISSUE TITLE
[iptorrents] Request to Jackett server failed

### ISSUE THREAD

**Issue by Yuhanun** [Jackett/Jackett#7906]
### Environment

**OS**: Ubuntu 18.04.4 LTS

**Versions**:
I run the :latest from these images
https://hub.docker.com/r/linuxserver/jackett/
https://hub.docker.com/r/linuxserver/sonarr/
https://hub.docker.com/r/linuxserver/radarr/

**Last Working Jackett Version**: First time I try

**Are you using a proxy or VPN?** [yes/no] no

### Description
Go to your jackett page, add indexer -> search for "iptorrents", hit the 
![image](https://user-images.githubusercontent.com/49172424/77830917-36cb1500-712c-11ea-86ec-acf2d59166e8.png)

(forgot what the name is) and there you go.

### Logged Error Messages
Can't find any,

### Screenshots
![image](https://user-images.githubusercontent.com/49172424/77830908-25820880-712c-11ea-8ea2-31a23493a16b.png)

### Similar issues
https://github.com/Jackett/Jackett/issues/3932 -> unrelated because it happens after the settings are modified
https://github.com/Jackett/Jackett/issues/6850 -> im on latest version
https://github.com/Jackett/Jackett/issues/1792 -> Unrelated, i can access it just fine from my own isp

**Comment by garfield69** [comment]
I am sorry, but stating that you are on the **latest** Jackett is not useful, we really, really need to know what version of Jackett you are on, as the docker images are not built by us, and we have no control over them.
So please access your Jackett dashboard, scroll to the bottom, and report the version number there. 
This is so that we can eliminate possible fixes that have been published since the release you may be on.
Thanks.

**Comment by Yuhanun** [comment]
Hi, the issue was that i didn't actually have docker-compose pull the new images, my bad.

Issue closed.
