### ISSUE TITLE
[req] dirtytorrents.com

### ISSUE THREAD

**Issue by 3xploiton3** [Jackett/Jackett#7918]
Public meta-search engine https://dirtytorrents.com

**Comment by garfield69** [comment]
Dirtytorrents.com is a free meta-search engine.
The download links it provides are actually the torrent details pages of the sites that Dirtytorrents has  crawled for.
What this means is that this site in not suitable as a yaml indexer, because the Cardigann processor expects download links to be either URLs to a .torrent file or a URI of a magnet.
So this indexer will need to be coded in c#

**Comment by garfield69** [comment]
A possible complication to the usefulness of this site, in this current climate of DDoS attacks and ISP blocking, is that while dirtytorrents.com may be free of ISP blocks and anti-DDoS challenges itself, the pages that the sites links to for the downloads may not be, and so many users may get surprised when their download links don't get resolved. 
If we add this site as a c# indexer, we should probably put a warning info note in the config.

**Comment by ngosang** [comment]
I think we can't do this one. There is no way to get the download link because there are too many cases. Furthermore the site doesn't prove new content, it's just a mirror...
