### ISSUE TITLE
[New Tracker REQ] TenYardTracker (TYT)

### ISSUE THREAD

**Issue by adamwinn** [Jackett/Jackett#795]
Even tho it's a sport tracker, they have many tv shows uploaded there that are on thetvdb and would integrate into Sonarr.  Thanks! 

~~http://tenyardtracker.com/~~

forum https://talk.tenyardtracker.com/

**Comment by kaso17** [comment]
Please send an invite to kaso1717 -at- gmail.com and I'll add it.

**Comment by adamwinn** [comment]
I think invites are turned off right now.  Do you want me to temporarily change my account's password and share it with you?  Or give you my buddy's account for a while?

**Comment by garfield69** [comment]
#10020 highlighted that the web site has been supposedly temporarily moved to a forum based freestyle tracker while the original gets rebuilt.
Since the current indexer no longer works this will be removed and this ticket will track any work volunteers do to create a replacement indexer in c# to handle the forum version, if that is even possible.

**Comment by garfield69** [comment]
closing as stale.
