### ISSUE TITLE
7torrents: download links are not working

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#7966]
If I search "silicon valley" and click in the torrent "Silicon Valley. Season 6 (2019) WEBRip-AVC [Ukr.Eng] [Hurtom]" something weird happens. The magnet link is fine, just the torrent.

I get a link to => http://itorrents.org/torrent/10837fb3ef11ec1e82c126ec93a4e0fc3c775a47.torrent
But then I'm redirected to => https://www.limetorrents.info/home/

If I replace the hash with upper case hash it's working. (we can also change HTTP with HTTPS)
https://itorrents.org/torrent/10837FB3EF11EC1E82C126EC93A4E0FC3C775A47.torrent

I sent an email to the owner, but I don't know if he is going to change it. I think we should remove the link and let only the magnet until he answer.

**Comment by ilike2burnthing** [comment]
The Jackett provided link is working for me if I don't use a proxy. With a proxy results in same error as https://github.com/Jackett/Jackett/issues/7325

[log - no proxy - download.txt](https://github.com/Jackett/Jackett/files/4411953/log.-.no.proxy.-.download.txt)
[log - proxy - download.txt](https://github.com/Jackett/Jackett/files/4411954/log.-.proxy.-.download.txt)

v0.14.365.0 Docker container

**Comment by garfield69** [comment]
itorrents.org is run by the same people as limetorrents.
When itorrents.org cannot find a magnethash in its database it redirects to limetorrents.
this is normal behaviour.
It can take itorrents.org up to 4 hours before they have the latest magnets available as .torrents in their db
nothing can be done about this and it has nothing to do 7torrents
also common is when itorrents.olg fails to respond because of cloudflare DDoS.
The Jackett download processor does not expect to get an intermediate page between the http get of the downloadling and the delivery of the .torrent file.

**Comment by ngosang** [comment]
> It can take itorrents.org up to 4 hours before they have the latest magnets available as .torrents in their db

@garfield69 this can cause problems with new releases. I think most clients prefer .torrent instead of magnet when .torrent is available. But, if the torrent is not working they don't try the magnet. Since we also have the magnet link for all torrents, can we remove the .torrent download link? Just comment the code and let a message pointing to this issue.
