### ISSUE TITLE
[XSpeeds] Maximum torrent name length has been increased; not reflected in Jackett

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#7975]
XSpeeds has increased the maximum number of characters in the torrent name/title to 200 characters from the previous 50. However, this has not been reflected in Jackett. I tried reconfiguring the tracker but it didn't change anything.

Are there any changes that need to be made on Jackett's end? 

Some examples of particularly long titles to test:

The Assassination of Jesse James by the Coward Robert Ford
Borat Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan

These should be displayed in full now.

**Comment by RoloSoze** [comment]
@garfield69 Thanks. I see that the old code includes a note about the shortened release name.
If you are aware of other trackers, of which I'm a member, that truncate release names, please let me know. I already spoke to M-Team TP and FANO about this, and I believe FileList's truncated release names should be fixed when the API is implemented with #7004

**Comment by cadatoiva** [comment]
The way this tracker was previously bypassed the truncated name because the full name was found in an attribute of the HTML tag surrounding it. Which means that changing the max untruncated length wouldn't have made a difference in how we need to process it, unless they removed the attribute, but then we'd just lose all titles completely.

**Comment by garfield69** [comment]
Previously, the xspeeds web site had the abbreviated title in the **details** selector and the full title in the **tooltip** selector (tooltip was optionally missing, but in reality was always present).
Xspeeds have now simply swapped the text content between those two selectors around.
Since the swap, the old indexer code ended up always presenting the abbreviated title.
The new indexer code ignores the tooltip selector and always uses the details selector.

**Comment by cadatoiva** [comment]
Ah, so they moved the abbreviated title into the tooltip, breaking everything. Got it. That's kinda silly though, but oh well.

**Comment by garfield69** [comment]
Jackett 0.14.384
