### ISSUE TITLE
[prostylex] Exception (prostylex): Login Failed, got redirected.: Parse error (Test)

### ISSUE THREAD

**Issue by xif666** [Jackett/Jackett#7998]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: docker linuxserver/jackett

**.Net Runtime**:

**.Net Version**:

**Jackett Version**: 0.14.384.0

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
works for me.
see if the following applies to you.
https://github.com/Jackett/Jackett/wiki/Troubleshooting#login-failed-got-redirected
reply with an enhanced log if you still have issues.

**Comment by garfield69** [comment]
@littlejeem 
it appears from the log you provided that prostylex is not accepting your login attempt for some reason. Unfortunately nothing in the log points to a reason why the login did not work.

Read https://github.com/Jackett/Jackett/wiki/Troubleshooting#login-failed-got-redirected and follow the suggested steps provided, see if that help sort it out.
The indexer works for me, so we are fairly confident this is not a Jackett problem.
Let me know how it goes.

Also, you are on Jackett 0.14.112 and there has been changes since 16 days ago when this was published,  so you may want to upgrade to the latest version.

**Comment by littlejeem** [comment]
@garfield69 it seems the tracker no longer allows 'free' access. I set up an account and gave these credentials to Jackett, all started working. Happy my end for this to closed, sorry it was that easy.

**Comment by garfield69** [comment]
Oh!
It never occurred to me that you were leaving the login fields empty ;-D
Yes the site turned semi-private around Feb 20th
Only indexers marked public don't require logins, we try to keep those as flags up to date as we can.
