### ISSUE TITLE
(request) magnet link https://torrentdownloads.proxyportal.fun/

### ISSUE THREAD

**Issue by 3xploiton3** [Jackett/Jackett#8006]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Manjaro linux

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.14.376.0

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** no

### Screenshots

![image](https://user-images.githubusercontent.com/19517680/78328661-e596a780-75a9-11ea-9a3d-c0eccacc95ff.png)

please add to grab magnet link

**Comment by garfield69** [comment]
- access your Jackett dashboard and **edit** the indexer config (use the **wrench** icon)
- select **magnet** from the **Download link** pulldown
- click **OKAY**

Don't let the download icon in the Jackett search results fool you, it will be a magnet if you have set that config option.
Jackett cannot display the magnet icon for this site because the download link type is not available in the primary results page, its hidden in the torrent details page which is not accessed until you actually click on the download icon.
