### ISSUE TITLE
core: category parsing and filtering

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#8049]
I don't like how Jackett handles categories internally. I have found several issues in the C# indexers and each one is solving the problems in his own way or worst, it's not working at all.

In the following examples imagine a regular tracker with movies/tv. Each torrent can have only 1 category and the categories can be MoviesSD, MoviesHD, TVSD, TVHD only.

In the supported categories we have 6: Movies, MoviesSD, MoviesHD, TV, TVSD, TVHD . There aren't torrents with category Movies, but we add that category to search all movies categories.
NOTE: If I remove the Movies and TV categories, everything works fine in the following examples. **What torznabs says about this? Should we add Movies/TV categories in the trackers even if the trackers only have the children categories?**

**Example 1**
If I select category MoviesHD only, it works as expected. Sends MoviesHD id in the search, and filter the results that contains category MoviesHD. All the results are MoviesHD. Good.

**Example 2**
If I select the category "Movies" only. I expect to get all movies with all resolutions, but **I get 0 results.**
1. First issue: Some trackers will have a special category or parent category called Movies to search all resolutions. In that case the mapping is 1 to 1 and it's fine. If the tracker doesn't support that, we need to convert category Movies => categories MoviesSD & MoviesHD to search in the tracker with both. Maybe exists, but **I don't know any function in Jackett to do that conversion.**
2. Second issue: Assume the first issue is solved and the we have the expected results. The results will have the category MoviesSD or MoviesHD. Jackett has a filter that removes the results with a category not in the query.Categories(). In this case, Jackett will remove all results because none of them has the category Movies. **Jackett should be smarter and not remove the results with child categories.**

**Example 3**
If I select the categories "Movies" and "MoviesHD" (both). I expect to get all movies with all resolutions, the same as when I select the category Movies only (example 2). I'm getting only the movies MoviesHD. This case will be fixed if we solve both issues in example 2.

What do you think? @Jackett/maintainers @RoloSoze

**Comment by RoloSoze** [comment]
@ngosang I agree with your logic. I noticed a long time ago that things were a little inconsistent with regards to Jackett TV & Movie categories. I wasn't sure whether this is due to how Jackett defines these categories and their subcategories internally, or whether it has to do with having to deal with so many trackers that use different logic for defining their own categories. 

I didn't want to raise this issue personally because I didn't have a problem with it. That's because I never pick which category to search in Jackett or via the trackers' websites. In Jackett, my 'Category' is always set to 'Any'. This way I make sure that I search all categories, sort by size, and filter the results using specific keywords in the secondary box in Jackett, and that's it. I don't have to deal with any issues related to categories. 

Because of my approach, all that matters to me as an end-user is that all categories from every tracker are mapped in Jackett and nothing is missed, so as long as all relevant results are returned, I'm OK with it. I also do this because I don't trust that all uploaders/trackers will categorize torrents correctly. For example, 1080p REMUX movies should be under Movies/HD in Jackett, but some trackers treat those torrents as Movies/BluRay. Because of this, I don't want to check just one category and miss out on results from the other, so I just let Jackett search 'Any'. 

Apply this example to many other inconsistencies among trackers, or simply just different ways of defining categories, and it's potentially a mess, especially if you search many trackers at once. 

However, I agree with the rationale you gave:

Example 2, Point 1: If the parent category (e.g. Movies) is selected, results from all subcategories should be returned. If there is no parent category defined by the tracker, then results from all subcategories should ideally be selected and mapped back to Jackett's definition of the parent category. 

Example 2, Point 2 and Example 3: If that is indeed the case, both are major issues that should be resolved. I might not have encountered or noticed either of them, or even Example 2 Point 1, because I never specifically pick a category, but they should be addressed for the benefit of those who do.

**Comment by cadatoiva** [comment]
The fix is likely related to needing to summon parent- or sub- categories included in the results. The default search algorithm takes the categories you choose and passes them into the tracker, but holds on to them in the query object. Then filters the results by their categories before presenting them to the user. There is some logic hanging around to add in parent categories or to check if a category matches any sub-categories in addition to the main category being searched, but these are used in inconsistent ways across the trackers.

We should adjust the rules in BaseWebIndexer to make more sense from a user's intended usage.

**Comment by ngosang** [comment]
This is fixed only for AvistaZ trackers, we need to provide a global solution for all trackers.

**Comment by ngosang** [comment]
Jackett v0.16.1996
