### ISSUE TITLE
[req] theodyssey.cc - New italian tracker to add

### ISSUE THREAD

**Issue by VMax4** [Jackett/Jackett#8054]
http://theodyssey.cc/

It's a free new semi-private Italian tracker and would be great if you will add it to the Jackett list

**Comment by VMax4** [comment]
Thank you!!!

**Comment by garfield69** [comment]
### road block.
the site requires the user to say-thanks before the magnet is made available.
While the cardigann yaml processor is able to do this kind of pre-processing before downloading, the parms for the thankyou link are not available from the details link, its missing the memberid to whom the thankyou should be directed.
also the structure of the thankyou link is different than usual, with parms separated by semicolons instead of the usual ampers.
so for example, the download link from the results page might look like
`http://theodyssey.cc/index.php?topic=301.msg357#msg357`
and the download block has access to the topic, and msg, but the member is not provided.
this is actually available on the results page in the uploader details
`http://theodyssey.cc/index.php?action=profile;u=19`
which the download block cannot access.
so the download block needs to build
`http://theodyssey.cc/index.php?action=thank;msg=357;member=19;topic=301;refresh=1`
but the best it can currently do is
`http://theodyssey.cc/index.php?action=thank&msg=357&topic=301&refresh=1`
which will not get the job done.

Therefore this indexer will need to be written in c#

**Comment by cadatoiva** [comment]
Well, that's interesting. Although it doesn't put this 100% back into YAML territory, we just merged a PR that is one step away (adding the option to the YAML interface) from allowing you to use the semicolon as a param separator (#7915). If there were a way to either collect the Member ID or otherwise do without it, we could prevent needing a C# indexer on this one.

**Comment by garfield69** [comment]
one way this might work would be if the download block had access to the .Result.$varname variables created in the search block. I believe it has access to the .Config.$varname from the settings block, but I do not think it has access to .Result.$varname from the search block.
then I could add a fields selector for a field called, for example `member`, and the download block would be able to reference it as {{ .Result.member }} 
but because the download block is only processed from the details page, the result row that invoked it may not be available any longer?

**Comment by cadatoiva** [comment]
I'll look into this and get back to you on that. If it's feasible to make that kind of adjustment, I'll add both features to the Cardigann processor and we can proceed with a YAML definition for this one.

**Comment by VMax4** [comment]
I see, thank you for this update, and for everithing as well, do you think it will be possible to make a mod to have the download block working with this indexer?

Thank you again for all the support

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
Il venerdì 10 aprile 2020 03:19, garfield69 <notifications@github.com> ha scritto:

**Comment by cadatoiva** [comment]
@garfield69 I need some clarification on the Cardigann processor. When we need to create a download link that goes to some kind of details page to get the magnet/torrent, it looks like there's a way to add query params to our intermediate link via the YAML? Those can then be accessed in the Download section via `.DownloadUri.Query.Key` so this could be an existing way to pass over the `.Result.$varname` like you requested above.

**Comment by garfield69** [comment]
the DownloadUri var table is generated by Cardigann from the href in the fields block download selector, by processing all the parms in the url supplied.
so in the example I gave earlier, 
the indexer had a fields block download selector that returned a href=
`http://theodyssey.cc/index.php?topic=301.msg357#msg357` which points to the torretn details page we need to processes.

And Cardigann builds the one var `.DownloadUri.Query.topic` with value `301.msg357` or possibly even the value `301.msg357#msg357` not sure if it knows about # as a sub-document anchor or not.
And because that href does not have any other parms there will be no additional vars created.

I don't think Candigann can change that href, we needed it as it is to fetch the details page to get the thank you href and eventually the real download href for the .torrent or magnet,
otherwise I could just append my own parms to the href before the download block got control, and load it up with the member number and what not.
But If I did that the web site might complain that the href to fetch the details page is not valid?
Maybe I should try that out and see what happens.
let me test to prove it does not work.

**Comment by cadatoiva** [comment]
No, I see it. It currently only uses the link to get the download page. It's not what I thought it was.

**Comment by cadatoiva** [comment]
There is a Before sub-block sitting in the cardigann download code. It uses the download link as a referrer and lets you specify a page to request before running the actual download. Is that where you do the thank before getting going back and getting the real download link? It might be a good insertion point for some code that modifies the download link if needed.

**Comment by garfield69** [comment]
yes, the **before** block is the method by which we can fetch from the details page the thank you href and do a post or get to set the thank you. 
then the details page gets returned/refreshed and the download href should have become available for the download selector to find and be used to fetch the .torrent/magnet.
note that the **before** block is optional as many sites do not require pre-processing before looking for the download href in the details page.

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/wiki/Definition-format#download if want more details on the download block and the yaml statements that make up its processing.

**Comment by cadatoiva** [comment]
Yes, I saw in the code that it was optional (it checks for not null first). I also saw that we just throw away the page it gets. I'm about to submit a PR that add the separator specifier so you can change "&" to ";" at least. This will become available as an optional "queryseparator" key in Search.Paths and Download.Before from what I can see.

**Comment by cadatoiva** [comment]
So, I'm not sure to what he was referring, but @kaso17 mentioned in https://github.com/Jackett/Jackett/issues/3189#issuecomment-422064740 that the download.before section can generate a thank link using details found on the results page as is, from 2 years ago. Since this is the only missing puzzle piece to keep this one YAML instead of C#, I wonder what he meant?

**Comment by garfield69** [comment]
Yeah, dunno what he meant by that statement. 

I have browsed all the yaml that are currently required to do a thankyou before downloading.
And they all build the necessary parameters for the thankyou link out of the parameters that came from the search block download selector, (whose parameters are provided as variables via the .DownloadUri.Query.$varname),  or with other default  .DownloadUri.$var,s see https://github.com/Jackett/Jackett/wiki/Definition-format#variables-available-in-the-download-block, or with hard coded strings (via the inputs section), or via .Config.$varnames.

I have not had the time yet to experiment with using .Result.$varnames or adding my own parms to the search block download selector to see if the get passed on to the download block without preventing the url from fetching the page that has the thankyou button/href we need to generate.

**Comment by garfield69** [comment]
I have completed my research, and there is not current way I can produce the correct thankyou url by using Cardigann. The uploader member number needs to be included in the thankyou url and is not available to the download block.
This indexer will need to be coded in C#

**Comment by cadatoiva** [comment]
I'm not sure how we would go about implementing this in C# either. At least, I haven't come across a C# tracker that implements the download block as part of the processing.

**Comment by ilike2burnthing** [comment]
dead site
@VMax4 has the domain changed?

**Comment by VMax4** [comment]
Yes, i think they have moved here https://odsplanet.com/ it's required a new registration

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
Il mercoledì 16 giugno 2021 09:43, ilike2burnthing ***@***.***> ha scritto:

**Comment by garfield69** [comment]
with the switch to the new domain they are now using WordPress 5.8.1 as the engine, and all the comments prior to this are now irrelevant.

Despite the wordpress help page implying that the details pages of torrents would have both magnet and Easybytez  links, 
the first 5 torrents I checked using a keywordless search `https://odsplanet.com/?s=` only have the easybytez file storage service.

Jackett can only support .torrent or magnet downloads. The use of 3rd party services for direct file downloads is not supported (they are not compatible with torznab apps).

 I will close this ticket as wontfix. I will re-open if someone can point me to a magnet or .torrent page that I may have missed.
