### ISSUE TITLE
IPTorrents is returning more results than specified to Sonarr

### ISSUE THREAD

**Issue by SunsparcSolaris** [Jackett/Jackett#8102]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Linux/UnRAID

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] Unsure

**.Net Version**: N/A

**Jackett Version**: 0.14.476.0

**Last Working Jackett Version**: Unsure, updated docker today to latest.

**Are you using a proxy or VPN?** [yes/no] No

### Description

My setup was working fine up until a day or so ago. I have Jackett setup with site IPTorrents, with Sonarr utilizting Jackett for indexing.

When I do an interactive search in Sonarr for a single episode, Jackett returns up to 100 results instead of matching the single episode. In the below example screenshot and log, an interactive search was run for "Deadliest Catch Season 15 Episode 21". However, a lot of older episodes and even a Season 16 episode was included in the results. This is happening for all shows contained in Sonarr, not just this particular one.

When checking Sonarr's trace log, it shows that it is requesting the specific season and episode number "S15E21" in the GET URL, but Jackett is returning those results anyway.

Some other searching I have done has suggested there was a previous bug in an old version that allowed Jackett to search by IMDB ID but would not properly return results. It was indicated that the issue was fixed, but this seems to be the exact same issue.

### Logged Error Messages

No error messages that I can see.

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

https://i.imgur.com/jSnVsiQ.png

[log.txt](https://github.com/Jackett/Jackett/files/4453779/log.txt)

**Comment by garfield69** [comment]
In the last 5 days the IPTorrents C# indexer has gone through some extensive revision #8066 #8034 #8011 and may need some further adjustments.

@ngosang, the Sonarr search for this test case is:
`t=tvsearch&cat=100099,100005,100022,100073,100065,100023&imdbid=tt0446809&season=15&ep=21`
and the URL the IPTorrent indexer sends to the IPTorrents Web Site is
`https://iptorrents.com/t?q=tt0446809&99=&5=&22=&73=&65=&23=`
which I have to say, is not the usual category list that I am used to seeing sent to other indexers, which normally look more like `&c99=1&c5=1&c22=1&c73=1&c65=1&c23=1`

but that aside, the real cause of the problem here, is that Sonarr is sending imdbid tt0446809, which is the id for the **top level** series and not for the particular **episode** s15e21.

IF Sonarr cannot send the episode imdbid, then the indexer may need to test for the presence of the **season** and **ep** query and decide to override the **q** when it contains an imdbid format.

**Comment by garfield69** [comment]
So looking at how Sonarr v3 implemented the imdbid, https://github.com/Sonarr/Sonarr/commit/24fba7a36dc0ff5300a02522f3d0b61bb35aca7f this is the series imdbid not the episode imdbid.

**Comment by SunsparcSolaris** [comment]
@garfield69 The interesting thing is that the automation is working fine. Episodes are downloading fine on their own when Sonarr does its thing, it is pulling the correct ones. It's only the interactive search that is giving problems.

**Comment by ngosang** [comment]
This issue is affecting more trackers. See #8107
The PR #8108 will close this issue.

> is not the usual category list that I am used to seeing sent to other indexers,

Categories in IPTorrents are weird, but they are ok.

**Comment by kevindd992002** [comment]
I get this same exact issue with TorrentDay. And for me, it's not working with automation together with interactive search in Sonarr v3.
