### ISSUE TITLE
[Awesome-HD] Parse error: Invalid URI: The format of the URI could not be determined. (Config)

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#8113]
### Environment

**OS**: Windows 10 Pro 64-bit

**.Net Runtime**: N/A

**.Net Version**: N/A

**Jackett Version**: 0.14.485.0

**Last Working Jackett Version**: 0.14.476

**Are you using a proxy or VPN?** No

### Description
I am unable to configure AHD in Jackett. It was working fine about a day ago.

### Logged Error Messages

`An error occurred while updating this indexer
Parse error: Invalid URI: The format of the URI could not be determined.`

### Screenshots
Not needed

**Comment by RoloSoze** [comment]
@garfield69 Not related to this error in specific, but the word 'occurred' is misspelled as `occured` in all error messages that contain the word :)

**Comment by Motophan** [comment]
I am having his issue also

**Comment by garfield69** [comment]
>but the word `occurred` is misspelled as `occured` in all error messages

that is strange, I thought I had already done this back in 1st March 175249d6f0ab861547604519d9825efa3ce8fc3d
but a closer inspection shows I somehow only changed 2 out of the 6 occurrences :-D

**Comment by garfield69** [comment]
looks like awsome-hd have let the banner link slip in a couple of their rows
several have 
`<smallcover>w154/jtrhTYB7xSrJxR1vusu99nvnZ1g.jpg</smallcover>`
instead of
`<smallcover>https://image.tmdb.org/t/p/w154/q1epO0eO8DWu8Vo8tPfvVlzW48T.jpg</smallcover>`

**Comment by RoloSoze** [comment]
Issue now resolved!

**Comment by garfield69** [comment]
@RoloSoze  if it is resolves then it was not because of any changes made on the Jackett side.

So if you are not seeing any errors right now, that simply means that the latest torrents page the indexer fetched does not contain any titles that used the shortened small-cover link in the first 100 torrents fetched.

So to be completely sure the problem is resolved, use the Jackett dashboard to search awesome-hd indexer and search for `The Gentlemen` or `tt8367814` and see if you get any errors.
if you do not get any errors then this means that some one has corrected the torrent details on the awesome-hd web site. Great.
but if you still get errors then this meas the indexer will need amending to cope with small-cover short links.

**Comment by RoloSoze** [comment]
> So to be completely sure the problem is resolved, use the Jackett dashboard to search awesome-hd indexer and search for `The Gentlemen` or `tt8367814` and see if you get any errors.

No errors. The search works well with both title & IMDb ID.

**Comment by garfield69** [comment]
good. then someone must have adjusted the torrent details on the web site and this problem was an aberration with awesome-hd data and not a fault with the jackett indexer processing code.
