### ISSUE TITLE
Can automatic re-search be disable when Jackett is re-opened?

### ISSUE THREAD

**Issue by wellloaded** [Jackett/Jackett#8119]
If I need to close the browser to e.g. update it, it seems like reopening the old tabs make Jackett run a search on the very last search it was performed.

Personally speaking this is unwanted, when I use Jackett I do everything I need, quickly, and by the time I leave the tab I have really no reason to go back unless I need to search for something else.

With the current behaviour say I have just reopened the browser and restored the old tabs, I will need to wait for the old search to finish before being able to run my new search.

It would make sense to me to allow users to decide what's the behaviour on re-oening

my 2 cents.

**Comment by garfield69** [comment]
I believe that this is nothing to do with jackett, but with the options you have set in your browser on what it does with tabs that are reopened.
Look to your browser setting for solution to prevent this.

**Comment by cadatoiva** [comment]
Jackett uses GET instead of POST requests when using the interface, which means that the URL changes for each page, search, etc that you do. As example, if you put in `<yourJacket>/UI/Dashboard#search` into the URL bar, the page that comes up will already have the manual search open and read for a search. If the URL is `<yourJackett>/UI/Dashboard#search=<search+terms>&tracker=<trackers,selected>&category=<categories,selected>` then it will start the whole thing off with that particular search.

This means that when you close your browser and it restores all the tabs when you reopen it, it will load whatever URL for Jackett you last had open. If that happens to be a URL that had some search results open (like above) it will re-run that search because that's what the browser told Jackett to do. On the other hand, closing the search results popup will change the URL (specifically to `<yourJackett>/UI/Dashboard#`) which will not run a search when opened. So before closing the browser, you have to make sure to click the `x` on the search results window, or click anywhere in the greyed out part around the search results window to clear the address bar of your last search request. Also make sure any bookmarks, frequently visited links entries, or any use of "undo closed tab" that you use to navigate to your Jackett UI are similarly not pointing to a link that's trying to search for something.

There is very little we can do to change this behavior on our end without completely changing jackett from the ground up, and even then it removes functionality that other people use. As example, I have set up a custom search engine in my browser so I can search Jackett directly from the URL bar without opening a tab or bookmark first.
