### ISSUE TITLE
[btdb] .json file size keeps increasing - Cloudflare cookie headers

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#8126]
v0.14.501.0 Docker, but has been happening for a while, possibly since I added it, not sure

Tried deleting and re-adding a few times, but it gets back up to this size after a day or two (currently 1.27MB, has been bigger), adding more and more Cloudflare cookie headers. Most others are 1-2KB, a few in the low double digits.

[btdb.txt](https://github.com/Jackett/Jackett/files/4463891/btdb.txt) (extension changed to allow uploading to GH)

Does this get capped at a certain point? Current file size obviously isn't an issue, just concerned if it goes unchecked.

**Comment by ngosang** [comment]
This is important, may affect all trackers.

There are different types of cookies but all of them have an expiration date. We are saving only the cookies, without the expiration date so we can't distinguish the old cookies.

The maximum size for a cookie depends on the browser, the webserver and more things and there are no standard value, but most browsers support:
20 cookies per domain * 4096 bytes per cookie = 80KB
In this issue we are talking about MB, not KB.

**I think it's reasonable to remove the cookie (with all values) if size > 80KB.** This won't be a problem because most trackers have re-login if the cookie is invalid. In the trackers with "cookie login method" I think the cookie won't grow because is set by the user. Usually the cookies are only append after each relogin.

@cadatoiva I don't know what will be the best place to remove the cookie. For most users removing big cookies when Jackett starts will be enough and easy to do for us. But I'm worried about users with manual update... You looked at the httpclient code, maybe you now a better place.

**Comment by garfield69** [comment]
are we saving the whole cookie as given by the server, or are we actually saving the key pairs into the json cookie value....if it the latter why are we not replacing the same keys rather than appending?

**Comment by ngosang** [comment]
The server doesn't send all the required cookies in every request. A simple use case:
1. We enter aaa.com, the site has cloudflare are we are redirected
2. We solve cloudflare challenge and cloudflare set his cookie (sending this header => https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie)
3. We are redirected to the site aaa.com and we do the login, the site set his cookie.
We have to append the cookies to send all of them in each request. That is how browsers works adn thats why we have so many privacy issues.

**Comment by garfield69** [comment]
sure, but my point is that the json file contains the following
```json
  {
    "id": "cookieheader",
    "type": "hiddendata",
    "name": "CookieHeader",
    "value": "__cfduid=d**************0;
PHPSESSID=d************6; flash=; 
cf_clearance=e4*********64-1575957134-0-150;
__cf_bm=42*********32-1585772507-1800-Ae********rN=;
__cf_bm=8c*********c7-1585772507-1800-AX********tty/G/9zz******k=;
__cf_bm=e1*********5b-1585772507-1800-Ab********qF//ic*******8=;
__cf_bm=e2*********b3-1585772507-1800-Af*********PB/5H***********8=; 
[ lots more __cf_bm keys]
```
why are there multiple `__cf_bm` keys and how come we are not able to save the last key in that cookie json?
The browser only ever shows one of  that particular key when it is used to display the cookies for the site.

**Comment by ngosang** [comment]
I didn't notice, you are right. We should overwrite the cookie `__cf_bm` whit the last value.
This is happening in most trackers:
![image](https://user-images.githubusercontent.com/10577978/79033944-ab816300-7bb2-11ea-8aef-80ffaa211966.png)

**Comment by garfield69** [comment]
Jackett 0.15.36
