### ISSUE TITLE
[ExtraTorrent-ag] is back, and [ExtraTorrent-cd] uses TPB results

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#8186]
I have either only just noticed, or it's only just happened, but .si shows the exact same results as TPB

![ET si](https://user-images.githubusercontent.com/59480337/79192304-606c8780-7e20-11ea-8c0f-e610b9e637eb.png)
![tpb](https://user-images.githubusercontent.com/59480337/79192305-61051e00-7e20-11ea-860f-2797dea347f9.png)

That then made me realise that the unblockit.one proxy isn't for .si but .ag, which we don't support anymore - https://github.com/Jackett/Jackett/issues/6742

.ag is back up and running, so do we bring it back (and switch that proxy over)? And do we give .si a month to stop being a reskinned TPB?

**Comment by garfield69** [comment]
It is likely that ET.si has always used TPB results for its own click ads to earn revenue, its just that no one has noticed until now. Well spotted.

Still, its very popular, and I am inclined to leave it, and treat it as just another unofficial proxy for TPB albeit it with a different look. As long as it does not start delivering malware, and the search engine works...

And if ET.ag is working again (it was dropped due to their search engine being broken) then we can add that back to Jackett.

**Comment by ilike2burnthing** [comment]
Yea, sounds good to me.

I'll leave restoring .ag and transferring the proxy to yourself or someone else. I'll watch and learn 😉

**Comment by ilike2burnthing** [comment]
Ah damn, I'm 3 years too late 😋 
https://torrentfreak.com/no-extratorrent-has-not-been-resurected-170524/

**Comment by garfield69** [comment]
Jackett 0.16.18
