### ISSUE TITLE
[Request]Magnet links for manual search results

### ISSUE THREAD

**Issue by onlytanmoy** [Jackett/Jackett#8194]
Hi, please see below screenshot from Jackett -> Manual Search
Can you add copy magnet links for all the results and not just download (of course for the sites that support them)? for example 1337x allows you to copy magnet links and also download them, but here it only shows download option.
![Screenshot_3](https://user-images.githubusercontent.com/48493659/79239851-f3c9ab00-7e68-11ea-858e-ff5a04c41d78.png)

**Comment by garfield69** [comment]
this is not possible. 
the reason is that some web sites do not have the magnet link on their primary results page, but have it only on the torrent details page.
When Jackett pulls the search results from the web site, any site that has the magnet in the results will get the magnet icon shown on the Jackett dashboard, because Jackett obviously knows that type of link that is, magnet or .torrent.
But for sites that only provide download link on the torrent details page, Jackett does not know what type they are, because it is not going to fetch that page until you click on the download button.
It is only then that you find out of the site has a magnet, or .torrent, or even it the site requires you to click  a thankyou button before you get the download link presented.

**Comment by onlytanmoy** [comment]
@garfield69 okay got it... thanks for the clarification.
