### ISSUE TITLE
[TopNow] Found no results - HTML has changed again

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#8199]
~Will post a WIP soon~

Up. Comments/recommendations appreciated

**Comment by garfield69** [comment]
So basically, **topnow** displays search results in two card formats.
The new cards have the _.torrent link_ in the row, and _no details_ page link.
The old cards have _no .torrent link_ in the row, but _have a details page_ link with the .torrent link available in that page.

There is no way for Cardigann to currently handle this, because when an indexer has a **download block**, Cardigann will always pass control to it after the row download selector provides a href, and the download block will always assume this href to be a details page link that it needs to be fetched so that it can go look for a torrent selector.

However, since the new cards have the .torrent link in the row, then after the row download selector has provided the href to the .torrent link the download block will fetch the content of the .torrent file, which is not a html page, and thus will return a 404 not found.

The download block does not currently have any logic to know its dealing with a direct link to the .torrent and not a details page.

So long term, the indexer will need to be converted to C# if we want access to old and new .torrents.

Short term, we can code the yaml indexer to drop off the old cards, and set it up to process the new cards only. At least this way topnow can be of some use until the C# indexer becomes available.

**Comment by garfield69** [comment]
Jackett 0.16.23

**Comment by garfield69** [comment]
TopNow have changed once again.
now the TV series are no longer individually presented in the result page, but any search for a series episode returns a single poster for the series, and cliking that returns a separate page with the episodes posters.

I am going to remove the yml indexer as it no longer provides tv results.

**Comment by ilike2burnthing** [comment]
Site is dead. Apparently it was run out of Ukraine.
