### ISSUE TITLE
Yggcookie - Download issue

### ISSUE THREAD

**Issue by grostim** [Jackett/Jackett#8209]
### Environment

**OS**: 
LSIO Docker container
linuxserver/jackett:latest

**Jackett Version**:
Jackett Version 0.16.18.0

**Are you using a proxy or VPN?** 
no

### Description

If i search for a file: Evirthing is ok.
When i click on one of the result to download the torrent, the download fail (error 404)
https://jackett.mydomain.com/dl/yggcookie/?jackett_apikey=XXXXXX&path=Q2ZESjhPZFFpNVFNTk9oR2dqZm9oMmphbUFYMGhtS0tkV2d3bkZJcVNJbWI0S1Z1eFNCaVdPRjJjUTBQd19DZUhHX3QtYnprV3pGMVdVU2xJQmxfbEpoWVQ0UGZoaGtyX3BvdkUtaUhybVRTcjZkX1R0VkNSeUlGa3g1d0Ffc2dEcWJXNXBlcFliNl9kakQzX1BVNmI0eFh5dmxsWmg3d21IM2xjOGJEdUFlZHB4RGlmWnRLNDlNRHpJQjFTNFBCLUVmaFRR&file=file.mp4

### Logged Error Messages

ERROR 404

**Comment by garfield69** [comment]
Remember that the YGGCookie indexer is using a session id that depends on several things:
- that the cookie has no been expired by the YGGTorrent web site (Daily as far as I can tell with this site)
- If your browser gets updated to a new release, the user-agent string will change so remember whenever you grab the cookie also grab the user-agent at the same time

I have tested YGGCookie and can confirm it works for me

So it is very likely your issue is that your cookie has expired.

Check your log, scroll down to the red error message and if you see `Error Vous devez vous connecter pour télécharger un torrent` then that means the YGGTorrent Web site thinks you are not logged in, so you need to do so and save the cookie/user-agent to YGGCookie to succeed downloading.

**Comment by grostim** [comment]
Indeed, Something was wrong with the user agent.
Thanks for your help!
