### ISSUE TITLE
Unable to use Jackett with Sickchill

### ISSUE THREAD

**Issue by Tiwas** [Jackett/Jackett#8217]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Windows 10

**.Net Runtime**: .Net-Framework

**.Net Version**: Microsoft .NET Framework 4 Client Profile
KB2468871
KB2468871v2
KB2478063
KB2533523
KB2544514
KB2600211
KB2600217
Microsoft .NET Framework 4 Extended
KB2468871
KB2468871v2
KB2478063
KB2533523
KB2544514
KB2600211
KB2600217

**Jackett Version**: 0.16.18.0

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** no

### Description

This is my first attempt at setting up Jackett. I tried searching, but couldn't find anything similar.

I've gone through the setup and have added some (ok, a buttload) of indexers. I'm thinking of using this as a supplement to the regular indexers in sickchill and sonarr in order to get hits from search engines not directly compatible with sonarr/sickchill. The idea behind jackett is awesome - and I want to love it ;)

Now, if I try to add them in sickchill I get the following errors. I'll use the ones from 1337x, but they are the same for each one I've tried (a few, but not all). I've pasted them in the "RSS URL" field under "Configure Custom Torrent Providers".

- "Copy potato feed" => "No items found in the RSS feed http://1.2.3.4:9117/api/v2.0/indexers/ettv/results/potato"
- "Copy Torznab Feed" => "No items found in the RSS feed http://1.2.3.4:9117/api/v2.0/indexers/1337x/results/torznab"
- "Copy RSS Feed" => "Error when trying to load RSS: write() argument 1 must be string or buffer, not None"

If I open them in a browser, I get the following:
- "Copy potato feed" => 
![image](https://user-images.githubusercontent.com/17053402/79423904-b297df00-7fbf-11ea-9a30-33285ec01501.png)

- "Copy Torznab Feed" => 
![image](https://user-images.githubusercontent.com/17053402/79423889-ac096780-7fbf-11ea-948b-13b5fed97110.png)

- "Copy RSS Feed" => 
![image](https://user-images.githubusercontent.com/17053402/79423820-8b411200-7fbf-11ea-8f1b-6fdc5294d4d1.png)

I've seen a couple of guides mentioning that I should add the providers as nzb providers, but then I won't be able to send them directly to my external bt client, which would break my setup.

Anyone able to help out?

Cheers!

**Comment by ilike2burnthing** [comment]
I got that same error:
https://github.com/Jackett/Jackett/issues/8064#issuecomment-610020142

Looking into it further, it does seem that you have to set it up via newznab, because that's how SickChill/Rage decided to organise things... 🙄 and then you set up NZB Search to 'send to black hole', and configure your torrent client to monitor that folder for new .torrent files:
https://community.seedboxes.cc/articles/how-to-use-jackett-with-sickchill-sickrage (just skip the first bit)

**Comment by Tiwas** [comment]
@ilike2burnthing Thanks. This is all well and good, however that brings up the issue of loading the magnet into my remote deluge. I tried using the autoadd plugin, but that doesn't seem to monitor local folders.

**Comment by ilike2burnthing** [comment]
Not sure if this is necessarily a solution, but have a look at - https://dev.deluge-torrent.org/wiki/UserGuide/ThinClient

Otherwise, you need to mount the remote directory so Deluge can access that folder, or so you can sync it to a folder local to Deluge with something like rsync. If that doesn't work then have a look at SSHFS.

You might even be able to skip that and just add the IP and directory location to autoadd, e.g. `\\192.168.0.XXX\Torrents`.

I'm going to close this thread as we're well outside of the bounds of Jackett. Hopefully you get a response to [your comment on the Deluge forums](https://forum.deluge-torrent.org/viewtopic.php?f=9&t=26775&start=70#p231545). If not, I'd try making a separate post.

Best of luck, and if you get it working, let us know how. Might help someone else 🙂
