### ISSUE TITLE
thepiratebay.org is back online but jackett can't change it back : it switchs to thepiratebay.vip

### ISSUE THREAD

**Issue by ToXinE** [Jackett/Jackett#8249]
### Environment

**OS**: Debian 9

**.Net Runtime**: [Mono]

**.Net Version**: latest

**Jackett Version**: 0.16.54.0

**Last Working Jackett Version**: 0.16.54.0

**Are you using a proxy or VPN?** [yes]

### Description

as you can see here (https://torrentfreak.com/the-pirate-bays-main-domain-returns-after-month-of-downtime-200411/ ) thepiratebay.org is officially back but the indexer can't switch back to the official url (ie thepiratebay.org) because if you try to do so, jackett change it back to "thepiratebay.vip" which is not the official one.

**Comment by RoloSoze** [comment]
@garfield69 Aside from the Site Link change, I see that Jackett only returns 30 results from TPB whereas the website itself returns way more than that. Is this something that can be fixed?

**Comment by cadatoiva** [comment]
The original issue is because thepiratebay.org is listed in [`LegacyLinks`](https://github.com/Jackett/Jackett/blob/b29a4770c2f3efc0bb025c94961f24f6292f46eb/src/Jackett.Common/Definitions/thepiratebay.yml#L32) which means it gets updated to one of the items in the Links section any time it checks.

@RoloSoze, Jackett only searches the first page on this tracker, which is why you get the max of 30 results.

**Comment by RoloSoze** [comment]
> @RoloSoze, Jackett only searches the first page on this tracker, which is why you get the max of 30 results.

I realize Jackett only searches the first page. TBP displays around 100 or so results in the first page:

https://thepiratebay.org/search.php?q=avengers+endgame&all=on&search=Pirate+Search&page=0&orderby=

**Comment by cadatoiva** [comment]
@RoloSoze since thepiratebay.org is in LegacyLinks, Jakett does not use that site. The TPB sites we do use still display the old style 30 results list: https://thepiratebay.vip/search/Avengers%20Endgame

This discrepency should self-resolve once we get the tracker working with the newly re-opened site and it's moved out of LegacyLinks

**Comment by garfield69** [comment]
We cannot support the new TPB engine via the Cardigann yaml indexer, as the results the new TPB  presents are generated dynamically via JavaScript.

As you may know, when Cardigann makes a query it received HTML back. But unlike your browser which can run JavaScript in a VM and refresh the display, Cardigann can only work from the HTML it was given in response to a query. If the results are not in the HTML at that time, then there is no data to process.
If  we want to support TPB in its new incarnation, the indexer will need to be rewritten in C#.

Fortunately, some proxies are using the TPB's TOR onion site, and fetch their data from that site and continue to present the full HTML that the indexer can handle.
So any domains that use the new TPB engine have been placed in the legacylinks section so that the indexer can continue to work.

**Comment by garfield69** [comment]
IMO, while the existing indexer links continue to fetch current TPB results, I do see why we need to do anything.
In the event they all stop working, then we can instigate a rewrite of the yaml TPB indexer into C#. we can reopen this ticket or start a new one when that occurs.

**Comment by ToXinE** [comment]
now the indexer links to https://thepiratebay0.org/ by default and i can't change it back to https://thepiratebay.org/ (which is working...)

**Comment by garfield69** [comment]
you cannot switch the indexer back to https://thepiratebay.org/ because although the **.org** has been working since it came back online a few months ago, it changed at that time the engine which prevents the Jackett indexer from pulling results.
But TPB on the **TOR** is still using the old engine, and all the proxies listed in the indexer **sitelinks** pull data from the TPB TOR and thus the Jackett indexer can still search and fetch results from them.
