### ISSUE TITLE
Magnet link in proxy link format

### ISSUE THREAD

**Issue by prise6** [Jackett/Jackett#8252]
### Environment

**OS**: docker: linuxserver/jackett:latest

**Jackett Version**: Jackett Version 0.16.34.0

**Last Working Jackett Version**: Jackett Version 0.16.34.0

**Are you using a proxy or VPN?** no 

### Description

I would like to understand why magnet links are encrypted in proxy link format.
Example with indexer *torrentv* with torznab results feed, **link** property is in proxy format whereas it's a magnet link. 

> localhost:9117/dl/torrentv/?jackett_apikey=XXXXX&amp;path=Q2ZESjhLRTZGRkwzLWhWTHR3Y3V2XzV2dURhMVcyRndHa1hDVnJOQmZ6R09DeFhCd0czS1BncnFQc2Fsc2p1WHpHdUJlRzlmOWdhcWM4enZXbmF2T0xSMExtbmpRUm1zQUN4ZDRENW1zMms1dm1IYzVlQ2RWNk9ELW5zQkRza29CQS1xVTItd3pHR2x2VExkdGVSeEhVZUhiRkV5OHQyYksxSzBBZlBhNG1wa19hR0w3QzREMk9DbGxwVkRlbEZqRzhVQndZSTREcjJjN29iSEZxaDdfVFF0eGUw&amp;file=XXXXX

Maybe it's complety normal, but i don't see where in the code it's done.

From **ResultsController.cs**, there is a loop on realease to transform thanks to `serverService.ConvertToProxyLink()` method.
In this method, i read:

```
if (link == null || (link.IsAbsoluteUri && link.Scheme == "magnet" && action != "bh")) // no need to convert a magnet link to a proxy link unless it's a blackhole link
                return link;
```

And in my case, i use 'dl' action and uri is absolute, right ?

Can someone explain to me how it works ? 

PS: how can y decrypt path base64 encoded string if i want to check link is magnet or not?

Thanks

**Comment by cadatoiva** [comment]
The proxy link method is largely used for trackers that put their download links behind a secondary link, like needing to click the result to get to a details page to collect the download link. Rather than Jackett going to every single details page and collecting those links, we encode a proxy link with the details area. This way we don't over-tax their servers in a DDoS style. When you decide to download a link, we then user the proxy link to pull that details page, parse out the real download link and *then* we redirect to this true download.

If the tracker supplies a magnet link on the details page then you'll be redirected to the magnet, but there's no way to know that from the details link alone.

**Comment by prise6** [comment]
Oh, i think i undersant.
I didn't realize that the real dl link is not the one encoded. It's only on the dl action that you scrape the page to select in the web result the correct link.
Ok, so i need to catch the redirection and parse the direction link to see if it's magnet or not.

Ok thanks !

**Comment by cadatoiva** [comment]
Yup, we send a 302 redirect after scraping the details page, so that's where you'll need to catch the true link in your scripts. But this is only true for links that point to your jacket install beginning with `<jackett-ip>:<jackett-port` If we don't need to scrape the details page to get the link, we'll display the link directly without the proxy. Good luck!
