### ISSUE TITLE
[eztv] Exception (eztv): certificate validation failed: [Subject]  E=root@localhost.localdomain, CN=localhost.localdomain, OU=IT, O=MyCompany, L=Seattle, S=WA, C=US[Issuer]  E=root@localhost.localdomain, CN=localhost.localdomain, OU=IT, O=MyCompany, L=Seattle, S=WA, C=US[Serial Number]  0FB76903[Not Before]  5/11/2018 1:56:51 PM[Not After]  5/8/2028 1:56:51 The SSL connection could not be established, see inner exception. (Test)

### ISSUE THREAD

**Issue by maskofsanity666** [Jackett/Jackett#8276]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
these are the official thumbprints for the EZTV domain and alternate sitelinks that we have loaded in the indexer
```
https://eztv.io/ 02aab7bdf4a888f307e326766c03fda271fe192b
https://eztv.root.yt/ 2dee53628fdc093e9430b21c4c9a6032449abc46
https://eztv.unblockninja.com/ 7db759065c556a1610e5758df6a4f10456763aa2
https://eztv.black-mirror.xyz/ b265d8e5e2e8a7db90b0ab16459f83a31683cf06
https://eztv.unblocked.casa/ d21dfe781b2f425f602ee33066552fdb9f205393
https://eztv.proxyportal.fun/ 2d0b42f97a2a9fc8a7214b00cbb6f2ed58d3fd85
https://eztv.uk-unblock.xyz/ a8a1b6e53545c1cf7a1d9d2dc20de3e9f56617e6
https://eztv.ind-unblock.xyz/ fba1c36b78e9100548a23c306bbb8a60d2adb163
```
since yours is B26A658C02735154AD05D773E5CC3E23082E918E this implies one of two things:
- you are not using one of the provided sitelinks from the indexer (in which case it is unsupported and there is nothing we can do about it. Try using one of the supported sitelinks).
 - you are being blocked by an ISP and routed down a black hole whose certificate is invalid (in which case:
   - Use a Browser on the same machine that is running Jackett, access the Site using the same address as the Indexer's config SiteLink and confirm that this is the case. You may see a notice by the ISP or by some other authority explaining the block
   - A possible solution you can try is to stop using the DNS provided by your ISP and switch to one of the public ones from Google (8.8.8.8 and 8.8.4.4) or Cloudflare (1.1.1.1 and 1.0.0.1).
   - An alternate approach is to use a VPN or proxy which will use a different server/ISP with a different IP address to your own which may help bypass this issue).

Since this has little to do with Jackett itself, there is no other help we can provide for you.
