### ISSUE TITLE
Request for keepfrds

### ISSUE THREAD

**Issue by gaofashao** [Jackett/Jackett#8299]
site: https://pt.keepfrds.com/
Keep Friends PT (FRDS-PT) is a CHINESE Private Torrent Tracker for HD MOVIES

**Comment by RoloSoze** [comment]
I believe access to most Chinese trackers right now is restricted. You can only view the website if you're already logged in, and this will likely continue until early May or so https://github.com/Jackett/Jackett/issues/7950#issuecomment-615231734

Once this is over, if a developer is willing to add the indexer,  you may need to provide an invite since this is a private tracker.

**Comment by garfield69** [comment]
Once the World Intellectual Property Day login-lock-down is over (early April to early May is a measure taken by some Chinese trackers to protect themselves),
then,
If you send an invite to garfieldsixtynine -at- gmail.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by RoloSoze** [comment]
@garfield69 It uses NexusPHP like most other Chinese trackers, so I guess the indexer can be done in YAML. If you do get the invite, be aware of the following rules. I found them on one of their official recruitment threads. Translated from Mandarin: 

1. The uploader must limit the upload speed to less than 100 Mbps (12.5 MB/s). Overspeeding may result in banning your account. VIP and above levels are not restricted

2. Parked accounts will be deleted if the user does not log in for 90 consecutive days

3. Non-parked accounts will be deleted if the user does not log in for 30 consecutive days

4. Accounts with no traffic (i.e. upload/download data is 0) will be deleted if the user does not log in for 7 consecutive days

**Comment by gaofashao** [comment]
@RoloSoze I'm sorry I currently do not have permission to send invitations. I will try to find people who can send you a invitation. Sorry, I thought I was able to send an invitation but I just checked the rules and found that I need to register for 60 weeks.

**Comment by RoloSoze** [comment]
@gaofashao It might be better to get the invite from the tracker's admin/sysop if they're interested in adding support for Best Friends in Jackett. Most Chinese trackers are supported already.

**Comment by gaofashao** [comment]
@RoloSoze OK, I will try to contact them.

**Comment by RoloSoze** [comment]
@gaofashao Any updates?

**Comment by gaofashao** [comment]
@RoloSoze I'm sorry I couldn't find a invitation for you and wasting your time, maybe I should learn to modify the yml file to adapt this site. I am sorry.

**Comment by RoloSoze** [comment]
@gaofashao Don't worry about it. This ticket will remain open if you ever get a staff invite. Good luck!

**Comment by garfield69** [comment]
Jackett 0.16.496

**Comment by RoloSoze** [comment]
@garfield69 For this tracker, torrent names are always in Chinese whereas the proper English release name is actually in the secondary line that's called "Small Description", which is basically the opposite of all other Chinese trackers. 

Jackett returns the Chinese torrent name, which is useless for non-Chinese speakers. Can you set it so that it returns the proper English release name?

**Comment by garfield69** [comment]
I will add a config option to allow users to select the English title when its available.

**Comment by garfield69** [comment]
Jackett 0.16.511
the option default to show Chinese titles.
