### ISSUE TITLE
Jackett v0.16.71 loop when installing

### ISSUE THREAD

**Issue by MaurizioRicci** [Jackett/Jackett#8300]
### Environment

**OS**: Windows 10

**Last Working Jackett Version**: v0.16.70

**Are you using a proxy or VPN?** [yes/no] no

### Description

I downloaded the Jackett installer for windows, i double click on the exe and the i install it with the default options. Installation is ok but when i click finish after some seconds the installation process restarts from scratch. If i do the installation once again it will restart it another time, it's a loop. Moreover Jackett is not installet even though i did the installation phase 4-5 times.
Jackett v0.16.70 installer works as expected.

Edit: I made a mistake reporting the version of the software: v 0.16.96 gave me the loop on installing. Version 0.16.71 works fine

**Comment by garfield69** [comment]
This is all a bit confusing as there is no 0.16.70 release. 
I published 0.16.59 three  days ago, 0.16.71 two days ago and 0.16.96 twelve hours ago.

So what is the situation with your Jackett at the moment, have you got a version installed and running and if so which version is it? (scroll to the bottom of the Jackett dashboard and report what the version is).

If you have a working version, what happens if you click on the **check for update** button on the dashboard? (do so, wait a minute, refresh the dashboard and see if the version changes, and if not, then open the log and look for a reason).

**Comment by garfield69** [comment]
As a control to your report, I have just tested installing 0.16.71 and 0.16.96 and both installers worked for me on my win10 home image.
So this suggests that there is something amiss with your windows platform someplace that is preventing the installation from completing properly.

**Comment by MaurizioRicci** [comment]
Sorry i made a mistake, i'have updated my original issue. Now that i have installed v.0.16.71 i tried with version 0.16.96 and everything worked as well. I don't know maybe it was that i was just using an old version of Jackett (as far as i remember was something like 0.12.x). So i close this issue because i cannot provide you any useful information about the problem.
