### ISSUE TITLE
[academictorrents] Exception (academictorrents): An attempt was made to access a socket in a way forbidden by its access permissions.: An attempt was made to access a socket in a way forbidden by its access permissions. (Test)

### ISSUE THREAD

**Issue by tomkumaton** [Jackett/Jackett#8335]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
This indexer works for me which suggests your problem is something external to Jackett.
A socket error can be caused by the antivirus or firewall software. Basically, a needed socket connection is being denied. Socket error message implies that a port is blocked and/or unreachable.
have a read of https://github.com/Jackett/Jackett/wiki/Troubleshooting#an-existing-connection-was-forcibly-closed-by-the-remote-host and see if it help you out.
