### ISSUE TITLE
[speedcd] Exception (speedcd): Clearance failed after 30 attempt(s).: Clearance failed after 30 attempt(s). (Test)

### ISSUE THREAD

**Issue by myplexter** [Jackett/Jackett#8337]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: LINUX - DEDISEEDBOX

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.14.485.0

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no] NO

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
The speed.cd indexer is working for me, but that is because I am on the latest version of Jackett, **0.16.105**, which includes a new version of the custom cloudflareSolverRe library which has had an update to handle the new cloudflare challenge.

- So you either need to upgrade your Jackett 0.14.485 to 0.16.105 if you want to use speed.cd 
or
- if for some reason you are unable to upgrade, then wait until speed.cd lift the blacklist and stop using the cloudflare anti-DDoS challenge
or
-maybe you can try using a VPN on your seedbox so you get a new regional server IP address that may not be blacklisted.
