### ISSUE TITLE
[Enhancement] Allow renaming & merging of trackers with config

### ISSUE THREAD

**Issue by cadatoiva** [Jackett/Jackett#8355]
Currently the system depends on the name of the tracker in Jackett to create and find config files per tracker. This means we cannot change tracker names without invalidating every user's config. The linked issue below is one such tracker where the name is incorrect, but we can't fix it. Recently I've seen at least one pair of trackers merge (don't remember issue #), and there's #8349 with a bad name too (and others).

Decoupling the config files from the tracker name into some other variable or some kind of lookup table would be the most straight forward solution. But with other requests like enable/disable trackers, custom aggregates, multiple configs per tracker, dynamic load/unload of trackers, and some of the Core changes in the pipeline, it might be a good idea long-term to switch to a .db design instead? There's good built-in support via LINQ and Entity Framework for database designs. 

> Having seen a few trackers merge or rename in the past, it might be worth implementing a system to allow renames without breaking all the existing users' configs

_Originally posted by @cadatoiva in https://github.com/Jackett/Jackett/issues/8345#issuecomment-619305299_

**Comment by ngosang** [comment]
@garfield69 I have been thinking a bit.

**.yaml**
* Currently the filename is not used, I think the file can be renamed without problem.
* The field `site` is used as `id` and can't be changed. Changing that is like having a new indexer and you lose the configuration.
* We can rename the field `site` to `id` to avoid confusions.

**C#**
* We are using the filename as `id` (in lower case). So, we can't rename the classes.
* I think we should add a new field in the constructor called `id` (next to the name and description). That field will be the equivalent to `site/id` in the yaml and can't be changed.

I can do all changes easy and without breaking compatibility. After this change we will be able to rename all files and changing the indexer names without breaking anything. The id must be unique and we can't change it. We can't remove the id because is used to find the configuration file and it's used in the torznab/rss/potato URLs.

>  But with other requests like enable/disable trackers, custom aggregates, multiple configs per tracker, dynamic load/unload of trackers, and some of the 
 it might be a good idea long-term to switch to a .db design instead? 

At this point I don't see any advantage in having a database. In the future if we implement those features it can be useful but the unique id will be required anyway...

**Comment by ngosang** [comment]
@garfield69 is the proposed solution good enough?

**Comment by garfield69** [comment]
So let me see if I understand this correctly.
You propose bringing yaml and c# inline with each other, by having a id which is what gets used to identify an indexer when the torznab api makes a call, and its also used to name the config file.
And the existing filenames for the yaml source and c# become free entities because somehow they are loaded by Jackett simply by being present in the definitions folder (for yaml) or in the indexer source folder (where they are collected and compiled into the common.dll).
And the name is only used for display on the Jackett dashboard active indexers and add indexers pages.
And we switch site in yaml to id, and add id to the c# and we get consistency across the two indexer sources and bob's your uncle.
LGTM. If I understood correctly that is.

**Comment by ngosang** [comment]
Yes that is. In a second iteration I will think how to rename the ids (it's possible but it needs more c# development)

Btw, I don't know who is bob.

**Comment by ngosang** [comment]
After #8612 it's possible to rename files, names and ids. We have to review all indexers to see what should be renamed (the id, name and file name). In this table are some candidates but can be more.
@garfield69 wait few days until we see if users complain about #8612 (nostalgic)
|  Id |  Name  |
|---|---|
|amigosshare|amigos share club|
|tehconnectionme|anthelion|
|bluebirdhd|bluebird|
|yourexotic|exoticaz|
|kickasstorrent-kathow|kickasstorrent (kat.li)|
|mteamtp|m-team - tp|
|transmithenet|nebulance|
|nnm-club|noname club|
|passtheheadphones|redacted|
|rstorrent|redstartorrent|
|RockBox|rockbox rock/metal tracker|
|metaliplayro|romanian metal torrent|
|newretro|the new retro|
|nostalgic|vhstapes|
|wihd|world-in-hd|

**Comment by garfield69** [comment]
doc at https://github.com/Jackett/Jackett/wiki/Renaming-Indexers

**Comment by ngosang** [comment]
@garfield69 if you want to rename more indexers I can help you

**Comment by cadatoiva** [comment]
Sweet. Good work @ngosang 

I'm going through the 500+ notifications to get caught up on what I missed, so expect a bunch of comments while I wait for my system to finish updating. Then I'll hop back in to getting some code out.

**Comment by ngosang** [comment]
@cadatoiva @garfield69 @RoloSoze @ilike2burnthing If you know any other tracker that should be renamed, speak now. I would like to close this issue. :)

**Comment by RoloSoze** [comment]
I had a look at the C# Indexers:
`BroadcastTheNet > BroadcasTheNet`

This is the only one I know of that has a spelling mistake. The rest of the C# indexers all look fine to me. Minor capitalization inconsistencies do not really matter to me personally. 

YAML definitions are a different story because their names do not have proper capitalization at all, so I will not be looking at those.

**Comment by ngosang** [comment]
> BroadcastTheNet > BroadcasTheNet

Done #8888

> YAML definitions are a different story because their names do not have proper capitalization at all, so I will not be looking at those.

They do inside the YAML. See fields id and name

**Comment by ilike2burnthing** [comment]
Only one that springs to mind is [Cili180](https://www.lrcili1.xyz/). It went by [Liaorenso](https://www.liaorenso13.xyz/) until recently (turns out some of the old domains are working again), and now seems to be Liaorencili.

So `Cili180` to `Liaorencili`? Or `Liaorencili (Cili180)`?

**Comment by cadatoiva** [comment]
From what I saw of the list so far, you've hit all the ones I know about.

**Comment by garfield69** [comment]
Can be closed as far as I am concerned. Future renames can open their own tickets.

**Comment by garfield69** [comment]
Jackett 0.16.640
