### ISSUE TITLE
[thepiratebay] Exception (thepiratebay): The operation was canceled.: The operation was canceled. (Test)

### ISSUE THREAD

**Issue by Bidley** [Jackett/Jackett#8380]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

Docker

**OS**: OpenMediaVault

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.16.137.0

**Last Working Jackett Version**: Unsure

**Are you using a proxy or VPN?** [no]

### Description

Unable to add TPB as an indexer. I'm using the latest proxy, but no other link seems to work. Proxies work via web browser. I get the error "The operation was canceled.: The operation was canceled. (Test)" in Jackett, and neither Sonarr nor Radarr recognise the indexer as working. I have other indexers working fine in Jackett.

### Logged Error Messages

https://pastebin.com/DinTpykU

**Comment by garfield69** [comment]
Is the browser you are using running on the same machine as Jackett?
There are 18 proxies and all of them work for me which suggest this is a specific issue with your IP address being blacklisted by cloudflare.
Turn on **enhanced** logging and repeat the test on one of the sitelinks. You may see the html presented by cloudflare in the enhanced log presented before the cancelled task message. It may provide a reason why the cloudflareSolverRe library is not able to pass the challenge.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by Bidley** [comment]
Thanks for the reply.

No, I'm browsing on different machines - Jackett is running on an OMV NAS.

Here are my enhanced logs - hope I did this correctly https://pastebin.com/VvXhXnGr

**Comment by cybrnook** [comment]
Also seeing the same behavior.

**Comment by garfield69** [comment]
the log you provided shows that you are using pirateproxy.blue
I tested this proxy and it is not compatible with the jackett TPB indexer, I also get the same error as you with it.

only the alternate site links provided in the config have been tested to work with the indexer
so try them out, one at a time until you find one that works.

you may wonder why we are not using https://thepiratebay.org (the official domain).
the reason is that the official https domain switched a couple weeks back from using plain html to using a javascript based engine returning json, and that means the current jackett indexer will not work until it is rewritten in C#
But the alternate TPB domain on the onion TOR still returns plain html and all the proxies listed in the jackett TPB indexer config use the TOR domain to fetch their data.

pirateproxy.blue is not one of them, so even if they did not have the cloudflare anti-ddos getting in the way, it would still not be usable by the current Jackett TPB indexer with this proxy.

**Comment by cybrnook** [comment]
@garfield69 you are right. I didn't even realize there were so many proxy options. Instead, I would just choose the default TPB entry and add it to my list, and it would fail when testing.

However, I set it up on proxy https://thepiratebay1.com/ and that seems to work fine, for now.

**Comment by Bidley** [comment]
@garfield69 thanks for that, that's good info. I haven't been able to get any of the proxies to work, but hopefully a solution will present itself soon.
