### ISSUE TITLE
Jackett not showing Elite Tracker results

### ISSUE THREAD

**Issue by computman007** [Jackett/Jackett#8388]
### Environment
**OS**: Windows
**Jackett Version**: 0.16.137.0
**Last Working Jackett Version**: ??
**Are you using a proxy or VPN?** [yes/no] NO

### Description
Jackett do nos show Elite Tracker result

Doing a search on the tracker itself show results but not in Jacket whatever the category

Removing a andding again the tracker so not solve the issue.

No error messages are shown

### Logged Error Messages
NONE

![2020-04-27 08_58_26-Window](https://user-images.githubusercontent.com/25824896/80342910-4a6db680-8865-11ea-8789-69eba1574524.png)
![2020-04-27 08_58_08-Window](https://user-images.githubusercontent.com/25824896/80342911-4a6db680-8865-11ea-9b49-38aff9b709b0.png)

**Comment by garfield69** [comment]
works for me, which implies this is something affecting your machine or account.
![image](https://user-images.githubusercontent.com/6933240/80343477-0e187580-88ba-11ea-9de2-231a353dab96.png)

please provide an full **Enhanced** log which should include the html returned from the site when the indexer makes a query and any additional debug messages that may help us to figure out what is going on.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by computman007** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/4540922/log.txt)
Attached the log anonymized

**Comment by garfield69** [comment]
fascinating.
your log clearly shows that the web site returned `Aucun résultat` in its response html to your jackett query for `Koh-Lanta`
so its not a question of there being a problem with the indexer, since the indexer works for me doing the same search where the site returns results in its html.
and apparently, if you use the browser directly to access the site, you get results. 

So I started looking at my account settings on the site. I switched languages from French to English, and back, but that made no difference.

However, when I switched theme from `ET` to `default` then I too got the site to return `Aucun résultat` to my indexer query.

so, login to the web site, switch the theme on the https://elite-tracker.net/usercp.php?act=edit_theme_language panel to `ET` and save.

then try your indexer again and see if that works for you.

**Comment by garfield69** [comment]
no wait. that's not it. I got `Aucun résultat` because I used `Koh-Lanto` , duh!

**Comment by garfield69** [comment]
besides, your log shows you are using theme `ET` so its not that.

**Comment by garfield69** [comment]
@ngosang  @cadatoiva   this is a C# indexer, and I've taken a look and I cannot see anything that could explain why this user is not able to have the indexer return results for `Koh-Lanta` when I can.

Clearly, the web site is not responding to his query in the same way, which suggest that some other parameter is being sent to the site, or used by default, that I cannot see in the log.

the debug message in the log prior to the returned html from the site, shows simply
`https://elite-tracker.net/browse.php` as the url, which is unhelpful, but a result of the indexer having to use a POST instead of a GET.

Can we get the indexer to dump the query POST parms to the log when its in Debug mode, so I can see what is really being sent by the indexer to the web site?

**Comment by computman007** [comment]
It seems that the issue may come from the category. If I'm looking for any "animation" the result is empty too
Maybe other category are impacted like TV show like Koh-Lanta

**Comment by ngosang** [comment]
@computman007 I'm getting results too for "Koh-Lanta". Make sure you are using the default theme:
![image](https://user-images.githubusercontent.com/10577978/80515863-e8a36e80-8982-11ea-872a-caddc09e0d34.png)
About the categories you are with, they are not working. There are 2 problems.
1. We are not sending the user selected category. The site only supports 1 cat but something is better than nothing. This can be fixed in the source code with this. `{"category", MapTorznabCapsToTrackers(query).FirstIfSingleOrDefault("0")} // multi cat search not supported`
2. @garfield69 we have the same problem here with Jackett filtering categories. "Animation / 27" is a parent category that return results with children categories, and Jackett removes all of them. The html parsing is ok.

**Comment by computman007** [comment]
So this can be solved ?

**Comment by computman007** [comment]
I have done some tests and it seems that's on my profil. If I do not specify a category I can't see no result. Another user can do search with no category specified.

**Comment by computman007** [comment]
**Find the solution :** 
In the profile settings, you can set default categories. If you select some, the search in the tracker seems to not work properly.
I have deactivated all categories and now everything work correctly

**Comment by garfield69** [comment]
I cant find that in the settings. where is it hiding?

**Comment by computman007** [comment]
> I cant find that in the settings. where is it hiding?

https://elite-tracker.net/usercp.php?act=edit_details

The tracker can send a message to your email address to inform you when someone upload a torrent in one of your default browsing categories.
[]  Receive Email Notification of New Torrents
[]  Click to Select Default Categories

![2020-05-03 10_44_15-Welcome to your control panel _ Elite-Tracker - Vivaldi](https://user-images.githubusercontent.com/25824896/80909774-27db1200-8d2b-11ea-8d35-a9cc7d6a7535.png)

**Comment by garfield69** [comment]
Ah. that's what fooled me. I was expecting to see an already expanded list. ;-D
