### ISSUE TITLE
[bit-titan] Exception (bit-titan): Relogin failed: Parse error (Test)

### ISSUE THREAD

**Issue by Winblackka** [Jackett/Jackett#8394]
An error occurred while testing this indexer
Exception (bit-titan): Relogin failed: Parse error

**Comment by garfield69** [comment]
the indexer works for me, which implies the issue is at your end.

access your jackett dashboard, edit the bit-titan config and answer the challenge.

when you login successfully, a cookie is saved which allows the indexer to access the site.
but the cookie has an expiry date, so when the site determines it want to confirm you are human, it will renew the challenge and you will need to edit the config and complete the new challenge.

if you have done this, and you are still getting the parse error, then provide a full **enhanced** log so we can dig deeper and I will reopen this ticket.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by Winblackka** [comment]
Ah, okay, sry, my fault. The Tracker is working. Thx anyway!
