### ISSUE TITLE
vhstapes: rename nostalgic

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#8501]
Searching vhstapes in "add indexer" can't be found

**Comment by garfield69** [comment]
nostalgic came first.
and traditionally we have not bothered renaming (we just add the new name in brackers in the readme).
if #8355 gets implemented then we could rename without cost
but otherwise the only way to avoid inconveniencing existing users, would be to add a clone of nostalgic as vhstapes

**Comment by ngosang** [comment]
You can't rename the file or change the id, but you can change the name.
For example:
id: yourexotic
name: ExoticaZ

**Comment by garfield69** [comment]
... or we could do that

**Comment by ngosang** [comment]
I will think about
