### ISSUE TITLE
[TV Vault] Add IMDb ID search | Implement searching for TV seasons using Sxx format | Display full filename

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#8508]
- [x] IMDb ID search capability needs to be added, which is already mentioned in #4859. Under 'Show Advanced Options', there is an "IMDB Info Link" search box where you can search with the IMDb ID. There's also a note next to it that says, "If nothing found, also try searching Show Description."

- [ ] Also, the IMDb URL appears on the TV show's homepage but not next to each individual torrent. If it can be displayed in Jackett, that would be ideal. _[Update: Cannot be done without an API - Revisit in the future if an API is created]_

- [x] Searching for a specific TV season using the format `Show Title Sxx` currently returns nothing since season titles in TV Vault are displayed using the format `Show Title - Season xx` or `Show Title - Season x` (can be either one due to naming inconsistencies). It would be great if Jackett users can search using the standard `Sxx` format as is the case with most major trackers. The same should also be possible for individual episodes using the format ` Show Title SxxExx`.

- [ ] Jackett displays the tags of each release e.g. ` Futurama -​ Season 6 (1080p) (2010) (MKV/​H.​264/​DTS/​Blu-​ray/Freeleech!)` but does not show the full filename/release name, which is consistent with TV Vault's website. If possible, Jackett should return the full release name followed by the aforementioned tags in a manner similar to that of PTP's - see #6783 (comment) - Start reading from where it says, "The best implementation example I've seen in Jackett." Also, see my explanation for the same issue for Anthelion in point number 3 - https://github.com/Jackett/Jackett/issues/7923#issue-589794715 _[Update: Cannot be done without an API - Revisit in the future if an API is created]_

**Comment by ngosang** [comment]
@RoloSoze I have been investigating. The main issue is this tracker is using Gazelle tracker, but it has `ajax.php` API disabled, so we are scrapping the HTML instead of using the API. The ideal solution will be to talk with the staff to enable the API.
Eg:
AlphaRatio OK => https://alpharatio.cc/ajax.php?action=browse&order_by=time&order_way=desc&searchstr=harry
TV-Vault KO => https://tv-vault.me/ajax.php?action=browse&order_by=time&order_way=desc&searchstr=harry
If this is not possible:
1. IMDB search is doable.
2. Show IMDB URL in Jackett is not doable because is in the torrent details.
3. Season search is doable.
4. Show Irelease name in Jackett  is not doable because is in the torrent details.

**Comment by ngosang** [comment]
1) and 3) fixed in #8969
Other points can't be fixed by Jackett and the site owner is not willing to do the changes in his side.
Keep this open for future reference.

**Comment by RoloSoze** [comment]
@ngosang Thank you. If the two issues you worked on have been addressed, I prefer to close the issue rather that put it on hold. This is because in the other issues I have on hold (#6783 & #7829), staff have indicated that future internal upgrades might help address the remaining issues, whereas here, this does not seem likely at all as no future plans exist.

**Comment by garfield69** [comment]
Jackett 0.16.722
