### ISSUE TITLE
TVChaosUK remove torznab button

### ISSUE THREAD

**Issue by 2fst4u** [Jackett/Jackett#8547]
I'm not sure if this is possible and it's just an idea, but because TVChaosUK doesn't use proper naming convention there's no point in ever using the torznab functionality for them. I'm forced to use RSS for them in order to grab anything.

I prefer to use the Jackett RSS instead of their own as it keeps all my trackers tidy and in one place.

So since torznab is functionally useless for them, is there a way to have Jackett "grey out" the torznab link button or remove it entirely to prevent people from getting confused about it not working?

**Comment by garfield69** [comment]
No it is not possible.
Jackett was actually built around the Torznab specifications, to provide an API to other Apps via the Torznab API.
The other features, such as the Jackett dashboard manual search, the RSS feed, the couchpotato API, all came later.
The Jackett RSS is actually an internal torznab query (using a keyword-less search) whose results are then translated into an XML presentation.
There is current no way for the Jackett dashboard to disable the torznab button as this interface is always available on all indexers, since without it, none of the other features (excluding couchpotato) would work.
