### ISSUE TITLE
[dmhy] Exception (dmhy): 由于目标计算机积极拒绝，无法连接。: 由于目标计算机积极拒绝，无法连接。 (Test)

### ISSUE THREAD

**Issue by blue2517** [Jackett/Jackett#8551]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
the dmhy indexer works for me so the issue is likely at your end.
google translates the error you reported as
`Unable to connect because the target computer actively refused.`
have a read of https://github.com/Jackett/Jackett/wiki/Troubleshooting#no-connection-could-be-made-because-the-target-machine-actively-refused-it and see if that helps you figure out your issue.
