### ISSUE TITLE
Lidarr Rutracker/Jackett -- Unable to connect to indexer

### ISSUE THREAD

**Issue by Jrswitchblade** [Jackett/Jackett#8553]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:
Ubuntu 20.04 LTS

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]
Mono 6.8.0.105

**.Net Version**:

**Jackett Version**:
Jackett Version 0.16.296.0

**Last Working Jackett Version**:
n.a. New install

**Are you using a proxy or VPN?** [yes/no]
No

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]
Linked Rutracker via Jackett to lidarr. Lidarr wants to search Rutracker and an error occurs.

### Logged Error Messages

https://pastebin.com/MQ0JcKAp

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
I am able to set up the Jackett rutracker indexer with Lidarr and use it to search for music, which suggests the issue is at your end.
you log shows that the task is being cancelled see https://github.com/Jackett/Jackett/wiki/TroubleShooting#the-operation-was-canceled for explanations on possible reasons.

to progress this further we are going to need to see an **enhanced** log which contains debug and html that may help provide clues to why you are having issues.
see https://github.com/Jackett/Jackett/wiki/TroubleShooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by Jrswitchblade** [comment]
Hi,

It is fixed now. I forgot to install a package. Thanks for your support.
You can close the case.

libcurl4-openssl-dev bzip2 mono-devel

mono-devel is required for some private trackers

Regards, Jafetth Rowaan
