### ISSUE TITLE
[REQ]erzsebet.pl

### ISSUE THREAD

**Issue by berat1397** [Jackett/Jackett#8556]
Site link: http://erzsebet.pl/
This site russian adult  semi-private torrent sites like erzsebet.org.
Search engine is running.
Search engine page: http://erzsebet.pl/tracker.php

**Comment by garfield69** [comment]
Jackett 0.16.485

**Comment by garfield69** [comment]
https://erzsebet.pl/ redirects to https://erzsebet.org/ so it looks like .pl has been hijacked by *.org
Since my *.pl account is clearly different from my *.org account, they clearly ware two different sites despite using similar engines and html presentations.
So if on 30 days *.pl does not regain its domain then I will remove that indexer.

**Comment by ilike2burnthing** [comment]
https://erzsebet.pl/ - `Technical work, we'll be back soon.`

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://erzsebet.pl/ returning Error 523 Origin is unreachable

**Comment by ilike2burnthing** [comment]
`Welcome!
Site 31.210.170.23 just created.
Real content coming soon.`

**Comment by garfield69** [comment]
v0.18.432
