### ISSUE TITLE
[eztv] Exception (eztv): certificate validation failed: [Subject]  CN=www.tvicb.com, OU=Telstra Operations, O=Telstra Corporation Limited, L=Melbourne, S=Victoria, C=AU[Issuer]  CN=QuoVadis Global SSL ICA G2, O=QuoVadis Limited, C=BM[Serial Number]  5A5B55982F3BD259BA4F3B1DF21B8E0B6C308217[Not Before]  6/1/2016 2:54:51 PM[Not After]  6/1/2019 2:54:48 PM[Thumbprint]  C1F1745CB17D0D7A270814F70F9DB3A349B99920: The SSL connection could not be established, see inner exception. (Test)

### ISSUE THREAD

**Issue by samhentunen** [Jackett/Jackett#8559]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
The Jackett EZTV indexer works for me which suggest the problem is at your end.
the official https://eztv.io/ site has a certificate thumbprint of 02aab7bdf4a888f307e326766c03fda271fe192b
you are seeing a certificate thumbprint of C1F1745CB17D0D7A270814F70F9DB3A349B99920

this probably means that your ISP is blocking your access to eztv and directing you down a black hole to a dead end with an invalid certificate and hence the error.

Use a Browser on the same machine that is running Jackett, access the Site using the same address as the Indexer's config SiteLink and confirm that this is the case.
A possible solution you can try is to stop using the DNS provided by your ISP and switch to one of the public ones from Google (8.8.8.8 and 8.8.4.4) or Cloudflare (1.1.1.1 and 1.0.0.1).
An alternate approach is to use a VPN or proxy.

**Comment by samhentunen** [comment]
That sounds right to me, thanks for your quick response.
