### ISSUE TITLE
[1337x] Exception (1337x): Authentication failed because the remote party has closed the transport stream.: The SSL connection could not be established, see inner exception. (Test)

### ISSUE THREAD

**Issue by dha72** [Jackett/Jackett#8563]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Window 10

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.16.310.0

**Last Working Jackett Version**: Don't remember. It was working on my mac.

**Are you using a proxy or VPN?** no

### Description
When I click on test, it gives me this error.

### Logged Error Messages

An error occurred while testing this indexer
Exception (1337x): Authentication failed because the remote party has closed the transport stream.: The SSL connection could not be established, see inner exception.

**Comment by garfield69** [comment]
The Jackett 1337x indexer (using https://1337x.to/) works for me which suggests the issue is at your end.
Have a read of https://github.com/Jackett/Jackett/wiki/Troubleshooting#authentication-failed-because-the-remote-party-has-closed-the-transport-stream and see if that helps you figure out how to resolve you issue.
