### ISSUE TITLE
[Req]thetradersden.org

### ISSUE THREAD

**Issue by MaDTaZ** [Jackett/Jackett#8594]
New Site that I would like added to Jackett.  
The Trader Den
http://www.thetradersden.org

They have open sign ups right now

Powered by: vBulletin

**Comment by garfield69** [comment]
are you familiar with this site?
is there a search that returns the torrent lists in the same format as
http://www.thetradersden.org/forums/torrents.php?tor=list
because any time I use some search option I get a different layout (a topics/thread view) tather than a torrent list view.
Is there a search that returns a torrent view?

**Comment by garfield69** [comment]
the reason I ask is because the threads view does not have the size, seeders, leechers and completed columns.

**Comment by garfield69** [comment]
correction:
the thread view has s/l/c as part of the title row, but not the size. 
still, if there is a way to get the torrent view, that would simply processing.

**Comment by MaDTaZ** [comment]
Ya it is more of a forum based search engine you have to actually click the link to get the download so looks pretty hard to pull th einfo

**Comment by garfield69** [comment]
in that case this indexer will need to be written in C# because the two different ways of presenting results is not something yaml can handle.

**Comment by garfield69** [comment]
closing as stale.
