### ISSUE TITLE
[Bug] TorrentLeech Doesn't Work 

### ISSUE THREAD

**Issue by VadVoci** [Jackett/Jackett#862]
[Bug] TorrentLeech Doesn't Work 

Configuration failed: Found no results while trying to browse this tracker

**Comment by kaso17** [comment]
which version are you running?

**Comment by VadVoci** [comment]
Jackett Version 0.7.713.0

**Comment by kaso17** [comment]
upgrade to the latest and it should work

**Comment by Yarli** [comment]
Had the same issue so I downloaded the latest release, currently 0.7.824.0 and tried again.
No success.  I was able to search using the manual search through Jackett but searches would fail through Sonarr. Sonarr keeps moaning that the indexer is offline due to failures so I tried removing the connection to TorrentLeech in Jackett and tried re-adding it. Now it won't let me add the account again saying configuration failed.

I tried updating my environment using sudo apt-get update && sudo apt-get upgrade, but that's not helped either. I know Torrentleech seem to have updated their site lately to a new design, so I'm guessing maybe the code which connects Jackett with Torrentleech may also need updating too perhaps ?

**Comment by kaso17** [comment]
Please post the output of `curl -v  https://www.torrentleech.org`

**Comment by Yarli** [comment]
I've attached as a text file as the raw output from curl seems to mess up when being parsed as a comment on here.

[Issue 862.txt](https://github.com/Jackett/Jackett/files/671586/Issue.862.txt)

**Comment by kaso17** [comment]
Would have expected a TLS error, but it seems to work.
Try running Jackett with the "--IgnoreSslErrors true" option anyway please.
If it's still not running please provide a tcpdump for the connection attempt.
The "got NotImplemented/InternalServerError" is happening on low-level connection error (so far a failed TLS handshake/connection timeout is the only known reason)

**Comment by Yarli** [comment]
Can I confirm that the following is the  correct way to do this on Ubuntu 14.x

execute: /etc/init.d/jacket stop

Edit /etc/init.d/jacket
Amend line 35
From: DAEMON_OPTS=" "$EXENAME
To: DAEMON_OPTS=" --IgnoreSslErrors true "$EXENAME

execute: /etc/init.d/jacket start

If so, I tried that and it didn't seem to make any difference. Still getting the same errors in the logs and also getting a message saying configuration failed when attempting to add the login credentials to jackett.

I'm working on the tcpdump at the moment. It's a bit time consuming because the same machine running jackett also handles several other "online" tasks and omitting those from the logs is proving to be a little troublesome. I can take some services offline but I also need to configure my firewall to stop forwarding some services to the machine temporarily whilst I do the tcpdump. I'll aim to do this when I have a bit more time.

**Comment by kaso17** [comment]
you can use e.g. tcpdump host 1.2.3.4 to filter only traffic for a specific IP. No need to shut down anything

**Comment by Yarli** [comment]
Perfect. Thank you. Not used tcpdump for ages and totally forgot that you could do that.

After running it I noticed several checksum errors and also seemed that there was very little traffic coming in, certainly a lot less traffic than I was expecting, I could see the packets going out but nothing returning, so I turned to my Intrusion Detection System back at my primary firewall and noticed that it was blocking that host due to empty request URI's (Potentially Bad Traffic). So I've since put that host onto a supress list and it's now working. 

Really sorry to have flagged this as a fault. It was down to my IDS falsely picking up on that as a threat all along.

Maybe if @VadVoci or anyone else are still having trouble getting this to work, then try checking your firewall/router to see if you have some form of IDS or threat protection and try temporally turning it off and see if it then works. 
If it does, then there should be a way of adding www.torrentleech.org or 104.20.22.72 as a whitelisted host or supressing the "Empty URI" rule.

**Comment by kaso17** [comment]
@Yarli: does the IDS intercept HTTPS? Otherwise it shouldn't see the HTTP/URI headers. And even if it sees the traffic the URIs shouldn't be empty.

Or was the complete host blocked due to some non Jackett related HTTP requests?

**Comment by Yarli** [comment]
I believe it does some basic HTTPS inspection, mainly ensuring the traffic conforms to the standards for HTTPS I should imagine, obviously the traffic is encrypted so it can't really inspect the packets. 

Looks like it blocked the whole host when it discovered a problem. Not sure how it spotted the issue though, unless maybe a HTTP request triggered the block and that subsequently blocked it for HTTPS as well. Hard to say. 
It may have also been me that triggered the original HTTP request that started all this, as I frequently visit the site, although I usually use HTTPS every time I do.
I have noticed this happen regularly when sites use JSON/AJAX requests, which I know torrentleech does use, so perhaps it was that which caused the issue, and might not actually be Jackett which did this at all. Again hard to say.

I think we can probably chalk this one down to an issue outside of Jackett so we can probably close this issue down perhaps ?
