### ISSUE TITLE
Error while parsing Cardigann definition [vanila.yml]

### ISSUE THREAD

**Issue by lucknaumann** [Jackett/Jackett#8648]
### Environment

**OS**: 
Windows 10 v1809

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]
.Net-Framework

**.Net Version**:
4.8.03761

**Jackett Version**:
0.16.438.0

**Last Working Jackett Version**:
It works but keeps displaying this error in the logs. Last version prior to this error? No idea. (I'm reporting because it might help. No idea what this error means or why it's being reported.)

**Are you using a proxy or VPN?** [yes/no]
no

### Description
Displays error after updating via the web app. I don't check the log if I've had to download the exe to update. 

### Logged Error Messages

Error while parsing Cardigann definition C:\ProgramData\Jackett\Definitions\vanila.yml: (Line: 2, Col: 3, Idx: 6) - (Line: 2, Col: 3, Idx: 6): Exception during deserialization

[vanila.zip](https://github.com/Jackett/Jackett/files/4631876/vanila.zip)

**Comment by garfield69** [comment]
Thank you for reporting.
The vanila indexer was supposed to have been removed back in Feb 2020 with 0.13.144 but an oversight meant that a cleanup step was left out. While the indexer in no longer being published, the step to delete it from users' definitions folder is missing.
Should be fixed with the next release in about 5 hours or so.

**Comment by lucknaumann** [comment]
Sounds great! Thanks & you're welcome! =)

**Comment by garfield69** [comment]
Jackett 0.16.449

**Comment by lucknaumann** [comment]
Apologies for the late reply. The update went fine with no error message. Thanks for your speedy replies and handling and for Jackett! 😃
