### ISSUE TITLE
[SpringSunday] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#8697]
### Environment

**OS**: Windows 10 Pro 64-bit

**.Net Runtime**: N/A

**.Net Version**: N/A

**Jackett Version**: 0.16.496

**Last Working Jackett Version**: Not sure. This is my first time configuring SSD in Jackett

**Are you using a proxy or VPN?** No

### Description
I'm able to configure SSD, but searches do not returns any results.

### Logged Error Messages
`An error occurred while testing this indexer`
`Found no results while trying to browse this tracker`

Enhanced log
[log.txt](https://github.com/Jackett/Jackett/files/4644751/log.txt)

### Screenshots
Not needed

**Comment by RoloSoze** [comment]
@Curtis-L This is happening for you as well, right?

**Comment by garfield69** [comment]
Looking at the log you provided, it appears you are getting an additional field in the torrent row which the indexer is not expecting, which bumps the selectors out by 1, causing the indexer to fail to pick up the date and causing it to reject the whole row.
While the Site is a NexusPHP there is obviously been some customisation since the time the indexer was written.
I should be able to amend the indexer to cope, but It would be better if I could test my changes before publishing. But my account was suspended since I did not pass the novice trial.

**Comment by RoloSoze** [comment]
> I should be able to amend the indexer to cope, but It would be better if I could test my changes before publishing. But my account was suspended since I did not pass the novice trial.

Would it be possible to make the changes and merge them so I can download the drop folder and test your changes prior to releasing the next release?

**Comment by garfield69** [comment]
yes I can do that.

**Comment by garfield69** [comment]
Jackett 0.16.511
