### ISSUE TITLE
[generationfree] Too many requests with Jackett for the tracker

### ISSUE THREAD

**Issue by Arrowblood** [Jackett/Jackett#8702]
Hello,
https://generation-free.biz/  staff warned me I make too many requests on the tracker. But I simply use Jackett manually as a search engine so I type in movie's titles and ask all my trackers with one request. Of course I do a lot of search requests from time to time, but I don't think it's so much (I'm not so sure, but they told me about 9000 requests for one year).
Perhaps you can implement same settings you did for ABN to simulate human browsing ? 

Thanks

**Comment by garfield69** [comment]
Switching the current yaml indexer to one written in c# to simulate human browsing like ABN will not reduce the number of requests made to the site.

Normally, Jackett aims to provide up to 100 results per search.
And because the site returns only up to 40 results per search page, the current indexer has been coded to fetch two pages for every search.

So we can stop making a query for the second page, and be satisfied with just the maximum 40 results possible per search.
And that would reduce the number of requests by half.

But on the other side of the coin you are the first user to report this issue, others so far, apparently manage to make less than 12 request per day (4500 request per year / 365 days is 12 request a day * 2 pages per request = the 9000 per year you are apparently doing).
So the question is, does 12 requests per day constitute a normal workload, or are you too aggressive a searcher?

Myself, I generally do about 1 to 5 per day, depending on my tv episode calendar. And for movies, maybe 5 searches per week.
@ngosang  @cadatoiva @RoloSoze  Does 12 searches per day seem like a high number, how many do you do per day ?
Should we drop fetching the second page and be happy with up to 40 results from this site?

**Comment by RoloSoze** [comment]
@garfield69 On weekends when I'm looking for multiple movies/TV seasons, and being very particular about the exact version I want, I'd probably do two to three dozen searches a day, but I try to wait little in between searches so as not to overload any tracker with my queries. If I'm testing things for Jackett, it could be even more than that. 

Off the top of my head, the only tracker that has issues with the number of searches/amount of traffic generated is PassThePopcorn. However, PTP would automatically prevent the user from generating further traffic by disabling access to the website, and instructing the user to return the next day. This amount is defined and built into PTP's API/website. 

For this particular case, I don't think 12 searches per day constitutes a particularly high number, and it doesn't seem like they have a defined number as to what constitutes a high number of requests. However, it's possible that @Arrowblood uses this tracker daily and has done so for a while, the traffic generated caught the staffs' attention as it could be more than the majority of the tracker's users.

In this case, I suggest not fetching the second page and just sticking to the first. @Arrowblood Maybe you could try to be more specific in your search queries to prevent returning more than 40 results at a time. Assuming you can't change the number of torrents per page from your profile settings, you could also try requesting the staff to increase that number to 100? Just a thought.

**Comment by garfield69** [comment]
I've checked settings, there does not appear to be one for adjusting torrent results per page on the web site like other sites can.
I'll drop the second page and see if we get any negative feedback from others.

**Comment by garfield69** [comment]
Jackett 0.16.511

**Comment by xfouloux** [comment]
i just got warned, added the tracker 6 days ago and i'm on the top10 of user request toward the site !
I got 2 sonarr with 2954 show each (one for VO+VOSTFR, the other for MULTI only), radarr with 30k movies and lidarr with 800 artists, RSS search is set to 15min
is there any way to cache results of jackett for X min for indexers ? like my 2 sonarr hit each other the same results in cache ?
Thanks

**Comment by garfield69** [comment]
@xfouloux IMO the RSS searching set to every 15 minutes is riddicously frequent and totally pointless.
No one needs to know if a torrent is available within 15 minutes of being released, across the whole library of tv or movies or music.
@ngosang  any thoughts on this topic? see https://github.com/Jackett/Jackett/issues/8702#issuecomment-737251433 in particular.

**Comment by xfouloux** [comment]
having set everything at 1H on RSS is fine now it seems

**Comment by ngosang** [comment]
The current cache in Jackett is useless as it's. I would like to make improvements but I have little time I am busy with the maintenance of the trackers, review prs ...

More details:  #10382

**Comment by xfouloux** [comment]
well seems like i got blocked again, with 1H setting, putting 2H RSS interval settings.

**Comment by ngosang** [comment]
> I don't get it, other than RSS interval, when *arr is requesting the latest torrents since last time, is there anything else triggering jackett ?

No, Jackett doesn't make requests for himself. Jackett prints 1 trace with each request. Take a look at the traces.
I'm working on the cache but it will take some time.
