### ISSUE TITLE
[passthepopcorn] Exception (passthepopcorn): Unexpected character encountered while parsing value: Y. Path '', line 0, position 0.: Parse error (Test)

### ISSUE THREAD

**Issue by z0mn** [Jackett/Jackett#8706]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
I've not see this error message before so if you want us to help you diagnose this issue then try to answer as many of the question in the first post of this ticket as you can, and provide a full **enhanced** log so that we can hopefully see that PTP is sending you. See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
