### ISSUE TITLE
[thepiratebay] Exception (thepiratebay): Connection reset by peer: The SSL connection could not be established, see inner exception. (Test)

### ISSUE THREAD

**Issue by Bidley** [Jackett/Jackett#8744]
### Environment

**OS**: OpenMediaVault5 (Docker/Portainer)

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: Latest

**Last Working Jackett Version**: Unsure but weeks possibly months ago

**Are you using a proxy or VPN?** [no]

### Description

None of the proxies work for TPB, nor have they since they switched it up. I'm not sure if this is expected or if it's just me. I've periodically gone through all the proxies listed on the Jackett GUI, and none of them work, giving the mentioned error.

All other indexers (I have another 8-10 set up) work fine.

### Logged Error Messages

Logs: https://pastebin.com/1p5n3kss

**Comment by garfield69** [comment]
I tested `https://thepiratebay1.live/` (which is the only url in the log you provided), and it works for me, as should all the other proxies as they are checked regularly by @ilike2burnthing 
Which implies the issue is at your end.

Reporting that you are on the **latest** Jackett in not useful, please identify the **specific** Jackett version that you are on, by accessing your Jackett dashboard and scrolling to the bottom. 

Let see if we can get more info.
Please open a terminal to your docker Jackett container (typically `docker exec -it jackett /bin/bash`) and post the results of 
`curl -vvv https://thepiratebay1.live/`
and 
`openssl s_client -connect thepiratebay1.live:443`
Thanks.

**Comment by ilike2burnthing** [comment]
Just checked, all tpb proxies are working in browser and Jackett

**Comment by Bidley** [comment]
Thanks - I suspected the problem may be my end.

Jackett version is 0.16.521.0

Results of curl...
*   Trying 104.28.17.205...
* TCP_NODELAY set
* Connected to thepiratebay1.live (104.28.17.205) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to thepiratebay1.live:443 
* stopped the pause stream!
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to thepiratebay1.live:443 

Results of openssl...
 CONNECTED(00000005)
write:errno=104
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 320 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)

**Comment by garfield69** [comment]
unlikely to be anything to do with Jackett.
It appears that the ca store on the docker image does not contain a CA to match the one cloudflare is presenting when you access  thepiratebay1.live
you may want to follow this up with the docker support staff.

**Comment by Bidley** [comment]
I'm a moron. My ISP was blocking TPB. I've routed Jackett through a VPN and all is well.

Thanks for all your help.
