### ISSUE TITLE
vhstapes: no results

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#8777]
I can remove and configure the tracker in Jackett but I don't get search results.

**Comment by garfield69** [comment]
looks like the default view for the torrents search page is now a **gallery view** instead of the **list view**
while you can change the view back to list via a link on that page, I cannot find any setting to permanently set it to list.
So unless you have better luck finding that option I will have to recode the indexer to process the gallery view results :-(

**Comment by garfield69** [comment]
hold the phone, found `https://vhstapes.org/torrents.php?view=list` which may solve the issue.

**Comment by ngosang** [comment]
You can use these URLs:
* https://vhstapes.org/torrents.php?view=list&searchtext=
* https://vhstapes.org/torrents.php?view=list&searchtext=harry

;)

**Comment by ngosang** [comment]
I was fast but not enough :thinking:

**Comment by kilroyma** [comment]
Just commenting to follow when this gets fixed

**Comment by garfield69** [comment]
was fixed beginning with 0.16.551 but it seems the site has made further changes again which requires more adjustments. will investigate.

**Comment by garfield69** [comment]
site has dropped the view=list parm of the search url.
now you need to login to the web site and check that your torrent search page is in list view, toggle it if it is currently in galley view back to list.
then logout and try jackett again.
currently working for me.

**Comment by garfield69** [comment]
Jackett 0.16.589

**Comment by ngosang** [comment]
> currently working for me.

+1
