### ISSUE TITLE
[yts] The SSL connection could not be established, see inner exception.: The handshake failed due to an unexpected packet format. (Config)

### ISSUE THREAD

**Issue by tellice** [Jackett/Jackett#8789]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

I am trying to add YTS.mx to my indexer, but getting the following error. 

### Logged Error Messages

 An error occurred while updating this indexer
The SSL connection could not be established, see inner exception.: The handshake failed due to an unexpected packet format.
Click here to open an issue on GitHub for this indexer.

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
The most common reason for error is that your ISP is blocking access to the site.
Can you access the site via browser running on the same machine as Jackett?
follow https://github.com/Jackett/Jackett/wiki/Troubleshooting#authentication-failed-because-the-remote-party-has-closed-the-transport-stream for suggestions.
