### ISSUE TITLE
[BakaBT] Duplicate torrents in Jackett

### ISSUE THREAD

**Issue by just-an-alt** [Jackett/Jackett#8828]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**Jackett Version**: Linuxserver's Jackett image (Version 0.16.585.0)

### Description
The movie "Spirited Away" appears twice per quality in Jackett.
I suspect this is because of the "|" character, but I'm not sure.

### Screenshots
BakaBT: https://i.imgur.com/IOEl8oR.png
Jackett: https://i.imgur.com/olv3H1Z.png

**Comment by jellofishi** [comment]
This does appear to be due to the "|" character.

It appears to be like this since the tracker was added (or moved) in 2016.

the logic to regards each search response with a "|" to count as 2 separate releases, one with the english name and one with the japanese phonetic.

Perhaps this is to make the search results more usable for sonarr and the like ?

**Comment by RoloSoze** [comment]
@seeyabye Since you're a member of BakaBT, do you think you can work on this issue?

**Comment by garfield69** [comment]
Jackett 0.16.1549
