### ISSUE TITLE
[The Pirate Bay] Jackett reporting no results from TPB but when using TPB manually results are shown

### ISSUE THREAD

**Issue by aidenmitchell** [Jackett/Jackett#8829]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Windows 10

**.Net Runtime**: Unsure

**.Net Version**: Unsure

**Jackett Version**: 0.16.585.0

**Last Working Jackett Version**: Unsure

**Are you using a proxy or VPN?** yes

### Description

When searching for "It's Always Sunny in Philadelphia", Jackett returns no results for The Pirate Bay, however when using the site directly, I can find the proper release.

### Logged Error Messages

Errors: https://paste.ubuntu.com/p/3cwvT5qMsC/

Full log: https://paste.ubuntu.com/p/3Kv6bpvtx3/

### Screenshots

N/A

**Comment by garfield69** [comment]
it is the `it's` that causing it. Many sites from the apostrophe and use `its` while others use `it s`.
needs research for the best method to use for this site.

**Comment by ngosang** [comment]
@garfield69 what should we do?

**Comment by garfield69** [comment]
The situation is complicated for this indexer because of #7291 which replaces simplified Chinese characters with the mask `.`
But this has the unintended effect of also replacing `'` with `.` which makes Jackett search for `it.s` 

TPB web site has torrents named `It's Always Sunny in Philadelphia` and `Its Always Sunny in Philadelphia` and the only way to get both results on the web site is to search for `Always Sunny in Philadelphia`
So I propose adding a keywordsfilters to remove `it's` from the search string.

**Comment by garfield69** [comment]
Jackett 0.16.759
