### ISSUE TITLE
[Feature Request] User space Definitions Folder

### ISSUE THREAD

**Issue by zenof** [Jackett/Jackett#8886]
Sometimes the tracker may enable Cloudflare temporarily and lead to the API service unavailable. But it's their provisional measures, therefore we are no need to change the definition file permanently in the repo. However, when changed the file locally, it will be rewritten every time the Jackett auto-updates.

Therefore we should add a userspace definitions folder under the config path. The definitions with the same name loaded from userspace should have a higher priority to the built-in definitions. Also, for a userspace definition file with the same name with a built-in definition, it may only have a partial section that will be replaced to the section of integrated definition. For example, it can only contain the `login` part and will apply to the integrated definition's login part. And the Jackett watch this folder and reload automatically when a file changes. It will also be beneficial to the debug of definitions file.

**Comment by garfield69** [comment]
restart your jackett service then take a look at the log.
you will find a log entry beginning with `Loading Cardigann definitions from:`
on my windows for example
`Loading Cardigann definitions from: C:\WINDOWS\system32\config\systemprofile\AppData\Roaming\cardigann\definitions\, C:\WINDOWS\system32\config\systemprofile\AppData\Local\cardigann\definitions\, C:\ProgramData\Jackett\Definitions`
so this feature already exists.
by placing your personal yml indexders in any folder listed prior to the last one, you should achieve what you want.
One caveat: use a unique **filename**, and internal yml **id** and **name** keywords so that there is not clash or possible overwrite from the yml loaded in the last folder (which should be the Jackett package folder)
