### ISSUE TITLE
[Enhancement] Trackers with line/word wrap issues

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#889]
When conducting a manual search, I noticed that some trackers do not currently support line/word wrap. A long torrent name is displayed with ... either in the middle or at the end of the torrent's name, instead of being wrapped to the next line to show the full name. 

This becomes an issue when filtering based on certain keywords after conducting a manual search query. If the keyword is not present in the portion of the torrent's name that's displayed in Jackett, the torrent doesn't appear in the filtered results.  

Let me know if you require names of trackers where this happens.

**Comment by kaso17** [comment]
For some trackers a long title is simply not available on the search results page. For others it's available in the title/tooltip. If you're aware of any cases where it's available on the tracker but not used by jackett, please let us know. Otherwise you've to convince the operator of the tracker first to included it in the search results first.

**Comment by armani316** [comment]
Alright, let me examine the trackers I identified. I compared the title in Jackett's search results with the title on the torrent's main page on every tracker in question, but I'll now compare to the titles that appear on the tracker's search results instead.

**Comment by armani316** [comment]
@kaso17 I checked out all the trackers that had this issue in Jackett, and you're right. The full name is not available on the trackers' search results to begin with, so there's nothing that can be done about it here. I'm closing this.
