### ISSUE TITLE
[SpringSunDay] Clearance failed after 10 attempt(s).

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#8911]
@garfield69 I think SSD needs to shift to the cookie method to bypass the Cloudflare challenge, the same way you did it for OurBits in #8881 via 6ed3413

@Curtis-L I'm guessing you have the same issue?

**Comment by RoloSoze** [comment]
Tested. Works well! Thank you.

**Comment by garfield69** [comment]
Jackett 0.16.650

**Comment by Curtis-L** [comment]
> @garfield69 I think SSD needs to shift to the cookie method to bypass the Cloudflare challenge, the same way you did it for OurBits in #8881 via [6ed3413](https://github.com/Jackett/Jackett/commit/6ed341354e28dc7dda5e4579ea0f9c2b2fe58230)
> 
> @Curtis-L I'm guessing you have the same issue?

my cookie isn't expired and when i added SSD, it doesn't have cloudflare challenge.

me personal actually prefer cookie way of adding it, re-adding it with password and captcha costs more time, but for sites without captcha, password way can be more convenient since it won't have to face cookie expiration.

**Comment by RoloSoze** [comment]
@Curtis-L I agree. SSD now uses the cookie method, and it works well for me.
