### ISSUE TITLE
Jackett in Heroku

### ISSUE THREAD

**Issue by foremtehan** [Jackett/Jackett#8956]
As you may know heroku restarts its dyno every 24hr hence the api key will change every time. So, My question is how can add indexer, get/set the api key on the fly ? I mean without visiting the page, does jacket have api inside itself for this particular thing ?

**Comment by garfield69** [comment]
the Jackett API key is set at first time initialisation, and is saved in the ServerConfig.json file.
The next time Jackett is started, if the ServerConfig.json file is found, that API key will be used.
Which Jackett package are you installing on this platform?
Does Heroku provide for a folder for retaining configs and settings?
If so, then by altering your jackett startup you can specify where the configs are kept and thus retain your Jackett settings and Indexer configs between container resets.

**Comment by foremtehan** [comment]
>Which Jackett package are you installing on this platform?
Deployed via docker: https://github.com/weslley39/jackett-heroku

>Does Heroku provide for a folder for retaining configs and settings?

I dont know i just tried to access the json that you mentiond: 
www.myheroku.com/ServerConfig.json but not working 

Can you please run it by yourself ? heroku have free tier and you can easly deploy jacket through that docker package

**Comment by garfield69** [comment]
No, sorry. The package you are using is not supported by this repository.
You need to direct your questions to https://github.com/weslley39/jackett-heroku since this person is your provider.
Presumably that person is familiar with Heroku and know these things.
I don't have any free time to spend researching installations on platforms not supported by https://github.com/Jackett/Jackett
