### ISSUE TITLE
[soundpark] Login failed: No form found on https://sound-park.world/login using form selector form[action=

### ISSUE THREAD

**Issue by GoodOldJack12** [Jackett/Jackett#8968]
### Environment

**OS**: Docker container

**.Net Runtime**: Unknown

**.Net Version**: Unknown

**Jackett Version**: 0.16.252.0

**Last Working Jackett Version**: 0.16.252.0

**Are you using a proxy or VPN?** No

### Description

A few months ago I added Soundpark to jackett, and it worked fine. 
Now it fails to login, even though the form with the action "/login" does exist on the page

**Comment by garfield69** [comment]
The soundpark indexer works for me, which suggests that the problem is at your end.
Login to the web site with your browser and confirm that your account credentials are correct, and that you have a good ratio, and that you do not have any outstanding alerts, notices or unread PM that could prevent you accessing the web sites torrent search page.
If all the above is good, then to progress this further we are going to need to see what the web site is sending to the indexer. 
Please provide a **full enhanced** log file which should include debug and HTML.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by garfield69** [comment]
Hi @GoodOldJack12,

No response has been received for 9 days. To prevent issue tracker clutter, this issue will now be closed. To re-open the issue, please provide the information requested and the issue will automatically re-open.
