### ISSUE TITLE
[BakaBT] Last keyword being cut out

### ISSUE THREAD

**Issue by janot** [Jackett/Jackett#8993]
e.g. when searching for "harry potter azkaban":

2020-06-17 01:12:47	Debug	
WebClient(HttpWebClient2NetCore): Returning OK => <!doctype html><html><head><meta charset="utf-8"></meta><title>Search results for &quot;harry potter&quot; - BakaBT</title>

**Comment by garfield69** [comment]
are you using the bakabt indexer on its own when you do this search, or are you doing a multi indexer search or using the aggregate ALL indexer?

**Comment by janot** [comment]
on its own. tried a clean jackett install only with this indexer added

**Comment by ngosang** [comment]
We have 4 issues open for this tracker but I don't have an account. If someone can invite me I can fix them.

**Comment by janot** [comment]
@ngosang site went private in 2017 and for 3 years since then the only way to get invited is to pass interview. that's unlikely to change anytime soon =/

https://wiki.bakabt.me/index.php/Sign_up#How_do_I_get_invited.3F
> **How do I get invited?**
> Right now, the only way to get invited is by passing an interview administered by site staff. These interviews are conducted on IRC, so follow our guide to find your way there.

I suppose it's more of a formality, but still an interview.

**Comment by ngosang** [comment]
Sorry, I don't have time to spend the interview. Maybe you can contact the administrators and show them these issues. Maybe they'll invite me.

**Comment by jellofishi** [comment]
BakaBT indexer assumes request is coming from non human source (eg. sonarr) which always appends the episode number to the search query. The last element of the search query is cut regardless of what it is.

Jackett.Common\Indexers\BakaBT.cs : 88:

`if (!string.IsNullOrWhiteSpace(queryCopy.SearchTerm))
            {
                var splitindex = queryCopy.SearchTerm.LastIndexOf(' ');
                if (splitindex > -1)
                    queryCopy.SearchTerm = queryCopy.SearchTerm.Substring(0, splitindex);
            }`

Don't think arbitrarily removing any number from the end of the query is good since it will affect anime's with actual numbers in the anime name.

Is there a way to detect if a request is an automated one from an application or a human using jackett ?

**Comment by garfield69** [comment]
No I don't think there is a way. The dashboard search and the processed API search can end up looking the same to the indexer that receives the query.
Is the episode a SxxExx or just the absolute episode number?
The best compromise would be for the bakabt indexer to check if the last search term is a 1 to 3 digit number or a SxxExx term, which it it then can remove, presumably because the bakabt search engine cannot handle searches that include these terms?

**Comment by jellofishi** [comment]
Arbitrarily removing the number breaks some search results:

Example:
"Ichi the Killer 2" returns the single result for the live action movie
"Ichi the Killer" returns both the first and second movies.

I tested through sonarr and it just sends an episode number (eh. season 1 episode 5 appends "5", season 2 episode 4 appends 4 + the number of episodes in season 1, which is very odd imho, and only appears to happen when the show is explicitly marked as anime in sonarr)

**Comment by RoloSoze** [comment]
@seeyabye Since you're a member of BakaBT, do you think you can work on this issue?

**Comment by seeyabye** [comment]
Just a remark on this before I push my PR.

Like what @jellofishi has mentioned, BakaBT was coded in a way to be compatible with Sonarr.
In case Sonarr's series is marked as Anime, it will send out each Anime as a search request with absolute numbering (if it's present) and alternative titles (if it's present in TheXEM).

Anyhow, I don't see a problem including the numbering even though BakaBT does not support individual episodes. The goal in mind is that if BakaBT does not return a particular result, so should Jackett. Hence, I don't see a point in dropping the last keyword in the search. I will be removing this part of the code in the PR.

The main problem though is Sonarr's compatibility. Because of how Sonarr does season searches for shows classified as 'Anime', it will be sending each absolute episode numbers from that particular season. In this case, the search result would be something like

```
One Piece 01
One Piece 02
One Piece ...
One Piece 08
```

Where Season 1 of One Piece has about eight episodes in Sonarr.

Right now, there is no good real solution for this because there's no way to know for sure if the request is coming from Sonarr or otherwise. I'm still trying to cook up a solution for this, but for starters, there're important protocols that have to be in place beforehand.

As a compromise, the upcoming PR will truncate any last digit numbers for the sake of retaining compatibility with Sonarr.

In the example given by @jellofishi, having two results is better than one as Sonarr eventually filters the right one.

**Comment by garfield69** [comment]
Jackett 0.16.1549
