### ISSUE TITLE
[extratorrent-cd] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by purevertigo** [Jackett/Jackett#9031]
also tried https://extratorrent.ag/
https://extratorrent.cd
https://extratorrent.si/

**Comment by garfield69** [comment]
the extratorrent-cd indexer is set up to only use https://extratorrent.si/ which works for me, which suggest that the problem is at your end.
1. ensure you are using Jackett  0.16.759
2. if you are not getting results then provide a **full enhanced** log so we can see debug and HTML.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by purevertigo** [comment]
OK. Thank you I think that might be the case.

@garfield69  How would I add extratorrent.ag as an alias?

**Comment by garfield69** [comment]
> How would I add extratorrent.ag as an alias?

you cant. 
1. the ETag uses a different HTML presentation so the ETcd indexer will not work with any ETag domains.
2. the ETag site is broken. It's search engine does not return any results. Its been that way for over a month which is why we deleted that indexer from Jackett.

**Comment by purevertigo** [comment]
OK. Thanks @garfield69 I wil delete from my list then.
