### ISSUE TITLE
[req] LatinoP2P (torrentseed.cl) https://latinop2p.com/ private Spanish/English

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#9065]
TorrentSeed https://torrentseed.cl/ private Spanish/English

**Comment by garfield69** [comment]
https://torrentseed.cl/ returning ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
```
Site has resurfaced on a new domain, essentially starting from scratch.
New URL: https://latinop2p.com/
```
https://torrentinvites.org/f31/latinop2p-torrentseed-cl-news-580402/

```
Tracker's Name: LatinoP2P (TorrentSeed.cl)
Genre: General
Sign-up Link: https://latinop2p.com/signup.php
Closing date: Soon!
Additional information: LatinoP2P (TorrentSeed.cl) is a Chilean Private Torrent
Tracker for Movies / TV / General Releases. "We invite you to join this new
community, a variety of torrents in Latin Spanish, English."
```
https://torrentinvites.org/f37/open-latinop2p-torrentseed-cl-general-580403/

Not sure if accounts were transferred over, hence posting here rather than as a new request. @garfield69 and/or @ngosang can you check?

It still uses TS Special Edition v.8.0 so I signed up for an account using a temp email just to check, and simply changing the site link worked (keyword and keywordless searches work, as do magnet and torrent downloads, and sorting appears to work, though I only did a quick check).

Categories might be the only things needing updating, but don't quote me on that.

**Comment by garfield69** [comment]
>Not sure if accounts were transferred over, hence posting here rather than as a new request. @garfield69 and/or @ngosang can you check?

accounts have not been carried over. As you surmised at the start, its starting from scratch.

**Comment by ilike2burnthing** [comment]
Shall I remove this one, or do you want to just rename and edit it (and make edits to the readme and program.cs) when you get time?

**Comment by garfield69** [comment]
In my next free slot I shall review and take the required actions.

**Comment by garfield69** [comment]
Jackett 0.16.1724

**Comment by garfield69** [comment]
https://latinop2p.com/ returning This site can’t be reached

**Comment by garfield69** [comment]
v0.18.656
