### ISSUE TITLE
[BroadcasTheNet] Missing search results

### ISSUE THREAD

**Issue by janot** [Jackett/Jackett#9086]
Getting results with this query on site directly, but not in Jackett:

2020-07-03 10:54:26 | Info | Manual search for "Beverly Hills 90210" on broadcasthenet with 0 results.
-- | -- | --
2020-07-03 10:54:26 | Debug | WebClient(HttpWebClient2NetCore): Returning OK => {"id":"122lx5f1","result":{"results":"0"}}
2020-07-03 10:54:25 | Debug | WebClient(HttpWebClient2NetCore).GetString(Url:https://api.broadcasthe.net)

**Comment by RoloSoze** [comment]
I have noticed that BTN's integration with Jackett needs a little bit of work since I find myself having to search their website quite often instead of Jackett to get accurate results. I never raised an issue because none of the current active C# developers is a BTN member.

@janot If you have a spare invite, are you able to send it to @ngosang? If not, are you willing to speak to BTN's staff about provide a staff invite so that BTN can have an active maintainer? Thank you.

**Comment by janot** [comment]
No invites, sorry
And I'd prefer to avoid conversations with their staff

**Comment by Nottt** [comment]
I can get an invite if you can fix my tracker issue :+1:

**Comment by RoloSoze** [comment]
@Nottt Can you detail the issue? If it's different from this issue, please open a new ticket for it.

**Comment by Nottt** [comment]
https://github.com/Jackett/Jackett/issues/9082

**Comment by RoloSoze** [comment]
@Nottt That's a different tracker. We're only discussing BTN here. Feel free to post over there about your willingness to invite the developer who's abole to fix that issue. They won't see it if you post here :)

**Comment by ngosang** [comment]
@Nottt Sorry, I don't have account in BJShare. Could you send me the BTN invitation anyway?

**Comment by Nottt** [comment]
I can get an account in bj-share if needed

**Comment by ngosang** [comment]
I don't like the exchange of favors. The other issue will be fixed at some point but it's not related.

**Comment by Nottt** [comment]
BTN is over their limit so the invites are disabled :/ only learned that now

**Comment by seeyabye** [comment]
@janot @RoloSoze 

For starters, can you provide a list of queries that mostly fails?

**Comment by janot** [comment]
@seeyabye 

Can't remember them now. If you provide me with a list of queries to test, I'll check.

**Comment by seeyabye** [comment]
@janot I have a fix ready for this. I just need a couple of queries that you've tried and have failed besides the one above. 

If it works out fine, I will submit a PR for this.

**Comment by janot** [comment]
@seeyabye looks like it's connected with commas in title, e.g. these queries fail too:
Doogie Howser, M.D.
Yes, Dear
etc.
Doesn't matter if I enter them in Jackett with or without comma

**Comment by ngosang** [comment]
Fixed in #9680

**Comment by RoloSoze** [comment]
> Rolo

My apologies, @seeyabye! I just saw this. Glad that you guys managed to fix these issues. 

@ngosang Are you a BTN member now? 

@seeyabye Since you're a BTN member and are willing to help with Jackett's issues (thank you!), can you check whether it's possible to enable IMDb ID search? On BTN's website, it is an option via Advance Search, but I'm not sure if it can be implemented in Jackett:

https://broadcasthe.net/torrents.php?action=advanced

**Comment by seeyabye** [comment]
@RoloSoze I have just checked it. Unfortunately, there's no IMDB ID search available on BTN's API.
However, there's TVDB support. I can look into implementing it later. I will need to see if Jackett natively supports this beforehand.

**Comment by RoloSoze** [comment]
@seeyabye Yeah that's what I thought :( With regards to TVDB ID, I personally never use this method to search, but maybe @garfield69 can explain whether it's supported in Jackett.

**Comment by garfield69** [comment]
Jackett supports tbdbid searching if the c# indexer has `SupportsTvdbSearch= true`, example of use https://github.com/Jackett/Jackett/blob/973aca364691fb2215030dcc0fea2743c38b3f01/src/Jackett.Common/Indexers/HDBitsApi.cs
and in yaml indexer if `tv-search: [q, season, ep, imdbid, tvdbid]` is present, example of use https://github.com/Jackett/Jackett/blob/a67cf545acbed17c5cef255a6cf6b2561912126e/src/Jackett.Common/Definitions/blutopia.yml

**Comment by garfield69** [comment]
Jackett 0.16.1472
