### ISSUE TITLE
[hachede] Exception (hachede): Login failed: Selector

### ISSUE THREAD

**Issue by Sergiodiaz53** [Jackett/Jackett#9116]
Hello,

I'm  having  some troubles with this tracker. 

In the log section I can see: [v0.2.0.1504] NzbDrone.Core.Indexers.Torznab.TorznabException: Torznab error detected: Jackett.Common.IndexerException: Exception (hachede): Login failed: Selector "div#member_info_bar" didn't match

So maybe they changed the login website. Can  you help me or explain at least where can I find the config file for this tracker?

Thanks in advance and thanks for all the job done.

**Comment by garfield69** [comment]
@RicardoVelaC  are you able to use the hachede indexer ok?

**Comment by garfield69** [comment]
@Sergiodiaz53  the hachede indexer requires you to use a cookie since its login page is protected by a reCaptcha which Jackett cannot solve using the standard login form.
The cooke has an expiry date, so you will need to regularly update it to keep current.
Don't ask me how often it expires, each web site has its own period, daily, weekly, monthly, whatever.
Access your Jackett dashboard, edit the hachede indexer config (wrench icon) and update the cookie.
Instructions are on the config panel, or see https://github.com/Jackett/Jackett/wiki/TroubleShooting#your-cookie-did-not-work for more details.

**Comment by Sergiodiaz53** [comment]
Yes, you are right. Its weird  because  I was still logged in the browser but the cookie was not working in jackett.. 
Anyway, I'll be checking it regularly.

Thanks in advance!!
