### ISSUE TITLE
https://torrentz2k.xyz/ error title name

### ISSUE THREAD

**Issue by 3xploiton3** [Jackett/Jackett#9143]
name title only showing https://torrentz2k.xyz

### Environment

**OS**: windows 10

**Jackett Version**: 0.16.817.0

### Screenshots

![image](https://user-images.githubusercontent.com/19517680/87254092-52bfb000-c4aa-11ea-8403-1078ce630aec.png)

**Comment by garfield69** [comment]
This is because the Torrentz2k web site does not actually have a **details page href link** for the titles in its search results.
The details that you see on the web site when you click on the title are generated dynamically by using a form and a call to a javascript function, its not actually a separate page with an address that can be reached by link navigation.
The Jackett cardigann engine that fetches the torrentz2k results cannot run JS.
The indexer would probably need to be re-written in c#. Not worth the effort IMO.
