### ISSUE TITLE
indexer duplication

### ISSUE THREAD

**Issue by ced455** [Jackett/Jackett#9150]
Hello,

I am trying to duplicate my YGG indexer since it's now working back and we cannot add it from the search

I duplicated the .json and changed the file name, restarted my docker but i cannot see it in my list, i guess i need to change something else but i don't want to break anything,

Could you help me out ?

Thanks

**Comment by garfield69** [comment]
Not sure I understand what you are trying to achieve.
Is it that you have customised your own personal version of the yggtorrent indexer?

In which case, make sure that the **id** is unique.
It is the **id** that determines the filename of the config .json, and it should also be the filename of your customised indexer yml code.
Also for convenience, you should change the **name** and **description** too, so that you can tell it apart from the official YGGtorrent indexer on the jackett dashboard.
So for example, if you cloned and customised yggtorrent.yml as yggtorrent2.yml, then the first four lines of your custom indexer should be:
```json
---
id: yggtorrent2
name: YGGtorrent2
description: "YGGTorrent2 is my customised version of the YGGtorrent indexer."
```
Jackett will then create a yggtorrent2.json config file to support the settings for your custom indexer.

**Comment by Danelem** [comment]
I would also add it in a different folder to avoid the file being deleted when there is an update. For example there:
cardigann/definitions/
