### ISSUE TITLE
1337x.to cannot download to qbittorrent

### ISSUE THREAD

**Issue by 3xploiton3** [Jackett/Jackett#9153]
### Environment

**OS**: windows 10

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.16.836.0

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [/no]

### Description

link : https://1337x.to/torrent/1540517/Taegukgi-The-Brotherhood-of-War-2004-KOREAN-720p-BRrip-x265-HEVC-10bit-PoOlLa/

download : http://127.0.0.1:9117/dl/1337x/?jackett_apikey=6x0gcosq134huy9eeq1ha3l3av5ppfic&path=Q2ZESjhEckhQWlJZT1lWS25Kb0lEanhlY21WRUZYQzBoU0d5V1hBR0poaktrSXdfUEpoRDlCbXVzVk9hb2plenU1b0R6TzJGVllkSVZJdzZyZkZyOGJMX0JTaG43a2pIdzAwWURSUFJQMlBfOTRtcGlzTEJVSUFjTWFBc0pUdnZGWkF1WFN6OFFzc1pyamtta2dUMTJHdENHT2tLNmZaTVBHZnN0aF9TYTlRaXN1dHI0UDh3djJ4dW1SRE9OdldTVkU2ZjN2TWN2MUE2STVzUllFeXk2WVBKamxlOHE5VDZfUlBmSzBZS2F5WE9EaEJ4Um9OdUVlaWMyQkFkNkFMZTZrWkdldw&file=Taegukgi+The+Brotherhood+of+War+2004+KOREAN+720p+BRrip+x265+HEVC+10bit+PoOlLa

#### ERROR LOG
http://127.0.0.1:9117/dl/1337x/?jackett_apikey=6x0gcosq134huy9eeq1ha3l3av5ppfic&path=Q2ZESjhEckhQWlJZT1lWS25Kb0lEanhlY21WRUZYQzBoU0d5V1hBR0poaktrSXdfUEpoRDlCbXVzVk9hb2plenU1b0R6TzJGVllkSVZJdzZyZkZyOGJMX0JTaG43a2pIdzAwWURSUFJQMlBfOTRtcGlzTEJVSUFjTWFBc0pUdnZGWkF1WFN6OFFzc1pyamtta2dUMTJHdENHT2tLNmZaTVBHZnN0aF9TYTlRaXN1dHI0UDh3djJ4dW1SRE9OdldTVkU2ZjN2TWN2MUE2STVzUllFeXk2WVBKamxlOHE5VDZfUlBmSzBZS2F5WE9EaEJ4Um9OdUVlaWMyQkFkNkFMZTZrWkdldw&file=Taegukgi+The+Brotherhood+of+War+2004+KOREAN+720p+BRrip+x265+HEVC+10bit+PoOlLa

### Screenshots

![image](https://user-images.githubusercontent.com/19517680/87329846-d688a380-c561-11ea-9c8f-081995ec0b1a.png)

![image](https://user-images.githubusercontent.com/19517680/87329915-f9b35300-c561-11ea-8dee-2275b1ce62b9.png)

**Comment by garfield69** [comment]
works for me which suggests the issue is at your end.
![image](https://user-images.githubusercontent.com/6933240/87348045-3f930a00-c5a8-11ea-833b-a551e2bdd5d2.png)

In general, 1337x does not store their own .torrent files, but use the itorrents.org service to fetch the .torrent file. In this instance, http://itorrents.org/torrent/28767B3AD848F252CA0CF762FD08D973FAB858DE.torrent for the title you are searching in this ticket.

However, since this is a 3rd party site with its own domain, if, for whatever reason, your system cannot access that link, then jackett cannot fetch the torrent.
It may be that your ISP is blocking access to itorrents.org or that service was offline at the time you made the search, or who knows what.

Something you can try as an alternative, it to switch the 1337x indexer from fetching .torrent to magnet. 
Use you Jackett dashboard, edit the 1337x indexer config, and change the download link to magnet
![image](https://user-images.githubusercontent.com/6933240/87348638-3191b900-c5a9-11ea-84fd-276d61bee0ad.png)

and see if that works.

**Comment by 3xploiton3** [comment]
thx, work again,

i'm change to this
![image](https://user-images.githubusercontent.com/19517680/87400164-a9300a00-c5e2-11ea-9358-8a82fa0ce4c9.png)
