### ISSUE TITLE
[Request] www.lostfilm.run. Use mirror for the main website

### ISSUE THREAD

**Issue by Prosecutor** [Jackett/Jackett#9154]
Hey! 

The torrent tracker already exists in Jackett under domain lostfilm.tv but some of the ISP is blocking it, so that's why i'm asking you to add/use mirror for it => lostfilm.run

Cheers!

**Comment by garfield69** [comment]
Thanks for reporting.
I have been blocked by the web site itself from using the ***.tv** domain, and have had to resort to using the **hide.me** **vpn** to access the site using a **Canadian** ip address.

So I am happy to add *.run as a secondary sitelink to the indexer. Should be available in the next release of Jackett due in about 10 hours or so.

If using the jackett dashboard you cannot edit the **lostfilm** indexer config (because the block is preventing the login page from being fetched by the config panel), then a backdoor method you can use right now is to:
- shutdown the jackett service, 
- find the **lostfilm.json** config file (usually in `~/.config/Jackett/Indexers` folder on linux, or `%ProgramData%\Jackett\Indexers` on windows,
- and using a plain text editor change the **value** of the **sitelink** block from **.tv** to **.run** and save.
example of the first 6 lines...
```json
[
  {
    "id": "sitelink",
    "type": "inputstring",
    "name": "Site Link",
    "value": "https://www.lostfilm.run/"
  },
 ```
- restart the jackett service 
- and now you shold be able to edit the config from the jackett dashboard, answer the number challenge, click **OKAY** and be good to go.

**Comment by Prosecutor** [comment]
Thank you.

**Comment by MaLaH88** [comment]
Can we reopen this issue and add a new mirror URL for lostfoilm please - https://www.lostfilm.uno/

Also, I'm not able to change the lost film URL in my config, because I removed it, and I cannot add it back because the .run is blocked.

**Comment by garfield69** [comment]
@MaLaH88 
*.uno was added as an alternate site link about 10 days ago. Jackett beginning with  v0.17.580 onwards have it.

if you cannot edit the indexer config using the Jackett dashboard because your are blocked and the config will not open, 
then here is a back door hack you can try.
1. Stop the Jackett service.
2. then find the lostfilm.json config file (usually in `~/.config/Jackett/Indexers` folder on linux, or `%ProgramData%\Jackett\Indexers` on windows), OR create a new one using a plain text editor.
3. if it exists, then just edit the site link, if creating a new one then paste the following
```json
[
  {
    "id": "sitelink",
    "type": "inputstring",
    "name": "Site Link",
    "value": "https://www.lostfilm.uno/"
  }
]
```
4. now start the Jackett service to reload the config and you should be good to go.

**Comment by MaLaH88** [comment]
Just fixed it based on your last year's comment. Thanks!
