### ISSUE TITLE
[REQ]torrentoyun.net

### ISSUE THREAD

**Issue by berat1397** [Jackett/Jackett#9180]
Turkish public game torrent site.
Link: https://torrentoyun.net/
Search engine is running.

**Comment by garfield69** [comment]
i'm getting 
![image](https://user-images.githubusercontent.com/6933240/87867115-addb3080-c9dd-11ea-85f1-54d7024b5dba.png)
whether I'm using my regional IP or a VPN set up as with a Canadian IP.
someone else will have to volunteer to code this one.

**Comment by garfield69** [comment]
seems I have access now, so I'll see if I can build an indexer for the site.

**Comment by garfield69** [comment]
This site is not suitable for use with Jackett which only supports sites that provide direct links to magnet or .torrent

On this site, the download link that is in the details page of each title is not always a direct .torrent link, but can be a link  to 3rd party providers such as zippyshare etc.
Jackett cannot download from these indirect links.

And since these links are not in the main search page, Jackett cannot filter out the non .torrent titles
