### ISSUE TITLE
https://dontorrent.org/ & https://pctreload.com/

### ISSUE THREAD

**Issue by leiva1990** [Jackett/Jackett#9191]
Spanish movie and shows( Best ES-ES  share torrent site )
Link: https://dontorrent.org/

Spanish movie and shows ( Castellano / Latino ) share torrent site.
https://pctreload.com/

**Comment by garfield69** [comment]
Please in future open one ticket per request, so that the progress of each indexer can be tracked and closed when completed separately.

https://dontorrent.org/ already has a request ticket #6214 so I am closing this ticket as a duplicate.

https://pctreload.com/ does not appear to have any .torrent or magnet links of its own.
instead it redirects to 3rd party providers that offer streaming or direct downloads.
As such it is not suitable for use with Jackett.

**Comment by ilike2burnthing** [comment]
https://pctreload.com/ is included as a proxy for NewPCT - https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/NewPCT.cs#L104
