### ISSUE TITLE
[jpopsuki] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by bearxbeat** [Jackett/Jackett#9194]
An error occurred while testing this indexer
Found no results while trying to browse this tracker
Click here to open an issue on GitHub for this indexer.

**Comment by garfield69** [comment]
please provide a full **enhanced** log without which we have no way to help further.
https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by garfield69** [comment]
also access your jackett dashboard and report the Jackett version.

**Comment by bearxbeat** [comment]
> 
> 
> also access your jackett dashboard and report the Jackett version.

Current version: v0.16.865
[log.txt](https://github.com/Jackett/Jackett/files/4951904/log.txt)

**Comment by garfield69** [comment]
your log shows that the indexer you are using is not the latest version that is included in Jackett 0.16.865.
your jpopsuki indexer is getting `Error while parsing field=files, selector=td:nth-child(3)`
while field=files should be `td:nth-last-child(6)`

are you using a custom version of the jpopsuki indexer, or a version stored in other than the default definitions folder?

**Comment by bearxbeat** [comment]
default version i am using..

**Comment by garfield69** [comment]
I should have looked at the datestamps in your log. 
the error I was referring to was from back in 2020-07-08
you did upgrade to 0.16.865 on 2020-07-20

but the log should this is not an **enhanced** log. 
please provide a full **enhanced** log without which we have no way to help further.
https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

you will know when you have it right because you will see lots of Debug messages and HTML.

**Comment by bearxbeat** [comment]
i am sorry i think the update was error
i try restart my pie
now the version is v0.16.873.0

now jpopsuki its fixed.
thank you!

**Comment by ParkerSaint** [comment]
Your bot closed my issue because it said that this is related, I have the same problem, however I made sure that I am on the most recent version.
