### ISSUE TITLE
XWTorrents Error Please check the capabilities (t=caps)

### ISSUE THREAD

**Issue by DJMValentino** [Jackett/Jackett#9215]
When I run the test for the connect for XWTorrents in Radarr and add the category 5060 its works fine. Once I do a search it errors out and shows the following in the logs
NzbDrone.Core.Indexers.Torznab.TorznabException: Torznab error detected: xwtorrents does not support the requested query. Please check the capabilities (t=caps) and make sure the search mode and categories are supported

**OS**: Ubuntu 18.04

**Jackett Version**: 0.16.891.0

**Comment by garfield69** [comment]
Radarr is for movies which usually does not support TV series. 
the Jacket XWTorrents indexer is set up for TV/Sport
So you should probably be using Sonarr.

**Comment by DJMValentino** [comment]
Yeah but they have PPVs that show up under MovieDB on that site. Also IP Torrents is able to show them under 5060 as well.

**Comment by garfield69** [comment]
I just successfully added to Radarr 0.2.0.1504 the jackett indexer XWTorrents and searched and found wwe extreme rules 2020
![image](https://user-images.githubusercontent.com/6933240/88233296-87faa800-cccb-11ea-82e8-0fd767987336.png)
so it works for me.

what version of Radarr are you using?
if you want more help then turn on the jackett **enhanced** log and repeat your test and upload the log file so I can take a look.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by DJMValentino** [comment]
I'm using Radarr - 3.0.0.3243
[log.txt](https://github.com/Jackett/Jackett/files/4963154/log.txt)

**Comment by DJMValentino** [comment]
I'm using Radarr - 3.0.0.3243
[log.txt](https://github.com/Jackett/Jackett/files/4963246/log.txt)

**Comment by garfield69** [comment]
RadarrV3 operates a little differently than RadarrV2

When doing the indexer TEST, RadarrV3 uses the **t=search** query
http://127.0.0.1:9117/api/v2.0/indexers/xwtorrents/results/torznab/api?t=search&cat=5060&extended=1&apikey=***redacted***&offset=0&limit=100
but when you use RadarrV3 to actually search for a title is uses the **t=movie** query
http://127.0.0.1:9117/api/v2.0/indexers/xwtorrents/results/torznab/api?t=movie&cat=5060&extended=1&apikey=***redacted***&offset=0&limit=100&q=WWE%20Extreme%20Rules%202020%202020
which the Jackett indexer rejects, because the only queries that the Jackett XWTorrents indexer supports are
```yaml
  modes:
    search: [q]
    tv-search: [q, season, ep]
```
and that is why you see the error
```
<error code="201" description="xwtorrents does not support the requested query. Please check the capabilities (t=caps) and make sure the search mode and categories are supported."/>
```

I will add a movie search mode to the indexer, and change one of the categories from TV/Sport to Movies, so that RadarrV3 can use the indexer too.
The update will be included in the next Jackett release due in about 6 hours or so.

**Comment by garfield69** [comment]
BTW, you should update your RadarrV3 xwtorrent indexer definition to only look for categories 2000,5060
the others in the default list are not valid for this Jackett indexer and its better if they are not included in each request that RadarrV3 makes to Jackett.

**Comment by DJMValentino** [comment]
Works perfectly after the new version and categories, thanks so much!
