### ISSUE TITLE
[torrentseeds] Object reference not set to an instance of an object. (Config)

### ISSUE THREAD

**Issue by Wh1t3Rose** [Jackett/Jackett#9230]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Unknown

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]: Unknown

**.Net Version**: Unknown

**Jackett Version**: 0.16.849.0

**Last Working Jackett Version**: Unknown

**Are you using a proxy or VPN?** [yes/no] No

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]
Add Tracker in Jackett
Put in Login Info
Submit

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
the indexer is working for me which suggest the issue is at your end.

please provide an **enhanced** log file containing the debug and HTML so we can try to figure out what is going on for you.
most likely you are being blocked by your ISP or some other issue is preventing the web site responding to the Jackett query in the expected manner.

see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by Wh1t3Rose** [comment]
Resolved. Didn't realize I wasn't up to date. Sorry!
