### ISSUE TITLE
[anidex] Could not find releases from this URL (Config)

### ISSUE THREAD

**Issue by droopified** [Jackett/Jackett#9261]
not able to add this but works fine on my browser. any suggestions?

**Comment by garfield69** [comment]
Jackett cannot solve the DDoS-guard security challenge. 
The only possibility is to use a VPN and try allocating a server from regions other than your own, so that you do not get the DDoS-guard being invoked by the web site.
Otherwise wait for the web site to relax their security again. 
Those of us who do not get the DDoS-guard challenge can use the Jackett indexer for this site.
