### ISSUE TITLE
[1337x] Exception (1337x): The message received was unexpected or badly formatted.: The SSL connection could not be established, see inner exception. (Test)

### ISSUE THREAD

**Issue by brandonheley** [Jackett/Jackett#9264]
**OS**:Windows 10

**Jackett Version**:0.16.933

**Last Working Jackett Version**: just started using today

**Are you using a proxy or VPN?** yes

### Description
Ive added TPB and 1337x using the listed known links but when i test them it brings back the error message

--An error occurred while testing this indexer
Exception (1337x): The message received was unexpected or badly formatted.: The SSL connection could not be established, see inner exception.

Ive tried on my VPN and off
### Logged Error Messages

An error occurred while testing this indexer
Exception (1337x): The message received was unexpected or badly formatted.: The SSL connection could not be established, see inner exception.

Sorry if ive missed any information that is needed i can add if there is anything else you need to help me out

**Comment by garfield69** [comment]
TPB https://thepiratebay0.org/ and 1337x https://1337x.to/ indexers are working for me on my win 10 Jackett 0.16.922
Which suggests the issue is likely happening to you due to ISP blocking or some other security app (anti-malware, firewall, router) getting in the way of establishing a secure connection.

https://1337x.gd/, https://1337x.is/, https://1337x.st/, https://x1337x.ws/, https://x1337x.eu/, https://x1337x.se/, https://1337x.unblocked.bar/, https://1337x.proxyportal.pw/, https://1337x.uk-unblock.pro/ all gets me a `Clearance failed after 10 attempt(s)` exception

https://1337.root.yt/, https://1337x.unblockit.win/ and https://1337x.to/ work for me.

Using a browser on the same machine that is running Jackett, and going through the same VPN (or not) as you were using when testing Jackett, do any of the 1337x links work for you, without getting a `Checking your browser before accessing <domain>.` cloudflare anti-DDoS check ?

Any domain that presents such a page will not work with Jackett.
Try changing the VPN region so you get allocated a server from a different country than your local IP address, and see if that helps.
Other than that, I have little else useful to suggest.

**Comment by brandonheley** [comment]
thank you that worked for 1337x but not the pirate bay any tips?

**Comment by garfield69** [comment]
>but not the pirate bay any tips?

have you tried editing the jackett thepiratebay indexer config any trying any of the alternative site links listed there?
if none work then I have no further suggestions for you.
