### ISSUE TITLE
[yggtorrent] Clearance failed after 10 attempt(s). (Config)

### ISSUE THREAD

**Issue by bossovitch** [Jackett/Jackett#9308]
### Environment

**OS**: Nas Synology

**.Net Runtime**:  Mono version: 5.20.1.34

**.Net Version**:

**Jackett Version**: 0.16.949.0

**Last Working Jackett Version**: ? previous week?

**Are you using a proxy or VPN?** no

Hello,
Someone else have this problem? is it the annoying and recurring problem with Cloudflare which is back or is it coming from me and my ip?

**Comment by garfield69** [comment]
>Someone else have this problem? is it the annoying and recurring problem with Cloudflare which is back or is it coming from me and my ip?

YGG have **not** enabled a _global_  cloudflare anti-DDoS challenge, as I can use the YGGTorrent indexer without problems.
Therefore the issue is with your IP address currently being blacklisted by cloudflare.
An experimental solve for the cloudflare protection is being worked on with #9029  but this is a long way from being ready for release.
your best bet is to use a VPN to allocate an IP from a region of the world other than your own which should hopefully allow you access with the indexer.
