### ISSUE TITLE
[jpopsuki] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by ParkerSaint** [Jackett/Jackett#9329]
jpopsuki seems to return no results when testing.

**Comment by garfield69** [comment]
if you are **not** on Jackett v0.16.836 through v0.16.985 then **upgrade**.
if you are, then the only way to research your issue is for you to provide **full enhanced** log with the debug and HTML so that we can have a look at what the site is sending you.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
