### ISSUE TITLE
Jackett on a budget: Rpi/other SoC/Android using Linux Deploy and Busybox?

### ISSUE THREAD

**Issue by dairefagan** [Jackett/Jackett#9359]
With very little Easy HTML Parser documentation and examples out there the last few days I have been enjoying learning basic python but less so painstakingly trying to make dom scraper queries that work on the CLI also work through an Elementum JSON  - and then I learned about Jackett - thank you.

I could just install Jackett on my Ubuntu desktop but and for my Nvidia Shield it had seemed my only option would be to set up an old Raspberry Pi. I was also hoping to gift some family and friends budget Android devices at Christmas, which I would configure for them with Kodi and control updates remotely, but if I want them to benefit from Jackett they would also need a Raspberry Pi, and that makes me consider if Rpi's are now at a point where they do not frequently freeze running Kodi - and Jackett? (The last Rpi I used Kodi on was version 2). If possible I would prefer the device I gift to also offer an Android experience - but not at the cost of the Kodi-Elementum-Jackett experience.

If I could make Jackett run on Android some how, I could perhaps use it at home on my Shield and on whatever budget Android devices I choose for friends and family. I have been reading about running linux distributions and Jackett on Android devices [Turning an old Android Phone into a Plex Media Server + PVR](https://www.alexbevi.com/blog/2017/09/22/turning-an-old-android-phone-into-a-plex-media-server/) and I wanted to ask if this would be a practical setup Jacket on the Shield and the Firestick, or whatever the best budget Android device is at the moment. Or - is the best option to just set up Jackett on my own Raspberry Pi 3 and buy Pi version 4s for friends and family or another budget SoC to run everything for them? Or perhaps setup Jackett at home and let my friends and family use it remotely from Kodi?

**Comment by dracossan** [comment]
PI , no issue:

https://github.com/Jackett/Jackett/issues/9402

**Comment by dairefagan** [comment]
Thanks. For testing I have been using an old Rpi 3 locally to serve a single device at a time with ~20 indexers and the only issue I have experienced is with the Kodi add-on Elementum timing out before it can process the results from Jackett Connector[Jackett Connector](https://github.com/fugkco/script.elementum.jackett).

I can see from Jackett's logs it provides the results for both the individual episode and season search within ~40-60 seconds. I have the timeouts for Elementum set to maximum and I can look at editing the values manually if necessary but first I want to report an issue with logs for the connector, which only released v1.0 in recent weeks.

When it does all work, it works incredibly well.

**Comment by ngosang** [comment]
I'm running Jackett on a RaspberryPi since long time ago. RPi 3b and 4b, both have enough CPU, disk and network speed to run Kodi + bittorrent client + jackett.
The problem is the RAM. Kodi needs ~500MB, Deluge ~300MB, Jackett ~250MB. 1GB of RAM is not enough and you are going to swap memory and that destroys the SD card in few months. I recommend you at least RPi 4b with 2GB of RAM.
If you have more budget, you can buy RPi 4 with 4 or 8 GB of RAM. That will allow you to install Kodi + bittorrent client + jackett + radarr + sonarr + lidarr + bazarr. You can install even Plex (but you can stream more than 1 or 2 movies at the same time). With 4/8GB of RAM you can use Docker to simplify the installation/upgrade (In 2 GB version I don't recommend it because it uses a bir more RAM).
