### ISSUE TITLE
[yggtorrent] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by TheoBrigitte** [Jackett/Jackett#9370]
### Environment

**OS**: Ubuntu 18.04.5 LTS / 4.19.0.8 (64bit OS) (64bit process)

**.Net Runtime**: .Net-Core

**.Net Version**: unkown (using linuxserver.io version https://hub.docker.com/r/linuxserver/jackett)

**Jackett Version**: 3.1.7 

**Last Working Jackett Version**: 3.1.7 

**Are you using a proxy or VPN?** no

### Description

* Add indexer: YGGtorrent, with yggtorrent.si as domain.
* Click Test, yield `An error occured while testing this indexer`

I would expect the test to pass and the indexer to work.

My credentials are correct and I can login into YGGtorrent.

### Logged Error Messages

[jackett-yggtorrent.log](https://github.com/Jackett/Jackett/files/5096789/jackett-yggtorrent.log)

**Comment by garfield69** [comment]
The issue is that you are using the wrong domain, and are getting an http **404 not found** error.
- Access your Jackett dashboard and edit your YGGtorrent config with the wrench icon button.
- Update the **site link** to `https://www.yggtorrent.si/` 
- And the **search and download url** to `www2.yggtorrent.si` 
- And click **OKAY**
- If you get an error click **CLOSE**, and edit and repeat. 
It should save the second time.

BTW, the Jackett version is at the bottom of the Jackett Dashboard. We have never released a version 3.1.7. 
The current latest Jackett version is 0.16.1018 ;-)

**Comment by TheoBrigitte** [comment]
It worked, thanks you.

You're right my Jackett version is 0.16.1018.0 ;)

Thanks you for this amazing software btw!
