### ISSUE TITLE
Virus alert on Kaspersky starting from version v0.16.427

### ISSUE THREAD

**Issue by AvtomatAK** [Jackett/Jackett#9377]
### Environment

**OS**: Windows 7 x64

**.Net Runtime**: .NET Framework 4.8

**Jackett Version**: v0.16.1023

**Last Working Jackett Version**: v0.16.373

**Are you using a proxy or VPN?** no

### Description
Starting from yesterday Kaspersky Internet Security (latest version) started to fire alarms on Jackett Console and Jackett Updater
that there is a trojan virus VHO:Trojan.Win32.Sdum.gen.
I thought that this was a false-positive alarm and added it to exclusions. Then today computer start generating errors with different system dlls of wrong versions and started rebooting on its own - apparently a virus activity. I tried to restore the whole system with Acronis True Image to a version 3 days ago - situation after reboot repeated. Then I tried to restore the system again but I renamed Jackett folder so that it wouldn't autostart and then system started properly after restore and reboot without any issues. So apparently virus is only in these two files and it did not affect system files before today.
Then I checked binary files of different releases by downloading them and checking if they generate a virus alarm or not. Results are below:
Date - Result
.....
2405 - Infected
1605 - Infected
1305 - Infected (v0.16.427)
1205 - OK (v0.16.373)
1005 - OK
0905 - OK
0505 - OK
0105 - OK
......

So apparently starting from version v0.16.427 from 13.05.2020 it is infected by some virus which has an activation date set to today.

Strange that on VirusTotal only Microsoft Defender gives alarm that it is Program:Win32/Wacapew.C!ml and Kaspersky doesn't generate an alarm there (maybe it is related with configuration, I have almost everything maxed: heuristics, all protection etc.).

It would be nice if someone would check the actual differences between versions 0.16.373 and 0.16.427.
![Console](https://user-images.githubusercontent.com/70092189/90975228-bff74400-e532-11ea-9427-e12d21958883.png)
![Updater](https://user-images.githubusercontent.com/70092189/90975232-c84f7f00-e532-11ea-9c84-d8f825c054a3.png)

**Comment by cocokola** [comment]
I just found a pop up on my Kaspersky for Jacket installer flagging the virus as well from two days ago.  My cache had the current 16.1033, I have the app set to auto-update using update pre-release.

I have not used the computer in over 3 days, so this must have been pulled from the jacket app itself from whatever distro is used.    Upon starting, I saw this message in the log "An error occurred during the last update. If this error occurs again, you need to reinstall Jackett following the documentation. If the problem continues after reinstalling, report the issue, and attach the Jackett and Updater logs.
--"
![Jackett2](https://user-images.githubusercontent.com/9909697/91008070-274cdc80-e5a3-11ea-897b-f89593151dbf.JPG)
![Jackett1](https://user-images.githubusercontent.com/9909697/91008074-287e0980-e5a3-11ea-8bdb-ad7cf8104635.JPG)

these are the Kaspersky flags showing definitely something was wrong.  It was the console.  Do these online virus scanners you use scan zip files contained within?   

what install is pulled, the .exe, or the zip?

Can you look at history for this file ON ALL YOUR DISTROS to see the last few days of updates/changes? I bet someone uploaded this with the virus not knowing and a recompile/upload from them or someone else 'fixed' this?

Is it a false positive? in order to get this update process working with Kaspersky, I had to put in special permissions on the installer to allow it to install without scanning, figuring it would pick it anything once the final files are dropped on the HARDDRIVE.

I have them in my quarantine in Kaspersky, so I can upload the files themselves that were flagged unless that is what you already did.  When I saw Trogen.win32.s*.gen which is MORE than just the Gen error that was also flagged.   I canceled the install and pulled a fresh copy that worked fine, but this is 2 days later.

**Comment by cocokola** [comment]
Can we say with 100% confidence it was false positive?

**Comment by ilike2burnthing** [comment]
You may need to run an update for Kaspersky. These detection were resolved yesterday. I've just updated and ran a scan using KIS 2021, with heuristics set to deep, on the last 10 releases, binaries .zip and installer .exe, plus the release for a few hours from now, and got zero detections from just shy of 30k objects scanned.

Definitely false positives.

**Comment by Spandexman18** [comment]
Hey just saw this discussion and while I'm a noob ,Windows defender detected 2 seperate instances of Trojan during 2 different scans at different times. I have attached the screenshots but please do let me know if further information is required
![threat1](https://user-images.githubusercontent.com/70193446/91136361-ebf9fd00-e6cb-11ea-8a40-24f60a107703.png)

![threat2](https://user-images.githubusercontent.com/70193446/91136404-ee5c5700-e6cb-11ea-9a0c-d1c6bde256d1.png)

**Comment by lucknaumann** [comment]
FWIW: I've had Kaspersky flag this as a Trojan before and recently, in fact. Usually, it does this when I update via the web GUI and then I have to download the .exe to install, which it never has an issue with. I didn't report this when it happened the other day (as I never have) because I ignore it, perhaps foolishly. I just don't think it's ever actually a trojan with Jackett. Anyway, Kasperky recently updated to version 20.0.14.1085(k) and I haven't had it flag this since, as often happens.

**Comment by ilike2burnthing** [comment]
@Spandexman18 seems like Defender's machine learning needs a little more education, more false positives :/ 

1023 .zip - https://www.virustotal.com/gui/file/e802968e6450e0d5c65efef5a84af953b07a9cd5a3623c1e1652a9e5273323bf/detection
1038 .zip - https://www.virustotal.com/gui/file/20e26bbbe8a5c083d15d37f0033413791be4b8aab22f3e2237c719f2b4546f78/detection

We'll have to wait to hear back from @ngosang as to why this may be happening.

@lucknaumann don't worry, it's definitely a false positive.

**Comment by lucknaumann** [comment]
@ilike2burnthing Yeah, as I said, that's what I always figure when this happens. Haven't gotten a Trojan from Jackett yet. 😃 Thanks for the response.
