### ISSUE TITLE
Ethor.net (Thor's Land) blank name in result

### ISSUE THREAD

**Issue by maxcore** [Jackett/Jackett#9389]
Use last version on docker unraid
thats normal ethor not show the result name ? i have the same problem in radarr no name was show in result after search.

![Annotation 2020-08-25 103204](https://user-images.githubusercontent.com/4043787/91187809-94a16000-e6be-11ea-9be1-bff8777780eb.png)

**Comment by garfield69** [comment]
The indexer is supposed to be able to extract the title. 
The indexer was recently changed to improve the title extraction by @j0nathan33 with #9346 but clearly this is not working for you.
Since I don't have an account I cannot work on this myself independently.

Can you please provide a **full enhanced** log with the debug and HTML included, by following https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket and I will take a look and see if I can amend the indexer to work correctly.

Thanks.

**Comment by maxcore** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/5126067/log.txt)

**Comment by garfield69** [comment]
please access your Jackett dashboard and scroll to the bottom and report your Jackett version. Thanks.

**Comment by maxcore** [comment]
@garfield69  i just update the docker and now was fix .. sorry about thats ! 
Jackett Version 0.16.1037.0

i close the issus

**Comment by pipopop** [comment]
Ethor is dead : https://torrentfreak.com/new-mpa-subpoena-targets-private-bittorrent-tracker-locally-significant-pirate-sites-201121/
last paragraph
