### ISSUE TITLE
Raspberry pi 3 (Raspbian) : Use Jackett over the internet? 

### ISSUE THREAD

**Issue by chicungunya** [Jackett/Jackett#9402]
Hi guys,
I use Jackett on a raspberry Pi (raspbian) which is working locally.
I would like to use Jackett over the Internet for a friend with my wan IP, is that possible ?

I opened my port 9117 on my router and add my Jackett local ip but when I put my external adress:9117 on my browser, it's not working

Thanks a lot

**Comment by garfield69** [comment]
access your Jackett dashboard and scroll down to the **external access** check box. Tick the box and click on the **apply server settings** button.

**Comment by chicungunya** [comment]
> access your Jackett dashboard and scroll down to the **external access** check box. Tick the box and click on the **apply server settings** button.

Thanks for your reply but it's already configured like this

**Comment by garfield69** [comment]
works for me, so the issue is most likely a security app blocking access.
check your firewall settings, router settings to ensure port 9117 is open to the WAN and that nothing is blocking incoming traffic on that port.

**Comment by chicungunya** [comment]
Do i need to set a static ip on my raspberry pi? Is it a mandatory ?

**Comment by garfield69** [comment]
I do not know. I don't have a rasp.

on my windows10 I just set up a firewall rule to allow any app to respond to traffic on incoming port 9117.
on my router I opened 9117 to the wan.
and on my Jackett I use the default settings with the *allow external access* switched on.

from my browser I can access the dashboard locally with `http://127.0.0.1:9117/UI/Dashboard`, `http://localhost:9117/UI/Dashboard`, with my LAN ip `http://192.168.xxx.xxx:9117/UI/Dashboard` and externally with my WAN ip `http://xxx.xxx.xxx.xxx:9117/UI/Dashboard'
@ngosang  @cadatoiva  any info you can add to this from non windows perspective?

**Comment by chicungunya** [comment]
All right,
Thank you for your explanation but everything is working except with the WAN.
I'll wait the answer of @ngosang  and @cadatoiva

**Comment by chicungunya** [comment]
@garfield69  can you please reopen the issue ? 
Thanks

**Comment by dracossan** [comment]
Working fine on PI:

 Jackett Version 0.16.1045.0 


> cat /proc/device-tree/model
`Raspberry Pi 4 Model B Rev 1.1`

> uname -a
`Linux raspsvr 5.4.0-1015-raspi #15-Ubuntu SMP Fri Jul 10 05:34:24 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux`

> cat /etc/debian_version 
`bullseye/sid`

>netstat -an | grep LISTEN | grep 9117
`tcp6       0      0 :::9117                 :::*                    LISTEN`

Optional, can disable the PI firewall, or make the correct rules. For testing purpose, just disable it
>ufw disable
`Firewall stopped and disabled on system startup`

>ufw status
`Status: inactive`

> netstat --all --program | grep '9117'
`tcp6       0      0 [::]:9117               [::]:*                  LISTEN      1468908/jackett`
`tcp6       0      0 [::]:9117               94.108.56.119.unk:52150 ESTABLISHED 1468908/jackett   # Connected from Public IP`
`tcp6       0      0 [::]:9117               94.108.56.119.unk:52158 ESTABLISHED 1468908/jackett   # Connected from Public IP`

Can access from outside. Just ensure your PI have a fixed IP, and your forwarded port opening from your router/firewall is correct.

**Comment by dracossan** [comment]
check if your  port is open from outisde:
https://www.canyouseeme.org/

**Comment by dairefagan** [comment]
Can you please tell me how does your Rpi manage receiving multiple queries at the same time?

**Comment by dracossan** [comment]
A single request on the jackett web client direct returning ~1000 entries take between 5 to 10 seconds max with ~ 25 indexers
with some scripting i simulated 10 concurrent request (from another PI 3 btw ) , with different keyword, return each around 1000 entries, so 10 000 entries in total, and i didn't notice any issue in term of performance, no timeout, considering both client and server are PI ... which for my own usage, is more than enough ... :) (as long as the indexers website itself answer fast). from my own experience, on PI you need to reduce to min all file IO which take forever.I use the standard debian  distrib, but custom all log writing to the minimum possible, and don't write/read anything from an USB or MMC if not really needed.

Now for your issue on timeout, i will probably investigate on the client request/protocol/stack first, rather than Jacket itself. maybe some debug and sniffing will help you to find where the timeout come from ...

**Comment by chicungunya** [comment]
> check if your port is open from outside:
> https://www.canyouseeme.org/
> 
> Some Services Provider can block some port...

Error: I could not see your service on 66.158.153.153 on port (9117)
Reason: Connection timed out 

I opened it on my router but I think my ISP blocks it ...

**Comment by chicungunya** [comment]
> check if your port is open from outside:
> https://www.canyouseeme.org/
> 
> Some Services Provider can block some port...

Error: I could not see your service on XX.XX.XX.XX on port (9117)
Reason: Connection timed out

I opened it on my router but I think my ISP blocks it ...

**Comment by ngosang** [comment]
Sorry for the late response. I let some lines for future users. Yes it's possible to expose Jackett service from home using a RaspberryPi, NAS, PC...
1. **WAN/External IP** You need a public static IP provided by your ISP. If that is not possible you should use a https://en.wikipedia.org/wiki/Dynamic_DNS I recommend you to use https://www.duckdns.org/ In few words, you create a DNS domain and you run a script/software in your RaspberryPi that changes the DNS IP when your home IP changes. Users must use the DNS domain instead of the IP. Eg http://XXXXX.duckdns.org:9117/
2. **LAN/Internal IP** Configure a static IP in your LAN for the RaspberryPi. In your router configuration => DHCP / static IPs. That IP will be used in point 3. 
3. You need to open the Jackett port in your home router. External 9117 => RaspberryPi static IP (**LAN/Internal IP**) port 9117
4. At this point you can use a online service or 3G/4G internet connection in your smartphone to test the service is available from internet. http://XXXXX.duckdns.org:9117/
5. (optional) Configure a password in Jackett
5. (optional) Configure HTTPS instead of HTTP. You need a certificate for your DNS domain. Free certificates from Let's Encrypt works well. Then you have to configure a reverse proxy using that certificate => https://github.com/Jackett/Jackett#running-jackett-behind-a-reverse-proxy

**Comment by dracossan** [comment]
7. (optional) check your local Linux Firewall (Depending of your distribution).

**Comment by chicungunya** [comment]
@ngosang 
thank you everything works except the last step.
Do you have a tuto to ssl duckdns ?
I'm trying this : https://pimylifeup.com/raspberry-pi-ssl-lets-encrypt/
But I have some errors.
Thanks

**Comment by chicungunya** [comment]
Thanks @ngosang 
All is good :)
