### ISSUE TITLE
[ilcorsaroblu] Login failed: Selector

### ISSUE THREAD

**Issue by rpalmese** [Jackett/Jackett#9419]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Pi OS 5.4

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.16.1049.0

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no] no

### Description

Fails to add indexer ilcorsaroblu

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
The indexer works for me which suggests the problem is at your end.
But to determine the reason why you are having a problem you are going to need to provide us with a **full enhanced** log with the debug and HTML included so that we can see what the site is sending you.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
