### ISSUE TITLE
[funfile] Received an invalid header line: 'pin-sha256=

### ISSUE THREAD

**Issue by d8ahazard** [Jackett/Jackett#9422]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Docker

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 
0.16.1045.0

**Last Working Jackett Version**:
Unknown

**Are you using a proxy or VPN?** [yes/no]

No

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]
Try to configure funfile indexer.

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]
See title.

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
The indexer is working for me which suggests the issue is at your end.
I suggest accessing your Jackett dashboard and using the trashbin button to delete the funfile config.
The navigate to the add-indexer and add the funfile indexer afresh, with your login credentials.
Let us know if that helps or not.
