### ISSUE TITLE
Raspberry cannot establish SSL connection

### ISSUE THREAD

**Issue by Toxaris-NL** [Jackett/Jackett#9425]
This error occurs since I updated to the latest version. Previously I was using version 0.16.630 and that was working fine. I am running on a Raspberry Pi with the latest patches applied.

I can add the whole error if required. I get the error when using any tracker, either by searching or testing. In short, the message attached.

[Jackettlog.txt](https://github.com/Jackett/Jackett/files/5151082/Jackettlog.txt)

It seems that the SSL connection cannot be established. I have OpenSSL 1.1.1g running and it was using OpenSSL before in the previous version I assume.

**Comment by ngosang** [comment]
OpenSSL 1.1.1g version is fine.
Try searching in Google about `debian update ca certificates` or `ubuntu update ca certificates`
Are you using Docker?

**Comment by DeborahCox** [comment]
I am currently facing the same issue here, most of my indexers have the error of SSL connection problem.

(The handshake failed due to an unexpected packet format.: The SSL connection could not be established, see inner exception.)

And yes, running in docker.

**Jackett Version:** 0.16.1340.0

Did an update ca-certificate inside the container, problem still.
