### ISSUE TITLE
Cannot Download from Avistaz

### ISSUE THREAD

**Issue by andrep182** [Jackett/Jackett#9433]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Ubuntu 18.04

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.16.1050.0

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no] Yes

### Description

It has been a few weeks where I cannot download torrent file from avistaz. Please see the screenshot for the log. If I understood it right, it looks like it's searching for category 2035, but it doesn't exist in the Avistaz account within Jackett.

### Logged Error Messages

![image](https://user-images.githubusercontent.com/44149762/92011862-88da1d00-ed00-11ea-874b-715fb4ffb7ba.png)

**Comment by garfield69** [comment]
I don't have an a/c on avistaz so I can't investigate. @ngosang  can help with this one, when he has time to contribute.

But the 2035 is a red herring.
The issue with the download is that there is something preventing you accessing the download link, whether that is because your download ratio is in the red, or because the Jackett indexer is broken I cannot tell.
So logon to avistaz with your browser and confirm that you are allowed to download.

With regards to the 2035 message, this is due to your Radarr avistaz indexer definition making queries with categories that are not supported by the Jackett avistaz indexer (because there is no such category at the avistaz web site).

When accessing your Radarr indexer page, enable the **advanced** switch, then edit your avistaz indexer, and update the category list to only contain `2000,2030,2040,2045` since these are the only valid cats the Jackett indexer supports for the avistaz web site.

**Comment by andrep182** [comment]
@garfield69 Thanks for the 2035 tip. I figured it's something like that, but I overlooked the category list on Radarr. I found it and deleted it.

However, the failed downloading is still a mistery. I have been forced to download from Avistaz directly and manually import the movies for the past month just because of this issue. I have no problem downloading the torrent directly.

Here's the log from Jackett in case it can be useful. It seems that it said clearance failed? Not sure what that means. When I tried testing the account on Jackett main page, it always return back a successful message.

![image](https://user-images.githubusercontent.com/44149762/92032786-84712c80-ed1f-11ea-8c24-ca35be4f4481.png)
![image](https://user-images.githubusercontent.com/44149762/92032822-8fc45800-ed1f-11ea-8e0f-2d13369c3e9d.png)

**Comment by garfield69** [comment]
Ahh.
so the Jackett indexer is discovering that the avistaz download link is no longer a **direct link** to the download.
what ever avistaz have changed in the download process it is interfering with the Jackett indexer expectation that by following the download link a file (.torrent or magnet) will be returned.
Instead, the indexer is being presented with an intermediate page (some kind of avistaz security or secondary check?) or possibly a cloudflare anti-DDoS challenge?) and Jackett cannot handle such an event.

**Comment by andrep182** [comment]
Oh man, my first thought was maybe I enabled 2FA, but that wasn't even the case... Sounds like Avistaz is doing the extra step for security, but that prevented Jackett to work huh? Curious, is there anything that could be done from Jackett side, or is it up to Avistaz to allow access for Jackett at this point?

**Comment by garfield69** [comment]
I don't know. this is c# code territory which is not my cup of tea. which is why I assigned the ticket to @ngosang 
he has an a/c on the site and is a c# dev, so best placed to investigate.

**Comment by garfield69** [comment]
related to #9257

**Comment by seeyabye** [comment]
I just tested this out, and I had no issues downloading from Avistaz.

@andrep182 What happens when you click on the Download Button on Jackett?

![Annotation 2020-09-11 233927](https://user-images.githubusercontent.com/36906720/92939069-4a72f980-f488-11ea-8134-a4789e86ead0.png)

**Comment by andrep182** [comment]
@seeyabye That's odd. So I did manual search just like you. I clicked download button, it was thinking for a bit then gave me a blank page. I then went to logs and see a similar error as before.

Are you saying that when you hit download, you were able to download the torrent file?

![IMG_20200912_174531 - Edited](https://user-images.githubusercontent.com/44149762/93007706-7fcb2600-f520-11ea-9052-1306bf23490b.jpg)


![IMG_20200912_174618](https://user-images.githubusercontent.com/44149762/93007691-3ed31180-f520-11ea-9a96-3e2672b3972c.jpg)

**Comment by seeyabye** [comment]
By the looks of it, I think AvistaZ has deployed Cloudflare protection and this could be related to https://github.com/Jackett/Jackett/issues/9029.

The only way right now to get this to work involves manually changing the cookies in your indexer's JSON file. See https://github.com/Jackett/Jackett/issues/9493 where @garfield69 mentions this.

The alternative method is to run Jackett with FlareSolverr (https://github.com/Jackett/Jackett/issues/9029).

On the side note, what happens when you visit AvistaZ.to with your proxy? Does it trigger a Cloudflare protection page that requires you to wait for a couple of seconds? On my end, I'm running Jackett locally from home, so I don't see such a page. Occasionally, I do, but most often not, which explains why I do not have the problem mentioned above.

**Comment by ngosang** [comment]
I just tested AvistaZ and it's working very well in Jackett. I can search, download, go to torrent details. All is fine.

In the tracker configuration you can read:
> You have to check 'Enable RSS Feed' in 'My Account', without this configuration the torrent download does not work.

Could you try to do that, remove the tracker from Jackett and configure it again?
