### ISSUE TITLE
Added all public trackers but some don't work 

### ISSUE THREAD

**Issue by Bearmancer** [Jackett/Jackett#9444]
### Environment

**OS**: Windows 10 Pro 2004 19041.450

**.Net Runtime**: I used this guide: https://smartdoc.zendesk.com/hc/en-us/articles/205232308-How-to-check-your-NET-Framework-version and the registry key only shows up until 4.0 so I don't have later versions.

**.Net Version**: ^^

**Jackett Version**:  v0.16.1057

**Last Working Jackett Version**: Installed it today

**Are you using a proxy or VPN?** VPN yes. Have tried without VPN too.

### Description

To enable all public trackers, I used this code on console: https://github.com/Jackett/Jackett/issues/1576
All public trackers except NewPCT (I need help as to why it won't. I tried pressing the add button but it didn't work.

However when I tried searching for a torrent (with VPN because my country bans many torrent sites), many sites were offline. The reasons are varied - they are attached in the screenshots below. The situation doesn't change without VPN.

The links for the torrent sites mentioned on the application work BTW.

### Logged Error Messages

[log.txt](https://github.com/Jackett/Jackett/files/5170153/log.txt)
[log.txt.20200903.00006.txt](https://github.com/Jackett/Jackett/files/5170168/log.txt.20200903.00006.txt)

### Screenshots
Before VPN:
![image](https://user-images.githubusercontent.com/70022442/92144895-04d58180-ee35-11ea-9b1e-f6c09337f86d.png)

After VPN:
![Post VPN](https://user-images.githubusercontent.com/70022442/92148684-8d0a5580-ee3a-11ea-81a4-96294ec21e31.jpg)

Error messages:
![image](https://user-images.githubusercontent.com/70022442/92145245-8f1de580-ee35-11ea-8795-3d5d97e73286.png)
![image](https://user-images.githubusercontent.com/70022442/92145256-93e29980-ee35-11ea-891e-c584c0a0adb5.png)
![image](https://user-images.githubusercontent.com/70022442/92145265-980eb700-ee35-11ea-8ac1-d690fb21deff.png)
![image](https://user-images.githubusercontent.com/70022442/92145280-9d6c0180-ee35-11ea-9438-4f7c120548b7.png)
![image](https://user-images.githubusercontent.com/70022442/92145319-aceb4a80-ee35-11ea-8642-27c445bc49b8.png)

**Comment by ilike2burnthing** [comment]
Click the configuration button (spanner icon) to change the link for those with that option. Others will be blocked due to their use of DDoS protection pages which can't currently be bypassed by Jackett.

Make sure you can also visit those links when using your VPN, as some sites will ban certain VPN IP addresses.

KAT is currently down.

If there are any issues not covered by those explanations, let us know.

**Comment by Bearmancer** [comment]
Why would I change the links? I said that the links in the application were correct. I will try changing my location.

**Comment by garfield69** [comment]
>Why would I change the links? I said that the links in the application were correct.

Because some torrent web sites have more than one domain, and others are supported by 3rd party unblock domains, such that you may be able to get results from the original web site by using these alternate domains.
But this is only valid for those alternate domains that are listed in the corresponding indexer's config.
