### ISSUE TITLE
[karagarga] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by yossarian82it** [Jackett/Jackett#9466]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Ubuntu-1804-bionic-64-minimal

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.16.1077.0

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no] no

### Description

Karagarga does not work.

**Comment by garfield69** [comment]
@RoloSoze  is the karagarga indexer working for you?

**Comment by RoloSoze** [comment]
@garfield69 It's working fine, yes.

**Comment by garfield69** [comment]
@yossarian82it  So it seems the issue is at your end since other users are not having any problems with this indexer.
If you want help to try determine what could be going on then you are going to need to turn on the **enhanced** log switch and repeat your test and upload the full log. Hopefully the debug and HTML included will yield some clues.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by yossarian82it** [comment]
Ok, I hope I did it well. Here's the log.
[log.txt](https://github.com/Jackett/Jackett/files/5187344/log.txt)

**Comment by garfield69** [comment]
you have hit the login limit and are getting 
`You can only try to log in 5 times in any 1 hour period. Please wait and try again.`

**Comment by garfield69** [comment]
after the hour has passed, then check that you still have the **enhanced** switch enabled (it get reset whenever Jackett is restarted or if it gets auto-updated)
and then repeat the test and we shall see if we get capture of what the real reason for the login failure may be.

**Comment by yossarian82it** [comment]
still no luck
[log.txt](https://github.com/Jackett/Jackett/files/5188163/log.txt)
