### ISSUE TITLE
[enhancement] "Replace MULTI by another language in release name" for all french indexers

### ISSUE THREAD

**Issue by tchirou** [Jackett/Jackett#9544]
Hi
Would it be possible to consider adding "Replace MULTI by another language in release name" to the Sharewood indexer and if possible all french indexers. This option currently exists for yggtorrent and yggcookie

![image](https://user-images.githubusercontent.com/6749420/93454709-a354ee80-f8db-11ea-858b-2db53c0858d0.png)

Many thanks

**Comment by garfield69** [comment]
Can do.
However, since each change has to be customised for each individual indexer, as not all web sites present the information in the same way, I can only make this change for French indexers at which I have access, which is to say, **public**, **semi-private**, and **only private that I have accounts at**.
I'll add to this ticket each indexer that I manage to enhance, and it there are any left that you want altered then you will need to assist. More on that last part after I do the ones I can access.

**Comment by tchirou** [comment]
Great !
To be honest, personally, I only know about sharewood having a lot of multi besides yggtorrent. I thought it would be easier to add to all French indexers, so I guess the ones you can do will be enough until someone make a request 
Thanks a lot

**Comment by garfield69** [comment]
@vlevas I would like to add enhancement #9544 and #9456 to the HD-Forever indexer,  but I don't have an account on the site.
If you would like to help please post a html dump of the HD-F **torrent search** page using https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source
Thanks.

**Comment by garfield69** [comment]
@pipopop  I would like to add enhancement #9544 and #9456 to theLeSaloon indexer, but I don't have an account on the site.
If you would like to help please post a html dump of the LeSaloon torrent search page using https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source
Thanks.

**Comment by pipopop** [comment]
You have this account on LeSaloon : garfield1969 | garfield69@outlook.com. If I can I will send you the html source this afternoon or tomorrow morning.

**Comment by pipopop** [comment]
[LeSaloonSearch.txt](https://github.com/Jackett/Jackett/files/5251307/LeSaloonSearch.txt)
Can you please remove it when it will be possible ?

**Comment by garfield69** [comment]
>You have this account on LeSaloon : garfield1969

that account is disabled.

The HTML source you sent should get the job done. 
Thanks.

**Comment by pipopop** [comment]
Ok. I forgot to remove personal information. If you have it, it's ok. Otherwise I can send you another one without personal information.
Thanks!

**Comment by garfield69** [comment]
all done, thanks.

**Comment by foXaCe** [comment]
hello,
it possible to update please ?
https://hd-only.org/  ---- I don't have an invitation
https://hdf.world/    --- (hd-forever)  I can send you an invitation if needed

**Comment by garfield69** [comment]
@foXaCe  none of the team have an account for hd-only, which also happens to a gazelle based site whose indexer is written in C#. We will need a C# dev to volunteer.

as for hd-f, If you send an invite to garfieldsixtynine -at- gmail.com I can add the multi support.

**Comment by foXaCe** [comment]
Because the user limit has been reached, you cannot send invitations at this time.

shit

**Comment by garfield69** [comment]
@foXaCe wrote:
>The two sites [hd-f and hd-only] have the same structure, can it be enough to modify the links www.

Not sure I understand what you are saying/asking. 
The indexer for hd-only is written in C# and the one for hd-f is written in yaml
I support yaml ,and don't make changes to C# unless they are extremely simple changes, I am not a C# developer.
They may look the same using a browser (I would not know since I don't have access to either) but behind the scenes they must be quite different or I would have expected that they would both be written in yaml or both in C#.

>I can lend you but identifier if necessary, I will change the password once you finish  

Sure. If you want to PM temporary credentials to access your HD-F account while I update and test the indexer, that's fine by me.
Once I'm done you can change your a/c password to establish private access once again.

**Comment by garfield69** [comment]
@foXaCe yes, I'm done.

**Comment by foXaCe** [comment]
in radarr it gives zero result
did I omit something?
hd-f and hd only same problem
Categories 2000

log radarr for all movie
2020-10-12 18:46:33.9|Info|DownloadDecisionMaker|No results found

**Comment by OnigamiSama** [comment]
Hello.

I don't know if it's the right place or if i should have open e new issue for this but with Sharewood the parameter "Replace MULTI by another language in release name" do not seems to work.

I have set it to to replace MULTI with FRENCH in Jackett, but Sonarr keep telling me the language is ENGLISH and the ENGLISH is not allowed in profile FRENCH.

I might just do something wrong here but I can't figure it out.

**Comment by JigSawFr** [comment]
Just for my knowledge, why is this necessary ?

As you have some options on indexer in radarr/sonnarr as:

![image](https://user-images.githubusercontent.com/5781907/116892869-9bf71100-ac30-11eb-8c22-5a90534de1fb.png)

**Comment by tchirou** [comment]
Just in radarr, but not in sonarr unfortunately.

**Comment by JigSawFr** [comment]
> Just in radarr, but not in sonarr unfortunately.

Correct, thank you

**Comment by neoestremi** [comment]
It seems that it is case sensitive.
<img width="113" alt="MULTi" src="https://user-images.githubusercontent.com/1340877/193789478-1fa416b9-88b0-4e5f-9448-767cf04ec0de.png">
The top one is from Abnormal and the bottom one is from YGGtorrent, both files have "MULTi" but YGG indexes everything with full uppercase, not Abnormal, is it possible to make it case insensitive ?
I can open a new issue if needed.

**Comment by ilike2burnthing** [comment]
It's not case sensitive, however it was fixed in https://github.com/Jackett/Jackett/commit/a54f574527947a39830406406411ad36ba063b7f, available in [v0.20.2034](https://github.com/Jackett/Jackett/releases/tag/v0.20.2034). Update to resolve your issue.

All indexers have now been updated, so closing this issue.
