### ISSUE TITLE
[Xthor] tracker modification

### ISSUE THREAD

**Issue by pipopop** [Jackett/Jackett#9547]
Hello,
When we click on a link in manual search, it goes the old address (xthor.to). I think this modifications can resolve the problem:
In [Xthor.cs](https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/Xthor.cs):
Line 30: replace **https://xthor.to** by **https://xthor.tk**
remove line 30: **"https://xthor.bz/",**

P.S. : no problem for download link or with automated search and download.
Thanks for all,
Pipopop

**Comment by garfield69** [comment]
The xthor indexer had its domains all changed to *.tk starting with version  0.12.847 576efcccccd9127dc99c182f3d446cb17e3bb931 21 Oct 2019

The lines of code you are referring to
https://github.com/Jackett/Jackett/blob/d44a078cebecb07d271bcda1de3dce09f82e3504/src/Jackett.Common/Indexers/Xthor.cs#L28-L31
are the legacylinks which allows the indexer to automatically replace the sitelink with the current link
https://github.com/Jackett/Jackett/blob/d44a078cebecb07d271bcda1de3dce09f82e3504/src/Jackett.Common/Indexers/Xthor.cs#L47
when any configs have the old sitelinks defined.

please expand on your description of the problem. which link are you talking about in manual search?
are you referring to clicking on the titles in the name column which should would usually take you to the torrent details page for that torrent?

note that the data the indexer is using comes from the API xthor provides rather than the web site browser page.
https://github.com/Jackett/Jackett/blob/d44a078cebecb07d271bcda1de3dce09f82e3504/src/Jackett.Common/Indexers/Xthor.cs#L26

**Comment by pipopop** [comment]
Sorry, you were right. I hadn't changed the xthor.to link in the tracker settings.
I close this issue.
Thanks for all.
