### ISSUE TITLE
Add UI tool for sampling generation definitions

### ISSUE THREAD

**Issue by T-REX-XP** [Jackett/Jackett#955]
Could you please provide opportunity to generate definitions(Cardigans) for new trackers using some tool. It will be very useful for user. Thanks

**Comment by kaso17** [comment]
All you need is a texteditor and web browser + some experience with css selectors.

**Comment by armani316** [comment]
@T-REX-XP Could you please provide more details on this suggestion?

**Comment by zductiv** [comment]
Perhaps a guided tool that will prompt the user to copy / paste from the developer tab and from the url bar, so that even if @kaso17 , or other indexer contributors don't have access to the site without an invite, that the definition can still be developed. The output would get posted to the indexer request.

**Comment by kaso17** [comment]
Properly testing everything without access would be very hard. I personally wound't add an indexer to which I don't have access.

**Comment by garfield69** [comment]
Closing as stale.
