### ISSUE TITLE
cpasbien.to : add french if no language mentionned

### ISSUE THREAD

**Issue by kornflex** [Jackett/Jackett#9553]
Hello,

cpasbien.to is a french indexer.
With radarr, if found this title :

Maleficent 2014 1080p BluRay x264 DTS-HD MA 7.1-RARBG

There is no language mentionned, so Radarr declares : French wanted, but english found.

Is it possible to add "FRENCH" if no language mentionned ?

I think this can be used for all other french indexers.

Thank you

**Comment by garfield69** [comment]
I am not sure that this is practical.
Titles that do not specifically have a French label are usually English by default, or in some cases Multi, such as that title you mentioned `Maleficent 2014 1080p BluRay x264 DTS-HD MA 7.1-RARBG` which happens to have 4 audio tracks, DTS7.1 English, DTS5.1 French, DD5.1 Russian and DD5.1 Kazakh.

But the problem is that this indexer is written in yaml, and searching for the presence of multiple labels in a title (English, French, Spanish, Multi, TrueFrench, Vostfr, Russian, etc etc) as well as ignoring case sensitivity, and if none present append French to the title,  is not something that the yaml processor can manage.

What you ask would best be implemented by rewriting the indexer in C# where obviously you can do pretty much anything.
But there is no interest from any volunteer to write C# indexers, check out  the long list of indexers requested that need to be coded in C# https://github.com/Jackett/Jackett/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+C%23%22+title%3A%22%5Breq%5D%22
