### ISSUE TITLE
[nebulance]  (Config)

### ISSUE THREAD

**Issue by Bansantion** [Jackett/Jackett#9571]
**Jackett Version**: 0.16.1260.0

### Description

after looking up the error i understand its the cookies but where is the Jackett indexer config cookie box? i dont understand where to find this to paste in new cookies

### Logged Error Messages

An error occurred while updating this indexer

**Comment by Bansantion** [comment]
because i cant find an explanation for where the Jackett indexer config cookie box is

**Comment by ilike2burnthing** [comment]
Click the configuration button, the spanner icon

**Comment by Bansantion** [comment]
https://ptpimg.me/x6zzy6.png

there is no cookie option there

**Comment by ilike2burnthing** [comment]
Oh sorry, I should have checked.

Ensure your details are correct and that you can access your account in browser from the same device and IP. Make sure your account is in good standing and that there are no unread messages.

If all that checks out, it may be related to #9563 #9568 #9569

**Comment by garfield69** [comment]
The nebulance indexer works for me, which suggests the issue is at your end.

If the indexer detects that the standard login page can be used, then it presents the username/password config.
If however something prevents that login page being used (such as a captcha or some DDoS protection), then the config asks for a cookie instead.

It may be that when you previously had the nebulance indexer working, you had set it up when a cookie was required.
Now that this is not required, you have to edit your config and enter you username and password because the config may not have ever saved those details before.

Or it may be that you had username/password saved, but while using the cookie you at some point changed the password on your site, and now that the indexer is asking for username/password again, the old password in the config needs updating.

**Comment by Bansantion** [comment]
![sss](https://user-images.githubusercontent.com/71607370/93722198-0ad09f80-fb63-11ea-9da0-a5036d40fe89.png)

i never used cookie before i was just asking cause that's what my research showed as the fix

**Comment by ilike2burnthing** [comment]
Tried deleting the indexer, restarting Jackett, and adding again?

**Comment by garfield69** [comment]
in which case it may well be related to the webclient changes yesterday, as this has made direct changes to the nebulance indexer.
what flavour of Jackett are you using (LinuxAMDx64, LinuxARM32, .LinuxARM64, macOS, Mono, Windows) ?

**Comment by Bansantion** [comment]
cant delete whats not entered

i've used 2 different ones in an attempt to get it to work 1'st i have dedi seedbox with jacket installed directly into that got same error

then i tried installing jackett to windows and that way with same error

**Comment by ilike2burnthing** [comment]
Try the last release - https://github.com/Jackett/Jackett/releases/tag/v0.16.1252

**Comment by Bansantion** [comment]
the latest release is 0.16.1260.0 which i have

**Comment by ilike2burnthing** [comment]
Which, as mentioned earlier, likely is the cause of the issue. Try that earlier build, it doesn't have the same problem.

**Comment by garfield69** [comment]
install from https://github.com/Jackett/Jackett/releases/tag/v0.16.1252
and if it works then, while the problem is worked on, use the Jackett dashboard to tick the **disable auto updates** and click the **apply server settings** to prevent issue.

**Comment by Bansantion** [comment]
Ty that allowed me to add indexer to jackett

**Comment by garfield69** [comment]
re-opening ticket so that we can track when the fix is applied, and notify you when you can update to the latest Jackett again, and turn on the auto-update switch again.

**Comment by ngosang** [comment]
@Bansantion are you using .NetCore or Mono version? Tell us the Mono version too.

**Comment by garfield69** [comment]
@Bansantion  try out Jackett 0.16.1269 and report back. Thanks.

**Comment by ngosang** [comment]
Nebulance is working fine for me in the latest release.
