### ISSUE TITLE
[TorrentDownloads] Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#9595]
currently keywordless seaches on TorrentDownloads is returning
`System.Exception: Found no results while trying to browse this tracker`

The indexer uses the today link to fetch the latest torrents when a keywordless search is performed
 https://www.torrentdownloads.info/today/?search=
however currently the site is not returning anything
![image](https://user-images.githubusercontent.com/6933240/93853460-02fe3000-fd08-11ea-897c-54fa4a04bbef.png)

if the site does not fix this then at some point we may need to look at doing an alternate search such as using the .Today.Year for instance.

**Comment by ilike2burnthing** [comment]
Yea, I noticed that yesterday and figured it was because it was only a few minutes past midnight, and they were being very literal about 'today'. It didn't get resolved until around 10pm, and then broke again.

There are results up now, so I'm hoping it's a temporary issue, and they're ironing out the kinks.

Their */yesterday/ page doesn't seem to have the same problem, but obviously you've then got a 24hr delay.

The homepage displays recent torrents for each category, and works in Jackett (just tested), so that's always an option.

**Comment by garfield69** [comment]
seems to have been a site glitch. 
working fine just now, so I'll close.

**Comment by ilike2burnthing** [comment]
https://www.torrentdownloads.info/today/?search= - no torrents

**Comment by garfield69** [comment]
its a repeat of https://github.com/Jackett/Jackett/issues/9595#issue-706138585

**Comment by ilike2burnthing** [comment]
Oh I know, just gonna see if it gets resolved this time, or ends up being a recurring issue

**Comment by ilike2burnthing** [comment]
Populated with torrents again, but I'll leave this open for another day and keep an eye on it.

**Comment by garfield69** [comment]
https://www.torrentdownloads.me/search/ returning 
```
This page isn’t working
www.torrentdownloads.me is currently unable to handle this request.
HTTP ERROR 500
```
the latest page https://www.torrentdownloads.me/today/?search=
works but the search engine is broken
https://www.torrentdownloads.me/search/?search=mandalorian

**Comment by ilike2burnthing** [comment]
back up
