### ISSUE TITLE
Questions regarding Jackett with (synology DSM6)

### ISSUE THREAD

**Issue by Antonell333** [Jackett/Jackett#960]
hi,
i have installed mono & jackett, both running fine, configured 2 indexers using the dashboard. i have 2 questions:
1) can i configure DSM's download station to use jackett queries results (i mean without having to go through the jackett dashboard and a different torrent client)? if so, how?
2) can i get synodroid phone app to use jacket queries result?

thanks

**Comment by kaso17** [comment]
this is one for @Dr-Bean :)

**Comment by Dr-Bean** [comment]
Not sure I can answer this one though ;) I actually don't use Jackett myself...with only private indexers, can't set up a testenv, and I don't use DownloadStation either. With that, here's some input:
1) Assuming Jackett outputs RSS feeds in a format that Download Station understands, you should be able to add those feeds to Download Station. Otherwise:
2) Download Station has an API to do various things ([documentation](http://usdl.synology.com/download/Document/DeveloperGuide/Synology_Download_Station_Web_API.pdf)).
This means that an interface between Jackett and DownloadStation can be created. This interface can presumably be added to some sort of application to translate Jackett's output into a DS task, be that Synodroid or some other middleware. I don't believe that interface exists atm.

**Comment by armani316** [comment]
@Antonell333 Did @Dr-Bean's response answer your questions? If so, can we close this issue?

**Comment by kaso17** [comment]
Based on the answers.
1.) Yes you should be able to use the torznab feeds (they are extended RSS feeds).
2.) No idea what the synodroid app does
