### ISSUE TITLE
TorrentBD Site update

### ISSUE THREAD

**Issue by ahsan540** [Jackett/Jackett#9682]
### Environment

**OS**:
Windows 10

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]
unknown

**.Net Version**:
unknown

**Jackett Version**:
0.16.1252.0

**Last Working Jackett Version**:
(actually the site was updated few days ago, it was used to run nicely before that)

**Are you using a proxy or VPN?** [no]

### Description
https://www.torrentbd.net/ was updated few days ago, after that jackett stopped working with it. At last update they had updated their login ways. Can you guys check it out?

### Screenshots

<a href="https://ibb.co/2qjW5p6"><img src="https://i.ibb.co/WncGsR3/image.png" alt="image" border="0"></a>

**Comment by garfield69** [comment]
The TorrentBD indexer is working for me so this suggests the issue is at your end.
You do know that cookies expire and need to be replace from time to time?

Have you accessed the TorrentBD web site  from a browser running on the same machine as Jackett, logged in to the web site, navigated to the torrent search page, and then fetched the cookie as described in the Jackett TorrentBD indexer config?

**Comment by ahsan540** [comment]
actually i did. I did try to use new cookie but it didnt work
I have reset my windows last night, will setup the whole thing this night.. ill give an update after that

**Comment by garfield69** [comment]
and you have a good ratio, have read all outstanding notices, alerts and PM, anything that might prevent you accessing the torren search page just after login?

**Comment by ahsan540** [comment]
![image](https://user-images.githubusercontent.com/72017607/94658621-da3bf300-0324-11eb-94fd-6b8b8f7077c3.png)
yes i do have an good ratio and im not blocked by any cause :( 
I could easilu access in my home page and search for anything

**Comment by garfield69** [comment]
ok, well, lets see if the **enhanced** log with the debug and HTML yields something useful.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
Thanks.

**Comment by RoloSoze** [comment]
@ahsan540 What changes were made? I'm unable to login even via the browser. When I try to log in, nothing happens. I don't get a message; the login page stays as it is, and the Login button becomes unclickable. Tried a couple of different browsers - same behavior.

**Comment by garfield69** [comment]
@RoloSoze  try clearing the browser cookies using the Browser **view site information** icon on the left of the address bar when you are on the torrentbd site. Click on **cookies** and then use the **remove** button to delete each group.
I don't have issued accessing https://www.torrentbd.net/account-login.php and once I've logged on and access the torrent search page, I can use the cookie to update the indexer without issue.

**Comment by ahsan540** [comment]
https://pastebin.com/fxpXBqnQ
here's the full log, 
I can see protected by captcha while logging in at the log in page, they've added 2fa feature and some new things

**Comment by garfield69** [comment]
@ahsan540 the log shows that your Jackett indexer is trying to access https://www.torrentbd.net/ which is returning 301 Moved Permanently
In your original post stated that you were on Jackett 0.16.1252 but the log shows that you are actually still on Jackett 0.16.1163
Which is a problem because the torrentBD indexer was updated starting with Jackett 0.16.1269 to handle the changes to the site.

so upgrade your Jackett to the latest version (currently 0.16.1451 at the time of this post) and you should be good to go.

**Comment by RoloSoze** [comment]
@garfield69 Clearing cookies did not fix it, but clicking on the URL you provided https://www.torrentbd.net/account-login.php did!

I reconfigured it & it works fine for me!

**Comment by ahsan540** [comment]
actually it worked! there must've been something wrong with 0.16.1252.0 and 0.16.1163 for the new site? :/ 
or it might be some bug from my side who knows.. 

and about the version mismatch, i originally downloaded 0.16.1163 installer at the beginning. After giving a windows reset (which i gave after making this thread), I installed from the old installer thinking it would auto check and download updates itself? :/ It was my fault that I didnt give it a second check :_D
