### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Login failed: No form found on https://www2.yggtorrent.si/ using form selector 

### ISSUE THREAD

**Issue by zeppelinlg** [Jackett/Jackett#9700]
There is an error with yggtorrent on the last jackett version with the docker of linuxserver

**Comment by garfield69** [comment]
the yggtorrent indexer works for me which suggests the problem is at your end.
edit the yggtorrent config and update the sitelink to `https://www.yggtorrent.si/` and the search link to `www2.yggtorrent.si` and click OKAY.
if you get an error, click CLOSE and edit and save again. it should work the second time.
