### ISSUE TITLE
[1337x] Exception (1337x): certificate validation failed: [Subject]  CN=1337x.to[Issuer]  CN=

### ISSUE THREAD

**Issue by Pensondiofe** [Jackett/Jackett#9715]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
the cert that the https://1337x.to/ site is using is valid, so you need to update your certificate store because it is out of date.
either that, or you are being blocked  by your ISP or security app or vpn service, and being presented with an invalid cert.
since you have not provided any of the info requested in the first post its difficult to help further.
