### ISSUE TITLE
[epublibre] The SSL connection could not be established, see inner exception.: Unable to read data from the transport connection: Connection reset by peer. (Config)

### ISSUE THREAD

**Issue by pkreuzt** [Jackett/Jackett#9737]
### Environment

**OS**: Raspbian armv7l

**.Net Runtime**: Mono

**.Net Version**: 5.18.0.240

**Jackett Version**: 0.16.1549.0

**Are you using a proxy or VPN?** [yes/no]: no

### Description

Adding EpubLibre tracker fails with this error:

`The SSL connection could not be established, see inner exception.: Unable to read data from the transport connection: Connection reset by peer.`

### Logged Error Messages

[jackett.log](https://github.com/Jackett/Jackett/files/5322912/jackett.log)

### Screenshots

![Captura de pantalla_2020-10-04_11-25-34](https://user-images.githubusercontent.com/6936840/95011882-5b043300-0634-11eb-95c5-527b86e1069e.png)

**Comment by garfield69** [comment]
the indexer is working for me which suggests the problem is at your end.
it is likely that something is blocking your access to the site, either a security app, or ISP or something.
we may get more info is you enable the **enhanced** log and provide the debug and HTML
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by pkreuzt** [comment]
You're right. I usually browse the web with torbrowser and noticed no problem accesing the site, but with an unproxied browser it returns 404. Made a quick search and it seems some ISPs in Spain have blocked access to this site recently because of a court order. It doesn't have alternative domains, so I'll have to configure some proxy to get through.

Closing the issue, thanks!
