### ISSUE TITLE
[Spirit of Revolution] Finds the right results in Jackett but not in Radarr

### ISSUE THREAD

**Issue by Winblackka** [Jackett/Jackett#9752]
Jackett Version  0.16.1583.0 (Docker)

Hello,

if im looking for a movie like "joker" in radarr, every indexer im using is finding the correct movie, except for the spirit of revolution tracker, this one is only giving me the latest 10 movies  that were uploaded to the tracker  as a result. 

I have used the right category, that one that was used in Jackett to find the right movie. The manually jackett search works perfect, the manually radarr search not. 

Alle indexers are setup in the same way.

If this is not the right place, to post the issue, im sorry.

**Comment by garfield69** [comment]
No one of the team has an account on SoR so we cannot investigate independently for you.

The best way forward is for you to set up a test so that the Jackett logs capture first a jackett-dashboard search for **joker** using only the SoR indexer, and then after uploading that log, doing a Radarr search for jackett using ONLY the Radarr SoR indexer that you have set up to pull off the Jackett SoR indexer. (do not use the Aggregate indexer as that will generate far too much output), and uploading that log here so we can compare.

To enable the **full enhanced** logs on Jackett see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by Winblackka** [comment]
Okay, i will do that. I can send you an invite if it's easier for you.

**Comment by garfield69** [comment]
> I can send you an invite if it's easier for you

I have an account but it is disabled, probably due to inactivity. With over 200 accounts that I have built over the time I've maintain Jackett indexers, there is not enough time in the day to keep all the varied sites happy with whatever rules they enforce, and I only really use the a/c for maintaining Jackett indexers, not to actually contribute to the sites with UL or DL or chats or donations.

**Comment by Winblackka** [comment]
> No one of the team has an account on SoR so we cannot investigate independently for you.
> 
> The best way forward is for you to set up a test so that the Jackett logs capture first a jackett-dashboard search for **joker** using only the SoR indexer, and then after uploading that log, doing a Radarr search for jackett using ONLY the Radarr SoR indexer that you have set up to pull off the Jackett SoR indexer. (do not use the Aggregate indexer as that will generate far too much output), and uploading that log here so we can compare.
> 
> To enable the **full enhanced** logs on Jackett see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

Here are the logs:
[log_jackett.txt](https://github.com/Jackett/Jackett/files/5332608/log_jackett.txt)
[log_radarr.txt](https://github.com/Jackett/Jackett/files/5332609/log_radarr.txt)

I hope that will help, thank you!

**Comment by garfield69** [comment]
First off, thank you for a job well done with the logs, they were very useful.

Second, to recap, when I first set up this indexer for you back in March 2020, the SoR web site had a search option that included using the **IMDBid** as a search parm, by selecting **blah=4** in its search query parms.

What you may not have realised is that the version of Radarr you are using will search for a movie using the **IMDBid** search query if the indexer reports that this option is available
.
So when you we comparing results from a manual Jackett dashboard, you were not actually comparing the same search methods with Radarr. To see what Jackett is returning to Radarr for **Joker**, you would need to use the Jackett dashboard manual search with SoR indexer using the search term **tt7286456** 

And finally, the cause of the problem. It seems that recently the SoR website changed the IMDBid search option to **blah=3**, and that is why the Radarr search is not returning expected results.

So I will update the indexer to use **blah=3** instead of _blah=4_. The update should be available in the next release of Jackett due out in about 11 or12 hours from the time of this post.

**Comment by Winblackka** [comment]
Thank you so much!

You always friendly, informative and super fast.
SoR is a small Tracker and there are not many users that are using Jackett, but you treat us like a big one.

Fantastic work, thanks again!

**Comment by garfield69** [comment]
Jackett 0.16.1621
