### ISSUE TITLE
[Monova] Returning removed torrents 

### ISSUE THREAD

**Issue by Dark-Yox** [Jackett/Jackett#9784]
### Environment

**OS**: Windows 10 (64-bit) 2004

**.Net Runtime**: .Net-Framework

**.Net Version**: 4.8

**Jackett Version**: 0.16.1635

**Are you using a proxy or VPN?** No

### Description

Search for "Pialoof" then try downloading "Pialoof -​ Mika Ito (Bible Black).​zip" and you will get a 404 error 
This 127.0.0.1 page can’t be found
HTTP ERROR 404

### Logged Error Messages

2020-10-08 13:10:39 | Error | Error downloading. indexer: monova path: https://monova.org/1D67A9D06BB193400D973DBD036C10A7309BB559 System.Exception: Download selector a#download-file didn't match    at Jackett.Common.Indexers.CardigannIndexer.Download(Uri link) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1818    at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in D:\a\1\s\src\Jackett.Server\Controllers\DownloadController.cs:line 56
-- | -- | --
2020-10-08 13:10:39 | Error | CardigannIndexer (monova): Download selector a#download-file didn't match: (A lot of HTML)

### Screenshots

![image](https://user-images.githubusercontent.com/45209462/95451778-8f475e80-0968-11eb-81f8-7a9a081e94d7.png)

**Comment by garfield69** [comment]
This is a problem.
The monova web site does not indicate whether  a torrent listed in its primary search results page is going to be missing the download link in the torrent's respective details page, so Jackett cannot filter out those broken torrent entries at the time it is generating the search results table.
So right now, you only find out if the download link is missing when you actually go to fetch the download.

We cant pro-actively examine the details page of every torrent listed in the search page, as that would cause up to 100 additional queries, which would probably be construed as a DDoS attack by the web site every time you do a search.

@ngosang  I don't know what do to about this... Monova is obviously going through a DMCA binge in order to avoid litigation, but rather than just dropping the torrent from its listing, it just posts the `torrent removed` message on the details page.

**Comment by ngosang** [comment]
@garfield69 Easy, the info_hash is in the URL, even if the torrent is removed. We should generate the magnet from the details page link.
* https://monova.org/1D67A9D06BB193400D973DBD036C10A7309BB559

**Comment by garfield69** [comment]
Ah, good spotting.
I'll code that solution.

**Comment by garfield69** [comment]
Jackett 0.16.1664
