### ISSUE TITLE
[gktorrent] Cannot get results - html parse error

### ISSUE THREAD

**Issue by neo62248** [Jackett/Jackett#9877]
### Environment

**OS**: Synology

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: last stable

**Last Working Jackett Version**: last stable

**Are you using a proxy or VPN?** [yes/no] no

### Description

Search with provider : GKTORRENT
No result is shown.

### Logged Error Messages

[gktorrent_log.txt](https://github.com/Jackett/Jackett/files/5396434/gktorrent_log.txt)
Excerpt of my jackett logs. Showing "Download selector a[href*="{{ .Config.downloadlink }}"] didn't match"

**Comment by garfield69** [comment]
**last stable** is really not very useful ;-( 
Please access your browser Jackett dashboard and scroll to the bottom and provide the version.
If you are not on 0.16.1307 or better then the issue is likely that you are using an out of date indexer, which had DL fixed 26 days ago, so upgrade.
Current latest version at the time of this post is 0.16.1771. 
The indexer is working for me so if after upgrading you still have an issue let us know.

**Comment by neo62248** [comment]
My Jackett Version is 0.16.1771.0. 

Sorry for my mistake, I don't have problem with fetching results. The links to download torrents (on each result line) does not seems to works and that's what the log I copied explains (I mean).

**Comment by garfield69** [comment]
ok, lets try this.
access your dashboard and edit the gktorrent config.
on the Download link pulldown, select the alternate option and click okay.
then edit again and select the original download link again and click okay.
then check if it working now.

**Comment by neo62248** [comment]
Ok, it is working now. It is a good tip that i'll adopt for others providers if i get this problem again. 

Thanks
