### ISSUE TITLE
[REQ]ggbases.com

### ISSUE THREAD

**Issue by berat1397** [Jackett/Jackett#9967]
Public ~~mix anime(tv-seriers,movie,game,manga,+18) content share~~ Japanese galgame (a subset of Bishōjo games)  torrent site.

Link: https://www.ggbases.com/
Seach engine and magnets torrents working.
[edit] this is not a movie and tv site, but a game site specialising in Japanese galgame

**Comment by garfield69** [comment]
both the magnet and .torrent links are not direct download links, but links to a secondary page which then provides the relevant magnet or .torrent file.
this will need a C# indexer.

**Comment by garfield69** [comment]
with the addition of usebeforeresponse to the download block introduced by 7235638310c6e3f8bec6acf54a4cf39ac3f8d9f3 on  6 Oct 2021 it may be that this site can now be processed with yaml. I'll take a look.

**Comment by garfield69** [comment]
Nah. its all changed since the last time we looked at this.
 the download page is all javascript with a ajax post to build the magnet hash so that `magnet.so?downid=e6d08895-843d-4dda-8a07-b2e282a5af1b&json=1&id=111576` becomes 'magnet:?xt=urn:btih:fe0d64f92fb2b9c960a947d79e497431b90dc1b3' and I cant figure out how to code the yaml download block for this.
back on the c# queue.

**Comment by garfield69** [comment]
closing as not suitable and stale.
