### ISSUE TITLE
[yggtorrent] Login failed: No form found on https://ww3.yggtorrent.si/ using form selector 

### ISSUE THREAD

**Issue by 3th3r** [Jackett/Jackett#9975]
**Didn't find any recent bug for yggtorrent, but if I've theirs already a ticket openned feel free to delete this one.

### Environment

CentOS 8

Mono Version: Unknown
NEt version: Unkown

Jackett Version: 0.16.1896.0

Jackett Version: 0.16.1896.0

No VPN

### Description

trackers; yggtorrent not working, again.
Login impossible, 'form page not found'

jackett work fine with others trackers, yggtorrent worked fine until a few days ago.
Certainly an update on their side.

### Logged Error Messages

 An error occurred while updating this indexer
Login failed: No form found on https://ww3.yggtorrent.si/ using form selector #user-login

**Comment by r33int** [comment]
Can confirm, +1

**Comment by ChrysMacZ** [comment]
Hi, confirm too, doesn't work anymore +1

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/9960#issuecomment-716090147

**Comment by garfield69** [comment]
With Jackett 0.16.1922 you should be able to make use of the YGGTorrent indexer again ... until the next DDoS event.

**Comment by ddamien53** [comment]
for my part it does not work

**Comment by garfield69** [comment]
@ddamien53 
The YGGTorrent indexer is working for me so the issue is likely at your end
1. upgrade to Jackett 0.16.1922 to pick up the fix for handling 307-temp-redirection error
2. access the Jackett dashboard and edit the YGGTorrent config
3. set the **Site Link** to `https://www.yggtorrent.si/`
4. set the **Search Link** to `www2.yggtorrent.si`
5. click **OKAY**

if you get an error, click **CLOSE** and try again, it should save again.

**Comment by 3th3r** [comment]
The 0.16.1922.0 works fine for me to.

Thanks guy's that was fast !
